### ISSUE TITLE
0.6.0 break Nextcloud 15.0.7 when fulltextsearch is enabled

### ISSUE THREAD

**Issue by reinerj** [nextcloud/deck#1004]
**Describe the bug**
After the update was installed on a 15.0.7 Nextcloud broke complete. No option to see any files, the apps or any other unction 

**To Reproduce**
Install 0.6.0 on 15.0.7

**Client details:**
 - OS: MacOS
 - Browser Safari, Firefox, Iridium 

**Operating system**:
Docker Image

**Web server:**

See the official Docker image

**Database:**
MySQL

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
15.0.7

When we delete the app Nextcloud work again

**Comment by adietz00** [comment]
Seconded; this happened to me as soon as I applied the latest update today. Keeping it disabled for now.

**Comment by metsuke0** [comment]
Maybe I will open my own topic, but I also am having issues with this release.  My whole Nextcloud instance is not broken like the OP, but the app itself is broken:

`{"Exception":"Error","Message":"Class 'OCA\\Deck\\Middleware\\SharingMiddleware' not found","Code":0,"Trace":[{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":118,"function":"OCA\\Deck\\AppInfo\\{closure}","class":"OCA\\Deck\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/usr\/local\/www\/nextcloud\/lib\/private\/AppFramework\/Depend`

**Comment by plinss** [comment]
I have a similar issue, but it appears to be an incompatibility between deck and other apps, in my case, fulltextsearch. See https://github.com/nextcloud/fulltextsearch/issues/487 for my crash log.

Disabling either deck or fulltextsearch clears the error for me.

Is deck possibly monkeypatching something in nextcloud that other apps rely on?

**Comment by juliushaertl** [comment]
cc @daita

**Comment by juliushaertl** [comment]
Seems to be an issue in fulltextsearch. Possible fix is in https://github.com/nextcloud/fulltextsearch/pull/488

**Comment by emansije** [comment]
> Maybe I will open my own topic, but I also am having issues with this release. My whole Nextcloud instance is not broken like the OP, but the app itself is broken:

I have the same problem. I don't have fulltextsearch installed, but Deck stopped working after the upgrade to 0.6.0, while Nextcloud itself is still working fine.

**Comment by juliushaertl** [comment]
> I have the same problem. I don't have fulltextsearch installed, but Deck stopped working after the upgrade to 0.6.0, while Nextcloud itself is still working fine.

Please open a separate issue for that and provide a filled out issue template with relevant logs/errors.

**Comment by juliushaertl** [comment]
Fix is available with fulltextsearch 1.2.6 and 1.3.1
