### ISSUE TITLE
Deck 0.6.0 is broken (Error: Class 'OCA\Deck\Middleware\SharingMiddleware' not found)

### ISSUE THREAD

**Issue by cddf** [nextcloud/deck#1006]
### Steps to reproduce
1. Go to 'Deck'
2. See the internal server error. Other pages are still working.

### Expected behaviour
Deck should open.

### Actual behaviour
After upgrading to 0.6.0 the Deck app can not be opened, it raises an internal server error.

## Server configuration detail

**Operating system:** Linux 4.19.0-0.bpo.4-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.25

**PHP version:** 

7.2.17
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, intl, json, ldap, mbstring, pcntl, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 15.0.7 - 15.0.7.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 15.0.5 I think

**Where did you install Nextcloud from:** snap

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - apporder: 0.6.0
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.1
 - dav: 1.8.1
 - deck: 0.6.0
 - end_to_end_encryption: 1.1.0
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.4.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - impersonate: 1.2.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - music: 0.9.4
 - notes: 2.6.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - provisioning_api: 1.5.0
 - quota_warning: 1.4.0
 - registration: 0.4.6
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - spreed: 5.0.3
 - systemtags: 1.5.0
 - tasks: 0.9.8
 - twofactor_backupcodes: 1.4.1
 - workflowengine: 1.5.0
Disabled:
 - admin_audit
 - announcementcenter
 - dashboard
 - encryption
 - files_fulltextsearch
 - fulltextsearch
 - fulltextsearch_elasticsearch
 - nextcloud_announcements
 - support
 - survey_client
 - theming
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        removed
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "15.0.7.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "overwriteprotocol": "https",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "overwrite.cli.url": "https:\/\/nuc",
    "loglevel": 2,
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** another nextcloud

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
nothing
```
</details>

<details><summary>Nextcloud log</summary>

```
[index] Error: Error: Class 'OCA\Deck\Middleware\SharingMiddleware' not found at <<closure>>

 0. /snap/nextcloud/12753/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\Deck\AppInfo\{closure}("*** sensitive parameters replaced ***")
 1. /snap/nextcloud/12753/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php line 298
    offsetGet("SharingMiddleware")
 2. /snap/nextcloud/12753/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OC\AppFramework\DependencyInjection\{closure}("*** sensitive parameters replaced ***")
 3. /snap/nextcloud/12753/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php line 166
    offsetGet("MiddlewareDispatcher")
 4. /snap/nextcloud/12753/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OC\AppFramework\DependencyInjection\{closure}("*** sensitive parameters replaced ***")
 5. /snap/nextcloud/12753/htdocs/lib/private/AppFramework/App.php line 110
    offsetGet("Dispatcher")
 6. /snap/nextcloud/12753/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OCA\\Deck\\Controller\\PageController", "index", "*** sensitive parameter replaced ***", {_route: "deck.page.index"})
 7. <<closure>>
    __invoke({_route: "deck.page.index"})
 8. /snap/nextcloud/12753/htdocs/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "deck.page.index"})
 9. /snap/nextcloud/12753/htdocs/lib/base.php line 987
    match("/apps/deck/")
10. /snap/nextcloud/12753/htdocs/index.php line 42
    handleRequest()

GET /index.php/apps/deck/
from 134.100.106.101 at 2019-04-24T15:27:19+00:00
```
</details>

<details><summary>Browser log</summary>

```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). deck:1:1
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
ReferenceError: oc_appconfig is not defined[Weitere Informationen] merged-share-backend.js:24:4
    <anonym> /index.php/js/core/merged-share-backend.js?v=624d4502:24
    <anonym> /index.php/js/core/merged-share-backend.js?v=624d4502:13
```
</details>

**Comment by juliushaertl** [comment]
Possible fix is in https://github.com/nextcloud/deck/pull/1011

**Comment by kostasy** [comment]
Hi, I am new here, but I have the same problem. How should I fix it or when will the bug fix release?


"Error: Class 'OCA\Deck\Middleware\SharingMiddleware' not found_

    /snap/nextcloud/12753/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php - line 118:

    OCA\Deck\AppInfo\Application->OCA\Deck\AppInfo\{closure}("*** sensiti ... *")

    /snap/nextcloud/12753/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 298:

    Pimple\Container->offsetGet("SharingMiddleware")

    /snap/nextcloud/12753/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php - line 118:

    OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}("*** sensiti ... *")

    /snap/nextcloud/12753/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 166:

    Pimple\Container->offsetGet("MiddlewareDispatcher")

    /snap/nextcloud/12753/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php - line 118:

    OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}("*** sensiti ... *")

    /snap/nextcloud/12753/htdocs/lib/private/AppFramework/App.php - line 110:

    Pimple\Container->offsetGet("Dispatcher")

    /snap/nextcloud/12753/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Deck\\ ... r", "index", "*** sensiti ... *", { _route: "deck.page.index"})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "deck.page.index"})

    /snap/nextcloud/12753/htdocs/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "deck.page.index"})

    /snap/nextcloud/12753/htdocs/lib/base.php - line 987:

    OC\Route\Router->match("/apps/deck/")

    /snap/nextcloud/12753/htdocs/index.php - line 42:

    OC::handleRequest()"

**Comment by juliushaertl** [comment]
I will prepare another release over the weekend. In the meantime you can apply the changes from https://github.com/nextcloud/deck/pull/1011/files manually. You just need to remove the line `use OCA\Deck\Middleware\SharingMiddleware;` from lib/AppInfo/Application.php in the deck app directory.

**Comment by cddf** [comment]
Thank you for your fast response.
> You just need to remove the line `use OCA\Deck\Middleware\SharingMiddleware;` from lib/AppInfo/Application.php in the deck app directory.

I tried that way, but I still get the same error.

**Comment by juliushaertl** [comment]
Do you have opcache enabled? In that case restart your webserver/php-fpm service?

**Comment by cddf** [comment]
Good point :+1: 
It's solved
