### ISSUE TITLE
Any chance to get this working on ownCloud?

### ISSUE THREAD

**Issue by vollknorke1337** [nextcloud/deck#1008]
**Is your feature request related to a problem? Please describe.**
No problem, only a request.

**Describe the solution you'd like**
I went from Nextcloud to ownCoud and missing Decks. Would love to install Decks in ownCloud.

**Describe alternatives you've considered**
"Tasks" app doesn't fit. 

**Additional context**
none

**Comment by juliushaertl** [comment]
This app is Nextcloud only. :wink:
