### ISSUE TITLE
board.sidebarView: "Collections" is not translated

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#1009]
**Describe the bug**
"Collections" is not translated

**To Reproduce**
1. change the language in NC from English to another language
2. Open board.sidebarView

 "Collections" is not translated

**Expected behavior**
 "Collections" is translated

**tested Version**
Deck 0.6.0
NC 16, NC 15

**Screenshot (NC15)**
![Screenshot_2019-04-25 Persönlich Deck - Nextcloud(1)](https://user-images.githubusercontent.com/34692335/56714578-84c5e480-6735-11e9-9148-83429daa4a39.png)

**Comment by juliushaertl** [comment]
Ah we actually shouldn't show that on NC15 and collections is the old term. Thanks for pointing out, translations for that should come from the server anyway.

**Comment by cloud2018** [comment]
Here is no p($l->t(
https://github.com/nextcloud/deck/blob/ca5a1bcddaa75a6fbe42ddb90aa1c9ff7fa78399/templates/part.board.sidebarView.php#L93
