### ISSUE TITLE
Current master branch doesn't work

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#101]
Current master branch throws lot of errors:
![screenshot_20170429_203448](https://cloud.githubusercontent.com/assets/16517095/25557888/61c3947e-2d1b-11e7-828e-f48c47d4806b.png)

**Comment by juliushaertl** [comment]
@artemanufrij I cannot reprocude this.

Can you check the following:
- After running make install-deps those files in js/vendor/* should exist
- Those should also be in the release tar archive
- make appstore should merge all app javascript files into js/public/app.js Does this file exist in your tar archive?

**Comment by artemanufrij** [comment]
@juliushaertl 
1. fresh clone of master.git
2. `make install-deps` -> `js/vendor` doesn't exits
3. `js/public/app.js` exists

![screenshot_20170430_121627](https://cloud.githubusercontent.com/assets/16517095/25563580/10fb6448-2d9f-11e7-9e0e-3a95f4789f58.png)

**Comment by juliushaertl** [comment]
Fixed with #103
