### ISSUE TITLE
(old/pre-0.6.0) boards not shown

### ISSUE THREAD

**Issue by blizzz** [nextcloud/deck#1012]
### Steps to reproduce
1. Have a couple of boards with cards, normal usage
2. Upgrade to deck 0.6 (and Nc 16)
3. Go to the Deck app

### Expected behaviour
All boards are shown

### Actual behaviour
No board is shown. But they are not deleted either. With the links from activities, they can be opened, for example. 

A user who has not used Deck before does not have these problems. 

## Server configuration detail

**Operating system:** Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.25

**PHP version:** 

7.2.17-0ubuntu0.18.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, iconv, igbinary, imagick, imap, intl, json, exif, mysqli, pdo_mysql, Phar, posix, pspell, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 16.0.0 - 16.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** 

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - audioplayer: 2.7.0
 - bookmarks: 0.17.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.1
 - dav: 1.9.2
 - deck: 0.6.0
 - drawio: 0.9.2
 - dropit: 0.2.1
 - event_update_notification: 0.3.4
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_markdown: 2.0.6
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - groupfolders: 3.0.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.14.0
 - news: 13.1.6
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - qownnotesapi: 18.11.0
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - richdocuments: 3.2.4
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - socialsharing_diaspora: 1.0.4
 - socialsharing_email: 1.0.5
 - socialsharing_facebook: 1.0.4
 - spreed: 6.0.0-rc.2
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.9.8
 - telephoneprovider: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 2.1.2
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - apporder
 - defaultlinkopen
 - encryption
 - files_external
 - gallery
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.0.9",
    "installedat": "1326327271.69",
    "lastupdatedat": "1338667774.87",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "maintenance": false,
    "loglevel": 2,
    "trusted_domains": [
        "o.schiwon.me",
        "ovin.schiwon.me"
    ],
    "secret": "***REMOVED SENSITIVE VALUE***",
    "share_folder": "\/Shared",
    "appstoreenabled": true,
    "trashbin_retention_obligation": "auto",
    "appstore.experimental.enabled": true,
    "updater.release.channel": "beta",
    "updater.server.url": "https:\/\/updates.nextcloud.com\/internal_updater_server\/",
    "mysql.utf8mb4": true,
    "debug": false,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "overwrite.cli.url": "https:\/\/ovin.schiwon.me",
    "htaccess.RewriteBase": "\/",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "PLAIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "app_install_overwrite": [
        "apporder",
        "audioplayer",
        "deck",
        "drawio",
        "qownnotesapi",
        "tasks"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Operating system:** Antergos

## Logs

<details><summary>Web server error log</summary>

```
nothing related
```
</details>

<details><summary>Nextcloud log</summary>

```
nothing related
```
</details>

<details><summary>Browser log</summary>

Does not seem to be a problem, as it happens for users where boards are either shown or not.

Both users:

Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). deck.js:30678:6

"New" user:

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). deck:39:41579
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). deck:32654:9

​
</details>

**Comment by juliushaertl** [comment]
> Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). deck.js:30678:6

That error seems to originate from angular checking the CSP, so it is probably unrelated. We should actually set the csp rules in our angular app to avoid those logs

deck.js:30678
```
  function noUnsafeEval() {
    try {
      // eslint-disable-next-line no-new, no-new-func
      new Function('');
      return false;
    } catch (e) {
      return true;
    }
  }
```

@blizzz Are the boards properly returned by the API endpoint?
![image](https://user-images.githubusercontent.com/3404133/56730866-43dfc700-6759-11e9-91ac-a1991c4d629f.png)

**Comment by blizzz** [comment]
> @blizzz Are the boards properly returned by the API endpoint?

Nope, just an empty `[]`

**Comment by blizzz** [comment]
When I look at the boards table, what the missing boards have in common is that `last_modified` is set to 0.

**Comment by juliushaertl** [comment]
Ok, that might be the reason, since we added the last_modified date for the rest api, I'll have a look.
