### ISSUE TITLE
add an object to collection is not possible, after a tab in board-details-view has been clicked

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#1018]
**Describe the bug**
It is not possible to add an object to collection after a tab "Tags", "Deleted items" or "Timeline" has been clicked

**To Reproduce**
1. Open board details (-> tab "Sharing" is default) 
2. Add a board to collection
3. Click a tab ("Tags", "Deleted items" or "Timeline")
4. It is not possible to add another object to collection

**Expected behavior**
It should be possible to add an object to collection after a tab has been clicked

**Screenshots**
Without changing the tab, it's like expected:
![Screenshot_2019-04-27 board1 Deck - Nextcloud](https://user-images.githubusercontent.com/34692335/56847950-d8c1fc00-68e2-11e9-928b-b532d02c57d2.png)

After changing the tab and go back to tab "Sharing":
![Screenshot_2019-04-27 board1 Deck - Nextcloud(1)](https://user-images.githubusercontent.com/34692335/56847963-fbecab80-68e2-11e9-977f-c1c1cbe74ad3.png)
**Workaround**
Close board-detail-view and reopen board-detail-view

**Enviromnemt**
NC 16.0.0
Deck 0.6.1

**Comment by juliushaertl** [comment]
Should be fixed on master
