### ISSUE TITLE
change user rights

### ISSUE THREAD

**Issue by ApoRes1337** [nextcloud/deck#1024]
**Describe the bug**
When changing the rights of users, they are not accepted.

**To Reproduce**
1. Go to 'Deck'
2. Click on 'Board Details'
3. Add a Nextcloud User to the Deck
4. Open the Details again and change the rights
5. nothing happens

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/26686045/56907466-96e0b380-6aa4-11e9-8b8e-641d8cc492be.png)
![Screenshot_2](https://user-images.githubusercontent.com/26686045/56907467-97794a00-6aa4-11e9-97e2-0543b7d67d7c.png)

**Client details:**
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Operating system**: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64

**Web server:** nginx/1.15.12 (fpm-fcgi)

**Database:** mysql 10.3.14

**PHP version:** 7.3.4-1+0~20190412071350.37+stretch~1.gbpabc171
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 16.0.0 - 16.0.0.9 and 15.X.X

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-16.0.0.zip

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
Enabled:
  - activity: 2.9.1
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - deck: 0.6.1
  - encryption: 2.4.0
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - issuetemplate: 0.5.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - accessibility
  - admin_audit
  - federation
  - files_external
  - firstrunwizard
  - sharebymail
  - support
  - user_ldap

```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"vtATluI2FRBeC0zXIWpp","level":2,"time":"2019-04-29T14:58:57+00:00","remoteAddr":"213.229.25.142","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/dav\/files\/Cedric\/","message":"Login failed: 'cedric' (Remote IP: '213.229.25.142')","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.2git (Nextcloud)","version":"16.0.0.9"}
{"reqId":"6toWuWFJQwsDBYiGKJ9I","level":2,"time":"2019-04-29T14:59:12+00:00","remoteAddr":"5.28.108.214","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/dav\/files\/SkyfaR\/","message":"Login failed: 'SkyfaR' (Remote IP: '5.28.108.214')","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.1final (build 20181204) (Nextcloud)","version":"16.0.0.9"}
```

**Comment by ymybe** [comment]
I confirm the issue, with Deck 0.6.1 Nextcloud 16.0.0 on php7.3.4 mariadb 10.3.latest

**Comment by argotechnica** [comment]
Also experiencing this issue on Deck 0.6.1 / Nextcloud 16.0.0 / PHP 7.3.5 / MariaDB 10.3.14 / Nginx 1.14.0. The issue manifests as a ```405: Method Not Allowed``` on the PUT request for file "acl". The Referrer Policy mentioned is ```no-referrer-when-downgrade```. My nginx config has recommended settings per the documentation (https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html), namely:

```
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
    add_header Referrer-Policy no-referrer;
```

FWIW, by referencing https://github.com/nextcloud/deck/issues/29 I ended up confirming MariaDB settings here: https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by Peronia** [comment]
Thanks, fixed it for me too.
