### ISSUE TITLE
Unhandled expired CSRF token response

### ISSUE THREAD

**Issue by jirislav** [nextcloud/deck#1040]
When I open deck after some PC sleep, the CSRF token is expired. So when I prompt for task detail, it shows loading gif forever, while already received response to the XHR request with 412 HTTP status code and description of an expired CSRF token.

Similar behavior was reported in #633 , but it was closed with this comment:
> That is an issue with Nextcloud 13 since after some timeout the CSRF token is becoming invalid. There is nothing we can do about that in deck, but with Nextcloud 14 the token is updating in the background so the issue should be fixed there.

Apparently, Nextcloud 14 didn't solve this issue, so I suggest to simply reload the whole page when expired CSRF token error is returned, which solves both the issues (the mentioned one probably shouldn't be closed as it's not solved yet).

I'm using stable Nextcloud 15.0.7 and latest Deck 0.6.1.

**Comment by juliushaertl** [comment]
Hm yes, we don't update the token properly in deck yet:

https://github.com/nextcloud/deck/blob/e08c430422a408d72799db112bad4c5c234694b8/js/app/Config.js#L32

**Comment by juliushaertl** [comment]
Should be handled properly now in master with the usage of the `@nextcloud/axios` package.
