### ISSUE TITLE
Unable to set permissions

### ISSUE THREAD

**Issue by mikaeli** [nextcloud/deck#1041]
In deck version 0.6.1 with Nextcloud 16.0.0 it is not possible to grant additional permissions to other users.

If the user who created a deck/project shares it with other user and ticks permission to Manage or Share, the permission does not change. The tick is applied but the setting will not be saved.

There is following error on the console:

deck.js?v=86ad1f4f-17:42951 PUT https://cloud.********.***/apps/deck/boards/10/acl 405
(anonymous) @ deck.js?v=86ad1f4f-17:42951
sendReq @ deck.js?v=86ad1f4f-17:42677
serverRequest @ deck.js?v=86ad1f4f-17:42418
processQueue @ deck.js?v=86ad1f4f-17:47334
(anonymous) @ deck.js?v=86ad1f4f-17:47382
$digest @ deck.js?v=86ad1f4f-17:48501
$apply @ deck.js?v=86ad1f4f-17:48889
$$debounceViewValueCommit @ deck.js?v=86ad1f4f-17:60289
$setViewValue @ deck.js?v=86ad1f4f-17:60263
listener @ deck.js?v=86ad1f4f-17:56570
dispatch @ main.js?v=86ad1f4f-17:39
_.handle @ main.js?v=86ad1f4f-17:39

**Comment by mikaeli** [comment]
Sorry for noise. Just noticed this has already been dealt with.

**Comment by iamit** [comment]
I have the same problem in the latest version, so could you please add the link where "this has already been dealt wiht"? next cloud  16.0.0 , deck: 0.6.1

**Comment by mikaeli** [comment]
After submitting the issue, I noticed that there were already two duplicate reports #1024 and #1036.
Those had been fixed in #1026 and the fix will be included in next version, which hopefully gets published soon!

**Comment by iamit** [comment]
Thanks for the extra comment, had to search for ACL to find the other requests. We just upgraded to 0.6.2 and my issue is solved, thanks for the fix!
