### ISSUE TITLE
Board Permissions (edit, manage, share) of group not saved

### ISSUE THREAD

**Issue by iamit** [nextcloud/deck#1048]
I need to have a group (user group) only view access, so on share the board with a group, I deselect edit permission.

in debug mode, you see it does the request, but gets an error message 9and the premissions are not saved)

none of the other permissions are saved.

this is the response:
Request URL: https://my-domain/apps/deck/boards/4/acl
Request Method: PUT
Status Code: 405 Method Not Allowed

**Comment by juliushaertl** [comment]
Fixed in https://github.com/nextcloud/deck/pull/1026
