### ISSUE TITLE
Custom background

### ISSUE THREAD

**Issue by GallandJe** [nextcloud/deck#1051]
Hello,

I propose to implement a feature to let the user select a custom background image or color.
Because it's a litle bit too white ;)

Bests regards

**Comment by mdberryh** [comment]
I removed the addon for next cloud because I just couldn't see the card. Changing background would help, or make the card's border or even the card's color different than the background would be helpful. Another option would be if they set the card's title to a solid color.

**Comment by sunjam** [comment]
Setting custom backgrounds would be nice!  For now, you can also go to /settings/accessibility to use the new dark theme beta for Nextcloud at large.

**Comment by TobiasDev** [comment]
Not sure if this falls into the same, if not, let me know and I can add a new feature request. Would it be possible to add so we can color individual columns? 

That would make it a lot faster to focus on one column as I can tie the column to a color. 

Eg. something like this: 
![image](https://user-images.githubusercontent.com/5912371/58069893-4d612100-7b97-11e9-999b-e822460af50a.png)

**Comment by lightnin** [comment]
I'd like to reopen this one. For a lot of users with multiple boards, this helps provide quick visual orientation. And, you know, nice backgrounds are nice. :)

**Comment by fti7** [comment]
Yes please Reopen. Custom Backgrounds is a Must-Have :-) Especially if you use this Tool for Work and Private... you want a different visual look or you are getting crazy

**Comment by youtous** [comment]
The background feature is listed on the latest Deck Survey :)
https://cloud.nextcloud.com/apps/forms/nBkxsxa8nJdyPoZa

> The survey will be just a few minutes and mostly present you features and ask you to pick those most important to you.

**Comment by sunjam** [comment]
@youtous "There was an an Error sending" the survey.

**Comment by thefeiter** [comment]
I would also like to reopen, since this is a very useful feature, which users who previously worked with trello prefer having.
@GallandJe Are you able to reopen?

**Comment by GallandJe** [comment]
@thefeiter Unfortunately no... I can't reopen this request :-(
