### ISSUE TITLE
make error text of file upload translatable

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#1058]
**Describe the bug**
text of file upload error is not fully translated

**To Reproduce**
1. Choose German as language
2. Go to card details
3. Try to upload a large file
4. See error message
**Failed to upload** meine-Testdatei.png
Maximale Dateigröße von 2.00 MB überschritten

**Expected behavior**
error text is fully translated
or
there is a string "Failed to upload" on Transifex for translation

**Screenshots**
![Persönlich   Deck   Nextcloud(1)](https://user-images.githubusercontent.com/34692335/58077580-231a5e00-7bad-11e9-9e37-f5f790e40472.png)

**tested with**
Deck 0.6.2
NC 16.0.1
https://demo.nextcloud.com

**Comment by juliushaertl** [comment]
Fixed with the vue rewrite
