### ISSUE TITLE
Can´t add new cards from mobile (Fennec)

### ISSUE THREAD

**Issue by TobiasDev** [nextcloud/deck#1071]
**Describe the bug**
When I visit NextCloud Deck from my Android browser (Fennec and Bromite tested), there are times when it doesn´t  create new cards for me. 

**To Reproduce**
1. Go to NextCloud Deck in Bromite or Fennec
2. Add a new card
3. If it works try adding another
4. See that it will break at some point

**Expected behavior**
That I´m able to create new cards

**Screenshots**

**Client details:**
 - OS: Android - LineageOS 16.0, Android 9
 - Browser: Fennec and Bromite
 - Device: OnePlus 3t

I have the latest version of NextCloud Deck, I just double checked this.

**Comment by juliushaertl** [comment]
Any chance you could obtain the browser console logs with those browsers when the error is happening?
