### ISSUE TITLE
[UX] add button to confirm adding of item in a stack

### ISSUE THREAD

**Issue by BobyMCbobs** [nextcloud/deck#1072]
**Is your feature request related to a problem? Please describe.**
Some users are more mouse driven than keyboard driven, if there isn't a confirm button they will be unsure on what to do when adding new items to a stack.

**Describe the solution you'd like**
A button, to confirm the new item in the given stack, should be added inside the new item box similar to how it is when adding a new tag in Deck.

**Describe alternatives you've considered**
not applicable.

**Additional context**
nothing to add.

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master.

![image](https://user-images.githubusercontent.com/3404133/73119399-93118d00-3f61-11ea-817e-dbf88957b923.png)
