### ISSUE TITLE
delete a project

### ISSUE THREAD

**Issue by himbeere** [nextcloud/deck#108]
Deck 0.1.3

Hello Devs.

Maybe a stupid question but how do i delete a project? Can't find any button / setting for that.

thanks and cheers
t.

**Comment by artemanufrij** [comment]
@himbeere 

url/to/my/projectongithub/**settings**

**Comment by juliushaertl** [comment]
@himbeere I guess you mean inside the deck app. Just click the 3-dots menu and then the delete icon.

![2017-05-01-193002_246x65_scrot](https://cloud.githubusercontent.com/assets/3404133/25587501/a4f8a6f0-2ea4-11e7-9792-ea9ecd34a89e.png)

Be aware, that there is currently no confirmation/undo functionality. This is requested in #85

**Comment by himbeere** [comment]
Thanks @juliushaertl but that does not work here. I see the trash can too but when hitting the trash can nothing happens. Mouse over shows "Freigabe löschen" which means "cancel sharing this" or so I guess. 

My System: Apache2.4, PHP-7.1.4,Nextcloud 11.0.3

![img_20170501_202614](https://cloud.githubusercontent.com/assets/631865/25589659/b549da2a-2ead-11e7-94dd-7cd276212335.jpg)

**Comment by juliushaertl** [comment]
Ok thanks for reporting. Seems there is a bug caused by #43. The checks in https://github.com/nextcloud/deck/blob/master/templates/part.navigation.php#L16-L18 are not working correctly. I'll look into that tomorrow.

**Comment by juliushaertl** [comment]
Fixed with #113
