### ISSUE TITLE
Possible name and terminology change

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#1088]
We discussed in the past that our current naming might need revision.
It’s currently **Deck**, Board, Stack, Card (app name in bold).

Alternative ideas @juliushaertl and I had:
- **Boards**, Board, Stack, Card
- **Plans**, Plan, Stack, Card
- "Projects" is already taken by the Projects feature in core, so we can not use that.

Just researched how others call it:
- **Trello**, Board, List, Card
- **GitHub Projects**, Project, Column, Card
- **Wekan**, Board, List, Card
- **Asana**, Board, Column, Task
- **Monday.com Kanban**, Board, Column?, Pulse?
- This [blog post](https://zapier.com/blog/best-kanban-apps/) also says: Board, List, Card

So after that, it’s pretty clear that "Card" is the one thing almost everyone uses. Then "List" instead of "Stack/Column" seems to be good and more understandable. And "Board" is also basically standard.

That leaves the app name. So these are our options:
- **Nextcloud Deck**, Board, List, Card
- **Nextcloud Boards**, Board, List, Card
- **Nextcloud Plan/Plans**, Board, List, Card
- Or another app name idea?

What do you think @nextcloud/designers @nextcloud/deck?

**Comment by skjnldsv** [comment]
I like Board :)

**Comment by jancborchardt** [comment]
My problem with "Board" or "Boards" is that for someone unfamiliar with Kanban it is absolutely confusing. Hell, I’m thinking of snowboards, skateboards and surfboards. ;)

To that extent, it is not much better than the current "Deck".

"Nextcloud Plan" seems to be the clearest, both for newcomers and people who know about it. Like it comes from "project planning", or you could even say "do you have it on the Plan?" ;)

**Comment by putt1ck** [comment]
Deck is fine. Trello has done very well with a similar functionality ($425m well) while being called Trello. Board, List, Card works, with List maybe better than Stack. 

Given the uses you can come up with for such a system, we probably can explain why Trello isn't "Plano" or "Projecto". It's fairly clear why it's not "Boardo" on many levels... Given that people already use Deck for more than planning and more than projects, Deck is likely an optimal name.

**Comment by jancborchardt** [comment]
I’m also fine doing it step by step and sticking with Deck for now. :) It is reasonably established, at least in the Nextcloud bubble.

Then let’s go with changing the "Stack" to "List" and we’re done? @juliushaertl

**Comment by juliushaertl** [comment]
@jancborchardt Thanks for summarizing what we discussed :+1: 

I also think that renaming stack to list is the most important one. After thinking about it, I also feel that renaming the app is probably going to be hard, as we also have the android app named Deck now. Maybe it would already help if we come up with a better short description of the app. In the app store for example you only see:
![image](https://user-images.githubusercontent.com/3404133/59905991-da520100-9407-11e9-85be-e6cdb589ee33.png)

Which basically requires you to know what kanban is. Maybe we should go with something more descriptive similar to:

- Organize your projects
- Project organization for you and your team

Maybe @jospoortvliet also has a nice idea here?

**Comment by jancborchardt** [comment]
- Simple project organization & collaboration
- Personal planning and team project organization

Also like your 2nd proposal @juliushaertl. Just pick one and we go with that. :)

**Comment by putt1ck** [comment]
I'd add something about supporting other workflows as we use it for more than projects - it makes for an effective trouble ticket system, for example.

**Comment by jancborchardt** [comment]
> I'd add something about supporting other workflows as we use it for more than projects - it makes for an effective trouble ticket system, for example.

This is for a **short** description, so we need to be brief. :)

**Comment by Valdnet** [comment]
@juliushaertl, @jancborchardt In my opinion the name of the app should contain the name "Board" and should be translated. It looks strange how other app names have been translated into their native language and "Deck" doesn't. See for yourself:

![obraz](https://user-images.githubusercontent.com/47037905/73380951-339ae080-42c5-11ea-9c41-b744403cc3aa.png)

**Comment by stefan-niedermann** [comment]
>  I also feel that renaming the app is probably going to be hard, as we also have the android app named Deck now. 

@juliushaertl: No problem from our side - We can adjust everything on the surface (except the application id in the Play Store & F-Droid which are rarely visible anywhere).

But i'm fine with keeping 'Deck' since it's already known by many people.

Another question:

Do you call it `Label` or `Tag`? The latest version of your branch has inconsistent names, so i am not sure for what you will go (See `Tags` in tab title vs `+ Add a new label` below the labels):

![grafik](https://user-images.githubusercontent.com/4741199/76880645-40c15e00-6878-11ea-91db-88454c10ca21.png)

**Comment by juliushaertl** [comment]
Ah yes, i think we mixed that up since the code of course still uses labels in some parts. We went for **Tag** as the wording for this in https://github.com/nextcloud/deck/pull/305
