### ISSUE TITLE
Exporting and importing boards (as JSON or something)

### ISSUE THREAD

**Issue by BobyMCbobs** [nextcloud/deck#1089]
**Is your feature request related to a problem? Please describe.**
Migrating deck boards across instances isn't possible.
There are cases where a deck board should be migrated but not the Nextcloud instance, this feature is super important for that.

**Describe the solution you'd like**
The ability to export and import a board as JSON.

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by juliushaertl** [comment]
Duplicate of #87
