### ISSUE TITLE
Deleted tasks with due date still appear as notification

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/deck#1094]
Similar to https://github.com/nextcloud/deck/issues/768 I get notifications on deleted (not archived as in https://github.com/nextcloud/deck/issues/768) tasks, when they were deleted before the due date.

https://github.com/nextcloud/deck/issues/768 is marked as solved, it seems this problem could be related but not identical.

**Comment by 0xbb** [comment]
I can confirm this issue

**Comment by rabesocke** [comment]
I can confirm this issue in that way, that a notification is still present if the due date is cleared / deleted in the card while the card stays active (not deleted or archived).
