### ISSUE TITLE
timeline is broken not loading

### ISSUE THREAD

**Issue by SnackyWell** [nextcloud/deck#1097]
our timeline is broken and not loading comments and actions.

[Screen](https://i.imgur.com/wR6w4hn.png)

that is showen in that console
deck.js?v=148eec79-25:42964 GET https://next.***/ocs/v2.php/apps/activity/api/v2/activity/filter?format=json&object_type=deck_card&object_id=83&limit=50&since=-1&sort=asc 404 (Not Found)
deck.js?v=148eec79-25:42964 GET https://next.***/ocs/v2.php/apps/activity/api/v2/activity/filter?format=json&object_type=deck_card&object_id=83&limit=50&since=0 404 (Not Found)

**Comment by juliushaertl** [comment]
Thanks for your report, please fill out the complete issue template. Especially the Nextcloud log files would also be interesting.

**Comment by stevecopeza** [comment]
We're experiencing the same problem.
The content (comments and actions) are visible to me as the administrator, but not to other people on the board.

![Design___Deck_-_Nextcloud_and_Passwords](https://user-images.githubusercontent.com/19606448/60172151-5daa9280-980c-11e9-90b5-74fb0e1bd9d8.jpg)
![Pasted_Image_2019_06_26__12_17](https://user-images.githubusercontent.com/19606448/60172190-79ae3400-980c-11e9-8ef0-170a5578c6e4.jpg)

**Comment by juliushaertl** [comment]
Should be fixed with 0.6.3

**Comment by juliushaertl** [comment]
Note that for activity entries you still need to have the stream checkbox in the activity settings enabled for deck activities.
