### ISSUE TITLE
Option to show both archived and active cards

### ISSUE THREAD

**Issue by dadosch** [nextcloud/deck#1098]
**Is your feature request related to a problem? Please describe.**
A option which shows both, active and archived, cards would be good because it gives an overview what you have already achieved and what still needs to be done 

**Describe the solution you'd like**
archived cards could be shown greyed out, the others normal.

Currently, you can switch only between archived or active cards, there is no possibility to show both

**Comment by juliushaertl** [comment]
I added this as an addition to #414
