### ISSUE TITLE
Boards are not deleted

### ISSUE THREAD

**Issue by nul7** [nextcloud/deck#1101]
First off, thank you for your work.

**Describe the bug**
Deleted projects never go away. They just become disabled with a button to undelete and a note that they will be removed when the next cron job runs. I have a cron job set to run every 5 minutes (verified by the status in Basic Settings). Same behavior is observed manually running the Nextcloud cron.php. No logs are created. I'm not sure how to test whether the cron job is actually doing anything other than updating the "Last job run ..." timer. Any ideas?

**Client details:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.100
 - Device: Desktop

Server configuration detail
Operating system: Linux 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64

Webserver: Apache/2.4.29 (Ubuntu) (apache2handler)

Database: mysql 10.1.40

PHP version:

7.2.19-0ubuntu0.18.04.1 Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, mapi, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 16.0.1 - 16.0.1.1

Updated from an older Nextcloud/ownCloud or fresh install: Fresh install

List of activated apps
Enabled:
 - activity: 2.9.1
 - announcementcenter: 3.5.1
 - bruteforcesettings: 1.3.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - dav: 1.9.2
 - deck: 0.6.2
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_antivirus: 2.1.1
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trackdownloads: 1.5.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - gallery: 18.3.0
 - groupfolders: 4.0.3
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - onlyoffice: 2.1.10
 - password_policy: 1.6.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - socialsharing_email: 1.0.5
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - unsplash: 1.1.3
 - updatenotification: 1.6.0
 - user_ldap: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - accessibility
 - admin_audit
 - encryption
 - files_external
 - firstrunwizard
 - nextcloud_announcements
 - support
 - survey_client

**Comment by juliushaertl** [comment]
Can you check the content of your oc_jobs table with the following query:
```
select * from oc_jobs WHERE class LIKE '%Deck%'
```

This should contain timestamps for the last run time

**Comment by ghosttable** [comment]
Hi, i noticed on Nectcloud with Ajax instead of cron, which i have to use as Setting, the Board, created as normal user isnt deleted too.

**Comment by bkhl** [comment]
I seem to have the same issue with Nextcloud 16.0.5 and Deck 0.6.6 

Here's what I get from that SQL query:

```
MySQL [bkhl_cloud]> select * from oc_jobs WHERE class LIKE '%Deck%'
    -> ;
+----+---------------------------------------+----------+------------+--------------+-------------+--------------------+
| id | class                                 | argument | last_run   | last_checked | reserved_at | execution_duration |
+----+---------------------------------------+----------+------------+--------------+-------------+--------------------+
| 48 | OCA\Deck\Cron\DeleteCron              | null     | 1546511102 |   1569686433 |           0 |                  0 |
| 49 | OCA\Deck\Cron\ScheduledNotifications  | null     | 1546511102 |   1569686433 |           0 |                  0 |
| 50 | OCA\Deck\Cron\CardDescriptionActivity | null     | 1546511102 |   1569686433 |           0 |                  0 |
+----+---------------------------------------+----------+------------+--------------+-------------+--------------------+
3 rows in set (0.00 sec)
```
