### ISSUE TITLE
Header ordering is not correct

### ISSUE THREAD

**Issue by towo** [nextcloud/deck#1102]
**Describe the bug**

When viewing a board, the header structure is as follows:

* Application name
  * nothing
    * Column name
      * Task name
      * Task name
   * [...]
    * Open task name

Missing the 2nd level shouldn't be a thing.
(Yes, I know, this is minor… but.)

**To Reproduce**

Normal usage.

**Expected behavior**

Header level "2" as the top level of the application-specific content.

**Screenshots**

![Screenshot from 2019-06-22 19-48-16](https://user-images.githubusercontent.com/271819/59967166-ba652f00-9526-11e9-9462-ef0b1fecf26d.png)

As presented with the [headingsMap](https://chrome.google.com/webstore/detail/headingsmap/flbjommegcjonpdmenkdiocclhjacmbi) Chrome extension.

**Client details:**
 - OS: Linux
 - Browser Chrome
 - Version NextCloud 15.0.8, Chrome 75
 - Device: Desktop

[Cut irrelephant questions]

**Comment by juliushaertl** [comment]
Closing as this was fixed in the vue branch and is now merged to master
