### ISSUE TITLE
Cards not delete when sthack delete

### ISSUE THREAD

**Issue by Nzt110000** [nextcloud/deck#1105]
**Describe the bug**
When we delete a sthack the cards are not positioned to be deleted or deleted in the database. The cards are therefore orphan.

**To Reproduce**
1. Create a deck
2. Create a sthack
3. Create a cards
4. Delete Sthack without archive or delete the cards.
5. Watch in database the table oc_deck_cards, nothing change for the cards. But the cards is not visible in the deck interface.

**Expected behavior**
Is it possible to set the cards also deleted or archived in the database when a deck or a sthack ar archived or deleted ?

**Comment by juliushaertl** [comment]
Deleted items will be cleaned up later with a cronjob, so they can be restored at least 5 minutes after their deletion.
