### ISSUE TITLE
REST API Update Board ACL Method Not Found

### ISSUE THREAD

**Issue by Llewxamris** [nextcloud/deck#1106]
**Describe the bug**
According to the REST API documentation, PUTting on the endpoint `/boards/{boardId}/acl/{aclId}` should result in an attempted update of the ACL with the associated ACL ID.
Instead, I receive a `405 Method Not Found` error. 

**To Reproduce**
1. `curl -X PUT ".../api/v1.0/boards/{boardId}/acl/{aclId} -H "Content-Type: application/json" -H "OCS-APIRequest: true" -d '{"permissionEdit": true, "persmissionShare": true, "permissionManage": true }'`

**Expected behavior**
Receive either:
- a `200 OK` and all permissions on that ACL rule are set to true
- a `400 Bad Request` indicating a parameter is missing
- a `403 Permission Denied` indicating I do not have access to that entity

**Client details:**
 Curl 7.64.0

**Operating system**:
Ubuntu 18.04.2

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.8

**Where did you install Nextcloud from:**
Installed via the Nextcloud Snap package

```
No errors have been found.
```

**List of activated apps:**
Defaults + Deck

**Comment by Llewxamris** [comment]
Looking at `routes.php`, I see [a route that does not include the ACL ID in the path](https://github.com/nextcloud/deck/blob/37a2858d5f1cd61c7a92eb47ad7578cdd8753cb4/appinfo/routes.php#L38). Hitting that endpoint returns back a `400 Bad Request` with the body `{"status": 400, "message": "id must be a number"}`. Including an `id` field set to the ACL ID in the payload returns the same response.

**Comment by juliushaertl** [comment]
Thanks, the parameter was indeed missing in the routes.php
