### ISSUE TITLE
Red line around the field "add new stack" after removing text

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/deck#111]
### Steps to reproduce
1.Open Deck
2.Open a board
3.Type something inside the _Add new stack_ field
4. Remove the text from the _Add new stack_ field
5. Click outside the field

### Expected behaviour
The field is empty

### Actual behaviour
The field is empty with a red line around it

**Comment by juliushaertl** [comment]
@armaccloud Thanks for reporting. Looks like this is an issue in firefox only, caused by the required attribute.

**Comment by juliushaertl** [comment]
Fixed with #114
