### ISSUE TITLE
Comments in timeline not showing (again)

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/deck#1112]
After clicking on a card, and selecting the Timeline Tab, i start writing a new comment.
As soon as as i click the arrow to post/save the comment, what i wrote vanishes but does not show as a comment.

What i already tried to solve the problem:

disabled enabled the app
removed the app and installed it again
let occ repair the database
checked the file permissions of the app
tried different browsers (firefox, chrome, vivaldi)

My system:
Debian 10
Nextcloud 16
Apache 2.4.38
PHP 7.3

Activity is not enabled.

**Comment by juliushaertl** [comment]
Unfortunately the activity app is currently required for comments to work. This is something we need to fix in the future, but most likely after #355

**Comment by rasos** [comment]
We are facing the same issue on NC 16 with Deck 0.6.6 and Activity 2.9.1  enabled: comments are not shown, they also do not show up in the activity stream.

**Comment by scbrouwer** [comment]
I am a new user but I still see the problem occurs. I added some comments in timeline, but it's gone and nothing to see

**Comment by catgento** [comment]
Hi, same issue here.

**Comment by juliushaertl** [comment]
Let's close this then, since this will be fixed with 1.0
