### ISSUE TITLE
Errors with card attachments

### ISSUE THREAD

**Issue by rev138** [nextcloud/deck#1113]
**Describe the bug**
When a user uploads an attachment to a card an "Failed to upload" error is displayed. However, if they refresh the page, the attachment exists and can be downloaded. Attempts to delete the attachment fail (no user feedback, but the console logs an error).

**To Reproduce**
1. Go to the Deck app
2. Click on a card
3. In the details pane, go to the Attachments tab
4. Upload an attachment
5. Refresh
6. Attempt to delete the attachment

**Expected behavior**
Attachments are uploaded and deleted without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/1538633/60539452-c1d0c900-9cda-11e9-94af-6fa7edf7fcb4.png)

**Client details:**
 - OS: Linux
 - Browser: Firefox
 - Version: 67
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 16.0.1

**Where did you install Nextcloud from:** Tarball

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.0
  - circles: 0.17.4
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - data_request: 1.3.0
  - dav: 1.9.2
  - deck: 0.6.4
  - drop_account: 0.1.0
  - encryption: 2.4.0
  - event_update_notification: 0.3.4
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_antivirus: 2.1.1
  - files_automatedtagging: 1.6.0
  - files_pdfviewer: 1.5.0
  - files_retention: 1.5.1
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - groupfolders: 4.0.3
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - news: 14.0.0-alpha0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - ojsxc: 3.4.4
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - richdocuments: 3.3.12
  - serverinfo: 1.6.0
  - spreed: 6.0.2
  - support: 1.0.0
  - systemtags: 1.6.0
  - tasks: 0.11.0
  - terms_of_service: 1.2.1
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 2.1.2
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - federation
  - files_external
  - firstrunwizard
  - sharebymail
  - survey_client
  - theming
  - updatenotification
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "dashboard,files",
        "default_language": "en",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image"
        ],
        "filelocking.enabled": true,
        "htaccess.RewriteBase": "\/",
        "knowledgebaseenabled": false,
        "log_rotate_size": 104857600,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": false,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mysql.utf8mb4": true,
        "overwrite.cli.url": "https:\/\/example.com",
        "overwriteprotocol": "https",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "remember_login_cookie_lifetime": 86400,
        "skeletondirectory": "\/opt\/nextcloud-data\/skeleton_files",
        "theme": "gibberfish",
        "token_auth_enforced": true,
        "trusted_domains": [
            "cloud.gibber.fish",
            "4ywub55unvc6dxqh.onion"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "upgrade.disable-web": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "version": "16.0.1.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}
```

**Are you using an external user-backend, if yes which one:** N/A

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
Error logged when uploading a attachment
```
[index] Error: Error: Call to a member function getId() on array at <<closure>>

 0. /opt/nextcloud/apps/deck/lib/Activity/ActivityManager.php line 243
    OCA\Deck\Activity\ActivityManager->createEvent("deck_card", OCA\Deck\Db\Attachment {id: 4}, "attachment_create", [], null)
 1. /opt/nextcloud/apps/deck/lib/Service/AttachmentService.php line 213
    OCA\Deck\Activity\ActivityManager->triggerEvent("deck_card", OCA\Deck\Db\Attachment {id: 4}, "attachment_create")
 2. /opt/nextcloud/apps/deck/lib/Controller/AttachmentController.php line 67
    OCA\Deck\Service\AttachmentService->create("6", "deck_file", null)
 3. /opt/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Deck\Controller\AttachmentController->create("6")
 4. /opt/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Deck\Control ... {}, "create")
 5. /opt/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Deck\Control ... {}, "create")
 6. /opt/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Deck\\Cont ... r", "create", OC\AppFramework\ ... {}, {cardId: "6",_ro ... "})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({cardId: "6",_ro ... "})
 8. /opt/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {cardId: "6",_ro ... "})
 9. /opt/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/apps/deck/cards/6/attachment")
10. /opt/nextcloud/index.php line 42
    OC::handleRequest()
```

#### Browser log
Error logged when attempting to delete an attachment
```
Possibly unhandled rejection: Error when removing the attachment deck.js:53432:41
    consoleLog https://cloud.gibber.fish/apps/deck/js/build/deck.js?v=f5146097:53432
    get https://cloud.gibber.fish/apps/deck/js/build/deck.js?v=f5146097:49711
    processChecks https://cloud.gibber.fish/apps/deck/js/build/deck.js?v=f5146097:55842
    $digest https://cloud.gibber.fish/apps/deck/js/build/deck.js?v=f5146097:56977
    $apply https://cloud.gibber.fish/apps/deck/js/build/deck.js?v=f5146097:57365
    done https://cloud.gibber.fish/apps/deck/js/build/deck.js?v=f5146097:51208
    completeRequest https://cloud.gibber.fish/apps/deck/js/build/deck.js?v=f5146097:51465
    requestLoaded https://cloud.gibber.fish/apps/deck/js/build/deck.js?v=f5146097:51370
```

</details>

**Comment by pdproanio** [comment]
I have the same issue, on Nextcloud 15.0.8 (snap installation), with deck 0.6.4. When the user try to upload a file in to card (he has the corrects rights), deck says Failed to upload.

Here is the log:

{"reqId":"8thxFMFJcWOjnZWxpp3A","level":3,"time":"2019-07-02T19:28:57+00:00","remoteAddr":"192.168.160.111","user":"EE3BE7F1-7D92-4E5D-A7EE-600093417579","app":"index","method":"POST","url":"/index.php/apps/deck/cards/7/attachment?type=deck_file","message":{"Exception":"Error","Message":"Call to a member function getId() on array","Code":0,"Trace":[{"file":"/var/snap/nextcloud/13968/nextcloud/extra-apps/deck/lib/Activity/ActivityManager.php","line":243,"function":"createEvent","class":"OCA\\Deck\\Activity\\ActivityManager","type":"->","args":["deck_card",{"id":89,"__class__":"OCA\\Deck\\Db\\Attachment"},"attachment_create",[],null]},{"file":"/var/snap/nextcloud/13968/nextcloud/extra-apps/deck/lib/Service/AttachmentService.php","line":213,"function":"triggerEvent","class":"OCA\\Deck\\Activity\\ActivityManager","type":"->","args":["deck_card",{"id":89,"__class__":"OCA\\Deck\\Db\\Attachment"},"attachment_create"]},{"file":"/var/snap/nextcloud/13968/nextcloud/extra-apps/deck/lib/Controller/AttachmentController.php","line":67,"function":"create","class":"OCA\\Deck\\Service\\AttachmentService","type":"->","args":["7","deck_file",null]},{"file":"/snap/nextcloud/13968/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"create","class":"OCA\\Deck\\Controller\\AttachmentController","type":"->","args":["7"]},{"file":"/snap/nextcloud/13968/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\AttachmentController"},"create"]},{"file":"/snap/nextcloud/13968/htdocs/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\AttachmentController"},"create"]},{"file":"/snap/nextcloud/13968/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\AttachmentController","create",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"cardId":"7","_route":"deck.attachment.create"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"cardId":"7","_route":"deck.attachment.create"}]},{"file":"/snap/nextcloud/13968/htdocs/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"cardId":"7","_route":"deck.attachment.create"}]},{"file":"/snap/nextcloud/13968/htdocs/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/deck/cards/7/attachment"]},{"file":"/snap/nextcloud/13968/htdocs/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/snap/nextcloud/13968/nextcloud/extra-apps/deck/lib/Activity/ActivityManager.php","Line":398,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36","version":"15.0.8.1","id":"5d1bb07ca9043"}

**Comment by pdproanio** [comment]
There is some solution for this issue? the users cant re upload or delete attachment on the cards
