### ISSUE TITLE
moving a card generates an incomplete entry in timeline 

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#1115]
**Describe the bug**
Moving a card generates an incomplete entry in timeline 

**To Reproduce**
1. Move a card to another stack
2. Open card details
3. Click on timeline
4. The entry is just an icon (change.svg) without text

**Expected behavior**
As in earlier versions, the entry in the timeline should also contain a text, not just an icon
(ex: You have moved the card {card} from stack {stackBefore} to {stack}').
or 
no entry in timeline

**Screenshots**

![Personal   Deck   Nextcloud](https://user-images.githubusercontent.com/34692335/60644445-6f0c2400-9e36-11e9-82ef-35b17ea76e79.png)

The entry in activity app contains a text:
![Activity   Nextcloud](https://user-images.githubusercontent.com/34692335/60645110-1d649900-9e38-11e9-9dba-62efea2dfb0a.png)

Tested with 
demo.nextcloud.com
Nextcloud 16.0.1
deck 0.6.2 and 0.6.4

**Comment by putt1ck** [comment]
Confirmed here (16.01, 0.6.4)
