### ISSUE TITLE
add description to cards overview

### ISSUE THREAD

**Issue by PietsHost** [nextcloud/deck#112]
The description should be added to the cards, so you can see it directly if you open the deck app.

Now you have to open every single card to view the description.

here are my suggestions:
- Add description to card overview
- add shortcodes to description like numbered list, formatting, etc.

**Comment by juliushaertl** [comment]
> Add description to card overview

That would add to much content for a simple overview. Do you have a specific usecase for this?

> add shortcodes to description like numbered list, formatting, etc.
Markdown is supported in the description. You can learn more about that here http://commonmark.org/

**Comment by PietsHost** [comment]
Hmm not a use case but maybe add something like a description preview instead of the whole description?

Let's say you have 10 cards and on every card you have 2 words. Then you would like to see these 2 words on every card on the overview instead of opening 10 cards to get these 2 word descriptions

**Comment by artemanufrij** [comment]
@PietsHost You don't need to open it, just move cursor over "description" icon:
![description-tooltip](https://cloud.githubusercontent.com/assets/16517095/25608454/250047ce-2f1b-11e7-8d29-072ae45e3164.png)

**Comment by PietsHost** [comment]
True, but there i just have the plain description and not (markdown) formatted

**Comment by juliushaertl** [comment]
> Let's say you have 10 cards and on every card you have 2 words. Then you would like to see these 2 words on every card on the overview instead of opening 10 cards to get these 2 word descriptions

So in this case it might make sense to just put those information into the title. The board should provide a quick overview of the cards and if you have many of them showing the descripting will be to much information there.

**Comment by artemanufrij** [comment]
I confirm Julius.
