### ISSUE TITLE
Not able to see timeline from before the board was shared

### ISSUE THREAD

**Issue by Emi94** [nextcloud/deck#1125]
Hi,

Not sure if this is considered bug or a feature but if a board has some activity (e.g. comments on cards) and then gets shared with a person, that person can't see any activity before the board was shared with him, just what happens after the share. I tested this on multiple Nextcloud servers (16.0.x) with the latest deck version (0.6.4) and the behavior is the same.

Can this be fixed so people see all board activity (timeline) even if it was just recently shared with him? If this is a feature, then it should have an option to allow the user to see or not see activity before the board was shared with him.

**Comment by juliushaertl** [comment]
This is actually expected behavior as we use the nextcloud activity app, which stores events per user when they are emitted. So there is unfortunately no way we can implement this with the current activity app.

**Comment by putt1ck** [comment]
@juliushaertl implying, but never noticed that a new user would be unable to see a document's history?

**Comment by juliushaertl** [comment]
Sure, but that is how the activity app works in general. It is the same for files, calendar and other apps that integrate it. Maybe we need to look into at some point if we can implement this differently in the activity app, as this is nothing that apps should implement individually.

**Comment by putt1ck** [comment]
@Emi94 can we check this is the same for shared files?

**Comment by Emi94** [comment]
@putt1ck you mean activity for a shared file?

**Comment by Emi94** [comment]
Yes, sharing a file doesn't show the previous activity for the receiving person.

**Comment by putt1ck** [comment]
@Emi94 ok I'll report that as a bug, because the metadata for a collaboration files can be as important, if not more important, than the files themselves

**Comment by putt1ck** [comment]
https://github.com/nextcloud/server/issues/16605

**Comment by putt1ck** [comment]
@juliushaertl in the new comments implementation will it be possible to make historic comments available to anyone who is granted access to the card or is it still limited by the activity app?

**Comment by juliushaertl** [comment]
Yes, the new frontend doesn't have that limitation anymore.
