### ISSUE TITLE
Attachment can not be deleted

### ISSUE THREAD

**Issue by MelBourbon** [nextcloud/deck#1133]
**Describe the bug**
Attachments to a card can not be deleted.

**To Reproduce**
1. Open a card
2. Click on attachment tab
3. Click on the 3 dots next to an attachment
4. Click on the recycle bin or delete attachment text

**Expected behavior**
Attachment should be removed from deck card after click on bin or text

**Observed behavior**
Nothing happens. No error message and attachment still existing. Even after closing and re-opening card.

**Client details:**
 - OS: Windows
 - Browser: Chrome 75.0.3770.80 (64bit) with almost no plugins

**Operating system**: Ubuntu 18.04
**Web server:** Nginx
**Database:** MariaDB
**PHP version:** 7.2
**Nextcloud version:** 16.0.3

**Comment by geez0x1** [comment]
Also seeing this issue under Nextcloud 15.0.10.

**Comment by 0xbb** [comment]
Same with Nextcloud 16 :(. It seems to be CSP related.

**Comment by juliushaertl** [comment]
Fix from https://github.com/nextcloud/deck/pull/1117 was released with 0.6.5
