### ISSUE TITLE
Duplicated card or stack if typing multiple times on Enter

### ISSUE THREAD

**Issue by vnourdin** [nextcloud/deck#1140]
**Describe the bug**

When adding a new card or stack, if I type multiple times on `Enter` (or hit the `+`), multiple duplicated cards or stacks will be created.

As told on the issue #409 it seems to be related to network latency.

**To Reproduce**

1. Go to 'add card'
2. Write a name
3. Type `Enter` 3 times, fastly
4. 3 duplicated cards appeared.

**Expected behavior**

There should be only one card created.

**Client details:**
 - OS: Debian
 - Browser: Firefox

**Server details:**
 - Host: Raspberry Pi 3
 - OS: DietPi v6.25.3
 - NC version: 16.0.3
 - Deck version: 0.6.4

**Comment by juliushaertl** [comment]
Yes, we should disable the input until the state is cleared and sent to the server, let's track this in the existing ticket.
