### ISSUE TITLE
Attach something other than a file to a card

### ISSUE THREAD

**Issue by ryanprior** [nextcloud/deck#1151]
I love that we can attach files (eg images, documents) to a card and I see in other issues (like #564) that we will eventually be able to attach files already stored in NextCloud.

I'd also like to attach other NextCloud objects to my cards. For example:
* Social media posts (eg commentary about this card)
* Calendar events (eg an event related to this card)
* Another card (eg an earlier task for which this card is a follow-up)

It is generally possible to link to these things in the commentary, but like links to files, they don't provide much value or visibility.

**Comment by juliushaertl** [comment]
This is what Nextcloud projects integration was ment for, however we only support linking to boards at the moment. Linking cards is proposed in #965 so I'll close this in favor of that one.

**Comment by ryanprior** [comment]
I tried to link a card to a calendar event today & found I couldn't. @juliushaertl can we reopen this issue since #965 didn't resolve it?

**Comment by juliushaertl** [comment]
The support is there in the deck app, it is basically calendar that is missing https://github.com/nextcloud/calendar/issues/1504
