### ISSUE TITLE
2 MB upload limit, why?

### ISSUE THREAD

**Issue by ghosttable** [nextcloud/deck#1159]
Hi folks,

is there a reason that attachments in Deck are limited to 2 MB and not to the limit of the Nextcloud  host?

Greets

**Comment by putt1ck** [comment]
Technically the host is no longer limited because uploads are chunked (there's a way to set a limit with ACLs). Not sure where the limit in Deck is, but given ability to link large files from the files app via projects, maybe the limit's not a bad thing?

**Comment by ghosttable** [comment]
Its not a Bad thing, but it would be nice if i could set it myself. 
Sure linking is a option but setting it up to 5 MB would help me a lot :)

**Comment by juliushaertl** [comment]
Deck doesn't support chunked uploading yet unfortunately, so the limit you are experiencing is something that is most likely set in your php config.

**Comment by ghosttable** [comment]
Ah ok, so i would need to contact my hoster for editing this to 5 MB. Thx for the Info.

**Comment by juliushaertl** [comment]
upload_max_filesize and post_max_size are the two php.ini settings you might want to check related to than.

**Comment by ghosttable** [comment]
Ok, we would need to reopen cause i have no limits set so far with 2 MB
The webtools Console shows me that the error is caused here 
/deck/js/build/deck.js?v=c4ae8d69-18:83545
any ideas
