### ISSUE TITLE
Redesign header for Nextcloud 12

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#116]
WIth the new app menu in Nextcloud 12 the header doesn't fit well in the design anymore. 

![2017-05-02-180747_959x94_scrot](https://cloud.githubusercontent.com/assets/3404133/25627292/63b3a49c-2f62-11e7-814f-4dc78d3d2bbf.png)

**Comment by pixelipo** [comment]
I can take care of this.
