### ISSUE TITLE
Moving card shows "From"-Stack also as "To"-Stack in timeline

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/deck#1169]
**Describe the bug**
After moving a card, the timeline entry is wrong. It contains the name of the "From"-Stack also as "To"-Stack.

**To Reproduce**
1. Go to Deck App, Open Board
2. Move Card from one Stack to another
3. Open Card details, timeline
4. See wrong entry "Du hast die Karte Beispielaufgabe 3 vom Stapel Offen nach Offen verschoben". "Offen" was the "From"-Stack, the "To"-Stack was here "In Arbeit".

**Expected behavior**
"Du hast die Karte Beispielaufgabe 3 vom Stapel Offen nach In Arbeit verschoben"

**Client details:**
 - OS: Win 10
 - Browser: Firefox 
 - Version: 68.0.1
 - Device: desktop
 - Nextcloud: 16.0.3
 - Deck: 0.6.6

**Comment by putt1ck** [comment]
Confirmed here.

**Comment by msumm** [comment]
The same behaviour applies to **renaming a card** - the activity shows the original name twice instead of the new name.

**Comment by msumm** [comment]
As this also affects the (e-mail) notification of changes to all users of a shared board I'm looking forward to an early bug fix ...

**Comment by a11exandru** [comment]
I solved the moving cards from a stack to another bug and now i'm looking forward to solve the card update description bug, @msumm .
