### ISSUE TITLE
Request: Add option to turn off closing of sidebar when clicking task board

### ISSUE THREAD

**Issue by mchonan1996** [nextcloud/deck#117]
# Why?
I personally used Deck and loved that it wouldn't close my details as I was working. With the latest release, every time I focus the window (by clicking) my details disappear.

So could we possibly add an options menu in Nextcloud's 'Personal' options?

Much appreciated if so.

**Comment by artemanufrij** [comment]
we could add a pin in the top corner for fixing the sidebar. 
![pin](https://cloud.githubusercontent.com/assets/16517095/25649516/6b0d507a-2fd6-11e7-8259-e4fe51d20298.png)

**Comment by juliushaertl** [comment]
I'm not to happy with adding options. We should have a good default for that. I'll have a look how other nextcloud apps behave on that.
