### ISSUE TITLE
Integrate deck with stratos

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#1186]
https://github.com/nextcloud/server/pull/17016

**Comment by juliushaertl** [comment]
Also related to #256

**Comment by desperateCoder** [comment]
> https://github.com/daita/stratos

Link is dead?!

**Comment by splitt3r** [comment]
It was moved to https://github.com/nextcloud/push

**Comment by desperateCoder** [comment]
Woah, seems pretty fancy! No idea how it affects battery life on mobile app side, but looks quite neat and well integrated

**Comment by juliushaertl** [comment]
Let's actually use https://github.com/nextcloud/deck/issues/256 to track this
