### ISSUE TITLE
Clone / Copy boards [$150]

### ISSUE THREAD

**Issue by JSoko** [nextcloud/deck#119]
Imho it would be very helpful to be able to copy boards with and without their content

So you don't have to create the Markers new for each board and can split boards monthly or weekly

Btw: Thanks for your great work!

**Comment by juliushaertl** [comment]
Makes sense. Would also be nice to have for cards/stacks as well.

**Comment by plrunner** [comment]
+1

**Comment by monsieurhannes** [comment]
We have the same case, similar rutines and way too many tags to write them every time. I don't know if that was discussed already, but it would be also great to have a new tag automatically added to the board when someone writes that in the blank tag field. 
**Anyway, great app!**

**Comment by rhersel** [comment]
We make much use of templates in Kanban boards. If you create a new board, you don't want to design it again an again.

**Comment by Energiegenossenschaft** [comment]
We use nextcloud in our cooperative. We would like to say goodbye to Trello and change completely on deck. But the function to copy boards is missing. We would welcome this extension and are willing to pay an amount of CHF 150. Thank you for your efforts so far!

**Comment by novadeviator** [comment]
Duplicating boards (and stacks and tasks) seems to be a really crucial feature in order for Deck to be really useful for any medium sized project management.

**Comment by juliushaertl** [comment]
@Energiegenossenschaft You can always put a bounty on it at https://www.bountysource.com/issues/44830048-clone-copy-boards That way community contributors who solve the issue will get the money then.

**Comment by niftylouie** [comment]
This feature is absolutely needed. Add templates or Copy or both, and it will become a web based project management solution overnight. I'm an architect licensed in two states who plans to use this system for collaborative project management - one-stop-shop.

**Comment by charlessteiner** [comment]
Agreed. It would be cool. 
What is a rough figure for a bounty for this? Maybe a few of us can contribute.

**Comment by pieter-groeneweg** [comment]
mmm.. yes.. or a way to create templates for recurring projects types.
when creating a new website 90% of the activities is similar...
when clicking new board it would be nice to be able from a list of present templates.

**Comment by frankmaszinek** [comment]
Exactly!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Energiegenossenschaft** [comment]
We will push this issue with additional CHF 150. Which means we are now at bounty CHF 300.-. We would extremely welcome a rapid implementation!

**Comment by juliushaertl** [comment]
@Energiegenossenschaft That is awesome :rocket: 

@jakobroehrl Implemented the first part of this in our vue rewrite that is currently happening. The next release will come with a basic clone functionality that creates a copy of the board with stacks and labels taken from the original one. 

For copying cards in the same run I'd like to get some feedback if that is actually a use case.

**Comment by Energiegenossenschaft** [comment]
Stormy times... When can we expect the integration & release from copy/clone into deck?

**Comment by Energiegenossenschaft** [comment]
@juliushaertl
> For copying cards in the same run I'd like to get some feedback if that is actually a use case.

It is practical if a project template can be created and cloned with the whole content. The cards should be included, otherwise the whole thing doesn't make much sense!

**Comment by juliushaertl** [comment]
THe point for not including them would be that I was assuming that a template would define the board layout (columns) and labels, while the actual cards or tasks would be different for each new clone of the board.

But maybe we can just add an option then to either include cards or not when cloning.

**Comment by Energiegenossenschaft** [comment]
@juliushaertl
> But maybe we can just add an option then to either include cards or not when cloning.
This would be ideal, to choose by cloning the board with or without the cards. We would very much welcome an implementation and integration in the coming weeks. We would be ready to pay additional CHF 100 for this. Do you think an implementation by mid of June is realistic?

**Comment by juliushaertl** [comment]
I won't have time for this, but maybe something for you to implement and hunt some bounty @jakobroehrl since you already did the first part of cloning. :wink:

**Comment by jakobroehrl** [comment]
Will do this, after https://github.com/nextcloud/deck/pull/1777 is implemented

**Comment by juliushaertl** [comment]
Hey there,

I'd just like to let you know that due to the [ongoing issue with Bountysource](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943) we're discussing ways to move to a different platform. As it looks right now, Bountysource might claim some of the money that was contributed by the community. We will try our best to prevent that. Historically we – the Nextcloud GmbH employees – simply put the claimed bounties back to other tickets until one was solved by a community member. So the money was always *from the community* and *for the community*. We'll therefore move to a better platform and currently don't post any new bounties until this situation is resolved. The current goal is to move/donate the money to [Nextcloud include](https://nextcloud.com/include/) but details will follow in the [forum post](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).

Hope this makes sense. If you have any questions please ask them on the forum. This comment will be copy-pasted to all open issues with bounties.

**Comment by coach1988** [comment]
> 
> 
> @Energiegenossenschaft That is awesome 🚀
> 
> @jakobroehrl Implemented the first part of this in our vue rewrite that is currently happening. The next release will come with a basic clone functionality that creates a copy of the board with stacks and labels taken from the original one.
> 
> For copying cards in the same run I'd like to get some feedback if that is actually a use case.

Received a request today that the clone function doesn't include the cards, so it looks like at least some users expect them to get copied, too.
Both makes sense in my opinion, being able to copy the cards would probably help with separate boards for similar tasks.

**Comment by artifactdev** [comment]
> > @Energiegenossenschaft That is awesome 🚀
> > @jakobroehrl Implemented the first part of this in our vue rewrite that is currently happening. The next release will come with a basic clone functionality that creates a copy of the board with stacks and labels taken from the original one.
> > For copying cards in the same run I'd like to get some feedback if that is actually a use case.
> 
> Received a request today that the clone function doesn't include the cards, so it looks like at least some users expect them to get copied, too.
> Both makes sense in my opinion, being able to copy the cards would probably help with separate boards for similar tasks.

Indeed I expected at least the option to duplicate a board with all the cards to have a "template-board" for same type of projects.

**Comment by Draco-Red** [comment]
Is there any eta on cloning of the cards along with the boards?  I'm trying to implement a template type system since our work process is largely the same for each project, and was surprised to find that "Cloning" the board didn't automatically clone the cards as well.  Thanks.

**Comment by maxammann** [comment]
This could be implemented quite easily with https://github.com/maxammann/trello-to-deck/issues

Would this be sufficient for the people who have the need to clone boards?

**Comment by compumatter** [comment]
Totally necessary.  All other pro board software has this.  Trello included.  Opensource Wekan also has it.  Templates are a required feature for businesses because they define for a specific purpose and need that same purpose over and over again.  Copying a board might work as a substitute but it's a hack compared to the right way which is defining multiple templates, allowing to name for their intended purpose and then use them as needed.

**Comment by Energiegenossenschaft** [comment]
Our cooperative uses deck every day and we are very grateful for this tool!! Cloning boards, including cards, would make our day-to-day project work , we are building solar powerplants, much easier. Of course, we would still pay the promised commission of $300.

**Comment by jakobroehrl** [comment]
@juliushaertl 
Could you take time to review https://github.com/nextcloud/deck/pull/1777 ?
This feature should be almost ready

**Comment by juliushaertl** [comment]
Closing in favor of https://github.com/nextcloud/deck/issues/2797 for the remaining part to also clone the cards.
