### ISSUE TITLE
Icons should be reordered...

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#120]
[EDIT] [DELETE] or [DELETE] [EDIT]

![icons](https://cloud.githubusercontent.com/assets/16517095/25713858/6a71c09e-30f6-11e7-9c16-24c36886e30f.png)

**Comment by artemanufrij** [comment]
@juliushaertl if you confirm this issue, so I can fix it...

**Comment by juliushaertl** [comment]
Edit, Delete makes sense, as it is already done in #121 :+1:

**Comment by pixelipo** [comment]
Close?

**Comment by artemanufrij** [comment]
@pixelipo yes. it's already merged
