### ISSUE TITLE
Personal board color is black

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#1218]
![Deck personal board color is black - should be green or so](https://user-images.githubusercontent.com/925062/64190545-ec740500-ce76-11e9-88e6-5b64c482d079.png)

Should instead be the first color of the presets in the color picker, so blue or green or so. What do you think?

**Comment by MinhHaDuong** [comment]
Thanks. That also bugged me.

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master
