### ISSUE TITLE
Download through Nextcloud appstore impossible for v0.1.4

### ISSUE THREAD

**Issue by Bloodsoul** [nextcloud/deck#122]
The corresponding tag to the release of v0.1.4 is named with a doubled v, therefore it is not possible to download it through the appstore:
`Client error response [url] https://github.com/nextcloud/deck/releases/download/v0.1.4/deck.tar.gz [status code] 404 [reason phrase] Not Found`

Currently working link includes maybe misspelled tag name:
`https://github.com/nextcloud/deck/releases/download/vv0.1.4/deck.tar.gz`

**Comment by morph027** [comment]
Jip, same here

**Comment by juliushaertl** [comment]
Fixed. Thanks for the hint everyone. Something must have gone wrong when adding the changelog. After the release.
