### ISSUE TITLE
ER: Minimized Left Panel

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/deck#123]
It would be nice if I could minimize the left panel -  perhaps only showing the round circles to represent the other kanbans (without text). 

I've already been in a situation where I was going over a kanban with a client who was able to see the names of my other kanbans (including one for a competitor).

**Comment by artemanufrij** [comment]
@aproposnix @juliushaertl what do you think about a solution like files:
![screenshot_20170601_223559](https://cloud.githubusercontent.com/assets/16517095/26699779/3c5b2502-471b-11e7-91cf-4d0d59316deb.png)
![screenshot_20170601_223655](https://cloud.githubusercontent.com/assets/16517095/26699780/3c5c916c-471b-11e7-9ddb-7e5939f5ef51.png)

**Comment by juliushaertl** [comment]
@artemanufrij Let's do it like this, since otherwise the sidebar is also not accessible on mobile which is required after #133. Do you want to prepare a PR?

**Comment by artemanufrij** [comment]
I have already a PR on my local system

**Comment by artemanufrij** [comment]
issue fixed in #177

**Comment by aproposnix** [comment]
Sorry for the late reply, but yeah, this is great! Thank you!
