### ISSUE TITLE
Case insensitive searching

### ISSUE THREAD

**Issue by rprpx** [nextcloud/deck#1233]
Could we make the SEARCH field in the upper right case-INsensitive? 

Having to be sure I search for the same CASE may lead me to miss a card that's actually present.

Additionally, case-INsensitive searching in this field would then be consistent with typing/adding a TAG to an item/card, which narrows your tag selections as you type regardless of case used in the actual TAG. 

Thank you!

**Comment by matchish** [comment]
A Search engine for the query can be different for different applications. For example, if an application uses Elasticsearch then results can be sorted by a score(relevancy) so then you will get all cards but cards with the wrong case will be at the end of the list.

So I think it not the best idea to lowercase query in the field, but I agree that usually, it's more useful to have a case-insensitive search. In what application you don't have case-insensitive search. I mean in `files` and `contacts` for example the search is case-insensitive.
