### ISSUE TITLE
Cannot assign cards to circle members

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/deck#1237]
**Describe the bug**
I can assign a circle to a board, but not cards to circle members.

**Steps to reproduce**
1. Circles app: Create a circle _myCircle_ (bug applies to all circle types)
2. Assign some users to the circle
3. Deck app: create a board _myBoard_
4. Open details for _myBoard_
5. share board with circle _myCircle_
6. create stack _myStack_
7. create card _myCard_ in _myStack_
8. open details for _myCard_
9. click on the **#** at _assign users_

**Expected behavior**
The dropdown menu shows me and the circle members added under 2.

**Actual behavior**
Only my name is shown.

tested with
- NC 17.0.0 Beta 4 with Circles 0.17.7 and Deck 0.7.0
- NC 16.0.4 with Circles 0.17.7 and Deck 0.6.6

**Comment by juliushaertl** [comment]
Fixed with 1.0.0 and latest circles release
