### ISSUE TITLE
Show list of assignments

### ISSUE THREAD

**Issue by klemens-u** [nextcloud/deck#1239]
I'm missing a view with all cards assigned to one person. 
That would provide a helpful overview which cards are assigned to me, and to other persons.

Ideally there would be an option to view assignments per board and globally.

So in the menu on the left side:

- Cards assigned to me
- Cards assigned to
   [Select box]
   [ Tom ]
   [ Anna ]
   [ John ]

**Comment by klemens-u** [comment]
Still valid.

**Comment by putt1ck** [comment]
Closed because it's part of #414
