### ISSUE TITLE
Add card above

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/deck#1240]
As you can only add new cards at the bottom of a stack you sometimes have to scroll down quite a bit. And if you want to add a new "high priority" card that shall sit at the **top of the stack**, you have to first **scroll down** for creation and then **move it all the way up**.

Wouldn't it be easier to add the entry **Add card above** or **New card above** to the context menu if you click on the three dots of any card?

It could look like this:
![https://cloud.privacy1st.de/s/fq3o7EXgTMDHPom/preview](https://cloud.privacy1st.de/s/fq3o7EXgTMDHPom/preview)

If I just missed a second way how it is already possible to create new cards apart from the "Add card" button at the bottom of each stack, I'm really sorry!

**Comment by juliushaertl** [comment]
I don't think we should add another way of creating cards. I get that it is a shortcut to not needing to reorder cards after adding them, but adding a menu entry for this feels a bit to much and is not really related to the card (where the context menu is showing up) We should keep UI options limited to what is actually required.

@nextcloud/designers

**Comment by langfingaz** [comment]
Well, looking back on this issue now, I understand your point. To add a fourth option for this would make the context menu 1/3 larger... Thanks for the reply!
