### ISSUE TITLE
Assing only cards to users

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/deck#1241]
**Is your feature request related to a problem? Please describe.**
At times I want to assign a single card to users to look at and contribute to it (comments, description, attachments), and not share the entire deck.

**Describe the solution you'd like**
Assign card to users - and only that card will be visible to them. Will hide all of the other cards.

**Comment by juliushaertl** [comment]
duplicate of https://github.com/nextcloud/deck/issues/663
