### ISSUE TITLE
Use clip instead of folder to represent attachment

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#1253]
Please use a clip icon instead of a folder to represent attachments.

The android client will do so. BTW this is a feature request by @jancborchardt who said it would be good to do this in the web interface also :)

![grafik](https://user-images.githubusercontent.com/4741199/64985964-5accb480-d8c6-11e9-9f06-53cef71af248.png)

**Comment by jancborchardt** [comment]
To be specific it’s @jenniferpiperek who brought it up, I simply agree with it. :)

**Comment by jakobroehrl** [comment]
@jancborchardt Where can I get the icon?
Didn't found it here: https://docs.nextcloud.com/server/17/developer_manual/design/icons.html

**Comment by jancborchardt** [comment]
I assume @stefan-niedermann has it from Material icons, and it would be findable in his repo at https://github.com/stefan-niedermann/nextcloud-deck ? :)

**Comment by juliushaertl** [comment]
Are those icons compatible to be used with AGPL?

**Comment by jancborchardt** [comment]
> Are those icons compatible to be used with AGPL?

Yep, it’s Apache 2.0 as per https://material.io/resources/icons/?style=baseline and https://github.com/google/material-design-icons :)

**Comment by jancborchardt** [comment]
> Are those icons compatible to be used with AGPL?

Yep, it’s Apache 2.0 as per https://material.io/resources/icons/?style=baseline and https://github.com/google/material-design-icons :)

See specific compatibility info: https://en.wikipedia.org/wiki/Apache_License#Compatibility (TL;DR Apache is more permissive than the copyleft GPL, so it is ok to include Apache stuff into GPL, just not the other way around.)

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master
