### ISSUE TITLE
Date picker does not work for 31st

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/deck#1258]
**Describe the bug**
If you choose October 31st at the date picker, it becomes October 1st. This behavior seems the same for all months with 31 days.
For months with 30 days, everything is ok, for February 29th it becomes 28th.

After a retry (clicking the 31st again), it works.

Reproducable with Nextcloud 15.0.11 and 16.0.4, if you need more info because you can't reproduce, please let me know, then I will fill out the whole template.

**Comment by juliushaertl** [comment]
Should be fixed in the upcoming 1.0 with the date picker component we use from https://nextcloud-vue-components.netlify.app/
