### ISSUE TITLE
REST-API only usable after web app has been opened at least once

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#1262]
**Describe the bug**
The REST-API does respond with error messages when it is used before the user has opened the web interface at least one time before.

**To Reproduce**
1. Create new dummy user
2. Do NOT open the deck app in the browser
3. Use Android Deck App to connect
4. See error in log (something like `owner is null`)

**Expected behavior**
REST-API can be used fully without opening it in the web interface. Maybe do first initialization stuff as post install hook or when using the REST-API (like checking a flag `isInitialized` and do initialization if flag is `false`)

**Comment by stefan-niedermann** [comment]
Please keep open @juliushaertl

**Comment by juliushaertl** [comment]
@stefan-niedermann Do you have the actual log error available?

**Comment by stefan-niedermann** [comment]
currently not, but if i am at my notebook back again, i will reproduce this error

**Comment by stefan-niedermann** [comment]
Maybe @desperateCoder can explain better what exactly is happening here.

https://github.com/stefan-niedermann/nextcloud-deck/blob/9898c0135132b323c433f0bc33ce3fbd2bef7b88/app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/SyncManager.java#L205

It has been a while since september, i do not remember exactly, but i let a hint there "this can be the case if the Deck app has never before been opened in the webinterface" - and voila - as soon as i opened the deck app on my test user the very first time, this does not happen anymore.

**Comment by desperateCoder** [comment]
@stefan-niedermann i actually have no idea. safe to close?

**Comment by stefan-niedermann** [comment]
No, create a new user, try to connect to it. Does only work, when the web UI for this user has at least been opened once. No log available yet

**Comment by desperateCoder** [comment]
What do we need? Server response for this case? PHP logs from the server?

**Comment by juliushaertl** [comment]
I don't see where this would fail on the server side, if the user has never opened the web interface the /boards endpoint will just return an empty array as no default "Personal" board has been created. 

I'll prepare a pull request to create the initial board from the API as well, but I guess there is also an issue on the app side here.

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/deck/pull/1492
