### ISSUE TITLE
Drag feature is no longer working with iPad iOS 13.1

### ISSUE THREAD

**Issue by str0g** [nextcloud/deck#1263]
**Describe the bug**
Ticket cannot be touched focused in iOS 13.1. (There was no problem with 12.x version)

**To Reproduce**
1. Create 3 columns
2. Create ticket in column 1
3. Try to move tickets between column
4. Ticket element is being seen as text element only and text copy action has been applied

**Expected behavior**
Ticket should’ve  be moveable  across the board. I’ve try this with jira and they tickets are still working correctly. 

**Screenshots**
N/A

**Client details:**
 - OS: iOS 13.1
 - Browser [firefox, safari]
 - Device: [iPad Pro 11]

<details>
<summary>Server details</summary>

**Operating system**:
ArchLinux
**Web server:**
Apach 2.4
**Database:**
Postgres
**PHP version:**
7.3.9

**Nextcloud version:** (see Nextcloud admin page)
16.0.4
**Where did you install Nextcloud from:**
AUR
**Signing status:**

```
No errors have been found.
```

**Comment by BKapelari** [comment]
This is a huge problem! Drag and Drop does not work on iPhone and iPad. I didn’t test it on other touch devices but this is really annoying cause it makes the app unusable!

The Vue Plugin for DnD used in Deck supports touch devices ans I have no problems on their demo:
https://kutlugsahin.github.io/vue-smooth-dnd/#/cards

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by juliushaertl** [comment]
Both of your reports miss the actual deck version this is happening on. 

> The Vue Plugin for DnD used in Deck supports touch devices ans I have no problems on their demo:

Our Vue frontend is only available on our nightly builds until now. Could you give those a try?

**Comment by BKapelari** [comment]
> > The Vue Plugin for DnD used in Deck supports touch devices ans I have no problems on their demo:
> 
> Our Vue frontend is only available on our nightly builds until now. Could you give those a try?

Okay, my fault. Now I tried it with the nightly build and DnD works BUT: The horizontal scrolling does irritate. So you can't control where to drop. On the old version, the stacks were listed among themselves. I think we have to make this again. Horizontal scrolling does also fire the show/hide sidebar gesture

**Comment by juliushaertl** [comment]
Thanks for giving this a try. Yes, that is a regression by the vue migration. Let me add that to our list of things to fix before the release.

**Comment by juliushaertl** [comment]
We removed the sidebar dragging for now and @jakobroehrl tested that dragging is working properly now on iOS.
