### ISSUE TITLE
Focus mode for card editing

### ISSUE THREAD

**Issue by Zocker1999NET** [nextcloud/deck#1264]
**Is your feature request related to a problem? Please describe.**
The sidebar for editing the description of cards is a little bit too small on desktops if single lines of the descriptions are a little bit long like for example hyperlinks/urls.

**Describe the solution you'd like**
Please add a way to maximize the sidebar across the whole screen width so longer lines may not be wrapped.

**Describe alternatives you've considered**
An alternative may be to change the sidebar to a popup which resizes automatically or add a way to resize the sidebar with the mouse.

**Additional context**
I refer to this sidebar:
![65671020-02b84f80-e036-11e9-823f-33c670c740e9](https://user-images.githubusercontent.com/1645646/66332215-81659480-e934-11e9-8d0c-fc96d8f4d171.png)

**Comment by juliushaertl** [comment]
Trello uses a popover which gives a bit more space but then you loose the context of the rest of the board. Maybe we just increase the sidebar width a bit on larger screens? cc @nextcloud/designers

**Comment by Dubidubiduu** [comment]
I don't get the problem. Your request is not about having long text in that field, but with long lines? What is wrong with wrapping long lines?

**Comment by Zocker1999NET** [comment]
@Dubidubiduu It is for example a problem if I paste long hyperlinks into the text field together with a label before. For example editing the following example note does not look good:

```
- My first article: https://shop.example.com/article/A_Really_Long_Article_Name_For_Something/654321
- My second article: https://shop.example.com/article/This_is_not_good_readable_on_the_small_sidebar/123456
```

On a screen with a width of 1920 pixels where I can only use roundabout 450 pixels to type in a note is not preferable in my opinion. My example in action:
![image](https://user-images.githubusercontent.com/1645646/66331905-d7860800-e933-11e9-8285-b7f4ebde19c2.png)
Compared to if the sidebar width is increased:
![image](https://user-images.githubusercontent.com/1645646/66332087-321f6400-e934-11e9-8fb7-1e7a7413b80b.png)

@juliushaertl This is a good proposal. Another way would be to let the user change the width but let the default be adaptive to the screen's width (e.g. 20% of the screen's width).

**Comment by stefan-niedermann** [comment]
Well, log entries like this should be put in thre backticks, so the lines should not be wrapped, just like at github IMHO

**Comment by Zocker1999NET** [comment]
@stefan-niedermann Backticks only work in "view" mode, my problem is about the "edit" mode

**Comment by jancborchardt** [comment]
> Maybe we just increase the sidebar width a bit on larger screens? cc @nextcloud/designers

@juliushaertl similar to the point that @ma12-co had on the left navigation width. Let’s talk about this during today’s meeting maybe?

But also let’s keep in mind that this will just slightly enhance it, and longer links will not work again then. :)

**Comment by juliushaertl** [comment]
Let me add the notes from our discussion yesterday:

## AppSidebar width

- Julius: Sidebar size needs to be wider for deck? Had a request from someone who wanted to

- Jan: have navigation and sidebar behave the same? (width speaking)
  
  - Jenni: it could be super nice ot have the option to choose your own width (flexibility increase and interaction) And for the left navigation, there should be a max width.
  
  - Julius: Data into both of the items are not very alike. Not sure it make sense to do it
  
  - Jan: we have to remember the setting if we do it. But should it be on per app basis? Or just a global setting?
  
  - Jan: Open full screen focused editor for larger text fields

**→ Let’s try with the full screen focused viewer with a button in the Deck app description field (Julius)**

**Comment by kbeerepoot** [comment]
> I don't get the problem. Your request is not about having long text in that field, but with long lines? What is wrong with wrapping long lines?

The problem is that the title of the card will wrap when the card details are just _displayed_, but the moment you want to _edit_ the card title it will switch to showing it on one (1) line which will need to be horizontally scrolled because the width of the details section is not wide enough. This is incredibly annoying, and would not be a problem if editing was possible on a wrapped line ...

**Comment by jancborchardt** [comment]
Right – in the Deck app it is a special case where it makes sense to wrap the card title to multiple lines and not force it to one. :)

**Comment by alexanderdd** [comment]
@juliushaertl I think this can be closed because the new modal view is implemented?

**Comment by juliushaertl** [comment]
Yes, definitely, thanks for the notice :+1:
