### ISSUE TITLE
l10n/en_GB not change 

### ISSUE THREAD

**Issue by wicky-info** [nextcloud/deck#1266]
I try to change languange form folder l10n/en_GB.js . I want to change name "Deck" with my languange 

OC.L10N.register(
    "deck",
    {
    "Please provide a content for your comment." : "Please provide a content for your comment.",
    "Posting the comment failed." : "Posting the comment failed.",
    "Remove user from card" : "Remove user from card",
    "Hours" : "Hours",
    "Minutes" : "Minutes",
    "Deck" : "I need this name with my languange but can't change",
    "The card \"%s\" on \"%s\" has reached its due date." : "The card \"%s\" on \"%s\" has reached its due date.",
    "The board \"%s\" has been shared with you by %s." : "The board \"%s\" has been shared with you by %s.",
    "{user} has shared the board %s with you." : "{user} has shared the board %s with you.",
    "Finished" : "Finished",
    "To review" : "To review",
    "Action needed" : "Action needed",
    "Later" : "Later",

**Comment by juliushaertl** [comment]
There is also a json file to change that is used by the backend. Please use help.nextcloud.com for questions in general, since this is an issue tracker to plan features and track bugs.
