### ISSUE TITLE
Tags are not localized

### ISSUE THREAD

**Issue by MagicFab** [nextcloud/deck#1273]
When switching languages, tags remain in the original language the admin user had when the app was installed.

**Expected behavior**
When switching languages tags should be localized. This would probably also require ability to enter several languages in UI when creating new tags.

NC version 16, Deck v. 0.6.6

**Comment by putt1ck** [comment]
Aren't the tags in Deck the same as across NC - so user created and therefore not translatable per se?

**Comment by MagicFab** [comment]
> Aren't the tags in Deck the same as across NC - so user created and therefore not translatable per se?

No, see #201

**Comment by juliushaertl** [comment]
The tags will be created once per user when the board is created. Since they are basically a free text field I don't see how we could support having them translated. Also when sharing the board to different users, the text will always be static.
