### ISSUE TITLE
Review Overall design and CSS strategy - implement FLEX

### ISSUE THREAD

**Issue by x9t9** [nextcloud/deck#128]
After seeing #82 and #84 , I have decided to create a new issue that would potentially handle -  and could be referenced from - all the other issues and / or improvements that can be handled or addressed  with having a more stable and thoughtful overall design strategy , like moving to a `flex` CSS flex technique .
Feel free to reference all layout related issues here , contribute , or close this issue if deemed unnecessary .

- [x] Use flexbox for new board form/colors (fixed in #133)

**Comment by artemanufrij** [comment]
let close it. 
it's a continuous process.
