### ISSUE TITLE
History/timeline for a board

### ISSUE THREAD

**Issue by sheepchen** [nextcloud/deck#1281]
Hi,

it would be nice if you have a timeline for your board. Here should be logged when and who moved a card from which staple to which. Also creating, archiving or deleting should be logged. There is a timeline tab for the boards, but it is empty.

**Comment by juliushaertl** [comment]
Do you have the activity app enabled?

**Comment by sheepchen** [comment]
Thanks, it was deactivated. But now i have tried it. I moved a card from "ToDo" to "Abgeschlossen" (finished in german).
The activity message is "Du hast die Karte OPAmp bauen vom Stapel ToDo nach ToDo verschoben"
translated: "You moved the card 'build OPAmp' from staple ToDo to ToDo"
There should stand "from ToDo to Abgeschlossen"

This error is reproducable.

**Comment by putt1ck** [comment]
That's a known and patched (next release?) bug https://github.com/nextcloud/deck/issues/1169
