### ISSUE TITLE
newline in card + linkhighlighting

### ISSUE THREAD

**Issue by sheepchen** [nextcloud/deck#1282]
Hi, 

It would be nice if you can make a newline in a card. Like in Excel with ALT+ENTER or SHIFT+ENTER.
Also links should highlight (blue + unterline, clickable) in cards

**Comment by gary-kim** [comment]
The card description is using markdown so you can make a new paragrah by putting two new lines or putting two spaces before the new line.

**Comment by juliushaertl** [comment]
Yes, formatting is available in the description. We should not add it to the title itself as this would create a much more cluttered interface.

**Comment by prokler** [comment]
> We should not add it to the title itself as this would create a much more cluttered interface.

I disagree. You should definitely make it possible to add line breaks to the title. That would be really useful and doesn't create a more cluttered interface at all.

<sup>Thanks for the nice work btw.! </sup>
