### ISSUE TITLE
Add simple info on markdown input elements

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/deck#129]
As mentioned in #127 , users could use a simple "how-to" on writing markdown.

My proposal is to add an "i" button in the (lower) right corner that would show a small markdown cheat-sheet in a popover, similar to this:

![image](https://cloud.githubusercontent.com/assets/4129927/25895326/b028af98-357f-11e7-96f7-678e5b9cff86.png)

How does that sound?

P.S. Someone should come up with a list of what should actually go there. [This](http://daringfireball.net/projects/markdown/basics) or [this](https://bitbucket.org/tutorials/markdowndemo/overview) list might be good starting points.

**Comment by juliushaertl** [comment]
Good point, i guess we should have a short description directly inside the app and link to a more extensive documentation. 
Similar to what Trello does:

[Trello Markdown hints](https://cloud.githubusercontent.com/assets/3404133/26050419/d4081042-395e-11e7-9afd-b44315b846f8.png)

**Comment by x9t9** [comment]
I think that is the way to go, but it need to be hosted .
Not sure if nexcloud has a help wiki like page, or somewhere to host this help if indeed external.
Other option is just to provide a link to another markdown - related help, or even the help page of the actual script itself .

**Comment by juliushaertl** [comment]
@x9t9 We can just create a page on the github repo wiki for that.

**Comment by x9t9** [comment]
Sure , I can do that if needed . as long as I don't interfere with @pixelipo wip ...

**Comment by x9t9** [comment]
After creating the page and while editing it I actually noticed that the wikipage would just result in duplicated content.
I feel it is much better to just incorporate the (`_BLANK` ) link to https://markdown-it.github.io, which provides demo, a kind of playground, and a comprehensive list of all the supported features .
The only useful entry is the `known issues` reference to #127 and the cited solution .
This can also be places in a general `known-issues` page for deck. No need for a special markdown page.
So feel free to just delete the whole page .

**Comment by juliushaertl** [comment]
I'd prefer to still keep the wiki page and link to that, since we can then also mention plugins we use as it might come with #53 

I did some further adjustments to that https://github.com/nextcloud/deck/wiki/Markdown-Help
Thanks for getting it started @x9t9
