### ISSUE TITLE
New Owner for a board

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#1306]
**Is your feature request related to a problem? Please describe.**
I accidentally created a board with a wrong user, now it is full of decks.

**Describe the solution you'd like**
I want to give the ownership to another user.

**Describe alternatives you've considered**
Copying deck to another user, would be needed that this is an exact copy with history, discussion and all.

**Additional context**
I want to have everything under one user which is used for administration purposes. I think this way I don't get any problems if people pass of my team.

**Comment by sgdox** [comment]
Hello, we need this enhancement, because when a user left the organization, or change their functions, its impossible to change the owner.

**Comment by Dubidubiduu** [comment]
@juliushaertl as you asked in #119, if there is a use case in also copy cards in a run with copying boards, yeah, so here is one use case.

Just wondering: Do you think, as for me it's just two boards, it's enough to change owner in "oc_deck_boards"-table in the database to another owner? Will this break anything?

Then I could finally delete the old users...

**Comment by juliushaertl** [comment]
> Just wondering: Do you think, as for me it's just two boards, it's enough to change owner in "oc_deck_boards"-table in the database to another owner? Will this break anything?

That should work fine. 

Maybe we could start of with a simple occ command to transfer the ownership of a board to a different user (similar to how it works for files).

**Comment by Dubidubiduu** [comment]
> That should work fine.

Almost.

My situation:

Board x - users:
A (deprecated user) - owner
B - shared with user

So ownership should be transformed from A to B. When I just change owner in database it becomes:

Board x - users:
B - owner
B - shared with user

And with this situation, somehow, I wasn't able to delete the share. So I gave the owner to another user C, deleted the share of B, and then gave the ownership to B.

Maybe it was just some caching and I wasn't patient enough, just wanted to let you know.

**Comment by matchish** [comment]
I've implemented the feature for my needs as an `occ` command. If it has a value for the community I can create PR

**Comment by juliushaertl** [comment]
@matchish Cool, a pull requests for that would bei highly appreciated. 🎉

**Comment by benjamindahl** [comment]
in occweb deck doesn't offer deck:transfer-ownership for me. Am I doing something wrong?

`Sun Mar 14 2021 23:26:26Press Enter for more information on occ commands.
occ $ deck:transfer-ownership
                                                       Command "deck:transfer-ownership" is not defined.                                                         Did you mean one of these?                               deck:export                                          files:transfer-ownership                                                                            `

Cheers
Benny

**Comment by nursoda** [comment]
We have a PR that is not reviewed or integrated for over a year? Wow. Pleas tell me, what's needed for the review? How to help?

**Comment by robinofe** [comment]
Deck V 1.5.5:
 Command "deck:transfer-ownership" is not defined. 

deck:transfer-ownership seems not to be implemented yet.

br rob
