### ISSUE TITLE
Card title overflows/goes under the card-options button

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/deck#131]
See screenshot for two (related) problems:

![title-overflow](https://cloud.githubusercontent.com/assets/4129927/25901166/292bd60c-3596-11e7-8a35-2d33eebffc4f.png)

It's really simple to fix - I'll create a PR tomorrow

**Comment by x9t9** [comment]
I would suggest moving it altogether somewhere else , instead  of trying to fix it .
I believe that from UX point of view, and in consideration of future functions / icons / metadata , All of them should be concentrated in a footer / header part of card .
Same problem exists BTW also in the stack title ..

**Comment by pixelipo** [comment]
@x9t9 it would be awesome if you (or anyone) would come up with a comprehensive design strategy for this project. That would really simplify development.

However, until we have something like that, I would consider this a bug to be fixed.

Regarding this particular issue, title **is** header, right? So even if we set a static position for buttons, the issue persists. Looking at Trello, they keep a similar button in the top-right corner and it often goes over card title. However, their button has a gray background on hover, so it's not as bad (but I still don't this it's a great solution):
![image](https://cloud.githubusercontent.com/assets/4129927/25942879/4d307622-363e-11e7-94d1-06baaf788fc7.png)

**Comment by pixelipo** [comment]
By the way, thanks for noticing a similar issue with the stack title. The problem there is actually even worse - because `<h2>` element contains a block element `<div class="stack-actions">` which is not a valid HTML code.

**Comment by artemanufrij** [comment]
@pixelipo are you working on this issue?

**Comment by pixelipo** [comment]
@artemanufrij I totally forgot about this issue. I have the code ready, I jest need to rebase and push. PR will be ready for review today.

**Comment by artemanufrij** [comment]
@pixelipo ok, it would be cool if you push it today. At the moment I make a small card redesign
