### ISSUE TITLE
Tag creation with dark theme

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/deck#1313]
![Bildschirmfoto von 2019-10-30 10-56-19](https://user-images.githubusercontent.com/213943/67847956-0b53e800-fb04-11e9-9b0a-c471ead68083.png)

The input value is not readable by default...

**Comment by ishantgupta777** [comment]
I think this issue is already solved.
![text_issue_solved_necl](https://user-images.githubusercontent.com/27751740/79110525-3ff8ea80-7d98-11ea-9770-e0d9008635ca.png)

Is there anything I am missing?

**Comment by juliushaertl** [comment]
Yes, fixed on master during the vue rewrite
