### ISSUE TITLE
Mail notification when a board was shared

### ISSUE THREAD

**Issue by markuman** [nextcloud/deck#1314]
**Is your feature request related to a problem? Please describe.**

When my user "markuman" shares a board with user "something". I would expect that the user "something" gets an email about that. But that doesn't happen.  
So I'm not sure if this is a bug or just a missing feature? Because I got no errors nor I find something similiar in this Issue tracker.

**Describe the solution you'd like**

User should get an Email notification when a board is shared with them.

**Describe alternatives you've considered**

Maybe the notification can be optional (opt-out of deck email notification).

**Comment by putt1ck** [comment]
It depends on that user's activity settings i.e. I get emails from NC when someone shares a new board with me, but I have the "email me" Deck options ticked. Maybe the question is whether that should be the default for a project management app like Deck (although there's no requirement in NC for a user to have an email address, which could be an issue).

**Comment by markuman** [comment]
@putt1ck nice hint!

![Screenshot_2019-10-30 Settings - lekker Box](https://user-images.githubusercontent.com/3920157/67863174-50cfdf80-fb1b-11e9-8028-a337451e0ab8.png)

So I've enabled everything with "deck" in the name - and also enabled the  `A file or folder has been shared` to make sure that the email notification works in general (it does).

But unfortunately there comes no email about activities in the deck app. Nor share notificatio, no description hast changed notification, no comment mentioned.  
I'm running nextcloud 16 atm. Any ideas?

**Comment by markuman** [comment]
Oh, okey, with a longer delay, I got now an "Activity notification" Email
