### ISSUE TITLE
Wrong reminder time

### ISSUE THREAD

**Issue by Ricomanda** [nextcloud/deck#1334]
Entering a reminder, e.g. 16:15 leads to a 05:15 reminder.

**Comment by juliushaertl** [comment]
I cannot reproduce this, please fill out the complete issue template and report your locale used in Nextcloud and your browser.

**Comment by Ricomanda** [comment]
Here is a screenshot after creating a new card with reminder:
![Screenshot_20191111-152925_Nextcloud_Deck](https://user-images.githubusercontent.com/44298441/68597243-ec0e7080-049c-11ea-9c23-9407a86fe8da.png)

Reopening leads to this:
![Screenshot_20191111-152944_Nextcloud_Deck](https://user-images.githubusercontent.com/44298441/68597351-19f3b500-049d-11ea-8b16-c13b6964e1bf.png)

I am using the newest Deck version v0.0.14 (v0.6.6 server version) on Android (Lineage OS 16.0, BQ Aquaris X) running a nextcloud instance (NextCloudPi 16.0.5) on a raspberry pi 3 B.

**Comment by juliushaertl** [comment]
Please open this issue at https://github.com/stefan-niedermann/nextcloud-deck (which is the android apps repo) Works fine in the web UI.
