### ISSUE TITLE
No mark of the selected column

### ISSUE THREAD

**Issue by Ricomanda** [nextcloud/deck#1335]
There is no mark (the white line under the colum name) when pushing a card from one column to another.

**Comment by juliushaertl** [comment]
Can you post a screenshot to show what white line you are referring to?

**Comment by Ricomanda** [comment]
![Screenshot_20191111-152809_Nextcloud_Deck](https://user-images.githubusercontent.com/44298441/68597914-11e84500-049e-11ea-9c46-ff742970ee9c.png)

Swiping through the columns doesn't change the position of the line so I can't see where I drop the card.

**Comment by juliushaertl** [comment]
Please open this issue at https://github.com/stefan-niedermann/nextcloud-deck (which is the android apps repo) Works fine in the web UI.
