### ISSUE TITLE
Question: Why is it allowed to make multiple boards with the same title?

### ISSUE THREAD

**Issue by tcassaert** [nextcloud/deck#1336]
**Describe the bug**
I'm not sure if it's a bug or not. But currently it is possible to make multiple boards with the same title. The boards are identified with an ID of course, but it seems nonlogical to me that the same title can be used multiple times.

**To Reproduce**
1. Create a new board with title `Test`
2. Create another board with title `Test`

**Expected behavior**
I would expect Deck to throw an error, stating there already is a board with that title.

**Comment by putt1ck** [comment]
This would make picking a board via API harder, unless there's a really easy (non-techie) way to get the board ID - and would break the work done on using the API to allow emails to be written as cards which has assumed a unique board name.

(and that's aside from the human confusion of seeing multiple boards with the same name at the Deck top level)

**Comment by tcassaert** [comment]
Apparently this also applies to stacks. They can also have the same name on the same board.

**Comment by juliushaertl** [comment]
Boards need an id different from the title as different users can of course have a board with the same name. 

> This would make picking a board via API harder, unless there's a really easy (non-techie) way to get the board ID - and would break the work done on using the API to allow emails to be written as cards which has assumed a unique board name.

I agree that for one user it would make sense to make board titles to be unique, but imagine a shared board with the same name? I would rather prefer to allow duplicate names (as it is right now) than adding additional logic for handling name conflicts in sharing.
