### ISSUE TITLE
CSP is broken on Mozilla Firefox, not loading tags correctly

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/deck#1337]
**Describe the bug**
CSP is broken in Mozilla Firefox 70 resulting in a broken UI. Everything works in Chromium-based browsers like Vivaldi/Opera/Chrome.

**To Reproduce**
1. Open a stack in the Deck app in Firefox 70.0.1.

**Expected behavior**
The tags in the stack should be shown correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/10073629/68875639-75bf7780-0703-11ea-81e5-c89c61580ebb.png)

**Client details:**
 - OS:  Debian Buster
 - Browser: Firefox
 - Version: 70
 - Device: Desktop

**Server details:**

**Operating system**: Debian Buster

**Web server:** Apache 2.4

**Database:** Mariadb 10

**PHP version:** 7.3

**Nextcloud version:**17.0.1

**Where did you install Nextcloud from:** Official tar.gz release

#### Browser log
```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). deck.js:38989:6
```

</details>

**Comment by mjanssens** [comment]
Same on NC 16.0.6 with deck 0.6.6 with Firefox 70.0.1
Chromium 78.0.3904.87 works fine

**Comment by mjanssens** [comment]
Just upgraded to NC 17.0.1, including the update to Deck 0.7.0.
Issue is gone now.
