### ISSUE TITLE
Can't rename stack title

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#135]
### Steps to reproduce
1. Add a new stack
2. Edit stack title by clicking on "edit" icon
3. Rename stack title
4. Click <ENTER> or on arrow icon
5. Click on Deck-App-Icon (Nextcloud navigation bar)
6. Choose last board
-> You will see old stack title

**Comment by x9t9** [comment]
I think it is related, or same as #89 .
Also in this case , I can reproduce your issue, but pressing `enter` always does work for me..

**Comment by artemanufrij** [comment]
I think we should hide all icons when board will be renamed - like renaming files in NC, FileExplorer (Dolphin, etc.)
