### ISSUE TITLE
attaching mp4 video file not working

### ISSUE THREAD

**Issue by funky123** [nextcloud/deck#1383]
i tryied to add some mp4 video to deck (after Update NC to latest version 17.01, latest version of deck 0.7.0)

Playing the video isn't possible no errors in logfile.

**Comment by juliushaertl** [comment]
File displaying in handled by the browser, so if your browser doesn't support playing mp4 files there is no way we can support that right now.

**Comment by funky123** [comment]
HM.. it is definitely a bug in deck - adding those mp3 files in the normal NC storage and opening it works easy.
But I just tested at 2 Nextclouds using deck with 2 diferent mp4 files, it does not work! :(

**Comment by acs-ferreira** [comment]
Can reproduce here with NC 17.0.3 and Deck 0.8.0.
Video is played under Firefox, but not Chrome.

Chrome console complains about CSP:

> Refused to load media from 'https://nextcloud.lan/apps/deck/cards/1/attachment/1' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by acsfer** [comment]
#1741 fixes it. Thanks 👍
