### ISSUE TITLE
Feature request: desktop client

### ISSUE THREAD

**Issue by tomdereub** [nextcloud/deck#1414]
Hi,
I'm looking for a kanban solution for use in a small enterprise, and the only thing that's still missing for us with dick is the possibility to have a desktop client that could be working offline, and then synchronize when it comes back online. The objective is mainly to be able to work in the train or in meetings without internet connection.
The android client is now very close to manage to do that, so I just would like to get the same thing on my computer.
Is a desktop client already planned ? If not, could it be planned ? Or maybe this need is to marginal ?
Thanks for the work.

**Comment by juliushaertl** [comment]
Nothing planned into that direction and I don't think this will happen anytime soon as there is still more than enough on our todo list for the web app.

If anyone want's to start a desktop app as a community project feel free to do so, everything needed should be there with the REST API that the android app also uses.

**Comment by rogercreagh** [comment]
Anyone working on this? Specifically a linux (ubuntu) version? Having to fire up a browser and login etc is a bit clunky for desktop/laptop use and requires you to be online which is not always possible.
Alternatively is anyone aware of any Kanban type linux apps that will sync with Nextcloud Deck?
