### ISSUE TITLE
Task end date and time

### ISSUE THREAD

**Issue by serverbroad** [nextcloud/deck#1429]
just requesting to add task ending date and time in future feature  check image attached

![image](https://user-images.githubusercontent.com/25059027/71783996-68798780-2fe6-11ea-8b34-0924e4da7de7.png)

**Comment by juliushaertl** [comment]
Could you describe the scenario for this a bit more in detail? The due date is actually the end date of the task when we send a notification that the task is overdue.

**Comment by serverbroad** [comment]
OK, IF I COULD UNDERSTANT, IT MEANS THAT THE DATE DISPLAYED AND CAN BE PROGRAMMED IS DUE DATE, IF THAT SHOULD BE THE CASE

GOOD JOB, IT IS OKEY BY ME
