### ISSUE TITLE
REST-API: DueDate not saved on create card

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/deck#1430]
**Describe the bug**
Hi, while using the REST-API we can not save the due date on card creation. The date is simply thrown away and null is returned.

**To Reproduce**
1. `curl https://user:password@nextcloud.domain.com/index.php/apps/deck/api/v1.0/boards/98/stacks/481/cards -X POST -H 'OCS-APIRequest: true' -H 'Content-Type: application/json' -d '{"archived":false,"attachmentCount":0,"commentsUnread":0,"description":"test","duedate":"2020-01-04T23:00:34.326Z","notified":false,"order":0,"overdue":0,"stackId":481,"title":"dueDateTest","userId":4,"accountId":2,"localId":60,"status":2}' | jq`
2. see in the answer: `duedate: null`
3. In the UI the date isn't shown, too
4. Using a PUT afterwards setting the due date in the same format works

**Expected behavior**
The duedate should be saved at create

**Comment by desperateCoder** [comment]
Still happening in 1.0.0 alpha nightly. 😉

**Comment by juliushaertl** [comment]
Coming with https://github.com/nextcloud/deck/pull/1648
