### ISSUE TITLE
Edit attached document with Onyoffice

### ISSUE THREAD

**Issue by PelleHanses** [nextcloud/deck#1431]
**Describe the solution you'd like**
Is it possible to use Onlyoffice for editing attached documents in Deck? We are using Onlyoffice to edit documents in Nextcloud Files.

/Pelle

**Comment by juliushaertl** [comment]
This is currently not possible due to the location where deck stores the attachments. This will be possible once https://github.com/nextcloud/deck/issues/564 is implemented.
