### ISSUE TITLE
CSS card sizing to fit screen better

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/deck#1432]
**Is your feature request related to a problem? Please describe.**
Minor layout.

**Describe the solution you'd like**
Sizing of cards to account for all borders / padding / margins.

**Describe alternatives you've considered**
None

**Additional context**
Amending the .stack CSS allows the cards to sit within the screen size as opposed to overlapping the edge.
` .stack {
    width: calc((100% - 40px)/6);
    min-width: calc((100% - 40px)/6);
}`

**Comment by juliushaertl** [comment]
> Amending the .stack CSS allows the cards to sit within the screen size as opposed to overlapping the edge.

This highly depends on the amount of stacks you are using. We probably could just reduce the size a bit to fit 1 or 2 more stacks on a regular full hd screen. Feel free to propose changes directly as pull requests. For visual changes it would be awesome if you could also include screenshots right away that show before/after.

**Comment by a1pilot** [comment]
@juliushaertl The stacks appear to be fixed width. i.e. 5 stacks don't resize to fit the screen. So I don't believe it matters how many you use. I also think the css I showed would compensate for screen sizes as it is percantage based whilst accomodating the fixed items such as padding and margin.

I'll get some screen shots shortly. I'm unable to do pull requests at this time.
