### ISSUE TITLE
Remove border from last card

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/deck#1433]
**Is your feature request related to a problem? Please describe.**
Minor layout.

**Describe the solution you'd like**
Remove the bar from the end (last child) card.

**Describe alternatives you've considered**
None

**Additional context**
`.stack:last-child {
    border-right: none;
}`

**Comment by juliushaertl** [comment]
As discussed some time ago with @jancborchardt iirc we probably should think about moving the card add button to the top of the list to make it always accessible, similar to github projects:

![image](https://user-images.githubusercontent.com/3404133/72180931-8f6dfa00-33e8-11ea-8eda-7106682bf958.png)

**Comment by jancborchardt** [comment]
Yup, what @juliushaertl said – this would fix the actual issue. :)

**Comment by juliushaertl** [comment]
Something for the vue migration

**Comment by a1pilot** [comment]
@jancborchardt just to confirm, moving the "add" button will remove the end border?

**Comment by jancborchardt** [comment]
Yep we’ll do it in the same process. :)

**Comment by juliushaertl** [comment]
![image](https://user-images.githubusercontent.com/3404133/73119409-bdfbe100-3f61-11ea-8c46-42c45db594d0.png)

Closing as this was implemented in the vue branch and is now merged to master
