### ISSUE TITLE
Use Esc key to close card

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/deck#1452]
**Is your feature request related to a problem? Please describe.**
The functionality of Deck already provides two ways of closing a card

- Clicking outside of the card
- Clicking the X of the card

For the first option, you often have to look for an empty spot to click outside the card
For the second option, you have to move the mouse to the X to close the card.

**Describe the solution you'd like**
For speeding up the workflow, it would be good if a keyboard shortcut could close a currently open card. The Esc key would be logical imo.

**Comment by putt1ck** [comment]
If the card is open i.e. you are adding stuff to description etc., what's the next step in the workflow (after closing the card)?

**Comment by armaccloud** [comment]
This could be anything (such as reviewing the full board, opening another board, card).

Maybe good if I illustrate one of my use cases.
I have many tasks defined on my card within the description field, using the [ ] option.
I often review my stacks to prioritize cards and check on the status of the ToDo's within them, which basically goes like this.

Open card - check contents - close card
Open another card - etc.
Keeping perspective is important, closing the card enables me to see the whole board in one overview again when I have a large board. Also, often I want to open a card that on a stack that is hidden behind the card dialogue causing me to want to close the card.

This functionality could be the beginning of optimizing the workflow using keyboard shortcuts (for people like me, who often use keyboard shortcuts.
The working would be exactly the same as the Nextcloud Calendar dialogue, which you can also close using the Esc key, making it consistent with other NC apps.

**Comment by putt1ck** [comment]
OK, useful. I was just thinking aloud to see if there were other keystrokes that might be added to improve workflow beyond closing a card

**Comment by juliushaertl** [comment]
Makes sense to have. I've added it to the keyboard shortcut feature request in https://github.com/nextcloud/deck/issues/46#issuecomment-278278174
