### ISSUE TITLE
add checklist instructions to user documentation

### ISSUE THREAD

**Issue by nielsgeo** [nextcloud/deck#1456]
from experience with users who are new to deck: I suggest to include short info on how to create checklists here:
https://deck.readthedocs.io/en/latest/Markdown/
or here or both?
https://deck.readthedocs.io/en/latest/User_documentation_en/#using-deck
As far as my colleague and me see it is not obvious from current documentation and the links therein that [ ] creates items
Thanks a lot for creating and continuously improving this great free and open trello alternative!

**Comment by juliushaertl** [comment]
Good point, the documentation is built from https://github.com/nextcloud/deck/blob/master/docs/Markdown.md

Pull requests are welcome :wink:

**Comment by ossie** [comment]
Even better would be a toolbar with "usefull" shortcuts to Markdown functionality.
Similar to github here or dokuwiki.

**Comment by juliushaertl** [comment]
See #1561 for editor enhancements
