### ISSUE TITLE
Moving deck duplicates itself

### ISSUE THREAD

**Issue by republicus** [nextcloud/deck#1471]
**Describe the bug**
Moving stack intermittently duplicates itself.

![movestack](https://user-images.githubusercontent.com/47370709/72673734-9a560980-3a3c-11ea-8d56-20a0fa2cfac0.gif)

**Client details:**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.169
 - Device: Desktop

**Operating system**: Debian 10
**Web server:** Apache2
**Database:** MariaDB
**PHP version:** PHP 7.3.11-1
**Nextcloud version:** 17.0.2

**Comment by juliushaertl** [comment]
This should be fixed on master now since we have done a complete revamp of the frontend code including the drag-and-drop behavior.
