### ISSUE TITLE
Tag creation not working inside the tag selector

### ISSUE THREAD

**Issue by wdfee** [nextcloud/deck#1472]
**Describe the bug**
Entered tags do not show up / are not saved.

**To Reproduce**
1. Go to a card's details view
2. Enter a new own tag into tags field
3. click enter
4. an empty label is added to tags field, no tag is added to card

**Expected behavior**
An label with the entered tag is created and added to the card.

**Comment by wdfee** [comment]
Uh, I just figured out that tags have to be created in the board settings, not in the input field of a card. So this is no real bug, but maybe it needs some attention to avoid some confusion like this. There should not be an empty tag created at all. 
It would be nice if a tag could be created in the card's input field, too. But if not, there should be some advice for users who try that.

**Comment by deljones** [comment]
I've just flagged the same thing. On the Android app you can create tags, new tags, it even randomly pics a colour for you. The newly created tag is sync'ed to the web version but it appears you cant create a new tag the same way from the web browser. Unless I've missed somethig?

**Comment by storyjesse** [comment]
> Uh, I just figured out that tags have to be created in the board settings

**Where are the board setting??** Can someone please tell me. I can't find them anywhere. :cry:

**Comment by xdaftcraft** [comment]
Hello,

Follow these steps:
Click here
![image](https://user-images.githubusercontent.com/17741063/95458340-51e7ce80-0972-11eb-9a7c-1fccd3264b31.png)
After "Details..."
![image](https://user-images.githubusercontent.com/17741063/95458432-6fb53380-0972-11eb-8a23-37406532c94f.png)
And on the right
![image](https://user-images.githubusercontent.com/17741063/95458529-93787980-0972-11eb-8cee-a709d697ddd8.png)

You can create tag here. When you create a tag it is assigned and usable only to its own table.

**Comment by Iceman0073** [comment]
Does somebody know if the creation of new Tags is now only avail within board settings or is it a bug that I can't create a new Tag on a specific card?

Many thanks for your help.

**Comment by osm-frasch** [comment]
>     * I also went to the Nextcloud Settings, and under the 'Administration' 'Basic Settings' section found 'Collaborative tags'. I have created several 'Collaborative tags' and set them to be 'Public'. I can assign these tags to Document files but they are not available anywhere in Deck.

==> to create 'Collaborative tags' from the  'Administration' 'Basic Settings' section **so that all registered Users can use this tags in the Deck-App too**. This would be a great enhancement for the Deck-App. So Process-Management is more straight forwards.

**Comment by stefan-niedermann** [comment]
@osm-frasch your comment is already adressed in https://github.com/nextcloud/deck/issues/2316 - let's keep those topics separate 🙂

**Comment by RAYs3T** [comment]
My expectation would be that a new tag is created when clicking on the "+" symbol. But nothing happens instead.
This is confusing and should either be implemented to create a new tag or remove the "+" symbol from the tag search completely.

Steps taken as video: https://nc.edging.tech/s/QzLsm3RAKXtwXKK

**Comment by bru500** [comment]
My Card-Details look a bit different (see screenshot). If I enter a new tag a plus "+" appears. But it is not possible to add an new tag in the web app. With the android app it works fine.

![grafik](https://user-images.githubusercontent.com/40229231/130754623-cc5e372f-21b1-474e-a24d-ba49a5cc41f5.png)

**Comment by fabian727** [comment]
same here, would be nice to have the plus sign add the tag.

**Comment by Shadow-Devil** [comment]
Hi, I would like to work on this issue.
How I see this is, that the [NCMultiselect](https://nextcloud-vue-components.netlify.app/#/Components/NcMultiselect?id=ncmultiselect-1) used [here](https://github.com/Shadow-Devil/deck/blob/316bc29d7011ce5ff9ab810722153769e427116d/src/components/card/CardSidebarTabDetails.vue#L69) is missing the `@Tag` which is documented [here](https://vue-multiselect.js.org/#sub-tagging).
My proposal would be to add following to the NCMultiselect: `@tag="addLabelToBoardAndCard"`
and add the method 
```js
addLabelToBoardAndCard(name){
  const newLabel = {
    title: name,
    color: "ffffff" //TODO
  }
  this.$store.dispatch('addLabelToCurrentBoard', newLabel)
  this.addLabelToCard(newLabel)
},
```
Is there any chance I can test this out without installing a full Nextcloud instance? 
I'm using Windows and would need to use docker or the VM which would take some time to set up.

**Comment by Shadow-Devil** [comment]
For the color of the new label the android app uses [this approach](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/ui/card/LabelAutoCompleteAdapter.java#L37).
I think the webversion should be similar, just select a random color, right?

**Comment by Shadow-Devil** [comment]
Random color could be calculated as following:
```js
randomColor() {
  return Math.floor(Math.random() * (0xffffffff + 1)).toString(16).padStart(8, "0")
}
```

**Comment by juliushaertl** [comment]
This has been merged with https://github.com/nextcloud/deck/pull/4344 thanks to @Shadow-Devil 🎉

**Comment by Shadow-Devil** [comment]
@juliushaertl Thank you for merging🎉
