### ISSUE TITLE
REST-API: Comments support

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/deck#1473]
**Is your feature request related to a problem? Please describe.**
While implementing comments support for the Android-Deck-App (https://github.com/stefan-niedermann/nextcloud-deck/issues/207#issuecomment-569286497), I realized there is no endpoint in Deck for this. The web-UI calls webdav-stuff (remote.php) to make it shown in the activities.
Thats fine so far, but by further investigation i saw some non-REST-compliant calls (PROPPATCH HTTP-method, XML) which made me wish a clean, REST-compliant API as a deck endpoint.

Since we are using SSO for server communication, they also would have to support these exotic HTTP-methods and so on. But this won't change the fact, that I would have to send a JSON/XML mix of entities, I'll never get back in the form I sent them, resulting in very ugly code to make it possible.

**Describe the solution you'd like**
I'd love a clean REST-compliant endpoint, i can POST and PUT comments to, so I wouldn't have to mess around with webdav-stuff.

POSTing or PUTing a simple string to a URL with board+stack+card context woud be all I need.

Nice to have: Since our app has full offline capabilities, i could send the timestamp of the creation as well. This would make the timeline more clear after a sync, if you offline-commented a card in the desert :smile: 

**Describe alternatives you've considered**
Write a bunch of ugly code, breaking my whole code-architecture only to get such a simple task done. But I'd like to omit this very badly.

**Comment by juliushaertl** [comment]
I'll have a look to see if we can wrap a rest api around the servers comments for deck.

**Comment by desperateCoder** [comment]
Thank you so much! Otherwise this would be quite painful for me to implement

**Comment by juliushaertl** [comment]
Done and documented at https://deck.readthedocs.io/en/latest/API/#comments
