### ISSUE TITLE
Mattermost integration: create card from a message

### ISSUE THREAD

**Issue by biva** [nextcloud/deck#1474]
Hello,

I would like to use Mattermost (https://mattermost.com/) together with Nextcloud Deck. The final objective would be to create tasks in Nextcloud Deck by sending a message on Mattermost (assigning the task to a specific person, with a due date, ...)

As a first step, I would like to create (from Mattermost) a new card in Nextcloud Deck. There's an API in Nextcloud Deck (https://deck.readthedocs.io/en/latest/API/#cards). On Mattermost side, I understand that I can use either outgoing webhook (https://docs.mattermost.com/developer/webhooks-outgoing.html) or slash command (https://docs.mattermost.com/developer/slash-commands.html#custom-slash-command).

As I'm a beginner in this field, what do you advise me? Did anybody already try something similar? Would anybody be ready to help because I don't have a lot of skills regarding that :(

Thanks for your support!

I understand that both nextcloud and mattermost teams would be happy to have some kind of integration (https://forum.mattermost.org/t/nextcloud-integration-and-collabora-integration/5645 and https://github.com/nextcloud/server/issues/3202): do you think this idea could be a first step?

**Comment by putt1ck** [comment]
We've done some work with the API for email submission with https://github.com/putt1ck/mail2deck - I'd imagine basically the same except the content is being pulled from Mattermost and the content isn't an email, so would need parsing differently - which would depend on how the Mattermost API exposes a message.

**Comment by juliushaertl** [comment]
I agree with @putt1ck that this is something that the REST API is the way to hook into deck for integrations like that.

Closing this as this is an external integration that would be nice to have, but is out of scope of the deck repo.

If someone is working on this and questions arise, feel free to still just comment here.

**Comment by biva** [comment]
For information, Mattermost is developing a similar feature: https://github.com/mattermost/focalboard/issues/382
