### ISSUE TITLE
missing translation?

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#1484]
Is the translation correct implemented?

https://github.com/nextcloud/deck/blob/ef986842a57724642e89aae5b7446467900c540b/src/components/card/CardSidebarTabComments.vue#L34-L36

https://github.com/nextcloud/deck/blob/ef986842a57724642e89aae5b7446467900c540b/src/components/card/CardSidebarTabComments.vue#L44-L46

https://github.com/nextcloud/deck/blob/ef986842a57724642e89aae5b7446467900c540b/src/components/card/CardSidebarTabComments.vue#L50-L52

https://github.com/nextcloud/deck/blob/ef986842a57724642e89aae5b7446467900c540b/src/components/Controls.vue#L40-L42

https://github.com/nextcloud/deck/blob/ef986842a57724642e89aae5b7446467900c540b/src/components/board/Stack.vue#L60-L62

https://github.com/nextcloud/deck/blob/ef986842a57724642e89aae5b7446467900c540b/src/components/board/TimelineTabSidebar.vue#L09-L11

[Edit: some more links]

**Comment by juliushaertl** [comment]
Thanks for pointing out, there is indeed still a lot missing. We'll look into that. cc @jakobroehrl
