### ISSUE TITLE
Scrum Expansion

### ISSUE THREAD

**Issue by david-kalbermatten** [nextcloud/deck#1485]
## Is your feature request related to a problem? Please describe.
My feature request revolves around the idea of using deck as a 'Scrum Management Software' for smaller projects. So no, it's not a problem, more of a convenience-idea...

### Story Points
for weighing the difficulty/needed man-power for a task, visible on the card

### Sprints
Instead of one board for a project, I propose to have multiple sub-boards for a sprint (a sprint is a development cycle with a set duration: start, end)

### Backlog
In addition to the Sprint-Boards, there should also be a backlog for an entire project, where you can store all of the planned tasks that haven't been assigned to a specific sprint-board

## Describe alternatives you've considered
Since 'Deck' is pretty unique I haven't been able to find an alternative withing the Nextcloud app store

## Additional context
My inspiration for this request stems from **Atlassian's "Jira"** Project Management Software, which is pretty nice, but costly...
And because I'm in the process of learning to work with Scrum for my education.

**Comment by JensUweB** [comment]
I would really love to see more scrum related features implemented! I would additionally to that add epics & subtasks to the list. And instead of some fixed properties, the ability to define custom ticket properties per board.

**Comment by grisoftumut** [comment]
and also it would be great if it had a simple burndown chart in sprint view widget or something
