### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/deck#149]
There are plenty of empty links, such as this one:

`<a ng-if="boardservice.canManage()" ng-click="labelDelete(label)" class="icon"><i class="icon icon-delete" ></i></a>`

Screen readers have trouble accessing such tags. Proper solution is to add `title` attribute as well as `<span class="hidden-visually"><?php p($l->t('Title')); ?></span>` to all icon-links.

**Comment by juliushaertl** [comment]
Fixed by #328
