### ISSUE TITLE
Where are the files dedicated to Deck user data ?

### ISSUE THREAD

**Issue by iSpeeX** [nextcloud/deck#1493]
Hello everyone,
I got a problem with one of my nextcloud install and I don't have access to the UI anymore.
Therefore, I can't export data from the Nextcloud UI and I'm stuck with it.
My question is, whare are the user data of every deck board on the system ?
I'de like to copy/paste everything to my new Nextcloud install, is it possible ?

Thank you,
Best regards.

**Comment by juliushaertl** [comment]
The main data of deck is stored in the database in oc_deck_* tables. The files are located in the data/appdata_[instanceid]/deck directory.
