### ISSUE TITLE
no current nightly builds found

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#1495]
In https://github.com/nextcloud/deck/blob/master/README.md is a link to the nigthly builds, but in https://download.bitgrid.net/nextcloud/deck/nightly/ are only old builds

The latest nightly builds (deck_nightly_2019-07-13.tar.gz and deck_nightly_latest.tar.gz) are from 13-Jul-2019 15:01

**Comment by juliushaertl** [comment]
Yes, there was an issue with the script as we switched to krankerl for building the release package. I didn't finish my adjustments to the nightly build script. Let me see if i can fix that, since nightly builds would be quite nice to get people to test the vue rewrite.

**Comment by jakobroehrl** [comment]
https://github.com/nextcloud/deck/pull/1503
