### ISSUE TITLE
Internationalization of due date calendar

### ISSUE THREAD

**Issue by Salokyn** [nextcloud/deck#1506]
**Describe the bug**
The due date calendar is not translated according to language chosen in profile settings (in French at least)

**To Reproduce**
1. Click on the due date field
2. The calendar appears with first day beeing Sunday and months and days in english (instead of profile language settings)

**Expected behavior**
Follow the user profile regional settings
- Start day of the week
- Week day names
- Month names

**Client details:**
 - OS: Windows, Android
 - Browser IE, FF

<details>
<summary>Server details</summary>

**Operating system:** nextcloud:18-fpm-alpine
**Web server:** nginx
**Database:** MariaDB
**PHP version:** 7.3
**Nextcloud version:** 18
**Deck version:** 0.8.0
**Where did you install Nextcloud from:** Nextcloud Docker repo

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
Nothing relevant

#### Browser log
```
a) The javascript console log
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à eval (« script-src »). angular.js:1291
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). jquery.js:5114:38
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). angular.js:3267
```

</details>

**Comment by reox** [comment]
Same for German (Austrian) Setting.
The Settings Page says "Weeks start on Mondays", however the calendar in Deck starts on sundays.
The Calendar is shown in English too.

**Comment by juliushaertl** [comment]
For reference, this is what we still need to achieve this with the new vue datepicker: https://github.com/nextcloud/server/blob/9a0fa63a5c1f8fa6bb4ce21fd77de55c66aaacbf/apps/files_sharing/src/mixins/SharesMixin.js#L104-L129

**Comment by BKapelari** [comment]
Is this related on this pull?
https://github.com/nextcloud/nextcloud-vue/pull/146

**Comment by juliushaertl** [comment]
For reference, this is what we need to do mainly:

https://github.com/nextcloud/calendar/blob/cd4d4f4607025771ab5408d5b458e98f6dd810d0/src/components/Shared/TimePicker.vue#L62-L69

Added week day names  and month names to the topic as well from #1947

**Comment by D-side** [comment]
Also an issue in Russian, where weeks start with Mondays.
I realize that it's essentially a +1 (and I placed a 👍 on the issue), but I do think knowing affected languages is more helpful to evaluate the impact than merely the number of votes 🙂

**Comment by juliushaertl** [comment]
Yes, this should of course depend on the locale not the language ;)

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/deck/pull/2282
