### ISSUE TITLE
No app name translation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/deck#1509]
**Describe the bug**
There is no translation of the application name in the navigation bar.

**Expected behavior**
Translated app name in the top navigation bar.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/47037905/73380951-339ae080-42c5-11ea-9c41-b744403cc3aa.png)

**Nextcloud version:** (see Nextcloud admin page)
17.0.2
**Deck version:**
0.8.0

**Comment by juliushaertl** [comment]
Yes, that is an issue with the actual name, since it is not descriptive as the others but more a proper name. This has been discussed in #1088 and for now the consense was to keep it. But feel free to continue with proposals in the other issue.
