### ISSUE TITLE
Pin column name to top of the content section

### ISSUE THREAD

**Issue by matchish** [nextcloud/deck#1512]
When we have a long list of cards in a column, after scroll at the end of the list we should scroll up to see the column name

It will be great always to see column names. I would like to pin a column name to the top of the content section

http://prntscr.com/qv02fp

I'm ready to implement and create a pull request.

**Comment by juliushaertl** [comment]
Yes, that is actually how it is now implemented in our vue.js rewrite on master already. If you are curious you can give the nightly builds a try: https://github.com/nextcloud/deck/releases/tag/nightly :warning: Consider those as alpha release, probably not good to run in production yet. :wink:
