### ISSUE TITLE
Mention of user in comment does not work when username contains spaces

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/deck#1515]
**Describe the bug**
Usernames with space character in it cannot be mentioned, probably due to wrong or missing escaping.

**To Reproduce**
1. Create user "Test with space" and user "Test-Login"
2. Login as user "Test-Login", create a board and share it with user "Test with space"
3. Try to mention (@) user "Test with space" in the timeline of a card.

**Expected behavior**
Mentioning works.

**Screenshots**
"Unknown user" is mentioned, the remaining part of the username "with space" is shown as plain text.
If another user "Test" exists, it is mentioned instead of "Unknown user".

**Client details:**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 72
 - Device: desktop

Nextcloud 18.
If necessary, I can provide more details to the server, but I think it is a general problem (I know there are a few problems and it is not generally supported to have usernames containing spaces).

**Comment by putt1ck** [comment]
I'd be tempted to say the bug was allowing usernames with spaces in.

**Comment by Nils160988** [comment]
I would say the same ;)

But now there are instances with usernames containing spaces around and userids cannot be changed (https://github.com/nextcloud/server/issues/8429 or https://github.com/nextcloud/documentation/issues/1774).

**Comment by juliushaertl** [comment]
Yes, files comments also work with spaces in usernames, the plain text then uses `@'user name'`. I'll look into that.
