### ISSUE TITLE
Creating the first table after app installation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/deck#1523]
**Describe the bug**
When creating the first array after installing the app, `{{b.title}}` is visible for a moment. In my opinion, this should be hidden when creating.

**To Reproduce**

1. Install the app.
2. Go to Deck

**Expected behavior**
No `{{b.title}}` code visible.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/47037905/73611849-91da0300-45e6-11ea-8129-4ee1c9447fcf.png)

**Client details:**
Firefox 72.0.2
 - Deck 0.8.0

**Comment by juliushaertl** [comment]
Thanks for reporting, this is already fixed on master with our vue rewrite currently in place.
