### ISSUE TITLE
New Deck Viewer App for MagicMirror

### ISSUE THREAD

**Issue by motey** [nextcloud/deck#1538]
hey guys, just created and released a new Nextcloud Deck viewer app for [MagicMirror](https://magicmirror.builders/)
Have look at https://github.com/motey/MMM_ncdeck
If you give it a try please some feedback at the repo.
Cheers Tim

**Comment by juliushaertl** [comment]
@motey Thanks for sharing, looks very nice. I think we could add some kind integration listing to our documentation, so that people are able to find scripts and external integrations like this a bit more easier.

**Comment by juliushaertl** [comment]
We have a new integrations category in our app store, feel free to register there with a link and some description of the app: https://apps.nextcloud.com/developer/integration/new
