### ISSUE TITLE
Board templates

### ISSUE THREAD

**Issue by JSoko** [nextcloud/deck#154]
Feature request:

In addition to my wish to be able to copy boards (https://github.com/nextcloud/deck/issues/119), I think Templates would also be a nice feature.

Templates should contain the stacks and the labels...

**Comment by artemanufrij** [comment]
How many boards have you in deck?

**Comment by JSoko** [comment]
At the monent: 12

But to document my work and to be able to find things easy, I need weekly or monthly decks...
...so I have the need to produce identical new decks...

**Comment by juliushaertl** [comment]
Unless i don't think we will be adding multiple board templates, a way to define default stacks/labels that will be created on every new board would be nice.

**Comment by pixelipo** [comment]
Wouldn't this issue be solved by #119 ?

**Comment by JSoko** [comment]
@pixelipo 

> Wouldn't this issue be solved by #119 ?

Yes and no...
If copy would work, you can use this fuunction for copying Template-Boards...
...Offering copying and templates would make the system mor professional and clear...

**Comment by juliushaertl** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by risikoflop** [comment]
It's sad to see that this essential feature is not being implemented, when there have been feature requests since 2017.

**Comment by niftylouie** [comment]
This feature is absolutely needed.  Add templates or Copy or both, and it  will become a web based project management solution overnight.   I'm an architect licensed in two states who plans to use this system for collaborative project management.

**Comment by putt1ck** [comment]
https://github.com/nextcloud/deck/pull/1221

**Comment by KeithCu** [comment]
Copying a template and making it a card isn't difficult. The important / killer feature is the ability to update the template, and have all existing cards reflect the changes.

**Comment by zamantech** [comment]
Any News,
or it's available for just enterprise?

**Comment by putt1ck** [comment]
Like https://github.com/nextcloud/deck/issues/119 ?
