### ISSUE TITLE
Mail-Reminder for "Due Date"

### ISSUE THREAD

**Issue by mcteefax** [nextcloud/deck#1548]
In Nextcloud "activities" it is possible to activate Mail-Reminders for several DecK-activities. But I didn't find a possibility to get an Mail-Reminder, when a "Due-Date" is reached or when a card is assigned to me. So i have also look via browser in Deck.

For me it doesn't matter, if I would have to activate it in "activities" or anywhere in Deck.

**Comment by juliushaertl** [comment]
Duplicate of https://github.com/nextcloud/deck/issues/1202
