### ISSUE TITLE
Feature request: Tree-like dependancy of decks

### ISSUE THREAD

**Issue by c4tb3rt** [nextcloud/deck#1550]
**Problem**
I now share multiple decks with the same people (for different projects within a programme for example). I have to share each deck individually and can't move cards from one deck to the next.

**Suggested solution**
A tree-like dependancy of decks, where the main tree with its branches can be shared at once and cards can be moved from one deck to the next.

**Describe alternatives you've considered**
Creating a folder where you can put all decks that you want to keep together and being able to share a complete folder with others.

**Comment by juliushaertl** [comment]
This sounds like a nice feature, but there are no plans to implement something like that right now. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
