### ISSUE TITLE
Description update activities are too verbose and HTML tags are displayed to users

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/deck#1557]
**Describe the bug**
Incorrectly displayed content of the card description change in "Activity" for the user.

**To Reproduce**

1. Create a board.
2. Add stack.
3. Add card.
4. Add a card description.
5. Go to "Activity" Nextcloud.

**Expected behavior**

**Screenshots**

![obraz](https://user-images.githubusercontent.com/47037905/75228347-47e0d900-57b0-11ea-8b9a-364ebdd1cc96.png)

**Client details:**
   Win10
   Firefox
   73.0.1

**Nextcloud version:** (see Nextcloud admin page)
18.0.1

**Deck version:**
0.8.0

**Comment by juliushaertl** [comment]
Non-functional diff display was removed now with 54536eff93a4a8676deea27dc32744993f21db26
