### ISSUE TITLE
Mobile: improve drag-and-drop

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#156]
Follow up of #35

Idea:
> Instead of having to scroll horizontally through the stacks, just put them on top of each other in mobile mode so that you can scroll vertically.

- [x] Align stacks horizontally on mobile
- [ ] Make drag to scroll work also inside the stacks container

**Comment by artemanufrij** [comment]
may be like this:
![screenshot_20170524_204630](https://cloud.githubusercontent.com/assets/16517095/26420160/1ab381a6-40c2-11e7-90af-a21e3e476c0f.png)

**Comment by e-alfred** [comment]
I can't move a card to an empty stack. No rectangle is shown by hovering a card over the stack like in stacks with at least one card.
