### ISSUE TITLE
Integrate Nextcloud Text as a markdown editor

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#1561]
As discussed with @jakobroehrl we should make use of the capabilities that Nextcloud Text offers as a nicer way of markdown editing.

To achieve this it would be great if we can extract the actual editor parts of text into a dedicated library that can then be used by apps. As a first step this could be done without collaborative editing, since that would either require a custom backend in deck or extending the text app to support other sources than files.

~The basic entry point would be some refactored version of the [EditorWrapper](https://github.com/nextcloud/text/blob/master/src/components/EditorWrapper.vue), but we need to make sure that the [collaboration plugin](https://github.com/nextcloud/text/blob/master/src/components/EditorWrapper.vue#L311-L323) and [sync service handling](https://github.com/nextcloud/text/blob/master/src/components/EditorWrapper.vue#L263-L279) can be injected from outside (by the text app) if needed.~

Ongoing effort on moving the editor parts into a shared npm library: https://github.com/nextcloud/text/pull/2278

**Comment by ShogunWeb** [comment]
As a simple user, I would greatly appreciate to have the kind of WYSIWYG interface that Nextcloud Text offers. Well, any kind of "styling" menu would be great to me, as I'm not very familiar to markdown notation...

**Comment by putt1ck** [comment]
V1 (currently in beta) provides a link to Markdown notation, which is really easy once you've used it a few times. Ends up here: https://commonmark.org/help/

**Comment by joreiff** [comment]
Currently, we have the ability to toggle between the fully rendered and the plain text version (with some markup) of the description. This has the advantage that it is easy to copy/paste the description to/from other apps supporting markdown, e.g. Tasks. Would Nextcloud Text integration remove this separation? From https://github.com/nextcloud/text/issues/439 it seems like Text will not have a source view anytime soon. Or would it still be possible to have a raw view?

**Comment by mgielda** [comment]
I second @joreiff 's question - e.g. the files_markdown app is actually very cool in that it has this source editing with preview setup, and the lack of such capability in Text is a huge blocker for our use case. We believe there is huge value in plain text (ability to diff using simple tools, version in git, simple interop with many other tools), and collaborative editing of plain text would be ideal, as it transcends many use cases (including not only simple documents but also e.g. technical documentations). So integrating the Nextcloud Text approach (with the "prosemirror cannot into plaintext" limitation) into more apps actually breaks them from our point of view...

**Comment by mgielda** [comment]
Don't get me wrong of course - the Nextcloud Text app is awesome work, but the absolutely-no-plaintext limitation is severe for many of the awesome potential use cases. Now as long as Text is a standalone app that I can just exchange for other stuff, it's really cool. But if the limitation starts running across many of the Nextcloud apps, it starts to be a problem...

**Comment by juliushaertl** [comment]
Well, it is mainly an issue that there was no better way for rich formatting when the markdown support to deck was added. While I personally am a big supporter of Markdown I don't think that a description field should be based on a rather technical syntax but instead use a proper visual editor that any user is able to quickly work with.

**Comment by mgielda** [comment]
Well of course I don't deny the value of WYSIWIG in general, but it's definitely possible to have the cake and eat it, i.e. give people a nicely rendered output but also the ability to modify the markdown source. Netlify CMS has an example - they just have a switch between Markdown and Rich Text.

See: https://cms-demo.netlify.com/#/collections/posts

Click on any of the posts, you will see the ability to switch between the modes seamlessly.

**Comment by witzker** [comment]
Pls don't waste time with the editor!

It's mandatory to have a User-friendly editor as I have no rocket scientists in my team! (maybe I'm not The only one?)
Its also mandatory to be able to insert screenshots for productive Description!
Without having to tinker around to get finally  a meaningful description 
This is killing the creativity on the task to-do!

Why not take an editor like This here on GitHub?
If one does not need the features he will simply not use it!
Give them the opportunity to edit the displayed features like e.g. in different Joomla editors.
As described above if you want to take care of your markdown junkies look at the editor on Reddit
simply switch to markdown or not.

And pls. Hurry up with your decision (There are plenty of other fish in the sea) a lot of Free Self-Hosted alternatives are already perfect in managing kanban with user-defined fields & subtasks etc.
They can easily be implemented in Nextcloud via External sites.

Further pls. Do not ignore the fact that Deck & Tasks still don't work together well and 2 apps are needed just to have the functionally of a list view of deck cards & maybe subtasks if working!

What do you think?

**Comment by compgeniuses** [comment]
Whats Happening Here?

**Comment by reox** [comment]
Nice!
Does this by chance also solve #533 ?

**Comment by juliushaertl** [comment]
Not immediately, but it did some preparation for that ;)
