### ISSUE TITLE
Automatic card creation via email

### ISSUE THREAD

**Issue by mrchainman** [nextcloud/deck#1571]
**Is your feature request related to a problem? Please describe.**
No, it would just be great to have

**Describe the solution you'd like**
Now that nextcloud 18 has released flow, maybe it could be integrated into Deck to automatically create a card when an email arrives in a certain account INBOX

**Describe alternatives you've considered**
Alternatives would be to use a milter on the mailserver.

**Comment by juliushaertl** [comment]
Duplicate of #392
