### ISSUE TITLE
[discussion] Create a list view?

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/deck#1592]
As discussed here https://github.com/nextcloud/deck/pull/1319 the deck and tasks topics are getting  very close into the same territory.

**Possibility 1:**
Link deck and tasks, store the same data within calDAV

**Possibility 2:**
there are a lot of the same functionality in Deck and Tasks (eg: assign to user, share with user, group, comments, attachments, tags, activity, due, filter, sort, ...)
Maybe it's easier to create a list view in deck then to duplicate and maintain the hole functionality in two apps.

**Comment by juliushaertl** [comment]
I think we came to the conclusion in various discussions that we aim for reusing the tasks app together with https://github.com/nextcloud/deck/issues/15
