### ISSUE TITLE
We should remove unused css code

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#160]
For more transparency

**Comment by artemanufrij** [comment]
request is already merged

**Comment by pixelipo** [comment]
@artemanufrij stll some work on this task. I will make more PRs under the same issue, ok?

**Comment by artemanufrij** [comment]
@pixelipo: Sure!

**Comment by juliushaertl** [comment]
Let's remove that from the 0.2 milestone, since this is something ongoing and nothing that is really required for now. :wink:

**Comment by artemanufrij** [comment]
fixed in #219
