### ISSUE TITLE
All boards gone after update NC 17.0.4 to NC 18.0.2

### ISSUE THREAD

**Issue by jgrete** [nextcloud/deck#1604]
### Steps to reproduce
Update from 17.0.4 to 18.0.2
Don't know if this is essential. I havn't  used the app for month now (maybe since last spring)

### Expected behaviour
No Boards deleted

### Actual behaviour
All boards are gone. The mobile Deck app still holds all boards but there's no possibility to upload/sync with the server app

## Server configuration detail

**Operating system:** Linux 4.12.14-lp151.28.36-default #1 SMP Fri Dec 6 13:50:27 UTC 2019 (8f4a495) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.3.20

**PHP version:** 

7.2.5
Modules loaded: Core, date, libxml, pcre, filter, hash, Reflection, SPL, session, SimpleXML, standard, xml, mysqlnd, apache2handler, apcu, bz2, ctype, curl, dom, mbstring, fileinfo, gd, gmp, iconv, imagick, intl, json, exif, mysqli, openssl, pcntl, PDO, pdo_mysql, pdo_sqlite, posix, readline, redis, smbclient, sqlite3, tokenizer, xmlreader, xmlwriter, zip, zlib, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.2 - 18.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 17.0.4

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - analytics: 2.1.1
 - announcementcenter: 3.7.0
 - appointments: 1.1.5
 - apporder: 0.9.0
 - bookmarks: 2.3.4
 - breezedark: 18.0.8
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.2
 - camerarawpreviews: 0.7.3
 - checksum: 0.4.4
 - circles: 0.18.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - cookbook: 0.5.7
 - dashboardcharts: 0.1.3
 - data_request: 1.5.0
 - dav: 1.14.0
 - deck: 0.8.0
 - drawio: 0.9.5
 - emlviewer: 0.0.5
 - end_to_end_encryption: 1.4.0
 - event_update_notification: 1.0.1
 - external: 3.5.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.0
 - files_downloadactivity: 1.7.0
 - files_external: 1.9.0
 - files_fulltextsearch: 1.4.1
 - files_linkeditor: 1.0.13
 - files_lock: 0.8.1
 - files_markdown: 2.2.0
 - files_mindmap: 0.0.18
 - files_pdfviewer: 1.7.0
 - files_retention: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trackdownloads: 1.7.0
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - flowupload: 0.1.8
 - fulltextsearch: 1.4.1
 - fulltextsearch_elasticsearch: 1.5.0
 - gpxedit: 0.0.13
 - gpxmotion: 0.0.11
 - gpxpod: 4.1.1
 - groupfolders: 6.0.1
 - groupquota: 0.1.2
 - guests: 1.4.1
 - hsts: 0.4.0
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - keeweb: 0.6.2
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.3
 - maps: 0.1.6
 - metadata: 0.11.1
 - nextbackup: 19.12.1
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.5
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocdownloader: 1.7.6
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - phonetrack: 0.6.2
 - photos: 1.0.0
 - polls: 1.3.0
 - preferred_providers: 1.6.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - qownnotesapi: 20.1.0
 - quicknotes: 0.2.3
 - quota_warning: 1.7.0
 - ransomware_protection: 1.6.0
 - recommendations: 0.6.0
 - registration: 0.4.7
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - sharingpath: 0.1.1
 - socialsharing_diaspora: 2.0.0
 - socialsharing_email: 2.0.0
 - socialsharing_twitter: 2.0.0
 - spreed: 8.0.5
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - talk_simple_poll: 1.1.0
 - tasks: 0.12.1
 - telephoneprovider: 1.0.3
 - terms_of_service: 1.4.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_admin: 2.0.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_email: 1.0.1
 - twofactor_gateway: 0.15.1
 - twofactor_nextcloud_notification: 2.2.0
 - updatenotification: 1.8.0
 - video_converter: 0.1.3
 - viewer: 1.2.0
 - workflow_pdf_converter: 1.3.1
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - audioplayer
 - audioplayer_editor
 - dropit
 - encryption
 - files_antivirus
 - files_readmemd
 - music
 - printer
 - quickaccesssorting
 - ransomware_detection
 - sharerenamer
 - social
 - uploaddetails
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxxx.dedyn.io",
        "cloud.fritz.box",
        "fritz.box"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.2.2",
    "overwrite.cli.url": "http:\/\/xxxxxx.dedyn.io\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "has_rebuilt_cache": true,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** Kubuntu eoan

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by juliushaertl** [comment]
Please check your nextcloud and browser log for errors. If the app still shows the boards i would assume there is just an issue with loading the boards from the API in the web app.

**Comment by jgrete** [comment]
No errors nor suspicious entries.
Mobile app and NC App seem to be disconnected. No change on either platform is synced so it looks like  both apps are completely unrelated (they aren't, I have to sign in with the mobile app).
Absolutely no clue how this could happen. Is it possible to save the boards on my mobile? I would try to reimport on a fresh installed deck app on my mobile

**Comment by jgrete** [comment]
Do you need more info? Please tell me how to provide

**Comment by juliushaertl** [comment]
Can you check your database if the information is still present there?

**Comment by jgrete** [comment]
I've deleted my mobile app. It  would be a good thing to have an export function on both the NC app and mobile app.
After reinstallation the mobile app both apps are synching, but there's nothing left on the NC app from the former decks. I found only data belonging to the actually existing decks.
I think we could close this - no solution but also no chance to find one
