### ISSUE TITLE
Confirmation screen when deleting a Board

### ISSUE THREAD

**Issue by xXGorgonzolaXx** [nextcloud/deck#1611]
Hello, 

I am trying to build a confirmation screen ("Cancel" or "OK")  which appears when deleting a board.
My issue is that i have problems identifying where i have to edit the code.

As you might have guessed by this question, i am a beginner and im just trying to get a feeling for editing someone elses work to apply my own ideas.
So any help you can give me is much appreciated.

Some pointers i think i need are:

- How do you orient yourself in Deck
- What basic knowledge do you recommend to learn to implement this feature

PS: i hope it's fine to ask this question here

**Comment by gitalexa** [comment]
nice idea! we vote for it!

**Comment by juliushaertl** [comment]
@xXGorgonzolaXx Sorry for the delayed reply, I missed that issue. Here are some pointers:
- We use vue and vuex so I recommend getting familiar with those first a bit, before diving into the deck code
- The delete action in the navigation is defined in https://github.com/nextcloud/deck/blob/dc904f421c50d281541fd9f82121d7295029af9b/src/components/navigation/AppNavigationBoard.vue#L190-L205
- It should ask for the confirmation before calling the deleteBoard api method
