### ISSUE TITLE
UI - Tooltip doesn't hide when pressed

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/deck#1612]
**Describe the bug**
"Show/hide archived cards" tooltip should hide automatically but it doesn't. Page refresh is required

**To Reproduce**
![tooltip](https://user-images.githubusercontent.com/36133540/77233991-8731f800-6bab-11ea-9e59-cf518fb85c4a.gif)

**Client details:**
Deck 0.8.0 on NC 17.0.3

**Comment by juliushaertl** [comment]
Should be fixed in the upcoming release with the mgiratino to v-tooltip.
