### ISSUE TITLE
What am I doing? Across boards?

### ISSUE THREAD

**Issue by ilippert** [nextcloud/deck#1630]
When I approach the deck app, at first I see a list of my boards (with the owner), for my different projects.
I wonder: could we add a column? For instance a column of list cards of "doing" decks. 
that would allow me to see at one glance where I am across various projects.

Or, specifically: for each board, one deck could be optionally&manually marked as "show on overview page"; and then the first/top card of that deck is shown on the overview page.

**Comment by putt1ck** [comment]
Like a filter e.g. #1507 ?

**Comment by ilippert** [comment]
Well, yes, it is like a filter, but, I guess it employs two filters:

1. filter for a relevant deck (e.g. a deck marked as "show on dashboard/start page");
2. filter for the top card on that deck

Then, add a column at the dashboard/startpage and show for each board the top card's name.

Required would be

- option to mark a deck as "show on dashboard/start page"
- option to add a column on that dashboard/start page (however that's called)

**Comment by jakobroehrl** [comment]
Would this solution be helpful?
https://github.com/nextcloud/deck/pull/1319

**Comment by ilippert** [comment]
https://github.com/nextcloud/deck/pull/1319 seems quite helpful. I would argue that not everybody is using due dates (I simply do not need these in my project management).

But the https://github.com/nextcloud/deck/pull/1319#issuecomment-577861069 suggestion comes close to what I would really like to see - with the difference that I was not looking for the filter by due dates but a filter of what is currently worked on (in the kanban logic the "doing" cards (all of them, or simply the top "doing" card).

**Comment by ilippert** [comment]
Just to add an example. I work on these projects/boards (with cards)
product 1 (card 1, card 2, card 3*)
product 2 (card 1, card 2*, card 3)
product 3 (card 1, card 2, card 3*)

in each board I mark a card with a tag or with a stack* as currently worked on.

Now an overview of all those marked cards would be helpful:

list of *
product 1      card 3    due date
product 2      card 2    due date
product 3      card 3    due date

**Comment by juliushaertl** [comment]
The main issue i see with this is that we currently have no way to define which column is the todo one and this is rather specific to your use case. I think a general approach of a card overview with upcoming/important ones is more the way to go as aimed for in #1319.
