### ISSUE TITLE
No activities in 1.0.0-alpha1

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#1632]
**Describe the bug**
No Activities are displayed

**To Reproduce**
1. Create card
2. modify it (add labels, add description and so on)
3. Go to card details and view activity
4. See nothing

**Expected behavior**
Activities from step 2 should be displayed

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4741199/77404968-ca11ec80-6db2-11ea-9807-37433d887505.png)

**Client details:**
 - OS: [e.g. iOS] Any
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] Latest ESR
 - Device: [e.g. iPhone6, desktop] Notebook

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 18.0.3

**Where did you install Nextcloud from:** Fresh downloaded .zip-file

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

#### Browser log

`GET` `https://example.com/ocs/v1.php/apps/activity/api/v2/activity/filter?format=json&type=deck&since=0&object_type=deck_card&object_id=243&limit=50`

```json
{
    "ocs": {
        "meta": {
            "status": "failure",
            "statuscode": 998,
            "message": "Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.\n"
        },
        "data": []
    }
}
```

**Comment by putt1ck** [comment]
Confirmed in beta 1. Note this seems to cause issues with activity tracking in general; the activities view never completes loading for "all", "by you", "by others" and "deck", but loads fine for anything with no Deck component.

**Comment by juliushaertl** [comment]
So this was actually an issue with the release bundle, will be fixed in beta 2 with https://github.com/nextcloud/deck/commit/1308f93a1faf2f1c23829a95ebd90325baaa6457
