### ISSUE TITLE
Ask for deletion on board delete

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#1633]
A board deletion is a very destructive action and therefore should have a confirmation required before performing it. In general Undo should of course also be supported.

**Comment by juliushaertl** [comment]
Maybe something for you @jakobroehrl :wink:

**Comment by Kakiaki** [comment]
#1611 Someone might be already working on it. At least he asked nicely how to do so :)

**Comment by juliushaertl** [comment]
Thanks, I did miss that somehow. Let's continue at #1611 then.
