### ISSUE TITLE
Option to create a Link to a Nextcloud-File in an card

### ISSUE THREAD

**Issue by AsumYT** [nextcloud/deck#1634]
**Is your feature request related to a problem? Please describe.**
No, just a Feature Request.

**Describe the solution you'd like**
An addition to the `Description` or `Attachment` Option, to link a file or folder that is saved in a Nextcloud with an card.
And maybe if i click on that linked file/folder, i will be redirected to that file/folder.

PS: Sorry for my bad English.

**Comment by jakobroehrl** [comment]
Is that would you mean?
https://github.com/nextcloud/deck/issues/564

**Comment by AsumYT** [comment]
Oh, yeah that's what i mean.

Sorry, i haven't found that Feature Request.

**Comment by jakobroehrl** [comment]
No problem, so I will close this Issue for now.
