### ISSUE TITLE
Images for Cards

### ISSUE THREAD

**Issue by ttytm** [nextcloud/deck#1635]
Images tell more then thousand words. I would love to have the possibility to add an image to my cards that is displayed with the card on the board. It would make it more attractive and easier to get an overview for my users.

Here is a Screenshot how it could look.

![FireShot Capture 132 - trello1 jpg (1999×1087) - www blogdumoderateur com](https://user-images.githubusercontent.com/34311583/77793645-bb555f00-706a-11ea-90ec-af4365a9fdd5.jpg)

best regards,
Toby

**Comment by juliushaertl** [comment]
cc @jakobroehrl Since we talked about this already.

The main concern that is currently blocking such a limitation is, that we don't have any preview generation with our current way of storing the files in appdata. So either we need to wait for #564 or add some additional logic to generate previews for appdata files, but I would definitely prefer the first.

**Comment by tobealive** [comment]
oh i see. Looks like 564 is a big one for some issues. Unfortunately i'm missing the knowledge to offer some good help :/

**Comment by juliushaertl** [comment]
Yes, we plan to tackle #564 after our vue migration (1.0 release) is finished, but no ETA for that yet.

**Comment by tm9k1** [comment]
Hi, sorry for the necroposting, but is this being worked on?

**Comment by ArtyRivera** [comment]
Checking back in on this item -- still a popular request from my team, which is how I found this post. Curious if there's an ETA on this and/or if there's any way I or my team could help to contribute to this?

**Comment by gri38** [comment]
Hello. +1.
Thanks for your great project !

**Comment by t-maes** [comment]
I also think this could be a great enhancement of the card view, in brief, a thumbnail of the first attached file. 
Isn't there a way to put a feature request on it, it seems so obvious?

**Comment by bueroblanko** [comment]
any update here?

**Comment by Gobytego** [comment]
how is the mobile app doing this feature?? maybe use the same implementation? i would also like to see this.

**Comment by juliushaertl** [comment]
There also has been some work started in https://github.com/nextcloud/deck/pull/2858 already, but discontinued due to lack of time. Anyone interested can of course pick this up again.

**Comment by jszeibert** [comment]
I would like to revive this discussion as I really like the CoverImge feature from the mobile app.
Above you can find a draft of a possible/ simpler implementation I did a while ago for my own nextcloud setup and just ported and improved slightly to work with stable26.

My goal with this draft PR would be to collect feedback and bepending on that, maybe improve/ complete my imprementation to a proper PR.

Would love to hear your thought of my code.

**Comment by t-maes** [comment]
Hi,
I don't know how to test. 
For the code itself, I think I don't have the level to juge it.
I'm happy to know you work on it
