### ISSUE TITLE
addtional add stack button at the main area

### ISSUE THREAD

**Issue by dassio** [nextcloud/deck#1655]
**Is your feature request related to a problem? Please describe.**
the first time created an board, i don't know how to create a stack , the button on the right upper side is too small.  the grey color make it also too easy to ignore 

**Describe the solution you'd like**
the add stack button should be at  where you can create the stack:
- if empty board, put the new stack button at the first column
- if there are already a stack, move the create stack to the  second column  

**Describe alternatives you've considered**
make the add stack  button more noticeable by changing it's color

**Comment by juliushaertl** [comment]
> if there are already a stack, move the create stack to the second column

We had this in an earlier version but this was taking up space that was not really used and required the users to scroll if there were some stacks on a board and the new stack button was to wide on the right.

> if empty board, put the new stack button at the first column

Totally, this would really improve the first use experience.
