### ISSUE TITLE
0.8.1 - After update to latest version, deck is completly broken

### ISSUE THREAD

**Issue by jgrete** [nextcloud/deck#1668]
Updated to latest version and getting this:
![grafik](https://user-images.githubusercontent.com/14105933/78820278-ccda2780-79d7-11ea-9575-7edde9017ea8.png)

No operations possible, no boards, nothing...
Deck is developing - but in the wrong direction...

**Comment by crdxfire** [comment]
same problem here

**Comment by eachtime** [comment]
exactly the same issue here

**Comment by karlbeecken** [comment]
same here

**Comment by SteffnVo** [comment]
same here :-(

**Comment by karlbeecken** [comment]
no idea if it helps, but <a href="//imgur.com/a/bkKFP0a">here</a>'s the dev console output

**Comment by eachtime** [comment]
I have two warning in the browser console :
```
Loading failed for the <script> with source “https:/my.nextcloud.instance/apps/deck/js/build/collections.js?v=443968a6-38”.
Loading failed for the <script> with source “https://my.nextcloud.instance/apps/deck/js/build/deck.js?v=443968a6-38”.
```

**Comment by SIN3R6Y** [comment]
Can confirm on 18.0.3

**Comment by juliushaertl** [comment]
Sorry for the inconvenience, aparently the exclude list in the build script was to wide so it was missing the javascript bundles. A new release was pushed out and should be available from the app store soon.

**Comment by crdxfire** [comment]
👍

**Comment by Dubidubiduu** [comment]
updated, everything was broken, went into maintenance, then switched it off logged in, updatet to 0.8.2., now it seems to work again, but all the shared decks aren't shown anylonger, which are heavenly used?! @juliushaertl

**Comment by juliushaertl** [comment]
@Dubidubiduu I could not reproduce this and also works fine on my personal instance. Please open a new issue with some more details and check the browser console and Nextcloud logs.
