### ISSUE TITLE
Empty Deck - Shares broken - propably connected to update

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#1671]
### Steps to reproduce
1. I updated Deck to 0.8.1 (& Group folders to 6.0.5) by web and got into the maintenance mode, waited a short period of time, deactivated that mode, also tried repair, however got back into nc, deck broke like in #1668.
2. I then updated Deck to 0.8.2, go to Deck.

### Expected behaviour
See all the decks shared with me.

### Actual behaviour
Just see my personal-deck.

Few further information:
A master user still owns the boards. With this user the shares are still shown, just don't work anylonger. With this user I'm able to recreate the group shares and they work again, it's just a bunch of work.
Could be connected to User and Group SQL Backend, as it seems that there isn't a problem for an old local user.. Also see the propably connected nextcloud log

Outcommented these for debugging:
12   <IfModule mod_env.c>
 13     # Add security and privacy related headers
 14     # Header always set Referrer-Policy "no-referrer"
 15     # Header always set X-Content-Type-Options "nosniff"
 16     # Header always set X-Download-Options "noopen"
 17     # Header always set X-Frame-Options "SAMEORIGIN"
 18     # Header always set X-Permitted-Cross-Domain-Policies "none"
 19     # Header always set X-Robots-Tag "none"
 20     # Header always set X-XSS-Protection "1; mode=block"
 21     # SetEnv modHeadersAvailable true
 22   </IfModule>

## Server configuration detail

**Operating system:** Linux 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64 #1 SMP Wed May 29 04:37:40 EDT 2019 x86_64

**Webserver:** LiteSpeed (litespeed)

**Database:** mysql 10.2.31

**PHP version:** 

7.4.4
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, litespeed, apcu, bcmath, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, exif, mysqlnd, mysqli, odbc, PDFlib, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, Phar, posix, pspell, soap, sockets, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [error_log] => Array
                        (
                            [expected] => 
                            [current] => 0f9a8e7951ff00381af5f9bffb37a353012887a75327ae29962d0c0237cf8ae208ca2c0c3f8f0fee3810f4522fc2bb55f5ee30df03ffe17bf8d40171126bd833
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.9.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.2
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - dav: 1.14.0
 - deck: 0.8.2
 - event_update_notification: 1.0.1
 - external: 3.5.0
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_markdown: 2.2.0
 - files_pdfviewer: 1.7.0
 - files_readmemd: 1.1.3
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - groupfolders: 6.0.5
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.4
 - metadata: 0.11.1
 - news: 14.1.3
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocr: 6.0.29
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - polls: 1.3.0
 - previewgenerator: 2.3.0
 - printer: 0.0.1
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.7
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - talk_simple_poll: 1.1.0
 - telephoneprovider: 1.0.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - user_sql: 4.4.1
 - viewer: 1.2.0
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - appointments
 - documentserver_community
 - drawio
 - encryption
 - files_automatedtagging
 - files_external
 - files_mindmap
 - firstrunwizard
 - nextcloud_announcements
 - passman
 - passwords
 - photos
 - ransomware_protection
 - recommendations
 - sharerenamer
 - side_menu
 - socialsharing_email
 - timetracker
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.sozis-tiere.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "tempdirectory": "\/home\/xxx\/nc\/tmp",
    "default_language": "de",
    "force_locale": "de",
    "overwrite.cli.url": "https:\/\/cloud.xxx.de\/",
    "lost_password_link": "https:\/\/xxx.de\/yyy\/?action=lostpassword",
    "dbtype": "mysql",
    "version": "18.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "defaultapp": "apporder",
    "loglevel": 0,
    "filelocking.enabled": true,
    "debug": false,
    "log_type": "file",
    "skeletondirectory": "",
    "enable_previews": true,
    "preview_max_x": 800,
    "preview_max_y": 800,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "updater.release.channel": "stable",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "app_install_overwrite": [
        "apporder",
        "files_readmemd",
        "polls",
        "printer"
    ],
    "integrity.check.disabled": false
}
```
</details>

**Are you using an external user-backend, if yes which one:**  User and Group SQL Backends 4.4.1

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Error	core	TypeError: Argument 3 passed to OCA\Deck\Activity\DeckProvider::setSubjects() must be of the type array, null given, called in /home/xxx/subdomains/cloud/apps/deck/lib/Activity/DeckProvider.php on line 153	
2020-04-09T11:01:22+0200
Error	PHP	Undefined variable: params at /home/xxx/subdomains/cloud/apps/deck/lib/Activity/DeckProvider.php#140	
2020-04-09T11:01:22+0200
Error	PHP	Module 'sqlite3' already loaded at Unknown#0	
2020-04-09T11:01:16+0200
```
</details>

<details><summary>Browser log</summary>

Firefox javascript:
Content Security Policy: Die Direktive 'child-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'worker-src' zum Kontrollieren von Workern bzw. die Direktive 'frame-src' zum Kontrollieren von Frames.
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. addStylesClient.js:220:17
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 2 globals.js:66:15
@babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning. index.js:10
Proxying an event bus of version 1.1.2 with 0.2.1 nextcloud-vue-collections.js:1:15836
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src"). angular.js:1291
oc_requesttoken is deprecated: use OC.requestToken instead globals.js:66:15
oc_current_user is deprecated: use OC.getCurrentUser().uid instead globals.js:66:15
oc_isadmin is deprecated: use OC.isUserAdmin() instead globals.js:66:15
oc_defaults is deprecated: use OC.theme instead globals.js:66:15
oc_isadmin is deprecated: use OC.isUserAdmin() instead globals.js:66:15
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 25 globals.js:66:15
md5 is deprecated: please ship your own, this will be removed in Nextcloud 20 5 globals.js:66:15
</details>

**Comment by Dubidubiduu** [comment]
So, yesterday I updated to 1.0.0. and everything was fine. Then today I had 500 internal server error on my cloud, from the morning till the evening, changed a few settings (.htaccess, config, tried a few repair commands by occ etc., deactivated few apps (also deck!)), nothing helped. Haven't found anything in the logs...

Then somehow, it (nc) worked again, I then updatet from 18.0.3 to 18.0.4 ..

And now I checked, the shares are broken AGAIN.

**Comment by juliushaertl** [comment]
A 500 error should definitely cause some logging :/

Did you use the beta releases of deck 1.0 on that instance and/or are you using the android app?

**Comment by Dubidubiduu** [comment]
I do some testing and syncing with android app, downloaded via f-droid. More on this next time, I guess.

**Comment by juliushaertl** [comment]
I'll close this for now since we cannot reproduce and there are no additional hints on what is going on here. Feel free to reopen with additional information.
