### ISSUE TITLE
v1 beta 1: Settings menu opens in "hard to use" state

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#1675]
When clicking on the Settings button bottom of the left bar the box that appears explains only what an option is but doesn't clearly show (a) the options available related to it nor (b) that there are no other options beyond limiting Deck functions by group. Primary cause appears to be the drop down list of available groups going up instead of down and layering underneath the buttons and board list above

In 0.8.2 the settings are clearer, specifically because the group drop down drops down not up.

Browser used was Firefox 72.02

**Comment by juliushaertl** [comment]
> specifically because the group drop down drops down not up.

Agreed, that should open downwards or not be overlayed by the settings header.
