### ISSUE TITLE
v1 beta 1: card ordering changes on reload after adding new card

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#1677]
When reloading a board after adding a card the ordering of cards in lists changes, possibly randomly.

To reproduce: open board with existing cards in a list. Add a new card to a list, which appears at the bottom of the list. Reload the board in some way, card ordering in the list has changed with some degree of randomness (more specifically I can't see a pattern in where cards then end up in the list). Lists that did not have new cards added appear unchanged)

Expected behaviour is the cards remain in the order last used as per current release.

**Comment by juliushaertl** [comment]
I can see this happening maybe as the order is always 999 for new cards and we don't yet use the creation date as a second parameter to sort the cards yet. However it is still strange that it never happens on my test instances. What database are you using?

**Comment by putt1ck** [comment]
Postgre 10.9 on Ubuntu 18.04
