### ISSUE TITLE
v1 beta 1: not all users/groups show up as options to share with

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#1678]
(This may be related to messing around done when exploring #1675 ?)

New boards created post upgrade to v1b1 cannot "see" all users and groups in the sharing dialogue. Boards that are already shared to "missing" groups still show as shared to them. The missing users and groups are consistent but without an obvious pattern (when the group or user was added, naming etc. do not seem relevant). A new group was added for testing purposes but did not appear.

**Comment by juliushaertl** [comment]
Could you post your Nextcloud sharing settings? Is there any limitation set there?

**Comment by putt1ck** [comment]
Unchanged from before the beta Deck was installed:
![image](https://user-images.githubusercontent.com/2872580/79631305-531d0900-8150-11ea-873e-db5bd1c415cf.png)

**Comment by juliushaertl** [comment]
PR in https://github.com/nextcloud/deck/pull/1726
