### ISSUE TITLE
1.0.0-alpha1: tooltips: unexpected oder not shown

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#1679]
**Describe the bug**
tooltips are not displayed or show unexpected text

**To Reproduce**
Move over the icons

**Screenshots**
no tooltipps:

unexpected tooltip over share and action icon:
![d1](https://user-images.githubusercontent.com/34692335/79043228-5ec37980-7bfe-11ea-9939-5b5e3cb45ba3.png)
 *  *  *  *  *
unexpected tooltip over avatar:
![d2](https://user-images.githubusercontent.com/34692335/79043232-6420c400-7bfe-11ea-8243-d48b18fd3b9f.png)
 *  *  *  *  *
no: tooltips on add, filter, ...
![d3](https://user-images.githubusercontent.com/34692335/79043239-66831e00-7bfe-11ea-891e-e90ba2b5ccc4.png)

**Version**
deck: 1.0.0-alpha1
Nextcloud: 19.0.0 beta 2

**Comment by putt1ck** [comment]
Confirmed on Deck v 1 beta 1 on NC 18
