### ISSUE TITLE
Bad Spanish translation to "new-stack-input-main" input

### ISSUE THREAD

**Issue by gusarg81** [nextcloud/deck#1699]
Hi,

This not a "bug" but a bad translation to Spanish of "new-stack-input-main" input.
It has a literal translation of Stack which is wrong (when first time installed this App, I had to "guess" what was that input for).

I don't know which could be the exact translation, but in Spanish could be more like column (Columna), like many other Kanban apps.

The current translation "Añadir nuevo motón" does not make any sense.

App version: 0.8.2

**Comment by juliushaertl** [comment]
The translation for the upcoming 1.0 release will be "Añadir nueva lista" which I assume is a bit more suitable. 

For further translation improvements feel free to join our transifex team at https://www.transifex.com/nextcloud/nextcloud/dashboard/
