### ISSUE TITLE
Move edit/delete stack icons to the popover menu

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#170]
https://github.com/nextcloud/deck/pull/121#issuecomment-304907357

**Comment by artemanufrij** [comment]
like this:
![screenshot_20170530_230245](https://cloud.githubusercontent.com/assets/16517095/26604894/219d3060-458c-11e7-90df-435fc18f9bb6.png)

**Comment by pixelipo** [comment]
@jancborchardt referring to your comment in #121 - I definitely agree with it (better accessibility, lower learning curve, cleaner UI), but I made a PR #173 which deprecates of of the two existing icons (Edit). Should that single (Delete) icon still be moved to the popover?

@juliushaertl you probably have plans for more actions related to stack (Move, Copy, Archive, Archive All Cards...), so popover definitely makes sense, but should we wait until we populate it more?

**Comment by jancborchardt** [comment]
@pixelipo nice, good call with making rename more seamless! :)

A single icon should never be in a popover, but please do add a tooltip to it which appears on hover (using the JS tooltip function). But yeah as you say maybe it makes most sense to do a popover right away when more actions come in.

**Comment by jancborchardt** [comment]
@pixelipo @artemanufrij btw, if you folks come to Berlin some time, for example for our [Nextcloud conference](https://nextcloud.com/conf/) – we should make a bike tour! https://www.reddit.com/r/FixedGearBicycle/comments/6eib4c/breakbrake17_transfer_raw_cinelli_gazzetta/ ;)

**Comment by artemanufrij** [comment]
@jancborchardt Cool! I plan to visit NC conference
