### ISSUE TITLE
[Feature Request] Support for inline latex equations

### ISSUE THREAD

**Issue by lgtrombetta** [nextcloud/deck#1701]
I think this would make a great and useful feature when using Deck for research projects in formal fields such as mathematics and theoretical physics. Latex is the standard for typesetting within these fields so it would make sense as the go-to solution for such a feature.

**Comment by juliushaertl** [comment]
Since we aim to use Nextcloud text as editor for the card description with #1663 I'll close this in favor of https://github.com/nextcloud/text/issues/163 and https://github.com/nextcloud/text/issues/684
