### ISSUE TITLE
Add a tag to card should move it to other stack

### ISSUE THREAD

**Issue by marvinjuette** [nextcloud/deck#1703]
**Is your feature request related to a problem? Please describe.**
There is no option to automove cards with tags to a certain column.

**Describe the solution you'd like**
E.g. when I tag a card with later I want the card moved into the e.g. ideas column while cards with action required are moved to priority. In best case the user can setup thoose rules by himself.

**Describe alternatives you've considered**
Moving all the cards manually, which can get annoing if you have a lot of cards.

**Comment by juliushaertl** [comment]
I think that would be a perfect candidate for integration with Nextcloud Flow so I created https://github.com/nextcloud/deck/issues/1722 and added your use case to that.
