### ISSUE TITLE
Managing Volunteers/Workers - Loosing track

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#1704]
**Is your feature request related to a problem? Please describe.**
We're a small NGO, using Deck for managing the tasks. I've got about fifty people who are interested in doing something, but aren't proactive looking into deck, so I have to look what could fit for them and then suggest.

Problem is, I loose track:
1.) I don't know who has access on specific board on first glance. In my structure this is also who is interested in that topic (it, layout, ecology etc.). (I want to know the user, not just the group)
2.) I don't know who has/hasn't got a task right now.
3.) How to get informed of a card assigned to a volunteer running late/overdue.

**Describe the solution you'd like**
1.) + 2.) Put a list of all users of the deck in #1507 (which is awesome!!) , add (n) behind their names. n = open cards.
3.) a) Workaround: Also assign it to me/bot-account. negative: seems like I want to work, when I just want to know when the work is done.
further ideas:
b) person who created card/assigned the user to card get notification, maybe with turn on/off switch. c) ppl. with managing access to a board get notifications

**Comment by juliushaertl** [comment]
> 1.) + 2.) Put a list of all users of the deck in #1507 (which is awesome!!) , add (n) behind their names. n = open cards.

That sounds like a good enhancement to me, please open a separate issue for this one, as it is easier to track small individual enhancements than issues covering multiple things. :wink: 

> 3.) How to get informed of a card assigned to a volunteer running late/overdue.

This should be solved by https://github.com/nextcloud/deck/issues/713 You could then be notified for all cards on a board while the other users only get notifications for the assigned cards.
