### ISSUE TITLE
markdown formatting (bold, italic, check boxes) in card description gone with 1.0.0 beta

### ISSUE THREAD

**Issue by benjamindahl** [nextcloud/deck#1709]
**Describe the bug**
Before the deck app was updated last week we had formatted check boxes in the card description. Now it appears only as markdown syntax.

**To Reproduce**
1. Go to ' Deck app'
2. Click on 'Any Card'
3. View 'Description with markdown syntax'

**Expected behavior**
See markdown formatted Text

**Screenshots**

![Bildschirmfoto 2020-04-17 um 09 44 35](https://user-images.githubusercontent.com/2698024/79545067-5e106480-8090-11ea-8021-1fd34e0ddca8.png)

**Client details:**
 - OS: macOS 10.12
 - Browser  Chrome

**Server details:**
 - nextcloud 18.0.4 RC1 (snap version)

**Comment by juliushaertl** [comment]
cc @jakobroehrl 

We actually should adapt https://github.com/nextcloud/notes/pull/303 / https://github.com/nextcloud/notes/pull/419 until #1663 is ready

**Comment by juliushaertl** [comment]
For the first issue, yes we will always show markdown syntax for now so users don't need to switch between a preview and the editor. The barrier of using markdown will be solved by #1663

**Comment by benjamindahl** [comment]
I think writing in markdown is ok but it should then switch to preview automatically.
To use nextcloud text editor is a good idea.

cheers

b
