### ISSUE TITLE
How to archive all tasks in a column?

### ISSUE THREAD

**Issue by patrick-motard** [nextcloud/deck#1711]
**Is your feature request related to a problem? Please describe.**
I use three columns; 'todo', 'doing', 'done'. Over time, the done column fills up. In order to archive the issues in the column, I have to archive each issue individually. I think a better user experience would be a button that allows me to archive all issues in a column. Bonus points if it only archives issues older than x date. Super bonus points if it can happen automatically daily.

**Comment by juliushaertl** [comment]
Makes sense to have an archive all button imo. #1721 is also somehow related

**Comment by jakobroehrl** [comment]
basis function will be available in the next version

**Comment by juliushaertl** [comment]
Let's keep this open until the pr is actually merged :wink:

**Comment by jakobroehrl** [comment]
unassign me because PR is ready

**Comment by stefan-niedermann** [comment]
Note: This feature is available in the Android-App since version [`1.5.0`](https://github.com/stefan-niedermann/nextcloud-deck/issues/495)
