### ISSUE TITLE
Attachments aren't updated in the sidebar on card change

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/deck#1750]
https://github.com/nextcloud/deck/blob/396a5c395f783580dfd885cf82d3fcc0abff04bd/src/components/card/CardSidebarTabAttachments.vue#L123

**Comment by juliushaertl** [comment]
The issue is actually that attachments are only fetched once the component is created. I'll do some refactoring once you are done with your attachment PR.

**Comment by jakobroehrl** [comment]
I think this so already working, can't recognize the bug anymore.

**Comment by juliushaertl** [comment]
Yes I think that has been fixed somewhere :wink:
