### ISSUE TITLE
"Repair error" and deck disabled after upgrade to nextcloud 18.04

### ISSUE THREAD

**Issue by wiertz** [nextcloud/deck#1756]
**Describe the bug**
I updated nextcloud from 18.03 to 18.04 using the manual upgrade method. The upgrader runs successfully, but reports  `Repair error: Repair step 'OCA\Deck\Migration\UnknownUsers' is unknown. After the upgrade, nextcloud works fine, but Deck is disabled. Removing and reinstalling Deck does not solve the issue.

**Operating system**:
Ubuntu 18.04 LTS

**Deck version 0.8.2**

### Steps to reproduce
Upgrade from 18.03 to 18.04
### Expected behaviour
Deck works as before

### Actual behaviour
Deck is disabled

## Server configuration detail

**Operating system:** Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 10.4.12

**PHP version:** 

7.2.24-0ubuntu0.18.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 18.03 - 18.04

**Where did you install Nextcloud from:** nextcloud

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - deck
 - encryption
 - files_external
 - firstrunwizard
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.geographie.uni-freiburg.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "#####",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\/mnt\/nc_data\/skeleton",
    "default_language": "en",
    "maintenance": false,
    "auth.bruteforce.protection.enabled": false,
    "theme": "",
    "loglevel": 2,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36

**Operating system:** Mac

## Logs
<details><summary>Nextcloud log</summary>

```
**Nextcloud logs (on trying to reenable Deck)**:
```
{
    "reqId": "qY3p3fSehgmxe9biqpvq",
    "level": 3,
    "time": "2020-04-24T07:22:45+00:00",
    "remoteAddr": "#####",
    "user": "#####",
    "app": "no app in context",
    "method": "POST",
    "url": "/index.php/settings/apps/enable",
    "message": {
        "Exception": "Exception",
        "Message": "Cannot include autoload. Did you run install dependencies using composer?",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 266,
                "function": "require_once"
            },
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 155,
                "function": "requireAppFile",
                "class": "OC_App",
                "type": "::",
                "args": [
                    "deck"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 966,
                "function": "loadApp",
                "class": "OC_App",
                "type": "::",
                "args": [
                    "deck"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/Installer.php",
                "line": 160,
                "function": "executeRepairSteps",
                "class": "OC_App",
                "type": "::",
                "args": [
                    "deck",
                    {
                        "step": "OCA\\Deck\\Migration\\UnknownUsers"
                    }
                ]
            },
            {
                "file": "/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
                "line": 443,
                "function": "installApp",
                "class": "OC\\Installer",
                "type": "->",
                "args": [
                    "deck"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 170,
                "function": "enableApps",
                "class": "OCA\\Settings\\Controller\\AppSettingsController",
                "type": "->",
                "args": [
                    [
                        "deck"
                    ],
                    []
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 99,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Settings\\Controller\\AppSettingsController"
                    },
                    "enableApps"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
                "line": 125,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Settings\\Controller\\AppSettingsController"
                    },
                    "enableApps"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php",
                "line": 47,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": [
                    "OCA\\Settings\\Controller\\AppSettingsController",
                    "enableApps",
                    {
                        "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    },
                    {
                        "_route": "settings.AppSettings.enableApps"
                    }
                ]
            },
            {
                "function": "__invoke",
                "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
                "type": "->",
                "args": [
                    {
                        "_route": "settings.AppSettings.enableApps"
                    }
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/Route/Router.php",
                "line": 299,
                "function": "call_user_func",
                "args": [
                    {
                        "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
                    },
                    {
                        "_route": "settings.AppSettings.enableApps"
                    }
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/base.php",
                "line": 1008,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": [
                    "/settings/apps/enable"
                ]
            },
            {
                "file": "/var/www/nextcloud/index.php",
                "line": 38,
                "function": "handleRequest",
                "class": "OC",
                "type": "::",
                "args": []
            }
        ],
        "File": "/var/www/nextcloud/apps/deck/appinfo/app.php",
        "Line": 25,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15",
    "version": "18.0.4.2",
    "id": "5ea293ca12118"
}

{
    "reqId": "qY3p3fSehgmxe9biqpvq",
    "level": 3,
    "time": "2020-04-24T07:22:45+00:00",
    "remoteAddr": "#####",
    "user": "#####",
    "app": "no app in context",
    "method": "POST",
    "url": "/index.php/settings/apps/enable",
    "message": {
        "Exception": "Exception",
        "Message": "Repair step 'OCA\\Deck\\Migration\\UnknownUsers' is unknown",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 974,
                "function": "addStep",
                "class": "OC\\Repair",
                "type": "->",
                "args": [
                    "OCA\\Deck\\Migration\\UnknownUsers"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/Installer.php",
                "line": 160,
                "function": "executeRepairSteps",
                "class": "OC_App",
                "type": "::",
                "args": [
                    "deck",
                    {
                        "step": "OCA\\Deck\\Migration\\UnknownUsers"
                    }
                ]
            },
            {
                "file": "/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
                "line": 443,
                "function": "installApp",
                "class": "OC\\Installer",
                "type": "->",
                "args": [
                    "deck"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 170,
                "function": "enableApps",
                "class": "OCA\\Settings\\Controller\\AppSettingsController",
                "type": "->",
                "args": [
                    [
                        "deck"
                    ],
                    []
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 99,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Settings\\Controller\\AppSettingsController"
                    },
                    "enableApps"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
                "line": 125,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OCA\\Settings\\Controller\\AppSettingsController"
                    },
                    "enableApps"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php",
                "line": 47,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": [
                    "OCA\\Settings\\Controller\\AppSettingsController",
                    "enableApps",
                    {
                        "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    },
                    {
                        "_route": "settings.AppSettings.enableApps"
                    }
                ]
            },
            {
                "function": "__invoke",
                "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
                "type": "->",
                "args": [
                    {
                        "_route": "settings.AppSettings.enableApps"
                    }
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/Route/Router.php",
                "line": 299,
                "function": "call_user_func",
                "args": [
                    {
                        "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
                    },
                    {
                        "_route": "settings.AppSettings.enableApps"
                    }
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/base.php",
                "line": 1008,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": [
                    "/settings/apps/enable"
                ]
            },
            {
                "file": "/var/www/nextcloud/index.php",
                "line": 38,
                "function": "handleRequest",
                "class": "OC",
                "type": "::",
                "args": []
            }
        ],
        "File": "/var/www/nextcloud/lib/private/Repair.php",
        "Line": 122,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15",
    "version": "18.0.4.2",
    "id": "5ea293ca1202a"
}

{
    "reqId": "kX2hcnPfEL2T8fYrTpZd",
    "level": 3,
    "time": "2020-04-24T07:22:45+00:00",
    "remoteAddr": "#####",
    "user": "#####",
    "app": "no app in context",
    "method": "GET",
    "url": "/index.php/apps/files",
    "message": {
        "Exception": "Exception",
        "Message": "Cannot include autoload. Did you run install dependencies using composer?",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 266,
                "function": "require_once"
            },
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 155,
                "function": "requireAppFile",
                "class": "OC_App",
                "type": "::",
                "args": [
                    "deck"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 128,
                "function": "loadApp",
                "class": "OC_App",
                "type": "::",
                "args": [
                    "deck"
                ]
            },
            {
                "file": "/var/www/nextcloud/apps/dav/appinfo/app.php",
                "line": 36,
                "function": "loadApps",
                "class": "OC_App",
                "type": "::",
                "args": [
                    [
                        "dav"
                    ]
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 266,
                "args": [
                    "/var/www/nextcloud/apps/dav/appinfo/app.php"
                ],
                "function": "require_once"
            },
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 155,
                "function": "requireAppFile",
                "class": "OC_App",
                "type": "::",
                "args": [
                    "dav"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/legacy/app.php",
                "line": 128,
                "function": "loadApp",
                "class": "OC_App",
                "type": "::",
                "args": [
                    "dav"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/base.php",
                "line": 993,
                "function": "loadApps",
                "class": "OC_App",
                "type": "::",
                "args": []
            },
            {
                "file": "/var/www/nextcloud/index.php",
                "line": 38,
                "function": "handleRequest",
                "class": "OC",
                "type": "::",
                "args": []
            }
        ],
        "File": "/var/www/nextcloud/apps/deck/appinfo/app.php",
        "Line": 25,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15",
    "version": "18.0.4.2",
    "id": "5ea293ca11f4d"
}
```
</details>

**Comment by juliushaertl** [comment]
Please fill out the complete issue template, especially what version of deck you are using.

**Comment by wiertz** [comment]
I added more above, Deck was up to date (0.8.2)

**Comment by wiertz** [comment]
How embarrassing – checking for the file I realized that the nextcloud install disk ran full. Everything works fine now. Sorry for bothering you with this!

**Comment by juliushaertl** [comment]
All right, thanks for the update.
