### ISSUE TITLE
Searchbox autoenable

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/deck#176]
It seems that we are using a hack to show force display `#searchbox`:
https://github.com/nextcloud/deck/blob/master/css/style.css#L57

From what I could tell, this tag is hidden by `hasFilter` in core search.js:
https://github.com/nextcloud/server/blob/master/core/search/js/search.js#L383

Mail app is defining this method:
```
setUpSearch: function() {
	SearchProxy.setFilter(require('search').filter);
}
```
which seems to do the trick.

I'm not too familiar with Deck's JS just yet to figure out where to implement this. @juliushaertl could you give me some hints?

**Comment by juliushaertl** [comment]
Not entirely sure, but i think https://github.com/nextcloud/deck/blob/master/js/directive/search.js is the right place. :wink:

**Comment by juliushaertl** [comment]
Fixed with the new search standard.
