### ISSUE TITLE
App for iOS

### ISSUE THREAD

**Issue by Starkstromkonsument** [nextcloud/deck#1769]
Is there / are you planning to implement an app for iOS?

**Comment by antonkarliner** [comment]
I also would be very interested in having such an app!

**Comment by fugohan** [comment]
That would be awesome!

**Comment by jakobroehrl** [comment]
@antonkarliner @fugohan Please use the Github Reactions feature instead of commenting without providing additional information: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/

**Comment by juliushaertl** [comment]
We have nothing planned in that regards. Anyone is of course welcome to start an app like our awesome android community did already with https://github.com/stefan-niedermann/nextcloud-deck

**Comment by stevecopeza** [comment]
The closest I've found to this is the following, https://github.com/cbackas/iOS-Deck anyone aware of any other project underway ?

**Comment by laurentperrinet** [comment]
The [upcoming release](https://github.com/nextcloud/deck/milestone/38) of deck will have [write access](https://github.com/nextcloud/deck/issues/2399) through CalDav protocol, meaning we could simply use the calendar app...

**Comment by jakobroehrl** [comment]
@laurentperrinet nice news, but wrong issue?

**Comment by laurentperrinet** [comment]
> @laurentperrinet nice news, but wrong issue?

indeed @jakobroehrl - this was just to share my current understanding of the development of the deck app within nextcloud, nothing related specifically to the issue - sorry for the noise.

**Comment by dosch** [comment]
> The closest I've found to this is the following, https://github.com/cbackas/iOS-Deck anyone aware of any other project underway ?

this is down... any other news on this front?

**Comment by Duckbilled** [comment]
> > The closest I've found to this is the following, https://github.com/cbackas/iOS-Deck anyone aware of any other project underway ?
> 
> this is down... any other news on this front?

I found a project regarding this, but looks like inactive at the moment. Maybe time for me to start learning how to code apps ;P

https://github.com/ctr49/iOS-Deck

**Comment by Duckbilled** [comment]
Thanks, this is a nice little addition. It is a shame there is no real app yet, but on my phone I usually would just add ideas etc anyway.

**Comment by stefan-niedermann** [comment]
https://github.com/StCyr/deck-react-native
