### ISSUE TITLE
Opening mp3 files as attachments

### ISSUE THREAD

**Issue by damucksta** [nextcloud/deck#1770]
Hi

I am not sure if this is a feature or a bug, so please excuse if I have this wrong.

I add an mp3 attachment to a card. When a user clicks on that attachment (we use firefox), I would like to see a download or open with dialog. This is because the use case I have in mind is that the mp3 playback can be controlled with an external controller (in this case, a foot pedal) - essentially a 'light' version of digital dictation. This necessitates the file opening with a modded version of vlc which can see or be controlled by the footpedal.

What happens now is the mp3 plays in a built-in player within the browser. This does not allow me to use the controller.

Nextcloud generally does not do this if the mp3 is uploaded as a file within the files app - if I upload an mp3 via that, it gives me the option to open with. I therefore presume this is something within deck, rather than nextcloud or the browser configuration, which I have set up normally.

Apologies if this is a stupid question, but is treating a click on an mp3 attachment within deck as a standard download / open with request possible?

Thanks.

**Comment by juliushaertl** [comment]
> What happens now is the mp3 plays in a built-in player within the browser. This does not allow me to use the controller.

This is the way it is working now, we basically rely on the browser handling of files. A possible enhancement might be that we use a file viewer (like in the files app) to present the file which will also not help your use case. 

As a hint, maybe you can disable the playing in your browser options somehow. I remember there was a setting for this at least in firefox.
