### ISSUE TITLE
Columns not aligned when a title is too long

### ISSUE THREAD

**Issue by Clementine46** [nextcloud/deck#1778]
When one list has a title that takes more than one line, the list ends up beginning lower than others, leaving the columns unaligned. 

<img width="1140" alt="Capture d’écran 2020-04-29 à 18 56 53" src="https://user-images.githubusercontent.com/50834537/80624002-5915c280-8a4b-11ea-87b2-3be2ad032524.png">

I believe the board would look much cleaner if the columns stayed aligned no matter what.

Here are my two suggestions : 

1. The space for titles could be restricted to a defined number of characters.
Cons : limiting the user's freedom (then again, are there a lot of people using long titles on the deck ?)

2. The columns should stay aligned even if some titles are longer than others.
Cons : Some lists migh end up having a big space between the title and the first card.

**Comment by Nyco** [comment]
3. Let the user type a long column title, but only show one line, show the whole title when hovered

Maybe a title is not enough: a sub-title or level 2 title, or a description. This second text to be shown smaller, which allows to display more text. For example, that could fill one of the key principles of Kanban, which is to explicit rules. Deck (or Trello) missing that feature, results are that in some teams, unmovable cards are kept manually at the top of each column (consequences: introduce erroneous data in reports).
