### ISSUE TITLE
Click outside card should close sidebar

### ISSUE THREAD

**Issue by simonspa** [nextcloud/deck#1794]
The sidebar opens when clicking on a card, and switches when clicking on another card. To stay in this logic, clicking outside of a card should close the sidebar.

Currently the user has to navigate to the `x` button top-right to close it.

**Comment by jakobroehrl** [comment]
@juliushaertl How can solve this issue? Could you give me a hint?

**Comment by simonspa** [comment]
There is a Vue module called `v-click-outside` which is used somewhere in `spreed` for example - maybe that helps? (don't know myself...)

**Comment by fm-sys** [comment]
If you edit a card title and click outside the card, the editing bar is closed. This may give us a hint how we could implement this feature for closing the sidebar...
![2020-06-22 12_49_15-Deck - Nextcloud](https://user-images.githubusercontent.com/64581222/85279561-eb07dd80-b486-11ea-81b7-be4c1682df14.png)

**Comment by fm-sys** [comment]
Still very important feature! Can someone please, please implement this?

**Comment by stefan-niedermann** [comment]
@fm-sys Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add.

**Comment by jakobroehrl** [comment]
The Esc key should close the sidebar, too
