### ISSUE TITLE
Nullpointer Exception

### ISSUE THREAD

**Issue by niccokunzmann** [nextcloud/deck#1796]
Hi,

I got this error message which I would like to share with you. I do not know if it is applicable to your version or a fork.

ˋˋˋ
Version: 0.0.16

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.full.FullStack.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createFullCard$15$SyncManager(SyncManager.java:483)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$5wr03jG8OdsDHSKN5T_Bjkxw8fI.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:764)
ˋˋˋ

Version: v0.0.16
Maintainer: Niedermann IT Dienstleistungen

**Comment by simonspa** [comment]
This looks like being related to the Android app by @stefan-niedermann rather than this web app.

**Comment by stefan-niedermann** [comment]
That's right, the correct GitHub Repository is here: https://github.com/stefan-niedermann/nextcloud-deck

But to be honest: Update the app. `0.0.16` is **so** outdated, that i can't provide support for it anymore.

Install the latest available version (should be something like `1.0.x`)
