### ISSUE TITLE
moving card to other board : long list of board not visible 

### ISSUE THREAD

**Issue by sergeimcadence** [nextcloud/deck#1797]
DECK version 1.0.0-beta2 

**Describe the bug**
When moving a card from a board to an other, if our number of boards is more than 4 , we do not see the 5th and the followings. To select , we need to click the down arrow by counting the position of the board because we do not see the scrolling down .  

**To Reproduce**
1. Select a card in your board 
2. You need to have at least 5 boards in the list of your boards 
3.  You need to assign the card to the 5th board on your list 
4. click the card menu and select Move card 
5  a box open with 2 selectable line boxes : click on top one == > it lists your board lists 
6. If the list is more than 5 , you do not see the 5th boards and the followings ones. 
7. we need to select the 5th board by clicking 5 times on the down arrow key 

**Expected behavior**
1. The board list is as long as the number of board. 
2. But if there are many boards , then it should be scrollable == > this is more difficult to implement. 
Option 1. seems more reasonable it should be OK up to 10 boards. 
**Screenshots**

![list_of_boards](https://user-images.githubusercontent.com/63451472/81012100-4808ef00-8e59-11ea-968d-a0d06113c44b.png)
![list_for_moving](https://user-images.githubusercontent.com/63451472/81012113-4d663980-8e59-11ea-9928-3200091066d7.png)

Server configuration detail
Operating system: Linux 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64
Webserver: Apache/2.4.29 (Ubuntu) (apache2handler)
Database: mysql 5.7.29
PHP version: 
7.2.24-0ubuntu0.18.04.4 Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
Nextcloud version: 18.0.4 - 18.0.4.2
Updated from an older Nextcloud/ownCloud or fresh install: updated from 17.0.4
Where did you install Nextcloud from: nextcloud.com
Signing status Array ( ) List of activated apps ``` Enabled: - accessibility: 1.4.0 - activity: 2.11.0 - bruteforcesettings: 1.6.0 - cloud_federation_api: 1.1.0 - comments: 1.8.0 - dav: 1.14.0 - deck: 1.0.0-beta2 - federatedfilesharing: 1.8.0 - federation: 1.8.0 - files: 1.13.1 - files_pdfviewer: 1.7.0 - files_rightclick: 0.15.2 - files_sharing: 1.10.1 - files_texteditor: 2.11.0 - files_trashbin: 1.8.0 - files_versions: 1.11.0 - files_videoplayer: 1.7.0 - firstrunwizard: 2.7.0 - issuetemplate: 0.6.0 - keeweb: 0.6.2 - logreader: 2.3.0 - lookup_server_connector: 1.6.0 - nextcloud_announcements: 1.7.0 - notifications: 2.6.0 - oauth2: 1.6.0 - password_policy: 1.8.0 - photos: 1.0.0 - privacy: 1.2.0 - provisioning_api: 1.8.0 - recommendations: 0.6.0 - serverinfo: 1.8.0 - settings: 1.0.0 - sharebymail: 1.8.0 - support: 1.1.0 - survey_client: 1.6.0 - systemtags: 1.8.0 - text: 2.0.0 - theming: 1.9.0 - twofactor_backupcodes: 1.7.0 - updatenotification: 1.8.0 - viewer: 1.2.0 - workflowengine: 2.0.0 Disabled: - admin_audit - encryption - files_external - user_ldap ``` Configuration (config/config.php) ``` { "instanceid": "***REMOVED SENSITIVE VALUE***", "passwordsalt": "***REMOVED SENSITIVE VALUE***", "secret": "***REMOVED SENSITIVE VALUE***", "trusted_domains": [ "localhost" ], "datadirectory": "***REMOVED SENSITIVE VALUE***", "dbtype": "mysql", "version": "18.0.4.2", "overwrite.cli.url": "http:\/\/localhost\/nextcloud", "dbname": "***REMOVED SENSITIVE VALUE***", "dbhost": "***REMOVED SENSITIVE VALUE***", "dbport": "", "dbtableprefix": "oc_", "mysql.utf8mb4": true, "dbuser": "***REMOVED SENSITIVE VALUE***", "dbpassword": "***REMOVED SENSITIVE VALUE***", "installed": true, "theme": "", "loglevel": 2, "maintenance": false } ``` 
Are you using external storage, if yes which one: no
Are you using encryption: no
Are you using an external user-backend, if yes which one: no
Client configuration
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
Operating system: Linux Ubuntu WSL in windows 10 

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```



**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** NO

#### Nextcloud log (data/nextcloud.log)
```
empty
```

#### Browser log
```
none
</details>

**Comment by juliushaertl** [comment]
cc @jakobroehrl
