### ISSUE TITLE
Text in Filter Form: { "tags": [ 136 ], "users": [ "Sokrates" ], "due": "overdue" } #bug

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#1803]
**Describe the bug**
Technical information in frontend.

**To Reproduce**
1. When I filter it shows { "tags": [ 136 ], "users": [ "Sokrates" ], "due": "overdue" } between "Nach Schlagwort filtern" and the labels.

**Expected behavior**
I don't see that information.

NC 18.0.3, Deck 1.0.0, Firefox.

**Comment by mamatt** [comment]
I confirm that's present with for NC 18.0.4 and deck 1.0.0 :

![image](https://user-images.githubusercontent.com/6310611/81269015-0474d780-9049-11ea-8ecd-7e648c409ef4.png)

**Comment by fm-sys** [comment]
Same Issue

**Comment by jakobroehrl** [comment]
fixed with next version
