### ISSUE TITLE
Indicate filter is in use

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#1804]
**Is your feature request related to a problem? Please describe.**
Maybe I forget I use a filter. I don't get a hint it is in use.

**Describe the solution you'd like**
Maybe add an alarming color-background circle to the filter icon, when it is in use.

**Comment by jakobroehrl** [comment]
There is a change it the opacity when a filter was set:
whithout filter:
![grafik](https://user-images.githubusercontent.com/24530680/81545765-a19d7c00-9379-11ea-8bd1-6184aba1f660.png)

with filter:
![grafik](https://user-images.githubusercontent.com/24530680/81545809-b8dc6980-9379-11ea-87fd-00310ea1ced4.png)

@nextcloud/designers Do you have a hint for me? I like it for exampe how it is done in the android deck app: 
![Screenshot_20200511-112449](https://user-images.githubusercontent.com/24530680/81546094-25efff00-937a-11ea-8e27-8eb7016154cc.jpg)

**Comment by Dubidubiduu** [comment]
Desktop:
I don't know if it is accessible, but I question it's obvious.

If I already know this filter could be activated, yeah, it's a helpful fast check. So imo this would work for heavy users. But if I just wonder why I don't see all cards this wouldn't come into my focus.

**Comment by juliushaertl** [comment]
We could also show some additional context to make it clear that the current view is filtered (if space allows) like trello shows the number of results:
![image](https://user-images.githubusercontent.com/3404133/81567521-b3444b00-939c-11ea-94ae-1b69c424364f.png)
