### ISSUE TITLE
[v1.0 release] No checkbox/line break rendering in description view

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/deck#1805]
As the titel says, the checkboxes doesn't render anymore, as well as line breaks are ignore. It looks now a bit weird. And maybe because this, the number of checked/unchecked checkboxes isn't visible on the card anymore.

View:
![grafik](https://user-images.githubusercontent.com/23138465/81184299-8b29a600-8fb0-11ea-9880-77cb9cc3e1f9.png)

Edit:
![grafik](https://user-images.githubusercontent.com/23138465/81184328-9381e100-8fb0-11ea-8012-38215bd4bd44.png)

**Comment by putt1ck** [comment]
This might be related to a change in the library used for markdown (discussed #1731); if you add a "- " before each item it should work again. Maybe there's something that could be done to take care of that automagically if you have a lot of cards with checkboxes.

**Comment by Pilzinsel64** [comment]
Oh, yes. Missed that. Why I didn't try that 😔 Does work now! Thanks.
And what's about insert empty lines? I mean, it looks weird if the distance of the header to the text above is smaller then the distance between the header and the text after that header.
![grafik](https://user-images.githubusercontent.com/23138465/81201550-ae128500-8fc5-11ea-9e53-9ac81c610c29.png)
![grafik](https://user-images.githubusercontent.com/23138465/81201570-b5399300-8fc5-11ea-8a33-94bde7ff0380.png)

**Comment by juliushaertl** [comment]
Let's track that in https://github.com/nextcloud/deck/issues/1808
