### ISSUE TITLE
Markdown does not render

### ISSUE THREAD

**Issue by Nyco** [nextcloud/deck#1808]
**Describe the bug**
Editing a ticket seems fine, but the rendering is not working, as it display all text in one line, with no unordered list not checboxes.

**To Reproduce**
1. Edit a ticket, with markdown code, for example unordered lists and checkboxes
2. Click the eye to render it

**Expected behavior**
The markdown code should be rendered

**Screenshots**

MD code editing:
![Capture d’écran 2020-05-06 à 16 12 55](https://user-images.githubusercontent.com/25348/81187872-e9f11e80-8fb4-11ea-9e68-b0b024d3a761.png)

MD code rendering:
![Capture d’écran 2020-05-06 à 16 13 07](https://user-images.githubusercontent.com/25348/81187885-ed84a580-8fb4-11ea-8ec9-6979a65c46e1.png)

**Client details:**
 - OS: macOS 10.14.6 Mojave
 - Browser: Chrome
 - Version: 81.0.4044.129
 - Device: MacBook Air (2013?)

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**
Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips (fpm-fcgi

**Database:**
mysql 5.5.56

**PHP version:**
7.2.17
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, gnupg, imagick, smbclient, zip, libsmbclient, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page)
18.0.3 - 18.0.3.0

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by SSpecken** [comment]
Got same behavior with Deck V1.0:

Client OS - Windows 10
Client browser - Firefox 76, Chrome  81.0.4044.129

Server configuration
Operating system: Ubuntu 18.04.1
Web server: Apache2
Database: PostgreSQL 10.10
PHP version: 7.2.24
Nextcloud version: 18.0.4

**Comment by Nyco** [comment]
Confirmed with Firefox 75 and 76.

**Comment by q-wertz** [comment]
Two little additions:
1. the checkmarks work when using '- [ ]' instead of '[ ]'
2. numbered lists also kind of work when usind '- 1.' '- 2.' ... but the rendering is out of the sidepanel size (see screenshot 2)

editing:
![Screenshot from 2020-05-06 18-59-00](https://user-images.githubusercontent.com/20948931/81206097-1f990600-8fbb-11ea-8e77-82974ac9ab98.png)

rendered:
![Screenshot from 2020-05-06 18-59-24](https://user-images.githubusercontent.com/20948931/81206114-26277d80-8fbb-11ea-9a3b-7108e153095e.png)

**Comment by joreiff** [comment]
It seems that this might be a CSS issue. As can be seen in the screenshot below, the HTML elements get inserted properly:
![Screenshot](https://user-images.githubusercontent.com/3749578/81263023-32edb500-903f-11ea-9293-0621d1d9f60a.png)

**Comment by danomatika** [comment]
>It seems that this might be a CSS issue.

I don't think so as the checkboxes are output as plain text unless you add the "-" bullets.

**Comment by joreiff** [comment]
The checkboxes are a different issue, however. There are a lot of different markdown dialects, and not every dialect supports checkboxes. Commonmarkdown, which is the dialect used according to the [Deck docs](/nextcloud/deck/blob/master/docs/Markdown.md), [does not](https://spec.commonmark.org/0.29/). So the fact that `- [ ]` works, is a non-standard extension of the parsing library.

**Comment by danomatika** [comment]
>Commonmarkdown, which is the dialect used according to the Deck docs, does not.

Slightly off topic: I would think the markdown dialect supported by Deck *would* accept checkboxes, seeing as how they are used the generate the card's task list metric, ie. "✓ 2/8."

**Comment by Nyco** [comment]
In previous versions, Deck used to support checkboxes in the card and progress on the board/stack à la "✓ 2/8."
So, one can assume it is supposed to work, thus it is probably a bug.

**Comment by joreiff** [comment]
The specific dialect used by Deck does indeed support checkboxes. But it seems like the syntax changed from just `[ ]` to `- [ ]`. Since this is not covered by the CommonMarkdown spec, different Markdown parsers can support different syntax. While this may be a breaking change, it is not a bug in the same way that most Markdown is not rendered properly.

**Comment by linucksrox** [comment]
While we're talking about documentation, it states that it uses the markdown-it script for markdown support. Anything that works in the markdown-it live editor should also work in Deck.

> Markdown comes in may flavors. The best way to learn markdown and understand how to use it, is simply to [try it](https://markdown-it.github.io/) on the original script official playground.

Besides checkboxes, I'm having bullet lists and even headings fail to render when adding `# ` in front of a line.

So if you copy the sample from the "try it" page into Deck you can see what's working and what's not. Links don't render as links, only as bold. Bullet points don't render. Emojis don't render. Only H2 and H3 headings render properly, but no other headings.

I think there's something besides a syntax issue going on here

![image](https://user-images.githubusercontent.com/5169868/81297963-169f4780-9042-11ea-8fa8-3827e4c05987.png)

**Comment by motifsmedia** [comment]
I"m having the same issue. 

I accidentally reported it in the Android Repo:
https://github.com/stefan-niedermann/nextcloud-deck/issues/474

**Comment by HieronymusCH** [comment]
I can confirm.

Deck: 1.0.0
NextCloud: 18.0.4
Kubuntu: 19.10

in edit mode:
https://hieronymusch.net/nextcloud/index.php/s/ToH5Fbs9yp235qg
in view mode:
https://hieronymusch.net/nextcloud/index.php/s/qj9oWfWCaFXQQxk

**Comment by mseift** [comment]
Love this Nextcloud App, i am sorry to have the same issue.
Got same behavior with Deck V1.0:

Client OS - Linux Mint 19.3
Client browser - Firefox 76.0

Web server: Apache
Nextcloud version: 18.0.3
