### ISSUE TITLE
multiple errors

### ISSUE THREAD

**Issue by simon-cirstoiu** [nextcloud/deck#1810]
**Describe the bug**
card asignation is not working, we cannot asign new cards to persons.
in "asign" list, is showing even disabled users.
Old cards, that had been asigned before the update, now suddenly dosen't appear to be asigned anymore.

**Comment by WebOscar** [comment]
Same problem here.

**Comment by juliushaertl** [comment]
Please fill out the complete issue template especially the error logs.
