### ISSUE TITLE
Attachment icon should always stay here, not only in editing mode

### ISSUE THREAD

**Issue by Nyco** [nextcloud/deck#1812]
**Is your feature request related to a problem? Please describe.**
In a card, on the details tab, the description can be viewed or edited by a simple switch icon: crayon or eye.
The problem is that icon location varies according to the mode (editing or viewing), because the middle button (attachment, paper clip icon) is only present in editing mode, not in viewing mode. So a user has to move the mouse/tracker pointer to switch mode.

Note : the "i" or information icon is always at the same place as expected.

**Describe the solution you'd like**
There should always be three unmovable icons/actions on the right end of the description, whatever the order:
* switch edit|view
* attach
* info

**Describe alternatives you've considered**
* The "i" or information icon could be placed somewhere else, as it is not an action, but a help.
* If the display of the attachment, paper clip icon is meant to be kept according to context (editing|viewing), then maybe place it before, so that when a user wants to switch, it is not necessary to move the mouse/tracker pointer. That would give a button order such as: 1. Attach 2. Edit/view 3. Info/help

**Additional context**
* Viewing mode:
![Capture d’écran 2020-05-06 à 17 30 09](https://user-images.githubusercontent.com/25348/81197330-689f8900-8fc0-11ea-9569-b9a18b8b2a84.png)

* Editing mode:
![Capture d’écran 2020-05-06 à 17 30 18](https://user-images.githubusercontent.com/25348/81197364-735a1e00-8fc0-11ea-90a5-32b69219ce91.png)

**Comment by juliushaertl** [comment]
I'd say just switching positions should be fine. The attachment icon is only useful when you can actually edit the description and at some point this will be migrated to the toolbar of nextcloud text anyway with #1663
