### ISSUE TITLE
V1.0.0 (from Nextcloud app update) - card movements spikes CPU and "hangs" browser

### ISSUE THREAD

**Issue by bsherwoodofdaptiv** [nextcloud/deck#1814]
**Describe the bug**
When trying to change the order of an existing card on an existing board, the card moves, and other cards open gaps to land in. Letting go of the card in the desired position hangs the browser. CPU utilization by Firefox hits 30+% (normally idles around 6%) and browser eventually declares "a web page is slowing down your browser".
Short boards (3 cards) hesitates two or three seconds, and then place the card. Large boards (170+ cards) hangs significantly. Eventually the card does get placed. (1 minute, 35 seconds timed on stop watch)
Prior version worked instantaneously on card move actions. 
**To Reproduce**
 -- open board with at least 2 lists. 
 -- one list should be three cards. The other should exceed 170 (but could present issue with less)
 -- move card to new position in short list (note 2 to 3 second 'hang')
 -- move card in large list (wait significantly longer amount of time for action to complete)

-- not applicable
-- not applicable
**Expected behavior**
-- Card moves should be instantaneous
**Screenshots**
-- not applicable
**Client details:**
-- Windows 10 (1909)
-- Firefox
-- 73.0.1 (64bit)
 - Device: [e.g. iPhone6, desktop]
Desktop (Core I3 - 2 cores / 4 logical processors - 8 gigs memory (50% used)
<details>
<summary>Server details</summary>

**Operating system**:
Linux (AWS LightSail)
**Web server:**
Apache
**Database:**
MySql (5.7.29)
**PHP version:**
7.3.17
**Nextcloud version:** (see Nextcloud admin page)
18.0.4
**Where did you install Nextcloud from:**
Ubuntu Snap package
**Signing status:**
-- ????
```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```No errors have been found.

**List of activated apps:**
``` Do not seem applicable to browser side performance

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
``` On Deck page load:
 search handler registered search.js:67:12
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.
On card move:
move card in stack 10 2  [Stack.Vue: 168 ] (short stack)  
move card in stack 11 2  [Stack.Vue: 168 ] (long stack)


</details>

**Comment by bsherwoodofdaptiv** [comment]
additional information and JSON performance data from Firefox ---
![Performance Data - Expanded suspect issue area](https://user-images.githubusercontent.com/2326615/81213123-c74a1000-8f8a-11ea-9f99-295f3efba817.png)

[DECK - profile.zip](https://github.com/nextcloud/deck/files/4588645/DECK.-.profile.zip)

**Comment by bsherwoodofdaptiv** [comment]
![Mid Card Move](https://user-images.githubusercontent.com/2326615/81213341-12fcb980-8f8b-11ea-93f1-eed292eb3749.jpg)
![Post Card Move](https://user-images.githubusercontent.com/2326615/81213354-17c16d80-8f8b-11ea-99b5-67683926d2f1.jpg)

**Comment by juliushaertl** [comment]
Thanks for the traces, it acutally seems that the CardItem component is rendering far to often during dragging (where is should probably not update at all).

![image](https://user-images.githubusercontent.com/3404133/81705563-772dea80-946f-11ea-974f-be6fff76768e.png)

This needs some more investigation but I can indeed reproduce the performance impact here.
