### ISSUE TITLE
Scroll dont work over select attachment when I want  "add attachment" in details section over card

### ISSUE THREAD

**Issue by kenernest** [nextcloud/deck#1815]
**Describe the bug**
When I upload multiple files (+8) and then I want to append it in the card description, I can only choose the ones that are seen in the popup window, without the possibility of scrolling

**To Reproduce**
1. Go to 'attachment"
2. Click on '.Upload attachment"
3. Go to Details
4. Ad attachment
5. You cant choose other files differents

Thanks

**Comment by jakobroehrl** [comment]
Modal doesn't scroll: 
![grafik](https://user-images.githubusercontent.com/24530680/81551225-c564c000-9381-11ea-8f8f-3bda00a4f7f9.png)
