### ISSUE TITLE
Filter: Filtered by a not available tag

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#1817]
**Describe the bug**
Won't see anything on a board, as a tag filter is active, but the tag isn't available on that board, so I don't get it that easily.

**To Reproduce**
1. Activate filter, filter by a tag.
2. Move to another board, where the tag isn't available.
3. You won't see anything. Only indication is that strange #1803 json(?) text.

**Expected behavior**
Have #1804, and in addition to that #1816 would be helpful.

**Comment by juliushaertl** [comment]
Yes, we should make sure that the filter is reset on switching boards.

**Comment by Dubidubiduu** [comment]
Dunno, actually I think it is an common process to check, which of my cards are overdue/overdue soon etc. To do so, right now, I need to switch through every board. It would be painful, to re-add the filter over and over again.

Alternate idea:
- leave the state of the filter, but indicate it is activated #1804
- check whether the tags/tags name are the same, maybe indicate, if they're not
- indicate if the before selected user isn't available

**Comment by jakobroehrl** [comment]
@juliushaertl 
How to do this? Should I do the filter reset here? https://github.com/nextcloud/deck/blob/master/src/store/main.js#L198-L200
