### ISSUE TITLE
Group Cards

### ISSUE THREAD

**Issue by beccon4** [nextcloud/deck#1818]
To manage projects one often divides tasks into subtasks which are handled together.

For that reason it would be very helpful to be able to group cards in a hierarchical manner like Trello does i.e. attach a card to the one above - and ident it accordingly.

**Comment by jakobroehrl** [comment]
Could you provide some screenshots?

**Comment by beccon4** [comment]
![grafik](https://user-images.githubusercontent.com/12436716/81675825-9b79cf00-944f-11ea-8935-8f9dd2eb0d53.png)

**Comment by juliushaertl** [comment]
Duplicate of #272
