### ISSUE TITLE
Error in mozilla when you move a card to another column

### ISSUE THREAD

**Issue by bernardomurillo** [nextcloud/deck#1825]
Hello,

Yesterday i updated to Deck new version 1.0
After that, when i try to move a card in mozilla to next column, the card freezes and mozilla shows message: "a website is slowing down your browser. Stop it or wait?".

If you scroll the page, the card is sticky in the page.

Regards,

**Comment by juliushaertl** [comment]
Duplicate of https://github.com/nextcloud/deck/issues/1814
