### ISSUE TITLE
1.0.0: Calendar formatting does not allow to choose next month

### ISSUE THREAD

**Issue by jacotec** [nextcloud/deck#1826]
**Describe the bug**
Simple. Tell me how to select to the next month ...

<img width="390" alt="grafik" src="https://user-images.githubusercontent.com/3321655/81315208-4d994b80-908a-11ea-8f4c-5ce06b04ee4d.png">

**Comment by fm-sys** [comment]
I have the same Issue. Hope that will be fixed quickly.

Until then following workaround to come to the next month:
![2020-05-08 11_42_52-Präsentation1 - PowerPoint](https://user-images.githubusercontent.com/64581222/81393905-686acf00-9121-11ea-83dc-09920deee905.png)
Click at one of the days of next month and then go back to date select. That's it!

**Comment by BKapelari** [comment]
Same issue here

**Comment by juliushaertl** [comment]
@BKapelari Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting without providing additional information.

**Comment by d0-wN** [comment]
at the moment, the easiest workaround (since @fm-sys solution does not quite work for me) is to install the"custom css plugin" ([store-link](https://apps.nextcloud.com/apps/theming_customcss)) and add the following code:
`.mx-datepicker[data-v-e1f55ce] .mx-calendar-header, .mx-datepicker[data-v-e1f55ce] .mx-time-header{
          width: auto !important;
}`

the design will be a little bit messed up, but all buttons you need to pick a date/time will be visible then. (let me know if this works for you guys)

**Comment by BKapelari** [comment]
> at the moment, the easiest workaround (since @fm-sys solution does not quite work for me) is to install the"custom css plugin" ([store-link](https://apps.nextcloud.com/apps/theming_customcss)) and add the following code:
> `.mx-datepicker[data-v-e1f55ce] .mx-calendar-header, .mx-datepicker[data-v-e1f55ce] .mx-time-header{ width: auto !important; }`
> 
> the design will be a little bit messed up, but all buttons you need to pick a date/time will be visible then. (let me know if this works for you guys)

Thank you for this solution. For me the following CSS-Code worked the best:
```
.mx-calendar-header {
    display: flex !important;
}
.mx-calendar-header-label {
    overflow: hidden;
}
.mx-btn.mx-btn-text.mx-btn-current-year {
  width: 3.2em;
  overflow: hidden;
}
```
![Bildschirmfoto 2020-05-18 um 10 24 01](https://user-images.githubusercontent.com/4718590/82190691-b46ffd80-98f1-11ea-81a9-943bd7789bfe.png)
