### ISSUE TITLE
1.0.0 - No indication of description entered on card

### ISSUE THREAD

**Issue by danklassen** [nextcloud/deck#1827]
In previous versions when a description was entered in the details tab an icon would show on the card indicating there was more information. Since 1.0 this no longer displays.

**To Reproduce**
Add a card with a description

**Expected behavior**
An icon displays on the card indicating there is a description entered

**Client details:**
 - OS: Ubuntu
 - Browser Brave
 - Device: desktop

**Comment by juliushaertl** [comment]
We removed this during the general card layout discussions in https://github.com/stefan-niedermann/nextcloud-deck/issues/298#issuecomment-611368560

>> Because tooltips are really not obvious. First line of description gives way better context and directly shows what’s there. 
> Personally I don't see much value in showing the first line of the description, I would even argue that we could remove the description indicator icon in the web app, since that only helps if you use it with the tooltip.
