### ISSUE TITLE
Can't create new tags in the web browser of Deck

### ISSUE THREAD

**Issue by deljones** [nextcloud/deck#1830]
Not able to create new tags

To Reproduce

    Create a board
    Create a list and a card in the list
    Double click the card. Info opens up on the right
    Go to tags. Type in the new tag name. Nothing happens

Expected behavior
New tag appears in a random colour as per the mobile app

**Smartphone **
In the Andoid version of Deck, YOU CAN create new tags that do appear on the desktop version. You just can't do it the other way.

**Comment by realvikr** [comment]
You can create a new tag in the board properties

**Comment by deljones** [comment]
Yep.. Found it... Thanks.

**Comment by juliushaertl** [comment]
Yes, creating directly in the tag selector is tracked in #1472
