### ISSUE TITLE
Add API documentation for "Reply comment" feature

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#1831]
Self explaining.

I think there is something missing in the [OCS comments API documentation](https://github.com/nextcloud/deck/blob/master/docs/API.md#comments)

**Comment by juliushaertl** [comment]
Quick summary until I find some time to wrap that into the docs:

- POST /cards/{cardId}/comments - Create a new comment
  The parentId can be set to an id of a comment in order to mark it as a reply to that one
- GET /cards/{cardId}/comments - List comments
  If a comment is a reply to another one, the parent comment is added in the replyTo property

```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": [
      {
        "id": "175",
        "objectId": "12",
        "message": "This is a comment with a mention to  @alice",
        "actorId": "admin",
        "actorType": "users",
        "actorDisplayName": "Administrator",
        "creationDateTime": "2020-03-10T10:23:07+00:00",
        "mentions": [
          {
            "mentionId": "alice",
            "mentionType": "user",
            "mentionDisplayName": "alice"
          }
        ],
        "replyTo": {
          "id": "150",
          "objectId": "12",
          "message": "This is the parent cmment",
          "actorId": "admin",
          "actorType": "users",
          "actorDisplayName": "Administrator",
          "creationDateTime": "2020-03-10T10:23:07+00:00",
          "mentions": [],
		}
      }
    ]
  }
}
```

**Comment by stefan-niedermann** [comment]
Are more than one level supported in general and in the web app?

**Comment by juliushaertl** [comment]
No just one parent to keep this simple.

**Comment by juliushaertl** [comment]
- [ ] integers are not accepted by type hints
- [ ] add check for access to parentId

**Comment by stefan-niedermann** [comment]
Thanks for adding those tasks. Please let me know in which version this will be fixed (I will shrink the Android support for replys to this version then to avoid synchronization errors)
