### ISSUE TITLE
Sharing Board - make "edit, manage, share"-status visible at once

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#1834]
**Is your feature request related to a problem? Please describe.**
If I overview a board shares I don't get the relevant information at first glance. Instead I need to open every "..." of all shares. That is a lot of unnecessary click work.

**Describe the solution you'd like**
Show all in one row. Make a small table head "edit | manage | share" and print the checkboxes respective. Eagerly get rid of the "kann" / "can" right before the status.

Also it should be clear, what's the meaning of a status, which it is not for "manage", as #679 also states. Prefer a span title to explan what's behind manage.

**Comment by juliushaertl** [comment]
We basically aligned this to the files app where we only show the most important permission by default. Also shortening the names might be fine in English, but the space will quickly exceed then with translations. In German for example it would be "[ ] Bearbeiten [ ] Teilen [ ] Verwalten" Other languages might of course be even longer.
