### ISSUE TITLE
V1.0.0 is buggy! How can you release this!

### ISSUE THREAD

**Issue by ramezrafla** [nextcloud/deck#1846]
**Describe the bug**

After upgrading to 1.0.0 from 0.8.0 we are getting a whole slew of issues. We can't assign card, we have errors in the console, we can't properly set a date. 

The issue tracker on github has a slew of bugs. How can you release this? Is there no oversight on this project?

To add insult to injury, we can't properly build it, are you properly creating your branches? Where is stable-1.0.0?

**To Reproduce**
Update to 1.0.0 (from the store or the release files on github) from 0.8.0

**Expected behavior**
Where do I begin? Assigning users should work. Calendar should work. Look at the other issues reported by others.

**Screenshots**
![deck-screenshot](https://user-images.githubusercontent.com/1903864/81507377-fcc46580-92ca-11ea-9a04-afce8944013a.png)

This is what happens when I click on 'Assign to me'

**Client details:**
 - OS: 5.3.0-51-generic #44-Ubuntu X64
 - Browser: Chrome
 - Version: 81
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**
Server is Linux 4.14.152-98.182.amzn1.x86_64 
Apache2 

**Database:**
MariaDB

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
18.0.4

**Where did you install Nextcloud from:**
Github

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ramezrafla** [comment]
Here are just some of the issues we faced #1828 #1826 #1823 #1811 #1810 #1846

Please downgrade on the apps store so it does not break deployments and build your test cases properly. Let us know if you need help.

**Comment by mseift** [comment]
> Here are just some of the issues we faced #1828 #1826 #1823 #1811 #1810 #1846
> 
> Please downgrade on the apps store so it does not break deployments and build your test cases properly. Let us know if you need help.

How does one downgrade the app via the app store?

**Comment by ramezrafla** [comment]
@mseift 
The the best of my knowledge, you can't, you need to manually put it in your apps folder
It's up to the developers to release a new version

**Comment by simonspa** [comment]
Dear @ramezrafla 

If you don't mind, I would like to close this ticket since it doesn't describe a particular problem to be fixed but is rather an expression of your opinion. If you would like to discuss or share your opinion I would suggest to head over to the forums, there is a category for the Deck app:
https://help.nextcloud.com/c/apps/deck/83

Apart from that I believe that the developers of this app did their best (and will continue to) in testing everything before a release. Unfortunately, some things slip and will have to be fixed later. If you depend on this software for your daily business I'd recommend to test things on a separate installation before updating your production server.

Best,
Simon
