### ISSUE TITLE
Export and Import

### ISSUE THREAD

**Issue by thromeaway** [nextcloud/deck#1847]
**Is your feature request related to a problem? Please describe.**
I wanted to move to another Nextcloud Server but had to manually copy all board entries

**Describe the solution you'd like**
Contacts, tasks, calender has ex- and import feature this should be possible with decks too

**Describe alternatives you've considered**
using tasks instead

**Additional context**
It would be useful and safe a lot of time. I might have to use tasks instead because atleast i cant ex and omport them in case i have to move servers again

**Comment by juliushaertl** [comment]
Duplicate of #87
