### ISSUE TITLE
3 Bugs in version 1.0.0

### ISSUE THREAD

**Issue by riparise** [nextcloud/deck#1861]
**Describe the bug**
I identified 3 bugs in the version 1.0.0:
1) Deleted cards still show up in the main view.
2) Cannot go back to the main view from a board view.
3) Can access deleted boards. Cannot undelete them.

**Steps To Reproduce**
Bug 1 - Boards not deleting properly:
1.1 In the "left side board panel":
1.2 Click Create new board, give any name.
1.3 After creating, click in the three dots (options), delete board.
1.4 Board disappears from "left side board panel", but is still visible in the main view.
1.5 If I achieve a board, it does disappear from the main view, as intended.

Bug 2 - Cannot go back to main view:
2.1 Click on any board to enter the board view.
2.2 Click on All boards in the "left side board panel" to go back to the initial view
2.3 The url changes back to https://xxxxxx/apps/deck/#/ but nothing else changes. Need to reload the page to go back to the initial view.

Bug 3:
3.1 Try to access the URL of a deleted board (that is not showing in the "left side board panel" nor in
the main view.
3.2 In my case, https://xxxxx/apps/deck/#/board/1
3.3 Can access this ghost board.
3.4 Cannot undelete it (this is probably more of a wish than a bug, since I deleted it accidentally and would like to undo this action.)

**Expected behavior**
I hope it is self-explanatory.

**Screenshots**
Please, if its not clear enough, let me know and I can provide screen shots or anything else. 

**Client details:**
 - server is installed on an Ubuntu with NGINX, accessed via Firefox in Windows 10
 - Deck is in version 1.0.0, Nextcloud 19.0.0 RC1 (beta update channel)

**Comment by juliushaertl** [comment]
Please open separate issues for each of those otherwise this is becoming really hard to track such things properly.
