### ISSUE TITLE
Parameters icon's placement on cards is not ideal

### ISSUE THREAD

**Issue by Clementine46** [nextcloud/deck#1862]
The parameters icon on cards is placed on the bottom-right corner.
According to me, this raises three issues : 

1) The placement is unnatural, parameters icons are usually found on top-right corners so this is unusual for the user.

2) Because of that placement, the bottom part of a card ends up being pretty big. There is a lot of empty space that seems unnecessary.

<img width="291" alt="Capture d’écran 2020-05-11 à 17 44 14" src="https://user-images.githubusercontent.com/50834537/81581651-4edeb700-93af-11ea-9c1a-914eacd9d1d5.png">

3) But most importantly, the card's parameters aren't accessible in compact mode, which is unpractical.

<img width="291" alt="Capture d’écran 2020-05-11 à 17 44 23" src="https://user-images.githubusercontent.com/50834537/81581545-2bb40780-93af-11ea-9afb-b9c24dd5e0b4.png">

By placing the parameters icon in the top right corner of a card, you can solve these three issues at once. 

![Deck_Parameters](https://user-images.githubusercontent.com/50834537/81581333-ded03100-93ae-11ea-8144-6a894307a220.png)

Here, you can see that there is no empty space anymore and the parameters are still accessible in compact mode.

What do you think ?

**Comment by juliushaertl** [comment]
Yes, we should definitely fix that. I would actually assume that a bug :wink:

**Comment by jakobroehrl** [comment]
Same topic as in here: https://github.com/nextcloud/deck/issues/799
