### ISSUE TITLE
style all modals identical

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/deck#1869]
- [ ] 4 times "add to project"
- [ ] move card
- [ ] add attachment to desc

**Comment by juliushaertl** [comment]
@jakobroehrl I'm not sure what this is exactly about, please be a bit more verbose about what an issue is about ;) Is it fixed already? :grin:

**Comment by jakobroehrl** [comment]
It's open. The idea was to see all modals and do an identical styling.

**Comment by juliushaertl** [comment]
OK, maybe we can collect some screenshots then so we can discuss the layout changes upfront.

**Comment by joshtrichards** [comment]
I guess this was in response to this thread: https://github.com/nextcloud/deck/pull/1875#discussion_r424977973

Still a thing? :)

**Comment by juliushaertl** [comment]
Let's close this, not entirely sure what this was about.
