### ISSUE TITLE
Labels are dominating the cards

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#1872]
**Is your feature request related to a problem? Please describe.**
If you use round labels on cards they are very dominant due to the padding and the large color area.
I would like to bring a simple redesign of the labels up for discussion.

**Describe the solution you'd like**
A more square design with less padding (like github) should save space and reduce the optical impact. IMHO the round design also doesn't look professional.

@juliushaertl @jakobroehrl  What do you think?
@stefan-niedermann I think this applies even more to the mobile app, as space is valueable here.

Deck v1.0.0

**Comment by juliushaertl** [comment]
The change was discussed in https://github.com/stefan-niedermann/nextcloud-deck/issues/298#issuecomment-611368560 and was basically oriented on material design chips. I think the rounded layout fits pretty well into how Nextcloud UI components are looking these days with fully rounded buttons for example.

I agree that we probably could decrease the padding a bit more to give them a bit less priority than the actual card title cc @nextcloud/designers and @jancborchardt

**Comment by Nyco** [comment]
Agree:
* the labels are too rounded, maybe a more square shape can help
* the padding is too large

In the previous, the square shape was quite right, but the padding too low.

**Comment by jancborchardt** [comment]
Are the labels clickable to use as a filter? Then their clickable size needs to be 44px at least. This can be separated from the visual part though, which could be made to appear smaller.

**Comment by juliushaertl** [comment]
> Are the labels clickable to use as a filter

No in the board view they are just indicators without any action. The whole card itself is clickable.

**Comment by bpcurse** [comment]
Regarding consistency in design:
![Screenshot_2020-05-16 Deck - Nextcloud](https://user-images.githubusercontent.com/29312856/82122970-1ff18800-9797-11ea-9131-59b184c4ea3d.png)
I think the design of the overdue indicator with less top/bottom padding would be a good solution.

**Comment by stefan-niedermann** [comment]
@bpcurse your proposal would make the due date hard to distinguish from tags, therefore 👎 from me.

**Comment by bpcurse** [comment]
@stefan-niedermann Thank you for clarification :)
I get your point, but isn't there also the spatial factor that should help in distinguishing them from each other?
What about introducing a new simple design element (light gray horizontal line) to structure the card and make this more obvious (see attached mockup)? @juliushaertl @jancborchardt 
![Deck Mockup Card additional design element](https://user-images.githubusercontent.com/29312856/82124543-f12bdf80-979f-11ea-8560-e2dabb47f423.png)

**Comment by vix95** [comment]
Hi, yes, you're right. First look goes to labels. My proporsal is:
![image](https://user-images.githubusercontent.com/38139321/82382662-a7a3f480-9a2c-11ea-91dd-8576a83b6b44.png)

Or this one:
![image](https://user-images.githubusercontent.com/38139321/82382887-13865d00-9a2d-11ea-8b7d-ad7f76e08b4b.png)

`.card .labels li {
    flex-grow: 0;
    flex-shrink: 1;
    display: flex;
    flex-direction: row;
    overflow: hidden;
    padding: 0px 5px;
    border-radius: 5px;
    font-size: 70%;
    margin-right: 3px;
    margin-bottom: 3px;
}`

**Comment by Nyco** [comment]
v0.8 design:
![0 8-design](https://user-images.githubusercontent.com/25348/84193582-f6790300-aa9b-11ea-9e9f-185972a1a792.png)

v1.0 design:
![1 0-design](https://user-images.githubusercontent.com/25348/84193576-f547d600-aa9b-11ea-9179-faa8adc23023.png)

This proposed design:
![new-design](https://user-images.githubusercontent.com/25348/84193595-fa0c8a00-aa9b-11ea-8db8-003f2639aa5b.png)

Trello design:
![Trello-design](https://user-images.githubusercontent.com/25348/84193934-8454ee00-aa9c-11ea-9c88-e8836dcff5fe.png)

It look to me like we could even remove one more pixel of padding.

**Comment by juliushaertl** [comment]
@stefan-niedermann How do you think about adjusting the android app as well, since we mainly changed this to be in sync. I think reducing the padding should still be fine since the label doesn't trigger and click/touch action so they are not really covered by the [material chips](https://material.io/components/chips)

**Comment by stefan-niedermann** [comment]
The Android app actually triggers touch actions when editing a card
- to remove a label 
![grafik](https://user-images.githubusercontent.com/4741199/84636708-289fc000-aef5-11ea-8f19-f2ab99c37a8d.png)
- to add a label
![grafik](https://user-images.githubusercontent.com/4741199/84636771-39503600-aef5-11ea-9a24-961bd1a625a6.png)

Though i could imagine to reduce the padding in the overview a bit

![grafik](https://user-images.githubusercontent.com/4741199/84636831-54bb4100-aef5-11ea-88c0-b2c333bb1d26.png)

How much padding do you think would be appropriate? I want the user to be able to associate the labels from the overview with the labels in the edit mode. Therefore they shouldn't look too much different.

And do you want to also change the border radius like proposed by @Nyco ? While the labels in the files app (web UI) are also not round:

![grafik](https://user-images.githubusercontent.com/4741199/84639066-23904000-aef8-11ea-8fc3-659092927f79.png)

i still think that the completely rounded corners fit the overall design of Nextcloud better

**Comment by Nyco** [comment]
It all makes sense on Android, but here, it is a ticket for the web app.

The main problem with this padding is that it occupies way too much space on the screen and on the card, and steals a lot of attention. Currently, the card title is supposed more important than the tags, but it is less visible.

For one card:
![1 0-design](https://user-images.githubusercontent.com/25348/84193576-f547d600-aa9b-11ea-9179-faa8adc23023.png)

For a whole Deck:
![Capture d’écran de 2020-06-17 11-11-17](https://user-images.githubusercontent.com/25348/84879327-5c145300-b08b-11ea-9bb6-5ab688274b0a.png)

Here you can clearly see that tags a widlely dominating the global Deck, it is barely possible to pay attention to cards titles.

As a comparison, Trello, it is more readable:
![Capture d’écran de 2020-06-17 11-18-04](https://user-images.githubusercontent.com/25348/84880011-49e6e480-b08c-11ea-9af0-12d41897c227.png)
![Capture d’écran de 2020-06-17 11-18-15](https://user-images.githubusercontent.com/25348/84880020-4ce1d500-b08c-11ea-8591-74d65b06e5ee.png)

**Comment by stefan-niedermann** [comment]
> It all makes sense on Android, but here, it is a ticket for the web app.

I can see that this issue is in the repository of the web UI, though the underlying problem you are describing would also affect Android - if it's an issue that the title should get more attention compared to the labels then it affects all clients.

We try to keep the UI similar if possible for a better orientation for users of both apps. Usually the Android app simply follows the design of the Web UI (respecting Material design).

But in this case @juliushaertl asked for my opinion and i just answered that the android app could not follow completely here because it uses the labels as touch target in some situations. Now we're looking for a solution (which can be either differing in this point *or* a common solution which we can follow in all clients)
