### ISSUE TITLE
kanboard

### ISSUE THREAD

**Issue by michelwend** [nextcloud/deck#188]
The ideal would be that the application looks like kanboard
https://kanboard.net/
Tanks

**Comment by pixelipo** [comment]
Why would that be ideal? Is that the ideal Kanban app? Better than any other Kanban app out there?

**Comment by juliushaertl** [comment]
@michelwend If you have any concrete change requests, please file separate issues on that. Just saying it sould be like another software is far to vague :wink:

**Comment by michelwend** [comment]
Hello, I did not want to hurt you in anything. I'm sorry if that's the case. I just find that this software that I know a little can be used as a track for the development to come. Indeed it is not ideal since it is not integrated with nextcloud. I had proposed setting up a Gantt chart (http://www.diagramme-de-gantt.fr/) previously for example. See you soon
