### ISSUE TITLE
Provide REST-Endpoint for getting a single comment by ID

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/deck#1889]
**Is your feature request related to a problem? Please describe.**
In some cases we get into race conditions while syncing the comments. The trouble starts, in case a reply to a comment comes before the parent comment. Persisting the comment is secured by a foreign key constraint, which fails in case the parent isn't existing yet.

**Describe the solution you'd like**
Here i see two possible solutions:
* return the comments ordered by creation time descending
* provide a REST endpoint to get a single comment by ID (the parent-id in my case)

**Describe alternatives you've considered**
Currently i built a workaround, where i (again) fetch all the comments to a card and filter it by the parent ID. 

In case you wonder:  reusing the initial list i gathered would break my whole nice code architecture. 

**Additional context**
How my code works: 
* get list of comments to a card
* iterate
* check if create or update (do we have a local ID?)
* execute some code in other interfaced data-provider-classes (parameter: single! entity, not the whole list)
-> this way i have exactly 1 sync logic for N entity types (cards, stacks, boards, etc.)

**Comment by stefan-niedermann** [comment]
I had a talk with @desperateCoder and we won't need the changes that he requested in this issue.

Just ignore this issue.
