### ISSUE TITLE
Add posibility to select TAGS when new item is created

### ISSUE THREAD

**Issue by vix95** [nextcloud/deck#1891]
I think it would be nice when I could select the TAGS during creating the item.

![image](https://user-images.githubusercontent.com/38139321/81987250-8fe9fc00-9639-11ea-860a-141c84616f33.png)

 For instance it could scroll down after create the item and open it and show the configuration.

![image](https://user-images.githubusercontent.com/38139321/81987346-b90a8c80-9639-11ea-84c4-2467d8979c52.png)

It will be easier to manage new item. Now I must to find in the category (I know that the item is on the last position) but it isn't friendly.

**Comment by juliushaertl** [comment]
Good point. We should actually open the sidebar right after the card was added I'd say. @nextcloud/designers
