### ISSUE TITLE
Stay in compact mode

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#1894]
**Is your feature request related to a problem? Please describe.**

When enabling the compact mode, it is only enabled until the page is reloaded.
I would rather like to enable the expanded view than enabling the compact mode all the time

**Describe the solution you'd like**

After the compact mode is enabled, it should stay on unless explicitly the expanded mode is enabled.

Deck v1.0.0

**Comment by juliushaertl** [comment]
Yes, i think that was lost during the vue rewrite. Iirc we stored the state of compact mode in the browsers local storage in the past.

**Comment by reox** [comment]
Ah okay, I wasn't sure if it worked before :sweat_smile: Because I was switching between too many workstations, I probably never noticed that it stayed for one browser.

**Comment by juliushaertl** [comment]
Probably worth to persist that setting on the server as well in a second step, right :+1:
