### ISSUE TITLE
Can't comment on tasks

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/deck#1898]
**Describe the bug**
Previously I could view task details, click timeline, and enter a comment (I have cards with comments in and they show). Now I can't enter comments anymore. There are no buttons to allow adding them, nor is the text field to type in visible.

### Steps to reproduce
Try to comment on a task. Open a task detail view, go to timeline, try to add a comment.

### Expected behaviour
A text area is visible that you can enter a comment into, and it has a button to submit.

### Actual behaviour
No text area / buttons to allow comments to be added.
![image](https://user-images.githubusercontent.com/665111/82033413-99548200-9694-11ea-9700-abdb476dcc55.png)

## Server configuration detail

**Operating system:** Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.3.22

**PHP version:** 

7.3.14-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, pdo_sqlite, apc, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.9.0
 - breezedark: 18.0.15
 - bruteforcesettings: 1.6.0
 - camerarawpreviews: 0.7.3
 - cloud_federation_api: 1.1.0
 - dav: 1.14.0
 - deck: 1.0.0
 - emlviewer: 0.0.5
 - extract: 1.2.4
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - jsloader: 1.0.2
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocr: 6.0.40
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - previewgenerator: 2.3.0
 - provisioning_api: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - theming_customcss: 1.5.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - uploaddetails: 0.1.3
 - video_converter: 0.1.4
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - comments
 - encryption
 - federation
 - files_versions
 - photos
 - privacy
 - recommendations
 - serverinfo
 - support
 - survey_client
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "jsloader",
        "bruteforcesettings",
        "ocr",
        "uploaddetails",
        "breezedark"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by juliushaertl** [comment]
> Disabled:
> - comments

The comments app needs to be enabled in order to use comments in deck.

**Comment by a1pilot** [comment]
I can only assume it was a Nextcloud update that automatically disabled it. I certainly haven't as Deck is actively used each day.

**Comment by juliushaertl** [comment]
If it was automatically disabled for some reason there should be a log entry that might give a hint why. :wink: Maybe that is something worth to check.
