### ISSUE TITLE
Markdown Checkbox "[ ]"|"[x]" still does not render correctly

### ISSUE THREAD

**Issue by Nyco** [nextcloud/deck#1905]
**Describe the bug**
The markdown has been only partially fixed: the checboxes are still borken, compared to 0.8

**To Reproduce**
1. Open an existing card
2. Details > Description > Edit
3. Type some checbox Markdown code, with and without ordered and unordered lists

**Expected behavior**
Render correctly checboxes and make them checkable when not editing

**Screenshots**

On a 1.0.1:
![Capture d’écran 2020-05-15 à 22 48 06](https://user-images.githubusercontent.com/25348/82095016-78c11200-96fe-11ea-9680-4bc72045d0a3.png)
![Capture d’écran 2020-05-15 à 22 48 14](https://user-images.githubusercontent.com/25348/82095024-7bbc0280-96fe-11ea-80f4-4c8078922f22.png)

On a 0.8:
![Capture d’écran 2020-05-15 à 23 01 59](https://user-images.githubusercontent.com/25348/82095818-24b72d00-9700-11ea-9a2e-c99d22b75e9c.png)
![Capture d’écran 2020-05-15 à 23 01 51](https://user-images.githubusercontent.com/25348/82095833-284ab400-9700-11ea-8cf5-518e41305235.png)

**Client details:**
 - OS: macOS 10.14.6 Mojave
 - Browser: Chrome
 - Version: 81.0.4044.129
 - Device: MacBook Air (2013?)
<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**
Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips (fpm-fcgi

**Database:**
mysql 5.5.56

**PHP version:**
7.2.17
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, gnupg, imagick, smbclient, zip, libsmbclient, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page)
18.0.3 - 18.0.3.0

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Ah right, we are actually lacking `breaks: true` in our markdown it configuration https://markdown-it.github.io/markdown-it/#MarkdownIt.new to have a line break also being forced in the rendered output.

**Comment by reox** [comment]
maybe related: I also saw that in the editor, "html tags" are highlighted. So if you are writing something like <foo bar> then it tries to highlight it as HTML, which is probably unnecessary?

**Comment by Nyco** [comment]
Here is some test/validation data:

[ ] without dash, unchecked
[x] without dash, checked
- [x] with dash, checked
- [ ] with dash, unchecked
	- [x] space, space, dash, checked
	- [ ] space, space, dash, unchecked
- [ ] with dash, unchecked
- [x] with dash, checked
[x] without dash, checked
[ ] without dash, unchecked

**Comment by juliushaertl** [comment]
That is actually expected (see https://github.com/nextcloud/deck/issues/1967#issuecomment-635996778 for details) I thought you were referring to the line breaks.

**Comment by Nyco** [comment]
Oops, sorry for the misunderstanding, I should be more precise on my tickets...
