### ISSUE TITLE
There is no descriptions to translate in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/deck#1906]
Transifex is missing descriptions to translate:

- Unarchive card
- Archive card

https://github.com/nextcloud/deck/blob/6c01ebd0f4be270fdce28186680cfcccceb7f91d/src/components/cards/CardMenu.vue#L30-L31

App:
Nextcloud 19.0.0 RC2
Deck 1.0.1

**Comment by vix95** [comment]
Ya, I'm using the Deck in different language and I can notice that the sentence isn't translated.

**Comment by juliushaertl** [comment]
Was fixed by https://github.com/nextcloud/deck/commit/a0e023b638589f09bf10cfb612de2e0fbd625124
