### ISSUE TITLE
Due date picker - do not show the time

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#1909]
**Describe the bug**
The displayed date is in ISO format and contains "T00:00:00.00" so it does not fit the window.
Controls on the right side of the date are therefore not visible.

**To Reproduce**
1. Create card
2. Open details
3. Set a due date

**Expected behavior**
Date should not show the time at this point and if possible obey user locale. Should fit the window.

**Screenshots**
![Bildschirmfoto_2020-05-16_17-15-51](https://user-images.githubusercontent.com/29312856/82123657-d0ad5680-979a-11ea-90d7-9ce0adb68ec1.png)

**Client/server details:**
Firefox 76.0.1 on Linux
Deck 1.0.1, Nextcloud 18.0.4

**Comment by aproposnix** [comment]
I cannot set the date at all because of this. As a workaround, I'm setting due dates and time on the Android App.

**Comment by jakobroehrl** [comment]
duplicate: https://github.com/nextcloud/deck/issues/1826
