### ISSUE TITLE
copy/view tag colors

### ISSUE THREAD

**Issue by jiblett1000** [nextcloud/deck#1911]
Hey all. First off, thanks to all the developers for the great work on this app. I am continually (and pleasantly) surprised at the pace at which this app is being worked on :)

Anyhow, I was going to add some tags today and thought it would be extremely useful to have a way to see or copy the color from one tag to another. This could potentially mean adding a text display of the hex code and a place for input of hex codes.

This could be useful for someone hoping to organize different tags by the same color. For example, they could organize tags for difficulty (easy, hard, etc) under the same color.

**Comment by juliushaertl** [comment]
We rely on the color picker from the vue components for that https://nextcloud-vue-components.netlify.app/#/Components/ColorPicker?id=colorpicker

> This could potentially mean adding a text display of the hex code and a place for input of hex codes.

Not sure if that is something to add to the vue component or if that is to technical to show a hex value cc @nextcloud/designers

**Comment by stefan-niedermann** [comment]
Maybe some kind of copy icon that copies the hex code into clipboard instead of directly showing the hey code?

**Comment by juliushaertl** [comment]
But where do you paste it then :wink:

**Comment by jiblett1000** [comment]
I'm not terribly familiar with the nextcloud components but I have messed around with Vue a bit. From looking at the component documentation linked by @juliushaertl, it would seem that the component takes a hex code in a string format as it's value. I'm guessing it would be possible to make a separate text input that binds to the same data property as the color picker. 

Also, rather than creating a separate color code output, maybe it makes more sense to just output to that same text field input which can be copied and/or modified there directly if needed. Hopefully I'm making some sense here.

**Comment by jiblett1000** [comment]
However, it does seem like this should be default functionality for the color picker in general.

**Comment by skjnldsv** [comment]
> Not sure if that is something to add to the vue component or if that is to technical to show a hex value cc @nextcloud/designers

for @jancborchardt

**Comment by JadeVane** [comment]
Using hexadecimal to select colors is a very convenient way, I really hope that I can select colors in this way.

**Comment by stefan-niedermann** [comment]
@JadeVane please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue.

**Comment by juliushaertl** [comment]
:ping_pong: @jancborchardt
