### ISSUE TITLE
users are no longer able to remove themselves from a card

### ISSUE THREAD

**Issue by MB82515** [nextcloud/deck#1921]
### Steps to reproduce
open a deck, create a card and assign it to you.
Now, try to remove yourself from this card. This is no longer working

### Expected behaviour

You should be able to remove yourself from the card.

### Actual behaviour
You cannot remove yourself from the card

## Server configuration detail

**Operating system:** Linux 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64

**Webserver:** Apache/2.4.37 (centos) OpenSSL/1.1.1c (fpm-fcgi)

**Database:** mysql 10.3.17

**PHP version:** 

7.4.5
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, apcu, igbinary, msgpack, zip, redis, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => c98ec6c839cd1c86e69900c8dbc2fe457b6fd7d6ae626cfa6247b1774dfac1444b2d9cfbc0060af2a891c10d74bc0acfbf8b70f341db05429825eabf2a406bff
                            [current] => 
                        )

                    [.user.ini] => Array
                        (
                            [expected] => 4843b3217e91f8536cb9b52700efb20300290292cf6286f92794d4cec99df286afeb7dd6c91b1be20bc55eda541eef230a5c5e7dcd46c189edd0ed1e80c6d3f5
                            [current] => 
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [core/img/filetypes/mindmap.svg] => Array
                        (
                            [expected] => 
                            [current] => 5a72a8b048dc999c3603b9eb56221198f9fdac4765329921634b7cac47cbe0b85f09db85953f49fab9db774528d81df941bfb3e5250a63003701f253a0525e2a
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - announcementcenter: 3.7.0
 - apporder: 0.9.0
 - browser_warning: 0.2.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - deck: 1.0.1
 - drawio: 0.9.5
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_downloadactivity: 1.7.0
 - files_fulltextsearch: 1.4.2
 - files_mindmap: 0.0.21
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trackdownloads: 1.7.0
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.6
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - keeweb: 0.6.2
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.6
 - notes: 3.3.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - polls: 1.4.3
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quota_warning: 1.7.0
 - ransomware_protection: 1.6.1
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - user_ldap: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - accessibility
 - admin_notifications
 - encryption
 - files_external
 - files_videoplayer
 - group_everyone
 - mail
 - nextcloud_announcements
 - photos
 - recommendations
 - support
 - wopi

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "debug": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "rsworcloud.netzwiesel.net",
        "cloud.rs-wor.de"
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "https:\/\/rsworcloud.netzwiesel.net",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "auth.bruteforce.protection.enabled": true,
    "loglevel": "3",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "enable_avatars": false,
    "lost_password_link": "disabled",
    "app_install_overwrite": [
        "spgverein",
        "gluusso",
        "admin_notifications",
        "dashboard",
        "documents",
        "mindmap_app",
        "defaultgroup"
    ],
    "maintenance": false,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
cleanUpJobOffset: 150enabled: yesinstalled_version: 1.8.0s01_lastChange: 1589554956s01has_memberof_filter_support: 1s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: cy0yTnNoZWdus01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: DC=paed,DC=locals01ldap_base_groups: DC=paed,DC=locals01ldap_base_users: DC=paed,DC=locals01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: displaynames01ldap_dn: CN=M B,CN=users,DC=paed,DC=locals01ldap_dynamic_group_member_url: s01ldap_email_attr: mails01ldap_experienced_admin: 0s01ldap_expert_username_attr: s01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_ext_storage_home_attribute: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: (|(cn=Lehrer)(cn=Schnattergruppe)(cn=Schueler))s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: members01ldap_groupfilter_groups: Lehrer
Schnattergruppe
Schuelers01ldap_groupfilter_objectclass: s01ldap_host: ldap://127.0.0.1s01ldap_login_filter: (&(&(|(objectclass=person))(|(|(memberof=CN=Schnattergruppe,CN=Users,DC=paed,DC=local)(primaryGroupID=1831))(|(memberof=CN=Lehrer,OU=Lehrer,DC=paed,DC=local)(primaryGroupID=1724))(|(memberof=CN=Schueler,OU=Schueler,DC=paed,DC=local)(primaryGroupID=1104))))(samaccountname=%uid))s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 0s01ldap_loginfilter_username: 1s01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 10389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: defaults01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: Schnattergruppe
Lehrer
Schuelers01ldap_userfilter_objectclass: persons01ldap_userlist_filter: (&(|(objectclass=person))(|(|(memberof=CN=Schnattergruppe,CN=Users,DC=paed,DC=local)(primaryGroupID=1831))(|(memberof=CN=Lehrer,OU=Lehrer,DC=paed,DC=local)(primaryGroupID=1724))(|(memberof=CN=Schueler,OU=Schueler,DC=paed,DC=local)(primaryGroupID=1104))))s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** OS X 10.15, but same issue can be found using a Windows PC with various  Firefox versions

## Logs

<details><summary>Web server error log</summary>

```
no logs are available
```
</details>

<details><summary>Nextcloud log</summary>

```
no logs are available
```
</details>

<details><summary>Browser log</summary>

no logs are available
</details>

**Comment by xtrasimplicity** [comment]
**Temporary work around:**

1. Click _Card Details_
2. Remove your name from the list next to _Assign a user to this card_

**Comment by jakobroehrl** [comment]
It's working for me on the latest master:
Click on the 3 dot card menu - assign to me: user is shown on the card
Click on the 3 dot card menu - unassign myself: user is removed from the card

![grafik](https://user-images.githubusercontent.com/24530680/84761317-90bfd600-afc9-11ea-9f22-ea75b6262ca5.png)

![grafik](https://user-images.githubusercontent.com/24530680/84761347-987f7a80-afc9-11ea-8723-47c395914e1f.png)

**Comment by juliushaertl** [comment]
The fix was merged some hours ago with https://github.com/nextcloud/deck/pull/2027 :wink:
