### ISSUE TITLE
Need help in uploading an attachment via API

### ISSUE THREAD

**Issue by morbificagent** [nextcloud/deck#1938]
Hi there,

actually i am trying to get mail2deck running.
Its a github project receiving mails via imap, extracting text and attachments and create a card for it.
[https://github.com/putt1ck/mail2deck/tree/master](url)

But the import of attachments via api doesnt work. (Cards in generally are created correctly)
i have tried to get it to work by changing its code a little bit but i am not good in php and such programming things ;-)

I have asked on the project-site of mail2deck but i was the only one there... it's frustrating empty. So i hope someone here can help as it could be a small thing.

The Mail2Deck feature would be such great.

Here is the problematic part with the fileupload after my changes. The original one is viewable in the link above.

`public function addAttachment($data) {
        global $mailData;
        global $cardId;
        global $boardId;
        global $stackId;
        
        
        $fullPath = '/home/mail2deck/mail2deck';

        for ($i = 1; $i < count($mailData->fileAttached); $i++) {
            $data = array(
            	'type' => 'deck_file',
                'file' => new CURLFile($fullPath."/attachments/" . $mailData->fileAttached[$i])
              );
            $this->apiCall("POST", NC_SERVER . "/index.php/apps/deck/api/v1.0/boards/".$boardId."/stacks/".$stackId."/cards/".$cardId."/attachments", $data);
        }
    } `

I have checked if all variables are filled probably and they are.
I have checked if the attachments are on the disk under $fullPath."/attachments/ and they are.

So i cant find the problem.

If no one wants to review the code someone eventually can give me an example of uploading a file via api as card attachment.

Have a nice evening all together

**Comment by putt1ck** [comment]
Maail2deck site not empty but will only get attention periodically, when time permits. I did think attachments were working so that will need looking into.

**Comment by morbificagent** [comment]
I am sorry for that.
I thought there was no one who is actively looking at it and because i was trying the whole day get it work i posted here.

But it would be great if you could take a look at it.

There was a dir hardcoded in your script (D:\...) but when i change it into my attachments dir it doesn't work too...
And the changed part i wrote here isnt working too.

**Comment by morbificagent** [comment]
Not sure if it belongs to the same problem, but the nextcloud-log shows:

`{"reqId":"4AD7SWWjB58DASKCfOHq","level":3,"time":"2020-05-22T07:35:05+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"deckbot","app":"PHP","method":"GET","url":"/index.php/apps/deck/api/v1.0/boards","message":"count(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud/lib/private/AppFramework/Http/Request.php#450","userAgent":"--","version":"18.0.4.2","id":"5ec7811c9db13"}

{"reqId":"FHT3MOd2Jds9iVwTY3XE","level":3,"time":"2020-05-22T07:35:05+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"deckbot","app":"PHP","method":"GET","url":"/index.php/apps/deck/api/v1.0/boards/16/stacks","message":"count(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud/lib/private/AppFramework/Http/Request.php#450","userAgent":"--","version":"18.0.4.2","id":"5ec7811c9db08"}`

**Comment by juliushaertl** [comment]
The errors don't look related, but for further debugging I would suggest to check for the actual http status and response of that api call in the script. That should give a hint about what is going wrong.

Closing this since it is not really related to the deck app and should be handled in the mail2deck repo.
