### ISSUE TITLE
Edit window stuck switching between cards - and more errors

### ISSUE THREAD

**Issue by NukeManDan** [nextcloud/deck#1939]
**Describe the bug**
In the card description, you hit edit, and a window opens to edit text. There is a bunch of issues:

1. I am using dark mode, this edit window is still white! (Minor)
2. Editing mode between cars gets stuck with one of the card's descriptions
3. There is no obvious way to stop editing the card - clicking outside the box, shift+enter, ect. The "view" icon appears to be the only way. **Please please have a keystroke do this :pray: **
4. **Major** - When moving to any other card with a stuck editing mode, on exiting it overrides the description of the new card.

**Screenshots**
![deck_edit_issue](https://user-images.githubusercontent.com/35669742/82599461-914f8300-9b69-11ea-9919-6f740acbde53.gif)

**Client details:**
 - OS: Linux MATE 20 LTS
 - Browser Firefox 76.0.1
 - Device: Laptop

<details>
<summary>Server details</summary>

**Operating system**:
ubuntu server 20

**Where did you install Nextcloud from:**
Vanilla: https://github.com/nextcloud/vm
Plus onlyoffice
```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Please split those into separate issues since otherwise this becomes really hard to track. For the new tickets please also check the browser console for errors during the time you encounter the issues.
