### ISSUE TITLE
Fix margin in header bar

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#194]
Files:
![margin-files](https://user-images.githubusercontent.com/16517095/27305347-9258e1ea-5541-11e7-9cd0-cbd4718f1e94.png)

Deck:
![margin-deck](https://user-images.githubusercontent.com/16517095/27305361-9c30dcd6-5541-11e7-9d25-1598cd5639c0.png)

**Comment by juliushaertl** [comment]
@artemanufrij So this was the issue caused by the audioplayer?

**Comment by artemanufrij** [comment]
No, it's our issue :)

**Comment by juliushaertl** [comment]
Ah you mean the space between the togge button and the home icon :+1:

**Comment by artemanufrij** [comment]
yes

**Comment by pixelipo** [comment]
wait a bit on this. I have an open PR that makes some changes to the breadcrumbs in Files.

**Comment by artemanufrij** [comment]
OK, I will wait for your feedback

**Comment by artemanufrij** [comment]
@pixelipo hey Marin had you time to open a PR?

**Comment by pixelipo** [comment]
I did, long time ago, but it hasn't been merged yet. See nextcloud/server#5229

**Comment by artemanufrij** [comment]
ah... ok... I see. Thank you for your feedback!

**Comment by juliushaertl** [comment]
Actually fixed with the new breadcumbs in 13 and adapted in #350
