### ISSUE TITLE
l10n: Strings are not present at Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/deck#1943]
https://github.com/nextcloud/deck/blob/1d589fe3e6f5117a246671eb3ceb98728b112501/src/components/cards/CardMenu.vue#L31

Neither "Unarchive card" nor "Archive card".

**Comment by rakekniven** [comment]
<img width="398" alt="Bildschirmfoto 2020-05-23 um 13 51 32" src="https://user-images.githubusercontent.com/2069590/82732187-e3c8a500-9d0b-11ea-9f9e-b1ae84c25c03.png">

**Comment by ahangarha** [comment]
I am sorry for asking the question here but I cannot find nextcloud on Transifex. the link in `contribution.md` shows 404.

**Comment by rakekniven** [comment]
@juliushaertl Both strings still do not show up at Transifex 👎

**Comment by juliushaertl** [comment]
Yes, the PR was not merged yet :wink:

**Comment by juliushaertl** [comment]
Done, should be there after the next sync tonight.
