### ISSUE TITLE
Indicate comments - unread or not

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#1954]
**Is your feature request related to a problem? Please describe.**
I just read #1886 and #1933 and the answers given to the comment section in general irritated me. Despite of bugs discussed in that issues, it seems that the desired behaviour of the app is, that only unread comments shows up. In my opinion that is not a good solution, this is why: 90% of my cards don't have comments and I don't check comments by default. Maybe I check a card, read a comment, don't act in that moment, and start the card a week later, I won't recognise these maybe important comments.

**Describe the solution you'd like**
Make two symbols: One for unread comments, one for already read comments. (Use different colors for the same icon).

**Describe alternatives you've considered**
Or, in sidebar of that card, put a number in the comment-toggle and add a strong contrast color to that number, so I'm aware of the number of comments and check that tab.

**Comment by juliushaertl** [comment]
Seems basically like https://github.com/nextcloud/deck/issues/730 to me :wink:
