### ISSUE TITLE
Missing support for bi-directional text

### ISSUE THREAD

**Issue by ahangarha** [nextcloud/deck#1959]
**Describe the bug**
Deck doesn't support bidi (bidirectional text) and as it is by default LTR, it doesn't show RTL text or mixed LTR and RTL text properly.

**To Reproduce**
1. Go to Deck
2. Make or edit any board or card and add this text "یک two سه four"
4. See how it appears (it shows یک on the left side as if it is LTR)

**Expected behavior**
The text should appear like the following screenshot:
![image](https://user-images.githubusercontent.com/11241315/82910571-06fb8a80-9f80-11ea-8ef3-d6c40dc73144.png)

**Screenshots**
This is how it looks now:

![image](https://user-images.githubusercontent.com/11241315/82910802-4fb34380-9f80-11ea-8328-7044955a633a.png)

and this is how I am solving the problem by using my own firefox addon called [Add Bidi Support](https://addons.mozilla.org/en-US/firefox/addon/add-bidi-support/) which added `dir="auto"` to elemtes like `p`:
![image](https://user-images.githubusercontent.com/11241315/82911085-b3d60780-9f80-11ea-876f-f40133809240.png)

**Client details:**
 - OS: Kubuntu 20.04
 - Browser Firefox
 - Version 76.0.1 (64-bit)
 - Device: desktop

**Comment by juliushaertl** [comment]
I must admit I don't have any experience with bi-directional text. Is there a way this could be enabled globally, because adding `dir="auto"` to every element doesn't sound like the most elegant way to solve this?

cc @jancborchardt Maybe you know if we already handle this anywhere else in Nextcloud?

**Comment by jancborchardt** [comment]
> adding `dir="auto"` to every element doesn't sound like the most elegant way to solve this?

Could be the necessary step – similar to `* { box-sizing: border-box; }`.

But I also lack the experience on that. @ahangarha would you like to submit a pull request to fix this?

**Comment by ahangarha** [comment]
I am not familiar with code base but if you approve my method, I can give it a try.

**Comment by juliushaertl** [comment]
OK, it seems that having a global `dir="auto"` would basically flip the whole element flow once the browser switches to rtl.

![image](https://user-images.githubusercontent.com/3404133/82928976-3fe92e80-9f83-11ea-807c-9191023320d6.png)


While I'm not entirely sure if having the UI switched around as well would be something wanted, I think that doing for individual dir tags would then be the way to go, just on text nodes where it makes sense then.

**Comment by ahangarha** [comment]
This is not a solution. There are many situation in which the user need to make RTL and LTR text in the app. Some issues might be RTL but some might be LTR.

Any elements that can contain text which can be either RTL or LTR, it should have `dir="auto"` attribute. As the result, I can have a card with description which has RTL text but also some LTR lines (such as links or code or...)

If needed, I can make a demo for it.

**Comment by juliushaertl** [comment]
> This is not a solution. There are many situation in which the user need to make RTL and LTR text in the app. Some issues might be RTL but some might be LTR.

Ok, makes sense of course.

> Any elements that can contain text which can be either RTL or LTR, it should have `dir="auto"` attribute. As the result, I can have a card with description which has RTL text but also some LTR lines (such as links or code or...)
> 
> If needed, I can make a demo for it.

That would be awesome. 👍
