### ISSUE TITLE
Feature Request; Application Group Access

### ISSUE THREAD

**Issue by kneiser** [nextcloud/deck#196]
### Steps to reproduce
1. Create a Nextcloud group (i.e. DevProj) and add users to new group.
2. Associate Desk App with the group.
3. Maybe even setup a group administrator.

### Expected behaviour
Only users that are members of the group will see the Deck app in the appmenu and have access to it.

### Actual behaviour
Nothing available now.

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by juliushaertl** [comment]
@kneiser I cannot reprodce this issue here with Deck 0.2.0 and NC12, can you please fill out the complete issue template?
