### ISSUE TITLE
Horizontal scrolling impossible on mobile devices

### ISSUE THREAD

**Issue by ChaoticEvilDM** [nextcloud/deck#1960]
Horizontal scrolling is not possible on small touch screen mobile devices with any gestures. You need to drag a card or a lane with you.

Affected versions:
Deck  >1.0.0

Tested on:
Android 7.0 with Chrome 81.0.4044.138
EDIT: Android 10 with latest Chrome Version
IoS 13.5.1 with Safari

**Comment by juliushaertl** [comment]
For some reasons tapping outside of the scrollcontainer once seems to stop the scroll gesture, not sure how to fix that yet. 

As a workaround I could always start scrolling again with double-tabbing the empty white background of the board itself.

**Comment by benks-io** [comment]
Also on a Dekstop Browser scrolling vertically to the last list when having lots of them is not possible.

**Comment by guldi011** [comment]
When switching to the desktop version (e.g. under Android chrome), the deck is completely unusable since all trys to scroll result in moving lists, assuming I touch a white surface and not a card. The same behaviour happens under the desktop version (which I personally don't think is cool since I often move lists unwanted).
I'd assume it was desired to move lists only by grabbing them on top (when the mous pointer is over the list name and the pointer changes to a hand) ?
I know this does not solve the scroll issue (which is still a very nasty thing :-( )directly. But maybe the desktop mode works better under IOS / Android browsers (no double tapping needed which works often but not allways) ?

My JS knowledge is very very limited, still I'd love to help solve this. just where to start ?


**@benks-io**: does scrolling by cursor fix your issue ? So far cursor scrolling on desktop worked under chrome for me

**Comment by benks-io** [comment]
@guldi011 no - I cannot scroll sidewards by clicking and dragging anywhere (firefox).

**Comment by piiskop** [comment]
Scrolling in any direction is impossible if trying for the second time.

**Comment by prismopensource** [comment]
Having the same problem on iOS 14.0.1. After you scroll horizontally for just a bit, vertical scrolling stops working completely. The double tap workaround doesn’t seem to work for me, only a refresh will enable vertical scrolling again.

**Comment by roboticsalign** [comment]
I have the same problem on iOS, android and windows, if I'm using the touchscreen. So I would suggest to rewrite the topic to "Touchscreen: Horizontal scrolling impossible"

In #846 we had the problem, that we could not move cards if the screen was scrolled to the right. That is improved and now, it's possible to move cards. But this improvement seems to be the reason for the scroll problem to me. 

In the meantime it is possible to move cards by using the context menu. Could it be an option to fix the cards and lists, if touch is detected or by a manual switch?

**Comment by vincentbitter** [comment]
> Could it be an option to fix the cards and lists, if touch is detected or by a manual switch?

My laptop also has a touch screen, so disabling drag&drop if touch is enabled will give me a lot of trouble. Although I completely agree something should be done to make Deck usable on a iOS. Maybe a different drag&drop library would be an option?

**Comment by vincentbitter** [comment]
Seems like the same issue as https://github.com/kutlugsahin/vue-smooth-dnd/issues/134

**Comment by dodedodo** [comment]
Mobile (chrome):
- On page load I'm able to scroll either horizontal or vertical, but only once.
- On a second try I cannot scroll either way. If I tap or double-tap anywhere in the browser I can subsequently scroll again, but only once. 
- This does not apply to the sidebars or modal. 

Desktop (chrome, firefox):
- I can scroll sideways with a sideways-scrolling action (such as on a touchpad, or fancy mouse with 2-way scrolling) 
- I can scroll sideways using the teeny-tiny 2px scrollbar at the bottom of the page. But that is easily overlooked, and quite hard to hit.

On Android, you should really be using stefan-niedermann's [app](https://f-droid.org/en/packages/it.niedermann.nextcloud.deck/).

**Comment by favincen** [comment]
> On Android, you should really be using stefan-niedermann's [app](https://f-droid.org/en/packages/it.niedermann.nextcloud.deck/).

Unfortunately there's no deck app for iOS  😭

**Comment by d4g** [comment]
I just started using deck and it is really annoying. You can barely use it on an iPad.

**Comment by d4g** [comment]
After trying it a bit more, we should change the issue to „Deck is unusable on mobile phones“:
- vertical and horizontal scrolling does not work most of the time
- All dropdown-menus are broken and are overlapped by the onscreen keyboard
- Drag and drop of cards is mostly broken
- The whole UX experience is incredibly bad on smartphone
- Text-edit mode is entered on smartphone on klick which then again results on the popup of the keyboard
- Zooming is broken. If you manage to zoom in a little you can’t  zoom out again
- The viewport does not work when you switch from landscape to portrait and vice versa

**Comment by favincen** [comment]
> Seems like the same issue as [kutlugsahin/vue-smooth-dnd#134](https://github.com/kutlugsahin/vue-smooth-dnd/issues/134)

There is a working workaround proposed in that page. Could it be implemented in Deck to solve the issue and make Deck usable ou touchscreens ??? Thanks a lot !

**Comment by JordanDIG** [comment]
It's been almost 2 years that the problem is raised and still persists, it's a shame

**Comment by tschombes** [comment]
I am a new NC user and this bug is really,really annoying. Impossible to use this app on a mobile.

**Comment by JordanDIG** [comment]
Yep and welcome to nextcloud

**Comment by piiskop** [comment]
Nextcloud is a like Estonia. It's a piece of shit but nothing's better, isn't it?.

**Comment by JordanDIG** [comment]
> Nextcloud is a like Estonia. It's a piece of shit but nothing's better, isn't it?.

Calm it is useless to get angry nextcloud is a good solution, it has some bugs but good

**Comment by favincen** [comment]
> Nextcloud is a like Estonia. It's a piece of shit but nothing's better, isn't it?.

It's a free software. So you're welcome to submit a fix in a pull request instead of waiting for someone else to solve your problem ! And if you're not able to, you'd rather ask politely (as many of us did in this thread)...

**Comment by favincen** [comment]
> > On Android, you should really be using stefan-niedermann's [app](https://f-droid.org/en/packages/it.niedermann.nextcloud.deck/).
> 
> Unfortunately there's no such deck app for iOS devices, which leaves quite a significant part of users alone in the dark. 😭

Actually there is now a NC deck iOS app ([here](https://apps.apple.com/fr/app/nextcloud-deck/id1570892788 )). Current version 0.9.2 is still pretty rough (at least on iPhone, I haven't tried on iPad), but at least it exists and a new version is currently published each month.
