### ISSUE TITLE
Tasks/Cards with Time Estimates

### ISSUE THREAD

**Issue by CornMaster** [nextcloud/deck#1978]
I've recently started recording the estimated time to completion of a task on my paper to-do list, and find it a great motivator to get things done.

It would be great if when creating or editing a card, you could add a field for time estimate.  Then add in a sort mode for a card that will allow you to sort tasks by time estimate, or filter mode to filter for tasks that will take a certain amount of time.  Ideally, that time estimate would be present on the face of the card along with the task name, and any other labels and indicators.

More advanced functionality could later be built on this simple time field like recommendations of what tasks to take on, or time tracking for tasks so that you could measure (for the purpose of accounting) how long was spent on a task, and compare it to the estimate.  Useful for freelancers who may be charging clients, or project managers.

**Comment by juliushaertl** [comment]
I'd say this would be something for #1833 which is a way more flexible approach than manually supporting various metadata.
