### ISSUE TITLE
Sidebar header not showing correctly after upgrade to 1.0.2

### ISSUE THREAD

**Issue by marc-romu** [nextcloud/deck#1980]
**Describe the bug**
After upgrading Deck to 1.0.2 on Nextcloud 18.0.4, sidebar's header has a fixed height of 52px, which doesn't allow title and subtitle to be read. Checked on Firefox, Chrome, Edge and Opera.

**To Reproduce**
1. Upgrade to Deck 1.0.2. My Nextcloud version is 18.0.4.
2. Go to any existing board or create a new one.
3. Click on an existing card or create a new one.
4. Click on it to show up its sidebar.
5. Title and subtitle are not shown.

**Expected behavior**
![imatge](https://user-images.githubusercontent.com/49920661/83645755-22cfe380-a5b3-11ea-993d-89fea4133996.png)

**Screenshots**
Problem:
![imatge](https://user-images.githubusercontent.com/49920661/83645304-9d4c3380-a5b2-11ea-8384-eb7efed5ef9d.png)

If I disable "height: 52px;" on Chrome's Inspector everything shows up correctly:
![imatge](https://user-images.githubusercontent.com/49920661/83645414-c10f7980-a5b2-11ea-9a8b-13abcafd6fc9.png)

**Client details:**
 - OS: Windows 10
 - Browser: Firefox 76.0.1, Chrome 83.0.4103.61, Edge 83.0.478.37 and Opera 68.0.3618.125
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**: Linux 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64

**Web server:** Apache/2.4.37 (centos) OpenSSL/1.1.1c mod_fcgid/2.3.9 (fpm-fcgi)

**Database:** mysql 10.3.17

**PHP version:** 7.4.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, apcu, imagick, smbclient, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Where did you install Nextcloud from:**

**Signing status:**
```
Array
(
    [deck] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- deck
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [deck] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

**List of activated apps:**
```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - deck: 1.0.2
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_automatedtagging: 1.8.3
 - files_external: 1.9.0
 - files_fulltextsearch: 1.4.2
 - files_pdfviewer: 1.7.0
 - files_readmemd: 1.1.4
 - files_retention: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - fulltextsearch: 1.4.1
 - issuetemplate: 0.6.0
 - limit_login_to_ip: 3.0.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.6
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - passwords: 2020.5.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quota_warning: 1.7.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - support: 1.1.0
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - text: 2.0.0
 - theming: 1.9.0
 - timetracker: 0.0.42
 - twofactor_backupcodes: 1.7.0
 - unsplash: 1.1.5
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - bruteforcesettings
 - cospend
 - encryption
 - files_accesscontrol
 - mail
 - notes
 - onlyoffice
 - ransomware_detection
 - ransomware_protection
 - sharebymail
 - socialsharing_email
 - spreed
 - survey_client
 - user_ldap
```

**Nextcloud configuration:**
```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.23.162",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "http:\/\/192.168.23.162\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "loglevel": 2,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "updater.release.channel": "stable"
}
```
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Nothing relevant.
```

#### Browser log
```
Nothing relevant.
```

</details>

**Comment by dd86k** [comment]
Just for fun I went to the Style Editor when unchecking one (inlined) style fixed it, the parent that holds the title and subtitle.

![image](https://user-images.githubusercontent.com/8390674/83657352-bc38ce80-a58e-11ea-8d3b-9f87aff4434d.png)

**Comment by AaronADev** [comment]
Same issue on chrome and firefox, NC 18.0.4

**Comment by Nyco** [comment]
Same bug with approx same conditions: NC 18 and 19, Chrome and Firefox

**Comment by sgdox** [comment]
Same problem on Brave Versión 1.9.76 Chromium: 81.0.4044.138.

**Comment by rkaraba** [comment]
Is there any progress on this issue?

**Comment by TorinKR** [comment]
The description shows that the App.vue file which is used to build Nextcloud has changed. Is it possible to change the files of an already working system ??

**Comment by ElpyDE** [comment]
As a possible **temporary hotfix** on running systems (until the bugfix will be released), you can use the [Custom CSS App](https://apps.nextcloud.com/apps/theming_customcss) and a CSS rule like this:

```css
header.app-sidebar-header div.app-sidebar-header__desc { height: auto !important; }
```
