### ISSUE TITLE
Broken font in verison 1.0.2

### ISSUE THREAD

**Issue by much-doge** [nextcloud/deck#1995]
**Describe the bug**
The title font on the right side is broken in version 1.0.2, before the update it was ok.

**To Reproduce**
1. upgrade to version 1.0.2
2. go to deck, select a card, the title is distorted, unreadable

**Expected behavior**
The title should not look broken.

**Screenshots**
![Screenshot from 2020-06-07 18-26-10](https://user-images.githubusercontent.com/20739853/83967570-0e5e5480-a8ed-11ea-9824-e1c30826ce80.png)

**Client details:**
 - OS: Fedora 300
 - Browser: FIrefox 76
  - Device: Laptop

**Comment by stefan-niedermann** [comment]
Seems to be a duplicate of https://github.com/nextcloud/deck/issues/1980

@much-doge can you confirm this?

**Comment by much-doge** [comment]
> Seems to be a duplicate of #1980
> 
> @much-doge can you confirm this?

Ahh, yes it is the same. closing this one.
