### ISSUE TITLE
Autosave description on card close

### ISSUE THREAD

**Issue by 4rnoP** [nextcloud/deck#1996]
**Is your feature request related to a problem? Please describe.**
Actually, to save a card description, you need to wait something like 3 second without doing anything, and if you close or switch card view, the modifications are lost.

**Describe the solution you'd like**
If you close the description editor or close/switch card view, it automatically save the description without any delay.

**Describe alternatives you've considered**
Add a modal asking if we really want to lost changes

**Comment by juliushaertl** [comment]
Yes, the description should definitely be saved then. I think that was the case before 1.0 so marking as a regression.
