### ISSUE TITLE
Add card dependencies

### ISSUE THREAD

**Issue by frau-underscore-lutzn** [nextcloud/deck#1997]
Thanks for this sleek-looking and well-working Netxcloud app!

I would like to use deck to track a project I'm currently working on. Quiet a number of tasks - or cards in deck terms -  depend on some other card(s) to be completed. I'd like to reproduce those dependencies in deck as well, to not lose the overview.

I would like to suggest the addition of card-dependencies that can be assigned in the card details view. A card should be able to depend upon multiple other cards. Once set the card detail view of all cards, which have been linked by dependency, should show something along the lines of "Depends on [Link to depending Card]" or "[Link to depending Card] depends on this" in reverse.
As an example in Jira this feature is called "issue link", if I remember correctly.

I imagine that if this were to be implemented and used alongside due dates and tags, a static Gantt chart could be rendered. (**Not** part of the feature request, just imagining.)

I have searched the open issues and could not find a request describing the above. In case I have overlooked an existing issue for this matter, feel free to close this as duplicate.

**Comment by juliushaertl** [comment]
Thanks for the kind words :)

This was already proposed in https://github.com/nextcloud/deck/issues/272 however we currently have no plans to implement such a feature. Just to be sure to mention this again:

> This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

Feel free to continue discussion possible ways to implement this in the closed ticket. We can always reopen it once someone is around to pick it up.
