### ISSUE TITLE
Left sidebar: Shared Boards' title not translated

### ISSUE THREAD

**Issue by aktivde** [nextcloud/deck#2001]
**Describe the bug**
Since updated to 1.0.2 the left sidebar doesn't display the "shared boards" label correctly and instead shows notification that translation is not required.

**To Reproduce**
Update to 1.0.2

**Expected behavior**
Label should be "Shared Boards" or at least "Geteilte Boards"

**Screenshots**
![image](https://user-images.githubusercontent.com/65334274/84039960-4a072600-a9a2-11ea-87be-39a215738664.png)

Nextcloud 19, Deck 1.0.2, German

**Comment by juliushaertl** [comment]
I can reproduce that with the informal german.

**Comment by rakekniven** [comment]
Fixed at Transifex and double checked all occurences.

Issue can be closed from my POV.

**Comment by juliushaertl** [comment]
@rakekniven Any idea why that might have happened in the first place? Is there anything wrongly annotated?

**Comment by rakekniven** [comment]
Oh yes, there is some kind of auto matching active at Transifex and some automatism fills in this string in my name. Happened many times and I do not find the cause. Either does Transifex. Sorry for the trouble.

**Comment by juliushaertl** [comment]
Good to know, thanks for taking care :+1:
