### ISSUE TITLE
Card count on column header/title/description

### ISSUE THREAD

**Issue by Nyco** [nextcloud/deck#2009]
**Is your feature request related to a problem? Please describe.**
Sometimes you have to scroll down to see how many cards there is in this column.

**Describe the solution you'd like**
Use the column header/title/description to display the number of cards in the column

**Describe alternatives you've considered**
I can't think of any, only to be able to live without :)

**Additional context**
If limits #2008 are implement, then it would be even cooler to display "n/m", n being the number of actual cards in the column, and m being the limit. Example "3/5" means 3 cards out of a limit of 5 cards.

**Comment by juliushaertl** [comment]
I'd say we could add the counter if a limit is somehow available, but otherwise we should avoid adding more to the stack header to keep the interface clean.
