### ISSUE TITLE
Feature request - Support for images (inline/attachment)

### ISSUE THREAD

**Issue by weipah** [nextcloud/deck#202]
It would be nice to have the possibility to insert images like screenshots either inline or as an attachment from the clipboard, via url or from the nc filesystem.

**Comment by juliushaertl** [comment]
Do you mean inserting into the card description or just attach them to the card?

For the attachments there is already #17

**Comment by weipah** [comment]
@juliushaertl I think both would be nice. Directly inline in the description and as attachment if it could be opened in a lightbox for example for direct view.
I dislike the trello approach on this, because if I remember correctly you have to download the file and rely on your browser to open it directly. When you use a lot of screenshots to document something on a card that is not very convenient.

**Comment by MuhammadShaban** [comment]
any new news

**Comment by art2crazy** [comment]
That's something I'd love to see, right now only way to include an image is to have it somewhere available through http link `![Image](http://....jpg)`, but that doesn't work for pics uploaded to the NC with Share links, it can only be included inline as link `[link](http://... )`

**Comment by juliushaertl** [comment]
Fixed with #488

**Comment by pdschandler** [comment]
Sorry to reopen this, but was the option of attaching a file via the Nextcloud filesystem abandoned? It's mentioned in the original first comment but I don't see it being discussed any further from there. That functionality would be way more useful to us than attachment of files on a local filesystem. I can open up a new feature request but wanted to make sure this wasn't already being covered by another issue or specifically abandoned for some reason.
