### ISSUE TITLE
Description icon is missing when you add notes to a moved card.

### ISSUE THREAD

**Issue by cappuMUC** [nextcloud/deck#203]
### Steps to reproduce
1. create card on stack 1
2. move card to stack 2
3. add description

### Expected behaviour
The description icon should appear in the card.
![descripton_icon_present](https://user-images.githubusercontent.com/9985266/27425815-f36bfc34-5739-11e7-97ae-9efe97120999.png)

### Actual behaviour
The description icon is missing.
![description_icon_missing](https://user-images.githubusercontent.com/9985266/27425816-f36d43be-5739-11e7-82ed-88f58d6d6fc1.png)

After setting a due date the icon appears and stays even if you remove the due date again.
![description_icon_duedate](https://user-images.githubusercontent.com/9985266/27425944-5a1b8bb6-573a-11e7-82d4-962ccb4b832d.png)

**Comment by pixelipo** [comment]
I can confirm this issue. Additionally, if you move the issue again to another card, description disappears completely.

So it means that description is not saved properly in the first place

**Comment by juliushaertl** [comment]
Sounds similar to https://github.com/nextcloud/deck/issues/147 where the changes from the CardService are not propagated to the StackService iirc.
