### ISSUE TITLE
Simplified Editor / Popup-Window for Card Details

### ISSUE THREAD

**Issue by nousernameavailableanymore** [nextcloud/deck#2031]
Can we get a "simplified editor" just like in the NC calendar, which brings up a pop-up window to edit the card details.

In the calendar this looks a lot more stylish than the clunky sidebar which eats up a lot of space.

![image](https://user-images.githubusercontent.com/45376324/84718750-c5a43c80-af79-11ea-9efd-d94fa41e7dfb.png)

**Comment by stefan-niedermann** [comment]
Duplicate of https://github.com/nextcloud/deck/issues/1941#issuecomment-639356502
