### ISSUE TITLE
Progress which shows percentage of completion by date

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/deck#2038]
To be able to watch the progress of each single task, there should be a column / input field of the estimated percentage of completion (by date).

regards, hitam4450

**Comment by stefan-niedermann** [comment]
Hi @hitam4450 
you mean something like this?

**Comment by hitam4450** [comment]
Hi, thanks  for your suggestion !
Yes, i think similar to the proposal...however most likely in percentage value!

**Comment by stefan-niedermann** [comment]
Well this is a screenshot from the current web UI (we also have this in the Android app), **so it's already there**.

It counts the tasks in the description

```
- [ ] Item 1
- [x] Item 2
```
will display exactly the screenshot (`✔️ 1/2`)

**Comment by hitam4450** [comment]
Sorry, i could not find it..otherwise I would have not mentioned it !

**Comment by stefan-niedermann** [comment]
Do you have a description with checkboxes? (see my sample above)

**Comment by hitam4450** [comment]
No, I do not have !

**Comment by stefan-niedermann** [comment]
Well, as i said: The progress in the card overview displays the count of the checked checkboxes in the desccription. To see it you obviously need checkboxes in the description. Or am i missing something here? Do you mean something different? Please offer a screenshot or a step by step description of you wanted behavior.

**Comment by hitam4450** [comment]
OK,, many thanks for your kind support !

i checked all menu items double and triple...i could not repeat your advice ! impossible !
just forget it !
regards, hitam4450

**Comment by stefan-niedermann** [comment]
This is the behavior i am describing:

![ezgif-3-099188af16e4](https://user-images.githubusercontent.com/4741199/85006825-f099b680-b15a-11ea-9cf9-1228bd5d2ccb.gif)

Just want to make sure:
- If you mean something different please specify
- If you mean this, but it does not work for you, then it might be a bug (then we should reopen the issue and analyze the bug)

**Comment by juliushaertl** [comment]
Also see https://github.com/nextcloud/deck/issues/1937 for some longer discussion on on the explorability of this feature.

**Comment by hitam4450** [comment]
Underneath the expiration date, should be an input field to input a percentage for the completion of the task.

I remember such an input field in one of the very early releases.

![deck_1](https://user-images.githubusercontent.com/9738727/85027492-492c7c00-b17a-11ea-9bbd-892b307afc41.png)

**Comment by D-side** [comment]
@hitam4450 you can place checkboxes in the **description** (where you have "Update LINUX System") with the following syntax:

```markdown
Update LINUX System (or any other content you want for that matter)

- [x] Checked
- [ ] Unchecked

(Can have content after the list as well!)

- [ ] Can even have multiple lists in one description,
  task display combines the tasks across all the lists
```

This is (arguably) even more useful than a field with an arbitrary percentage, since it not only *indicates* progress, but also *explains* it, in a way forcing to be more specific about it. If you don't want that, you can still use this feature with a list like this:

- [ ] 10%
- [ ] 20%
- ...
- [ ] 100%

...and check its boxes top to bottom.
