### ISSUE TITLE
Response time of API

### ISSUE THREAD

**Issue by JulienSambre** [nextcloud/deck#2039]
Hi!

I am looking for using Deck on my private Nextcloud instance as a replacement for Kanboard which is great but a little overkill for my simple need.

Deck web interface is perfect for my needs but I also want to make my IA use it, as I do with Kanboard.

The API documentation is pretty clear (with some flaws on the doc, on due date for example) and is almost complete (didn't see in the documentation how to move a card, so I had to delete/recreate the wanted card in a different stack). I created a python interface pretty easily.

But the main issue I have is with API response time. It is very, very long to respond : for example, almost 9 seconds to made the 3 querries needed to get all the cards for one stack : 
1. Get the board id from the boards list : ~3 seconds
2. Get the stack id from the stacks list, from the board id : ~3 seconds
3. Get the cards list from the cards list, from the board+stack id : ~3 seconds

In comparison, I have the same things done in less than a second with Kanboard.

Is there any plan to optimize the API or is there any problem with my querry?

Thanks :).

**Comment by juliushaertl** [comment]
Please fill out the issue template to provide some details about your setup. I don't see a reason why those requests would take so long, on my personal instance they are all done within ~300ms

**Comment by JulienSambre** [comment]
@juliushaertl Of course. If you have a ~300 ms of response time, I have good hope :).

**To Reproduce**
Steps to reproduce the behavior:
1. HTTP call with basic auth on : https://[domain.name]/index.php/apps/deck/api/v1.0/boards

**Expected behavior**
I tried this call with python and directly on my browser via RESTer. My response time is between 2 and 3 seconds.

I just looked on browser dev console when accessing Deck and I saw that call to "https://[domain.name]/index.php/apps/deck" was a lot faster (~150 ms). Can't explain why. Deck seems to load pretty fast from my browser (1s for the all load).

My only problem seems to be with the API, which I would like to response in 300-500 ms if possible.

**Client details:**
N/A. I tried with Python 3.7 and via RESTer (Firefox 77, Windows 10).

<details>
<summary>Server details</summary>

**Operating system**:
Centos 7.7

**Web server:**
 nginx (docker container)

**Database:**
MySQL 8.x (docker container)

**PHP version:**
7.3.19

**Nextcloud version:** (see Nextcloud admin page)
18.0.6

**Where did you install Nextcloud from:**
I use the official nextcloud docker image, coupled with a dockerized NGinx & MySQL

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.2
  - drawio: 0.9.6
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.3.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - occweb: 0.0.7
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - rainloop: 6.1.4
  - recommendations: 0.6.0
  - richdocuments: 3.7.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
                [I removed this one for security purpose]
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "versions_retention_obligation": "auto, 2",
        "trashbin_retention_obligation": "auto, 2",
        "overwrite.cli.url": [I removed this one for security purpose],
        "dbtype": "mysql",
        "version": "18.0.6.0",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "app.mail.imaplog.enabled": true,
        "app.mail.smtplog.enabled": true,
        "app.mail.imap.timeout": 40,
        "app.mail.smtp.timeout": 20,
        "appstore.experimental.enabled": true,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "app_install_overwrite": [
            "calendar",
            "occweb"
        ],
        "mysql.utf8mb4": true,
        "has_rebuilt_cache": true
    }
}
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by JulienSambre** [comment]
I've made a few test tonight and I succeeded to lower response time by allowing more CPU to my nextcloud instance : i tested from 0.3 vcpu (original value) to 1 vcpu (max tested value). I saw no improvement beyond 0.7/0.8 vcpu. My response time went between 2.5-3s, from the initial 9s. Big improvement, but not optimal.

Therefore I can't explain why Deck API is so CPU intensive :o. 0.3 vcpu fit the need of all my other applications.

**Comment by juliushaertl** [comment]
Could you check the contents of the `oc_bruteforce_attempts` table? Maybe your ip is listed there due to some failed login attempts and since we authenticate with user/pass on each api call, this could explain a general slow down.

**Comment by juliushaertl** [comment]
That would also explain why the web api is so much faster, since there we use the session to authenticate. The deck logic for listing the boards is actually exactly the same on both endpoints.

**Comment by JulienSambre** [comment]
Hi!

I just looked in `oc_bruteforce_attempts ` and I did'nt found any recent entry. To be sure, I cleaned the all table. But no change in response time unfortunately.

**Comment by juliushaertl** [comment]
Hm to bad I don't see any other reason why the API call should be so much slower. As mentioned both endpoints use the same code in deck actually. 

Maybe you can check the browser tab for the slow request, there should be some timings data just to be sure that there is not something else delaying the request.

**Comment by JulienSambre** [comment]
This is the strange fact : GUI is very fast (with my web browser), but the API is very slow when call from code (python for example).

The main difference is that the authentication method is different, as you said. Do you know if there is a way to hack the auth for the API call to see if it improve the response time?

**Comment by stefan-niedermann** [comment]
> The main difference is that the authentication method is different, as you said. Do you know if there is a way to hack the auth for the API call to see if it improve the response time?

Shouldn't it be enough to track the request in your browser console and copy all the headers which are sent?

Maybe you can also try with a different stack, light "postman" to verify that it's the API which is slow and not the stack of your 3rd party client?

**Comment by JulienSambre** [comment]
Hi,

Sorry for the delay of the answer!

I tried with the headers and with a postman like (RESTer) from my browser and I have the same response time may it be from RESTer or my python code : almost 2-3 seconds for getting the list of cards (3 web call). Response time are very nice only when I use Deck as a standard web app, not when I call the API.

**Comment by jordanbancino** [comment]
I am writing a Java API for Deck and I am facing this same issue: my requests are taking an absurd amount of time to complete I have confirmed that it is not a network bandwidth or server load issue, as everything else is blazing fast. Just Deck is being slow. And only the API is slow, not the actual GUI. I thought maybe it was something I was doing in Java, but it appears to be any client I use:

```
$ time curl -u $username:$password https://nextcloud.mydomain.com/index.php/apps/deck/api/v1.0/boards
...
real	0m50.170s
user	0m0.041s
sys	0m0.013s
```

The server does eventually return the data, but it really shouldn't take almost a minute. My requests are consistently taking 50 seconds to be fulfilled, which is not very nice.

An interesting thing is that it only seems to be getting slower. When I first started my project, everything was perfectly fine, but things have slowly been taking longer and longer....

**Comment by juliushaertl** [comment]
> An interesting thing is that it only seems to be getting slower. When I first started my project, everything was perfectly fine, but things have slowly been taking longer and longer....

Please check your `oc_bruteforce_attempts` table to see if your ip or subnet might be in there. Wrong authentication might lead to requests being delayed, however I'm still wondering a bit why that should happen after you authenticated properly again. 

For everyone just to make sure this is not a setup issue, feel free to drop me a mail, then I can give you some temporary accounts on a test setup, so maybe you can check if that also has the issue. Then I could to some tracing of the requests maybe.

**Comment by jordanbancino** [comment]
@juliushaertl I'll check that table sometime this week, hopefully. And I'll also try using a new app password.

**Comment by jordanbancino** [comment]
@juliushaertl I checked `oc_bruteforce_attempts` and sure enough, my IP address is in there. That must be the issue because I tried working on another computer with a completely different IP, and everything seems just fine. So now the question is, how do I safely clear my IP from that table?

**Comment by juliushaertl** [comment]
Checkout `occ security:bruteforce:reset` for that

**Comment by jordanbancino** [comment]
I couldn't find that, so I just ran `DELETE FROM oc_bruteforce_attempts WHERE ip = <my-ip>` and the problem is fixed. Nothing appears to be broken.

**Comment by JulienSambre** [comment]
> 
> 
> I couldn't find that, so I just ran `DELETE FROM oc_bruteforce_attempts WHERE ip = <my-ip>` and the problem is fixed. Nothing appears to be broken.

Hi @jordanbancino , could you tell me how long are your web call? Mine always take almost 1s, no matter what I try.

**Comment by jordanbancino** [comment]
@JulienSambre I just ran some rudimentary benchmarks. I have a `Http.request()` function that I wrote specifically for my project, and I timed the execution of the entire function, so that includes setting up the connection, opening the connection, making my request, reading the response, and then closing the connection. For all of those tasks, here are my results:

```
Request: 781ms
Request: 64ms
Request: 69ms

Request: 358ms
Request: 66ms
Request: 66ms
```

My unit test makes 3 requests, and I ran it twice. I should probably note that, while I'm not working on `localhost`, my server is sitting almost right next to me and is connected to the same router that my laptop, from which I'm doing this, is on.

**Comment by JulienSambre** [comment]
Thanks!

What requests take ~60ms and what request take ~700ms?

I have probably the same infrastructure as you (server is just next to me for my tests).

**Comment by jordanbancino** [comment]
@JulienSambre The first request is fetching all the boards (`GET /boards`, I believe) and the second ones are updating information on the board.

**Comment by JulienSambre** [comment]
@jordanbancino Thanks ! It is the response time I have myself.

@juliushaertl Could you tell me the sizing (CPU & RAM) of your Nextcloud instance? @jordanbancino seems to have the same response time as I have, but you seems to have much much lower response time ("on my personal instance they are all done within ~300ms").

I don't give up the opportunity to migrate my AI to Deck, as I love to use this at work or at home :).

**Comment by juliushaertl** [comment]
Also some details on the size of response would be interesting, do you have lots of shared boards? Can you also reproduce this with an empty account with just one board for example?

**Comment by jordanbancino** [comment]
@juliushaertl I have 4 boards, one of which is my test board with one stack and two cards. The other 3 are just personal boards for organizing my life. They have no more than 6 stacks and no more than 5 cards in each one at a time. I should probably note, however, that I archive cards when I'm done with them, I don't delete them. So I probably have a few hundred cards sitting in the database, just because I've been using Deck for a little over a year and things build up. 

I haven't tried a clean account, really just because I have what I'd consider a fairly clean account already. My responses are fairly small. That being said, I'd be happy to try it if you'd like! If you want me to mess around with it, I can do that. I'm working on setting up a little command-line interface for my Deck API client, so once I get that in a working state, it'll make testing API requests super easy.

**Comment by juliushaertl** [comment]
Are you using a proper database or just sqlite?

**Comment by jordanbancino** [comment]
@juliushaertl I am using MariaDB.

**Comment by juliushaertl** [comment]
So I really cannot see any obvious reason for this. If you are up for some further debugging you could check the slow query log of mariadb or as a next step try to setup xdebug and obtain some profiling of those api calls. That could give a hint on what is wrong there.

**Comment by jordanbancino** [comment]
@juliushaertl I will try to check the logs later today. I'm initially opposed to installing a debugging extension on my production server though, so maybe I'll have to set up a test server somehow to try it. I'm a little tight on time these days, however, so I'm not sure when or even if I'll be able to get to that.
