### ISSUE TITLE
It's not possible to use custom color for a board

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#204]
We need a color picker like `calendar`, `contacts` for boars
![screenshot_20170622_205322](https://user-images.githubusercontent.com/16517095/27450723-e4003c08-578c-11e7-90b3-1345dd9f2b03.png)

**Comment by ossie** [comment]
I would like to give this a try. 👋

**Comment by juliushaertl** [comment]
@ossie That's great to hear. Feel free to ask if you have any questions during the implementation.

**Comment by GoetheG** [comment]
Hey @juliushaertl,

will this be implemented in the future?

**Comment by juliushaertl** [comment]
Fixed with #405.
