### ISSUE TITLE
inconsistent design of mouseover text

### ISSUE THREAD

**Issue by fm-sys** [nextcloud/deck#2048]
This button bar is using the browser mouseover design...
![2020-06-19 14_37_06-Deck - Nextcloud](https://user-images.githubusercontent.com/64581222/85136265-ab9b8000-b23f-11ea-8e16-57d6f5010e51.png)

And here it's the nextcloud stile...
![2020-06-19 14_37_51-Deck - Nextcloud](https://user-images.githubusercontent.com/64581222/85136268-ab9b8000-b23f-11ea-9cc7-8fd066e22353.png)

I can reproduse this on all my browsers (firefox and chromium edge)

**Comment by juliushaertl** [comment]
Yes, this should all be the Nextcloud tooltip.

@jakobroehrl Maybe something for you :)

**Comment by cloud2018** [comment]
Could the text also standardized?

- Add card
- Add new list
- Create an new board (item and tooltip)

**Comment by jakobroehrl** [comment]
@cloud2018 
You mean to change eg from "New board title" to "Create new board"?

**Comment by fm-sys** [comment]
I think it should be **list name / board title** or **new list name / new board title**

**Add a new card** is fine, because it is displayed even after the creation is finished and you may add second card...
