### ISSUE TITLE
Current date should be highlighted in the due date selector

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#205]
Current date should be highlighted in the due date selector, otherwise it is quite hard to  find.

**Comment by pixelipo** [comment]
Something like this? 

```
.ui-datepicker-today .ui-state-default.ui-state-highlight {
	background-image: none;
	background-color: #0082C9;
	color: white;
}
```

**Comment by pixelipo** [comment]
Or something less intrusive:

```
.ui-datepicker-today {
    background-color: #6E6E6E;
}
```

**Comment by juliushaertl** [comment]
> .ui-datepicker-today

That doesn't look very nice. :wink: 

I think we should go for the first one but use a light gray as background color. Just that there is some difference to the other days. Primary nextcloud color is already used for the selected date.

**Comment by pixelipo** [comment]
I can take care of this task, however, I think it should be done at nextcloud/server level, so I created issue nextcloud/server#5691

**Comment by MorrisJobke** [comment]
Fixed in https://github.com/nextcloud/server/pull/5713

**Comment by juliushaertl** [comment]
@pixelipo @jancborchardt  Great work :tada:
