### ISSUE TITLE
Checkboxes are not saved

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2061]
v1.0.3

Steps to reproduce

1) create a new card
2) add some checkboxes like:
```
- [ ] hello
- [ ] baz
- [ ] bar
```
3) close card, reload page
4) click on card details
5) check first box
6) close details
7) reload page
8) checkbox is unchecked 

Other way to reproduce:
5) check first box
6) open edit view
7) first box is not checked

Firefox 68.9.0esr

Log output when loading page:
```
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Notifications permissions denied App.vue:248
New search handler registered search.js:67:12
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 6 globals.js:66:15
TypeError: "t.extendedData is undefined"
    pr AttachmentList.vue:1
    bt VueJS
    pr AttachmentList.vue:1
    VueJS 7
main.js:62:9
OC.requestToken changed RgeThUMoM09kkjMNhMMAC5awOhUXkvFk0SCxlTlbCCI=:Em7ky3pQWw4RpQNDz6dOJKbycmRBwIZR/nbF3wsuUVM= index.js:281:9
OC.requestToken changed GPitLK+GAZino/lRv9KKZXr+xtGKkMV1uXQD9EW9kmo=:TJHaYpb+adnSlMkf9LbESkq8jqDcwrJAliJ3vnfIyxs= index.js:281:9
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Notifications permissions denied App.vue:248
New search handler registered search.js:67:12
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 3 globals.js:66:15
```
No additional errors when clicking the checkbox

**Comment by juliushaertl** [comment]
Hm strange, i can reproduce this on my production instance but not on my development setup with 1.0.3 :/

**Comment by reox** [comment]
Has you upgraded the production instance while the dev system is fresh? Maybe it is an issue which only appears if the instance was upgraded before...

**Comment by SebastianHeitz** [comment]
I was about to report exactly the same error. However, I can add as additional information that the checkboxes remain filled in when using the Deck Android app. Maybe this information will help to solve the problem.

Android 10
Deck app version: 1.4.4
Deck version: 1.0.3
NC version: 18.0.4

**Comment by q-wertz** [comment]
Ann additional note:
When changing the checkboxes in the "Edit description" mode it is saved correctly.
Only in the "View Description" mode the problem arises.

**Comment by jotadominguez** [comment]
I now this issue is closed but i am having exactly the same problem.
NextCloud 27.1.3 on Docker
Deck 1.11.1

**Comment by juliushaertl** [comment]
The release is still pending.
