### ISSUE TITLE
CSS rule for blockquotes

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2064]
**Is your feature request related to a problem? Please describe.**

The Markdown editor allows for quotes using `>`:

```
This is not a quote
> This is a quote
```

However, blockquotes are not rendered in markdown.

**Describe the solution you'd like**

Something like this:

![image](https://user-images.githubusercontent.com/431045/85529668-95aa0880-b60d-11ea-8430-959c27d6c1a5.png)

this uses:
```
#description-preview blockquote {
    padding-left: 1em;
    border-left: 0.5ex solid black;
    font-style: italic;
}
```

**Describe alternatives you've considered**

There are plenty of quoting styles. Any style is fine as long as it can clearly be distinguished from normal text.

> this is how a quote in github looks like

**Additional context**
v1.0.3

**Comment by stefan-niedermann** [comment]
I would rather see the resources put in solving https://github.com/nextcloud/deck/issues/1561 (which supports quoted texts) instead of messing around with the current editor :smile: 

If this issue pinches you hard, you may want to create a Pull Request and contribute a quickfix? :slightly_smiling_face: :rocket:

**Comment by reox** [comment]
> I would rather see the resources put in solving #1561 (which supports quoted texts) instead of messing around with the current editor smile

Did not knew that! Then, this one could be closed as duplicate I guess.

> If this issue pinches you hard, you may want to create a Pull Request and contribute a quickfix? slightly_smiling_face rocket

The only thing I can offer is to push those changes in an untested branch :D 
But I do not even know where I should put the CSS :sweat_smile: 
Does it belong somewhere here: https://github.com/nextcloud/deck/blob/ebce6b5bc24db8b11e91c2a3e9144ed6addc495c/src/components/card/CardSidebar.vue#L626 ?

**Comment by juliushaertl** [comment]
This would be the right place actually: https://github.com/nextcloud/deck/blob/master/src/css/markdown.scss

Pull requests are very welcome :)

**Comment by reox** [comment]
yeah I could do that ;) but as I said I can not really test it, as I do not have any test setup rolling ...
