### ISSUE TITLE
Label edit view needs some polishing

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#207]
![2017-06-22-221735_498x194_scrot](https://user-images.githubusercontent.com/3404133/27454014-b52471ea-5798-11e7-89bb-fd431e64b1b8.png)

**Comment by artemanufrij** [comment]
Label List:
![label-list](https://user-images.githubusercontent.com/16517095/27458315-b5e77ce8-57a8-11e7-9106-23ad56a36f4c.png)

Label Edit:
![label-edit](https://user-images.githubusercontent.com/16517095/27458317-b7e01a14-57a8-11e7-90fc-b7d341ceec69.png)
