### ISSUE TITLE
some icons are gone

### ISSUE THREAD

**Issue by mokkin** [nextcloud/deck#2070]
### Steps to reproduce
open deck in Firefox
some icons of cards and the description are missing
maybe the webserver log helps

### Expected behaviour
all icons appear

### Actual behaviour
only some icons appear

## Server configuration detail

**Operating system:** Linux 4.9.0-0.bpo.11-amd64 #1 SMP Debian 4.9.189-3+deb9u1~deb8u1 (2019-09-30) x86_64

**Webserver:** Apache (cgi-fcgi) (shared hosting)

**Database:** mysql 5.7.28

**PHP version:** 

7.4.7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, gmp, SPL, iconv, session, json, mbstring, pcntl, standard, Phar, posix, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, mysqlnd, cgi-fcgi, imagick, curl, gd, mysqli, PDO, pdo_mysql, xsl, sqlite3, intl, sodium, ldap, tidy, pdo_sqlite, Zend OPcache

**Nextcloud version:** 18.0.6 - 18.0.6.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade since OC 4

**Where did you install Nextcloud from:** 

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - deck: 1.0.3
 - documentserver_community: 0.1.7
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_markdown: 2.3.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.6
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notes: 3.5.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - occweb: 0.0.7
 - onlyoffice: 4.2.0
 - password_policy: 1.8.0
 - passwords: 2020.6.0
 - photos: 1.0.0
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - qownnotesapi: 20.1.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - support: 1.1.1
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - files_readmemd
 - mail
 - maps
 - phonetrack
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
     
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.example.de",
    "dbtype": "mysql",
    "version": "18.0.6.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app.mail.server-side-cache.enabled": true,
    "theme": "",
    "loglevel": 2,
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "mysql.utf8mb4": true,
    "htaccess.RewriteBase": "\/"
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0

**Operating system:** Debian 9 shared host

## Logs

<details><summary>Web server error log</summary>

```
2020-06-25 09:24:00	Error	500	GET /ocs/v2.php/apps/spreed/api/v1/chat/ypjkictq?lookIntoFuture=1&lastKnownMessageId=3024&includeLastKnown=0 HTTP/1.0			1.53 K	SSL/TLS-Zugriff für Apache
2020-06-25 09:24:20	Error	500	GET /ocs/v2.php/apps/spreed/api/v1/signaling/ypjkictq HTTP/1.0			1.53 K	SSL/TLS-Zugriff für Apache
2020-06-25 09:24:30	Warning		(104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server				Apache-Fehler
2020-06-25 09:24:30	Error		End of script output before headers: v2.php				Apache-Fehler
2020-06-25 09:24:30	Warning		(104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server				Apache-Fehler
2020-06-25 09:24:30	Error		End of script output before headers: v2.php				Apache-Fehler
2020-06-25 09:33:56	Error	404	GET /ocs/v2.php/apps/spreed/api/v1/signaling/ypjkictq HTTP/1.0			999	SSL/TLS-Zugriff für Apache
2020-06-25 09:34:13	Error	404	GET /ocs/v2.php/apps/spreed/api/v1/signaling/ox9xcjeh HTTP/1.0			999	SSL/TLS-Zugriff für Apache
2020-06-25 09:34:26	Error	404	GET /avatar/test1/32 HTTP/1.0			888	SSL/TLS-Zugriff für Apache
2020-06-25 09:34:26	Error	404	GET /avatar/test/32 HTTP/1.0			888	SSL/TLS-Zugriff für Apache
2020-06-25 09:34:26	Error	404	GET /avatar/test2/32 HTTP/1.0			888	SSL/TLS-Zugriff für Apache
2020-06-25 09:35:09	Error	404	GET /core/preview?fileId=690793&c=bd02ee92a35c21669851afadd6192d6d&x=250&y=250&forceIcon=0 HTTP/1.0			888	SSL/TLS-Zugriff für Apache
2020-06-25 09:35:09	Error	404	GET /core/preview?fileId=690793&x=32&y=32 HTTP/1.0			888	SSL/TLS-Zugriff für Apache
2020-06-25 09:36:50	Error	401	GET /apps/deck/ HTTP/1.0			1.44 K	SSL/TLS-Zugriff für Apache
2020-06-25 09:36:56	Error	400	GET /remote.php/dav/calendars/john/contact_birthdays/ HTTP/1.1			248	SSL/TLS-Zugriff für nginx
2020-06-25 09:36:56	Error	400	GET /remote.php/dav/calendars/john/personal/ HTTP/1.1			248	SSL/TLS-Zugriff für nginx
2020-06-25 09:37:27	Error	401	OPTIONS /remote.php/dav/principals/users/markus/ HTTP/1.0			1.82 K	SSL/TLS-Zugriff für Apache
2020-06-25 09:37:31	Warning		mod_fcgid: stderr: PHP Deprecated: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /var/www/vhosts/hosting123456.example.netcup.net/httpdocs/cloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php on line 357				Apache-Fehler
2020-06-25 09:37:31	Warning		mod_fcgid: stderr: PHP Deprecated: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /var/www/vhosts/hosting123456.example.netcup.net/httpdocs/cloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php on line 423				Apache-Fehler

```
</details>

<details><summary>Nextcloud log</summary>

```
no entries at the query time
```
</details>

<details><summary>Browser log</summary>

GEThttps://cloud.example.de/apps/deck/#/board/16/card/69
[HTTP/2 200 OK 951ms]

GEThttps://cloud.example.de/core/js/dist/main.js?v=c1a2f515-10
GEThttps://cloud.example.de/js/core/merged-template-prepend.js?v=c1a2f515-10
GEThttps://cloud.example.de/core/search/js/search.js?v=c1a2f515-10
GEThttps://cloud.example.de/core/l10n/de.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/files_pdfviewer/js/previewplugin.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/files_sharing/l10n/de.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/files_sharing/js/dist/main.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/files_videoplayer/js/main.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/notifications/l10n/de.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/notifications/js/notifications.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/files_rightclick/l10n/de.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/files_rightclick/js/script.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/firstrunwizard/l10n/de.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/firstrunwizard/js/about.js?v=c1a2f515-10
GEThttps://cloud.example.de/core/search/js/searchprovider.js?v=c1a2f515-10
GEThttps://cloud.example.de/core/js/files/fileinfo.js?v=c1a2f515-10
GEThttps://cloud.example.de/core/js/files/client.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/deck/l10n/de.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/deck/js/deck.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/deck/js/collections.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/files_sharing/js/dist/collaboration.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/spreed/l10n/de.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/spreed/js/collections.js?v=c1a2f515-10
GEThttps://cloud.example.de/apps/accessibility/js/accessibility?v=0
GEThttps://cloud.example.de/apps/theming/js/theming?v=10
GEThttps://cloud.example.de/css/core/bcd6-d5c9-css-variables.css?v=d116eac7e333228880a979400ed50c09-c1a2f515-10
[HTTP/2 200 OK 384ms]

GEThttps://cloud.example.de/css/core/bcd6-d5c9-server.css?v=d116eac7e333228880a979400ed50c09-c1a2f515-10
[HTTP/2 200 OK 376ms]

GEThttps://cloud.example.de/apps/notifications/js/notifications.js?v=c1a2f515-10
[HTTP/2 200 OK 288ms]

GEThttps://cloud.example.de/apps/notifications/l10n/de.js?v=c1a2f515-10
[HTTP/2 200 OK 291ms]

GEThttps://cloud.example.de/apps/files_videoplayer/js/main.js?v=c1a2f515-10
[HTTP/2 200 OK 291ms]

GEThttps://cloud.example.de/apps/files_sharing/js/dist/main.js?v=c1a2f515-10
[HTTP/2 200 OK 286ms]

GEThttps://cloud.example.de/apps/files_sharing/l10n/de.js?v=c1a2f515-10
[HTTP/2 200 OK 285ms]

GEThttps://cloud.example.de/apps/files_pdfviewer/js/previewplugin.js?v=c1a2f515-10
[HTTP/2 200 OK 286ms]

GEThttps://cloud.example.de/core/l10n/de.js?v=c1a2f515-10
[HTTP/2 200 OK 285ms]

GEThttps://cloud.example.de/core/search/js/search.js?v=c1a2f515-10
[HTTP/2 200 OK 92ms]

GEThttps://cloud.example.de/js/core/merged-template-prepend.js?v=c1a2f515-10
[HTTP/2 200 OK 733ms]

GEThttps://cloud.example.de/core/js/dist/main.js?v=c1a2f515-10
[HTTP/2 200 OK 148ms]

GEThttps://cloud.example.de/apps/theming/styles?v=10
[HTTP/2 200 OK 590ms]

GEThttps://cloud.example.de/css/deck/1237-d5c9-globalstyles.css?v=d116eac7e333228880a979400ed50c09-12376378-10
[HTTP/2 200 OK 640ms]

GEThttps://cloud.example.de/css/core/bcd6-d5c9-results.css?v=d116eac7e333228880a979400ed50c09-c1a2f515-10
[HTTP/2 200 OK 900ms]

GEThttps://cloud.example.de/css/notifications/783c-d5c9-styles.css?v=d116eac7e333228880a979400ed50c09-783c3f18-10
[HTTP/2 200 OK 459ms]

GEThttps://cloud.example.de/apps/files_pdfviewer/css/style.css?v=6a154fe0-10
[HTTP/2 200 OK 90ms]

GEThttps://cloud.example.de/apps/deck/css/activity.css?v=12376378-10
[HTTP/2 200 OK 91ms]

GEThttps://cloud.example.de/apps/spreed/js/collections.js?v=c1a2f515-10
[HTTP/2 200 OK 351ms]

GEThttps://cloud.example.de/apps/spreed/l10n/de.js?v=c1a2f515-10
[HTTP/2 200 OK 351ms]

GEThttps://cloud.example.de/apps/files_sharing/js/dist/collaboration.js?v=c1a2f515-10
[HTTP/2 200 OK 351ms]

GEThttps://cloud.example.de/apps/deck/js/collections.js?v=c1a2f515-10
[HTTP/2 200 OK 351ms]

GEThttps://cloud.example.de/apps/deck/js/deck.js?v=c1a2f515-10
[HTTP/2 200 OK 294ms]

GEThttps://cloud.example.de/apps/deck/l10n/de.js?v=c1a2f515-10
[HTTP/2 200 OK 293ms]

GEThttps://cloud.example.de/core/js/files/client.js?v=c1a2f515-10
[HTTP/2 200 OK 293ms]

GEThttps://cloud.example.de/core/js/files/fileinfo.js?v=c1a2f515-10
[HTTP/2 200 OK 292ms]

GEThttps://cloud.example.de/core/search/js/searchprovider.js?v=c1a2f515-10
[HTTP/2 200 OK 351ms]

GEThttps://cloud.example.de/apps/firstrunwizard/js/about.js?v=c1a2f515-10
[HTTP/2 200 OK 293ms]

GEThttps://cloud.example.de/apps/firstrunwizard/l10n/de.js?v=c1a2f515-10
[HTTP/2 200 OK 351ms]

GEThttps://cloud.example.de/apps/files_rightclick/js/script.js?v=c1a2f515-10
[HTTP/2 200 OK 294ms]

GEThttps://cloud.example.de/apps/files_rightclick/l10n/de.js?v=c1a2f515-10
[HTTP/2 200 OK 292ms]

GEThttps://cloud.example.de/apps/contacts/img/app.svg?v=c1a2f515
[HTTP/2 200 OK 46ms]

GEThttps://cloud.example.de/apps/spreed/img/app.svg?v=c1a2f515
[HTTP/2 200 OK 47ms]

GEThttps://cloud.example.de/apps/activity/img/activity.svg?v=c1a2f515
[HTTP/2 200 OK 47ms]

GEThttps://cloud.example.de/apps/photos/img/app.svg?v=c1a2f515
[HTTP/2 200 OK 47ms]

GEThttps://cloud.example.de/apps/files/img/app.svg?v=c1a2f515
[HTTP/2 200 OK 47ms]

GEThttps://cloud.example.de/apps/theming/js/theming?v=10
[HTTP/2 200 OK 305ms]

GEThttps://cloud.example.de/apps/accessibility/js/accessibility?v=0
[HTTP/2 200 OK 190ms]

GEThttps://cloud.example.de/avatar/bob/32?v=1
[HTTP/2 200 OK 397ms]

GEThttps://cloud.example.de/core/img/actions/logout.svg?v=c1a2f515
[HTTP/2 200 OK 82ms]

GEThttps://cloud.example.de/apps/settings/img/help.svg?v=c1a2f515
[HTTP/2 200 OK 82ms]

GEThttps://cloud.example.de/apps/firstrunwizard/img/info.svg?v=c1a2f515
[HTTP/2 200 OK 82ms]

GEThttps://cloud.example.de/apps/settings/img/admin.svg?v=c1a2f515
[HTTP/2 200 OK 82ms]

GEThttps://cloud.example.de/apps/passwords/img/app.svg?v=c1a2f515
[HTTP/2 200 OK 82ms]

GEThttps://cloud.example.de/apps/tasks/img/tasks.svg?v=c1a2f515
[HTTP/2 200 OK 82ms]

GEThttps://cloud.example.de/apps/notes/img/notes.svg?v=c1a2f515
[HTTP/2 200 OK 47ms]

GEThttps://cloud.example.de/apps/deck/img/deck.svg?v=c1a2f515
[HTTP/2 200 OK 47ms]

GEThttps://cloud.example.de/apps/calendar/img/calendar.svg?v=c1a2f515
[HTTP/2 200 OK 46ms]

GEThttps://cloud.example.de/apps/theming/image/logo?v=10
[HTTP/2 200 OK 483ms]

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. addStylesClient.js:220:17
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Notifications permissions granted App.vue:242
GEThttps://cloud.example.de/apps/notifications/img/notifications.svg
[HTTP/2 200 OK 42ms]

New search handler registered search.js:67:12
Mutations-Ereignisse sollten nicht mehr verwendet werden. Verwenden Sie MutationObserver stattdessen. ContentPage.js:31:9
GEThttps://cloud.example.de/apps/theming/favicon/deck?v=10
[HTTP/2 200 OK 259ms]

GEThttps://cloud.example.de/apps/theming/icon/deck?v=10
[HTTP/2 200 OK 173ms]

GEThttps://cloud.example.de/avatar/bob/24?v=1
[HTTP/2 200 OK 256ms]

GEThttps://cloud.example.de/avatar/john.doe/24
[HTTP/2 200 OK 599ms]

GEThttps://cloud.example.de/avatar/alice.doe/24
[HTTP/2 201 Created 517ms]

GEThttps://cloud.example.de/avatar/charles.doe/24
[HTTP/2 200 OK 340ms]

The escapeHTML library is deprecated! It will be removed in nextcloud 19. 4 globals.js:66:15
GEThttps://cloud.example.de/avatar/charles.doe/32
[HTTP/2 200 OK 283ms]

GEThttps://cloud.example.de/avatar/john.doe/32
[HTTP/2 200 OK 445ms]

GEThttps://cloud.example.de/avatar/alice.doe/32
[HTTP/2 201 Created 181ms]

GEThttps://cloud.example.de/core/img/places/home.svg
[HTTP/2 200 OK 42ms]

</details>

![DeepinBildschirmfoto_Bereich auswählen_20200625093618](https://user-images.githubusercontent.com/2938748/85679665-e848fa80-b6c9-11ea-8a9a-bb3ae0828b5c.png)
![DeepinBildschirmfoto_Bereich auswählen_20200625094118](https://user-images.githubusercontent.com/2938748/85679676-ea12be00-b6c9-11ea-931f-d975f2843753.png)

**Comment by juliushaertl** [comment]
Maybe a Browser caching issue, did you try a hard refresh?

**Comment by mokkin** [comment]
Yes, of course.
Even with a "fresh" browser, another browser, another OS....

**Comment by mokkin** [comment]
Meanwhile I found out that icons are missing in other apps too such as the share menu in files or the project icon.

**Comment by mokkin** [comment]
After some try & error I found out that the issue seems to be connected  with "pretty URLs". I deactivated pretty URLs for the whole instance and all icons in all apps came back. This a workaround but no solution.
Should we move this to https://github.com/nextcloud/server/ ?
