### ISSUE TITLE
l10n: Label "Settings" is not shown localised

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/deck#2078]
Just installed v1.0.4.
Using german UI and label "Settings" is shown. Should be "Einstellungen".

See screenshot.
<img width="300" alt="Bildschirmfoto 2020-06-26 um 22 10 42" src="https://user-images.githubusercontent.com/2069590/85897173-14fc2f80-b7fa-11ea-9cb6-30c63a987b43.png">

Has been the same with v1.0.3 already

**Client details:**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] ff 77
 - Device: [e.g. iPhone6, desktop] Desktop

**Comment by stefan-niedermann** [comment]
Also using v1.0.4 here, seems all good:

![grafik](https://user-images.githubusercontent.com/4741199/86329697-d07ff200-bc46-11ea-8f22-8ecd1075c919.png)

Have you tried a force refresh (<kbd>Ctrl</kbd> + <kbd>F5</kbd>)?

**Comment by stefan-niedermann** [comment]
My language settings:

![grafik](https://user-images.githubusercontent.com/4741199/86329780-f86f5580-bc46-11ea-8927-eb300006ce16.png)

**Comment by rakekniven** [comment]
> Have you tried a force refresh (Ctrl + F5)?

Yes, I did. Still english.

> My language settings:

Nice catch. With do "Du" it works.

With "formell (Sie)" it doesn't work and that is my selection :-)

**Comment by rakekniven** [comment]
Any idead about the cause of it?

**Comment by stefan-niedermann** [comment]
Simplest explanation was that it hasn't been translated yet for german "formell (Sie)"?

**Comment by rakekniven** [comment]
Yes, but this isn't the case :-/

**Comment by rakekniven** [comment]
That string is not part of the deck app, right?
It is used from server part, or?

**Comment by juliushaertl** [comment]
It is actually coming from https://github.com/nextcloud/nextcloud-vue/blob/ff5d0e9ca4f9003b298f22d24cac34099ae6ffe0/src/components/AppNavigationSettings/AppNavigationSettings.vue#L53

Might be an issue with the weird de_DE workaround we use for formal/informal here, I'll have a look at some point.

**Comment by rakekniven** [comment]
I do not see the weird workaround :-/

Other apps use "Settings" and there it works. Should I start looking into it or will it be a quicky for you?

**Comment by juliushaertl** [comment]
Will be fixed with https://github.com/nextcloud/nextcloud-l10n/pull/172

**Comment by juliushaertl** [comment]
Closing as this will be fixed once `@nextcloud/l10n` is updated with a new version of `@nextcloud/vue`
