### ISSUE TITLE
Controls disappearing randomly

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/deck#2079]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
the board controls on top right of the screen disappear after some time when interacting with the app.

**To Reproduce**
Unknown, try switching between boards? 

**Expected behavior**
not disappearing

**Screenshots**
Controls: (Also minor UI bug that should be fixed: notice the opacity/color is different for the "show archived cards" button.)

![Screenshot_2](https://user-images.githubusercontent.com/36133540/85918010-5246d880-b85f-11ea-9b20-955544e4909a.png)

Disappeared state:

![Screenshot_1](https://user-images.githubusercontent.com/36133540/85918012-570b8c80-b85f-11ea-937a-ad10440dfd44.png)

**Client details:**
 - Browser brave
 - Version 1.0.4 deck, NC 19

**Comment by pilsnerbeer** [comment]
Seemingly related to #2070 but I dont use pretty URLs. Our browser are desktop OS are also different.

**Comment by juliushaertl** [comment]
Did you try a hard refresh in your browser? Might be a caching issue.
