### ISSUE TITLE
Formatting of deck card issue - subject and date shown next to each other

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/deck#2081]
### How to use GitHub

**Describe the solution you'd like**
I am unsure of what solution I would like to see, but in the current (updated) design, the subject of the card and the date are shown next to each other. This leaves very little space for the text making the formatting look sloppy. Also, a lot of unused white space is created on the card this way.

![image](https://user-images.githubusercontent.com/9272078/85931368-43464180-b8c4-11ea-9740-86b749e32f35.png)

Maybe if the date expiration is shown under the text, this would be shown in a better formatted way/

**Comment by stefan-niedermann** [comment]
We consider an expiration date as at least as important as the title. Therefore it is at the correct place (*IMHO*).

For proper displaing of the title have a look at https://github.com/nextcloud/deck/issues/1672

I would close this as dulicate therefore.

**Comment by armaccloud** [comment]
Hi @stefan-niedermann 

I understand, however does this importance automatically mean they have to be displayed next to each other?
If one or another would be displayed lower or higher, indicate its importance? I do not know, but they are questions that come up for me for it doesn't seem that clear cut to me.

The issue I am seeing here, however,  is that the result is the title isn't shown in a user friendly/elegant way in the current setup.

**Comment by stefan-niedermann** [comment]
> If one or another would be displayed lower or higher, indicate its importance?

Sure, we are used to read from left to right, from top to bottom (vice versa for right-to-left languages of course). The position is related to the importance.

I think the situation will getting better once #1672 is solved.

Though i have another idea: The appearance of the due date already is different depending on how far away the date in the future is. Maybe one could argue, that if it is away more than 4 weeks (or so, to be defined), it could be displayed collapsed to the calendar icon and not showing the exact date at all?

**Comment by armaccloud** [comment]
That might be a good option regarding showing a collapsed date to the calendar icon.

I also noticed that there is a lot of whitespace under the date. This is all unused in the current setup.

![image](https://user-images.githubusercontent.com/9272078/86345044-50b05280-bc5b-11ea-84fb-ced154b3fc94.png)

**Comment by juliushaertl** [comment]
We should probably set a max-width for the duedate label, anyways the general flow text around it issue will already help a lot and is tracked in https://github.com/nextcloud/deck/issues/1672
