### ISSUE TITLE
Projects need reload to be shown when browsing cards into a given board

### ISSUE THREAD

**Issue by Firerazer** [nextcloud/deck#2084]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
The project affiliation of a card is not show when you are coming from another card from the same board (i.e. without reload).

**To Reproduce**
1. Go to any card with a project linked into any board
2.1 If you don't see project while you should have one, reload the page and see the project now linked.
2.2 If you see the project, click on another card that should have a project and see the project not there. Reload the page to see the project

**Expected behavior**
When clicking through cards, linked projects should always be presented and should not need a page reload to be displayed

**Client details:**
 - OS: Win10
 - Browser Chrome
 - Version last version
 - Device: desktop

Note: I am not a programmer nor a developer, so I cannot provide any detailed information about the server. If this is really needed because anyone else can reproduce, then I will ask my overwhelmed dev to provide me the requested details
-- Nextcloud version: 19.0.0
-- All apps up to date

**Comment by Firerazer** [comment]
Little precision I just found:
This bug happens only when you navigate between cards that do not have the same project. If you click through cards that have the same project, the project is still displayed and can be interacted with.

**Comment by rms-joe** [comment]
I just came around to report the same issue, but with "link to a file"

Steps to reproduce the behavior:

1. Go to any card within a project with detail window open
2. add to project -> link to a file -> add one
3. go to another card
4. refresh website
5. go back to card with linked filed
-> file link not shown

6. refresh website:
-> file link shows up

**Comment by sunjam** [comment]
Projects functionality deprecated in nc25.

- https://github.com/nextcloud/server/issues/28320

**Comment by juliushaertl** [comment]
As the projects feature is superseded by related resources since Nextcloud 25 there are no plans to further work on this. As long as the feature is still there anyone is of course welcome to provide fixes through pull requests but I consider this part no longer maintained.

https://github.com/nextcloud/server/blob/stable27/config/config.sample.php#L2347-L2352 
https://github.com/nextcloud/server/issues/28320
