### ISSUE TITLE
Sharing a board need to be done twice

### ISSUE THREAD

**Issue by Firerazer** [nextcloud/deck#2086]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When you want to share a board with multiple individuals or groups, after the first one, every other one need to be done twice to be saved by the system.

**To Reproduce**
Pre-requesite: have more than 3 groups and/or users.
1. Create a test board
2. Go into the board sharing options
3. Add your first group/person - should be no problem, normal behavior
4. Add your second group/person straight away, without doing anything else in between the first addition and this one. The first enter to validate the sharing will not work, you need to do it again to have the sharing saved by the system
5. Add your 3rd group/person - save behavior as previously explained should occur. etc etc.
Note: reloading the page between addition/changing board between additions does make the additions for sharing working properly.

**Expected behavior**
You should be able to enter as many groups/persons as you want to share the board without the need of a page reload.

**Screenshots**
NA

Client details:

OS: Win10
Browser Chrome
Version last version
Device: desktop
Note: I am not a programmer nor a developer, so I cannot provide any detailed information about the server. If this is really needed because anyone else can reproduce, then I will ask my overwhelmed dev to provide me the requested details
-- Nextcloud version: 19.0.0
-- All apps up to date

**Comment by jakobroehrl** [comment]
Can confirm the problem
