### ISSUE TITLE
enable a 'list' view for a better overview

### ISSUE THREAD

**Issue by splashote** [nextcloud/deck#2087]
Hey,

it would be great to have the option to reduce the shown information when looking on a deck in order to get a better overview.
I'm thinking of having lists with less icons/inforation on each card.

**Comment by jakobroehrl** [comment]
Hi, did you check out the compact mode?
![grafik](https://user-images.githubusercontent.com/24530680/86568005-81023480-bf6c-11ea-9ef0-6851256e5770.png)

**Comment by splashote** [comment]
Great, I oversaw that button.

I hope to see it integrated in the Android app, too.

https://github.com/stefan-niedermann/nextcloud-deck/issues/579
