### ISSUE TITLE
Tags cannot be created directly in the card details

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#2088]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Tags cannot be created directly in the card details.

**To Reproduce**
1. Go to Card Details
2. Click on Tags input field
3. Enter a new tag name which does not yet exist, like "asdölfkjaösdlfkjasdölfkj"
4. Click on the row with the :heavy_plus_sign: sign to instantly create it
5. Tag is not created

**Expected behavior**
Tag should be created and directly assigned to this card

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4741199/86329013-e04b0680-bc45-11ea-9439-1857f5b55d87.png)

**Client details:**
 - OS: [e.g. iOS] Debian
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] latest ESR
 - Device: [e.g. iPhone6, desktop] desktop

Deck Version: 1.0.4
Nextcloud Version: 18

**Additional infos:**

- Browser console does not show any error
- **No network request** has be fired when clicking on the :heavy_plus_sign:

**Comment by xdaftcraft** [comment]
Hello,

i tested on my Deck application Android, it's work.

**Comment by gargeburt** [comment]
I have the same problem.

Deck Version: 1.0.4
Nextcloud Version: 19

**Comment by stefan-niedermann** [comment]
@gargeburt

**Comment by juliushaertl** [comment]
We actually have #1472 for that already :wink:
