### ISSUE TITLE
Move to SCSS and cleanup css code

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#21]
The css code has grown over the time and needs some cleanup.

Since SCSS is coming with Nc12 this might be helpful.

**Comment by bjornnorman** [comment]
I've been looking a little on the code while making some local changes and realized the build process just concatenates the js files and that source code lookups/inspections (using PHPStorm) fail without proper import statements etc. I have experience with Angular2 / Typescript, using webpack for building and SCSS processing - and karma/jasmine for unit-testing so I could probably update and rearrange the js code to support this if you like? The code would be easier to read and debug, and IDEs would likely be happier too ;)

**Comment by juliushaertl** [comment]
@bjornnorman I already thought about migrating to angular2 but I don't have any experience with it until now. Is it possible to keep exiting dependencies such as ng-sortable/angular-ui-select/... ? How big would the initial change be? Can we keep the seperate anguar components and migrate them step by step?

Anyhow I would really appreciate your help there. :rocket:

**Comment by bjornnorman** [comment]
Cool, I'll check the dependencies tomorrow. It'll require turning the modules etc into classes, adding corresponding import statements and using member vars in stead of $scope etc, but it's mostly search/replace. It's not really that much js code - so I can convince my employer to let me do that ;)

**Comment by juliushaertl** [comment]
@bjornnorman Awesome. I'm really looking forward to that. :+1: :tada:

**Comment by pixelipo** [comment]
Fixed in #219
