### ISSUE TITLE
Add a button for remove a board and cards associated

### ISSUE THREAD

**Issue by lp177** [nextcloud/deck#2104]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
We have no mechanism for remove a board in the web interface and that seem an essential thing for clear easly an unused board

**Describe the solution you'd like**
Add en entry to do that in the edit menu of the board

**Describe alternatives you've considered**
And dedicated page who we see all the board and a button on eatch for remove

**Additional context**

**Comment by stefan-niedermann** [comment]
What's wrong with the menu item you can see in the bottom right?

![grafik](https://user-images.githubusercontent.com/4741199/86519907-c5dc7d00-be3f-11ea-856a-ccfe53261511.png)

**Comment by lp177** [comment]
I don't have the two lasts, maybe a problem of version, thanks for the screenshoot

**Comment by lp177** [comment]
I don't have the two lasts, maybe a problem of version, thanks for the screenshoot
it seem hidden when the menu has not enougth heigth
![image](https://user-images.githubusercontent.com/5777316/86520092-510a4280-be41-11ea-9d7b-98dbd3bfb1ee.png)

**Comment by stefan-niedermann** [comment]
Can you please scroll down to check whether this issue is a dulpicate of https://github.com/nextcloud/deck/issues/2050 ?

**Comment by lp177** [comment]
Really thancks, sorry it's effectively a duplicate, I've fix finaly that in manualy adding a min-heigth of .app-navigation ul[data-v-b57f9b42]
but b57f9b42 is most probably changing at each css parsing

**Comment by stefan-niedermann** [comment]
Thank you very much for the hint! I'll add this as a comment in the linked issue and close this as a duplicate :slightly_smiling_face: 

Feel free to subscribe to the linked issue to get notified when the maintainer @juliushaertl  or another contributor had time to fix this nasty little bug.

**Comment by stefan-niedermann** [comment]
Maybe you want to contribute a Pull Request @lp177 ? :rocket:

**Comment by lp177** [comment]
I'm don't familiar with this pipeline and I don't understand the DCO error
https://github.com/nextcloud/nextcloud-vue/pull/1183/checks?check_run_id=837429484

**Comment by stefan-niedermann** [comment]
Sure :slightly_smiling_face: 

`DCO` error just means that you have to sign off your commits.

Just execute the following commands on your termina, like the linked page suggests:

```
git commit --amend --signoff
git push --force-with-lease origin patch-1
```

**Comment by lp177** [comment]
The hope to no have to clone ^^ (I have edited by the gitlab editor)

**Comment by stefan-niedermann** [comment]
Haha :smile: i just mentioned the your commit to the `vue-components` maintainers, maybe they have an easy workaround or can guide you to your first successful commit :slightly_smiling_face: :rocket: 

Thanks for your contribution by the way!

**Comment by lp177** [comment]
I think this time is ok ^^ sorry for the fail

**Comment by stefan-niedermann** [comment]
Hey, no problem :) We'll have a look as soon as possible - new contributor are always welcome 🙂 just wait for @skjnldsv or one of the `vue-components`-team to guide you (i am only the maintainer of the Deck Android app and can't help you much here unfortunately) - just wait  bit.

cc @nextcloud/javascript

**Comment by lp177** [comment]
Ok, thanks for your help ^^
