### ISSUE TITLE
Activity logs [$10]

### ISSUE THREAD

**Issue by scoopex** [nextcloud/deck#211]
Especially for team collaboration it might be a good thing to have a activity tracking and comments.
(which might be technically depended)

PS: Many thanks for creating this nice nextcloud enhancement! (Special greets to Julius ;-))

**Comment by juliushaertl** [comment]
Hi @scoopex, nice to see you here. :wink: 

Yes, activity logs would be nice to have. We should make use of the activity app for Nextcloud there.
For comments please check out #10 which is already on the list for our next release.
