### ISSUE TITLE
[UX Design Request] Colored Lists

### ISSUE THREAD

**Issue by foxhoundv** [nextcloud/deck#2110]
I think it would be helpful to have the Lists able to be colored and adjust borders when a card is added or removed to it. Like the example below.
![desk colored list](https://user-images.githubusercontent.com/16512250/87059383-7b079000-c1c6-11ea-96e7-7c896739e35a.png)

**Comment by juliushaertl** [comment]
Duplicate of https://github.com/nextcloud/deck/issues/833
