### ISSUE TITLE
Checklists [$15]

### ISSUE THREAD

**Issue by scoopex** [nextcloud/deck#212]
I really love the checklist feature of Trello. With the activity logs (#211) this might be a really good thing to work on complexer tasks or rather to have a confirmation that all important aspects of a tasks are completed.

**Comment by juliushaertl** [comment]
Any reason there should be a dedicated task list instead of the proposed checkbox feature for markdown in https://github.com/nextcloud/deck/issues/53 ? Otherwise i think having a GitHub like markdown support should be enough for that.

**Comment by GoetheG** [comment]
Yes. I agree. This function is needed as well.

**Comment by juliushaertl** [comment]
@GoetheG Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting that also need a specific feature. That way we can see your support without notifying all users subscribed to a given issue.

**Comment by juliushaertl** [comment]
The checkbox support for markdown has been merged with #463
