### ISSUE TITLE
Remove check for comments app

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#2126]
Since the comments app only handles files comments and the Api is always enabled, we should not take this as a check to disable comments in deck. They should just always work.

**Comment by jakobroehrl** [comment]
@juliushaertl 
So, do I have to just remove it there:
https://github.com/nextcloud/deck/blob/master/src/components/card/CardSidebar.vue#L190
https://github.com/nextcloud/deck/blob/master/src/components/card/CardSidebar.vue#L285
https://github.com/nextcloud/deck/blob/master/src/components/card/CardSidebar.vue#L237

**Comment by juliushaertl** [comment]
Well no, that is about activities ;)

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/deck/blob/master/src/components/card/CardSidebar.vue#L286

**Comment by jakobroehrl** [comment]
> 
> https://github.com/nextcloud/deck/blob/master/src/components/card/CardSidebar.vue#L286

🤦‍♂️ Thanks!

**Comment by joshtrichards** [comment]
Fixed in #2361
