### ISSUE TITLE
Duplication of text when using ** in checkbox

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2138]
**Describe the bug**

When using something like `*I*` in a checkbox, the text before the first asterix is repeated in the markdown rendering.
Not sure if this bug comes from deck directly or from the markdown rendering lib though.

**To Reproduce**
1. Create a new card
2. Enter the following text:
```
- [ ] This will be rendered correctly (I am groot)
- [ ] This will mess up (*I* am groot)
```
3. Click on view mode

**Expected behavior**
`*I*` should not trigger duplication of text and should render I in italic (as described in the markdown help)

**Screenshots**

![image](https://user-images.githubusercontent.com/431045/87912379-9481c500-ca6d-11ea-97c1-94b70a5bdfe3.png)

**Client details:**
 - OS: Linux
 - Browser Firefox / Chrome
 - Version: 68esr / 83
 - Device: desktop

Deck 1.0.5 / NC 18.0.7

JS Console:
```
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Notifications permissions denied App.vue:248
New search handler registered search.js:67:12
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 3 globals.js:66:15
```

**Comment by joreiff** [comment]
This does not only happen with `*italic*`, but all kinds of markup, e.g., `_italic_`, `**bold**`, `[Links](github.com)`. The latter, for example, renders as `Item Link Item [Link](github.com)`

**Comment by codeHorse87** [comment]
This does also happens with links, also when you bracket them in **<http...>** as described in [issue 127](https://github.com/nextcloud/deck/issues/127). Also when the link is at the end of a task definition starting with `- [ ]`  this will render all following text as an active element to the task. a problem seems to be that the parser does not terminate on `>` with the active element

**Comment by Zocker1999NET** [comment]
this seems to be a duplicate of #2109

**Comment by reox** [comment]
> 
> 
> this seems to be a duplicate of #2109

yes it is. closing in favor of #2109
