### ISSUE TITLE
Session_start(): A session had already been started - ignoring at ...

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/deck#2142]
**Describe the bug**
My error log keeps showing the following subsequent errors;

[PHP] Error: session_start(): A session had already been started - ignoring at /home/ewiqzonl/public_html/lib/private/Session/Internal.php#209

GET /index.php/apps/deck/api/v1.0/boards/26/stacks/94/cards/232?
from x.x.x.x at 2020-07-21T09:17:56+00:00

**To Reproduce**
1. Go to Settings
2. Click on Logging
3. See errors in the log

**Expected behavior**
These errors should not be occurring

**Screenshots**
![image](https://user-images.githubusercontent.com/9272078/88038571-b1d69200-cb46-11ea-80f3-4015013de875.png)

**Client details:**
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Operating system**:
Hosted

**Web server:**
Hosted

**Database:**
Hosted

**PHP version:**
Hosted

**Nextcloud version:** (see Nextcloud admin page)
19.0.1

**Where did you install Nextcloud from:**
Softaculous installer on hostiso.host

**Comment by juliushaertl** [comment]
Not a deck issue, see https://github.com/nextcloud/server/issues/20490
