### ISSUE TITLE
Text formatting support for cards comments

### ISSUE THREAD

**Issue by Cooler3D** [nextcloud/deck#2143]
Hello
It would be great to add text formatting support for commenting cards.
Currently, formatting is available only for card descriptions.

**Comment by vlastimilott** [comment]
Simple markdown would be great.

**Comment by juliushaertl** [comment]
If we do this it should apply to all comments in Nextcloud so we have it unified. Mind to check if there is already an issue in https://github.com/nextcloud/server and if not open a new one?

**Comment by fthommen** [comment]
There seems to be one at https://github.com/nextcloud/server/issues/17375

**Comment by Dunrar** [comment]
Doesn't seem to be much traction, but this is more important to Deck than to Nextcloud core, I think. Any chance this will be implemented in the Deck app separately from core? The Android app already does it.
