### ISSUE TITLE
Card Menu hidden behind sidebar

### ISSUE THREAD

**Issue by benks-io** [nextcloud/deck#2150]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
The menu of a card is displayed behind the sidebar.

**To Reproduce**
1. install and open decks and
2. create lots of Lists till one reaches the end of the window
3. creat a card and klick it to open the sidebar menu
4. create a card in the very right list
5. click the meat ball menu in the lower right of the card

**Expected behavior**
Menu should be visible as an overlay over the menu

**Screenshots**
![grafik](https://user-images.githubusercontent.com/57667105/88785932-20909c80-d192-11ea-8056-7d189fef29c7.png)

**Client details:**
 - OS: Debian
 - Browser Firefox
 - Version 68.10.0esr (64-Bit)
 - Device: Laptop

**Operating system**:
Debian

**Web server:**
Debian

**Database:**
Percona

**PHP version:**
 Version: 7.3.19 

**Nextcloud version:** (see Nextcloud admin page)
19.0.1

**Where did you install Nextcloud from:**
tar.gz

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
`No errors have been found.`

please ask for details if necessary to debug

**Comment by benks-io** [comment]
Adjusting the z-index is no solution. Showing the menu should not overlay the app content below, but e.g. shrink the app's main content container.
This or something else may be necessary for all apps, that use the upcoming meta concept of the sidebar.

**Comment by juliushaertl** [comment]
We need to fix this in the library, to either allow defining a container that is used for positioning or to make it automatically position left once the Actions menu has been migrated to the popover menu https://github.com/nextcloud/nextcloud-vue/issues/641

**Comment by juliushaertl** [comment]
Can't reproduce anymore on master:

![image](https://user-images.githubusercontent.com/3404133/99237834-4b623780-27f9-11eb-9b0a-6af10912e31e.png)
