### ISSUE TITLE
Error when tag will be removed

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#217]
### Steps to reproduce
1. Choose a card with selected tags
2. Remove tag by clicking on "x"

![screenshot_20170626_213657](https://user-images.githubusercontent.com/16517095/27556878-c6c8f430-5ab7-11e7-9098-9af555cd0881.png)

**Comment by juliushaertl** [comment]
Looks like an upstream bug in ui-select:

https://github.com/angular-ui/ui-select/blob/676675415a383bb72c40b6ea32f368ddea569a42/src/select2/match-multiple.tpl.html#L11

Similar to this: https://github.com/angular-ui/ui-select/pull/1182

**Comment by juliushaertl** [comment]
Since it is not breaking anything but just showing an error in the console, lets close this and make sure this gets fixed upstream.

**Comment by juliushaertl** [comment]
https://github.com/angular-ui/ui-select/pull/2023
