### ISSUE TITLE
Make columns independently scrollable

### ISSUE THREAD

**Issue by despens** [nextcloud/deck#2184]
When doing triage, you usually start with a first column of cards that you want to distribute across your columns. This means that the first column is very tall, filled with a lot of cards and the other columns are empty. To reach bottom cards in the first column it is required to scroll down. When you drag a card from the bottom of the first column into an empty column, the card gets placed on top of that column, which in many cases can would then be scrolled off-screen. The cards appears to vanish.

If each column could be scrolled independently, you could look at the bottom of one column and the top of another, making such triaging tasks much easier.

**Comment by stefan-niedermann** [comment]
Using the <kbd>START</kbd> and <kbd>END</kbd> keys on your keyboard might be a sufficient workaround?

**Comment by juliushaertl** [comment]
Yes, that seems to be also very common among other kanban-like solutions like trello and github projects. cc @nextcloud/designers
