### ISSUE TITLE
Checkboxes started with "+ [ ]" are not counted

### ISSUE THREAD

**Issue by joreiff** [nextcloud/deck#2187]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Description
The markdown dialect used by Nextcloud Deck allows unordered lists of checkboxes to be created using ´* [ ]´, ´- [ ]´ or ´+ [ ]´. The latter, however, is not included in the checked/total count on the card. The following functions need to be adapted:
https://github.com/nextcloud/deck/blob/1afca3a2d49778020893d9ba8424169066a5bb49/src/components/cards/CardBadges.vue#L54-L59

### Steps to reproduce
Create a card with the following description:
```
* [ ] first
- [ ] second
+ [ ] third
```

### Expected behavior
The card shows `0/3`.

### Actual behaviour
The card shows `0/2`.

<details>
<summary>Client details</summary>
**OS:** Fedora

**Browser:** Firefox 79

**Device:** desktop
</details>

<details>
<summary>Server details</summary>

**Operating system**: Centos 8

**Web server:** nginx

**Database:** postgresql

**PHP version:** 7.4

**Nextcloud version:** 18.0.7

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/latest.tar.bz2

**Signing status:**

```
No errors have been found.
```
</details>

**Comment by stefan-niedermann** [comment]
@joreiff do you want to contribute a Pull Request? 🚀 🤘

**Comment by joreiff** [comment]
I have opened pull request #2188 to fix this issue. I was not able to test the changes since I do not have a development environment for web applications set up. The changes, however, should be trivial enough (famous last words :wink:).
