### ISSUE TITLE
Update card description after switch to a new card

### ISSUE THREAD

**Issue by matchish** [nextcloud/deck#2189]
**Describe the bug**
When you edit a card description and switch to another card and then switch back first one, description from second card will be displayed

**To Reproduce**
1. Create to card with different description
2. Start to edit the first card
3.  Click on second card. You will see a description of this card
4. Click on first card. You will see description from second card

**Expected behavior**
The description of first card have to be displayed.

**Client details:**
 - OS: Ubuntu 20.04
 - Browser chrome,
 - Version 84.0.4147.105 (Official Build) (64-bit)
 - Device: desktop

<details>
<summary>Server details</summary>

**Nextcloud version:** 18.04

**List of activated apps:**

```
deck 1.0.1
```

</details>

**Comment by juliushaertl** [comment]
Please update to the latest version as this is fixed already.
