### ISSUE TITLE
NC Server log gets spammed with Error messages when syncing with Android app

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/deck#2196]
### Steps to reproduce
When synchronizing with mobile app, the Server error log is spammed with Errors

- Open the mobile app and refresh (should start automatically) 
- Watch Server Log fill up with errors like these: 

### Expected behaviour
There are no errors when synchronizing with mobile app.

### Actual behaviour
Server log is spammed with errors

## Server configuration detail

**Operating system:** Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.22

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 19.0.1 - 19.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - admin_audit: 1.9.0
 - apporder: 0.10.0
 - bookmarks: 3.3.3
 - breezedark: 19.0.4
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.8
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.0.5
 - documentserver_community: 0.1.7
 - drawio: 0.9.7
 - duplicatefinder: 0.0.2
 - epubreader: 1.4.2
 - event_update_notification: 1.0.2
 - external: 3.6.0
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_downloadactivity: 1.8.0
 - files_markdown: 2.3.0
 - files_mindmap: 0.0.22
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - forms: 2.0.2
 - gpxpod: 4.2.2
 - impersonate: 1.6.1
 - issuetemplate: 0.6.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - maps: 0.1.6
 - metadata: 0.12.0
 - music: 0.16.0
 - news: 14.1.11
 - nextbackup: 20.4.0
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.1
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - occweb: 0.0.7
 - onlyoffice: 4.3.0
 - password_policy: 1.9.1
 - phonetrack: 0.6.4
 - photos: 1.1.0
 - previewgenerator: 2.3.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - rainloop: 7.0.2
 - riotchat: 0.6.3
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - spreed: 9.0.3
 - support: 1.2.1
 - survey_client: 1.7.0
 - suspicious_login: 3.1.0
 - systemtags: 1.9.0
 - tasks: 0.13.3
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - audioplayer
 - encryption
 - files_external
 - firstrunwizard
 - guests
 - mail
 - recommendations
 - social
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "aproposnix.dyndns.org"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "19.0.1.1",
    "overwrite.cli.url": "https:\/\/aproposnix.dyndns.org\/",
    "Overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "app_install_overwrite": [
        "social",
        "dashboard",
        "occweb",
        "issuetemplate"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "updater.release.channel": "beta",
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0

**Operating system:** Ubuntu 20.04

## Logs

<details><summary>Web server error log</summary>

```
N/A
```
</details>

<details><summary>Nextcloud log</summary>

```
[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /index.php/apps/deck/api/v1.0/boards/33/stacks/133/cards/318?
from SNIP at 2020-08-16T00:25:21+00:00


[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /index.php/apps/deck/api/v1.0/boards/28/stacks/114/cards/257?
from SNIP at 2020-08-16T00:25:21+00:00

```
</details>

<details><summary>Browser log</summary>

N/A
</details>

P.S. I love this freaking app! Thank you!

Screen of Errors:
http://pix.toile-libre.org/upload/original/1597542968.png

**Comment by juliushaertl** [comment]
This is actually not a deck issue, see https://github.com/nextcloud/server/issues/20490 for details. A fix has been merged for Nextcloud 20 and the upcoming 19 maintenance release.

> P.S. I love this freaking app! Thank you!

:heart:
