### ISSUE TITLE
delete list in board - please no one click or implement a undo-function

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/deck#2197]
In Nextcloud Deck i can delete with one wrong click a list with a lot of cards. Then there are all deleted and there is no undo-function. Perhaps you can add a question for delete or hide the option in a sub-menu like the option for deleting sharing-links in Nextcloud Files.

Here a screenshot:

![Unbenannt](https://user-images.githubusercontent.com/58322182/90372463-bcfede00-e070-11ea-9720-6e2cb58903e5.PNG)

**Comment by stefan-niedermann** [comment]
@jakobroehrl can you confirm that this issue will be resolved when https://github.com/nextcloud/deck/pull/1853 gets merged?

**Comment by jakobroehrl** [comment]
@stefan-niedermann #1853 doesn't solve this issue. 
@devnull4242 You can undo the list deletion under: details > deleted objects:
![grafik](https://user-images.githubusercontent.com/24530680/90433166-b05ba380-e0cb-11ea-94b1-b07d87d2c641.png)
Does this work for you?

**Comment by stefan-niedermann** [comment]
Ah, sorry

**Comment by juliushaertl** [comment]
We should actually integrate https://github.com/nextcloud/nextcloud-dialogs/pull/106 to have a direct way to undo this in case it was an accident.

**Comment by jakobroehrl** [comment]
closing in favour of https://github.com/nextcloud/deck/issues/2226
