### ISSUE TITLE
Links in the deck notifications of the Activity app do not refer to the respective cards

### ISSUE THREAD

**Issue by black-mosquito** [nextcloud/deck#2199]
**Describe the bug**
The deck notification links in the Activity app will take you to the deck where the cards are organized, but the cards will not load properly. Instead of displaying the respective card, a blank page is displayed.

**To Reproduce**
Select a deck notification in the Activity App and click on the link to the deck card in which the change took place. 

**Expected behavior**
By clicking on the card link in the deck notification of the activity app, the card in which the change took place is displayed.

**Screenshots**
![NX_Deck_Issue](https://user-images.githubusercontent.com/63896203/90405956-c7d36600-e0a4-11ea-8634-f0a0112dc030.png)

**Client details:**
 - OS: macOS 10.15.6
 - Browser: Firefox Developer Edition
 - Version:  80.0b5 (64-Bit)
 - Device: MacMini, Desktop

<details>
<summary>Server details</summary>

**Nextcloud environment details:**
Nextcloud Version 19.0.1 (hosted at hetzner.de)
Nextcloud Deck App Version 1.0.5
Nextcloud Activity App Version 2.12.0

```
No errors have been found.
```

**List of activated apps:**
![NX_ActivatedApps](https://user-images.githubusercontent.com/63896203/90406915-1f260600-e0a6-11ea-8577-cdefe0ae1f22.png)

</details>

**Comment by putt1ck** [comment]
Duplicate #2185

**Comment by black-mosquito** [comment]
> Duplicate #2185

Thanks, I didn't know that this is a known issue and a ticket already exists because of the ambiguous name of the existing ticket.

**Comment by stefan-niedermann** [comment]
I agree and changed the title of the linked issue for clarity.
