### ISSUE TITLE
Archive all stale Cards in stack

### ISSUE THREAD

**Issue by DragonDev1906** [nextcloud/deck#2203]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I have a stack "Done" for completed cards. These cards have accumulated for a while and seem to slow down a refresh of the page (all of those cards have to be loaded). This problem would be solved by archiving the cards. Unfortunately it would take a while to archive all cards manually.

**Describe the solution you'd like**
I would like a button for each stack to archive all Cards older than 1 Month (e.g. in the ... dropdown). This button should archive all Cards in the stack that have been in the stack for at least a Month. Cards that exist for longer but have been moved there in the last month should not be archived. This would reduce the amount of Cards in the Done stack, maybe increase the loading time and it would be simple to archive multiple cards at once.

**Describe alternatives you've considered**
- Instead of 1 Month the time could be changed or there could even be multiple buttons (e.g. 1 Week, 2 Weeks, 1 Month, 2 Months, 4 Months).
- Maybe there could additionally be an option for the stack to do this automatically

**Additional context**
![2020-08-18_20:07:42](https://user-images.githubusercontent.com/8270201/90549005-21638f80-e18e-11ea-9eb1-64f386cf975c.png)

This might be related to #34 but I would like to archive the Cards but still have recent Cards non-archived.

**Comment by juliushaertl** [comment]
I'm really against having to many options in the menu, especially when they have such a limited use case. I'd say this is a good use case for a flow automation, so you might want to add this to #1722 so that cards older than x days can automatically be archived.
