### ISSUE TITLE
Lock Columns to prevent unintentionally displace

### ISSUE THREAD

**Issue by TimoErdmann** [nextcloud/deck#2204]
An option to lock the columns on a board would be great. So an unintentional displace is prevented. Maybe this could be even added for the cards. 
One option could be: Grab a card / collumn and drag it to the desired place. Start a countdown. If the countdown has expired place the card / column where it is dragged. Otherwise move it back to its original place.

**Comment by juliushaertl** [comment]
Dragging is not really a destructive action so I'd actually not do something like this since the order is easily revertable and this will add additional a lot of complexity for quite a small use case.

**Comment by quentinDupont** [comment]
The use case seems to be similar to https://github.com/nextcloud/deck/issues/2669
