### ISSUE TITLE
Add archive/delete buttons onto the grey area of cards

### ISSUE THREAD

**Issue by adamlove86** [nextcloud/deck#221]
Hi there, this is more of a feature request than an issue, but it would be fantastic to add the Archive/Delete buttons onto the empty grey area along the bottom of each card, which would mean less clicks/faster operation to complete those actions.

Obviously down track as more options in the menu are added, you won't be able to fit them all on the card, but as these are the two main ones, I thought it would be quite useful for people form wise.

![screen shot 2017-07-01 at 17 29 58](https://user-images.githubusercontent.com/20361489/27760161-1e3324be-5e84-11e7-8c3e-da084dc29901.png)

PS it's excellent app - really helpful! Thank you!

### Steps to reproduce
1.
2.s
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by pixelipo** [comment]
There are several reasons why I wouldn't go down that path:

- grey area is for car "Details", not " Actions"; it's counterintuitive to mix them together
- there are(will be) plenty of Actions for cards, I don't think Archive and Delete are most commonly used ones
- these two actions are "destructive", so it might be better to keep them one click away, so that user doesn't delete by accident

**Comment by artemanufrij** [comment]
I confirm with @pixelipo . No action buttons in the info line.

**Comment by juliushaertl** [comment]
Yep, let's close this. Keyboard shortcuts as proposed in #46 might be a good way to quickly archive/delete once those are implemented.
