### ISSUE TITLE
Sort/filter cards for last modification date

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#222]
If you use a board for project monitoring it's very helpful to see last modified date in the over view.

**Comment by juliushaertl** [comment]
Not sure if it makes sense by default. We could introduce some sorting functionality that will sort cards by last modify date and show it then. What do you think about that @artemanufrij ?

**Comment by pixelipo** [comment]
"Show modified (cards) since last viewed" filter would be perfect :1st_place_medal:

**Comment by juliushaertl** [comment]
Summarized the filtering/sorting in #414
