### ISSUE TITLE
Deck widget for new dashboard

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/deck#2221]
**Describe the solution you'd like**
It would be nice to have a dashboard widget that would provide some useful information about the open projects on the dashboard. For example: 
- Number of Open Projects
- Number of open tasks per project
- Notifications for card changes 

**Describe alternatives you've considered**
None that I know of 

**Additional context**
For Reference: 
https://github.com/nextcloud/nextcloud-vue-dashboard

Edit: If this is the wrong project to post this to, feel free to gently roast me :)

**Comment by juliushaertl** [comment]
Already work in progress in #2115 :wink:

**Comment by aproposnix** [comment]
Awesome! Thanks a lot. I'll close this request then.
