### ISSUE TITLE
Add vue-material-design-icons

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#2225]
https://www.npmjs.com/package/vue-material-design-icons

Would allow us to make use of some nice icons, e.g. for adding lists/cards:
![image](https://user-images.githubusercontent.com/3404133/91032780-be954c80-e602-11ea-858f-2c98a737ba30.png)
![image](https://user-images.githubusercontent.com/3404133/91032884-de2c7500-e602-11ea-99ff-6f678107b2b4.png)

**Comment by jakobroehrl** [comment]
@juliushaertl @nextcloud/designers 
Which deck icons I should change?

**Comment by juliushaertl** [comment]
Not sure yet if we need to change all in the first place, but if we find a matching replacement in the material icons it would make sense.
