### ISSUE TITLE
Implement undo methods

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#2226]
With https://github.com/nextcloud/deck/pull/2213 we should implement toast based undo for critical operations like delete.

- [ ] Delete Card
- [ ] Delete List
- [ ] Delete Board Tag

**Comment by jakobroehrl** [comment]
@juliushaertl Do you have a code example for me how to implement?

**Comment by juliushaertl** [comment]
Checkout the new showUndo method https://github.com/nextcloud/nextcloud-dialogs/pull/106/files#diff-1355aca4c744fdba046148edea3fb816R168
