### ISSUE TITLE
Feature Wish: Multiline comments

### ISSUE THREAD

**Issue by fthommen** [nextcloud/deck#2227]
It would be great, if comments could be multi-line.  Single-line comments don't allow to give good, structured comments on an issue

**Comment by stefan-niedermann** [comment]
Duloicate of https://github.com/nextcloud/deck/issues/2066

Please use search function before opening new issues 🙂

**Comment by fthommen** [comment]
I had, but I had searched for "multiline" and "multi-line".  It's hard to search for such general keywords.  The other issue doesn't contain _any_ keyword that would have come to my mind to describe the feature ;-).  I will try to manually browse through all open issues next time

**Comment by stefan-niedermann** [comment]
True. I had in mind that there was an open issue, but this one was hard to find 😄
