### ISSUE TITLE
Card overview view

### ISSUE THREAD

**Issue by fthommen** [nextcloud/deck#2229]
Unfortunately Deck doesn't allow to have a complete overview over an issue/card. E.g. details and comments are on different tabs. To compare the main descriptionand related comments, one has to switch back and forth between tabs.  It would be great, if there was a possibility to see detailed description and comments (and metadata as due date, assignee ecc.) on a single page or popover or similar.  Ideally this overview would be printable for those cases, where issues have to be documented or sent on printed paper

**Comment by juliushaertl** [comment]
There is no way we can move this all into one overview. This is just to much information that might occur there. The user interface should remain focussed to what is most important and allow to explore details when needed though the sidebar tabs i'd say.

cc @nextcloud/designers

**Comment by fthommen** [comment]
Is the closing final or is this open to discussion? Comparing with "bigger" tools of this type (YouTrack, Jira), to me this seems to be a important feature  to work effectively with tasks.  We don't need many features, but this one seems a must-have to me. Or are the features also limited by the NextCloud framework that has to be used by the apps?

**Comment by juliushaertl** [comment]
Sure, I'm happy to still discuss this. Maybe you can share some examples how other solutions handle that?

**Comment by fthommen** [comment]
This is be an example of an issue overview from YouTrack.  I don't have access to Jira any more, but it looks similar:

![youtrack_issue_overview](https://user-images.githubusercontent.com/279232/91357156-172a3c80-e7f1-11ea-94b2-438acbc03dce.png)

It's all here: Description, comments and metadata.  Description and comments support Markdown (but I understand that Markdown and multiline comments depend on basic NextCloud functionalities). A simpler version of this could IMHO greatly improve issue overview.

**Comment by stefan-niedermann** [comment]
As far as i know, Jira also has several tabs at the bottom of an issue - you can switch between comments, activities and (depending on installed plugins) a few others

**Comment by fthommen** [comment]
I got temporary access to a Jira instance:

![jira_issue_overview](https://user-images.githubusercontent.com/279232/91410643-7dda4500-e847-11ea-884c-8370d1c093a4.png)

Yes, Jira has some tabs at the bottom but you can still have the complete thematical content (descriptions and comments) in a single windows/screen.

In the frame of my feature wish, description and comments in a single view would be sufficient. I wouldn't even need the metadata.  I am happy with the metadata in the sidebar

**Comment by Dubidubiduu** [comment]
I want to back and modify this issue, as I have used the deck app a lot lately.

Problem:
I got the description, reading from top to bottom, maybe clicking on comments, reading from bottom up, which is irritating.

Also I don't want to check by myself if there is any comment. And even if #730 is closed, users could forget/oversee that important thing, which is a bad user experience. Same goes for attachment.

So, coming to my modification:
Show all in one tab, except of History/Zeitachse. Put Attachments beneath of "add to project", show comments from oldest to newest right under the description.

That way I got all the important information at acute glance.

**Comment by nidico** [comment]
I have created a new proposal with a similar outcome, but a slightly different focus, see #3511.

**Comment by dodedodo** [comment]
This would be solved by Clementine46's proposal in #2702, wouldn't it?

**Comment by fthommen** [comment]
> This would be solved by Clementine46's proposal in #2702, wouldn't it?

If the proposal includes a view where description and comments can be viewed on a single page, then yes.  I can't see such a view in #2702 and on https://marvelapp.com/prototype/237i8946/section/1281212 but maybe there is just no mockup for this specific layout :-) . Other than that I like the proposition (but not as much as @juliushaertl's initial proposition/mockup at https://github.com/nextcloud/deck/issues/2702#issue-778911380 :-) )
