### ISSUE TITLE
install deck

### ISSUE THREAD

**Issue by wangzq96** [nextcloud/deck#2236]
cURL error 7: Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by juliushaertl** [comment]
Seems there is a server or connection issue. Please check if you can manually download the file from https://github.com/nextcloud/deck/releases/download/v1.0.5/deck.tar.gz otherwise you might need to try again later.
