### ISSUE TITLE
Too many scrollbars / long descriptions

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2257]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

When having descriptions which are longer than a single screen page, a scrollbar is shown for the sidepanel and the description as well as the fields are scrollable:
![screenshot-20200904_09021599202926](https://user-images.githubusercontent.com/431045/92209617-97a20a80-ee8d-11ea-9e90-b5010a18bc78.png)

However, if the description is edited, an additional scrollbar shows up for the edit field:
![screenshot-20200904_09041599203081](https://user-images.githubusercontent.com/431045/92209690-b99b8d00-ee8d-11ea-8bf1-f2b40b0284fb.png)

there are now two problems:
1) When in the edit mode, it is annoying to edit text and for example insert attachments, as you have to scroll up and down constantly. Furthermore, as there are now two scrollbars, you either scroll the whole sidepanel or just the editbox.
2) When in view mode, I think it would make more sense to keep the fields fixed and only scroll the description - allthough I have to admit that probably depends on your screensize. For small screens that is not a good solution, as the description would be small.

**Describe the solution you'd like**

* At least get rid of one of the scrollbars in edit mode, for example the one of the edit field, as it looks like this one only scrolls a few lines.
* If possible, show the buttons for switching the modes and inserting attachments always.
* If possible with screen size etc, show all the fields during editing and viewing description (basically only ever scroll the description box not the whole sidebar)

**Comment by juliushaertl** [comment]
> If possible with screen size etc, show all the fields during editing and viewing description (basically only ever scroll the description box not the whole sidebar)

This might of course not work on mobile if the screen size is too small to show the full sidebar content.

However :+1: for all the other suggestions. We could probably think about a making the sidebar header and tabs sticky.

**Comment by juliushaertl** [comment]
Seems like we fixed this already somewhere on the road, doesn't happen anymore on master.

**Comment by newhinton** [comment]
I have the same issue with V1.4.2 (firefox 88.0 & chromium 90.0.4430.93)

![grafik](https://user-images.githubusercontent.com/25279821/117699298-f6f6ae00-b1c4-11eb-9a09-bd97796b6ac6.png)
