### ISSUE TITLE
App icon looks weird on 0.2.1

### ISSUE THREAD

**Issue by 9662** [nextcloud/deck#227]
I have just upgraded from 0.2.0 to 0.2.1 on NC11. I am using the [Direct Menu](https://github.com/juliushaertl/direct_menu/) application.

The deck icon after the 0.2.1 upgrade looks much smaller than the others. Not sure if this is intentional.

On desktop (deck icon is second from right):
![screenshot_20170705_160727](https://user-images.githubusercontent.com/13080040/27868615-97864d70-619d-11e7-9af0-3ca89b4a5a58.png)

---

On phone:
![screenshot_20170705-161305](https://user-images.githubusercontent.com/13080040/27868657-b323ac44-619d-11e7-83e1-d485ee0292b6.png)

**Comment by juliushaertl** [comment]
Fixed with #234
