### ISSUE TITLE
Provide image scaling via GET parameter

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#2273]
Attached images should be scalable via a parameter to reduce the size for previews.

Similar to the avatar endpoint one could add something like

```
https://<image-uri>/64
```

for a scaled down version of the image which fits into a 64x64 px square.

Alternatively a `GET` parameter like

```
https://<image-url>?size=64
```

would work, too.

Would also be needed for https://github.com/nextcloud/deck/issues/1635#issuecomment-605927698 but since we have an Android client in the meantime, this might be even more important :wink:

**Comment by juliushaertl** [comment]
Makes sense :+1:

**Comment by stefan-niedermann** [comment]
We have to decide whether or not the image should be cropped.

Avatars are always quadratical, which makes it easy, but i guess most attached images are in formats like 4:3 or so because they are photos.

Since *my* intention is to use it as previews, i would prefer to first center-crop them before downscaling, otherwise the preview thumbnail grid will look a bit messy.

What do you think?

**Comment by juliushaertl** [comment]
Once we have #2638 the files preview api can handle all of that, so let's close this here.
