### ISSUE TITLE
Remember nav sidebar status?

### ISSUE THREAD

**Issue by mxmilkiib** [nextcloud/deck#2284]
**Is your feature request related to a problem? Please describe.**

Closing the left burger sidebar, refreshing the page, the sidebar comes back again.

**Describe the solution you'd like**

The sidebar status to be remembered.

**Comment by juliushaertl** [comment]
I remember we had this at some point, so marking as a regression. Probably got lost during the vue rewrite.

**Comment by probastaller** [comment]
Wish it was added to v1.1.0 release...
Also would love to see the selection of "compact view" to be remembered unless changed even after logout and login again in nextcloud.
Sorry if it is not the right place to put it. I thought it could be related ;P
