### ISSUE TITLE
A more compact compact mode?

### ISSUE THREAD

**Issue by mxmilkiib** [nextcloud/deck#2285]
Compact mode task cards aren't really that compact, imo. There's space enough for another line above and below the text in each card (although it would touch the card edges, but still, that's a full line of text's height).

**Comment by jakobroehrl** [comment]
Could you provide a sketch eg?

**Comment by mxmilkiib** [comment]
Like, this is my Deck after copying my todos from my Kanboard
![image](https://user-images.githubusercontent.com/108225/93524772-eab79b00-f92c-11ea-822f-b7847a8a13fe.png)

This is my Kanboard (with custom CSS saved via a textarea in the admnin section)
![image](https://user-images.githubusercontent.com/108225/93524942-2b171900-f92d-11ea-8da7-cb838d27113e.png)

**Comment by juliushaertl** [comment]
I would generally not reduce the space there further as with the kanboard this feels quite cluttered, but cc @nextcloud/designers @jancborchardt for some more feedback.

**Comment by mxmilkiib** [comment]
I'm not sure why there are unhappy reactions to my shots as I'm not suggesting changing the existing compact mode, though I do admit my wording was ambiguous.

I would be interested in an new option. Like a super-compact mode.

Design and UX is intersubjective; I have a subjectively different conception of compact, but I'm fairly sure others "objectively" will share that opinion and would prefer the extra option.

But whatever may be may be, I can't have expectations, worst case I can install Stylus and override the existing theme.

**Comment by juliushaertl** [comment]
:ping_pong: @jancborchardt and @Clementine46 as well

**Comment by raimund-schluessler** [comment]
> But whatever may be may be, I can't have expectations, worst case I can install Stylus and override the existing theme.

You can use the Custom CSS app https://github.com/juliushaertl/theming_customcss to adjust Nextcloud styles.

**Comment by ma12-co** [comment]
@mxmilkiib we don't go below 44px for the shortest dimension in clickable elements for accessibility reasons. I think that that's pretty much as compact as we can get.

**Comment by mxmilkiib** [comment]
There are a diverse number of definitions of accessibility. Due to my issues with attention/memory, I (and, I'm sure, others) function better with all items visible on the screen at once.

I don't think the rational given for blocking this is logically consistent with the reality of how "accessibility" can fairly be defined.
