### ISSUE TITLE
Set a due date not working on 20.0.0beta4 using Deck v1.1.0-beta1

### ISSUE THREAD

**Issue by sunjam** [nextcloud/deck#2296]
Remains blank after selecting a card `Set Due Date` on both beta3 and now beta4.  Silently fails.
![image](https://user-images.githubusercontent.com/1787238/93006155-a59aff80-f50d-11ea-896f-9b6ec229e8d7.png)

[NextcloudPi 20.0.0beta4](https://github.com/nextcloud/nextcloudpi/issues/1177) on Odroid C2.

**Comment by juliushaertl** [comment]
Yes, this should be fixed on master already, new beta should arrive soonish.
