### ISSUE TITLE
Attachments not working

### ISSUE THREAD

**Issue by dhrunia** [nextcloud/deck#2300]
I am trying to add attachments to the description but when I click on the attachments button I just get a blank popup like this:

![Screenshot from 2020-09-15 17-02-11](https://user-images.githubusercontent.com/7869622/93228183-83a3b600-f775-11ea-890e-e45b7f30431d.png)

Nextcloud version: 19
Deck version: 1.0.5

**Comment by juliushaertl** [comment]
Fixed on master with #1740

**Comment by juliushaertl** [comment]
Will be part of 1.1.0
