### ISSUE TITLE
The style is broken after update to 0.2.1

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/deck#231]
Hi,

thank all of you for the next release of this great app, but after upgrade from `0.2.0` to `0.2.1`, the style is broken. Removing the app and reinstalling did not solve the problem....

Am I doing something wrong?

Thank you!

### Log:
```
Error	lib	ResourceLocator can not find a web root (root: /apps2/deck, file: css/deck/style.css, webRoot: , throw: true)
```

![board list](https://user-images.githubusercontent.com/20214043/27886811-f2f1fa98-61dd-11e7-9d2b-d77b79a3ce74.png)
![board](https://user-images.githubusercontent.com/20214043/27886812-f2f25222-61dd-11e7-88da-9dd4037916cf.png)

### Server configuration
**Operating system**: Linux 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64

**Web server:** nginx/1.13.1 (fpm-fcgi)

**Database:** pgsql PostgreSQL 9.6.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.2.1) 6.2.1 20160822, 64-bit

**PHP version:** 7.1.6
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, Phar, exif, ftp, gmp, intl, ldap, mcrypt, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.0 Build:2017-06-14T07:34:13+00:00 426a4c11d6700f011897d17330f2364f1c9b04ee - 12.0.0.29

**List of activated apps:**
<details>
	<summary>App list</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.1.0
 - audioplayer: 2.0.2
 - bookmarks: 0.10.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - checksum: 0.3.4
 - circles: 0.11.0
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.1
 - drawio: 0.8.8
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.4
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_markdown: 1.0.1
 - files_opds: 0.8.2
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxedit: 0.0.7
 - gpxpod: 2.1.4
 - groupfolders: 1.1.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - mood: 0.2.0
 - news: 11.0.5
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocsms: 1.12.0
 - ownbackup: 17.5.0
 - passman: 2.1.2
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - qownnotesapi: 17.5.0
 - quota_warning: 1.0.1
 - registration: 0.2.3
 - richdocuments: 1.12.33
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_diaspora: 1.0.1
 - socialsharing_email: 1.0.1
 - socialsharing_facebook: 1.0.1
 - socialsharing_googleplus: 1.0.1
 - socialsharing_twitter: 1.0.1
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - telephoneprovider: 1.0.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - twofactor_u2f: 1.3.2
 - updatenotification: 1.2.0
 - weather: 1.5.0
 - workflowengine: 1.2.0
 - workin2gether: 0.9.6

Disabled:
 - apporder
 - encryption
 - external
 - files_snapshots
 - keeweb
 - ojsxc
 - ownpad
 - previewgenerator
 - rainloop
 - user_external
 - user_ldap
```

</details>

**Are you using encryption:** no

### Client configuration

**Browser:**
- `Chromium`: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36
- `Mozilla Firefox`: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

**Operating system:** Fedora Rawhide

**Comment by artemanufrij** [comment]
@lachmanfrantisek 
have you try to refresh website by CTRL+F5?

**Comment by lachmanfrantisek** [comment]
Yes, but nothing changed...

I've also tried another browser, log out/log in and restarting the webserver..

**Comment by lachmanfrantisek** [comment]
Now, I've tried the fresh docker container ([wonderfall/nextcloud](https://hub.docker.com/r/wonderfall/nextcloud/) - `12` and `daily`), but with the same result.

**Comment by artemanufrij** [comment]
have you updated deck or fresh installed that?

**Comment by lachmanfrantisek** [comment]
I've tried both:

At first, I've only updated the deck. Since it didn't work, I've uninstall/remove/install the app (same result).

Now, I've also tried fresh install of nextcloud (`daily` and `12`) and only install the deck app, and the result was same.

Btw, thanks for such a quick response.

**Comment by artemanufrij** [comment]
I have it tested on apache and lighttp and it works fine.

tomorrow I will setup a system with nginx and I will try to reproduce this issue...

PS: I have almost same setup like you (apache instead nginx and mariadb instead postpresql) and it works very well on two systems

**Comment by lachmanfrantisek** [comment]
> I have it tested on apache and lighttp and it works fine.

Weird.

> PS: I have almost same setup like you (apache instead nginx and mariadb instead postpresql) and it works very well on two systems

I'm using Docker, so the setup should be reproducible easily.

(For the completeness, the fresh instances used SQLite..)

Anyway, thank you.

**Comment by juliushaertl** [comment]
@lachmanfrantisek This is a Nextcloud bug, see: https://github.com/nextcloud/server/issues/5289

**Comment by juliushaertl** [comment]
Btw. removing the style.scss file from decks app folder should fix the issue for now. :wink:

**Comment by lachmanfrantisek** [comment]
@juliushaertl Thank you for the info.

> Btw. removing the style.scss file from decks app folder should fix the issue for now. 😉

Yes, this works. Thank you.
