### ISSUE TITLE
Do not list archived projects in calendar/tasks

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/deck#2311]
First, I want to say that the new integration is very exciting! Thanks to everyone involved in this. 

**Describe the solution you'd like**
The new calendar/task view shows all calendars and task regardless whether they are active or not . I would like to only see my active projects or at least to be able to manually select which projects are to be listed in the calendar/tasks

**Describe alternatives you've considered**
No alternatives identified.

**Comment by juliushaertl** [comment]
Hm indeed that might have been missed somewhere. I'll look into that.

**Comment by juliushaertl** [comment]
> I would like to only see my active projects or at least to be able to manually select which projects are to be listed in the calendar/tasks

Yes that would be a second step I'd say. Would you mind to open a separate issue for this?

**Comment by aproposnix** [comment]
> > I would like to only see my active projects or at least to be able to manually select which projects are to be listed in the calendar/tasks
> 
> Yes that would be a second step I'd say. Would you mind to open a separate issue for this?

Yup... I will do it.

**Comment by jakobroehrl** [comment]
> Hm indeed that might have been missed somewhere. I'll look into that.

@juliushaertl 
Is the problem here: 
https://github.com/nextcloud/deck/blob/e460879f4108056992312d26f8155e34c9e5024b/lib/DAV/DeckCalendarBackend.php#L61

https://github.com/nextcloud/deck/blob/master/lib/Service/BoardService.php#L128

Do we need to add a filter for only non archived boards here?

**Comment by juliushaertl** [comment]
Fixed in 79b950e
