### ISSUE TITLE
API Call - Header "OCS-APIRequest"

### ISSUE THREAD

**Issue by reitbauer** [nextcloud/deck#2315]
API Docu:
All requests require a OCS-APIRequest HTTP header to be set to true and a Content-Type of application/json.

On try to send a request with OCS-APIRequest HTTP header i got an error:
Request header field OCS-APIRequest is not allowed by Access-Control-Allow-Headers.

**Comment by juliushaertl** [comment]
Could you provide some details about the request you are actually sending?

Apparently it works as expected here:
`curl --request GET --url 'https://admin:admin@nextcloud/index.php/apps/deck/api/v1.0/boards' --header 'ocs-apirequest: true' --header 'Content-Type: application/json' -v`

**Comment by reitbauer** [comment]
If you try to make this request with e.g. Axios, you will get an Cors error

**Comment by juliushaertl** [comment]
In case you are trying to perform requests from within Nextcloud, please see the regular routes in https://github.com/nextcloud/deck/blob/master/appinfo/routes.php#L30-L80 instead of the /api/v1.0/ ones.
