### ISSUE TITLE
Activity Stream link to Cards

### ISSUE THREAD

**Issue by yellelieder** [nextcloud/deck#2321]
If a card is mentioned in the activity stream, the reference link to this card does not link to the card. In the Link there ist one slash too much. 
 
Link is linke: https://DOMAIN/index.php/apps/deck/#/board/NUMBER//card/NUMBER
But should be: https://DOMAIN/index.php/apps/deck/#/board/NUMBER/card/NUMBER

So one can´t reach card directly form the activitiy stream.

**Comment by jakobroehrl** [comment]
@juliushaertl 
I can reproduce it. Where can I fix it? Can't find something in the ActivityManager.php. Is it another file where the actvitiy links are generated?

**Comment by stefan-niedermann** [comment]
references #2253 and #1698

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/deck/pull/2252 already, will be part of the next release.
