### ISSUE TITLE
deck card descriptions will not be saved / console: error 500, but no logs 

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/deck#2344]
### Steps to reproduce
create deck, try to enter text description

### Expected behaviour
description will be saved

### Actual behaviour
text message ('Speichere...') doesn't go away. Will not be saved. On RELOAD of browser page, it will be saved. 
The same is happening when I try to delete cards - on pressing 'reload' the card will be deleted.

## Server configuration detail

**Operating system:** Linux 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** pgsql PostgreSQL 12.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit

**PHP version:** 

7.3.19-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, gmp, gnupg, horde_lz4, iconv, igbinary, imagick, imap, intl, json, ldap, exif, memcache, msgpack, mysqli, pdo_mysql, pdo_pgsql, pgsql, apc, posix, propro, raphf, readline, redis, shmop, SimpleXML, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, http, memcached, Zend OPcache

**Nextcloud version:** 18.0.9 - 18.0.9.1

**Updated from an older Nextcloud/ownCloud or fresh install:** has been updated since years from some of the first owncloud versions

**Where did you install Nextcloud from:** updater

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.11.0
 - bbb: 1.1.0
 - bookmarks: 3.4.1
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.4.0
 - data_request: 1.5.0
 - dav: 1.14.0
 - deck: 1.1.0
 - external: 3.5.0
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_fulltextsearch: 1.4.3
 - files_fulltextsearch_tesseract: 1.4.2
 - files_linkeditor: 1.1.2
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 2.0.4
 - fulltextsearch: 1.4.2
 - fulltextsearch_elasticsearch: 1.5.2
 - groupfolders: 6.0.7
 - impersonate: 1.5.2
 - issuetemplate: 0.7.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.4.1
 - metadata: 0.12.0
 - nextcloud_announcements: 1.7.0
 - notes: 3.6.4
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocr: 6.0.56
 - photos: 1.0.0
 - polls: 1.4.3
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - rainloop: 6.1.4
 - ransomware_protection: 1.6.1
 - recommendations: 0.6.0
 - richdocuments: 3.7.4
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.8
 - support: 1.1.1
 - survey_client: 1.6.0
 - talk_simple_poll: 1.2.0
 - tasks: 0.13.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - user_ldap: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - drop_account
 - encryption
 - federation
 - files_clipboard
 - files_external
 - files_readmemd
 - password_policy
 - ransomware_detection
 - socialsharing_email
 - systemtags

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "18.0.9.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "theme": "",
    "maintenance": false,
    "maxZipInputSize": 838860800,
    "allowZipDownload": true,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "1": "cloud.elternserver.de",
        "2": "cloud.sohoserver.de",
        "3": "cloud.faudin.de"
    },
    "forcessl": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "overwritewebroot": "\/",
    "overwrite.cli.url": "https:\/\/cloud.faudin.de\/",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 2
    },
    "knowledgebaseenabled": false,
    "trashbin_retention_obligation": "auto",
    "versions_retention_obligation": "auto, 7",
    "check_for_working_wellknown_setup": true,
    "loglevel": 1,
    "updatechecker": true,
    "lost_password_link": "https:\/\/ssp.datilo.de\/?action=sendtoken",
    "tempdirectory": "\/var\/www\/tmp\/",
    "mail_smtpport": "25",
    "app.mail.imaplog.enabled": false,
    "cron_log": true,
    "log_rotate_size": 10485760,
    "appstoreenabled": true,
    "asset-pipeline.enabled": false,
    "activity_expire_days": 7,
    "singleuser": false,
    "ldapIgnoreNamingRules": false,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "updater.release.channel": "stable",
    "htaccess.RewriteBase": "\/",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_sendmailmode": "smtp",
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "files_clipboard",
        "passman"
    ],
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\PDF",
        "OC\\Preview\\Image",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\SVG",
        "OC\\Preview\\Font",
        "OC\\Preview\\MP3",
        "OC\\Preview\\Movie",
        "OC\\Preview\\MKV",
        "OC\\Preview\\MP4",
        "OC\\Preview\\AVI",
        "OC\\Preview\\HEIC"
    ],
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "spreed": {
        "bbb_server": "https:\/\/conference.faudin.de\/bigbluebutton\/",
        "bbb_secret": "Kycdc7BhbZmP6JdiEgsy4vreGoyGurJzZKEjtLj6o"
    },
    "overwritehost": "cloud.faudin.de",
    "overwriteprotocol": "https"
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
_lastChange: 1601369633background_sync_interval: 43200background_sync_offset: 0background_sync_prefix: cleanUpJobOffset: 100enabled: yeshas_memberof_filter_support: 1home_folder_naming_rule: attr:uidinstalled_version: 1.8.0last_jpegPhoto_lookup: 0ldap_agent_password: xxxxxxxx ldap_attributes_for_group_search: cn
descriptionldap_attributes_for_user_search: ldap_backup_host: ldap_backup_port: ldap_base: dc=elternserver,dc=deldap_base_groups: ou=groups,dc=elternserver.de,dc=elternserver,dc=deldap_base_users: ou=people,dc=elternserver,dc=deldap_cache_ttl: 600ldap_configuration_active: 1ldap_default_ppolicy_dn: ldap_display_name: cnldap_dn: cn=admin_ro,dc=elternserver,dc=deldap_dynamic_group_member_url: ldap_email_attr: mailldap_experienced_admin: 0ldap_expert_username_attr: ldap_expert_uuid_group_attr: cnldap_expert_uuid_user_attr: uidldap_gid_number: gidNumberldap_group_display_name: cnldap_group_filter: (&(|(objectclass=groupOfNames)))ldap_group_filter_mode: 1ldap_group_member_assoc_attribute: memberldap_groupfilter_groups: ldap_groupfilter_objectclass: groupOfNamesldap_host: someserver.localldap_login_filter: (&(&(|(objectclass=posixAccount)))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(mail=%uid))))ldap_login_filter_mode: 0ldap_loginfilter_attributes: mailldap_loginfilter_email: 1ldap_loginfilter_username: 1ldap_nested_groups: 0ldap_override_main_server: 0ldap_paging_size: 500ldap_port: 389ldap_quota_attr: ldap_quota_def: 20000000000ldap_tls: 1ldap_turn_off_cert_check: 0ldap_turn_on_pwd_change: 0ldap_user_display_name_2: mailldap_user_filter_mode: 1ldap_userfilter_groups: ldap_userfilter_objectclass: posixAccountldap_userlist_filter: (&(|(objectclass=posixAccount))(|(memberof=cn=xxxx,ou=groups,dc=elternserver,dc=de)))types: authenticationuse_memberof_to_detect_membership: 1
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

**Operating system:** osx

## Logs

<details><summary>Web server error log</summary>

```
(nothing relevant)
```
</details>

<details><summary>Nextcloud log</summary>

```
nothing relevant
```
</details>

<details><summary>Browser log</summary>

browser console errors: 

xhr.js:184 PUT https://cloud.blablablabla.de/apps/deck/cards/267 500 (Internal Server Error)

createError.js:16 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.p.onreadystatechange (xhr.js:69)

</details>

![image](https://user-images.githubusercontent.com/6523646/95001646-193fa200-05cc-11eb-93ed-832dfcb1f2cd.png)

**Comment by codeHorse87** [comment]
The exception object which is returned in the 500 response on my side is:

`{"exception":{"\u0000*\u0000message":"Call to undefined method OCA\\Deck\\Event\\FTSEvent::hasArgument()","\u0000Exception\u0000string":"","\u0000*\u0000code":0,"\u0000*\u0000file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","\u0000*\u0000line":109,"\u0000Exception\u0000trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{},"update"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\CardController","update",{},{"cardId":"1002","_route":"deck.card.update"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"cardId":"1002","_route":"deck.card.update"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{},{"cardId":"1002","_route":"deck.card.update"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1013,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/deck/cards/1002"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"\u0000Exception\u0000previous":{}}}`

**Comment by juliushaertl** [comment]
Testing and reviews are very welcome on https://github.com/nextcloud/deck/pull/2358 for this issue

**Comment by joergmschulz** [comment]
fixed in https://github.com/nextcloud/deck/pull/2358
