### ISSUE TITLE
Deck in russian not have share

### ISSUE THREAD

**Issue by morphay** [nextcloud/deck#2346]
Hi to all. When i switch the interface to russian, there is no share menu in the deck/board settings, instead there is a trash. But in other languages - english, ukrainian, bulgarian, italian, the sharing menu is present and works.

Nextcloud 19.0.3
OS: openSUSE Leap 15.2 x86_64, Kernel: 5.3.18-lp152.41-default 
PHP: 7.4.6; PHP Modules: apcu bcmath bz2 Core ctype curl date dom exif fileinfo filter ftp gd gettext gmp hash iconv imagick intl json ldap libxml mbstring memcached mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql pdo_sqlite posix redis Reflection session SimpleXML SPL sqlite3 standard tokenizer xml xmlreader xmlwriter Zend OPcache zip zlib

https://image.upweb.me/image/qGw
https://image.upweb.me/image/9F2

**Comment by stefan-niedermann** [comment]
Pretty sure this is related to https://github.com/nextcloud/deck/issues/2343 in some way...

**Comment by morphay** [comment]
https://image.upweb.me/image/VE1
https://image.upweb.me/image/zIe

**Comment by morphay** [comment]
in https://demo2.nextcloud.com/   also this problem is present

**Comment by juliushaertl** [comment]
Fix is proposed upstream for the vue library:
https://github.com/nextcloud/nextcloud-vue/pull/1431

**Comment by juliushaertl** [comment]
Fixed with `@nextcloud/vue@v2.6.9

**Comment by maxior2004** [comment]
Nextcloud 19.0.4
I got the same problem

npm i --save @nextcloud/vue
did not help
