### ISSUE TITLE
Description visible on/off

### ISSUE THREAD

**Issue by DarkknightAK** [nextcloud/deck#2348]
Hi,

Deck is awesome it give a great overview, but sometimes the description is a bit to hidden in the sidebar. Would it be possible to add an description visible on/off toggle? 

Than deck would be also similar to padlet which was used often in schools (for homeschooling).
https://www.netzwerk-digitale-bildung.de/wp-content/uploads/Padlet.jpg

**Comment by jakobroehrl** [comment]
So, you want to show (the first x lines) of the description in the card oerview, right?
I like the idea. 
@juliushaertl What do you think? 
Global Option or for every board?

**Comment by DarkknightAK** [comment]
Yes that's the idea show header + description like you know it from github, twitter, comment software, ...

**Comment by juliushaertl** [comment]
We decided to don't show the description (see stefan-niedermann/nextcloud-deck#298 for the whole discussion on the card layout) 

Generally we should not have settings for UI preferences and instead choose sane defaults. 

Quoting @jancborchardt on that:
> If we add settings for each simple thing, we also need to maintain all these and test them. And soon our interface will look like described in the article [»This Is What Happens When You Let Developers Create UI«](https://blog.codinghorror.com/this-is-what-happens-when-you-let-developers-create-ui/).

> Another important read is [»Choosing our preferences«](https://ometer.com/preferences.html).
