### ISSUE TITLE
 Impossible to drop the card in an empty column

### ISSUE THREAD

**Issue by oparoz** [nextcloud/deck#235]
### Steps to reproduce

1. Move a card from its current location to and empty column

### Expected behaviour

The dotted drop zone should show up

### Actual behaviour

Impossible to drop the card

On 0.2.1

**Comment by juliushaertl** [comment]
@pixelipo Can you have a look, this might be caused by the migration to SCSS.

**Comment by juliushaertl** [comment]
Fixed with #238
