### ISSUE TITLE
Add Comments to Tickets in Addition to the description

### ISSUE THREAD

**Issue by romulus010689** [nextcloud/deck#2350]
Would be really nice to have a "Comments" Section in the Tickets. The Description is normally used to describe the task more clearly, that anybody understands what needs to be done.

And the comments normally should track or help to review what exactly has already be made in this task. It would also be helpful if you use blockers, this way you could add a comment explaining why a task is blocked.

**Comment by stefan-niedermann** [comment]
There **is** a comments section in the sidebar of each card.
