### ISSUE TITLE
On Time Selection, Make Click Date to go back to Date Selection Clearer

### ISSUE THREAD

**Issue by SethiPandi** [nextcloud/deck#2354]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When setting a due date on an issue, sometimes the user regrets the data they selected and wants to back once on the time selection.  
The problem is there is no visual cue on how to go back from the time selection to the date selection. I found there was a way from guessing but _in my opinion_, the current UI/UX isn't intuitive for a new user. 

**Describe the solution you'd like**

There could be an icon prepended to the date so make a visual indication it performs the back function to go back to date selection, for example using the `⮨` icon.

![image](https://user-images.githubusercontent.com/22801583/95077132-477bc980-0713-11eb-9be0-e24e745b205a.png)

> Note, I am not a designer, and I'm not specifically suggesting this icon should be used. It's just an example.

**Describe alternatives you've considered**
Alternatively, there could be a "BACK" button on the opposite side of the "OK" button to go back.

![image](https://user-images.githubusercontent.com/22801583/95077768-52832980-0714-11eb-9d08-ccc92af16640.png)
> While this doubles up a 2nd button which does the same thing, it's immediately obvious that the back button will take a user back, unlike the date above which requires assuming, or hovering over to notice it's interactive.

**Comment by juliushaertl** [comment]
Please open an issue in our shared ui components repo https://github.com/nextcloud/nextcloud-vue about this since the date picker is coming from there and other Nextcloud apps could benefit from that enhancement as welll.
