### ISSUE TITLE
Content Overflows Cards in Archived Boards

### ISSUE THREAD

**Issue by paulcalabro** [nextcloud/deck#2356]
### Steps to reproduce
1. Create a board (e.g. "Foobar")
2. Create a card in the board (e.g. "Build Widget)
3. Assign the card to a user (e.g. Joe)
4. Archive the board
5. Click on 'Archived Boards' in the side menu
6. Click on the  "Foobar" board.
7. Examine the card. Note the user icon is not contained within the card any longer. Other content might overflow (not tested).

### Expected behaviour
Content should not overflow.

### Actual behaviour
Content overflows.

## Server configuration detail

**Operating system:** 

**Webserver:** nginx/1.19.0 (fpm-fcgi)

**Database:** 

**PHP version:** 

**Nextcloud version:** 19.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from a minor release

**Where did you install Nextcloud from:** Docker Hub

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - admin_audit: 1.9.0
 - analytics: 2.5.0
 - announcementcenter: 3.8.1
 - appointments: 1.7.7
 - apporder: 0.11.0
 - bookmarks: 3.4.1
 - breezedark: 19.0.4
 - browser_warning: 1.0.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - camerarawpreviews: 0.7.8
 - checksum: 0.4.5
 - circles: 0.19.6
 - cloud_federation_api: 1.2.0
 - cms_pico: 1.0.10
 - comments: 1.9.0
 - contacts: 3.4.0
 - contactsinteraction: 1.0.0
 - cookbook: 0.7.6
 - cospend: 1.0.5
 - customproperties: 1.0.1
 - data_request: 1.6.0
 - dav: 1.15.0
 - deck: 1.1.0
 - diffuse: 2.5.3
 - drawio: 0.9.7
 - duplicatefinder: 0.0.2
 - emlviewer: 0.0.18
 - encryption: 2.7.0
 - end_to_end_encryption: 1.5.2
 - epubreader: 1.4.2
 - event_update_notification: 1.0.2
 - external: 3.6.0
 - extract: 1.2.4
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_accesscontrol: 1.9.1
 - files_automatedtagging: 1.9.0
 - files_downloadactivity: 1.8.0
 - files_external: 1.10.0
 - files_fulltextsearch_tesseract: 1.4.2
 - files_linkeditor: 1.1.2
 - files_lock: 0.8.3
 - files_markdown: 2.3.1
 - files_mindmap: 0.0.22
 - files_pdfviewer: 1.8.0
 - files_photospheres: 1.19.1
 - files_retention: 1.8.2
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_texteditor: 2.11.0
 - files_trackdownloads: 1.8.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_versions_s3: 0.1.3
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - flowupload: 1.0.0
 - forms: 2.0.4
 - geoblocker: 0.3.2
 - gpxmotion: 0.0.11
 - gpxpod: 4.2.2
 - group_everyone: 0.1.6
 - groupfolders: 7.0.0
 - groupquota: 0.1.4
 - guests: 1.5.0
 - imageconverter: 1.2.1
 - impersonate: 1.6.1
 - issuetemplate: 0.7.0
 - keeweb: 0.6.3
 - limit_login_to_ip: 3.0.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - maps: 0.1.6
 - metadata: 0.12.0
 - music: 0.16.0
 - news: 14.2.2
 - nextbackup: 20.9.0
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - ocdownloader: 1.7.8
 - ocsms: 2.1.8
 - ojsxc: 4.1.1
 - onlyoffice: 6.0.2
 - ownpad: 0.6.15
 - passman: 2.3.6
 - password_policy: 1.9.1
 - passwords: 2020.10.0
 - phonetrack: 0.6.4
 - photos: 1.1.0
 - piwik: 0.7.0
 - polls: 1.4.3
 - previewgenerator: 2.3.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - qownnotesapi: 20.9.0
 - quickaccesssorting: 1.0.3
 - quicknotes: 0.6.1
 - quota_warning: 1.8.0
 - rainloop: 7.0.3
 - ransomware_detection: 0.8.0
 - ransomware_protection: 1.7.0
 - recommendations: 0.7.0
 - richdocuments: 3.7.4
 - richdocumentscode: 4.2.800
 - scanner: 0.1.9
 - sendent: 1.0.15
 - sensorlogger: 0.1.2
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - sharingpath: 0.2.5
 - side_menu: 1.16.0
 - social: 0.3.1
 - socialsharing_diaspora: 2.1.0
 - socialsharing_email: 2.1.0
 - socialsharing_facebook: 2.1.0
 - socialsharing_twitter: 2.1.0
 - spreed: 9.0.4
 - support: 1.2.1
 - survey_client: 1.7.0
 - suspicious_login: 3.2.1
 - systemtags: 1.9.0
 - talk_simple_poll: 1.2.0
 - tasks: 0.13.3
 - text: 3.0.1
 - theming: 1.10.0
 - timemanager: 0.1.4
 - timetracker: 0.0.43
 - transmission: 0.6.0
 - twofactor_admin: 3.0.0
 - twofactor_backupcodes: 1.8.0
 - twofactor_gateway: 0.17.0
 - twofactor_nextcloud_notification: 2.3.0
 - twofactor_totp: 5.0.0
 - twofactor_u2f: 6.0.0
 - updatenotification: 1.9.0
 - user_ldap: 1.9.0
 - user_retention: 1.2.0
 - user_saml: 3.2.0
 - user_usage_report: 1.3.3
 - video_converter: 0.1.4
 - viewer: 1.3.0
 - w2g2: 3.0.2
 - weather: 1.7.3
 - wopi: 3.5.5
 - workflow_pdf_converter: 1.4.0
 - workflow_script: 1.4.0
 - workflowengine: 2.1.0
Disabled:
 - dashboard
 - dashboardcharts
 - dropit
 - facerecognition
 - files_antivirus
 - files_ebookreader
 - files_frommail
 - gpgmailer
 - keeporsweep
 - mood
 - occweb
 - ocr
 - ownbackup
 - radio
 - telephoneprovider
 - twofactor_email
 - uploaddetails

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```

```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** 

<details><summary>LDAP configuration (delete this par if not used)</summary>

```

```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0

**Operating system:** macOS Catalina 10.15.7

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by paulcalabro** [comment]
Example:

![Screen Shot 2020-10-05 at 9 23 02 AM](https://user-images.githubusercontent.com/585059/95108325-ff977b00-06ef-11eb-8b4c-18df4ccf26ac.png)

**Comment by paulcalabro** [comment]
@juliushaertl 

Thanks for your help! 
I'm still seeing the issue across three browsers (FF, Chrome, and Safari) with the latest release (v1.1.1):

![Screen Shot 2020-10-13 at 8 12 48 AM](https://user-images.githubusercontent.com/585059/95880088-faf44780-0d2b-11eb-8468-1a1bbe5667c9.png)

Please let me know if you need additional info.

**Comment by juliushaertl** [comment]
Yes this was just done for the next maintenance release 1.1.2 https://github.com/nextcloud/deck/pull/2439

However since we have quite some nice fixes for that already I'll probably do another release this week.

**Comment by paulcalabro** [comment]
Thanks @juliushaertl ! I can confirm that the v1.1.2 release resolves the issue. 🎉
