### ISSUE TITLE
Deleting a Deck does not remove Deck Calendar

### ISSUE THREAD

**Issue by brimwats** [nextcloud/deck#2357]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
I deleted a deck, but the calendar "Deck: Title" remains
**To Reproduce**
1. Have deck that shows up on calendar.
2. Go to deck app, delete deck.
3. Go back to calendar, the Deck calendar is still present.

**Expected behavior**
Calendar should be deleted. 

**Screenshots**

**Client details:**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] latest Chrome
 - Version [e.g. 22] 19.03
 - Device: [e.g. iPhone6, desktop] desktop

<details>
<summary>Server details</summary>

**Operating system** & **Web server:**

Operating System:	Linux 3.10.0-962.3.2.lve1.5.27.el7.x86_64 x86_64 
CPU:	Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (8 cores) 
Memory:	31.26 GB

**Database:**
Type: mysql
Version: 5.7.31
Size: 46.1 MB

**PHP version:** 
Version: 7.3.21
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 300 MB

**Nextcloud version:** (see Nextcloud admin page) 19.03

**Where did you install Nextcloud from:** Cpanel

**Comment by freakms** [comment]
Information: I got an error with this way, that the cal's are not removable. Same issue

**Comment by vasyugan** [comment]
How is this fixed? I still cannot delete deck generated calendars.
