### ISSUE TITLE
Drag and drop broken when window is not full screen

### ISSUE THREAD

**Issue by oparoz** [nextcloud/deck#236]
### Steps to reproduce

1. Set the window size to half the screen
1. Bring out the description panel 
1. Move a card

### Expected behaviour

Card should be picked up where the mouse is

### Actual behaviour

Card jumps to another location, making it impossible to move to its destination.

0.2.1

Nextcloud stable12
Browser: Chromium 58

**Comment by juliushaertl** [comment]
@oparoz I cannot reproduce that. Can you report some details about Nextcloud/Browser version?

**Comment by oparoz** [comment]
Just tested and it's not broken, so will provide additional steps when I have them

**Comment by oparoz** [comment]
OK, so you simply need to bring out the description panel and things start to break
