### ISSUE TITLE
Edited Text is not reloaded if switching from enlarged to sidebar view

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2362]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**
1. Create new card
2. edit the description
3. switch into enlarged view while still in edit (or into sidepanel view if already in enlarged view)
4. description is empty
5. reloading the page fixes it

**Expected behavior**
Description should be synced, even if switching views

**Client details:**
 - OS: Debian Buster, Windows 10
 - Browser: Chrome, Firefox

Deck 1.1.0 / NC 19.0.3

**Comment by budachst** [comment]
Additionally to this, it seems not to be possible to further edit/change the description in the details tab. The first edit of the description will show after a page reload but subsequent edits never show. Also, there's a notfication that the changes get saved, which also doesn't go away.

**Comment by budachst** [comment]
My guess is, that the edited text didn't make it to the database. So I installed the latest nightly and that fixed the issue for me.

**Comment by juliushaertl** [comment]
@budachst Not sure if this is the same issue, since we had nothing in the regard of this one where master differs from 1.1.0, yours could be however related to https://github.com/nextcloud/deck/pull/2358

**Comment by budachst** [comment]
Well, I actually can't tell. All I was noticing was that, added tags would only show up an page reoads, as well as editing the description of a card would first, show the same behaviour and second couldn't be edited a 2nd time.

I then checked the database and found, that further edits to the description field would not make it to the database. This was when I scanned the nightly build for resolved bugs and spotted something regarding database access, installed that and the issues were both gone.

**Comment by reox** [comment]
I just checked in 1.2.3 and it seems to be fixed? Can someone else confirm that too?
However the behavior changed: When changing from sidebar to modal while in edit mode, the modal view will now be in view mode.

**Comment by juliushaertl** [comment]
Yes, should be fixed by ironing out some quirk where the sidebar was actually rendered twice (once hidden) when the modal was used.

> However the behavior changed: When changing from sidebar to modal while in edit mode, the modal view will now be in view mode.

Would make sense to restore the old behaviour i think. Feel free to open a new issue for that.

**Comment by juliushaertl** [comment]
Let's close. If anyone still encounters an issue, please let me know.

**Comment by reox** [comment]
> Would make sense to restore the old behaviour i think. Feel free to open a new issue for that. 

Personally: I do not care :D I usually work only in the modal view nowadays, because I find it much more pleasing.

Thanks for fixing that issue!
