### ISSUE TITLE
Cannot find people to share to

### ISSUE THREAD

**Issue by e8johan** [nextcloud/deck#2368]
**Describe the bug**

When trying to share a deck, I cannot seem to share with federated contacts, only locals.

**To Reproduce**
1. Go to Deck, and select a board
2. Click on Details -> Sharing
3. Enter a known, federated, user id (I already share files with the person)
4. The drop down reads "No Results"

**Expected behavior**

That I could share the board with the person.

**Operating system**:

NextCloudPi 19.0.3

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

"No errors have been found."

**Comment by juliushaertl** [comment]
This is not yet supported (see #789)
