### ISSUE TITLE
Error when updating Deck

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#237]
When I updated Deck to the latest version via git on my development environment and then upgraded my Nextcloud through the web interface (cause I had updated Deck), I got this error:

```
Doctrine\DBAL\Exception\TableNotFoundException:
An exception occurred while executing
'SELECT * FROM "oc_accounts" WHERE "user_id" IS NOT NULL LIMIT 1':
SQLSTATE[HY000]: General error: 1 no such table: oc_accounts
```

Was pretty scary … when I removed the Deck app it was fixed. Any idea @nextcloud/deck?

**Comment by juliushaertl** [comment]
@jancborchardt Are there any more details in the error log like a stacktrace where this error occurs?

**Comment by jancborchardt** [comment]
Hmm … it seems like my local development instance is a bit broken by something else. Need to investigate, but probably this has nothing to do with Deck. :)

**Comment by ChristophWurst** [comment]
I just got the same error when I switched branches of the nextcloud server (master to https://github.com/nextcloud/server/pull/5585). Maybe @nickvergessen knows more about this issue, it could be related to the new migrations mechnism.

**Comment by ChristophWurst** [comment]
Tracked down the exception to this code snippet: https://github.com/nextcloud/server/blob/21f2fe5cb97985596879032d1191612cab31b9d5/lib/private/Repair/Owncloud/SaveAccountsTableData.php#L90-L93

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/6001

Would have been nice someone created the issue in the server repo like a month ago...

**Comment by jancborchardt** [comment]
@nickvergessen had no idea this was an issue in the server. :) "Would have" also been nice if more people try out Deck. ;)
