### ISSUE TITLE
[invalid date] in Epiphany

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#240]
currently I work on elementary os. Deck shows "invalid date" in default browser Epiphany.

![bildschirmfoto von 2017-07-08 21 44 02](https://user-images.githubusercontent.com/16517095/27988647-29c69416-6427-11e7-9971-e30233ad9dc5.png)

**Comment by JiriMON** [comment]
I can confirm same behaviour on Safari and Chrome.

**Comment by juliushaertl** [comment]
@artemanufrij Does this happen on loading or does it appear after some time on the site?

**Comment by JiriMON** [comment]
For me, immediately after setting date. For both new and existing cards. Tried to disable and enable application, but this not solved the problem.

**Comment by artemanufrij** [comment]
@juliushaertl on loading

**Comment by jancborchardt** [comment]
Can confirm this happens on Safari on macOS as well. Stays there permanently, not only on loading.
