### ISSUE TITLE
After deletion of a card, next card klicked will not show description

### ISSUE THREAD

**Issue by ghost** [nextcloud/deck#2400]
**Describe the bug**
After deleting a card the next card you open will not show it's notes in the sidebar.

**To Reproduce**
1. Create three Cards with a Description
2. delete one card
3. klick on the other card
4. See Description empty
5. klick in the other card
6. See the Description is visible

**Expected behavior**
Descriptions should be visible every time a card is opened

**Client details:**
 - Device: [e.g. iPhone6, desktop]

**Operating system**: Debian Buster

**Web server:** Apache

**Database:** Percona

**PHP version:** 7.4

**Nextcloud version:** 20

**Where did you install Nextcloud from:** tar.gz

**Comment by joshtrichards** [comment]
Looks good today.
