### ISSUE TITLE
Use the last board and list moved to when reopening the "Move Card" dialog

### ISSUE THREAD

**Issue by Flamenco** [nextcloud/deck#2405]
This is self explanatory.  The fewer clicks the better.

**Comment by Flamenco** [comment]
<img width="286" alt="Screen Shot 2020-10-11 at 9 15 55 PM" src="https://user-images.githubusercontent.com/819940/95695903-fda94c80-0c06-11eb-952b-c3cb13e1db86.png">

**Comment by joshtrichards** [comment]
This is what happens today (unless the browser is refreshed).

**Comment by Flamenco** [comment]
Yes, "No one assigned" did a great job.  Buy her a coffee!. ☕️

**Comment by Flamenco** [comment]
It remembers if you do not even move the card at all. lol. 😂
