### ISSUE TITLE
Click and drag in slide details causes UI issues

### ISSUE THREAD

**Issue by TeknoShamin** [nextcloud/deck#241]
### Steps to reproduce
1. Create new board.
2. Create new deck.
3. Create new slide.
4. Enter text into slide.
5. Click on text and drag to the right.
6. Observe how the right hand window appears.

### Expected behaviour
Nothing should happen.

### Actual behaviour
The right hand window pane appears.

### Server configuration
**Operating system**: Linux farnsworth 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64

**Web server:** nginx/1.10.0 (fpm-fcgi)

**Database:** mysql 10.0.29

**PHP version:** 7.0.15-0ubuntu0.16.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

"No errors have been found."

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - activitylog: 0.0.1
 - admin_notifications: 1.0.0
 - announcementcenter: 3.0.0
 - apporder: 0.3.3
 - bookmarks: 0.10.0
 - calendar: 1.5.3
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - deck: 0.2.1
 - defaultgroup: 0.3.0
 - direct_menu: 0.10.2
 - drawio: 0.8.8
 - external: 1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_automatedtagging: 1.1.1
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.0.1
 - files_reader: 1.0.4
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextant: 1.0.8
 - nextcloud_announcements: 1.0
 - notes: 2.3.1
 - notifications: 1.0.1
 - ocsms: 1.12.0
 - ojsxc: 3.2.1
 - ownpad: 0.5.10
 - passman: 2.1.2
 - password_policy: 1.1.0
 - previewgenerator: 1.0.6
 - provisioning_api: 1.1.0
 - rainloop: 5.0.0
 - registration: 0.2.5
 - richdocuments: 1.11.33
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - audioplayer
 - encryption
 - files_accesscontrol
 - files_external
 - files_retention
 - githubmergetracker
 - keeweb
 - mail
 - news
 - piwik
 - spreed
 - spreedme
 - tasks
 - user_external
 - user_ldap
 - user_saml
 - weather
 - workin2gether
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "oceghwuwwlam",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.tripsit.me"
    ],
    "datadirectory": "\/usr\/share\/nginx\/nextcloud-data",
    "overwrite.cli.url": "https:\/\/cloud.tripsit.me",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_domain": "tripsit.me",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "mail_from_address": "cloud",
    "mail_smtpport": "465",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "mail.tripsit.me",
    "mail_smtptimeout": 30,
    "maintenance": false,
    "mail_smtpsecure": "ssl"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Operating system:**

Windows 7

===I can provide logs if needed ===

**Comment by artemanufrij** [comment]
confirm

**Comment by juliushaertl** [comment]
related to https://github.com/nextcloud/deck/issues/262

**Comment by juliushaertl** [comment]
Already fixed by 
ec5389b
