### ISSUE TITLE
Feature Request: Ability to archive decks

### ISSUE THREAD

**Issue by TeknoShamin** [nextcloud/deck#242]
Currently it's possible to archive Boards (options on the left pane) and Slides (entries within in columns) but not possible to archive Decks (the columns themselves). My team and I feel this feature would be useful to have. Thank you.

**Comment by artemanufrij** [comment]
Do you mean like this: #34 ?

**Comment by TeknoShamin** [comment]
They're basically the same thing, yes, though i think 'archive' is the better term. Feel free to close if you wish, thank you.

**Comment by artemanufrij** [comment]
ok. we will track in on #34
