### ISSUE TITLE
Show a comment badge for cards that have a description

### ISSUE THREAD

**Issue by Flamenco** [nextcloud/deck#2424]
<img width="286" alt="Screen Shot 2020-10-11 at 9 15 55 PM" src="https://user-images.githubusercontent.com/819940/95695937-216c9280-0c07-11eb-8beb-51c21acd91ca.png">

Other considerations to be discussed.

1. best position on card - bottom left
2. preview on hover - first x characters from comment and ellipsis
3. click action - open sidebar and select card
4. best icon to use - icon-comment
5. show icon in condensed mode? i suggest no.

**Comment by juliushaertl** [comment]
Dupicate of https://github.com/nextcloud/deck/issues/1873
