### ISSUE TITLE
Assign cards to groups

### ISSUE THREAD

**Issue by aixzellent** [nextcloud/deck#2431]
**Is your feature request related to a problem? Please describe.**
We would like to assign cards to groups.

**Describe the solution you'd like**

**Describe alternatives you've considered**
The assignment of cards to people would have to be extended so that they could also be assigned to groups with whom the board was shared. In addition, of course, other functions, such as the notification function, would have to be adapted accordingly.

**Additional context**
-

**Comment by juliushaertl** [comment]
Was already implemented with https://github.com/nextcloud/deck/pull/1629 and releases as part of 1.0.0
