### ISSUE TITLE
Mini calendar selector should highlight current date

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#244]
### Steps to reproduce
1. Choose a due date
2. Check what todays date is manually on your computer
3. Actually choose the due date ;)

### Expected behaviour
The calendar popover highlights the current day.

### Actual behaviour
It’s not highlighted.

Also cc @nextcloud/calendar since this should be fixed for all instances of this mini calendar popover. :)

**Comment by juliushaertl** [comment]
See https://github.com/nextcloud/deck/issues/205 :wink:

**Comment by jancborchardt** [comment]
:D Damn, sorry … should search or look through the other issues. Was sitting next to a user and had to keep up with some of the detail issues coming up. ;)
