### ISSUE TITLE
can't update to deck 1.1.1

### ISSUE THREAD

**Issue by ulph0** [nextcloud/deck#2447]
hi, i hope this is the right place to files this. didn't find this bug. i can't update from deck 1.0.5 to deck 1.1.1 in nextcloud 19.0.4. when i try to, an error message appears: "An error occured during the request. Unable to proceed.
Couldn't update app." this only happens with deck, all other "apps" are updating as usual.

nextcloud.log tells this:

{"reqId":"wnHizeb5RQp7gHir9KBm","level":3,"time":"2020-10-14T19:46:26+00:00","remoteAddr":"91.64.193.230","user":"xxxxxx","app":"core","method":"GET","url":"/index.php/settings/apps/update/deck","message":{"Exception":"Exception","Message":"Could not extract app deck","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Installer.php","line":197,"function":"downloadApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/www/html/apps/settings/lib/Controller/AppSettingsController.php","line":531,"function":"updateAppstoreApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"updateApp","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"updateApp"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"updateApp"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","updateApp",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"appId":"*** sensitive parameter replaced ***","_route":"settings.AppSettings.updateApp"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"appId":"*** sensitive parameter replaced ***","_route":"settings.AppSettings.updateApp"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"appId":"*** sensitive parameter replaced ***","_route":"settings.AppSettings.updateApp"}]},{"file":"/var/www/html/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/update/deck"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Installer.php","Line":295,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.4.2"}

**Comment by juliushaertl** [comment]
Hmm, that looks odd. It worked fine when installing it just some minutes ago on another instance of mine. Could be that there was an issue with the download. Can you check if it works after having another try?

**Comment by ulph0** [comment]
dear julius, this doesn't work for me since the update to 1.1.1 came out, so i tried it nearly approx. 20 times the last weeks, while i updated several others including nextcloud versions. now 21 times, but nothing changed. one thing changed; that meanwhile the update to 1.1.2 is out. but unfortuately it still doesn't work.

**Comment by juliushaertl** [comment]
Do other app updates work fine for you? Could you maybe check if your tmp directory is properly writable by the webserver?

As a reference this is where it fails in the server code:
https://github.com/nextcloud/server/blob/d9015a8c94bfd71fe484618a06d276701d3bf9ff/lib/private/Installer.php#L292-L306

**Comment by juliushaertl** [comment]
As a side note: you can always manually download the release from apps.nextcloud.com and replace the deck directory manually of course ;)

**Comment by ulph0** [comment]
dear julius, thank you very much, but didn't want to update manually, i wanted to find the solution for my problem, sorry, but that's how mybrain works :)
yes, other app updates worked, none ever didn't work, but fortunately your answer lead my to the solution. since i am running nc on a raspberry 3, i am using tmpfs for /tmp and didn't give it much memory, just 30MB. now i raised that to 60 MB and the update worked like a charme now. thank you very much and have a nice day. 
ps: of course an appropriate error message would have helped me to find the solution on my own.

**Comment by ulph0** [comment]
ok. https://github.com/nextcloud/server/issues/23482
