### ISSUE TITLE
Color for all created boards is the same unless modified

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#245]
### Steps to reproduce
1. Create a board
2. Create another board
3. Create another board

### Expected behaviour
The first board should be blue, the next should be (the next color in line), the third should be (third color in line) automatically.

### Actual behaviour
All are blue and need to be colored manually.

**Comment by 9662** [comment]
FWIW, I am not sure whether this is a bug or a feature.

One way to approach this is to ask: what is colour intended to communicate in the decks list?
 * If it is simply to highlight that there are multiple decks, is it adding much value?
 * If the choice of meaning (if any) of deck colour is left to the user, wouldn't it be better to apply a single default colour, and for the user to manually change it if they wish?

Just my thoughts. Funnily enough, I came here with a list of issues, and you have posted them all (and then some) a couple of hours ago. This was one which I considered but then decided I would not mention. 😛

**Comment by jancborchardt** [comment]
The point of a color is to quickly visually differentiate different boards. In a test it came to lots of confusion and tasks added to wrong boards because the title alone is not enough to differentiate (you don’t really look at it). See iOS Reminders for example: When you add a new list, the default selected color is one you haven’t used for any of the other lists (if possible).

Defaults are rarely changed by users and hence the defaults should always be really great. :)


@9662 nice :) keep the issues coming, especially design issues and detail findings are very appreciated on any Nextcloud app.

**Comment by juliushaertl** [comment]
> The first board should be blue, the next should be (the next color in line), the third should be (third color in line) automatically.

Good point. 

@jancborchardt @9662 Any issue reporting is very welcome here. :wink:  I sadly don't have much time to focus on deck right now.

This might be a good starter issue, just check for existing boards colors and select the first unused color when opening the view to create a new board.

**Comment by juliushaertl** [comment]
Fixed in #334. Thanks to @rpadovani

**Comment by frinanta** [comment]
I want every user can choose their own color in nextcloud templet, eg user a want yellow color, user b want green color, can you help me, how to make it?

**Comment by juliushaertl** [comment]
@frinanta Not possible at the moment and I don't see that coming, since it is a very specific feature that would add a lot of additional code that needs to be maintained.
