### ISSUE TITLE
editing title in sidebar or focus view is buggy/doesn't work

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/deck#2451]
**Describe the bug**
See Reproduction. Severe bug, unusable interface! Only way to edit tasks is directly on the card.

**To Reproduce**
1. click on a card
2. in sidebar or in focus view: click on title and start typing. 
3. a few letters get added, cursor jumps between end and other positions, then editing stops by itself, some letters jump around, editing as intended does not work

**Expected behavior**
edit title, type enter or click on arrow or click somewhere else to save new title.

**Client details:**
 - OS: Linux Mint 19.3
 - Browser: both Chromium 85.0.4183.121 and Firefox 81.0
 - Device: desktop

Nextcloud Server: both 19.0.3 and 18.0.3 on different hosters
Deck App: 1.1.2

**Comment by djsime1** [comment]
On NC 20.0.0 and Deck 1.1.2, I get a similar issue where after entering a single letter the text entry looses focuses. To be more specific, it looses focus when the PUT request gets a response from the server. Issue occurs in both latest Firefox and Chrome.

**Comment by alexanderdd** [comment]
@jakobroehrl can you please put this on 1.2.0 milestone? 
In my opinion this is a severe bug, making Deck unusable.

**Comment by jakobroehrl** [comment]
@juliushaertl Can confim it.

https://github.com/nextcloud/deck/blob/master/src/components/card/CardSidebar.vue#L24-L30
Any idea what the problem could be?

**Comment by absynth47215** [comment]
Latest Chrome and Safari on MacOS X here, on NC20.0.01 / Deck 1.1.2, same issue.

**Comment by juliushaertl** [comment]
This is actually fixed by #2500 

@jakobroehrl See https://github.com/nextcloud/deck/pull/2500/files#diff-e1cecfa1956390baf6fa4e14ed48b22cb5d3d09aadb6628a2c61f15e0bcd3c37R28-R30 in case you're interested in the details

**Comment by alexanderdd** [comment]
It works =) =) Thank you!!
Deck 1.2.1, Nextcloud 19.0.4
