### ISSUE TITLE
Integration with Nextcloud/GNOME

### ISSUE THREAD

**Issue by gerald-drissner** [nextcloud/deck#2461]
Hi, just a quick remark: It would be great if it was possible to integrate DECK (calendar entries) automatically with GNOME (Nextcloud Account -> Calendar). I appreciate any development into this direction. THANKS!

**Comment by stefan-niedermann** [comment]
Which version of Deck are you using? As far as i know this shoul already be possible since version 1.1.0, the boards are exposed via CalDAV as calendars.

**Comment by gerald-drissner** [comment]
I am using 1.1.2 and GNOME 3.36.3
Using the "online accounts" feature of GNOME, I only get the Nextcloud Calendar - but not Deck. 
I also tried to import it manually in Evolution via CalDAV. Didn't work either. It also didn't work to get Deck entries into Google Calendar by using CalDAV. Any idea is greatly appreciated. Your app is really amazing - keep up your great work!

**Comment by Torenga** [comment]
I set up the default groupware (GNOME Online Accounts, GNOME Calendar and GNOME Todo, all with Evolution as back-end) to check - The Deck-entries shows up in GNOME Todo as tasks. This indicates that the Evolution back-end sync is working, and it's down to how the GNOME groupware is handling it.

I've just been introduced to Deck's CalDAV-features myself so my speculation is that cards end up as "events" in the same way as regular tasks in the calendar file. Then perhaps adding general task support to GNOME Calendar is the way to go?

**Comment by gerald-drissner** [comment]
Same here! I see the entries as "tasks" - but in the calendar, I do not
see them. So far, I found no solution.

Am Sonntag, den 25.10.2020, 14:03 +0000 schrieb Torenga:
> I set up the default groupware (GNOME Online Accounts, GNOME Calendar
> and GNOME Todo, all with Evolution as back-end) to check - The Deck-
> entries shows up in GNOME Todo as tasks. This indicates that the
> Evolution back-end sync is working, and it's down to how the GNOME
> groupware is handling it.
> 
> I've just been introduced to Deck's CalDAV-features myself so my
> speculation is that cards end up as "events" in the same way as
> regular tasks in the calendar file. Then perhaps adding general task
> support to GNOME Calendar is the way to go? 
>

**Comment by juliushaertl** [comment]
> Then perhaps adding general task support to GNOME Calendar is the way to go?

Yes, that should be the way to go. I cannot find any issue for this in the gnome calendar repo, but showing task due dates in there would be the solution that makes most sense to me. Deck cards are not really calendar events, but rather todo entries as they are exposed as VTODO elements through CalDAV.
