### ISSUE TITLE
link boards to contacts, contacts to boards

### ISSUE THREAD

**Issue by xpseudonym** [nextcloud/deck#2462]
**Describe the bug**
Contacts should be assignable to boards, but are not.
It says here [https://nextcloud.com/blog/nextcloud-deck-1-0-available-today-plus-deck-for-android/](url):
>Is it that time of the year again? And you need to organize the same event for another time? Well everything (to do’s, contacts...

Issue #781 'Board linked to Contacts' was closed in favour of Issue #810 'Linking collaboration objects' which was in turn closed in favour of Issue #965 'Collections for cards' closed as implemented 25.01, but Issue #965 doesn't seem to do anything for linking Boards to Contacts...  And, I can't work out how to do it, so I think Issue #781 is the wood that got lost in the trees.

**To Reproduce**
1. Look for a way to link boards to contacts
2. Fail to find a way to link boards to contacts

**Expected behavior**
Boards can be linked to contacts

**Screenshots**
n/a

**Client details:**
 - OS: gnu/linux
 - Browser FF
 - Version 76
 - Device: desktop

<details>
<summary>CentOS8</summary>
Running:
ID
    5b02d746c27c
Tags
    docker.io/library/nextcloud:latest
Entrypoint
Command
    apache2-foreground
Created
    10/05/2020

Base version - apache run via podman-compose
</details>

**Comment by putt1ck** [comment]
Assignable to boards as in link contacts to boards, or as in "here is a board with cards, I want to assign a card to a contact *who is not a user on my NC*?

**Comment by xpseudonym** [comment]
Thanks - I'm not sure I understand the distinction, but probably both.
So, my jobs are generally one-off jobs for clients and so, I want (probably, early days yet) define boards by jobs by clients, thus by contacts and have all the client contact info available in the board.
That said, I might also want to assign someone who is not a client to a task (card) who is not a user on Nextcloud.
For the foreseeable future I'm going to be the only user on my Nextcloud, but I work with others.

**Comment by stefan-niedermann** [comment]
The Nextcloud Projects feature support linking Deck cards and boards with other artifacts in Nextcloud (e. g. Files, Talk rooms, etc.).

At the Deck side everything is already available, you should open an issue at the contacts repository to implement Nextcloud Projects.
