### ISSUE TITLE
Feature Request: Make a Native Desktop App for Deck

### ISSUE THREAD

**Issue by WulftheNordicRanger** [nextcloud/deck#2468]
The web app is nice, but for some people (like myself) the fact that one has to use a browser to run it is kinda annoying. A native app would be better for people such as myself.

**Comment by stefan-niedermann** [comment]
I doubt that this will happen - AFAIK there aren't native desktop clients for Jira, Trello and other comparable projects.

But there is a well documented [REST-API](https://decks.readthedocs.io) - Maybe you want to start one? 🙂

The resources are always limited and IMHO it makes more sense to use them carefully and better invest them into making this app to feel more like a native app (with offline support etc).

References https://github.com/nextcloud/deck/issues/2207

But that's just my opinion, let's wait for an official statement from the maintainer @juliushaertl

**Comment by juliushaertl** [comment]
Anyone is of course very welcome to write a native desktop client but there are no plans from our side on that.

Contributions regarding offline support would of course be very welcome, but it is also nothing on our roadmap as of today.
