### ISSUE TITLE
the same card has several places at the same time

### ISSUE THREAD

**Issue by Jeanoo** [nextcloud/deck#2487]
**Is your feature request related to a problem? Please describe.**
when I want to display a single card on another board I have to redo the card each time.

**Describe the solution you'd like**
I wish I could:
   1) possibility to see the same card in several different lists.
   2)  Possibility to see a list on several boards at the same time.

**Describe alternatives you've considered**
This saves a lot of time since you don’t need to create duplicates when you have several employees who have to do the same job but have different permissions or statuses.

**Comment by stefan-niedermann** [comment]
How would you handle the case, when a card appears in multiple boards at the same time, but the boards have different lists?

**Comment by Jeanoo** [comment]
it is necessary to choose the list and the table at the same time.

**Comment by juliushaertl** [comment]
Not just lists also labels and users might be different across boards so this is nothing we currently plan to implement.
