### ISSUE TITLE
Black icon instead of white one on the dashboard

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/deck#2492]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
The Dashboard app shows a dark icon for Deck instead of a white one if the dark mode is active.

**To Reproduce**
1. Turn on dark mode
1. Visit the Dashboard app
1. Add the Deck widget

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1869584/97908683-4dcb8880-1d47-11eb-8a50-b1a813892ed9.png)

**Details:**
- Got this bug on https://demo1.nextcloud.com/apps/dashboard/ so Nc 20 with newest versions of the apps probably.

Removing the inline svg code (which comes from https://github.com/nextcloud/deck/blob/master/src/css/dashboard.scss) fixes the color issue:

![image](https://user-images.githubusercontent.com/1869584/97910215-b9165a00-1d49-11eb-92fd-8411abfbea3e.png)

**Comment by splitt3r** [comment]
Also a "Create new card/board" button just like the calendar shows would be pretty cool 👍🏻

**Comment by rahulpatel596** [comment]
@juliushaertl  I'd like to work on this if still available for grab?

**Comment by juliushaertl** [comment]
> Also a "Create new card/board" button just like the calendar shows would be pretty cool 👍🏻

Please open a separate issue for this :)

**Comment by R7JANV1** [comment]
Is there any progress?

**Comment by foss-** [comment]
Working as expected in Deck 1.8.3, Nextcloud 25.0.3
Can this be closed?
<img width="290" alt="ok" src="https://user-images.githubusercontent.com/5708172/219882079-acadb20d-ecce-4444-b3ea-71d2f9023ea4.png">
