### ISSUE TITLE
"Create new card/board" for the Dashboard widget

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/deck#2494]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
There should be a "Create new card/board" button in the dashboard widget. I think it is not as easy as the calendar one because there is no route for the new form yet + you can delete everything in Deck but the calendar app has at least a personal calendar all the time. So there needs to be some logic to check if new card / board makes sense.

**Screenshots**
![image](https://user-images.githubusercontent.com/1869584/97908683-4dcb8880-1d47-11eb-8a50-b1a813892ed9.png)

_Originally posted by @splitt3r in https://github.com/nextcloud/deck/issues/2492#issuecomment-720672725_

**Comment by juliushaertl** [comment]
Yes, I'd say a modal with basic inputs for board/stack selection and card title would be a good starting point here.
