### ISSUE TITLE
Card title is being deleted/switched back while typing in the card details

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/deck#2499]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When I insert/edit the name of a card in the card details side pane, it's deleted/reverted again and again. it's not usable. 
Changing the title in the card itself (in the overview of the lists) works fine.

**To Reproduce**
1. Go to card details
2. Click on the title field
3. Try typing

**Expected behavior**
The text entered appears and doesn't get deleted/replaced with former text automatically.

**Client details:**
 - OS: Win10
 - Browser Firefox 82.0.2, Chrome 86.0.4240.111
 - Version Deck 1.1.2 | nextcloud 19.0.4
 - Device: desktop

**Comment by reox** [comment]
> When I insert/edit the name of a card in the card details side pane

I have this bug also in the detached view.

**Comment by alexanderdd** [comment]
Duplicate of https://github.com/nextcloud/deck/issues/2451
