### ISSUE TITLE
Emptycontent view for archived and shared boards filter [$10]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#250]
Currently the view for archived and shared boards (when there are none) is just an empty list with a header. This is quite confusing as people could see the header as placeholder text.

There should be the normal emptycontent view as it’s also in files for empty folders (simply use the same HTML :)

In the shared boards view, we could even say in the emptycontent view:

> ### No shared boards yet
> **[ Create a new board ]** and share it with people

With the button directly there.

**Comment by pixelipo** [comment]
Even better would be to hide those menu items when empty?

**Comment by jancborchardt** [comment]
Yeah, that’s maybe an even better call. For archived boards for sure, and I guess for shared ones too.

If we move to listing boards only in the navigation bar on the left, then I would do away with these special entries anyway. Boards could be sorted by recency of use/activity, shared boards will have an indicator, and on the bottom of the list will be a switch saying »Show archived boards« (like in the Mail app).

**Comment by Nebri** [comment]
> Even better would be to hide those menu items when empty? - pixelipo

Personally I like the way it is right now, but yes empty view placeholders is definitely good to clarify! Here's a list of the messages that I would insert. Upon @juliushaertl  approval I will get started!

"There are currently no stacks for this board, get started by creating a stack"

"There are currently no cards for this stack, get started by creating a card"

"There are currently no archived boards"

"There are currently no shared boards"

**Comment by jancborchardt** [comment]
@Nebri sounds good! :) Make sure to use the `div class="emptycontent"` standard with an icon, h2 and p inside of it. (Check how the Files app does it for empty folders for example.)

**Comment by Nebri** [comment]
> sounds good! :) Make sure to use the div class="emptycontent" standard with an icon, h2 and p inside of it. (Check how the Files app does it for empty folders for example.)

Thanks for pointing that out! I'll revise my PR :).
