### ISSUE TITLE
Ability to edit titles of cards in place [$10]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#251]
### Steps to reproduce
1. Add some stacks
2. Notice you can edit the titles of the stacks in place
3. Try the same on the cards

### Expected behaviour
It works and you can edit the titles of cards in place.

### Actual behaviour
It doesn’t and you need to use the right sidebar for that. It’s a bit confusing when some things are editable in place and some are not. ;)

**Comment by 9662** [comment]
This feature should probably be tested for (absence of) interference with card drag & drop, especially on small form-factor devices.

**Comment by GoetheG** [comment]
YES. Good idea.

**Comment by Nebri** [comment]
@juliushaertl This is pretty straight forward, I'd like to take this one on. I'll get started on your go-ahead.

**Comment by juliushaertl** [comment]
Fixed by #592
