### ISSUE TITLE
modal-header toggles invisibilty

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2516]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

When in the detached detail view, I can see that the modal-header div is toggling invisibility after some time.
That makes the text "Kartendetails" appear and disappear after some time.

It is this DIV in the HTML
```
<div data-v-df113852="" class="modal-header invisible" style="display: none;"><div data-v-df113852="" class="modal-title">
					Kartendetails
				</div> [...]</div>
```

After a while it displays as:
```
<div data-v-df113852="" class="modal-header" style=""><div data-v-df113852="" class="modal-title">
					Kartendetails
				</div> [...]</div>
```

(`[...]` is truncated HTML)

**To Reproduce**
1. Open a card 
2. wait some time and see "Kartendetails" appear and disappear

**Expected behavior**

The title should stay static

**Screenshots**

![image](https://user-images.githubusercontent.com/431045/98538096-8d83fa00-228a-11eb-844d-cd663a7b7eef.png)

just wait a bit to see:
![image](https://user-images.githubusercontent.com/431045/98538142-9c6aac80-228a-11eb-84f0-0565cc2f94e0.png)

**Client details:**
 - OS: Windows 10, Debian Buster
 - Browser: Chrome, Chromium, Firefox

No errors on JS console

NC 19.0.4 / Deck 1.1.2

**Comment by juliushaertl** [comment]
For fixing, we should set a `clear-view-delay="0"` on the modal component.

**Comment by wrox** [comment]
Hi! Can I work on this issue?

**Comment by wrox** [comment]
@juliushaertl Do you have permission to approve the PR?
