### ISSUE TITLE
Twice built js

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/deck#2528]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Just recognized, that deck builts it's main-entrypoint twice. Once from webpack-vue-config, once from it's own wepback-config.

**To Reproduce**
- Build the app. ;)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47433654/98996620-76b40080-2533-11eb-80de-e0bcc22bd131.png)

**Comment by juliushaertl** [comment]
Oh, nice catch :+1:
