### ISSUE TITLE
Attach bookmarks to cards

### ISSUE THREAD

**Issue by sunjam** [nextcloud/deck#2529]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to attach url's (bookmarks) to cards.

**Describe the solution you'd like**
File Attachments and descriptions are available for cards, but I'd really appreciate being able to attach [Bookmarks](https://github.com/nextcloud/bookmarks) as well.  [Here is API documentation](https://nextcloud-bookmarks.readthedocs.io/en/latest/)

**Describe alternatives you've considered**
Copy-paste or write the urls into the description field, but I already have thousands of bookmarks I could potentially attach directly from the bookmarks app.  Also, it'd be useful to attach bookmarks to cards while keeping the description field free for other information, especially when sharing cards with other users.
- Bookmarks can also include description fields and tags.

Thanks for considering!

**Comment by stefan-niedermann** [comment]
Maybe it would be better to implement support for Projects into Bookmark?
This way it is not only possible to link bookmarks to Deck cards, but also Deck boards, Files, Talk rooms and each other app which supports Projects 🤷‍♂️ .

**Comment by juliushaertl** [comment]
Closing as implementation happened in https://github.com/nextcloud/bookmarks/issues/1492
