### ISSUE TITLE
Consistent saving and save feedback of contents of description field

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#253]
### Steps to reproduce
1. Write a whole bunch of text into the description of a card
2. Look for a save button, or existing save feedback
3. Be very hesitant about what happens, copy the text of the textarea just to be safe

### Expected behaviour
There should be permanent saving feedback. Good comparison is like how we do it in the Text editor app: https://github.com/nextcloud/files_texteditor – it saves every time you don’t type for 500ms (I think). While you edit it shows an asterisk next to the title (we could improve that, any ideas?) and it then shows a »Saving …« and then »Saved!« feedback.

### Actual behaviour
You have no idea about if your data is saved and if not, how you could do it.

What do you think @nextcloud/deck? :)

**Comment by juliushaertl** [comment]
Makes sense. It should be clear that the work that users do is saved.
