### ISSUE TITLE
hide/archive the list with all its cards

### ISSUE THREAD

**Issue by Jeanoo** [nextcloud/deck#2530]
**Is your feature request related to a problem? Please describe.**
Let me tell you about my situation:
In the tableaux, I have students.
In each list, I have a specific exercise to do.
On the cards, the corrections and the objectives to be achieved each week.
When the objectives of the list are reached, it would be better to hide (archive) the list with all its cards instead of deleting it. This way I can have a better visibility and the student can review the old material. 

Je vous décris ma situation :
Dans les tableaux, j'ai des élèves.
Dans chaque liste, j'ai un exercice à faire spécifique.
Sur les cartes, les corrections et les objectifs à atteindre chaque semaine.
Lorsque les objectifs de la liste sont atteints, il serait préférable de cacher (archiver) la liste avec toutes ses cartes au lieu de la supprimer. De cette manière, je peux avoir une meilleure visibilité et l’élève peut revoir l'ancienne matière. 

**Describe the solution you'd like**
I would like to be able to archive lists and cards at the same time because I have so many lists.
J'aimerais pouvoir archiver les listes et les cartes au même temps parce que j'ai énormément des listes.
**Describe alternatives you've considered**
I don't know who to tell you

**Additional context**

**Comment by stefan-niedermann** [comment]
While the Android App will follow the behavior of the Server App, i *personally* disagree and downvoted this proposal for the reasons described [in the issue of the Android Apps tracker](https://github.com/stefan-niedermann/nextcloud-deck/issues/725#issuecomment-726329155):

> Because lists are meant to be a way to describe a kind of workflow for cards, like ToDo → Work in Progress → Done.
The cards should move from the left to the right within their lifecycle. Since the lists (= "states") are static in this scenario, they don't disappear when archiving all the cards of a list. The lists are the same for future cards which will be dragged there.

**Comment by Jeanoo** [comment]
Without you thinking that I want to make an application in my image, I give you my opinion.
For me a good application is one that adapts to the projects of each user. But as you describe the options of this one, it seems to be very limited and adapted to only one type of project.

Sans que vous pensiez que je souhaite faire une application à mon image, je vous donne mon opinion.
Pour moi une bonne application est celle qui s’adapte aux projets de chaque utilisateur. Mais comme vous décrivez les options de celle-ci, elle semble être très limitée et adaptée à un seul type de projet.

**Comment by Jeanoo** [comment]
I have just noticed that it is also possible to archive the tableaux.
So I don't understand why this persistence in not wanting to archive the lists.

Je viens de constater que c'est aussi possible d'archiver les tableaux.
Alors je ne comprend pas pourquoi cette persistance a ne pas vouloir archiver les listes.

**Comment by olerichter** [comment]
I would have a slightly different use case for archiving lists:

we currently use deck for running our sprints (scrum), so our cards move from

backlog -> todo -> in progress -> done - sprint number

After a while it would be nice to archive the done lists for passed sprints, to clean up the view but be able to recall the lists with the attached cards in the archive view

the alternative obviously would be #1721 but we would like to retain the connection in which sprint a task was completed for a later high level process review to enable us to improve the product cycle (we do hardware - not software).

**Comment by juliushaertl** [comment]
I agree with @stefan-niedermann here that lists are or rather should be decoupled from the archiving, so this is nothing we have on the roadmap currently.
