### ISSUE TITLE
Modal tabs "attachments" and "timeline" can not be opened

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#2534]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Clicks on Attachments and Timeline have no effect

**To Reproduce**
1. open card details in large view
2. Click on Attachments or Timeline
3. See error: nothing happen (only red marker)

**Expected behavior**
Any effect, when click on Attachments or Timeline

**Screenshots**
![d20](https://user-images.githubusercontent.com/34692335/99068862-925bed00-25ad-11eb-924a-90aceaa43a51.png)

**Versions**
Deck 1.2.0-beta1
Nextcloud 20.0.0

**Comment by juliushaertl** [comment]
Hm it seems there is something wrong with the tabs indeed there, looks like the just all show below each other, I'll have a look.
