### ISSUE TITLE
3 dots menu shows "Archive board" and "Unarchive board"

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#2537]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
boards 3 dots menu shows "Archive board" and "Unarchive board"

**To Reproduce**
1. Click on '...' in left board view
2. See "Archive board" and "Unarchive board"

**Expected behavior**
In previous versions of deck either "Archive board" or "Unarchive board" were visible

**Screenshots**
![d30](https://user-images.githubusercontent.com/34692335/99084917-d78d1880-25c7-11eb-9fc9-f3fecc8c569e.png)

**Versions**
Deck 1.2.0-beta1
Nextcloud 20.0.0

**Comment by cloud2018** [comment]
similar to missing "Unarchive cards"
![d30](https://user-images.githubusercontent.com/34692335/99085981-2c7d5e80-25c9-11eb-9ce6-40f6c28de2d1.png)

**Comment by juliushaertl** [comment]
Similar to https://github.com/nextcloud/deck/issues/2527
