### ISSUE TITLE
Papercut: Wording "modal card view", "bigger view"

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#2542]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
different wording for same card view. Please use same wording

**Screenshots**
![d40](https://user-images.githubusercontent.com/34692335/99093134-6141e380-25d2-11eb-99d9-ff9f019aad10.png)

![d41](https://user-images.githubusercontent.com/34692335/99093460-c85f9800-25d2-11eb-8417-e91baf724363.png)

**Versions**
Deck 1.2.0-beta1
Nextcloud 20.0.0

**Comment by stefan-niedermann** [comment]
@cloud2018 do you want to open a Pull Request for this papercut? That would be awesome 🚀

**Comment by cloud2018** [comment]
@stefan-niedermann sorry, i don't have a local development environment and i am not familiar with Git.
