### ISSUE TITLE
Undefined offset: 1 at /var/www/html/custom_apps/deck/lib/Service/ConfigService.php#94 in 1.2.0-beta1

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/deck#2544]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Error message in logs. Happens when I click the checkbox to show the board in the calendar from the upcoming cards view. Probably because there is no board selected at that moment

**To Reproduce**
1. Go to Deck / Upcoming cards
2. Click on settings
3. (de)select checkbox to show the board in calendar

**Expected behavior**
Checkbox not available in upcoming cards view

<details>
<summary>Server details</summary>

**Nextcloud version:** 20.0.1

**Where did you install Nextcloud from:** Docker

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[PHP] Error: Error: Undefined offset: 1 at /var/www/html/custom_apps/deck/lib/Service/ConfigService.php#94 at <<closure>>

0. /var/www/html/custom_apps/deck/lib/Service/ConfigService.php line 94
   OC\Log\ErrorHandler::onError(8, "Undefined offset: 1", "/var/www/html/c ... p", 94, {key: "calendar" ... "})
1. /var/www/html/custom_apps/deck/lib/Controller/ConfigController.php line 58
   OCA\Deck\Service\ConfigService->set("calendar", false)
2. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Deck\Controller\ConfigController->setValue("calendar", false)
3. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Deck\Controller\ConfigController {}, "setValue")
4. /var/www/html/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Deck\Controller\ConfigController {}, "setValue")
5. /var/www/html/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Deck\\Controller\\ConfigController", "setValue", OC\AppFramework\ ... {}, {action: null,ke ... "})
6. /var/www/html/ocs/v1.php line 88
   OC\Route\Router->match("/ocsapp/apps/de ... r")

POST /ocs/v1.php/apps/deck/api/v1.0/config/calendar
```

</details>

**Comment by stefan-niedermann** [comment]
Maybe related to https://github.com/nextcloud/deck/issues/2522

**Comment by juliushaertl** [comment]
Oh, totally overlooked this in the other fix. Follow up at https://github.com/nextcloud/deck/pull/2562

**Comment by Chartman123** [comment]
No more errors in the logs 👍
