### ISSUE TITLE
Unable to move card on mobile device

### ISSUE THREAD

**Issue by 9662** [nextcloud/deck#255]
### Steps to reproduce
1. Open a deck in a mobile device (navigate to `/apps/deck/#!/board/:id/`)
2. Try to move a card, either across stacks or to a different place in the same stack. Do this by long-pressing on the card, which seems to be a common language for “drag & drop” on touch devices.

### Expected behaviour
The card should be dragged into its new position.

### Actual behaviour
Either nothing occurs or text is selected, depending on where one taps.

### Server configuration
Deck 0.2.1, NC11, tried with Firefox on an Android device.

**Comment by juliushaertl** [comment]
Also related to #156

**Comment by juliushaertl** [comment]
Works fine with #352
