### ISSUE TITLE
Papercut: Wording Title -> Board name

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#2553]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
1. Please use "Board name" instead of "Title" 

**Screenshots**

![a1](https://user-images.githubusercontent.com/34692335/99145864-930a8700-2672-11eb-83b2-b27d0a7d1231.png)

**Versions**
Deck 1.2.0-beta1
Nextcloud 20.0.0

**Comment by stefan-niedermann** [comment]
@cloud2018 could you please split the issues up into two separate issues?

1. is easy to fix and clear what do do
2. is a design issue which might also affect other Nextcloud apps and it is unclear how to resolve this.

Thank you!

**Comment by cloud2018** [comment]
@stefan-niedermann 
See #2557
