### ISSUE TITLE
Move card shows deleted boards

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#2554]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Move card shows deleted boards

**To Reproduce**
1. Open move card
2. choose a board
4. See inconsistency: Deleted boards are listed in the selection for target, but not in the left sidebar 

**Expected behavior**
Deleted boards are not listed in the selection for target 

**Screenshots**
![d22](https://user-images.githubusercontent.com/34692335/99143004-73676480-265a-11eb-9cb6-cd2a404ccae8.png)

Note:
Please add feature: order the boards in the selection by name

Versions
Deck 1.2.0-beta1
Nextcloud 20.0.0

**Comment by stefan-niedermann** [comment]
Just for clarity: Boards are not physically deleted immediately, but as soon as the next cronjob has been executed. (This behavior is by design to enable "undo").

Can you please verify, that there only appear deleted boards which have been deleted *recently* and the deleted boards do no longer appear after the next cron job has been executed (for example after 30 minutes or so, depends on your configuration).

I guess there is missing some kind of

```sql
WHERE status != 'DELETED'
```

or so in the SQL query to fetch the proposals.

**Comment by stefan-niedermann** [comment]
Additional note: Maybe moving a card to a board which has been deleted should throw an error (some kind of HTTP 400)? This might prevent data loss when one moves a card to a board which has been deleted, but it might also expected, that the moved card is just gone with the board then...? 🤔 cc @juliushaertl for the desored behavior.

**Comment by cloud2018** [comment]
@stefan-niedermann 
"Can you please verify, that there only appear deleted boards which have been deleted recently and the deleted boards do no longer appear after the next cron job ..." 
sorry, I would have tested that before,  but there are problems with my cron job :-(
In the sidebar the list don't show recently deleted boards. If the dialog shows the same list, there is no need to throw an error

**Comment by stefan-niedermann** [comment]
> If the dialog shows the same list, there is no need to throw an error

The [additional notes](https://github.com/nextcloud/deck/issues/2554#issuecomment-727190011) does only affect sync clients like the [Android app](https://github.com/stefan-niedermann/nextcloud-deck) and are not directly related to the issue you have originally reported 🙂

**Comment by fecub** [comment]
my solution for this problem was to run this command:

```bash
docker exec -u www-data Nextcloud php -f /var/www/html/cron.php
```

After that, all things which was "marked for delete" were deleted :+1:
