### ISSUE TITLE
Description caret black in dark mode

### ISSUE THREAD

**Issue by JonFStr** [nextcloud/deck#2556]
### Steps to reproduce
1. Switch to dark mode
2. Open any card in detail view
3. Click on "Edit description" (The pen)

### Expected behaviour
The caret has a light color

### Actual behaviour
The caret is black and hardly visisble

## Server configuration detail

**Nextcloud version:** 20.0.1 - 20.0.1.1
**Deck version:** 1.1.2

## Possible fix
Applying the fix from codemirror/CodeMirror#3460 on the fly in the browsers's style editor fixed it.

**Comment by radoeka** [comment]
It would be very good when this will be solved.

It is very, very hard to read the cursor.  The cursor is present in the screenshot, arrow 1 is pointing to it.

The other one is the icon pointed to by arrow 2.

![image](https://user-images.githubusercontent.com/2937666/99905839-be751d80-2cd3-11eb-9025-150b510cdbb4.png)

**Comment by JonFStr** [comment]
It should be really quick to implement, if you know in which CSS file it belongs (at least for the caret)
Unfortunately, I currently don't have time to look into it

**Comment by juliushaertl** [comment]
Pull requests are welcome:

https://github.com/nextcloud/deck/blob/master/src/components/card/Description.vue#L286

The color should then use our css variable: `var(--color-main-text)`

**Comment by JonFStr** [comment]
When I'm done with that, should I test it?
I know it works on the fly but I haven't worked with Vue before so I don't know how to upload it to my server to test the change
