### ISSUE TITLE
Don't open input field when clicking on title in Deck

### ISSUE THREAD

**Issue by ad-si** [nextcloud/deck#2563]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When I click on the title of card it changes to an input box for editing the title. This, however, is different to any other kanban board I know of. For every other kanban board clicking on the title opens the card either in a sidebar or a pop up.

Also: The area of the title is a large share of the area of the card itself and since I much more often want to open the card then edit it, it seems bad to waste so much area for something that's done very seldomly.

**Describe the solution you'd like**
So for sake of consistency and a better usability it would be awesome if Deck behaved like other kanban boards.

For editing the title I'd either put a pencil symbol next to it, or just remove the function entirely from the small card view and only allow editing in the popup or the sidebar.

**Comment by alexanderdd** [comment]
I actually edit card titles a lot, and appreciate that you can do it fast (no need to open sidebar).

**Comment by ad-si** [comment]
> I actually edit card titles a lot, and appreciate that you can do it fast (no need to open sidebar).

Yeah, not having to open the sidebar for changing the title is probably cool, but this could also be achieved with a pencil / edit icon next to it.

**Comment by juliushaertl** [comment]
I personally prefer the inline editing here as well, and even without that we would not reduce the space much more in the card item view itself.

cc @jancborchardt @Clementine46 for feedback regarding the UX here

**Comment by Clementine46** [comment]
I agree that this editing function isn't the most intuitive but now some users are used to it. I think a good compromise could be to have a pencil icon appear on the top right corner of the card when hovering on the title (or the general upper part of where the title is). Basically like in Trello.
