### ISSUE TITLE
Inserted Images render in Editor

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2567]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

When inserting an image in the description, it should only be visible by the markdown text.
Since 1.2.0, it also shows as image in the editor and the editor freaks out if you want to select the markdown link.
You can not delete the text, because the cursor jumps all over the place, selecting text with the mouse is impossible.
Inserting an image (or having a card with an inserted image) makes it impossible to edit the card details below the image, because the image seems to mess up the lines. When clicking below the image into text, the cursor position does not coincide with the position where you start editing.

Furthermore, when I want to click on the Arrow to insert the attachment, the info dialog pops up and renders over the button. The mouse pointer changes from pointer to finger and back every split second. I have furiously click and try to hit the button in order to insert the image. (that might be worth another bug report though)

**To Reproduce**
1. Create card
2. Upload image
3. edit description
4. insert image

**Expected behavior**

The editor mode should only show the markdown link.

**Screenshots**
![image](https://user-images.githubusercontent.com/431045/99351885-e6165100-28a1-11eb-9ed0-6050bd202792.png)

**Client details:**
 - OS: Win10
 - Browser: Firefox 
 - Version: 82.0.3
 - Device: Desktop

Also on
- OS: CentOS
- Browser: FF

NC 19.0.4 / Deck 1.2.0

**Comment by stefan-niedermann** [comment]
This is similar to https://github.com/nextcloud/deck/issues/533

@reox can you please check whether your issue is covered by the linked issue?

**Comment by reox** [comment]
@stefan-niedermann  No, these are different. Since I upgraded to 1.2.0, the editor window shows the image instead of just showing the markdown text. 
This messes the editor up and makes editing at least very hard and painful.

In #533 the issue is different. At least on linux, I can paste images from the clipboard (for example a screenshot) into the editor and it will show a lot of unicode characters. However it looks like that this bug is fixed and I'm not able to paste images anymore - still the feature to paste images like here on github is still open.

**Comment by BKapelari** [comment]
Addition: In my case, the content of the editor doesn't save. If I leave the modal and reopen it, the image is gone. The only way to get it work was: Copy all (cmd + a), close the modal, reopen it an paste the content. 

Deck Version: 1.2.1
Nextcloud Version: 19.0.4
Browser: FireFox 83.0

**Comment by reox** [comment]
@BKapelari I wrote in #2484 that there is a workaround for that:
If an attachment is inserted and the editor is left, it does not save. However, if you edit the description after adding the attachment it saves it (at least so far...) But there are also other reports that the description field is broken right now :/
