### ISSUE TITLE
Card description is overwritten

### ISSUE THREAD

**Issue by LuCu11** [nextcloud/deck#2568]
Hi,
today I have installed the latest version 1.2 Thereby I noticed an error:
If the card is changed during editing, the description is copied to the other card.The description of the other map will be overwritten.
Is this only true for me, can anyone confirm the error?
Thanks!
User

**Comment by tschuppi73** [comment]
Hi,

I have the same error. Sometimes the whole Description of a card disappears.

**Comment by reox** [comment]
This one is also similar to #2484 but it looks like it got worse in 1.2.0...
It appears that the edited description is not saved under some circumstances.

**Comment by probastaller** [comment]
Similar here.
When opening a card in floating view. If the card has checkboxes in the description in view mode, and click to check any of those boxes, the whole description goes blank and... lost it.

**Comment by jpbraun** [comment]
I can confirm the error. After changing the description of one card, many cards of the same column suddenly had the same description. The original description has been lost. We lost many very import information!

**Comment by numerfolt** [comment]
Happens to me in normal view too.
How to reproduce (at least how it "worked" for me): Edit a card and select another one. (Doesnt matter whether you leave the edit mode or not)
Expected behaviour: The deselected card gets saved in the background and you can interact with the other one normally.
Actual behaviour: The other card saves the edits of the deselected card, overwriting the other content.

**Comment by probastaller** [comment]
emm... this is now closed, but what I exposed in my last entry is still happening...
Should I open a new issue? or maybe reopen this one?

**Comment by stefan-niedermann** [comment]
@probastaller i guess only when you click a checkbox?

See https://github.com/nextcloud/deck/issues/2580, https://github.com/nextcloud/deck/issues/2591, #2595 #2603, and #2592 for the checkbox issue.

[A fix](https://github.com/nextcloud/deck/pull/2584) is already in the pipeline.

You should be able to [restore the description content from the timeline tab](https://github.com/nextcloud/deck/issues/2580#issuecomment-730319105).

**Comment by juliushaertl** [comment]
Just pushed out 1.2.2 with the fix for this.
