### ISSUE TITLE
User delete throwing error in Deck 1.2.0

### ISSUE THREAD

**Issue by ksteinb** [nextcloud/deck#2569]
Deleting Users throws an error:

An unhandled exception has been thrown:
Error: Call to undefined method OCA\Deck\Db\AssignmentMapper::findByUserId() in /var/www/html/nextcloud/apps/deck/lib/AppInfo/ApplicationLegacy.php:117
Stack trace:
#0 [internal function]: OCA\Deck\AppInfo\ApplicationLegacy::OCA\Deck\AppInfo\{closure}(Object(OC\User\User))
#1 /var/www/html/nextcloud/lib/private/Hooks/EmitterTrait.php(101): call_user_func_array(Object(Closure), Array)
#2 /var/www/html/nextcloud/lib/private/Hooks/PublicEmitter.php(40): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'postDelete', Array)
#3 /var/www/html/nextcloud/lib/private/User/User.php(257): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'postDelete', Array)
#4 /var/www/html/nextcloud/core/Command/User/Delete.php(65): OC\User\User->delete()
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\User\Delete->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\User\Delete), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#12 {main}[

Reason is probably that the function call findByUID was not changed to findByParticipant in these files:
lib/AppInfo/Application20.php
lib/AppInfo/ApplicationLegacy.php

**Comment by juliushaertl** [comment]
Thanks for reporting and providing a fix :+1: 

Fixed with #2570 #2571
