### ISSUE TITLE
Card can not be dragged to empty stack

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#257]
### Steps to reproduce
1. Have a stack »To do«, »Doing« and »Done«
2. Add a bunch of cards to your »To do« stack
3. Start a task and try moving it to »Doing«

### Expected behaviour
It works, you can drag onto the stack column even though it’s empty.

### Actual behaviour
It does not work. You need to have at least one card in a stack so it becomes a drag target.

Marking this as high since this is pretty crucial. ;) @nextcloud/deck

**Comment by pixelipo** [comment]
Definitely a duplicate. There's a PR to be merged as well

**Comment by 9662** [comment]
#235 to be precise. #238 for the merge request I guess.

**Comment by jancborchardt** [comment]
Sorry! :) Closing in favor of the ones @9662 mentioned.
