### ISSUE TITLE
Modifying description of one card corrupts subsequently clicked cards

### ISSUE THREAD

**Issue by joutwate** [nextcloud/deck#2577]
Nextcloud version: 19.0.4
Decks version: 1.2.0
Browsers tested: Chrome, Edge
Not reproducible on try.nextcloud.com (different version of Nextcloud there?)

**Steps to reproduce:**
1. Create two cards in a deck (Test Card 1, Test Card 2)
2. Enter text into the description field of Test Card 2.
3. Wait for autosave to complete.
4. Click on Test Card 1.
5. See that text from Test Card 2 has been copied to Test Card 1's description field and is saved.

**Expected Behavior:**
Description text from the clicked card is loaded rather than replaced with previous card description text.

**Screen shots:**
1. See that Test Card 1 has no description
<img width="729" alt="Screenshot 2020-11-18 025504" src="https://user-images.githubusercontent.com/5501471/99522273-482a9100-294a-11eb-8028-6cb7316b926e.png">
2. Step where a description is added to Test Card 2
<img width="729" alt="Screenshot 2020-11-18 025602" src="https://user-images.githubusercontent.com/5501471/99522264-4660cd80-294a-11eb-8199-0e422e73935a.png">
3. See that when Test Card 1 is clicked on, the description is updated with Test Card 2's content
<img width="729" alt="Screenshot 2020-11-18 025624" src="https://user-images.githubusercontent.com/5501471/99522274-48c32780-294a-11eb-845c-1c5fc84779f1.png">

**Comment by putt1ck** [comment]
Fixed in 1.2.1 with https://github.com/nextcloud/deck/pull/2573

**Comment by joutwate** [comment]
Thank you so much for such a quick review and fix @putt1ck

**Comment by lightnin** [comment]
Indeed - thanks for the quick response. Happy to know the fix is in the pipeline.
