### ISSUE TITLE
Usage of tasklist in description deletes entire description

### ISSUE THREAD

**Issue by markuman** [nextcloud/deck#2580]
**Describe the bug**
When check off tasks of a markdown task list, the entire description will be deleted.

**To Reproduce**
1. create a task list

```
- [ ] a
- [ ] b
- [ ] c
```

2. check off one task after each other. 
3. you won't reach task "c", because after check off "b", everything is deleted.

It's also deleted in the database.

**Expected behavior**

description won't be deleted and the tasks list is just checked off.

**Screenshots**

![deckbug2](https://user-images.githubusercontent.com/3920157/99552084-e8210280-29bc-11eb-98cb-64f5b0b36a6d.gif)

**Client details:**
 - OS: linux
 - Browser firefox
 - Version 82.0.2
 - Device: desktop
 - Deck 1.2.1
 - Nextcloud 20.0.1.1
 - PHP 7.4.11

**Comment by LuCu11** [comment]
same here, is there an option to get the description back?

**Comment by markuman** [comment]
Afaik no. It's also deleted in the database.

**Comment by markuman** [comment]
The put request sets `description: ""`. So it's related to the frontend/vuejs.

**Comment by markuman** [comment]
https://github.com/nextcloud/deck/blob/master/src/components/card/Description.vue#L178

This is the function where the accident happen...

I'm a lousy js/vuejs hacker :D

**Comment by markuman** [comment]
...but I like to hotfix it

**Comment by LuCu11** [comment]
luckily the description was from an old deck and I could use a DB backup

**Comment by markuman** [comment]
In v1.1.2 it was `this.copiedCard.description.replace` ...now it replaces the content in place.

**Comment by markuman** [comment]
When you're on mariadb >= 10.3, a workaround to prevent dataloss is, simple add system versioning to that table.


```sql
alter table oc_deck_cards add system versioning;
```

https://mariadb.com/kb/en/system-versioned-tables/

You can than query the history and recover lost data

```sql
select title, description, row_start, row_end from oc_deck_cards FOR SYSTEM_TIME BETWEEN (NOW() - INTERVAL 1 YEAR) AND NOW() where title like 'YOUR CARD TITLE%';
```

But that's not a permanent solution. Hopefully @juliushaertl find a fix for that fast.

**Comment by markuman** [comment]
` this.description` is already empty when the function is triggered as far as I can see.

![Bildschirmfoto vom 2020-11-18 21-52-30](https://user-images.githubusercontent.com/3920157/99587078-de14f900-29e8-11eb-84b4-72a94856453c.png)

**Comment by markuman** [comment]
WOHOOOO I GOT IT

https://github.com/nextcloud/deck/blob/master/src/components/card/Description.vue#L183

must be ` this.card.description.replace`

**Comment by juliushaertl** [comment]
What a timing :grin: Thanks for looking into that already. I've pushed my fix (basically the same as yours) but included an additional commit to avoid issues in the modal in #2584 

Reviews and testing are very welcome. There is also an app build available in the pull request artifacts that can be used for testing this without requiring to build the app yourself:

https://github.com/nextcloud/deck/pull/2584/checks?check_run_id=1420738455
https://github.com/nextcloud/deck/suites/1524832079/artifacts/26934287

**Comment by markuman** [comment]
@juliushaertl works for me.  
Thx!

**Comment by fridlmue** [comment]
> same here, is there an option to get the description back?

For me it was always possible to recover the description from the history of the card. Hope this will work for you, too.
I hope the hotfix finds a fast way to a release :wink:

**Comment by markuman** [comment]
Oh well. Yeah, there is a timeline.

![Screenshot_2020-11-19 Deck - Nextcloud(1)](https://user-images.githubusercontent.com/3920157/99661963-e874d880-2a64-11eb-9de3-a47f5a6246c3.png)
