### ISSUE TITLE
Stack header  in Mac Safari not readable because of grey shadow above

### ISSUE THREAD

**Issue by mavoIn** [nextcloud/deck#2581]
Since deck version 1.2.0 (nextcloud 19.x) there is an grey css shadow above the stack_header only on safari 14.0.1. In other browser the list title is shown correctly. The "smooth-dnd-container vertical" seems to be incorrectly positioned.

<img width="649" alt="Bildschirmfoto 2020-11-18 um 18 50 24" src="https://user-images.githubusercontent.com/16373368/99567875-fa0ba100-29ce-11eb-8178-bd179ae7986e.png">

Thx for bugfixing it. Currently not usable in Safari

**Comment by juliushaertl** [comment]
@jancborchardt Do you remember this from the text app where the gradient from white to transparent also caused this? Do you remember how we fixed it there?

**Comment by Rello** [comment]
![Bildschirmfoto 2020-11-27 um 13 43 41](https://user-images.githubusercontent.com/13385119/100450814-92ccab80-30b6-11eb-9a30-9f54428a834c.png)

Any update?
this bug is really a pain

**Comment by stefan-niedermann** [comment]
@Rello Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue.
