### ISSUE TITLE
[Enhancement] Link Polls into project

### ISSUE THREAD

**Issue by meaz** [nextcloud/deck#2600]
It would be great to be able to link a [NC polls](https://apps.nextcloud.com/apps/polls) into a project in deck. For example, when working on a card that needs a decision.

**Comment by stefan-niedermann** [comment]
I agree that this would he awesome. However this is nothing which can be implemented in Deck. The support has to be integrated into the Polls App itself. There is already an issue in the Polls repository: https://github.com/nextcloud/polls/issues/950

You should upvote and subscribe to it 🙂
