### ISSUE TITLE
list template

### ISSUE THREAD

**Issue by sechanbask** [nextcloud/deck#2604]
Hello,

Deck is very usefull !

Is it possible to developp a template for "list" ? I always need 

- todo
- in progress
- done
- sent

Is it possible de add time to "card" and summarize it by board and by user ?

**Comment by putt1ck** [comment]
This sounds like 2 RFEs, and the first part should be covered by https://github.com/nextcloud/deck/issues/119. The second part is probably covered by https://github.com/nextcloud/deck/issues/2299
