### ISSUE TITLE
Add active board to the move card dialog

### ISSUE THREAD

**Issue by PVTGoesen** [nextcloud/deck#2607]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the solution you'd like**
Please add the active board to the move card dialog, to move the card in the active board. In my opinion in bigger boards it is easier to move a card this way.

This should be possible by editing _src/components/cards/CardMenu.vue_  row 128-132
Current:
```js
		boards() {
			return this.$store.getters.boards.filter(board => {
				return board.id !== this.currentBoard.id
			})
		},
```
Solution:
```js
		boards() {
			return this.$store.getters.boards.filter(board => {
				return board.id
			})
		},
```

**Comment by juliushaertl** [comment]
Makes sense. The computed property can then even be simplified more to not filter at all.
