### ISSUE TITLE
how to read out deck version as a user?

### ISSUE THREAD

**Issue by WAKIGA98** [nextcloud/deck#2608]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Neither deck settings nor REST API offer a "getVersion" function to add to an issue.
Note: I'm not the administrator, just a user with nextcloud/deck

**To Reproduce**
1. Setting include no version information
2. [REST API ](https://deck.readthedocs.io/en/latest/API/) has no version request

**Expected behavior**
getting version information to add to an issue

**Screenshots**
n/a

**Client details:**
 - OS: Windows
 - Browser Mozilla Firefox
 - Version 83.0 (32-Bit)
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by stefan-niedermann** [comment]
try the `capabilities` endpoint from nextcloud itself

**Comment by WAKIGA98** [comment]
Thanks
curl -u username:password -X GET 'https://cloud.example.com/ocs/v1.php/cloud/capabilities' -H "OCS-APIRequest: true"
displays version information
nextcloud 19.0.4
deck 1.1.2

**Comment by stefan-niedermann** [comment]
You can have a look of the implementation of the Deck Android app:

- API endpoint: https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/api/NextcloudServerAPI.java#L29
- Parsing: https://github.com/stefan-niedermann/nextcloud-deck/blob/2fabfcc0c295917b041ad1f881fde4ded28ffe3d/app/src/main/java/it/niedermann/nextcloud/deck/api/JsonToEntityParser.java#L539

The endpoint returns installed apps with their versions. This is AFAIK the (only) "official" way to get the version of the currently installed deck app.
