### ISSUE TITLE
"Add a card description" in sidebar has to be clicked twice

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#261]
In addition to the placeholder of the field "Enter your description here" there is text in it before clicking "Add a card description".

You need to click the field to make the text vanish, but the field doesnt get focused. So you need to click it again. The first text should not be there.

(Also, the better wording is "Add a detailed description …" - things like "Enter here" or "Click here" are always a bit strange.)

**Comment by juliushaertl** [comment]
I cannot reproduce here on chromium, but I see that the two different descriptions need to change. Add a detailed description makes sense to me. It sould also have the same style as the placeholder text.

**Comment by artemanufrij** [comment]
I can't reproduce it. It works fine on my system. Tested on Chromium, Chrome, Epiphany...
