### ISSUE TITLE
Description edit field is smaller than window

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2617]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

Since the update to 1.2.2, the description text fields in both sidebar and modal view are not full width.
It is only the edit field, as the rendered description is correct.

**To Reproduce**
1. Edit a card
2. Edit description

**Expected behavior**

Field should be 100% width.

(The new border around the textfield is good though, please do not change that back ;))

Does the class `CodeMirror` just require a `width:100%`?

**Screenshots**
![image](https://user-images.githubusercontent.com/431045/100189723-218dcc80-2eed-11eb-99f8-359bd0d066cc.png)

![image](https://user-images.githubusercontent.com/431045/100189757-35393300-2eed-11eb-9b7f-92689842d7dc.png)

**Client details:**
 - OS: W10
 - Browser: Chrome, Firefox
 - Version:  87.0.4280.66, 83.0
 - Device: Desktop

NC 19.0.5 / Deck 1.2.2

**Comment by reox** [comment]
It looks like this got fixed with NC 20.0.4? At least since I upgraded to 20.x, the sizes are equal again.
Please, can someone confirm that? Then this issue can be closed.

**Comment by juliushaertl** [comment]
I could reproduce a similar issue when zooming the webpack today see https://github.com/nextcloud/deck/pull/2983 for a possible fix
