### ISSUE TITLE
Insert Attachment button is hard to click

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2618]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

Since I think 1.2.0, the insert attachment button is very hard to use. If you try to click it, the tooltip shows up.
So you have to click the button like crazy to activate it.
Sometimes I can click it within a second, but sometimes it is almost not possible to hit it.
Also the button "flickers" when hovering with the mouse.

**To Reproduce**
1. Upload attachment
2. Edit Description
3. Select Attachment
4. try to click button

**Expected behavior**
Button should be easily clickable, just as before.

I think the tooltip should be over the button (just like the other buttons in the description window) and not left from it.
The arrow of the tooltop points up in this case, but It should point down and the box should appear over it.
Why the button freaks out when hovering, I have no idea...

**Screenshots**
I hope this illustrates the problem:
![insert_attachment2](https://user-images.githubusercontent.com/431045/100190752-366b5f80-2eef-11eb-96a5-f23c31841a43.gif)

**Client details:**
 - OS: W10, Centos 7.8
 - Browser: Chrome, Firefox
 - Version 87, 83
 - Device: Desktop

NC 19.0.5 / Deck 1.2.2

**Comment by juliushaertl** [comment]
Yes, something seems odd there with the click target.

**Comment by juliushaertl** [comment]
I cannot reproduce this anymore when testing with #2638

**Comment by reox** [comment]
@juliushaertl is the change already in v1.2.3? I just tested in there and I get the same behavior.

**Comment by juliushaertl** [comment]
Ok, now i can indeed reproduce it with Firefox, strangely it didn't happen on master for me. I'm not entirely sure why that happens yet, the button seems to span the full size but somehow the tooltip is toggled on and off when hovering the lower third.

**Comment by reox** [comment]
I just found out, that this only affects the last entry in the list. If you have several attachments, it works fine for all but the last.

**Comment by fm-sys** [comment]
I have found out something new: It is only happening when the browser is in full-screen. And it is a cross browser bug, as it happens at least for Firefox and Chromium Edge...

**Comment by reox** [comment]
> I have found out something new: It is only happening when the browser is in full-screen.

for me it happens all the time. But maybe it depends on the screen size? I have a 2540x1440px screen though

**Comment by fm-sys** [comment]
Can you test, what happens if you resize the window to a _very_ small size? Probably the problem occurs above a certain window size...

BTW, Has anyone figured out a workaround on how to temporarily fix this problem using custom CSS?

**Comment by reox** [comment]
> Can you test, what happens if you resize the window to a very small size? Probably the problem occurs above a certain window size...

indeed! if I resize the window it does not happen. But the window has to be really small though.

I would guess it is a similar issue as in #2704
There is simply not enough space in the div and the tooltip then renders over the mouse cursor.
If the window is resized there is probably another css rule kicking in... dunno 😅

**Comment by reox** [comment]
With the upgrade to NC 21.0.1 / Deck 1.3.2 the behaviour changed a bit: I can no longer see the tooltip on hovering, but the button is still freaking out and flickers like crazy..
But at least I can now click the button on the first try.

**Comment by juliushaertl** [comment]
Did some further research and seems that the tooltip might pick the wrong boundary due to the scroll container we have in place around the attachment list: https://github.com/Akryum/v-tooltip/issues/721

**Comment by juliushaertl** [comment]
The scroll overflow seems to cause the change of the boundary element: 

![image](https://user-images.githubusercontent.com/3404133/146009505-d33e0eb9-1df4-4b80-a6f5-4a3b9ac4483a.png)
