### ISSUE TITLE
Clicking Checkboxes in Bigger View doesn't save checked status 

### ISSUE THREAD

**Issue by lishevita** [nextcloud/deck#2619]
A card with a task list as checkboxes. When we go to check off tasks from the "bigger view", the checks do not save down to the card. Checks are only saved if done in the "sidebar view".

**Comment by lishevita** [comment]
Here is an example of what I mean:

![Screenshot at 2020-11-24 23-59-58](https://user-images.githubusercontent.com/1098365/100198868-4a906c00-2eb1-11eb-81a5-0c14452a6454.png)
![Screenshot at 2020-11-25 00-00-34](https://user-images.githubusercontent.com/1098365/100198875-4d8b5c80-2eb1-11eb-8fd1-88756f4c73fe.png)

**Comment by stefan-niedermann** [comment]
Please update to version `1.2.2` and fill in the issue template the next time - it is not there for fun 😉

**Comment by stefan-niedermann** [comment]
You should be able to [restore the description content from the timeline tab](https://github.com/nextcloud/deck/issues/2580#issuecomment-730319105).
