### ISSUE TITLE
nexct cloud/ deck notifications

### ISSUE THREAD

**Issue by gesal** [nextcloud/deck#2620]
hello,
i am new to this forum and have no it experience. i work part time at a collective and we recently use nextcloud and also some use the app with deck. we couldn´t figure out yet how we activate the notifications, for example if one would write a comment or change a topic or something similar.

maybe someone can help me out. i would appreciate any infi/link/hint :-)

thank you!

kr
gesal

**Comment by juliushaertl** [comment]
GitHub is used for tracking bugs or feature requests. For general questions I would like to ask you to raise your question in the forums instead at https://help.nextcloud.com

Thanks a lot :)

**Comment by gesal** [comment]
thank you so much! someone from the deck app send me the github forum 
link, sorry..i will try there then.

kr
gesal

Am 25.11.2020 13:48 schrieb Julius Härtl:

**Comment by stefan-niedermann** [comment]
Yeah, sorry, that was me 😄 

I wasn't sure whether this has to be treated as a feature request because i think that the mentioned kind of notifications can not yet be configured in that detail level.

But i wasn't sure.

**Comment by juliushaertl** [comment]
I could at least have commented on that I guess :see_no_evil: 

So currently the deck app only sends out notifications itself you get assigned to a card or if a card reaches a due date. For the due date you can tune your notification settings per board now with 1.2.x.

With Nextcloud 20 there is also the possibility to get push notifications for activity entries, which can be managed in the users/admins activity settings.

**Comment by gesal** [comment]
no worries :-) i appreciate the response :-) that helps a lot, since 
searching through google i have found that push isn´t avalaible :-)

thank you and stay safe!

kind regards
gesal

Am 25.11.2020 14:57 schrieb Julius Härtl:
