### ISSUE TITLE
Create a setting that allows cards to be exposed as events rather then as tasks in webdav.

### ISSUE THREAD

**Issue by mstyp** [nextcloud/deck#2629]
**Is your feature request related to a problem? Please describe.**
Most of my colaberators use google or microsoft office software exclusivly. Google calendar and microsoft outlook have functionality that allows them to subscribe to my nextcloud calendar by copy pasting a link I send them, but this does not work with tasks made by deck app (or the regular tasks app for that matter) 

**Describe the solution you'd like**
Create a setting that allows cards to be exposed as *events* rather then as *tasks* in webdav.

**Describe alternatives you've considered**
vdirsyncer, not supported: https://github.com/pimutils/vdirsyncer/issues/853
outlook syncer: the people I colaberate with wont install it. 

**Additional context**
Its imperative that nextcloud be interaperable with google and microsoft. I know those companies suck and dont follow standards, but they are the most popular platforms, and they wont change for us, so nextcloud has to become more interoperable with them. 

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by thw26** [comment]
I created a topic for this very thing on the Forums. Linking here for any discussion that may arise.

https://help.nextcloud.com/t/convert-task-only-calendar-to-full-calendar/99535

**Comment by juliushaertl** [comment]
There are no plans to do this at the moment. A calendar entry doesn't fit in terms of the properties we can expose to CalDAV there and logically a VTODO entry is just what makes most sense here.
