### ISSUE TITLE
Allow searching for tags

### ISSUE THREAD

**Issue by djibux** [nextcloud/deck#263]
### Steps to reproduce
1. Assign a tag called "Test" to a task not containing the word "Test" 
2. Search for "Test"

#### Minimal
The task should appear.
#### Ideal
I also think there should be a way to search exclusively for tags.  For instance "tag:Test" should only match tasks containing the tag "Test".  A task called "Test" but without tag shouldn't be in the search results.

### Actual behaviour
The task does not appear (does not match the search).

**Comment by juliushaertl** [comment]
Thanks for your feature request. I summarized the search improvements in https://github.com/nextcloud/deck/issues/286 

Let's continue there.
