### ISSUE TITLE
Talk app integration

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#2630]
Being able to share a reference to a Deck card in Nextcloud Talk. The card reference will be shared together with the title and a link to open the card inside of the Deck app. The user will also be able to turn a Talk message within a chat into a Deck card.

![image](https://user-images.githubusercontent.com/1589737/75150006-9dab7780-5703-11ea-94cd-17a850ffef7b.png)
The '...' menu of the right sidebar will provide a option to share a reference to a card to a chat room.

![image](https://user-images.githubusercontent.com/1589737/75150012-a439ef00-5703-11ea-8e2b-adeea01ce361.png)
 In Talk the '...' next to the message will provide a option to turn a message into a Deck card.

### Acceptance criteria

* The user can share a card reference from Deck to Talk. 
* The card reference will be shared together with the title and a link to open the card inside of the Deck app
 * The user c

**Comment by putt1ck** [comment]
Can some thought be given as to this feature being easily adapted to other chat plugins? We're working with Rocket for example.

**Comment by juliushaertl** [comment]
From the Chat to deck part it should already be possible to implement something like this with the rest api, for the other direction, if anyone is interested in writing such an integration I'm happy to talk about how we could provide an api for that. I could imagine we allow apps to just register a javascript method that allows to send a link over to whatever service then.

**Comment by juliushaertl** [comment]
We could do something similar for other apps of course as requested in #2709 for mail.

**Comment by jakobroehrl** [comment]
https://github.com/nextcloud/mail/issues/3064

**Comment by nickvergessen** [comment]
Rich object string definition in server so they can be part of chat messages: https://github.com/nextcloud/server/pull/25070

**Comment by juliushaertl** [comment]
Implemented with 1.3 already
