### ISSUE TITLE
Integrate Desk app into IOS application

### ISSUE THREAD

**Issue by Maxence1502** [nextcloud/deck#2636]
Nothing more to say than the title "Integrate Desk app into IOS application" 👍 
That I can see my desk on my phone.

Thanks :)

**Comment by stefan-niedermann** [comment]
See https://help.nextcloud.com/t/nextcloud-deck-android-1-12-1-attachment-picker/98011/3?u=stefan-niedermann

**Comment by juliushaertl** [comment]
Yes as stated in https://github.com/nextcloud/deck/issues/1769#issuecomment-628589380 we don't have any plans for an iOS app but since there is a community project already started I have high hopes in that one :grin:
