### ISSUE TITLE
Cards with Checklists

### ISSUE THREAD

**Issue by Energiegenossenschaft** [nextcloud/deck#2637]
It would be very pleasant, if checklists could be created in the cards. We know this feature from Trello and it optimizes the project workflow enormously.   

![Bildschirmfoto vom 2020-12-07 11-04-15](https://user-images.githubusercontent.com/50826951/101337730-52221e80-387c-11eb-9ef8-598d4a110877.png)

**Comment by putt1ck** [comment]
Already available.

Start with first one in the description text using `- [ ]` and the desired text, then pressing enter creates a new tasklist entry

**Comment by Energiegenossenschaft** [comment]
AWESOME!
Thank you for the quick reply!
