### ISSUE TITLE
Continuous notifications for shared boards

### ISSUE THREAD

**Issue by yamsu** [nextcloud/deck#2652]
**Describe the bug**
On sharing a deck board with another user I continuous get notifications which " xxx deck shared by user1"

This happens very day. I get 10-15 notifications in a day.

**To Reproduce**
Share any board with any other user and check for the notifications to the other user account.

**Expected behavior**

**Screenshots**

**Client details:**
 - OS: Linux and android
 - Browser firefox
 - Version nextcould 20.2
 - Device: Android 8 and desktop

**Operating system**:
Ubuntu Linux 20.04

**Web server:**
Nginx

**Database:**
Postgresql

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
20.02

**Where did you install Nextcloud from:**

**Signing status:**
Certified certificate

**Comment by juliushaertl** [comment]
I cannot reproduce that. Did you dismis the notification and are still getting new ones or are there multiple at the same time?
