### ISSUE TITLE
Upcoming Cards & global search shows cards from deleted lists

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#2660]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Cards from deleted lists are still shown in Upcoming Cards view and global search.

**To Reproduce**
1. Create a new list `My-List`
2. Create a card `My-Card` in this list
3. Assign yourself to this card
4. Delete the list from step 1
5. Go to upcoming cards view
6. It still shows `My-Card`

Side note: The card `My-Card` can also be found via the global search.

**Expected behavior**
The card is not accessible anymore using the default Deck Web UI tools - so it should also not be accessible via the Upcoming Cards view or the global search.

cc @desperateCoder

**Comment by juliushaertl** [comment]
I think i saw a related fix somewhere but I need to check that again.
