### ISSUE TITLE
Improve stack drag and drop behavior

### ISSUE THREAD

**Issue by Mr-Tin-25** [nextcloud/deck#2669]
## Summary from the issue discussion

A few points that would make the drag behavior feel more expected:

- [ ] Only allow drag and drop on the stack title
- [ ] Do not trigger the stack rename on release of the mouse button if dragging has started

## Original report

Hi,

could you please make columns/lists sticky even for people that are allowed to a add and remove them.
It happens to often to me that i move columns randomly.
Maybe you create an edit mode for columns.

Thanks
Martin

**Comment by juliushaertl** [comment]
Not sure about this, other solutions seem to also always allow reordering. 

cc @jancborchardt @Clementine46 What do you think?

**Comment by Mr-Tin-25** [comment]
and what about moving the columns only by grabbing them on top next to name?

**Comment by quentinDupont** [comment]
> and what about moving the columns only by grabbing them on top next to name?

I agree : what is confusing is that we can move columns by grabbing them anywhere and that the pointer is not changing as when we grab the column on top :

![Peek 21-01-2021 16-01](https://user-images.githubusercontent.com/9005817/105368516-ec0e1280-5c01-11eb-9f0e-cf6f2662f5ff.gif)

**Comment by quentinDupont** [comment]
Maybe a hover css on top column would be good ?

**Comment by Mr-Tin-25** [comment]
Or an icon as handler to grab. Like an arrow left right e.g.

Feature request:
If columns only move when grabbing on top, it would be great to move the whole board view left and right when grabbing background.

**Comment by juliushaertl** [comment]
A few points that would make the drag behavior feel more expected:

- [ ] Only allow drag and drop on the stack title
- [ ] Do not trigger the stack rename on release of the mouse button if dragging has started

**Comment by juliushaertl** [comment]
Related pull request for the cards: https://github.com/nextcloud/deck/pull/3916
