### ISSUE TITLE
Not able to assign users to cards...

### ISSUE THREAD

**Issue by deljones** [nextcloud/deck#2673]
**Describe the bug**
In Deck app 1.2.2 if I click in the field to assign a user to a card only *me* is available. If I attempt to add another known user they do not appear.

**To Reproduce**
1. Create a list on a board
2. Click to get the details on the right
3. Click in the "Assign a user to this card..."
4. Type in a known user.

**Expected behavior**
As you type the first letters of a known user they should appear ready to be assigned.

**Screenshots**
Sorry. No screenshots.

**Client details:**
Same problem on latest Android app

Sharing of boards works fine.

**Comment by stefan-niedermann** [comment]
Dumb question, but have you shared the board first with the user, so they have access to the board before trying to assign a card to the user?

**Comment by deljones** [comment]
@stefan-niedermann that is not a dumb question at all. The reality is that I'm dumb. Yes, I created a new test user, shared a board with that user then I could assign them a card. (what a surprise) 
I don't know why but long ago I thought that you could assign a card to anyone, but thinking about it why would you? 
I thought that by assigning a card to any user you could get them to work on that specific item (card) without them seeing the whole board.
But yes it works as it should and I got it wrong... Doh!
