### ISSUE TITLE
Moving Attachments into the first Tab

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/deck#2691]
![grafik](https://user-images.githubusercontent.com/24530680/103349805-27537080-4a9e-11eb-8d9c-73485825d46f.png)

**Comment by juliushaertl** [comment]
Please try to provide some arguments for such UI changes in the future and involve @nextcloud/designers for discussion :) (cc-ing @Clementine46 @jancborchardt especially for deck)

I generally don't like putting even more content into the sidebar by default. The tabs are a good way to quickly navigate to that if needed and especially if projects are linked the sidebar becomes rather messed in my opinion with this, so :-1: from my side.

**Comment by stefan-niedermann** [comment]
Speaking for the Android app (where we have limited space), i will not follow this approach - actually i planned to do the opposite and move the Project relations into its own tab in the future 😅

**Comment by juliushaertl** [comment]
I'd say that is totally fine for limited space (as we also have it in the sidebar). For the modal view see https://github.com/nextcloud/deck/issues/2702

**Comment by jakobroehrl** [comment]
@stefan-niedermann 
I think we should show the attachments on limited space, too. Otherwise it will be overseen. 
Example on Trello: (I can provide examples on zenkit, padlet, ... if needed)
![grafik](https://user-images.githubusercontent.com/24530680/103645209-ef45a500-4f57-11eb-90a9-c04baf1c3488.png)

**Comment by stefan-niedermann** [comment]
@jakobroehrl while i get the motivation now, i still think that this will lead to a very crowded.
I would prefer to hint to the attachments like proposed in #1635 instead.
