### ISSUE TITLE
In some cases the description is deleted

### ISSUE THREAD

**Issue by rscata** [nextcloud/deck#2705]
**Describe the bug**
In some cases the description is deleted

**To Reproduce**

**Expected behavior**
I encountered the problem several times, I save details in the description, and after a while if I do other actions on that card, the description is deleted
**Screenshots**

**Client details:**
 - OS: [Linux]
 - Browser [Firefox]
 - Version [84.0.1 (64-bit)]

<details>
<summary>Server details</summary>

**Operating system**:
- Ubuntu
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
- 20.0.4

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Please fill out the full issue template, especially which version of deck you are using and if there are any errors in the logs/browser console.

Can you pinpoint the issue to any specific action you have taken that removed the description? Maybe you can check the activity log for the card on the actions that happened?

**Comment by jdohm** [comment]
One way to replicate this behavior (in version 1.2.3) is by editing the description and than clicking preview.
It does *not* happen every time, I suspect it only appears if there are two actions in a short time frame.

Here is a small video clip of reproducing it, its set to 0.5xspeed [Video](https://dohm.webo.family/index.php/s/YNz4cKB78TBL9sX) 
(The added "1" on front of the link is missing after hitting preview)

**Comment by kartoffelheinz** [comment]
Happens also to us, and happens quite often. Super annoying. I can replicate by editing the description of a new card and moving the card to another stack or assigning a user. Simply, most actions will do the trick.

**Comment by kojid0** [comment]
Facing the same bug but I don't know why or when it occurs.
All I see is that the description is being deleted randomly...
Thought I report it as well to show that this is a "serious" bug concerning a lot of users.

**Comment by BKapelari** [comment]
We have the same issue! Its really annoying cause we lose a lot of data! We have to write everything in an external text editor first and copied into the description field, cause every time after we safe and change the board, the text is gone. When we refill the text, it stays. See screenshots from the console attached.

![Bild 19 02 21 um 15 25](https://user-images.githubusercontent.com/4718590/108678868-f7e44180-74eb-11eb-8b3b-dfc87056e13c.jpg)
![Bild 19 02 21 um 16 52](https://user-images.githubusercontent.com/4718590/108678872-f9156e80-74eb-11eb-9ac1-3de297fbfadc.jpg)
![Bild 19 02 21 um 15 33](https://user-images.githubusercontent.com/4718590/108678873-f9156e80-74eb-11eb-9390-3ef71c2ea98a.jpg)

NC 19 and 20. – Deck 1.2.4

**Comment by szimszon** [comment]
The same happens in NC21 and Deck 1.3.1 ;(

**Comment by jdohm** [comment]
Did #2947 address this issue @jakobroehrl? Looks like #2881 was closed, which seams to address the same issue.
Sadly I'm still able to reproduce this behavior after updating to Deck to 1.2.6

**Comment by jakobroehrl** [comment]
No, https://github.com/nextcloud/deck/pull/2947 solved https://github.com/nextcloud/deck/issues/2789
This issue is still open.
