### ISSUE TITLE
Beta version totally breaks Nextcloud. Something to do with IShare? Revert to 1.2.3 and working

### ISSUE THREAD

**Issue by camba063** [nextcloud/deck#2706]
Error: Undefined class constant 'OCP\Share\IShare::TYPE_DECK_USER'
Error: Undefined class constant 'TYPE_DECK'

Offending files are: 
/nextcloud/extra-apps/deck/lib/Sharing/DeckShareProvider.php
/nextcloud/extra-apps/deck/lib/Sharing/Listener.php

Hope you can find a fix. Thanks for the great work so far! Love the app and use it every day!!!

**Comment by juliushaertl** [comment]
I assume you were trying to install it on Nextcloud 20 which is and will not be supported https://github.com/nextcloud/deck/blob/master/appinfo/info.xml#L39 as we are introducing a new way to share files with deck which is only compatible with Nextcloud 21 and higher.
