### ISSUE TITLE
Creating cards from mails

### ISSUE THREAD

**Issue by morbificagent** [nextcloud/deck#2709]
Actualy we are using Outlook and Deck in our company as we are testing deck as a "case-management" system.

At the moment we have to manualy create a card, enter a title and so on to get the mails into deck as card.

it would be such great if it would be possible to create a card from outlook or nextcloud-mail by rightclick -> "make card" :-)

**Comment by juliushaertl** [comment]
For outlook this is rather out of scope of our repository, for mail I assume we could reuse the approach we plan for Nextcloud Talk in #2630 to also integrate it into Nextcloud Mail, so I'm closing this as a duplicate.

**Comment by putt1ck** [comment]
> Actualy we are using Outlook and Deck in our company as we are testing deck as a "case-management" system.
> 
> At the moment we have to manualy create a card, enter a title and so on to get the mails into deck as card.
> 
> it would be such great if it would be possible to create a card from outlook or nextcloud-mail by rightclick -> "make card" :-)

There's already this tool to get emails to Deck https://github.com/putt1ck/mail2deck - any use?

**Comment by morbificagent** [comment]
Yes i have tried it but had some problems with it as the results were very mixed.

Sometimes mail-attachments were problematic and as result there wasnt an attachment on the card but endles code in the card description...
Sometimes html formated mails were problematic as the body wasnt really readeable in the resulting card...

And if i sent a mail with a longer conversation the card looked very moderate as the subject had all AW: AW: WG: RE: in it, the body wasnt good readeable because of formating-problems.
So there wasnt filter mechanism to create a good looking and useable card at the end.

And after a while i created cards manually again because mail2deck results in much work often.

**Comment by putt1ck** [comment]
@morbificagent if you report those issues on Github someone will look at them - we've not had issues like those but use masil2deck for capturing direct submission type emails i.e. like an issue tracker.

For the more complex stuiff you might find saving the emails is a better option and using emlviewer to see the contents of the email, and just linking the email from the card.
