### ISSUE TITLE
Dependencies (parent/child) card management

### ISSUE THREAD

**Issue by rkantos** [nextcloud/deck#272]
I've always wanted a kanban board like Trello to have dependencies for cards, e.g. where you can set parents/children for cards. Meanwhile I'm just using Parent/Child Management by Handsome. It works ok. Trello now actually has this feature as a power-up: https://helloepics.com/ However for my usage the pricing is a bit steep (195$ for 5 members for 1 year...). I would like such feature added to deck! 

Thanks!

**Comment by juliushaertl** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by headkit** [comment]
This is a urgently needed feature!

**Comment by benyanke** [comment]
Given that Epics (#2742) will not be implemented as out-of-scope, could this issue be re-opened, even if it won't be worked on immediately? It seems it was closed as rolled into the the epics issue, which was later closed.
