### ISSUE TITLE
[master] Page refresh needed after creating new board when talk app is enabled

### ISSUE THREAD

**Issue by PVince81** [nextcloud/deck#2721]
### Steps

1. git clone latest NC master (e44f275cfedaf1b7934a3ff0d6b8f575a28d9ca6)
2. git clone latest deck app (5bbf96eab1f1b11df9e448155f03bb97d8f7ac4b)
3. Run `make build-js` or `make watch` as per README
4. `occ app:enable deck`
5. Go to web UI of the deck app
6. Type in a new board name
7. Hit enter and wait

### Expected result
New board entry appears.

### Actual result
No entry appears.
After a page refresh it appears.

### Logs

Nothing notable in the logs.
I do see that the POST request went through and returned a JSON payload and returned a 200 status.
So maybe some of the Vue update code is not working any more.

**Comment by PVince81** [comment]
Hmm, same problem when creating cards and creating new lists.

**Comment by juliushaertl** [comment]
I cannot see anything like that on master. Nothing in the browser logs there? Maybe when preserving it across the page reload?

**Comment by PVince81** [comment]
Okay, if it works for you then I'll try and debug this locally. Maybe a side effect with other enabled apps (like Talk)

**Comment by PVince81** [comment]
What !?

I just retried from scratch and it worked fine.
Then after enabling the talk app the bug appears again.

I'll try and debug this... possibly some weird side effect

**Comment by PVince81** [comment]
I've added some logging and can confirm that the board is pushed into the state... I wonder if some side effect is messing with reactivity.

**Comment by PVince81** [comment]
Okay, I got something: in the page the file "talk-files-sidebar" is loaded, probably because Deck also has a sidebar.
If I comment out that file in Talk's PHP to avoid loading, the bug disappear.

Now to go deeper...

**Comment by PVince81** [comment]
I've traced it down to this line: https://github.com/nextcloud/spreed/blob/master/src/mainFilesSidebar.js#L83

If you comment out `store` so that it doesn't get assigned to `window.OCA.Talk`, the side effect disappears :thinking: 

Still mysterious!

**Comment by juliushaertl** [comment]
Hm, i also can't see this with latest talk master installed. I'm wondering if there is any issue with having two entrypoints with a vuex store loaded then.

**Comment by PVince81** [comment]
Whaaaaaaat!!! If I disable the Chromium's Vue Devtool then it works fine...

I suspect that the Vue DevTool is tracking whatever store is attached to the window object...

**Comment by PVince81** [comment]
For reference, these are my versions:
- Chromium Version 87.0.4280.88 (openSUSE Build) (64-bit)
- Vue devtool extension Version 5.3.3

**Comment by PVince81** [comment]
I've posted something here: https://github.com/vuejs/vue-devtools/issues/430#issuecomment-759315830

**Comment by PVince81** [comment]
Closing as it's not a bug in neither Deck nor Talk apps
