### ISSUE TITLE
Erro ao alterar data com o modo de "Visualização ampliada"

### ISSUE THREAD

**Issue by tiagoTISME** [nextcloud/deck#2724]
Bom dia!
Foi identificado um erro na apresentação do check box para alterar data de vencimento do cartão no modo de visualização "Visualização ampliada"
Segue anexo do erro na visualização.

Desde já agradeço!

Att,
Tiago Mendes.
![ksnip_20210113-101432](https://user-images.githubusercontent.com/57405389/104458793-95ae2d80-558a-11eb-9fa7-64cd92d575f2.png)

**Comment by juliushaertl** [comment]
Please open issues in English and check for existing issues that might already be around before creating new ones. From the screenshot this seems like a duplicate of #2704
