### ISSUE TITLE
n8n integration for Deck app

### ISSUE THREAD

**Issue by sunjam** [nextcloud/deck#2726]
Related to #1722 Flow integration.  This is an alternative program developed on [Github](https://github.com/n8n-io/n8n) and [documentation here](https://docs.n8n.io/).

[n8n.io](n8n.io/) is fully open source and could prove extremely useful for the Deck app as it supports a number of app [integrations](https://n8n.io/integrations), including [Nextcloud](https://n8n.io/integrations/n8n-nodes-base.nextCloud), Trello and Taiga #450 and [WeKan](https://n8n.io/integrations/n8n-nodes-base.wekan).

**Comment by stefan-niedermann** [comment]
I downvoted because in my opinion this kind of integration should be a separate app which can be developed independently from the Deck app.

**Comment by sunjam** [comment]
Ah, someone how I missed this comment.  You are correct that the integration is needed on the n8n side of things, which already supports a number of other Nextcloud API's.  [Here is the full list of supported functions](https://docs.n8n.io/nodes/n8n-nodes-base.nextCloud/).

**Comment by stefan-niedermann** [comment]
Would you mind closing this issue then? 🙂 The API documentation [is here](https://deck.readthedocs.io/en/latest/API/) in case you want to point the guys of n8n there.
