### ISSUE TITLE
Floating card needs scrolling after opening date picker

### ISSUE THREAD

**Issue by bin101** [nextcloud/deck#2728]
If the description is to short or not existing you need to scroll to be able to choose a date on the lower half of the date picker.

![image](https://user-images.githubusercontent.com/12427722/104724018-6507f880-5730-11eb-9322-d5ad8695686c.png)

**Comment by 4tler** [comment]
I think it is ehe same like this: #2704

**Comment by bin101** [comment]
Your right it is a duplicate. I am closing this now.
