### ISSUE TITLE
DECK on NextcloudPI

### ISSUE THREAD

**Issue by fossy55** [nextcloud/deck#2735]
Hi, is it possible to use DECK on NextcloudPi ? The only version which I can find is 0.41 .

**Comment by jakobroehrl** [comment]
Sure, what is your nextcloud version?

**Comment by fossy55** [comment]
Hello oder Hallo, Jakob.
I use NextCloudPi 20.0.5 
Greetings

**Comment by jakobroehrl** [comment]
This is weird. 
But you can put the latest release under apps and unzip it: https://github.com/nextcloud/deck/releases

**Comment by Jeanoo** [comment]
The latest version of NextCloudPi is v1.34.7 https://github.com/nextcloud/nextcloudpi/blob/master/changelog.md this is not yet compatible with NextCloud 20.0.5

**Comment by fossy55** [comment]
Hi, here a scrennshot of system info
![Screenshot_2021-01-20 NextCloudPi Panel](https://user-images.githubusercontent.com/77576100/105165456-a9234080-5b16-11eb-82cd-b4fb6ba3ee54.png).
Why is it weird ?
Greetings

**Comment by juliushaertl** [comment]
Should be fine with the altest server release again through https://github.com/nextcloud/server/pull/25152
