### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by Nyco** [nextcloud/deck#2742]
- Context: In Agile and DevOps teams, specifications are usually described as "User Stories".
- Problem:
Sometimes it is extremely difficult to communicate in a multi-discplinary context (UX, QA, dev, sales, marketing, ops, Scrum Master, agile coach, Product Owner/Manager).
The problem is: the card is the unit of work in Deck which may be too precise, too focussed, too narrow, too tiny.
As a consequence, it is difficult to present things in a more abstract or higher level
- Solution:
A possible solution is to add an "Epic" feature, as a set of Cards (but not using Labels), as it is often used in Agile/DevOps contexts.
- Benefits:
The main benefits are you can plan and communicate that plan to higher levels and C-levels, like a roadmap.

If this feature can potentially be accepted, we can start to design it: just give us a go.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
A card is too precise.

**Describe the solution you'd like**
An Epic feature would be nice.

**Describe alternatives you've considered**
Use of labels as Epics. But this is overloading the number of Labels.

**Additional context**
It is often used in Agile teams.

**Comment by stefan-niedermann** [comment]
Please use the search function before opening new issues.

See for example

- https://github.com/nextcloud/deck/issues/1940
- https://github.com/nextcloud/deck/issues/272

and related (in terms of grouping elements withing a board)

- https://github.com/nextcloud/deck/issues/2103 (Sub-cards)
- https://github.com/nextcloud/deck/issues/32 (Swimlanes)
- https://github.com/nextcloud/deck/issues/855 (Sprints)

Pesonally i would advice you to use the Nextcloud Projects feature to connect multiple cards to one bigger project - as a benefit you are able to also link Talk rooms and other artifacts in Nextcloud to a Project.

**Comment by Nyco** [comment]
Sorry, you are right, I didn't find the other "Epics" card: https://github.com/nextcloud/deck/issues/1940

An Epic is not a sub-card, nor a dependency, nor a group of cards, nor a swimlane, nor a sprint.

Trying fast definitions and marking the differences:
- epic:
  - def: a group of task related to the same big feature
  - use: as an umbrella card that holds other cards
- sub-card:
  - def: it may be a card, but it is broken down (or "split" or "cut") from an original card, that sub-card may bring some content and meta-data copied from its original
  - use: when you need split/divide a card into smaller cards, for example, so that it fits in a sprint in a sprint, or so that you lower the undertainty
- label
  - def: flexible and customisable field of meta data
  - use: basically everything
- groups of cards
  - def: quite explicit, but loose definition
  - use: this does not say how nor what the use is
- swimlane
  - def: a visual lane in a kanban board, fit for given classes of service
  - use: SLA, like "Urgent customer demand", or "Internal need in order to be able to code faster later" 
- sprint:
  - def: a grouping by the period of time in whihc this card must be treated and done (delivered)
  - use: scrum or scrumban (mix/hybird between Scrum and Kanban)

Example:

An Epic for the development of Deck could be "Write a Epic feature".

That would be "Epic 3", with stories B, C, D, H, and M. And later S.

- Epic 3:
  - Story B: CRUD Epic
    - label: New feature
    - swimlane: High-level
    - sprint: 2
  - Story C: Add/remove card from Epic
    - label: Enhancement
    - swimlane: : High-level
    - sprint: 3
  - Story D: Epic view
    - label: Visualisation
    - swimlane: 
    - sprint: 3
  - Story H: Add Epic in Upcoming cards
    - label: Enhancement, Visualisation
    - swimlane:
    - sprint: 5
  - Story M: Epic metrics
    - label: Metrics
    - swimlane: High-level
    - sprint: 7
  - Story S: Roadmap
    - label: Visualisation
    - swimlane:
    - sprint: 9

**Comment by Nyco** [comment]
Epics in:
- JIRA: https://www.atlassian.com/agile/project-management/epics
- Taiga: https://tree.taiga.io/support/epics/what-is-an-epic/
- Asana: https://asana.com/guide/examples/project-management/asana-agile?missingtranslation=en#gl-epics
- Trello:
  - https://trello.com/power-ups/5b7ae739fad82e45988016cf/epic-cards-by-screenful
  - https://screenful.com/epics-for-trello
- GitLab: https://docs.gitlab.com/ee/user/group/epics/
- Redmine: https://www.redmineup.com/pages/blog/how-to-manage-epics-user-stories-in-redmine

**Comment by putt1ck** [comment]
Is it not just a "project" where multiple boards are connected together?

**Comment by Nyco** [comment]
I'd say an Epic is contained in a project or a product.
Some even add a layer on top of Epics: Themes.

**Comment by putt1ck** [comment]
I was thinking in Nextcloud terms, where "projects" are used to link together different assets and asset types.

**Comment by Nyco** [comment]
Nextcloud's projects are meant - if I understand correctly - to "group" different objects such as file/folder, board, discussion, etc.

An Epic would stay inside a Deck board as a group of cards.

**Comment by juliushaertl** [comment]
Thanks for your feature request. I can see this is a valid use case however we currently consider deck more as a simple tool that is easy to use and want to keep the complexity low. We target common use cases but don’t necessarily want to extend to a fully fledged project management tool. There are lots of good open source tools out there already for more complex use cases. Therefore I’d consider this out of scope.

**Comment by RubensRainelli** [comment]
I'd really need it...
