### ISSUE TITLE
Familyboard with points and advantages

### ISSUE THREAD

**Issue by dafreeze01** [nextcloud/deck#2762]
I'd like to use the board for my family (not for programming). My children have some tasks per week (clean litter box, bring out garbage,...) We want to combine the tasks with some advantages (extra screen time, presents, wishes, etc.). So they will get points for doing their tasks and the advantages are also linked to points and can be "activated" and selected.

The main idea is, to build a board, where the children can add their tasks to an own board (school tasks, personal tasks or ideas), a family board (ideas an wishes connected with points) and a Houseboard, where the typical home tasks (vacuuming, cleaning, ...) are connected with points as well. Everybody can earn points by doing a task. He can send points to another user or group.
The group or user can activate a wish, when they have enough points.

There is no alternative and i never saw anything like that. I think it would be a really cool thing implementing it. I'm a sysadmin and never programmed in the nextcloud api, but i think it's cool and maybeit will be a real extra

#480 is essential for it, because of the repeating tasks every weak an the period for doing it. (You should clean your room every week and you have one week for doing it)

A template for children would be nice as well.

- [ ] Ideas for a family board until 05.02.2021
- [ ] Database for points per user / group
- [ ] Database for repeating events and period
- [ ] Controller for points
- [ ] Controller for repeating events and period
- [ ] Frontend for points
- [ ] Frontend for repeating events and period
- [ ] Controller for tasks and dependencies (points or tasks)
- [ ] Template for Children

Feel free to add some more or split up tasks. I will look for the code on my own, but first i will learn, nextcloud coding works ;-)

**Comment by stefan-niedermann** [comment]
Well, this is a very specialized edge cases of using Deck.
I think there are already some building blocks / Issues which might summarized enable your use case, for example:

- #480 Recurrently cards
- #1833 user defined fields (For adding custom fields like the "points")
- #1556 Template Cards (Use clone feature as a workaround)
- #1722 Flow integration (For automatic processing the "points")

In my opinion we should focus on these issues as they are more generic and helpful for many use cases. It will be a nice benefit if they will also solve your special use case, but we should not focus on solving a single use case. Maybe you can / want contribute to one of them :slightly_smiling_face: ?

**Comment by dafreeze01** [comment]
i'd like to. I'll begin with #480 and #1722 we'll see how I get on

**Comment by jakobroehrl** [comment]
@dafreeze01 
Nice idea, you can ping me if you need help.

**Comment by juliushaertl** [comment]
Thanks for this detailed use case description. As Stefan mentioned the individual feature requests, I'd close this issue.
