### ISSUE TITLE
Link in tickable task is not rendered correctly

### ISSUE THREAD

**Issue by Zocker1999NET** [nextcloud/deck#2769]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Having a card with a tickable task and a link, the link will not be rendered correctly (see screenshot).

**To Reproduce**
1. Open a new card
2. Insert following text as description
```
- [ ] [GitHub](https://github.com)
```
3. Disable edit mode

**Expected behavior**
Expect it to be rendered correctly by just showing "GitHub" in this case.

**Screenshots**
Description in edit mode:
![image](https://user-images.githubusercontent.com/1645646/106381621-6422c800-63ba-11eb-87ad-f41b832f39e6.png)

Description in rendered view (with invalid rendering):
![image](https://user-images.githubusercontent.com/1645646/106381644-8288c380-63ba-11eb-928b-faf3bae25aa7.png)

**Client details:**
 - OS: Debian GNU/Linux testing
 - Browser: Mozilla Firefox
 - Version: 84.0.2 (64-bit)
 - Device: desktop

<details>
<summary>Server details</summary>

**Operating system**: Debian Buster (currently stable)

**Web server:** nginx + php-fpm (from Debian Buster)

**Database:** MySQL (from Debian Buster)

**PHP version:** 7.3.19-1~deb10u1

**Nextcloud version:** 20.0.6

**Where did you install Nextcloud from:** standalone (downloaded zip from your homepage

**Signing status:**

Server configs should not matter for this issue, otherwise I can provide them

**List of activated apps:**

Server configs should not matter for this issue, otherwise I can provide them

**Nextcloud configuration:**

Server configs should not matter for this issue, otherwise I can provide them

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
Server logs should not matter for this issue, otherwise I can provide them

#### Browser log
```
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:60:15
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 5 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
OC.getCapabilities is deprecated and will be removed in Nextcloud 21. See @nextcloud/capabilities 2 capabilities.js:32:9
OCA.Search is deprecated. Please use the unified search API instead search.js:31:10
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 12 globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 5 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 20 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 86 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 12 globals.js:60:15
XHRGEThttps://cloud.banananet.work/ocs/v2.php/apps/user_status/api/v1/statuses/undefined
[HTTP/2 404 Not Found 1892ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 73 globals.js:60:15
```

</details>

**Comment by stefan-niedermann** [comment]
Related: https://github.com/nextcloud/deck/issues/2138#issuecomment-679089099

**Comment by Zocker1999NET** [comment]
okay, seems like #2138 is my issue here, close this as duplicate

**Comment by stefan-niedermann** [comment]
Not sure, it just sounds related 😄
