### ISSUE TITLE
assign card to user when adding a due date on a shared board

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/deck#2771]
trello does this so
otherwise the card is not shown in the Upcoming card view

**Comment by stefan-niedermann** [comment]
And to which user? I mean if the board is shared, there are multiple possible users...?

**Comment by jakobroehrl** [comment]
To the current user.
If I add a due the card will be assigned to me.

**Comment by stefan-niedermann** [comment]
Hmm, while i understand the motivation to display the cards in the Upcoming cards view, i do vote against this automatic behavior (or at least make it configurable).

A team having a meeting has usually one person who writes down the stuff and with your proposal all cards would be assigned to this person and need changes (which will produce notifications and clutter the activity stream).
