### ISSUE TITLE
Users not available in the "Assing a user to this card" field

### ISSUE THREAD

**Issue by ctgcwiqc** [nextcloud/deck#2788]
Describe the bug:
Added user to server.  In deck, when creating a card, no other users are visible to this user, and this user is not visible to the other users.

Steps to reproduce:
Create new user
go to decks
create card
attempt to assign user to card (other than self)
no other users are able to be added

Expected behavior"
assign users should allow searching for other users in the DB

Client Details:
Ubuntu server 20.04 latest
NExcloud snap latest
Chrome Version 88.0.4324.146 (Official Build) (64-bit)
Also fails from android client as well as desktop
![missing users](https://user-images.githubusercontent.com/7608993/107137515-ef2c2280-68d2-11eb-9a72-ad906fa3be72.png)

**Comment by putt1ck** [comment]
Was the user available to be added to the board, just not the card?

**Comment by ctgcwiqc** [comment]
OK, thanks.  Will test as soon as I can.  I broke my server.  I will close this issue as you pointed me in the right direction.
THanks.
