### ISSUE TITLE
Sidebar is out of place when jsxc panel is visible

### ISSUE THREAD

**Issue by DiGGeR2** [nextcloud/deck#279]
### Steps to reproduce
1. Open deck App
2. Open or close chat tab

### Expected behaviour
A clean app visual when chat tab is open or closed

### Actual behaviour
If chat tab is oppenned when I open Deck, i cannot close the task property tab
If chat tab is closed when I open Deck and then I open chat tab, the refresh is very poor

**Comment by juliushaertl** [comment]
@DiGGeR2 

What chat tabs are you refering to? The jsxc app?

**Comment by DiGGeR2** [comment]
YesLe 10 août 2017 10:44 AM, Julius Härtl <notifications@github.com> a écrit :@DiGGeR2
What chat tabs are you refering to? The jsxc app?

**Comment by 11111000000** [comment]
aug 17?! when you're guys will fix that?

**Comment by juliushaertl** [comment]
Seems to work fine with latest release and Nextcloud 15.
