### ISSUE TITLE
Sync with Kanban-Tasker

### ISSUE THREAD

**Issue by Gunnar-GO** [nextcloud/deck#2852]
an "simple" Frontend for Kanban on Windows systems is aviable: Kanban-Tasker.

May a Sync would allow to make use more native, easier ... simply more fluent.

**Comment by stefan-niedermann** [comment]
You should open this issue at their repository - the Deck App already provides a [well documented REST-API](https://deck.readthedocs.io/en/latest/API/). So it's up to Kanban-Tasker to use it :wink:
