### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#286]
The search currently just filters cards on the current board by title. This issue summarizes search improvements we should have in the future:

- Searching should work globally if the users is on the #282 
- Allow searching by tags #263
- Allow searching full text in the card description
- Sort by last modified date

Probably having a simple search syntax similar to the one on github might be good, e.g.:
- tag:important querystring
- stack:todo tag:design icon

For user friendly search syntax something like the gitlab filtered search component would be nice:
https://gitlab-org.gitlab.io/gitlab-ui/?path=/story/base-filtered-search--default

**Comment by ferdiga** [comment]
just my 2c
the github search syntax is perfect for developers, but a no go for end users, especially on mobile devices

**Comment by juliushaertl** [comment]
@ferdiga good point, fuzzy search should of course work as well, but the advanced syntax would allow to specifiy that without the need of an additional user interface to specify search conditions.

Trello also has some nice search syntax where you can use `@exampleusername` to search for users or `#tagname` to search for a tag: http://help.trello.com/article/808-searching-for-cards-all-boards

**Comment by ossie** [comment]
Another point: Make search case insensitive

**Comment by pbek** [comment]
Thank you for this wonderful app to manage the things I do (beside managing them in QOwnNotes :smile: )! I want to give a +1 on the case insensitive search! That really would be an improvement in my opinion. I almost wanted to file an issue because I couldn't find my items. :)

**Comment by jfowl** [comment]
Push for case insensive search.

**Comment by Dubidubiduu** [comment]
I would love to seek for all decks I'm assigned to, on singular board and on all boards perspective.

Gmail search Syntax was also very nice in the old times

**Comment by nicolasVr** [comment]
I could not find any search option in Deck for the moment. It's a pity.
When using the search at the top right of the screen I have only a blank page and no result. I don't know if it is a bug or a missing feature.

**Comment by miguelsan** [comment]
@nicolasVr that sounds like a bug, I suggest to file in an extra issue, since the search function is working pretty well in the last versions, at least for me.

**Comment by miguelsan** [comment]
Case insensitive search works already. Kudos to the team for that

What about searching after tag or user? Is there any improvement in that direction? I find @juliushaertl [suggestion](https://github.com/nextcloud/deck/issues/286#issuecomment-321813145) pretty nice, btw.

**Comment by reox** [comment]
It would be nice to be able to search/filter for cards edited in the last n days, similar like the due to date filter. For example to retrieve a list of all finished cards of the last week.

**Comment by juliushaertl** [comment]
For some UI inspiration on the search filtering, gitlab has a nice filtered search ui component which would be worth to look into for the frontend here:

https://gitlab-org.gitlab.io/gitlab-ui/?path=/story/base-filtered-search--default

**Comment by ferdiga** [comment]
whats (really) missing is an easy filter for date ranges.

**Comment by stefan-niedermann** [comment]
@ferdiga this issue is about the **search**. If you need free date ranges in the due date **filter**, please open a separate issue for that.

Though, if the enhanced query language is coming, one might still think about adding keywords like `createdbefore`, `createdafter`, `duedatebefore` and `duedateafter`.

**Comment by juliushaertl** [comment]
or Something like `duedate:<today`. GitHub has something similar i think.

**Comment by dasBuero** [comment]
Kanboard has an [advanced search syntax](https://docs.kanboard.org/en/latest/user_guide/search.html) which seems to be a similar to GitHub.

**Comment by tomdereub** [comment]
An other improvement I think : let the word visible in the search bar. For now, if you type a word, it will let just the results visible in the board. But if you click to hide the search results, or even switch to another board, the search is still filtering the cards, but you don't see there is a keyword in the search bar : 
![Capture2](https://user-images.githubusercontent.com/16243499/106905002-1e3c6b80-66fc-11eb-8282-918fd6389302.PNG)
![Capture](https://user-images.githubusercontent.com/16243499/106905005-1f6d9880-66fc-11eb-8486-37576ffe1868.PNG)

In the example above, the board seems empty, but it's not, it's just filtered. But in second screenshot, you don't see on the screen that it's still filtered.
Maybe it should be an other issue ?

**Comment by juliushaertl** [comment]
@tomdereub The search in the header is a standardized part of the Nextcloud server, so maybe you can move that request for discussion to https://github.com/nextcloud/server/

**Comment by juliushaertl** [comment]
Implemented with #2934
