### ISSUE TITLE
Icons are invisible

### ISSUE THREAD

**Issue by fm-sys** [nextcloud/deck#2867]
After upgrading to Nextcloud 21, many icons are invisible. This issue might happen also for other Nextcloud Apps, but I have noticed it only on deck until now...

![grafik](https://user-images.githubusercontent.com/64581222/110248710-cef39000-7f72-11eb-97f0-a71e8cbe234f.png)

**Comment by Jonas-itquirks** [comment]
I have a very similar problem, which exists on my local install but not on the nextcloud instant trial.
The details button is there but invisible.

Nextcloud 21.0.1
Deck 1.4.0

![deck_bug1](https://user-images.githubusercontent.com/77517406/114612661-b3cb1d00-9ca2-11eb-84a5-4dc6d39be934.png)
![deck_bug2](https://user-images.githubusercontent.com/77517406/114612670-b75ea400-9ca2-11eb-82ac-16d4260635b1.png)

PS: This Button btw did work in version 1.3.2 to call up board details.

**Comment by juliushaertl** [comment]
Fix for the second report is in https://github.com/nextcloud/viewer/pull/856 the other one I cannot really repoduce, could you check if that might be a browser caching issue?

**Comment by fm-sys** [comment]
Outdated
