### ISSUE TITLE
Can assign Users to cards only after a page reload

### ISSUE THREAD

**Issue by dmueller78** [nextcloud/deck#2872]
Hey guys,

i have the following issue while using your plugin.

**To Reproduce**
I experience the following behavior when assigning users to cards. I create a new map, go to Share and there I see all users. But when I click on a specific one, I get the message: "Failed to create share with Username" and can't make an assignment accordingly. However, when I reload the page, the selected user appears in the list and I can assign it as expected.

In the logs of Nextcloud, Apache, PHP-FPM I don't see anything conspicuous, unfortunately. Would anyone have an idea how to address the problem?
 
 
**Operating system**:

**Web server:** Apache/2.4.41

**Database:** sql (PostgreSQL) 12.6

**PHP version:** PHP 7.4.3

**Nextcloud version:** 19.0.9

**Deck version:** 1.2.5

**Comment by dodedodo** [comment]
I cannot reproduce your issue on Nextcloud 20 with deck 1.2.5 also.
