### ISSUE TITLE
Checklist on a Card

### ISSUE THREAD

**Issue by danielromney** [nextcloud/deck#2876]
I see this utility as a way to track projects and not just tasks. I think it would be a great addition to have the ability to have a checklist on a card.
That way you could assign a card (project) to someone, and as they complete task in the project, they can check them off. I think that would be a great productivity tool and would make Deck just that much more useful.

**Comment by putt1ck** [comment]
In the card description use markdown `- [ ] item` which produces the first checklist item, then press enter to automatically generate a new checklist entry. Deck will then (a) render that as a checklist people can tick off and (b) show the number of items checked and remaining on the card

**Comment by danielromney** [comment]
This is fantastic.
Thank you so much.
