### ISSUE TITLE
Using a card to stop sharing an attachment deletes the entire file.

### ISSUE THREAD

**Issue by Czujackt** [nextcloud/deck#2877]
**Expected behavior** and **Describe the bug**

I understand attaching files actually like this.
You create a card and write a description and comments about it, then you link files. One user links a file and another user finds out that this file was not linked to the appropriate card. So the user unlinks the file. But, he does not want to delete the file!

Another problem is with the deck folder in Nextcloud. When a user deletes the contents of their deck folder, all users automatically have their data deleted and all cards have all attachments deleted as well. So a user can delete all attachments by mistake.

**Client details:**
 - OS: macOS
 - Browser Safari
 - Version 21
 - Device: desktop

**Comment by Czujackt** [comment]
Hi,
why is this a feature request?

If I share a file in a card and I don't want to share it anymore, then the file must not be deleted. The word share alone says that. If I share a file in the Nextcloud with another and then no longer share it, the file is not deleted. Why does Deck behave differently?

This problem is so significant that we can no longer use deck!

**Comment by stefan-niedermann** [comment]
Calm down. I added the label `feature: attachments` because it *affects* the existing features in the `attachments` section.

This is grouping and housekeeping and no reason to get angry. Afaik @juliushaertl is currently on vacation, maybe can @jakobroehrl have a look or you start a PR yourself.

I also think the behavior *was* intentional, so i'd like also to ring the @nextcloud/designers in again here - maybe the idea was to avoid dead attachments which aren't used anymore. Maybe we can have a combined solution: Unshare if the file has been shared otherwise, Delete if the file is not shared / referenced anywhere else.

**Comment by Czujackt** [comment]
Sorry for the harsh choice of words. We have been using Deck for a very long time and have gone through many development steps. But this step is a step backwards and means that we can no longer use Deck the way we do. 

I just think the idea behind it is wrong.
With attachments there are two ways to add files.

The first is 'upload new file'. Here, intuitively, it says upload a file that doesn't exist in Nextcloud to this card and store it in the deck card. If now another user, who can also edit this card, deletes this attachment again, then this attachment must also be deleted. Same right for all. It can't be that the attachment is gone for this user, but still exists for all other users. 

The second is 'Share from file'. Here it says quite clearly. A file from Nextcloud is shared with this card, so it is linked. So it is not the card that becomes the owner of the file. Now if you don't want to link the file anymore, then the file must not be deleted. Since the card did not become the owner of the file, it must not delete it.
If the file should be deleted, then there must be a second button, which is called: 'Don't link the file anymore and delete it'. That would be intuitive.

Translated with www.DeepL.com/Translator (free version)

**Comment by jakobroehrl** [comment]
Here are some ideas for making this better: https://github.com/nextcloud/deck/issues/2698

**Comment by florianwgnr** [comment]
Another thing worth mentioning is: 
After you have removed an attachment from a card (and therefore unintentionally removing it from nextcloud), it reappears when the original file is restored from trash. 

So after adding (wrong) a file, you can't remove it other than you delete the file.

**Comment by Czujackt** [comment]
Yes the Handling with the attachment is not very productive and intuitive.
