### ISSUE TITLE
In calendar, week and day mode no card information

### ISSUE THREAD

**Issue by rscata** [nextcloud/deck#2878]
**Describe the bug**
When I set a Due Date to a card, in Calendar App, in Day or Week view mode, no card information is seen. Only one line appears 

**To Reproduce**
1. Create a card
2. Set Due Date
3. Go to calendar app
4. Select Day or Week view

**Expected behavior**
It would be nice to have information, like in Month or List view mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/2580211/110757443-0f455d80-8254-11eb-999e-e9a8e602826e.png)

**Client details:**
 - OS: Linux Mint 20.1
 - Browser [Firefox]
 - Version [86.0 (64-bit)
 - Device: [Laptop]

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by dodedodo** [comment]
I agree that it's confusing but I don't think this is a deck issue. Deck cards in the calendar are just regular calandar-tasks. This is not limited to deck and shows on 'regular' tasks as well. 

You might wanna check the [issues for calendar](https://github.com/nextcloud/calendar/issues) and re-create there if it does not exist.
