### ISSUE TITLE
Drag and drop from on stack to another (empty one) doesn't work

### ISSUE THREAD

**Issue by OlivierAlves** [nextcloud/deck#288]
### Steps to reproduce
1. Create a new board
2. Create 2 stacks
3. Create a new item in stack 1
4. Attempt to drag newly created item to stack 2 (when stack two is empty) 
5. It is impossible to drag the item to the other stack 

### Expected behaviour
When I drag an item to an empty stack and drop it there, it should stay in that second stack 

### Actual behaviour
When I drag an item to the second empty stack and drop it their, the item stays in the first stack 

### Details
Latest stable nextcloud version, running on latest LAMP stack available
OS latest LTS version

**Comment by mithodin** [comment]
I also have this issue with the latest Deck (0.2.1) and Nextcloud (12.0.2) version.

**Comment by salulo** [comment]
Jepp, same here - Deck (0.2.1) and Nextcloud (12.0.2)

**Comment by rebeccaformfx** [comment]
me too (added a reaction!) However, I will add that once I start a drag from a single-card stack, it won't let me drag it back.  So it seems that once the stack is styled as "empty" we permanently lose the element that allows the card to drag back to its original position.

**Comment by janibonnevier** [comment]
#238 #235 #257

**Comment by juliushaertl** [comment]
As @janibonnevier said, this is a duplicate and will be fixed in the next release.

If anyone wants to help, there are two open pull requests that need some testing/review for 0.2.2 If they are merged I will release a new version.
