### ISSUE TITLE
deactivation the function decks in calender

### ISSUE THREAD

**Issue by BEESUPPORT** [nextcloud/deck#2882]
Hi, 
I wonder if there is an option to deactivate the apearing of "hundreds" of deck: [deckname] calenders in the 
"Calendar " app. First we used the deck indipendently from calender. But after one Update, don't know wich, im my calender views there are eight additional calenders. One for each kanban-board. 

I want to deaktivate this cause of a better overview.

Greetz
Stefan from BEE

**Comment by stefan-niedermann** [comment]
Please use the :mag: search function before opening new issues.

https://github.com/nextcloud/deck/issues/2824
https://github.com/nextcloud/deck/issues/2825
