### ISSUE TITLE
Allow filtering for tags

### ISSUE THREAD

**Issue by alirasol** [nextcloud/deck#289]
### Steps to reproduce
1. An option to show jobs according to lables. 

### Expected behaviour
When having many jobs in many orders that take some time to be done! there should be an option to view the unfinshed labels so it is easier to know what is to review and do it.

### Actual behaviour
no options

### My issue
I work in a car body shop, and I create a board for every day of the week and a stack for every car and then a card for every job I have to do for every car. 
Cars take between three day to two week to be done, and sometimes some cars get forgotten due to my short term memory. So it could be easier of there was an option to show every label alone so it could get easier to review. 

**Operating system**:
ubuntu 16.04

**Web server:**
apache

**Database:**
mysql
Version: 5.7.19

**PHP version:**
7.0.22

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

**Comment by juliushaertl** [comment]
Yes, that would ne nice to have. Might also be related to a search for specific tags as described in https://github.com/nextcloud/deck/issues/286

**Comment by juliushaertl** [comment]
I've created a summarizing issue regarding filters. Closing this in favor of #414
