### ISSUE TITLE
ETags not updated if card has been added to a new project

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#2892]
Given a card gets added to a new project in the Web UI (e. g. linking it to another card or a board), the `ETag`s are not updated. The changes are therefore not visible in the Deck Android app and other API clients.

**Comment by stefan-niedermann** [comment]
Might be caused by / related to #2485

**Comment by juliushaertl** [comment]
Yes, we cannot trigger anything there as the projects API is fully handled by the server and there are no events emitted yet so deck itself doesn't know about changes apart from the frontend which just queries the OCS API.

**Comment by stefan-niedermann** [comment]
Closing given `Projects` feature has been deprecated in favor of `Related Ressources`
