### ISSUE TITLE
Insert custom hex values into the color chooser (as label color)

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#2893]
Currently is it possible to choose a color from a color spectrum.

![Screenshot_20210316_141456](https://user-images.githubusercontent.com/16517095/111315014-42c42580-8662-11eb-8c56-165fe20ae567.png)

It would be very helpful to have an option for insert a custom color (hex value).

Thanks for your great work!

**Comment by stefan-niedermann** [comment]
Related to https://github.com/nextcloud/deck/issues/1911 and also here:

**Comment by skjnldsv** [comment]
Yes, this requires fixing in the vue components

**Comment by juliushaertl** [comment]
Yep, closing as a duplicate of https://github.com/nextcloud/deck/issues/1911
