### ISSUE TITLE
Don't send the board owner a notification when the board was shared with a group

### ISSUE THREAD

**Issue by schiessle** [nextcloud/deck#2895]
I shared a board with a group I'm a member of. Directly after sharing I get a message that a board was shared with me:

![image](https://user-images.githubusercontent.com/1589737/111436831-b61d7400-8702-11eb-8451-4ba4df3e0bdf.png)

I'm as the one who shared the board shouldn't get a notification.

**Comment by juliushaertl** [comment]
Was fixed in [`8d05926` (#2950)](https://github.com/nextcloud/deck/pull/2950/commits/8d05926ea5b4f1f3d136c1ec4843a15c6bc2afbc)
