### ISSUE TITLE
Ability to quick add/remove tags from board view

### ISSUE THREAD

**Issue by l-mb** [nextcloud/deck#2899]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Using labels to structure and organize my boards, I find the workflow of having to open a card's details, go to the `Details` tab, click on the `Assign a tag to this card`, and click on a tag. This is not very efficient when entering and organizing many cards.

**Describe the solution you'd like**

I'd like to be able to more quickly add/remove a tag.

My suggestion would be that, when the mouse is hovering above a card, we can hit a number key that'd assign (or, if already assigned, remove it) one of the top 0-9 labels.

**Additional context**

This is somewhat similar in how Trello does it.

**Comment by stefan-niedermann** [comment]
A redesign is already in progress and the tags will be more trello like reachable without switching the tab in the future :)
