### ISSUE TITLE
Boards do not auto-size to contents

### ISSUE THREAD

**Issue by rebeccaformfx** [nextcloud/deck#290]
Experimenting with the UI with my build and it seems as though the two boards auto-size to one another (I am styling the `.stack` element in my designs with a lighter grey color)  This seems like a sub-par visual experience.  The boards should wrap to their own contents and create a skyline of different heights.
  
<img width="731" alt="screen shot 2017-08-20 at 10 24 27 pm" src="https://user-images.githubusercontent.com/25747014/29501517-eb879bae-85f6-11e7-957e-774799109bb5.png">

### Steps to reproduce
1.  Create two different Kanban boards
2.  Add inequal numbers of tickets
3.  Both boards have the same height wrapper

### Expected behaviour
The height of each board should be dependent on its contents

### Actual behaviour
Each board is the same height 

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by juliushaertl** [comment]
@rebeccaformfx Yes, that makes sense to me. If you want to open a pull request to fix, that would be awesome.
