### ISSUE TITLE
option to show archived boards is missing

### ISSUE THREAD

**Issue by ManfredWisniewski** [nextcloud/deck#2914]
### Steps to reproduce
- open nextcloud "deck" app and look for a way to show archived boards
- archived boards are not deleted, it is still possible to link to them using the "link card" option

### Expected behaviour
- have an option in the deck settings (bottom left) to show archived boards
- hopefully have the possibility to un-archive and delete archived boards

### Actual behaviour
no option to show archived boards is available (or findable)

## Server configuration detail

**Operating system:** Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 8.0.22

**PHP version:** 

7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 20.0.8 - 20.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** nextcloud.com

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - apporder: 0.12.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.2.0
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.5.1
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.5
 - drawio: 1.0.0
 - event_update_notification: 1.2.0
 - external: 3.7.2
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_markdown: 2.3.3
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.2.2
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - rainloop: 7.1.2
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.6
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_saml: 3.2.2
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - announcementcenter
 - encryption
 - files_external
 - keeweb
 - sociallogin
 - support
 - user_ldap
 - wopi

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "office.witconsult.de",
        "cloud.witconsult.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.8.1",
    "overwrite.cli.url": "https:\/\/office.witconsult.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "defaultapp": "apporder",
    "app_install_overwrite": [
        "keeweb",
        "user_saml"
    ],
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "loglevel": 2,
    "skeletondirectory": "\/var\/www\/html\/witcloud\/data\/auth0|5f4e49141130850068178f24\/files\/witransit\/nextcloud-skeleton",
    "default_language": "de_DE",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Chrome current version

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by dodedodo** [comment]
@ManfredWisniewski For me (nc 20, deck 1.2.5) there is an 'archived boards' list. If you click it it will show your non-archived boards (bug?). However, if you click the little arrow to the left, it will expand to show a list of archived boards. 

![image](https://user-images.githubusercontent.com/3252036/112454714-44c06f80-8d59-11eb-9df8-5e20293f6139.png)

**Comment by ManfredWisniewski** [comment]
Thank you very much for showing me that - I actually had a missunderstanding and this issue is completely wrong.
The real issue is that I  can still see deleted boards when I use the "link card" functionality. I assumed that this was because I had archived them and could not see the archive any more. When in fact I had deleted them which is why the archive wasn't showing up anymore.

**Comment by ManfredWisniewski** [comment]
I will repost this issue as "deleted boards still available when using the link card" function. Thanks for reminding me how the archive works because I had forgotten. :) 👍

**Comment by stefan-niedermann** [comment]
@ManfredWisniewski see https://github.com/nextcloud/deck/issues/2198 before opening a new issue please.

**Comment by dodedodo** [comment]
I'd argue that clicking 'Archived boards' (not the arrow) should show a list of archived boards. Right now it shows your non-archived boards when you click on the 'archived boards' text in the sidebar. Like this:


![image](https://user-images.githubusercontent.com/3252036/112637422-70695580-8e3e-11eb-9a20-1ba3ad43ba71.png)

If you don't click the arrow you cannot actually use that sidebar entry. The arrow is only visible when hovering the sidebar entry.

Maybe this is a bug after all?

**Comment by ManfredWisniewski** [comment]
@dodedodo what you say is true - but for me a very minor issue :) I am just glad it works

@stefan-niedermann thanks! yes that is exactly my issue
