### ISSUE TITLE
Last modified & created date incorrect in Task view

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/deck#2915]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When viewing a task of the Deck in the Task app the dates are not shown when hovering over the info button in the sidebar.

Maybe related to https://github.com/nextcloud/deck/issues/2212 or https://github.com/nextcloud/deck/issues/2276. 

**To Reproduce**
1. Go to the task app
2. Click on one of the task lists that are created by Deck
3. Click on one of the tasks
4. When hovering over the info sign in the sidebar, the error is shown (see screenshot)

**Expected behavior**
Correct dates are shown and not an `Invalid date` message.

**Screenshots**
![image](https://user-images.githubusercontent.com/20948931/112604909-9d057900-8e0e-11eb-8528-ec405635cfef.png)

**Client details:**
 - OS: Ubuntu 20.10
 - Browser: checked on Firefox 87.0 and Chromium 89.0.4389.90
 - Device: Laptop

<details>
<summary>Server details</summary>

**Operating system**: Ubuntu 20.04.2 LTS

**Web server:** nginx/1.18.0

**PHP version:** PHP 7.4.3

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.2.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.5
  - drawio: 1.0.0
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.0
  - integration_gitlab: 1.0.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.9.4
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 1.7.5
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - spreed
  - survey_client
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mysql.utf8mb4": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "default_language": "de_DE",
        "default_locale": "de",
        "skeletondirectory": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "drawio"
        ],
        "mail_smtpsecure": "tls",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        }
    }
}

```

**Are you using an external user-backend, if yes which one:** ActiveDirectory

</details>

**Comment by dodedodo** [comment]
It's showing the correct date for me. Nc 20 and deck v1.2.5.

**Comment by q-wertz** [comment]
Ok. Strange. For me it is wrong in all of the Deck Task lists and shown correctly in the "real" task lists.

Same on my Nextcloud Server at home.

Do you maybe have a different Task version?

**Comment by dodedodo** [comment]
I'm sorry should've mentioned that. My tasks is version v0.13.6. I'm running nextcloud inside docker with MariaDB (10.5.8). 

I'm not certain on how dates are stored in nextcloud/deck/tasks, but I imagine it's the database's datetime datatype. What database are you using?

**Comment by q-wertz** [comment]
```
user@server:~$ mysql -V
mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
Not sure if this is the correct table but `last_modified` and `created_at` do not seem to have the correct datatype (`duedate` in contrast is correct)
```
MariaDB [nextcloud]> show fields from oc_deck_cards;
+------------------+---------------------+------+-----+---------+----------------+
| Field            | Type                | Null | Key | Default | Extra          |
+------------------+---------------------+------+-----+---------+----------------+
| id               | int(11)             | NO   | PRI | NULL    | auto_increment |
| title            | varchar(255)        | NO   |     | NULL    |                |
| description      | longtext            | YES  |     | NULL    |                |
| description_prev | longtext            | YES  |     | NULL    |                |
| stack_id         | bigint(20)          | NO   | MUL | NULL    |                |
| type             | varchar(64)         | NO   |     | plain   |                |
| last_modified    | int(10) unsigned    | YES  |     | 0       |                |
| last_editor      | varchar(64)         | YES  |     | NULL    |                |
| created_at       | int(10) unsigned    | YES  |     | 0       |                |
| owner            | varchar(64)         | NO   |     | NULL    |                |
| order            | bigint(20)          | YES  | MUL | NULL    |                |
| archived         | tinyint(1)          | YES  | MUL | 0       |                |
| duedate          | datetime            | YES  |     | NULL    |                |
| notified         | tinyint(1)          | YES  |     | 0       |                |
| deleted_at       | bigint(20) unsigned | YES  |     | 0       |                |
+------------------+---------------------+------+-----+---------+----------------+

```

**Comment by dodedodo** [comment]
I just double-checked, you've got the same schema as me. And again, the dates are showing just fine for me. The last_modified seems to be an epoch timestamp so it shouldn't be susceptible to quirks in notations and such due to locale (my initial thought). 

Try going through the Nextcloud and PHP logs again. I don't know how to help any further.

**Comment by q-wertz** [comment]
The server logs seem fine.

One thing I noticed in the browser is that when I hover over the icon 
`jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.` is thrown.

But probably not related. I will try to find something and come back.

**Comment by ToppDev** [comment]
I have the same Problem. And I am on
- NC 21.0.0 (manual install)
- Deck 1.3.1
- Tasks 0.13.6
- OS: FreeBSD 12.2-RELEASE-p3 TrueNAS
- MariaDB: Ver 15.1 Distrib 10.4.14-MariaDB

**Comment by q-wertz** [comment]
Can it be an issue due to 12h/24h format or something like that?

should be 24h format and dd/mm/yyyy in my case.

**Comment by q-wertz** [comment]
The information button has been removed from Tasks in the meantime. The subheader where in the normal Lists appears the last modified date is not available for the Deck tasklists
