### ISSUE TITLE
Where to find the actual Database Structure?

### ISSUE THREAD

**Issue by flyinghuman** [nextcloud/deck#2926]
Hello, we seem to have different issues because of many upgrades and failed Database migrations (e.g. Console throws an Error 500 when setting an due Date with the latest version in Nextcloud 21). 

For resolving these issues we would like to compare our Database Structure to the actual one on github but we can't find it. Where in the Code can we look to see the actual DB Scheme?

https://github.com/nextcloud/deck/blob/master/docs/structure.md seen to be outdated too.

Thanks!

**Comment by stefan-niedermann** [comment]
I'm not entirely sure (not a developer of the app), but maybe the database is created directly by the ORM from the [entities](https://github.com/nextcloud/deck/tree/2d10186557026cd13cdf0b622e854b2029695a45/lib/Db) and only adjusted by those [migrations](https://github.com/nextcloud/deck/tree/2d10186557026cd13cdf0b622e854b2029695a45/lib/Migration)? :thinking:

**Comment by flyinghuman** [comment]
> I'm not entirely sure (not a developer of the app), but maybe the database is created directly by the ORM from the [entities](https://github.com/nextcloud/deck/tree/2d10186557026cd13cdf0b622e854b2029695a45/lib/Db) and only adjusted by those [migrations](https://github.com/nextcloud/deck/tree/2d10186557026cd13cdf0b622e854b2029695a45/lib/Migration)? 🤔

it seems so. So i have to setup a new instance and check the databases afterwards seems actually the fastest option.

**Comment by juliushaertl** [comment]
The schema is defined in the migrations and the tables are created and modified step by step to reach the current state, so there is no full reference of it in once place except that you could have a look at the create table output of an existing installation. For the issues you encounter please open dedicated issues with the specific errors. 

For migration issues it might make sense to check if all migration have been executed properly by running `occ migrations:status deck`

**Comment by flyinghuman** [comment]
> The schema is defined in the migrations and the tables are created and modified step by step to reach the current state, so there is no full reference of it in once place except that you could have a look at the create table output of an existing installation. For the issues you encounter please open dedicated issues with the specific errors.
> 
> For migration issues it might make sense to check if all migration have been executed properly by running `occ migrations:status deck`

okay, thanks.
