### ISSUE TITLE
 500 Server Error  disclosing the Database table query information

### ISSUE THREAD

**Issue by ysthas** [nextcloud/deck#2948]
**Describe the bug**
The application throws 500 error that disclose the database table query information and full path of the application when More than 100 character string is entered in the title, color parameter.

**To Reproduce**
1. Login and Go to https://mycloud.domain.com/apps/deck/
2. Click on 'add boards' enter name string longer than 100 characters
3. Right-click and open inspect element and go to network tab
3. Send the request and observe the response.

**Expected behavior**
Error message without query information and internal path.

**Screenshots**
![information dis](https://user-images.githubusercontent.com/32809342/113822167-183e2780-974b-11eb-8a13-475a0108ff47.JPG)

<details>
<summary>Server details</summary>

**Operating system**:Linux

**Web server:**Nginx

**Nextcloud version:** (see Nextcloud admin page) No access

**Signing status:**User

</details>

**Comment by stefan-niedermann** [comment]
This looks like a duplicate (or reappearance) of #1923

Please post the output of `occ migrations:status deck`. Can you also please post version information of the very first information that you installed (or at least the first one you remember)?

**Comment by juliushaertl** [comment]
Please fill out the issue template so we an get a better idea about your configuration and versions in use.

**Comment by dodedodo** [comment]
I cannot reproduce ysthas's bug. My deck simply does nothing when I try to create a board name over 100 characters long. 

This is on nextcloud 20 with deck v1.2.5 (not the most recent).

**Comment by juliushaertl** [comment]
The trace might actually come from having debug mode enabled, which you shouldn't have in production.

**Comment by ysthas** [comment]
> This looks like a duplicate (or reappearance) of #1923
> 
> Please post the output of `occ migrations:status deck`. Can you also please post version information of the very first information that you installed (or at least the first one you remember)?

Hi! its been late due to internal process, it is seen in the "Next Cloud: 21.0.0" version.

**Comment by juliushaertl** [comment]
Shoud have been fixed long time ago by https://github.com/nextcloud/deck/pull/3384
