### ISSUE TITLE
Cannot share a deck with a group

### ISSUE THREAD

**Issue by tbalthazar** [nextcloud/deck#295]
### Steps to reproduce
1. Create a deck
2. Click on details → share
3. From the share list, select a group

### Expected behaviour
The deck should be shared with all members of the selected group, a group icon should be shown.

### Actual behaviour
No group icon is shown.
![deck-sharing](https://user-images.githubusercontent.com/3520/30161502-1fef3022-93d1-11e7-9b2b-6a9e369a68a7.png)

People in the group see the boards in the left sidebar, but when they click on it, they see "error occured"
![deck-error-occured](https://user-images.githubusercontent.com/3520/30161553-5a50ad40-93d1-11e7-985d-187f0f0157aa.png)

### General server configuration

**Operating system:** Linux web 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64

**Web server:** nginx/1.12.0 (fpm-fcgi)

**Database:** pgsql PostgreSQL 9.4.13 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit

**PHP version:** 7.0.18-1~dotdeb+8.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - cgi-fcgi
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imagick
 - intl
 - json
 - exif
 - mcrypt
 - pdo_pgsql
 - pgsql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 11.0.X (latest 11.X version)

**Where did you install Nextcloud from:**  manually

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.2
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.4
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - audioplayer
 - encryption
 - files_external
 - passman
 - passwords
 - richdocuments
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "oclkocba418a",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "files.neutrinet.be"
    ],
    "datadirectory": "\/var\/www\/files-neutrinet-be\/data",
    "overwrite.cli.url": "https:\/\/files.neutrinet.be",
    "dbtype": "pgsql",
    "version": "12.0.2.0",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "updater.release.channel": "stable",
    "maintenance": false,
    "loglevel": 2,
    "data-fingerprint": "8f747e72eb1d8ae9fbd532a528c15c3a",
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "theme": ""
}
```
</details>

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by juliushaertl** [comment]
@tbalthazar Thanks for your report. I cannot reproduce this issue here. Which version of Deck are you running? Are there any errors in the browser console? Also the output of the network tab in your browsers developer tools would help here.

**Comment by tbalthazar** [comment]
@juliushaertl I use Deck 0.2.2.
The JS console just says:
`JQMIGRATE: Migrate is installed, version 1.4.0`. I exported the Network console as a HAR file, hope that helps.
[Archive 17-09-07 13-55-17.har.tar.gz](https://github.com/nextcloud/deck/files/1284556/Archive.17-09-07.13-55-17.har.tar.gz)

Please let me know if you need anything else.

**Comment by tbalthazar** [comment]
So in my console, there's not much to see since. I can see the decks (since I created them I guess).

Here are screenshots of the console of a coworker who cannot see the decks.
![error-2](https://user-images.githubusercontent.com/3520/30163011-7d3af378-93d7-11e7-9bfa-43eb860ea468.png)
![error-1](https://user-images.githubusercontent.com/3520/30163010-7d37ccde-93d7-11e7-9207-c44f29f39a47.png)

**Comment by juliushaertl** [comment]
@tbalthazar Thanks. I could reproduce this and it is only related to instances using a postgresql database. I've created a patch to fix this at https://github.com/nextcloud/deck/pull/296. It would be great if you could help and test it.

**Comment by tbalthazar** [comment]
@juliushaertl Thanks a lot, will give the patch a try later today or tomorrow and ping you with the results!

**Comment by tbalthazar** [comment]
@juliushaertl I followed the [instructions to install with git](https://github.com/nextcloud/deck#install-from-git), as root, I did:
```
# cd nextcloud/apps
# mv deck deck-org
# git clone https://github.com/nextcloud/deck.git
# git checkout fix-numeric-acl-type
# make install-deps
```
got the following errors:
https://gist.github.com/tbalthazar/1debacaa6e6a7ae51729bd0575f01364

npm 5.3.0 is installed.
Did I do something wrong?
Thanks.

**Comment by juliushaertl** [comment]
Looks similar to: https://github.com/sass/node-sass/issues/1847#issuecomment-269846852 

Can you try going to the js directory and run: `npm install --unsafe-perm`. After that run `make` in the deck root.

Otherwise you can also just apply the pull request patch to the tarball from the app store, since it is an PHP-only change: https://patch-diff.githubusercontent.com/raw/nextcloud/deck/pull/296.patch That way you don't need to do all the javascript build stuff.

**Comment by tbalthazar** [comment]
@juliushaertl I manually applied the patch and it works, thanks a lot for your super quick answer and awesome work!

**Comment by albjeremias** [comment]
I'm using deck 1.16.3 with NC 32 and I can't add groups to any card deck. 
somehow i feel that this bug might be related with this one on the calendar of nextcloud?
https://github.com/nextcloud/calendar/issues/7924#issuecomment-3812447696
