### ISSUE TITLE
Bord details broken

### ISSUE THREAD

**Issue by jeltevdw** [nextcloud/deck#2951]
**Describe the bug**
Its no longer possible to open the bord details. It keeps on loading. Issue is only seen after upgrading from v1.2.5 to v1.2.6

**To Reproduce**

1. Login and Go to https://mycloud.domain.com/apps/deck/
2. Click on the 3 dots on the right of a bord name and click on 'Bord details'
3. Bord details are not loaded, screen is stuck at 'loading'

**Expected behavior**
Bord details are shown

**Screenshots**

**Client details:**
 - OS: Mac OS 11.2.3
 - Browser: Safari & Firefox (tested on both)
 - Version : Safari on 14.0.3 & Firefox on 87.0 
 - Device: MacBook Pro

**Nextcloud version:**
- Nextcloud version: 20.0.8
- Deck version: v1.2.6 

Also reproduced on:
- Nextcloud version: 21.0.0
- Deck version: v1.3.2 

#### Browser log
```
[Error] Failed to load resource: the server responded with a status of 400 () (NaN, line 0)
[Error] Error: Request failed with status code 400
	(anonieme functie) (main.js:2203:21988)
	c (collections.js:459:33325)
	(anonieme functie) (collections.js:459:33075)
	ln (main.js:2203:20121)
	s (main.js:2203:22212)
	promiseReactionJob
[Error] TypeError: null is not an object (evaluating 'this.board.id') — main.js:2203:21378
	(anonieme functie) (main.js:2257:623)
	Gt (main.js:915:11477)
	$t (main.js:915:11191)
	(anonieme functie) (main.js:915:35346)
	r (main.js:915:64449)
	(anonieme functie) (main.js:915:26615)
	(anonieme functie) (main.js:915:27498)
	un (main.js:915:25606)
	(anonieme functie) (main.js:915:12298)
	Zt (main.js:915:11738)
	promiseReactionJob

**Comment by juliushaertl** [comment]
> [Error] Failed to load resource: the server responded with a status of 400 () (NaN, line 0)

Anything in your Nextcloud log about that?

**Comment by jeltevdw** [comment]
Hi,

Yes sorry, I should have included the nextcloud.log as well. Log is taken on NextCloud 21.0.0 with app version v1.3.2 as this is my current test environment. I did already rollback on my production environment on NextCloud 20.0.8.

Issue is that its sending an Ajax request without Board Id present:

**Ajax call**
URL: https://cloud.test.spotontoneel.be/apps/deck/boards/**NaN**
Status: 400
Initiator: 
main.js:954:103413

**Nextcloud.log**

{"reqId":"rADSqGwVc67PWkTUfGwj","level":3,"time":"2021-04-08T06:17:40+00:00","remoteAddr":"x.x.x.x","user":"xxxx","app":"deck","method":"GET","url":"/apps/deck/boards/NaN","message":{"Exception":"OCA\\Deck\\BadRequestException","Message":"board id must be a number","Code":0,"Trace":[{"file":"/opt/nextcloud-test/apps/deck/lib/Controller/BoardController.php","line":57,"function":"find","class":"OCA\\Deck\\Service\\BoardService","type":"->","args":["NaN"]},{"file":"/opt/nextcloud-test/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"read","class":"OCA\\Deck\\Controller\\BoardController","type":"->","args":["NaN"]},{"file":"/opt/nextcloud-test/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\BoardController"},"read"]},{"file":"/opt/nextcloud-test/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\BoardController"},"read"]},{"file":"/opt/nextcloud-test/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\BoardController","read",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"boardId":"NaN","_route":"deck.board.read"}]},{"file":"/opt/nextcloud-test/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/deck/boards/NaN"]},{"file":"/opt/nextcloud-test/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/opt/nextcloud-test/apps/deck/lib/Service/BoardService.php","Line":172,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"21.0.0.18"}

**Comment by woolmilkpigs** [comment]
Having the same issue on NextCloud 21.0.0 with app version v1.3.2.

**Comment by z0rgster** [comment]
Can confirm this Issue for 1.3.2.
I updated from 1.3.1 this morning.

**Comment by osm-frasch** [comment]
Confirm. I can see the same problem here. 
Since yesterday's update to version 1.2.6, no one in our education center can access the deck details. 
Nextcloud version 20.0.8 (PhP: Version: 7.3.16). Testet with Browsers Firefox/Chrome (latest Version) on Win10 and Linux Systems

**Comment by Woody2209** [comment]
same Issue Nextcloud 21.0.1 Deck 1.3.2

**Comment by cabelodomato** [comment]
> 
> 
> same Issue Nextcloud 21.0.1 Deck 1.3.2

Same same here.

**Comment by stefan-niedermann** [comment]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please **don't comment** if you have no relevant information (like new version constellations) to add. (Everybody gets spammed with E-Mails and the issue will be incredibly hard to read.

**Comment by siripong-t** [comment]
Sadly. I have the same issue and it is quite urgent for me.

**Comment by grinapo** [comment]
Also a surprising workaround: there is an **invisible** icon in the top right corner (next to the +, filter and three dot) which opens the details without problems.
