### ISSUE TITLE
A task/card created from nc-deck works differently then a task created from nc-tasks in iOS reminders.

### ISSUE THREAD

**Issue by GitGramm** [nextcloud/deck#2953]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
A task/card created from nc-deck works differently then a task created from nc-tasks in iOS reminders.
I faced a issue where I cannot change a task created in deck from iOS reminders app.
Tasks created within the task-app can be changed in iOS reminders app and are synced back to NC.
A task/card created from deck does appears in iOS reminders but does sync back.

**To Reproduce**
1. Create a task from nc-tasks
2. Change the task in iOS-reminders
3. Check the correct syncing result in nc-tasks
4. Create a task from nc-deck
5. Change the task in iOS-reminders
6. Changes are not synced back but overwritten with the old values

**Expected behavior**
Same behaviour for tasks created from deck as from tasks

**Client details:**
 - OS: latest iOS 14 (also appears on old iPhone 5 running on iOS 10)
 - Apple iOS reminders app

<details>
<summary>Server details</summary>

**Operating system**:
Ubuntu 20.04 
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 21.0.0

</details>

Thanks,
Kris

**Comment by GitGramm** [comment]
I just stumbled across issue  #2399 maybe its related to it?

**Comment by juliushaertl** [comment]
Yes, the caldav endpoints are read only as of now, so this will require https://github.com/nextcloud/deck/issues/2399 in order to work properly.
