### ISSUE TITLE
question: npm markdown-it plugin install

### ISSUE THREAD

**Issue by lephtHanded** [nextcloud/deck#2954]
question:
(sorry if this isn't the place to put it)
I saw in other issues where users had asked for **markdown-it-xxx-yyy** plugin installed
one of the responses was that the plugin could be installed with __npm__.

i'm using docker, can anyone tell me how i could go about running the ```npm i markdown-it-code-copy``` command, (and where i would run it from?)

thanks

**Comment by juliushaertl** [comment]
You will need to setup a development environment and build the app from source (see the readme file). You can't just install a markdown-it plugin.
