### ISSUE TITLE
Android 1.16.2 client keeps crashing

### ISSUE THREAD

**Issue by ekianjo** [nextcloud/deck#2967]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
I just upgraded from 1.6.1 to 1.6.2 and the client keeps crashing, even upon clean reinstall.

**To Reproduce**
1. Fresh install of 1.6.2
2. Choose account
3. Immediate crash when trying to sync

**Expected behavior**

**Client details:**
 - OS: Android
 - Version 1.16.2 on Android
 - Device: Android 7.0

Server

**Operating system**: Debian Buster

**Web server:** 1.2.6 running 

**Database:** MariaDB

**PHP version:** 7.x

**Nextcloud version:** on 20.0.8 Nextcloud

**Where did you install Nextcloud from:** self install

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

No errors have been found.

**Comment by stefan-niedermann** [comment]
Wrong repository buddy 😉 
https://github.com/stefan-niedermann/nextcloud-deck/issues/930#issuecomment-818025817
