### ISSUE TITLE
Move permission type to integer value

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#297]
The backend code already uses the following integer types for board permissions:

```
	const PERMISSION_TYPE_USER = 0;
	const PERMISSION_TYPE_GROUP = 1;
```

The frontend code should be migrated to use them as well instead of the current strings "user" and "group".

**Comment by adioe3** [comment]
I'd like to take this

**Comment by juliushaertl** [comment]
@adioe3 Great to hear that, feel free to ask if you have any questions when implementing.
