### ISSUE TITLE
card projects disappear, recombine, duplicate or generally get messed up

### ISSUE THREAD

**Issue by grinapo** [nextcloud/deck#2970]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Card project assignments (or call it linking) get messed up all the time. Projects simply disappear, or get duplicated, or pop up on a different card. May re-appear on full reload - or not.

**To Reproduce**
1. create two boards
2. create cards in one
3. assign various project types to cards, one at a a time
4. click on cards: projects may or may not be there
5. select other board
6. get back to the first board, cards now lose their projects with high probability

**Expected behavior**
Projects stay the same when assigned.

**Screenshots**
![2021-04-13_13-43](https://user-images.githubusercontent.com/1056054/114547147-5ca35900-9c5e-11eb-8042-4d5a1b73624e.png)

**Client details:**
 - OS: linux
 - Browser firefox
 - Version NC 21.0.1.1, deck 1.3.2
 - Device: desktop 
<details>
<summary>Server details</summary>

**Operating system**: 
debian

**Web server:** 
nginx

**Database:** 
mariadb 10.3.27

**PHP version:**
7.3.27-1~deb10u1

**Nextcloud version:**
21.0.1.1

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
nothing
```

#### Browser log
`.../collaboration/?format=json` is retrieved when opening the deck. it looks to be in good format but contains random order or nothing.

</details>

**Comment by grinapo** [comment]
I went away, clicked in other decks, came back and it's now:
![2021-04-13_14-03](https://user-images.githubusercontent.com/1056054/114549306-20252c80-9c61-11eb-8ec8-fad8457bf4ec.png)

**Comment by varac** [comment]
I also experience duplicate cards. When I'm offline and add a card, it will appear 3 times after syncing when online again.

**Comment by juliushaertl** [comment]
As the projects feature is superseded by related resources since Nextcloud 25 there are no plans to further work on this. As long as the feature is still there anyone is of course welcome to provide fixes through pull requests but I consider this part no longer maintained.

https://github.com/nextcloud/server/blob/stable27/config/config.sample.php#L2347-L2352 
https://github.com/nextcloud/server/issues/28320
