### ISSUE TITLE
White icon on white background

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#2986]
Board details button has a white icon. To see it, you have to move your cursor over the button.

![image](https://user-images.githubusercontent.com/16517095/114843605-47533980-9dda-11eb-9a9d-cff089a6d491.png)

**Comment by juliushaertl** [comment]
Was fixed in the viewer app where the css rule was to wide, so this will be fixed with the next maintenance release of the server.

https://github.com/nextcloud/viewer/pull/856
