### ISSUE TITLE
Nextcloud crashes on new deck update (1.4.0)

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/deck#2987]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
I updated deck from cli after that nextcloud is showing me "server internal error".

**To Reproduce**
1. Update deck from cli
2. visit my nextcloud server

**Expected behavior**
A working updated deck app

**Screenshots**

**Client details:**
 - OS: Fedora workstation 33
 - Browser: Edge  89.0.774.77 
 - Version: 21.0.1
 - Device: desktop
#### Nextcloud log (data/nextcloud.log)
```
 {"reqId":"YHg@5utcFDuVfR1R3DaeVAAAAIU","level":4,"time":"2021-04-15T13:25:58+00:00","remoteAddr":"192.168.15.31","user":"--","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/Anteneh%20Kebere/","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Error: Class 'OCA\\Deck\\AppInfo\\Application20' not found","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"{closure}","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/remote.php","line":76,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/remote.php","line":171,"function":"handleException"}],"File":"/var/www/html/nextcloud/remote.php","Line":74,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/3.1.3stable-Win64 (build 20210218) (Nextcloud)","version":"21.0.1.1","id":"607843ecb219a"}
```

**Comment by juliushaertl** [comment]
`OCA\\Deck\\AppInfo\\Application20` there is no point to that in the code of 1.4.0 anymore, maybe this is some opcache caching issue so I'd suggest to try a restart of the webserver/php-fpm processes to be sure.

**Comment by elhananjair** [comment]
Yeah you're right restarting webserver fixed that, thanks
