### ISSUE TITLE
1.4, An error occurred while searching for Card comments

### ISSUE THREAD

**Issue by gvansanden** [nextcloud/deck#2996]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
After upgrading deck to 1.4 on NC 21, I get that error when searching for anything

**To Reproduce**
click the search icon next to your profile, enter text - > error

**Expected behavior**
search as normal

**Client details:**
 - OS: Ubunu 20.04
 - Version Deck 1.4.0 Nextcloud 21

<details>
<summary>Server details</summary>

**Operating system**:
Ubuntu 20.04.2 LTS

**Web server:**
Apache2

**Database:**
Postgres 12

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Where did you install Nextcloud from:**
tar-gz

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.0
  - circles: 0.21.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - deck: 1.4.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - notify_push: 0.1.7
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - passwords: 2021.4.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - socialsharing_email: 2.2.0
  - spreed: 11.1.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - dashboard
  - encryption
  - files_external
**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.wouters-hendrix.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.wouters-hendrix.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 5
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "trashbin_retention_obligation": "auto, 30",
        "maintenance": false,
        "app_install_overwrite": [
            "spreed"
        ],
        "logtimezone": "Europe\/Brussels",
        "log_rotate_size": 209715200,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "BE"
    }
}

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
AD

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
{"reqId":"g3hmD0VAv3uYSOhIJekn","level":3,"time":"2021-04-16T21:36:12+02:00","remoteAddr":"85.234.217.236","user":"wh","app":"no app in context","method":"GET","url":"/ocs/v2.php/search/providers/deck-comment/search?term=ds&from=%2Fapps%2Ffiles%2F%3Fdir%3D%2F%26fileid%3D302759","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = integer\nLINE 1: ...c_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\"...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":7,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1728,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},{"__class__":"Doctrine\\DBAL\\Query"}]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1667,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},{"__class__":"Doctrine\\DBAL\\Query"}]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1040,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},"SELECT \"c\".*, \"comments\".\"id\" AS \"comment_id\" FROM \"oc_deck_cards\" \"c\" INNER JOIN \"oc_deck_stacks\" \"s\" ON \"s\".\"id\" = \"c\".\"stack_id\" INNER JOIN \"oc_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\") AND (\"comments\".\"object_type\" = ?) INNER JOIN \"oc_deck_boards\" \"b\" ON \"b\".\"id\" = \"s\".\"board_id\" WHERE (\"s\".\"board_id\" IN (NULL)) AND (\"c\".\"deleted_at\" = ?) AND (\"s\".\"deleted_at\" = ?) AND (\"b\".\"deleted_at\" = ?) AND (\"comments\".\"message\" ILIKE ?) GROUP BY \"comments\".\"id\" ORDER BY \"comments\".\"id\" DESC LIMIT 5",["deckCard",0,0,0,"%ds%"],[2,1,1,1,2]]},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":226,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"c\".*, \"comments\".\"id\" AS \"comment_id\" FROM \"oc_deck_cards\" \"c\" INNER JOIN \"oc_deck_stacks\" \"s\" ON \"s\".\"id\" = \"c\".\"stack_id\" INNER JOIN \"oc_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\") AND (\"comments\".\"object_type\" = ?) INNER JOIN \"oc_deck_boards\" \"b\" ON \"b\".\"id\" = \"s\".\"board_id\" WHERE (\"s\".\"board_id\" IN (NULL)) AND (\"c\".\"deleted_at\" = ?) AND (\"s\".\"deleted_at\" = ?) AND (\"b\".\"deleted_at\" = ?) AND (\"comments\".\"message\" ILIKE ?) GROUP BY \"comments\".\"id\" ORDER BY \"comments\".\"id\" DESC LIMIT 5",["deckCard",0,0,0,"%ds%"],[2,1,1,1,2],null]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":210,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"c\".*, \"comments\".\"id\" AS \"comment_id\" FROM \"oc_deck_cards\" \"c\" INNER JOIN \"oc_deck_stacks\" \"s\" ON \"s\".\"id\" = \"c\".\"stack_id\" INNER JOIN \"oc_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\") AND (\"comments\".\"object_type\" = :dcValue5) INNER JOIN \"oc_deck_boards\" \"b\" ON \"b\".\"id\" = \"s\".\"board_id\" WHERE (\"s\".\"board_id\" IN (:dcValue1)) AND (\"c\".\"deleted_at\" = :dcValue2) AND (\"s\".\"deleted_at\" = :dcValue3) AND (\"b\".\"deleted_at\" = :dcValue4) AND (\"comments\".\"message\" ILIKE :dcValue6) GROUP BY \"comments\".\"id\" ORDER BY \"comments\".\"id\" DESC LIMIT 5",{"dcValue1":[],"dcValue2":0,"dcValue3":0,"dcValue4":0,"dcValue5":"deckCard","dcValue6":"%ds%"},{"dcValue1":101,"dcValue2":1,"dcValue3":1,"dcValue4":1,"dcValue5":2,"dcValue6":2}]},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/deck/lib/Db/CardMapper.php","line":351,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/deck/lib/Service/SearchService.php","line":104,"function":"searchComments","class":"OCA\\Deck\\Db\\CardMapper","type":"->","args":[[],{"__class__":"OCA\\Deck\\Search\\Query\\SearchQuery"},5,null]},{"file":"/var/www/nextcloud/apps/deck/lib/Search/CardCommentProvider.php","line":61,"function":"searchComments","class":"OCA\\Deck\\Service\\SearchService","type":"->","args":["ds",5,null]},{"file":"/var/www/nextcloud/lib/private/Search/SearchComposer.php","line":162,"function":"search","class":"OCA\\Deck\\Search\\CardCommentProvider","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Search\\SearchQuery"}]},{"file":"/var/www/nextcloud/core/Controller/UnifiedSearchController.php","line":110,"function":"search","class":"OC\\Search\\SearchComposer","type":"->","args":[{"__class__":"OC\\User\\User"},"deck-comment",{"__class__":"OC\\Search\\SearchQuery"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"search","class":"OC\\Core\\Controller\\UnifiedSearchController","type":"->","args":["deck-comment","ds",null,null,null,"/apps/files/?dir=/&fileid=302759"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\UnifiedSearchController"},"search"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\UnifiedSearchController"},"search"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\UnifiedSearchController","search",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"providerId":"deck-comment","_route":"ocs.core.UnifiedSearch.search"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/search/providers/deck-comment/search"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php","Line":83,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = integer\nLINE 1: ...c_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\"...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":7,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":84,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::","args":[{"errorInfo":["42883",7,"ERROR:  operator does not exist: character varying = integer\nLINE 1: ...c_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\"...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts."],"__class__":"PDOException"}]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1030,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":226,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"c\".*, \"comments\".\"id\" AS \"comment_id\" FROM \"oc_deck_cards\" \"c\" INNER JOIN \"oc_deck_stacks\" \"s\" ON \"s\".\"id\" = \"c\".\"stack_id\" INNER JOIN \"oc_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\") AND (\"comments\".\"object_type\" = ?) INNER JOIN \"oc_deck_boards\" \"b\" ON \"b\".\"id\" = \"s\".\"board_id\" WHERE (\"s\".\"board_id\" IN (NULL)) AND (\"c\".\"deleted_at\" = ?) AND (\"s\".\"deleted_at\" = ?) AND (\"b\".\"deleted_at\" = ?) AND (\"comments\".\"message\" ILIKE ?) GROUP BY \"comments\".\"id\" ORDER BY \"comments\".\"id\" DESC LIMIT 5",["deckCard",0,0,0,"%ds%"],[2,1,1,1,2],null]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":210,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"c\".*, \"comments\".\"id\" AS \"comment_id\" FROM \"oc_deck_cards\" \"c\" INNER JOIN \"oc_deck_stacks\" \"s\" ON \"s\".\"id\" = \"c\".\"stack_id\" INNER JOIN \"oc_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\") AND (\"comments\".\"object_type\" = :dcValue5) INNER JOIN \"oc_deck_boards\" \"b\" ON \"b\".\"id\" = \"s\".\"board_id\" WHERE (\"s\".\"board_id\" IN (:dcValue1)) AND (\"c\".\"deleted_at\" = :dcValue2) AND (\"s\".\"deleted_at\" = :dcValue3) AND (\"b\".\"deleted_at\" = :dcValue4) AND (\"comments\".\"message\" ILIKE :dcValue6) GROUP BY \"comments\".\"id\" ORDER BY \"comments\".\"id\" DESC LIMIT 5",{"dcValue1":[],"dcValue2":0,"dcValue3":0,"dcValue4":0,"dcValue5":"deckCard","dcValue6":"%ds%"},{"dcValue1":101,"dcValue2":1,"dcValue3":1,"dcValue4":1,"dcValue5":2,"dcValue6":2}]},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/deck/lib/Db/CardMapper.php","line":351,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/deck/lib/Service/SearchService.php","line":104,"function":"searchComments","class":"OCA\\Deck\\Db\\CardMapper","type":"->","args":[[],{"__class__":"OCA\\Deck\\Search\\Query\\SearchQuery"},5,null]},{"file":"/var/www/nextcloud/apps/deck/lib/Search/CardCommentProvider.php","line":61,"function":"searchComments","class":"OCA\\Deck\\Service\\SearchService","type":"->","args":["ds",5,null]},{"file":"/var/www/nextcloud/lib/private/Search/SearchComposer.php","line":162,"function":"search","class":"OCA\\Deck\\Search\\CardCommentProvider","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Search\\SearchQuery"}]},{"file":"/var/www/nextcloud/core/Controller/UnifiedSearchController.php","line":110,"function":"search","class":"OC\\Search\\SearchComposer","type":"->","args":[{"__class__":"OC\\User\\User"},"deck-comment",{"__class__":"OC\\Search\\SearchQuery"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"search","class":"OC\\Core\\Controller\\UnifiedSearchController","type":"->","args":["deck-comment","ds",null,null,null,"/apps/files/?dir=/&fileid=302759"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\UnifiedSearchController"},"search"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\UnifiedSearchController"},"search"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\UnifiedSearchController","search",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"providerId":"deck-comment","_route":"ocs.core.UnifiedSearch.search"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/search/providers/deck-comment/search"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = integer\nLINE 1: ...c_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\"...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":"42883","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1030,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":226,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"c\".*, \"comments\".\"id\" AS \"comment_id\" FROM \"oc_deck_cards\" \"c\" INNER JOIN \"oc_deck_stacks\" \"s\" ON \"s\".\"id\" = \"c\".\"stack_id\" INNER JOIN \"oc_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\") AND (\"comments\".\"object_type\" = ?) INNER JOIN \"oc_deck_boards\" \"b\" ON \"b\".\"id\" = \"s\".\"board_id\" WHERE (\"s\".\"board_id\" IN (NULL)) AND (\"c\".\"deleted_at\" = ?) AND (\"s\".\"deleted_at\" = ?) AND (\"b\".\"deleted_at\" = ?) AND (\"comments\".\"message\" ILIKE ?) GROUP BY \"comments\".\"id\" ORDER BY \"comments\".\"id\" DESC LIMIT 5",["deckCard",0,0,0,"%ds%"],[2,1,1,1,2],null]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":210,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"c\".*, \"comments\".\"id\" AS \"comment_id\" FROM \"oc_deck_cards\" \"c\" INNER JOIN \"oc_deck_stacks\" \"s\" ON \"s\".\"id\" = \"c\".\"stack_id\" INNER JOIN \"oc_comments\" \"comments\" ON (\"comments\".\"object_id\" = \"c\".\"id\") AND (\"comments\".\"object_type\" = :dcValue5) INNER JOIN \"oc_deck_boards\" \"b\" ON \"b\".\"id\" = \"s\".\"board_id\" WHERE (\"s\".\"board_id\" IN (:dcValue1)) AND (\"c\".\"deleted_at\" = :dcValue2) AND (\"s\".\"deleted_at\" = :dcValue3) AND (\"b\".\"deleted_at\" = :dcValue4) AND (\"comments\".\"message\" ILIKE :dcValue6) GROUP BY \"comments\".\"id\" ORDER BY \"comments\".\"id\" DESC LIMIT 5",{"dcValue1":[],"dcValue2":0,"dcValue3":0,"dcValue4":0,"dcValue5":"deckCard","dcValue6":"%ds%"},{"dcValue1":101,"dcValue2":1,"dcValue3":1,"dcValue4":1,"dcValue5":2,"dcValue6":2}]},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/deck/lib/Db/CardMapper.php","line":351,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/deck/lib/Service/SearchService.php","line":104,"function":"searchComments","class":"OCA\\Deck\\Db\\CardMapper","type":"->","args":[[],{"__class__":"OCA\\Deck\\Search\\Query\\SearchQuery"},5,null]},{"file":"/var/www/nextcloud/apps/deck/lib/Search/CardCommentProvider.php","line":61,"function":"searchComments","class":"OCA\\Deck\\Service\\SearchService","type":"->","args":["ds",5,null]},{"file":"/var/www/nextcloud/lib/private/Search/SearchComposer.php","line":162,"function":"search","class":"OCA\\Deck\\Search\\CardCommentProvider","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Search\\SearchQuery"}]},{"file":"/var/www/nextcloud/core/Controller/UnifiedSearchController.php","line":110,"function":"search","class":"OC\\Search\\SearchComposer","type":"->","args":[{"__class__":"OC\\User\\User"},"deck-comment",{"__class__":"OC\\Search\\SearchQuery"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"search","class":"OC\\Core\\Controller\\UnifiedSearchController","type":"->","args":["deck-comment","ds",null,null,null,"/apps/files/?dir=/&fileid=302759"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\UnifiedSearchController"},"search"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\UnifiedSearchController"},"search"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\UnifiedSearchController","search",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"providerId":"deck-comment","_route":"ocs.core.UnifiedSearch.search"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/search/providers/deck-comment/search"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":82}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36","version":"21.0.1.1"}

</details>

**Comment by stefan-niedermann** [comment]
Please use the :mag: search function before opening new issues.

https://github.com/nextcloud/deck/issues/2988
