### ISSUE TITLE
Upload a *.pdf File to Deck / Card / Attachments

### ISSUE THREAD

**Issue by witzker** [nextcloud/deck#2997]
Admin & User1 are in the same group

Cannot open *.pdf file uploaded there from User1 in the Group when logged in as Admin.

I can only open the files that User 1 has uploaded when logged in as User 1!

When I log in as Admin and upload a file User 1 cannot open it.

Hope its clear what I mean!?

**What's wrong?**

It's not possible to work on Nextcloud with this Behaviour!
PLS Help

**Comment by juliushaertl** [comment]
Thanks for your bug report. Please fill out the issue template to provide some more information about your setup and possible errors in the logfiles.

**Comment by witzker** [comment]
Excuse me I'm new with this!
Where to find issue template.
Where to find the mentioned log file.
My installation is on IONOS webspace

Could you reproduce this behavior described ?

**Or Better Other way round!**
What has to be configured where to make this described scenario possible!

Login As Admin:
Go To Deck / create a Card1 / go to Attachments / load up a 1.pdf File

Login as a User:
Go To Deck / go to this Card1 / go to Attachments / click on the 1.pdf File to open it

In my configuration nothing happens.

Pls tell me the necessary configuration steps by step to get this described scenario work.
Maybe I have a misconfiguration!
Or it is bug?

**Comment by witzker** [comment]
`@stefan-niedermann stefan-niedermann added the feature: attachments label 2 days ago`

Does That mean it is a bug?

**Comment by witzker** [comment]
Here is the scenario to be replicated:

Login as Admin
Create a Group → WIR
Create an User → User1
Assign User1 to Group → WIR
Go to Deck
Create a Deck → Nextcloud
Share it with Group → WIR
Go to Card → Details
Go to → Attachments
Click → Share from Files
Navigate to Documents
Choose → Nextcloud flyer.pdf
Click on the file just shared
**=> Opens up = OK**

Open Nextcloud in another Browser
login as User1
Go to → Deck
Choose → Card1 → Details → Attachments
The file: Nextcloud flyer.pdf can be seen
Click on the file to open!
**=> NOTHING Happens!**

BUG? or Misconfiguration?

Can You Pls. be so kind and follow this scenario on Your Nextcloud and comment?
THX

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/deck/pull/3038 Testing and review is very welcome

**Comment by witzker** [comment]
Can you tell me when will it be published,
to be able to work more productive?

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/deck/releases/tag/v1.4.2
