### ISSUE TITLE
Option to Display Board in a Table View

### ISSUE THREAD

**Issue by Tuxedo94** [nextcloud/deck#3013]
**Problem:**
After some time, the board gets overloaded with tasks and it looks clogged with different cards, because the cards naturally take a lot of space:
![Deck](https://user-images.githubusercontent.com/33806755/115847482-4dbd6300-a423-11eb-9439-9775ff525af2.PNG)

**Suggestion:**
Providing an option to switch to a table view of the cards (e.g. like Notion has it, see screenshot). This way we have a database-like table that include the information with a good overview. **Note**: Screenshot does not reflect the information in the first screenshot!
![Table](https://user-images.githubusercontent.com/33806755/115847455-48601880-a423-11eb-90b5-71a39d096131.PNG)

Best regards,
Tuxedo94

**Comment by stefan-niedermann** [comment]
Not directly a solution for this issue but have you tried the [Tasks](https://apps.nextcloud.com/apps/tasks) integration? As far as i know, write access is still missing, but that's [another issue](https://github.com/nextcloud/deck/issues/2399). The described view is already pretty close to what you proposed:
![image](https://user-images.githubusercontent.com/4741199/115854241-56fdfe00-a42a-11eb-9274-f8774f11f219.png)

**Comment by Tuxedo94** [comment]
> Not directly a solution for this issue but have you tried the [Tasks](https://apps.nextcloud.com/apps/tasks) integration? As far as i know, write access is still missing, but that's [another issue](https://github.com/nextcloud/deck/issues/2399). The described view is already pretty close to what you proposed:
> ![image](https://user-images.githubusercontent.com/4741199/115854241-56fdfe00-a42a-11eb-9274-f8774f11f219.png)

I tried the tasks integration, and I liked it. But I really like all the features of Nextcloud Deck to attach files, make comments, assign the tasks, etc.

In my honest opinion, the table view option would enhance Nexcloud Desk a lot. Because you have the Board view and also table view when you need a better overview of all the tasks. 

@stefan-niedermann: What are your views on this?

**Comment by stefan-niedermann** [comment]
You might have misunderstood me. The Tasks app will display also Deck boards, so you have *one* data pot. You can use the Deck app for your daily work and attach files to the cards etc. and if you need an overview, you can open the Tasks app which will display exactly the cards which you just created in the Deck app.

Therfore my opinion: The Tasks app already provides another kind of view for the same data that you entered in Deck (though write support will obly be available in the future). No need to do the work twice and implement the same stuff again and again. The integration makes it possible to wor with the same data from two different views 🙂

**Comment by Tuxedo94** [comment]
Yes, I have misunderstood you. It is a great integration indeed, the overview is better in the tasks integration. Obviously, an integrated version inside the Nextcloud Deck app would be the best solution. But what is good in the Nextcloud Tasks app, is the sort option. But I am missing here the filter option. And yes, write access would me amazing as well. I will for sure use the Nextcloud Tasks integration along-side the Nextcloud Deck. Cant wait for the write access :) Thank you for the information.

**Comment by Tuxedo94** [comment]
What happens with this issue now? I mean, it would be still nice if the table view will be directly integrated into Nextcloud Deck.

**Comment by stefan-niedermann** [comment]
I am not a developer or maintainer od the Deck server app,, so i just put my opinion here like you and wr will have to wait until @juliushaertl approves or declines it. :)

**Comment by jakobroehrl** [comment]
I like the notion view a lot, too. And I see the problem with the overloaded view. 
Started to implement a list view some month ago: https://github.com/nextcloud/deck/pull/1315
But we decided to not go this way in favour of the [Task integration](https://github.com/nextcloud/deck/issues/3013#issuecomment-825544153)

I would love to see a list/table view in deck.

**Comment by Tuxedo94** [comment]
In my honest opinion, it is not so convenient to install another Nextcloud app to just have the other view and it should be integrated into Nextcloud Desk itself. This is more user-friendly. I thought about to implement the table view by myself, this would be my first time ever I am contributing to an open source project. And also my first time using Vue.js. From what I understood, @juliushaertl is responsible to confirm if the table view option will be added as a feature or not.

**Comment by jakobroehrl** [comment]
Talked to Julius: We don't want to implement another view. Instead of we want to go in this direction:
https://github.com/nextcloud/deck/issues/2399
Is it ok, if we close this issue?

**Comment by Tuxedo94** [comment]
If you decided not to implement a table view at all, I respect that. Yes, if the tasks integration will have the write access it is very helpful. One thing I can suggest is, also to have the filter option in the tasks integration.

**Comment by stefan-niedermann** [comment]
> also to have the filter option in the tasks integration.

This will be something to request in [the repository of the tasks app](https://github.com/nextcloud/tasks/issues/new) then 🙂
