### ISSUE TITLE
Wording in Upcoming cards view

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/deck#3035]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
In the Upcoming cards view `This week` is one of the columns but it shows the cards of the next seven days.

**Expected behavior**
Column should be named `Next seven days` (In the app it is like this (at least in german))

**Screenshots**
![image](https://user-images.githubusercontent.com/20948931/116779413-df515400-aa65-11eb-8c15-171b3557e4e5.png)

**NC Talk Version**
1.2.7

**Comment by q-wertz** [comment]
This feature request is still valid in my opinion

**Comment by juliushaertl** [comment]
Not sure why the stale not is becoming active again, I thought I removed that one. Let me check that again

**Comment by tomdereub** [comment]
I think it would be nice to be able to freely configure the columns, like said here : https://github.com/nextcloud/deck/issues/2349. It would resolve this issue too.

**Comment by q-wertz** [comment]
I would like to open a PR to fix this but need input.

In my opinion there are (at least) two ways to solve this:
1. Change wording and variable names from everything like "this week" to "next seven days" or similar
2. Implement the sorting in a way that only cards are listed that are for this week 
    1. Differ between week starting monday and sunday?
    2. Only show "workdays"?

Input is welcome.

**Comment by stefan-niedermann** [comment]
At the Deck Android app we chose solution 1 😉
