### ISSUE TITLE
Error Deck Call to a member function isLevel() on null

### ISSUE THREAD

**Issue by Steg1971** [nextcloud/deck#3052]
After a Deck update up to version 1.4.2 all boards are visible, but cannot be opened.

<details>
**OS Version**:
Debian GNU/Linux 10 (buster)
**Web server:**
Server version: Apache/2.4.38 (Debian)
Server built:   2020-08-25T20:08:29
**Database:**
Your MariaDB connection id is 19169
Server version: 10.3.27-MariaDB-0+deb10u1-log Debian 10

**PHP version:**
PHP 8.0.5, bat with PHP7.3 or 7.4 the situation does not change.
**Nextcloud version:** 
Nextcloud 21.0.1
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
No errors have been found.
```

**List of activated apps:**

```
- accessibility: 1.7.0
  - activity: 2.14.3
  - audioplayer: 3.1.0
  - circles: 0.21.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - deck: 1.4.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 6.3.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.1.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - user_saml: 4.1.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0

```

**Nextcloud configuration:**
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xcloud.schleith-gruppe.de",
            "xcloud.intra.schleith.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "http:\/\/xcloud.schleith-gruppe.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "logtimezone": "Europe\/Berlin",
        "theme": "",
        "default_language": "de_DE",
        "default_phone_region": "DE",
        "force_locale": "de_DE",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "onlyoffice": {
            "verify_peer_off": true
        },
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "onlyoffice"
        ]
    }

```

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```

Error | deck | Error: Call to a member function isLevel() on null
-- | -- | --
1.	/var/www/nextcloud/apps/circles/lib/Api/v1/Circles.php - line 265: 
OCA\Circles\Service\CirclesService->detailsCircle()
2.	/var/www/nextcloud/apps/deck/lib/Db/BoardMapper.php - line 270: 
OCA\Circles\Api\v1\Circles::detailsCircle()
3.	/var/www/nextcloud/apps/deck/lib/Db/RelationalEntity.php - line 117: 
OCA\Deck\Db\BoardMapper->OCA\Deck\Db\{closure}("*** sensiti ... *")
4.	/var/www/nextcloud/apps/deck/lib/Db/BoardMapper.php - line 281: 
OCA\Deck\Db\RelationalEntity->resolveRelation()
5.	/var/www/nextcloud/apps/deck/lib/Service/BoardService.php - line 183: 
OCA\Deck\Db\BoardMapper->mapAcl()
6.	/var/www/nextcloud/apps/deck/lib/Controller/BoardController.php - line 57: 
OCA\Deck\Service\BoardService->find()
7.	/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218: 
OCA\Deck\Controller\BoardController->read()
8.	/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127: 
OC\AppFramework\Http\Dispatcher->executeController()
9.	/var/www/nextcloud/lib/private/AppFramework/App.php - line 157: 
OC\AppFramework\Http\Dispatcher->dispatch()
10.	/var/www/nextcloud/lib/private/Route/Router.php - line 302: 
OC\AppFramework\App::main()
11.	/var/www/nextcloud/lib/base.php - line 993: 
OC\Route\Router->match()
12.	/var/www/nextcloud/index.php - line 37: 
OC::handleRequest()
```

</details>

**Comment by juliushaertl** [comment]
I also cannot reproduce this. Since the version reported is quite old, please try if this is still an issue on the latest and don't hesitate to reopen if it is still an issue.
