### ISSUE TITLE
Tasks and Deck cards should be "the same"

### ISSUE THREAD

**Issue by dtcg** [nextcloud/deck#3053]
Nextcloud Deck integration in Tasks seems read-only and... pretty useless:

- All Deck lists are automatically mixed in a single Task list: unusable.
- Tasks in a "Deck task list" are undraggable, untickable, uneditable: what is the point?
- Tasks from a "normal" task list can't be dragged into a "deck" task list.

It seems to me that Tasks and cards in Deck don't share the same underlying structure.
Any chance of actually merging the two technologies?

**Comment by stefan-niedermann** [comment]
> Tasks seems read-only

If you wouldn't have ignored and removed the issue template and searched for existing issues, you would have noticed, that this is the *current* state and that [write access is a planned feature](https://github.com/nextcloud/deck/issues/2399).

> All Deck lists are automatically mixed in a single Task list: unusable.

One **board** of the Deck app corresponds to one task list in the Tasks app (see screenshot below). If you have a different behavior, it is a bug. In this case, open a new [bug report](https://github.com/nextcloud/deck/issues/new?assignees=&labels=&template=Bug_report.md), *filling the complete issue template*.

![grafik](https://user-images.githubusercontent.com/4741199/117185213-e1a30d80-add9-11eb-8dba-fe1e4cd8f053.png)

> Tasks in a "Deck task list" are undraggable, untickable, uneditable: what is the point?

A **card** can be dragged and dropped from one list to another in the Deck app. As mentioned above, this is of course not yet possible from the Tasks app until the write access has been implemented. Feel free to contribute a Pull Request, i have linked the corresponding issue above.

> Tasks from a "normal" task list can't be dragged into a "deck" task list.

The integration is one-way at the moment: Deck boards can be displayed in the tasks app.

> Tasks and Deck cards should be "the same"

No, they shouldn't. Both have different purposes and different target groups. One big fat app to "rule them all" never worked for anyone.

> It seems to me that Tasks and cards in Deck don't share the same underlying structure.

This is correct. Both apps started independently, one by the community, one by employees.
The goal should indeed be to unify the data storage in the backend with different views to this data for various use cases. There are already existing issues to track the progress to achieve this goal.

> [...] pretty useless
> [...] unusable

Please let me refer to the [Code of conduct](https://nextcloud.com/contribute/code-of-conduct/). Your comments are disrespectful and destructive. If you have feature requests or bug reports, you are welcome to post them here, but chances are high that people will listen to and respond to you when you are constructive.
