### ISSUE TITLE
Ability to save tag changes with enter

### ISSUE THREAD

**Issue by reginasipos** [nextcloud/deck#306]
### Steps to reproduce
1. change name or color of a tag
2. try to save it with enter

### Expected behaviour
Saving via enter should work for consistency, like with other functionalities

### Actual behaviour
Only check mark saves currently

**Comment by rpadovani** [comment]
I tried to fix it in #331

**Comment by juliushaertl** [comment]
Fixed in #331 
Thank you @rpadovani
