### ISSUE TITLE
Größere Kartenansicht verwenden / Anstehende Karten - Error on opening card

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/deck#3079]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

When i activate in the sidebar the setting "Größere Kartenansicht verwenden" and i am inside a board and i click on menu item "Anstehende Karten" and inside this menu i click on a specific card then this card not get opened. (in a specific board the modal always open)

no error in nextcloud.log but a js error: 
`main.js:63 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.insertBefore (https://cloud..de/apps/deck/js/main.js?v=d8bc8f3b-56:936:40468)
    at https://cloud..de/apps/deck/js/main.js?v=d8bc8f3b-56:936:55716
    at _ (https://cloud..de/apps/deck/js/main.js?v=d8bc8f3b-56:936:55834)
    at a.__patch__ (https://cloud..de/apps/deck/js/main.js?v=d8bc8f3b-56:936:56969)
    at a.t._update (https://cloud..de/apps/deck/js/main.js?v=d8bc8f3b-56:936:34334)
    at a.r (https://cloud..de/apps/deck/js/main.js?v=d8bc8f3b-56:936:64431)
    at mn.get (https://cloud..de/apps/deck/js/main.js?v=d8bc8f3b-56:936:26610)
    at mn.run (https://cloud..de/apps/deck/js/main.js?v=d8bc8f3b-56:936:27494)
    at un (https://cloud..de/apps/deck/js/main.js?v=d8bc8f3b-56:936:25602)
    at Array.<anonymous> (https://cloud.de/apps/deck/js/main.js?v=d8bc8f3b-56:936:12293)`

**Comment by juliushaertl** [comment]
Please fill out the issue template especially the deck version would be interesting here. I cannot reproduce any issue with the latest release, so in case you still see this please provide the exact version in use.

**Comment by support-netx** [comment]
Hi,

we have the same problem and I didn't want to open a new issue.

**Describe the bug**
After openening a card from the 'upcomming cards' site in deck application, the card is shown the way it should be. If we go back to 'upcomming cards' and try to open another card, nothing happens; only the link in the address bar changes.
The cards (to be precise: only one card) can only be opened after reloading the site.
Having a look using the ME Edge DevTools we found this error:

```
main.js:63
        
       DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.insertBefore (https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3654648)
    at https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3669859
    at x (https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3669977)
    at o.va.nodeOps [as __patch__] (https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3671112)
    at o.t._update (https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3648213)
    at o.r (https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3678533)
    at Tn.get (https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3640566)
    at Tn.run (https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3641450)
    at vn (https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3639558)
    at Array.<anonymous> (https://cloud.swnh.de/apps/deck/js/deck-main.js?v=25dffc0b-14:2:3626159)
```




**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Deck'-->'Upcoming cards'
2. Click on some random card
3. Go back to 'Upcomming cards'
4. Click on some random card
5. See error (only if cardview is set to "Use bigger card view")

**Expected behavior**
Cards should open from 'upcomming cards' site.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Client details:**
 - OS: [Window 10 Professional; Window Server 2019]
 - Browser [Microsoft Edge] 
 - Version [100.0.1185.50]
 - Device: [MS desktop, MS terminal server]

<details>
<summary>Server details</summary>


**Ubuntu Server 20.04 LTS**:

**nginx**

**Database: mariadb  Ver 15.1 Distrib 10.3.34-MariaDB**

**PHP version: 7.4.3**

**Nextcloud version: 23.0.4

**Where did you install Nextcloud from: https://download.nextcloud.com/server/releases/nextcloud-23.0.4.zip**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - bbb: 2.2.0
  - breezedark: 23.2.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.2.2
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - collectives: 1.0.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - external: 3.10.2
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - forms: 2.5.0
  - group_everyone: 0.1.10
  - groupfolders: 11.1.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - registration: 1.4.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.1
  - user_status: 1.3.1
  - user_usage_report: 1.7.0
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - welcome: 1.0.1
  - workflowengine: 2.5.0
Disabled:
  - encryption
  - files_external
  - files_trackdownloads: 1.11.0
  - firstrunwizard: 2.8.0
  - passwords: 2021.12.20

```

**Nextcloud configuration:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocnt4v5yhygd',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxx.xxx.xxx',
    1 => 'xxxxxx.xxxxx.de',
    2 => 'xxxxxxx.xxxx.de',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '23.0.4.1',
  'overwrite.cli.url' => 'https://xxx.xxx.xxx.xxx',
  'dbname' => 'xxxxxxxx',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'xxxxxxxxx',
  'dbpassword' => 'xxxxxxxxx',
  'installed' => true,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'maintenance' => false,
  'loglevel' => 2,
  'mail_from_address' => 'xxxxx',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'xxxxx.de',
  'mail_smtphost' => 'xxx.xxx.xxx.xxx',
  'mail_smtpport' => '25',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'integrity.check.disabled' => 'true',
  'theme' => '',
);

```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP Ver. 1.13.1>

<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
no error in nextcloud.log
```

#### Browser log
```
see bug description
```

</details>

**Comment by oneWaveAdrian** [comment]
Experienced the same issue as @support-netx reported on [MacOS] and [Edge] - Seems to work fine in [Safari]

**Comment by lu-krin** [comment]
Another bug for the same issue: https://github.com/nextcloud/deck/issues/3837

**Comment by juliushaertl** [comment]
I also cannot reproduce this. Since the version reported is quite old, please try if this is still an issue on the latest and don't hesitate to reopen if it is still an issue.

**Comment by b90g** [comment]
On NC 27.1.3 with Deck 1.11 i was still able to reporduce the issue.

as described in: https://github.com/nextcloud/deck/issues/3079#issuecomment-1109801700
