### ISSUE TITLE
Document title doesn't update when renaming active board

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/deck#308]
Steps to reproduce

1. Create a board "Foo"
2. Set "Foo" as active board
3. Rename "Foo" to "Bar" 

Expected behavior

The document title changes from "Foo | Deck - Nextcloud" to "Bar | Deck - Nextcloud"

Actual behavior

The document title stays at "Foo | Deck - Nextcloud"

**Comment by rpadovani** [comment]
I would be interested in fixing this one, but I am not sure how to proceed.

When you update the title of a board, the function `$scope.boardUpdate()` in `ListController.js` is called.

To update the page title, I need to call `$scope.setPageTitle()` in `BoardController.js`. 

Should I move `setPageTitle()` to a service so we can call it from anywhere in the code? Or there is another solution?

Sorry but my Angular skills are not so good

**Comment by juliushaertl** [comment]
@rpadovani The easiest would be to just use $watch to call setPageTitle everytime the current board data changes. Something like that should work (not tested):

```
$scope.$watch(function () {
   return BoardService.getCurrent().title;
}, function() {
   $scope.setPageTitle();
});
```

**Comment by rpadovani** [comment]
@juliushaertl  ok, I tested it and it works as expected, but doesn't this impact performances?

**Comment by juliushaertl** [comment]
@rpadovani Well angular makes heavy use of watchers anyway. A better solution would be to introduce some event messaging so that services emit events when some data changed. That way any controller using it can listen for the events and take action on them. But for now adding a watcher for this is the easiest and not that kind of an overhead imo.

**Comment by raxetul** [comment]
Can not rename board at the moment with nextcloud 15

**Comment by juliushaertl** [comment]
@raxetul please open a new issue

**Comment by raxetul** [comment]
Sorry, I found the correct location now, my mistake.
