### ISSUE TITLE
perfomance regarding boards/activity with many users

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/deck#3082]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**To Reproduce** 

i have a group with ~100 people in it.
when i share a board with this group every action in the board has a delay / needs some seconds in the backend.
(makes the usage unpossible) 

for me it seems this delay is coming because of writing activities for every of this actions to that many people.
is there something we can do about it or is sharing of boards with many user & activity app just not possible?
are there thoughts about changing the design (like do this action asnyc / in the background)

(similar issue i also discovered with changing files in frontend)

**Comment by kinimodmeyer** [comment]
i created now a issue in the activity app repo as this seems also be a issue on other apps.

https://github.com/nextcloud/activity/issues/590

**Comment by kinimodmeyer** [comment]
maybe the activity creation in deck-frontend could be done in background?

**Comment by juliushaertl** [comment]
Thinking about my comment in nextcloud/activity#590 I might have an idea on where the deck app might behave slower due to some missing caching, so let me reopen this one to investigate further a bit on that.

**Comment by juliushaertl** [comment]
So my suspicion was wrong, we properly cache any needed metadata that is added to the individual activity entries so any improvement in this area is up to the activity app.
