### ISSUE TITLE
Allow longer text in card comments

### ISSUE THREAD

**Issue by davidchavalarias** [nextcloud/deck#3124]
Comments on cards are useful to have team exchanges on card's task, but size is too limited and you can't have several lines comments. Allowing more structured and longer comments, like in kanboard would be very helpfull.

**Comment by juliushaertl** [comment]
The comments length limit is due to the fact that we only use the server comments API which has that limit, so there is nothing we can do about that in the deck app. I'd suggest to open a feature request in https://github.com/nextcloud/server/ about that to extend the limit globally.
