### ISSUE TITLE
Create coloured lists & possibility to copy cards

### ISSUE THREAD

**Issue by Oberlurch3000** [nextcloud/deck#3125]
Hello,

I really enjoy this add on for NC.

What I miss is to give the different lists a specific colour.
Another great freature would be to copy cards. So you could create templates.

**Comment by stefan-niedermann** [comment]
Hello, for list colors see https://github.com/nextcloud/deck/issues/833#issuecomment-452921464 for copying cards see https://github.com/nextcloud/deck/issues/1813

Please use the 🔍  search function before opening new issues 🙂
