### ISSUE TITLE
App for iOS and iPadOS

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/deck#3126]
Hi!
An app for IOS / IPadOS would be very cool, as the Deck Desktop / Web Version does not work with Safari on Ipad.
best regards

**Comment by stefan-niedermann** [comment]
Please see https://github.com/nextcloud/deck/issues/1769#issuecomment-628589380

Feel free to open specific bug reports regarding Safari on iPad filling the complete issue template, so they can be addressed and fixed instead of just keeping them around :wink:
