### ISSUE TITLE
cannot save edited comments

### ISSUE THREAD

**Issue by mokkin** [nextcloud/deck#3159]
### Steps to reproduce
While trying to edit a misspelled word I cannot save the comment.

### Expected behaviour
save the edited comment

### Actual behaviour
I cannot save the comment.

## Server configuration detail

**Operating system:** Linux 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.29

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 21.0.2 - 21.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - bbb: 1.4.1
 - bookmarks: 4.2.2
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.0
 - circles: 0.21.3
 - cloud_federation_api: 1.4.0
 - cms_pico: 1.0.15
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.4.2
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_external: 1.12.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - groupfolders: 9.0.2
 - impersonate: 1.8.0
 - integration_whiteboard: 0.0.14
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - nextcloud_announcements: 1.10.0
 - notes: 4.1.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - occweb: 0.0.7
 - password_policy: 1.11.0
 - passwords: 2021.6.20
 - photos: 1.3.0
 - polls: 2.0.4
 - previewgenerator: 3.1.1
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - richdocuments: 4.1.2
 - richdocumentscode: 6.4.806
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - spreed: 11.2.2
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.13.6
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - encryption
 - maps
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.xxx.de",
        "cloud.yyy.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.xxx.de",
    "dbtype": "mysql",
    "version": "21.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app.mail.server-side-cache.enabled": true,
    "theme": "",
    "loglevel": 1,
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "mysql.utf8mb4": true,
    "htaccess.IgnoreFrontController": true,
    "htaccess.RewriteBase": "\/",
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "occweb",
        "issuetemplate"
    ],
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "default_phone_region": "DE"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0

**Operating system:** Ubuntu 20.04

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

17:25:55.047 XHRPUThttps://cloud.xxx.de/ocs/v2.php/apps/deck/api/v1.0/cards/107/comments/9707
[HTTP/1.1 403 Forbidden 68ms]

	
PUT
	https://cloud.xxx.de/ocs/v2.php/apps/deck/api/v1.0/cards/107/comments/9707
Status403
Forbidden
VersionHTTP/1.1
Übertragen920 B (94 B Größe)
Referrer Policyno-referrer

    	
    Cache-Control
    	no-cache, no-store, must-revalidate
    Connection
    	Keep-Alive
    Content-Length
    	94
    Content-Security-Policy
    	default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
    Content-Type
    	application/json; charset=utf-8
    Date
    	Thu, 01 Jul 2021 15:25:55 GMT
    Expires
    	Thu, 19 Nov 1981 08:52:00 GMT
    Feature-Policy
    	autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
    Keep-Alive
    	timeout=5, max=98
    Pragma
    	no-cache
    Referrer-Policy
    	no-referrer
    Server
    	Apache/2.4.41 (Ubuntu)
    Strict-Transport-Security
    	max-age=15552000; includeSubDomains
    X-Content-Type-Options
    	nosniff
    X-Download-Options
    	noopen
    X-Frame-Options
    	SAMEORIGIN
    X-Permitted-Cross-Domain-Policies
    	none
    X-Robots-Tag
    	none
    X-XSS-Protection
    	1; mode=block
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3
    Connection
    	keep-alive
    Content-Length
    	844
    Content-Type
    	application/json;charset=utf-8
    Cookie
    	__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=markus; nc_token=LMjQJOFMNKyCnXUQscf4V8YeqcrhS01x; nc_session_id=7qd3hntv5ja5376vdcgc463g4t; oc_sessionPassphrase=1woR5gwrBo7lSndgyFSWJLH5Yftt70jXkjRNKdtJTlsphirFSZpovULHXkz3ksmv%2F1U9lWS3GVtQPmHP%2BKICx06Dquw79r1okq75p32Ra7wJSTYHzCX7njIDUWC9kCp1; ocg0s3qz6hhw=7qd3hntv5ja5376vdcgc463g4t
    DNT
    	1
    Host
    	cloud.xxx.de
    Origin
    	https://cloud.xxx.de
    requesttoken
    	KUXPni8dBM/BhYGauKu8xuDHmspVw6lYIV9HBIpvkuM=:ECCG8FVZNPamzc+u0sTQhZme/4gfuv4sexA3ZroZq4s=
    User-Agent
    	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
</details>

**Comment by juliushaertl** [comment]
I also cannot reproduce this. Since the version reported is quite old, please try if this is still an issue on the latest and don't hesitate to reopen if it is still an issue.
