### ISSUE TITLE
Don't open sidebar/popup editor when drag+drop is done

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/deck#3173]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
To be honest, I find it quite annoying that the editor pops up all the time when I move card to another stack or up/down within the same stack. Would it make sense to not open/popover when moving, but only when doing a normal/single click?

**Comment by timkrief** [comment]
It seems like a duplicate of #2594

**Comment by juliushaertl** [comment]
Yep, closing as a duplicate.
