### ISSUE TITLE
1.4.3 is release without release tag in github?

### ISSUE THREAD

**Issue by markuman** [nextcloud/deck#3184]
I see 

![Screenshot 2021-07-12 at 13-04-08 Apps - lekker Box](https://user-images.githubusercontent.com/3920157/125277433-b37a0680-e311-11eb-8d8c-33f92fdb27e1.png)

Are you doing manual releases without CI?

**Comment by stefan-niedermann** [comment]
# :question: 

https://github.com/nextcloud/deck/releases/tag/v1.4.3

![grafik](https://user-images.githubusercontent.com/4741199/125278729-6139e500-e313-11eb-849b-bc9c91a2e7da.png)

**Comment by stefan-niedermann** [comment]
Not sure in which way the proprietary GitHub-only "releases" feature is related to your question about manual or CI releases...

I agree that the [changelog](https://github.com/nextcloud/deck/blob/master/CHANGELOG.md) could need some love, but everything is tagged properly, so closing this issue as it isn't really an issue :wink:

**Comment by markuman** [comment]
Ah, github just collabse tags without messages

![Screenshot 2021-07-12 at 13-26-06 Releases · nextcloud deck](https://user-images.githubusercontent.com/3920157/125280005-deb22500-e314-11eb-80f1-ebc551a3c3a9.png)

sorry

**Comment by juliushaertl** [comment]
The release archives have been moved to https://github.com/nextcloud-releases/deck/
