### ISSUE TITLE
Copy / paste in Cards comments not possible in FireFox

### ISSUE THREAD

**Issue by davidchavalarias** [nextcloud/deck#3191]
Copy / paste in Cards comments is not possible in Firefox 89.0.2 (64 bits) ( but possible in chromium)

**Comment by stefan-niedermann** [comment]
As a Firefox 78.11.0esr (64-Bit) on a LMDE 4 linux distribution user, i can not reproduce this issue.

- I can copy text from
  - ✅ written comments
  - ✅ the comment input field
  - ✅ the description preview
  - ✅ the description input field
- I can paste text to
  - ✅ the comment input field
  - ✅ the description input field

**Please fill out the complete issue template, it is there for a reason.** Write clear steps to reproduce, provide screenshots and mark the fields which you can not copy from. Disable all add-ons in Firefox and post the content of the browser console.

**Comment by Discostu36** [comment]
Tested with Firefox 89.0.2 and Firefox 90.0 (both 64 Bit) on Windows 10. **Can** also **not reproduce** any issues when copy/pasting out of / into deck comments.
