### ISSUE TITLE
FR: More freedom 🗽 with the tags please

### ISSUE THREAD

**Issue by JOduMonT** [nextcloud/deck#3192]
I love this app and the fact it is integrated to the calendar, but It would be I see few improvements, which I'm pretty sure they are easy to implement, but I'm not a developer.

1. I would be nice to being able to rename the tags and/or even better to add more tags as we wish and more colours like in the calendar app.
Related to the tags, it is kinda redundant to have a tag to mark DONE, and a column named DONE and a function to achieve the card.

**Comment by stefan-niedermann** [comment]
Use the three dots menu in the left sidebar to open the "Board Details". There you can manage the tags of each board (create, edit, delete, change color, ...)

> it is kinda redundant to have a tag to mark DONE, and a column named DONE and a function to achieve the card.

Depending on the users workflow, each of them can make sense. They are initially there to demonstrate different ways of how to manage your stuff, but you don't need to keep them. Manage your tags as described above and also feel free to change the default lists. (Personally i removed the `done` tag in favor of the `Done` list. I keep cards there for some time to be abke to quickly access them and then archive them)

**Comment by JOduMonT** [comment]
> left sidebar
I guessed, I was using too much of my left brain and looking too much on the right side :)
Thanks for your quick and kind answer.
