### ISSUE TITLE
Scrolling columns doesn't work in safari

### ISSUE THREAD

**Issue by raboof** [nextcloud/deck#3203]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

When using the Safari desktop browser on mac, you cannot scroll individual columns: scrolling tries to scroll the 'whole' page, which doesn't work.

Switching to Chrome helps.

**Client details:**
 - OS: OSX
 - Browser safari
 - Version: 1.4.2
 - Device: macbook

<details>
no

</details>

**Comment by lzmartinico** [comment]
Further to this, on the latest iOS version of Safari, horizontal scrolling does not work, moving columns instead
