### ISSUE TITLE
cant add groups to deck

### ISSUE THREAD

**Issue by a4bits** [nextcloud/deck#3205]
Can't add groups to Decks via share...
The search circle is spinning, 

In network panel i get 404 for GET of: 
https://myapp.app/ocs/v2.php/apps/files_sharing/api/v1/sharees?search=&format=json&perPage=20&itemType=0%2C1%2C4%2C7&lookup=false

it gives back:
```{"ocs":{"meta":{"status":"failure","statuscode":404,"message":"Invalid query, please check the syntax. API specifications are here: http:\/\/www.freedesktop.org\/wiki\/Specifications\/open-collaboration-services.\n"},"data":[]}}```

JS console:
```
init-collections.js:44 OCA.Sharing.ShareSearch not ready
(anonymous) @ init-collections.js:44

Uncaught (in promise) Error: Request failed with status code 404
    at t.exports (createError.js:16)
    at t.exports (settle.js:17)
    at XMLHttpRequest.A.onreadystatechange (xhr.js:62)
```

system information:
version: 22.0.0.11
versionstring: 22.0.0
plugin version: 1.5.0

**Comment by juliushaertl** [comment]
Is your nextcloud maybe having files_sharing disabled? Those errors seem quite unexpected to me, especially the 404 on the search as this is the same endpoint that the files app would use for sharing.

**Comment by a4bits** [comment]
hi, had to go back to older version. can't test now. maybe someone else will have similar issue.

**Comment by Minocula** [comment]
So cool in Version nextcloud 22.1.1 and Deck Version 1.5.1 it works! thx for that fast fix!
