### ISSUE TITLE
Add more tag selection and custom tag support for tasks in Nextcloud Deck

### ISSUE THREAD

**Issue by stevenleeS0ht** [nextcloud/deck#3213]
Currently, Nextcloud Deck only support 4 type of tags (Finished, action needed, later, to review), and they are all predefined.

Sometimes users need custom tag defined by their own, and sometimes users need to define tags under specific project (context).

It would be good to provide user more flexibility to define task tags.

**Comment by putt1ck** [comment]
In the board details (available in the context menu for the boards in the sidebar list, or when viewing a board from the menu top right corner you can review the default (example) tags for the board and edit/delete/add as needed.
