### ISSUE TITLE
Incorrect displaying of data on main field of cards (header+due date)

### ISSUE THREAD

**Issue by neerro** [nextcloud/deck#3216]
**Describe the bug**
If I have a long text for card header and I set up due date for card, it is displaying incorrect on main cards' field (shown on the picture below):

![pic_01](https://user-images.githubusercontent.com/75830569/127073388-28ebf053-1897-4887-bd7a-1a1c9778a1e5.jpg)

**Expected behavior**
It would be great to change card's displaying as shown on the picture below:
  
![pic_02](https://user-images.githubusercontent.com/75830569/127073553-d3150d0e-1813-4cdd-84a9-d9e0ec130112.jpg)

**The changes will bring some profit for cards' displaying:** 
1. Reduced cards' sizing and will increase space needed for another cards' displaying.
2. Cards will get more functional structure.
3. Text header will be comfortable for reading.

**Comment by stefan-niedermann** [comment]
Looks like a duplucate of https://github.com/nextcloud/deck/issues/1672

**Comment by neerro** [comment]
I would better say additional remark, not duplicate 🙂

**Comment by juliushaertl** [comment]
Lets track this in #1672
