### ISSUE TITLE
UserID being used in attachments

### ISSUE THREAD

**Issue by meichthys** [nextcloud/deck#3223]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
I might be wrong, but I think the userID is intended to not be user-facing. A few other fixed bugs seem to have replaced the userID with a displayName or FullName ( #43, #74 ), however the userID still appears to be used when viewing attachments to cards:
![image](https://user-images.githubusercontent.com/10717998/127918264-3d41edce-0189-41f1-997e-8fd8b05673ff.png)

The timeline tab correctly shows the username (or says 'you') when an attachment has been added:
![image](https://user-images.githubusercontent.com/10717998/127918671-c67330b8-5e7a-43f9-b07d-56162ebdd14d.png)

**To Reproduce**
1. Go to Deck app
2. Click on a card to view details.
3. Add an attachment to the card.
4. See error: attachment shows userID (often an ugly uuid when using LDAP) instead of showing displayName or Full Name

**Expected behavior**
I would expect the attachment to show the displayName or FullName of the user who attached it rather than the userID

**Client details:**
 - OS: Windows 10
 - Browser: Firefox (also tested with other browsers)
 - Version: 22
 - Device: Desktop

**Comment by juliushaertl** [comment]
This has been fixed.
