### ISSUE TITLE
Directly download Files with new File attachments!

### ISSUE THREAD

**Issue by TheTiEr** [nextcloud/deck#3232]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

If the attached file has no viewer in NC it is opened in the file viewer of NC. Instead it should be downloaded if you left click on the filename. 

**To Reproduce**
upload a file without an integrated web viewer like "stl" as attachement to a card. Click on this File. 

**Expected behavior**
Directly download the file or add the possibility to download it with the "three dot menu" or a right click.

With the old Deck attachment this worked as expected. 

**Client details:**
 - OS:  Ubuntu 18.3 LTS
 - Browser Chrome but doesnt matter
 - Version 21.0.3 / Deck v.1.4.3
 - Device:  desktop

**Comment by juliushaertl** [comment]
Was implemented with https://github.com/nextcloud/deck/pull/3428
