### ISSUE TITLE
Problem with deck with recent update of nextcloud

### ISSUE THREAD

**Issue by seyzed** [nextcloud/deck#3247]
Hello,

We've recently updated nextcloud, we are facing issues with deck as it crashes the system (makes it unresponsive). Here is the log that causes the crash:

`2021-08-11T12:05:40.000Z [Wed Aug 11 12:05:40.107279 2021] [php7:notice] [pid 271] [client 172.18.0.1:50120] {"reqId":"tcszJZSVE98xDnk71Y3F","level":3,"time":"2021-08-11T12:05:40+00:00","remoteAddr":"172.18.0.1","user":"--","app":"index","method":"GET","url":"/index.php/login","message":"Argument 1 passed to OC\\\\Group\\\\Manager::getUserIdGroupIds() must be of the type string, null given, called in /app/code/lib/private/Group/Manager.php on line 316","userAgent":"Mozilla (CloudronHealth)","version":"22.0.0.11","exception":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\\\Group\\\\Manager::getUserIdGroupIds() must be of the type string, null given, called in /app/code/lib/private/Group/Manager.php on line 316","Code":0,"Trace":[{"file":"/app/code/lib/private/Group/Manager.php","line":316,"function":"getUserIdGroupIds","class":"OC\\\\Group\\\\Manager","type":"->"},{"file":"/app/data/apps/deck/lib/Service/PermissionService.php","line":316,"function":"isInGroup","class":"OC\\\\Group\\\\Manager","type":"->"},{"file":"/app/data/apps/deck/lib/Capabilities.php","line":53,"function":"canCreate","class":"OCA\\\\Deck\\\\Service\\\\PermissionService","type":"->"},{"file":"/app/code/lib/private/CapabilitiesManager.php","line":69,"function":"getCapabilities","class":"OCA\\\\Deck\\\\Capabilities","type":"->"},{"file":"/app/code/lib/private/Template/JSConfigHelper.php","line":190,"function":"getCapabilities","class":"OC\\\\CapabilitiesManager","type":"->"},{"file":"/app/code/lib/private/TemplateLayout.php","line":220,"function":"getConfig","class":"OC\\\\Template\\\\JSConfigHelper","type":"->"},{"file":"/app/code/lib/private/legacy/OC_Template.php","line":182,"function":"__construct","class":"OC\\\\TemplateLayout","type":"->"},{"file":"/app/code/lib/public/AppFramework/Http/TemplateResponse.php","line":204,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/app/code/lib/private/AppFramework/Http/Dispatcher.php","line":171,"function":"render","class":"OCP\\\\AppFramework\\\\Http\\\\TemplateResponse","type":"->"},{"file":"/app/code/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\\\AppFramework\\\\Http\\\\Dispatcher","type":"->"},{"file":"/app/code/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\\\AppFramework\\\\App","type":"::"},{"file":"/app/code/lib/base.php","line":1000,"function":"match","class":"OC\\\\Route\\\\Router","type":"->"},{"file":"/app/code/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/app/code/lib/private/Group/Manager.php","Line":333,"CustomMessage":"--"}}`

We've temporarily disabled the deck app. I'd appreciate if you could take a look at this, deck is very important to our business.

**Comment by juliushaertl** [comment]
Was fixed in https://github.com/nextcloud/deck/pull/3231 and will be part of the next release.
