### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by martin-77** [nextcloud/deck#3258]
**Is your feature request related to a problem? Please describe.**

It would be nice, to have an option for recurring events. Example: I have to adminstrate some servers. For each server I made a board with different cards. Some cards have the funktion of a reminder, to do things every x weeks - for example update Bigbluebutton and greenlight / docker. The command is written in a card for an easy copy paste job. 
I want to do this every 4 weeks. 

What works is: every 4 weeks, i get a reminder, to do this or that. Then, i have to manually adjust the date, to have my next reminder.

**Describe the solution you'd like**

It would be nice, to tell a card: reminder every x days / x weeks / monthly / etc.

Maybe I abuse Deck, and my Workflow is Semi-Professional, but it is just an example and i think there are a bunch of other possible recurring events.

Thanks in advance!

Seen to late: no new idea...
https://github.com/nextcloud/deck/issues/480

**Comment by sunjam** [comment]
You can close your issue since it duplicates 480. :)
