### ISSUE TITLE
Add label when creating card

### ISSUE THREAD

**Issue by dorignan** [nextcloud/deck#3262]
I'd like to be able to add labels when I write new card.

I have see this feature on TickTick : number sign (#) initiate a call to labels and, if the label exist, the new card have this label (and the call in title is removed).

For example : if I write "Buy milk #supermarket", the card "Buy milk" will be created with the label "supermarket"

**Comment by juliushaertl** [comment]
Thanks for the suggestion. Closing as a duplicate of #2777 as the other one also covers the user suggestion.
