### ISSUE TITLE
Showing All Tasks instead of Upcoming cards

### ISSUE THREAD

**Issue by mareekkk** [nextcloud/deck#3267]
Hi,

Is it possible to show **All Tasks** instead of **Upcoming cards** when clicking on the Deck icon? Not all of my tasks have dates or so I mostly visit the All Tasks section instead of upcoming cards. Is there a way to do this? 

Thanks!

**Comment by dodedodo** [comment]
Hey mareekkk,

If I understand correctly you want to open a specific board by default, instead of the Upcoming cards view. If so, keep an eye on #2840

**Comment by mareekkk** [comment]
> Hey mareekkk,
> 
> If I understand correctly you want to open a specific board by default, instead of the Upcoming cards view. If so, keep an eye on #2840

Awesome! This is even better than what I wanted as it has more options proposed. Thank you!
