### ISSUE TITLE
`CTRL` + `ENTER` to Save Changes on Card Description

### ISSUE THREAD

**Issue by SethFalco** [nextcloud/deck#3268]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

In many apps doing `CTRL` + `ENTER` acts as a "finished" action to either send, post, or save whatever the user is typing.

For example:
* To send an email in Tutanota.
* Submitting issues, pull requests, and comments on GitHub.
* Commenting on Reddit.
* Tweeting on Twitter.

**Describe the solution you'd like**

After clicking "Edit description" the user can type to edit the description of a card.
I think if a user does `CTRL` + `ENTER` it should act as if the user clicked "View description". (Save and return to the non-edit view.)

**Describe alternatives you've considered**

N/A

**Additional context**

Moved over from https://github.com/stefan-niedermann/nextcloud-deck/issues/1087

**Comment by stefan-niedermann** [comment]
Related to #46

**Comment by dodedodo** [comment]
I think `CTRL` + `S` would make more sense in this case. You're not sending or submitting a message like in a mail client or twitter, but rather saving a description. 

`CTRL` + `ENTER` would make sense for comments.

**Comment by SethFalco** [comment]
I think `CTRL` + `ENTER` makes more sense, since `CTRL` + `S` usually doesn't affect the view.
I'm not asking to only save the content of the description, I'm suggesting this should kick the user out of the "Edit description" view entirely.

This is likely subjective, however. In the end, I'm down for whatever most users are into.

**Comment by Ben-Ro** [comment]
Hey all,
this missing feature annoyed me for some time, so i decided to implement it. 

It uses Keylisteners on `easymde.codemirror`. Once the CMD/CTRL is pressed, it sets `keyExitState = 1` until the key is released. If Enter is pushed while this, it calls `hideEditor()` (just like the Action Button) and removes all Keylisteners.

I just create a Pull Request, i hope the code quality is ok :)
