### ISSUE TITLE
Could you build option to change description to the first position?

### ISSUE THREAD

**Issue by cmdntd** [nextcloud/deck#3282]
Description is the most important information for task, users often need to see this first.
I 'm not sure about others, but could you build option for this?
![EDLU27H5d7](https://user-images.githubusercontent.com/1112881/131529858-262fed3c-3ee2-40a2-9212-ef2587f5d736.png)

**Comment by stefan-niedermann** [comment]
Checkout the planned redesign of https://github.com/nextcloud/deck/issues/2702

Tags, assignees and due date will then only consume space if they are actually set. If you don't use them, they will be collapsed, so that the description field is basically at the top.
