### ISSUE TITLE
How could I remove filetype of onlyoffice?

### ISSUE THREAD

**Issue by cmdntd** [nextcloud/deck#3284]
I disabled and removed onlyoffice, but these filetype still there.
How could I remove these filetype of onlyoffice?
![YuQfRyJUGl](https://user-images.githubusercontent.com/1112881/131539587-208ffe2b-a516-466a-b3e9-0be7a3d706a6.png)

**Client details:**
Android 11
Chrome
Deck 1.5.0
Nextcloud 22.1.1
Samsung phone

**Server**
Google compute
Ubuntu 20.04
PHP 7.4
MySQL

**Comment by stefan-niedermann** [comment]
In which way is this related to the Deck app?

**Comment by cmdntd** [comment]
Sorry, this issue is about nextcloud.
