### ISSUE TITLE
due date not working

### ISSUE THREAD

**Issue by iluks** [nextcloud/deck#329]
### Steps to reproduce
1.create due date on a task 
2.due date/time shows on the relevant task 
3.click another task
4 click the task with due date and there is no due date/time any more

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: Ubuntu 16.04 - Appliance

**Web server:** Apache

**Database:** postgresql
 
**PHP version:** 7

**Nextcloud version:** (see Nextcloud admin page) 12.03

**Where did you install Nextcloud from:** appliance

**Signing status:** 

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**
root@cloud:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.0
  - apporder: 0.4.0
  - appvncsafe: 1.1.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - checksum: 0.3.5
  - circles: 0.12.4
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.2.4
  - drawio: 0.8.8
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_clipboard: 0.6.4
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - flowupload: 0.0.5
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - impersonate: 1.0.1
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.3
  - metadata: 0.5.0
  - news: 11.0.5
  - nextant: 1.0.8
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ojsxc: 3.3.0
  - passman: 2.1.4
  - password_policy: 1.2.2
  - polls: 0.7.3
  - previewgenerator: 1.0.7
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - radio: 0.6.0
  - ransomware_protection: 1.0.4
  - richdocuments: 1.12.35
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - spreedme: 0.3.11
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - twofactor_u2f: 1.3.3
  - updatenotification: 1.2.0
  - weather: 1.5.0
  - workflowengine: 1.2.0
Disabled:
  - dashboard
  - encryption
  - user_external
  - user_ldap
  - user_saml
```

**Comment by juliushaertl** [comment]
Thanks for your report. Can you please check if there are any errors in the Nextcloud log, browser console or failed requests in the network tab of your browsers developer tools.

**Comment by juliushaertl** [comment]
There was an issue with due dates on mysql databases (see #321) but since your setup uses postgres that might be something different. I currently cannot reproduce this on my postgres test setup.

**Comment by iluks** [comment]
Hi it looks like your gut instinct was correct ... date format issue

Error | index | Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_deck_cards` SET `duedate` = ?,`last_modified` = ? WHERE `id` = ?' with params ["2017-10-13T14:04:26+00:00", 1507903466, 12]: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2017-10-13T14:04:26+00:00' for column 'duedate' at row 1/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128:Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php - line 177:Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE `oc_deck...', Array)/var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php - line 247: Doctrine\DBAL\Statement->execute()/var/www/nextcloud/apps/deck/lib/Db/DeckMapper.php - line 40:OCP\AppFramework\Db\Mapper->execute('UPDATE `*PREFIX...', Array, NULL, NULL)/var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php - line 187: OCA\Deck\Db\DeckMapper->execute('UPDATE `*PREFIX...', Array)/var/www/nextcloud/apps/deck/lib/Db/CardMapper.php - line 50:OCP\AppFramework\Db\Mapper->update(Object(OCA\Deck\Db\Card))/var/www/nextcloud/apps/deck/lib/Service/CardService.php - line 92:OCA\Deck\Db\CardMapper->update(Object(OCA\Deck\Db\Card))/var/www/nextcloud/apps/deck/lib/Controller/CardController.php - line 94:OCA\Deck\Service\CardService->update(12, 'bull', 1, 'plain', 3, 'fdsaf', 'skuli', '2017-10-13T14 0...')[internal function]OCA\Deck\Controller\CardController->update(12, 'bull', 1, 'plain', 3, 'fdsaf', '2017-10-13T14 0...')/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160:call_user_func_array(Array, Array)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90:OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Deck\Controller\CardController), 'update')/var/www/nextcloud/lib/private/AppFramework/App.php - line 114:OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Deck\Controller\CardController), 'update')/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App main('OCA\\Deck\\Contro...', 'update', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function]OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/nextcloud/lib/private/Route/Router.php - line 299:call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/nextcloud/lib/base.php - line 1004: OC\Route\Router->match('/apps/deck/card...')/var/www/nextcloud/index.php - line 48: OC handleRequest(){main}
-- | -- | --

**Comment by iluks** [comment]
Who would I go about changing the format to dd.mm.yyyy  Icelandic format ?

**Comment by iluks** [comment]
how it should have been not who... sorry about that :S

**Comment by iluks** [comment]
We could use UTC ... (gmt0  without summertime changes)

**Comment by juliushaertl** [comment]
According to the log output you are not using postgres but mysql as a database backend, right? In that case this is already fixed for the next release.

On the date format, that still needs to be solved in the frontend JavaScript code. We should pick the users language settings from Nextcloud and change to an appropriate date/time format.

**Comment by juliushaertl** [comment]
See #330 for the date formating.
