### ISSUE TITLE
Folder download not possible - NC 22.1.0 (since version before)

### ISSUE THREAD

**Issue by StefCGN** [nextcloud/deck#3297]
Hi,
i have the issue, when trying to download a folder, a blue page appears, which tells me, that the server is not able, to handle my request.
The server protocol says:
`[index] Error: Class "OCP\User" not found
GET /index.php/apps/files/ajax/download.php?dir=%2F&files=Video%C3%9Cberwachung&downloadStartSecret=hc8zzipl1k
from 195.212.58.200 by Stephan@Kreyenborg.koeln at 2021-08-24T12:35:59+02:00`

What does the OCP\User not found mean?

**Comment by AlthaTechnology** [comment]
Hey Filip,
Added the change to the file, and performed, "service apache2 reload" to reload the scripts. Still the same error.
Shared directories are not showing the files.
Checked the console and getting these:
PROPFIND https://cloud.althatech.com/public.php/webdav/ 500
GET https://cloud.althatech.com/ocs/v2.php/apps/text/public/workspace?path=%2F&shareToken=cfnmPWYToDE6wzM 404

Will continue poking around. Thanks Filip.

Jared

**Comment by AlthaTechnology** [comment]
Ok, disabling Deck does fix the issue. So must've been the most recent Deck update to version 1.5.1 . Is there a way to downgrade an app to previous version?

**Comment by juliushaertl** [comment]
This issue should have been fixed with deck 1.5.2
