### ISSUE TITLE
No upload in group folder possible if Deck is active

### ISSUE THREAD

**Issue by sebsoftware** [nextcloud/deck#3309]
[webdav] Fatal: Must be logged in to get the group limit
PUT /public.php/webdav/test_2021_09_09.txt
from 11.22.33.44 at 2021-09-09T09:33:08+00:00

The error happens, when dragging a file to a public available upload folder for a non logged in user.

**Nextcloud version:** Nextcloud 22.1.1

**Comment by q-wertz** [comment]
See https://github.com/nextcloud/deck/issues/3292 and https://github.com/nextcloud/deck/issues/3302

**Comment by juliushaertl** [comment]
Should be fixed with the latest release 1.5.2 / 1.4.4
