### ISSUE TITLE
Update `Latest release` flag

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/deck#3311]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
In github the `Latest release` flag still points to an old version (1.4.2). Also no release information is available anymore.

**Expected behavior**
It always points to the newest Deck version.

**Screenshots**
Start page:
![image](https://user-images.githubusercontent.com/20948931/132719464-a484144a-76ab-4a35-be8b-7e9a241d1324.png)
Release page:
![image](https://user-images.githubusercontent.com/20948931/132719521-1d7e4419-fd2a-4588-9965-cf2d9a766d00.png)

**Comment by juliushaertl** [comment]
Makes sense, the release archives have been moved to https://github.com/nextcloud-releases/deck/ but we should still create the releases here and link to the archive.

**Comment by splitt3r** [comment]
> Makes sense, the release archives have been moved to https://github.com/nextcloud-releases/deck/ but we should still create the releases here and link to the archive.

Maybe automate and unify everything. E. g. https://github.com/nextcloud-releases/mail/pulls this one has code and even automated pull request but https://github.com/nextcloud-releases/deck has only releases. What about unifying them all and disabling everything except releases? This way everyone knows what it's for and there is no distraction. Maybe also wirte a note in the description about why the whole organization even exists? That it is about sealed releases and security etc.?
