### ISSUE TITLE
Adding comment/listing comments for cards with big bugs

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/deck#3320]
* If I open the detail view of a deck card, and try entering a comment, it would not do anything when pressing on the right arrow to save.
* If I add a comment on a file in a folder, where the folder has been linked to a card through a joined project, funnily that comment that I added to the file is shown 5 times in the comment section of the deck card.

Thus, comment function not working at all for deck cards.

**Comment by stefan-niedermann** [comment]
Please fill out the complete issue template, check your logs and browser console, post the used Nextcloud, Deck and browser versions etc.
