### ISSUE TITLE
can't share a board to other users

### ISSUE THREAD

**Issue by lioooooh** [nextcloud/deck#3338]
![图片](https://user-images.githubusercontent.com/19770171/134778190-e7bbd4bf-a8f6-40bc-8a88-3656ec38d7a2.png)

this search bar will loading for ever

and it will have a error in log
like this

<html><body>

error | no app in context | Exception: in_array() expects parameter 2 to be array, null given/var/www/html/lib/private/AppFramework/App.php - line 156: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Sh ... {}, "search")/var/www/html/lib/private/Route/Router.php - line 301: OC\AppFramework\App::main("OCA\\Files_ ... r", "search", OC\AppFramew ... {}, { _route: "o ... "})/var/www/html/ocs/v1.php - line 62: OC\Route\Router->match("/ocsapp/app ... s")/var/www/html/ocs/v2.php - line 23: require_once("/var/www/html/ocs/v1.php")造成的原因是 TypeError: in_array() expects parameter 2 to be array, null given/var/www/html/apps/circles/lib/Collaboration/v2/CollaboratorSearchPlugin.php - line 101: in_array(10, null)/var/www/html/lib/private/Collaboration/Collaborators/Search.php - line 72: OCA\Circles\Collaboration\v2\CollaboratorSearchPlugin->search("", 20, 0, OC\Collabora ... {})/var/www/html/apps/files_sharing/lib/Controller/ShareesAPIController.php - line 228: OC\Collaboration\Collaborators\Search->search("", [ 0,1,4,7,12], false, 20, 0)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 217: OCA\Files_Sharing\Controller\ShareesAPIController->search("", "0,1,4,7", 1, 20, null, false)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 126: OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Sh ... {}, "search")/var/www/html/lib/private/AppFramework/App.php - line 156: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Sh ... {}, "search")/var/www/html/lib/private/Route/Router.php - line 301: OC\AppFramework\App::main("OCA\\Files_ ... r", "search", OC\AppFramew ... {}, { _route: "o ... "})/var/www/html/ocs/v1.php - line 62: OC\Route\Router->match("/ocsapp/app ... s")/var/www/html/ocs/v2.php - line 23: require_once("/var/www/html/ocs/v1.php")
-- | -- | --

</body>
</html>

![图片](https://user-images.githubusercontent.com/19770171/134778323-9fd64f25-c0fe-4bd8-8362-e06a42bce86b.png)

maybe it's about share or Contacts 

what's wrong with it ? who can help me ! thanks!

**Comment by stefan-niedermann** [comment]
Please fill out the complete issue template. It is there for a reason 😉.

**Comment by lioooooh** [comment]
Describe the bug
描述错误
can't share a board tu other users ，can‘t search anything  
不能将看版分享给其他人，表现为搜索不到任何结果

#### To Reproduce
再现
重现行为的步骤：

   1. click right edit icon，select search bar
   2. then you  will find，can’t show anyone 
   3. in the logs，will have a error log 。

#### Expected behavior
预期行为
it will show sombody in my mail list

Screenshots
截图

![图片](https://user-images.githubusercontent.com/19770171/135558383-2c7cac2c-55d4-4f8a-b0f2-555f48a9c528.png)
![图片](https://user-images.githubusercontent.com/19770171/135558419-114f2cfd-b86a-4949-b4ef-c787da4ae06e.png)

#### Client details:
客户详情：
    OS: windows 
    Browser  firefox（ 92.0.1 (64 位)）、Microsoft Edge（版本 93.0.961.38 (官方内部版本) (64 位)）
    Version 
    Device: desktop

    操作系统：windows 
    浏览器  firefox（ 92.0.1 (64 位)）、Microsoft Edge（版本 93.0.961.38 (官方内部版本) (64 位)）
    版本  
    设备：desktop

<summary>Server details</summary>
服务器详情

操作系统 ：windows

网络服务器：

数据库：

PHP版本：

Nextcloud 版本：Nextcloud 22.1.0

您从哪里安装 Nextcloud：docker

签约状态：
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
**No errors have been found.**


已激活的应用程序列表：

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
 - activity: 2.15.0
  - admin_audit: 1.11.0
  - apporder: 0.13.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.3
  - circles: 22.1.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - deck: 1.5.3
  - drawio: 1.0.1
  - event_update_notification: 1.3.0
  - external: 3.9.0
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.1
  - files_mindmap: 0.0.25
  - files_pdfviewer: 2.3.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - richdocuments: 4.2.3
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - twofactor_totp: 6.1.0
  - updatenotification: 1.11.0
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - accessibility
  - announcementcenter
  - checksum
  - contacts
  - contactsinteraction
  - encryption
  - federation
  - files_antivirus
  - files_bpm
  - files_fulltextsearch
  - files_rightclick
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - ldap_contacts_backend
  - mail
  - nextcloud_announcements
  - officeonline
  - photos
  - quicknotes
  - recommendations
  - richdocumentscode
  - spreed
  - support
  - twofactor_gateway
  - user_ldap
  - user_status

Nextcloud 配置：

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
'''
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8780",
            "127.0.0.1:8780",
            "140.xxxxxxxxxxxxxxxxxxx.198:8600",
            "sexxxxxxxxxxxxxxxxxxxxxxxxace:8600",
            "192xxxxxxxxxxxxxxxxx6:8780",
            "nextcloxxxxxxxxxxxxxxxxxxxxxxxce:8600"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.1.0.1",
        "overwrite.cli.url": "http:\/\/localhost:8780",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "files_bpm"
        ],
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "user",
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [
            "sync"
        ],
        "mail_smtpport": "465"
    }
}
'''
or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

您是否使用外部用户后端，如果是，是哪一个： LDAP/ActiveDirectory/Webdav/...

#### log
日志
Nextcloud 日志 (data/nextcloud.log)

Exception: in_array() expects parameter 2 to be array, null given

    /var/www/html/lib/private/AppFramework/App.php - line 156:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Sh ... {}, "search")

    /var/www/html/lib/private/Route/Router.php - line 301:

    OC\AppFramework\App::main("OCA\\Files_ ... r", "search", OC\AppFramew ... {}, { _route: "o ... "})

    /var/www/html/ocs/v1.php - line 62:

    OC\Route\Router->match("/ocsapp/app ... s")

    /var/www/html/ocs/v2.php - line 23:

    require_once("/var/www/html/ocs/v1.php")

造成的原因是 TypeError: in_array() expects parameter 2 to be array, null given

    /var/www/html/apps/circles/lib/Collaboration/v2/CollaboratorSearchPlugin.php - line 101:

    in_array(10, null)

    /var/www/html/lib/private/Collaboration/Collaborators/Search.php - line 72:

    OCA\Circles\Collaboration\v2\CollaboratorSearchPlugin->search("", 20, 0, OC\Collabora ... {})

    /var/www/html/apps/files_sharing/lib/Controller/ShareesAPIController.php - line 228:

    OC\Collaboration\Collaborators\Search->search("", [ 0,1,4,7,12], false, 20, 0)

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 217:

    OCA\Files_Sharing\Controller\ShareesAPIController->search("", "0,1,4,7", 1, 20, null, false)

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 126:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Sh ... {}, "search")

    /var/www/html/lib/private/AppFramework/App.php - line 156:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Sh ... {}, "search")

    /var/www/html/lib/private/Route/Router.php - line 301:

    OC\AppFramework\App::main("OCA\\Files_ ... r", "search", OC\AppFramew ... {}, { _route: "o ... "})

    /var/www/html/ocs/v1.php - line 62:

    OC\Route\Router->match("/ocsapp/app ... s")

    /var/www/html/ocs/v2.php - line 23:

    require_once("/var/www/html/ocs/v1.php")



#### Browser log
浏览器日志

Insert your browser log here, this could for example include:

![图片](https://user-images.githubusercontent.com/19770171/135560133-4dc78f18-81ed-4974-b985-9f8ed3011511.png)
![图片](https://user-images.githubusercontent.com/19770171/135560201-d28120a8-d56c-494e-9933-bb28ff4c5842.png)

**Comment by km1** [comment]
> Can you upgrade your Nextcloud ?

I have made an upgrade to versions _22.2.0-fpm-alpine_ and the Deck work properly. Thank you.
