### ISSUE TITLE
Cannot assign cards to circle members

### ISSUE THREAD

**Issue by mrtntome** [nextcloud/deck#3342]
**Describe the bug**
I can share a Board to a Circle, but can't assign Cards to Circle members.

**Steps to reproduce**

    1. Create a Circle
    2. Assign some users to the Circle
    3. Create a Board
    4. Share the Board with Circle
    5. Create a List and a Card on that List
    6. Open details of the Card
    7. Click on drop-down menu to assign the Card

**Expected behavior**
The drop-down menu shows the Circle members.

**Actual behavior**
Only my name and Circle is shown.

**Tested with**
- NC 22.1.1
- Deck 1.5.3
- Circles 22.1.1

**Comment by gerazo** [comment]
Same here also with:
- NC 22.2
- Deck 1.5.3
- Circles 22.1.1

We had a similar one before https://github.com/nextcloud/deck/issues/1237 but there, you could not even share "with the circle". I think it does make Deck very hard to be used with circles.

**Comment by gerazo** [comment]
Unfortunately, I do not see any activity on this in the 1.6.0 pre-release :(

**Comment by gerazo** [comment]
NC 23, 
Deck 1.6.0 
still has this problem.
The interesting thing however that it coexists with https://github.com/nextcloud/deck/issues/2717 so there is something definitely happenning when you share a Deck with a Circle, but the glitch is still there.

**Comment by jok2** [comment]
NC 23,
Deck 1.6.0

we also have this problem. worked with NC 21, broke after updating to NC 22.

**Comment by gerazo** [comment]
I can confirm. It is fixed in Deck 1.6.1
Thanks a lot!

**Comment by juliushaertl** [comment]
Thanks for the update, yes, this was indeed fixed by https://github.com/nextcloud/deck/pull/3526
