### ISSUE TITLE
Add list-specific permissions

### ISSUE THREAD

**Issue by eiclu** [nextcloud/deck#3345]
Right now, when allowing specific users/groups to edit a deck, they can edit every list on the deck.

For some use cases it can be beneficial, to have an option to allow users/groups to edit only a subset of lists in the deck. 

Use cases:

- **Financial records:** Everyone can submit a bill, but only an accountant may move them into the lists "approved" & "denied"
- **Issue Tracker:** Everyone can submit issues, but only developers may move them into the lists "To Do", "Doing", "Done

In order to move issues, the user has to have permissions in both the "from"-list and the "to"-list

**Comment by juliushaertl** [comment]
Thanks for your feature request. I can see this is a valid use case however we currently consider deck more as a simple tool that is easy to use and want to keep the complexity low. We target common use cases but don’t necessarily want to extend to a fully fledged project management tool. There are lots of good open source tools out there already for more complex use cases. Therefore I’d consider this out of scope.

It might be worth to have a look at the tables app  which would allow separate views with different permissions on a shared dataset.
