### ISSUE TITLE
The due date is not set in some cards 

### ISSUE THREAD

**Issue by ArtemDrach** [nextcloud/deck#3363]
Can't set a due date on some of the new cards.
NC 22
Deck 1.5.3

In the logs: 

Exception: Argument 2 passed to OCA\Notifications\Handler::deleteById() must be of the type string, int given, called in /var/www/nc/public_html/apps/notifications/lib/Handler.php on line 113

    /var/www/nc/public_html/lib/private/AppFramework/App.php - line 156:
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Deck\Con ... {}, "update")
    /var/www/nc/public_html/lib/private/Route/Router.php - line 301:
    OC\AppFramework\App::main("OCA\\Deck\\ ... r", "update", OC\AppFramew ... {}, { cardId: "2 ... "})
    /var/www/nc/public_html/lib/base.php - line 1000:
    OC\Route\Router->match("/apps/deck/cards/20")
    /var/www/nc/public_html/index.php - line 36:
    OC::handleRequest()

По причине TypeError: Argument 2 passed to OCA\Notifications\Handler::deleteById() must be of the type string, int given, called in /var/www/nc/public_html/apps/notifications/lib/Handler.php on line 113
    /var/www/nc/public_html/apps/notifications/lib/Handler.php - line 113:
    OCA\Notifications\Handler->deleteById(239, 87013991125, OC\Notification\Notification {})
    /var/www/nc/public_html/apps/notifications/lib/App.php - line 78:
    OCA\Notifications\Handler->delete(OC\Notification\Notification {})
    /var/www/nc/public_html/lib/private/Notification/Manager.php - line 360:
    OCA\Notifications\App->markProcessed(OC\Notification\Notification {})
    /var/www/nc/public_html/apps/deck/lib/Db/CardMapper.php - line 106:
    OC\Notification\Manager->markProcessed(OC\Notification\Notification {})
    /var/www/nc/public_html/apps/deck/lib/Service/CardService.php - line 355:
    OCA\Deck\Db\CardMapper->update("*** sensiti ... *")
    /var/www/nc/public_html/apps/deck/lib/Controller/CardController.php - line 98:
    OCA\Deck\Service\CardService->update("*** sensiti ... *")
    /var/www/nc/public_html/lib/private/AppFramework/Http/Dispatcher.php - line 217:
    OCA\Deck\Controller\CardController->update("*** sensiti ... *")
    /var/www/nc/public_html/lib/private/AppFramework/Http/Dispatcher.php - line 126:
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Deck\Con ... {}, "update")
    /var/www/nc/public_html/lib/private/AppFramework/App.php - line 156:
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Deck\Con ... {}, "update")
    /var/www/nc/public_html/lib/private/Route/Router.php - line 301:
    OC\AppFramework\App::main("OCA\\Deck\\ ... r", "update", OC\AppFramew ... {}, { cardId: "2 ... "})
    /var/www/nc/public_html/lib/base.php - line 1000:
    OC\Route\Router->match("/apps/deck/cards/20")
    /var/www/nc/public_html/index.php - line 36:
    OC::handleRequest()

**Comment by juliushaertl** [comment]
Are you using numeric user ids by any chance and 87013991125 would be one that a user has on the board?

**Comment by juliushaertl** [comment]
The trace looks like the user is passed as an integer but I'm not sure why that would be the case when it is just coming from the database:

https://github.com/nextcloud/notifications/blob/5531cab0f32b09a93743312331e5ab3db4c51ecd/lib/Handler.php#L89-L113

**Comment by ArtemDrach** [comment]
Username - phone number
Display name - full name

**Comment by juliushaertl** [comment]
Could only be cards where users still have a notification present for

**Comment by juliushaertl** [comment]
Can you share which database backend you are using?

**Comment by ArtemDrach** [comment]
10.6.4 - MariaDB
PHP - 7.4.24

**Comment by ArtemDrach** [comment]
If I first set the due date in the new card, then it is set.

If in a new card I first assign a user and then a due date, then the date is not set and an error occurs.

**Comment by ArtemDrach** [comment]
https://github.com/nextcloud/notifications/pull/1087/files

**Comment by juliushaertl** [comment]
For easier reference on the other PR https://github.com/nextcloud/notifications/pull/1087

Let me close this then here as it is a notifications app bug then.
