### ISSUE TITLE
JavaScript files should use tabs

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#338]
Some javascript files still have some spaces instead of tabs.

**Comment by jmealo** [comment]
Is it too late to persuade the project to use a well-adopted community supported JavaScript style guide? If so, may I ask for what reason?

**Comment by juliushaertl** [comment]
@jmealo We use the default Nextcloud style as described in https://docs.nextcloud.com/server/12/developer_manual/general/codingguidelines.html There might be some parts where this still needs to be fixed.

**Comment by jmealo** [comment]
@juliushaertl: "Use tabs to indent" "A tab is 4 spaces wide" ... So, files should be indented with four spaces, not the tab character, correct?

**Comment by juliushaertl** [comment]
> A tab is 4 spaces wide

@jmealo I would say this is only how the tabwidth should be set in your editor. Tabs are indeed what is used in all nextcloud code i came across.

**Comment by jmealo** [comment]
@juliushaertl: Thanks for the clarification. This is the first time I've encountered anyone arguing for tabs. I just wanted to make sure that I understood.

**Comment by juliushaertl** [comment]
Fix is in #343
