### ISSUE TITLE
"Assign a user to this card…" and "Share board with a user, group or circle …" is not working, 

### ISSUE THREAD

**Issue by rickant0** [nextcloud/deck#3396]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When I try to add a user, group or circle to a board or a list, the search option never return any result, still loading forever. 

**To Reproduce**
1. Go to a board or a list details
2. Click on Sharing option or assign to a user
3. Scroll down to type the name of an existing user, group, circle
4. Search box never return any value.

**Expected behavior**
I wait for the list of user, groups, circles created on the nextCloud installation.

**Screenshots**

**Client details:**
 - OS: 
 -  - Browser [e.g. chrome, safari]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Operating system:** Linux Ubuntu 5.4.0-66-generic x86_64 Intel Core Processor (Skylake, IBRS) (2 cores)

**Web server:** Apache 2.4.41

**Database:** mySql 8.0.26

**PHP version:** PHP 7.4.3

**Nextcloud version:** 22.1.0.1

**Where did you install Nextcloud from:**

**Signing status:** ok 200 OK 22.1.0.1 none yes yes none none yes none no 57072271360 0.11 0.06 0.01 4030596 2132848 0 0 65 0 2 587 2 1 2 0 0 0 0 0 0 0 0 0 0 Apache/2.4.41 (Ubuntu) 7.4.3 134217728 3600 2097152 1 56329880 66980336 10907512 8.1267297267914 6291008 6290016 992 101391 3012 5712 16229 2920950 1635465601 0 0 0 0 3925 0 0 99.865806231036 mysql 8.0.26 2990080 1 1 1

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:
GET http://127.0.0.1/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/sharees?search=dev&format=json&perPage=20&itemType=0%2C1%2C4%2C7&lookup=false 404 (Not Found)
Uncaught (in promise) Error: Request failed with status code 404
    at t.exports (createError.js:16)
    at t.exports (settle.js:17)
    at XMLHttpRequest.A.onreadystatechange (xhr.js:62)
t.exports @ createError.js:16
t.exports @ settle.js:17
A.onreadystatechange @ xhr.js:62
Promise.then (async)
p @ deck-main.js?v=1aceb865-0:2
o @ deck-main.js?v=1aceb865-0:2
(anonymous) @ deck-main.js?v=1aceb865-0:2
(anonymous) @ deck-main.js?v=1aceb865-0:2
(anonymous) @ SharingTabSidebar.vue:152
v @ debounce.js:95
_ @ debounce.js:144
C @ debounce.js:132
setTimeout (async)
b @ debounce.js:103
x @ debounce.js:172
(anonymous) @ SharingTabSidebar.vue:158
l @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.t.<computed> @ runtime.js:97
p @ deck-main.js?v=1aceb865-0:2
o @ deck-main.js?v=1aceb865-0:2
(anonymous) @ deck-main.js?v=1aceb865-0:2
(anonymous) @ deck-main.js?v=1aceb865-0:2
(anonymous) @ SharingTabSidebar.vue:151
Qt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
Qt @ vue.runtime.esm.js:1863
t.$emit @ vue.runtime.esm.js:3903
search @ vue-multiselect.min.js:1
Qt @ vue.runtime.esm.js:1863
yn.run @ vue.runtime.esm.js:4584
vn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
te @ vue.runtime.esm.js:1915
Promise.then (async)
qt @ vue.runtime.esm.js:1942
ie @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
yn.update @ vue.runtime.esm.js:4560
At.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
Cn.set @ vue.runtime.esm.js:4644
deactivate @ vue-multiselect.min.js:1
blur @ vue-multiselect.min.js:1
Qt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
Tr.i._wrapper @ vue.runtime.esm.js:6961
4util.js:135 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:135
(anonymous) @ init.js:101
each @ jquery.js:354
each @ jquery.js:189
(anonymous) @ init.js:100

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliangommers** [comment]
It looks like issues #3387 and #3338 describe the same issue.
As mentioned there; an upgrade to 22.2.0-fpm-alpine version might resolve the issue.

**Comment by juliushaertl** [comment]
Closing as this is fixed with the currently supported versions.
