### ISSUE TITLE
notifications no link

### ISSUE THREAD

**Issue by Energiegenossenschaft** [nextcloud/deck#3404]
Unfortunately, the deck notifications no longer show links to the corresponding board. This way, it is no longer possible to track which board the message belongs to when someone writes a comment. Previously, this function was included. You could click on the text in the notification and was redirected to the corresponding card / board.

**Comment by stefan-niedermann** [comment]
Please fill out the issue temate, it is there for a reason. Otherwise we have to ask the same questions over and over again, for example which versions of Nextcloud and Deck you are using.

**Comment by Jeanoo** [comment]
In the past I also reported this problem, with screenshots, but nothing was done

**Comment by stefan-niedermann** [comment]
@Jeanoo would you mind linking your issue here then?

**Comment by Energiegenossenschaft** [comment]
Deck: 1.4.5
Nextcloud: 21.0.4

**Comment by juliushaertl** [comment]
This has been implemented with https://github.com/nextcloud/deck/pull/2935 but the backport to 1.4.x was not released yet, but will become part of the next maintenance release.
