### ISSUE TITLE
Only show the linked resource

### ISSUE THREAD

**Issue by mokkin** [nextcloud/deck#3405]
In the share view of a deck board other resources such as files or folders can be linked like in the example below. To create a clearer view only the linked resource (folder in this case) should be shown, but not the deck board itself.
The same is valid vice versa for the files app.

![grafik](https://user-images.githubusercontent.com/2938748/140390080-e5cf6b8a-e963-47ab-b3ac-81905a8d1de2.png)

**Comment by juliushaertl** [comment]
Makes sense, could you please open an issue about that in https://github.com/juliushaertl/nextcloud-vue-collections which is the shared library which is used for rendering the project list?

**Comment by mokkin** [comment]
Moved to https://github.com/juliushaertl/nextcloud-vue-collections/issues/769
