### ISSUE TITLE
sort boards non case sensitive

### ISSUE THREAD

**Issue by mokkin** [nextcloud/deck#3410]
Boards should be sorted non case sensitive as sometimes names are just correct or clearer written lowercase.

![image](https://user-images.githubusercontent.com/2938748/140550184-52af956e-09da-4652-8b25-00f3ce9ce393.png)

**Comment by Ben-Ro** [comment]
Hey,
i encountered the same issue and think i found the problem. The sorting in the computed array ```boardsSorted``` wasn't with with the localeCompare method which is for case-insensitive sorting. With the fix a list of boards like the one in the Issue should look like this:
<img width="301" alt="Bildschirmfoto 2022-01-26 um 20 23 11" src="https://user-images.githubusercontent.com/22852640/151232086-e9b91785-c3db-4aa3-a011-4122a6023551.png">
