### ISSUE TITLE
V1.5.4 broken? Screen emtpy.

### ISSUE THREAD

**Issue by koppd** [nextcloud/deck#3417]
After updating to 1.5.4 the app "deck" isn't working anymore.
The screen remains emtpy:

![grafik](https://user-images.githubusercontent.com/12296685/141159124-d7922c30-cc75-4dbd-b7a9-7c3231060026.png)

I have a second Nextcloud installation in a VM and it happens there, too.

**Environment:**
 - OS: Linux, openSUSE Tumbleweed, Apache as Webserver
 - Browser: Firefox, Edge
 - Device: desktop
 - Nextcloud 22.2.0

**Comment by HAF-Blade** [comment]
I've got the same issue after the update.
I get the following error message in the logs:

Required parameter $owner follows optional parameter $order at /var/www/nextcloud/apps/deck/lib/Controller/CardApiController.php#97

**Comment by vantino** [comment]
Wonderful, an update crashes the app, "echt toll".

I am running NC 22.2.0

**Comment by wemsras** [comment]
I have the same issue after upgrade to 1.5.4 empty screen
OS: MacOS
Browser: Safari + Firefox

**Comment by Nanouk171** [comment]
Same issue for me after upgrade.. :(
OS Server: Debian Buster
Tested on Opera, Chrome, Firefox (Ubuntu 21.04)

**Comment by pretorian91** [comment]
Same error here.

OS Server: Ubuntu 21.04
Browser: firefox, edge, chrome
Nextcloud 22.2.0

**Comment by stefan-wallner** [comment]
Same issue for me

OS Server: CentOS 8
Browser: firefox, chrome
Nextcloud 22.2.0

**Comment by Normand-Nadon** [comment]
Same issue Here and it is major!
Nextcloud 21.0.3
Running in a docker environment on Ubuntu server

This should get a red flag... App is unusable after update!

**Comment by juliushaertl** [comment]
Looking into this, thanks for reporting everyone.

**Comment by leonardohlee** [comment]
same Issue here.
OS Ubuntu 20.04 , 
nextcloud 22.2

**Comment by LarsJaensch** [comment]
Same

**Comment by juliushaertl** [comment]
New releases have been pushed out as the release built has had an issue with not including the frontend assets, this should now be fixed with 1.2.11, 1.4.7 and 1.5.5.

**Comment by HAF-Blade** [comment]
Thx for the fast fix. I'm looking forward to try it out. :)

**Comment by wemsras** [comment]
Thanks for the fix. Danke schön. 
All cards are shown.

**Comment by Nanouk171** [comment]
Thx a lot :)
it's work.
