### ISSUE TITLE
Notifications on change

### ISSUE THREAD

**Issue by PieterHollevoet** [nextcloud/deck#344]
To be able to use the deck as a team : 
When a user changes the description the subscribed or user mentioned users should get an notification.

**Comment by juliushaertl** [comment]
As a first step i would like to add activities for changes on cards, as it is done for calendar/tasks already. But yes, it should also be possible to receive notifications on changes if wanted.

**Comment by juliushaertl** [comment]
In case https://github.com/nextcloud/activity/issues/217 will be implemented into the activities app, we would not need any further adjustments in the deck app.

**Comment by juliushaertl** [comment]
As discussed in the activity feature request, notifications should only be used for actions to be taken by the user. Let's focus on implementing the activities for the changes on cards. That way you can view the changes in your activity stream. 

Another point i added to https://github.com/nextcloud/deck/issues/286 is that users should be able to sort cards by last modification date, so you easily see what cards have recently be changed.
