### ISSUE TITLE
Show board name in browser title

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/deck#3448]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When having multiple tabs open with Decks it's always hard to find back the correct one.

**Describe the solution you'd like**
The board title could be added to the browser title similar to talk's conversation names

**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment]
Seems to have closed by accident?
The PR is still open and the second PR seems unrelated?

**Comment by juliushaertl** [comment]
Indeed #3501 had the wrong reference
