### ISSUE TITLE
Feature Request: Global Tasks Open List

### ISSUE THREAD

**Issue by compumatter** [nextcloud/deck#345]
Hello,

I do not find a Feature Request area so I am posting it here.

At present I see no way to view global tasks for all projects.  This is of value with any project management software as it allows you to know what is a priority for this day. 

I would like to recommend this feature be implemented

Jay
CompuMatter

**Comment by juliushaertl** [comment]
Thanks for your feature request. We have discussion about this in #12. Let's continue there.
