### ISSUE TITLE
1.6.0-beta3: upcoming cards view is empty

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/deck#3451]
On every call I get this message:
Exception: count(): Argument #1 ($value) must be of type Countable|array, null given in file '/var/www/nextcloud/apps/deck/lib/Service/OverviewService.php' line 116

**Comment by juliushaertl** [comment]
Thanks for reporting and testing the beta :) I can reproduce this on my personal instance though not yet on my local development setup. Will keep investigating.
