### ISSUE TITLE
Search dialogue: German translation missing or not showed

### ISSUE THREAD

**Issue by ossie** [nextcloud/deck#3474]
**Bug**
In v1.4.7 the search dialogue shows english translation strings inside a german located Nextcloud environment. 

**Expected behavior**
Should show german translations.

**Screenshots**
![image](https://user-images.githubusercontent.com/462735/144809208-b1deb8ca-d1f3-41c8-87e6-4cae515286a4.png)
![image](https://user-images.githubusercontent.com/462735/144809566-26798df8-cdec-436e-8acc-63aafac593ae.png)

**Client details:**
 - OS: Windows
 - Browser: Chrome
 - Version: 96.0.4664.45
 - Device: Desktop

**Comment by stefan-niedermann** [comment]
cc @rakekniven

**Comment by rakekniven** [comment]
There have been few updates after v1.4.7 has been released.

Are you able to update to v1.6.0 and check if this is still the same?

**Comment by ossie** [comment]
We are still on NC 21 which is still a supported version. And v.1.4.7 is the latest release for NC 21.

**Comment by rakekniven** [comment]
Yes, understood. The thing I can tell you is, that the string is translated at the translation tool (transifx) and the screenshot I provide shows that it is fixed for v1.4.7 .

If you have a service contract for your NC you can open a ticket and ask for support.
