### ISSUE TITLE
Username when adding file to card 

### ISSUE THREAD

**Issue by ArtemDrach** [nextcloud/deck#3476]
Hello everyone.

I have a situation like this:
My username = phone number.
Display name = First name + Last name

When adding a file to the card, the usersname is written next to it.

Is it possible to do this so that the user's display name is written? 

Nextcloud 22.2.3

**Comment by dodedodo** [comment]
This might be somewhat related to #3389?

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/deck/pull/4036
