### ISSUE TITLE
Some unicode is replaced with �

### ISSUE THREAD

**Issue by qoheniac** [nextcloud/deck#3483]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
In descriptions some unicode characters are replaced with � but not in card titles for example.

**To Reproduce**
1. Open a card
2. Edit the description
3. Write 🚗
4. View the description
5. 🚗 is replaced with �

**Expected behavior**
The symbol stays the same.

**Client details:**
 - OS: Fedora 95
 - Browser: Firefox 95

**Server details:**
- Nextcloud 22.2.3
- Deck 1.5.5

**Comment by dodedodo** [comment]
If you're using MariaDB/MySQL: Maybe it has something to do with collation? I think It should be set to utf8mb4* to support emoji's.

This MySQL query shows you the collation of all deck tables, but you might need to edit the prefix (oc_) to match your setup. It should return utf8mb4_[something] for every table. Mine is utf8mb4_bin. I'm not sure what the differences between   _bin and _general_ci are exactly. 

``` MySQL
SELECT TABLE_NAME, TABLE_COLLATION FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'oc_deck%';
```

[Nextcloud docs on utf8mb4](https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html)

**Comment by qoheniac** [comment]
Oh, you were right it was set to `utf8_general_ci`. I changed it to `utf8mb4_general_ci` and know it works fine. Thank you for your support.
