### ISSUE TITLE
Assign a card to a team member (Feature Request)

### ISSUE THREAD

**Issue by wYhyzByH** [nextcloud/deck#349]
Hi

I really like this app. It's easy to use and looks good.

But in the current state it's useful for personal use or showing progress. But to work in a team, it would be great to be able to assign cards to persons in the groups/people this board is shared with.

I could not figure out how to do it. So I guess this is a new feature request.

If there is a way to do it already, let me know and I'm happy to augment the documentation in the wiki accordingly.

Thanks and best regards!

**Comment by juliushaertl** [comment]
This feature has already been implemented in #314 and will be there in the next release.
