### ISSUE TITLE
Improved usability in mobile browsers

### ISSUE THREAD

**Issue by poVoq** [nextcloud/deck#35]
There are a few issues with usability and rendering in mobile browsers.

Show stoppers are mainly that there is no drag & drop to move cards, so maybe there could be an alternative way to move cards between stacks via a drop-down menu of some sort?

The other thing is that you have to scroll horizontally a lot, which is not working so well especially as the left-hand menu is triggering it's slide to open feature all the time. Maybe the stacks could be automatically rearranged vertically in a mobile browser?

**Comment by juliushaertl** [comment]
@poVoq Thanks for the comments. Drag and drop works if you hit the right spot, but mobile really needs some improvements. 

> Maybe the stacks could be automatically rearranged vertically in a mobile browser?
I'm not sure if I get that right. Can you describe that a bit more in detail?

**Comment by poVoq** [comment]
Instead of having to scroll horizontally through the stacks, just put them on top of each other in mobile mode so that you can scroll vertically.

**Comment by mr-bolle** [comment]
Hi juliushaertl, thanks for your greath work. 
The last days i check the mobile browser usability.

- Board Details: it isn't possible to share a Board with other user/groups if i use the Deck in Portait-Mode from the Mobile Device. If i change the Screen rotation to Landscape-Mode i can use this Option.
![deck_nextcloud](https://cloud.githubusercontent.com/assets/22414212/23569917/2b821286-0062-11e7-9adb-0d95ae799358.png)

- delete (Stack, Boards): the rename icon is realy close to the trash basket. And it could easy happend to delete the whole Board. A additional confirmation will be helpfull, and don't destroy the work.

- Board Menu overlay: if i would change the Label/Card Description the Card Tile is overlayed from the Board Menu Icon
![deck_nextcloud 2](https://cloud.githubusercontent.com/assets/22414212/23571682/dcb89e32-006a-11e7-895a-3f22ff9f9615.png)

**Comment by octo777** [comment]
Just discovered Deck. Great work. I am excited to see how it develops.  So far for me chrome in android, I can grab the card, but it takes off to the left and scrolls to the beginning of the page and I can drop it in the first deck, but I can never get it to move to the right. If I move to the right edge of the screen, it just doesn't scroll at all.  I could have managed to move it one stack at a time since you can see two at a time, if it wasn't for the fact that when you pick up a card, it auto scrolls you quickly to the left.

**Comment by bjornnorman** [comment]
I did a test with using masonry for deck layout in stead of the horizontal lineup - it works great and looks awesome with the smooth transitions when rearranging the decks :) It also caused the decks to align vertically on mobile, but being able to set deck order is still a must. For mobile, in my opinion, ordering cards (and decks) would be much more user friendly if we required "hold" for 1 or 2 seconds before releasing the object for moving. That way we avoid the accidental rearranging of items when scrolling up and down on the page.

**Comment by pixelipo** [comment]
I would not go with masonry unless it's really the only way to solve a problem.

By the way, this issue seems to be discussing several different problems. Maybe it's worth splitting into smaller issues that can be tackled independently.

**Comment by juliushaertl** [comment]
Right, I've moved the drag-and-drop thing over to #156.
Please open new issues for any mobile related. Small bugs are easier to fix when you don't have to read a long discussion first.

I think all issues from @mr-bolle were fixed recently.
