### ISSUE TITLE
Import system for deck data

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#3507]
Export is currently possible as a custom json file through occ. It should be possible to import such files through the import handling implemented in #3182 by adding an implementation to properly handle the json format.

**Comment by benjamindahl** [comment]
definetely needed

**Comment by juliushaertl** [comment]
Done as occ command in https://github.com/nextcloud/deck/pull/4939

**Comment by alexanderdd** [comment]
starting with NC 32.0.0.9 it is also possible to export/import via GUI, but not in user docs yet https://deck.readthedocs.io/en/latest/User_documentation_en/

occ export/import is documented here https://github.com/nextcloud/deck/blob/main/docs/export-import.md
