### ISSUE TITLE
Any plan to support pandoc flavored markdown ?

### ISSUE THREAD

**Issue by touchft** [nextcloud/deck#3509]
The **pandoc** is a powerful tool to convert doc/text formats and **pandoc flavored markdown** has more features. Is there Any plan to support **pandoc flavored markdown** ?

**Comment by nidico** [comment]
For those wondering about "pandoc flavored markdown", see https://pandoc.org/MANUAL.html#pandocs-markdown

Deck seems to use an extended version of CommonMark according to https://deck.readthedocs.io/en/latest/Markdown/

**Comment by juliushaertl** [comment]
Yes, there are currently no plans to implement any other markdown standard besides CommonMark, also in regards to a possible integration of Nextcloud Text [#1663](https://github.com/nextcloud/deck/issues/1561)
