### ISSUE TITLE
"status" reporting in calendar interface

### ISSUE THREAD

**Issue by mortee** [nextcloud/deck#3556]
It sort of makes sense that cards only show up in calendars read-only. However, the fact that their status appears to be a fix "needs action" is less useful. I think that cards in certain lists, like "Done" should show up in the claendar as completed. Maybe it could be an additional porperty of a list whether it is considered as completed? Or, better yet, which iCal status value the list corresponds to, if any.

**Comment by stefan-niedermann** [comment]
Please use the :mag: search function before opening new issues.
- [`Done` state for cards](https://github.com/nextcloud/deck/issues/534)
- [Calensar integration with `Write` access](https://github.com/nextcloud/deck/issues/2399)

**Comment by mortee** [comment]
For what it's worth, I _did_ use the search function. Not knowing any better, I searched for issues about "calendar", but neither has that in their title.
