### ISSUE TITLE
Add "done" property to list -> hide them in the overview

### ISSUE THREAD

**Issue by Export33** [nextcloud/deck#3558]
I have some lists

* todo
* doing
* done

After putting my card  to done it is still shown in my "Upcoming Cards".
You should be able to set a property "set as done" or "hide from overview" to a  list in order to hide it in the upcoming cards view without manually archiving the card. 

Another property to autmatically archive the card when put to a list "Archive" would also be cool but in my main use-case i wan´t to see what´s done (not in the archive) without having it marked as overdue in the overview.

![grafik](https://user-images.githubusercontent.com/25232960/151047321-7babe51f-30e9-460c-9e2b-3613daca5d7c.png)

![grafik](https://user-images.githubusercontent.com/25232960/151047272-ebc08d67-8654-4f90-8830-7ff4b55aecbb.png)

**Comment by stefan-niedermann** [comment]
Please use the 🔍 search function before opening new issues.

There is large discussion with various different approaches and a summary in one of the recent comments in https://github.com/nextcloud/deck/issues/534. Please read at least the summary or even better the whole thread to understand the pros and contras of each proposal.
