### ISSUE TITLE
Add a preference / setting to have a filtered view per default which only shows cards that are assigned to the user or are not assigned to anybody

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/deck#3559]
**Is your feature request related to a problem? Please describe.**
When using deck for some projects the board can become quite cluttered and users start complaining that deck is much more confusing than simple task lists or others tools. In such projects oftentimes only the project manager regularly needs the full view, while many project members only need to see their own cards (or maybe their own and unassigned cards) when not in a review, meeting etc.  

**Describe the solution you'd like**
Because of the reason above it would be really useful if users can switch a setting per board, that they get a prefiltered view per default. This setting could have three or even better four options:

 1. show all cards per default
 2. only show own and unassigned cards per default
 3. only show own cards per default
 4. show last view per default

They then would have to spend a few seconds each time they enter a board to readjust the setting.

**Describe alternatives you've considered**
An alternative solution would be to save the last view to that this is the default in any case until the filter is cleared; but I would prefer the solution above because I think its oftentimes more helpful if the users just sees those tasks he's working on per default.

**Comment by dodedodo** [comment]
These filter options are already there, just not enabled by default or remembered. 

I think that's is a good thing. I wouldn't want to accidentally miss a card because I forgot to turn off a filter last week.

**Comment by lars-becker** [comment]
> EDIT: This is a duplicate of #2861, but I think you figured that out already wink.

Hmm, I read it again. I guess you're right and it is a duplicate. Hadn't read it carefully enough and though the author of that issue just wanted predefined filters like toodledo or others have it. But you're right. This ticket is a subset of #2861
