### ISSUE TITLE
Deck for 13

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/deck#356]
I updated to the latest version for 12 (0.2.8) on a Nextcloud 12. After an upgrade to 13 it disables this app, and says, that it is no longer compatible. Could you provide a version that is installable and upgradeable from 0.2.8 to support 13?

cc @juliushaertl

**Comment by juliushaertl** [comment]
Since NC13 needed a lot work on the left sidebar menu which I decided was to much to be backported to our 0.2 branch. I'll do a beta release of 0.3 by the end of the week.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by juliushaertl** [comment]
Here we go: https://help.nextcloud.com/t/help-testing-the-new-deck-version-0-3-beta/24850
