### ISSUE TITLE
Not seeing Board in Calendar

### ISSUE THREAD

**Issue by jpmv27** [nextcloud/deck#3562]
**Describe the bug**
A board in Deck is showing up in Tasks but not in Calendar

**To Reproduce**
1. Create a Board in Deck
2. Make sure that "Show boards in calendar/tasks" setting is checked
3. Switch to Calendar
4. No Calendar corresponding to Board

**Expected behavior**
A separate Calendar for the Board

**Client details:**
- NextCloud 22.2.3
- Deck 1.5.5
- Calendar 3.0.5
- "Show tasks in Calendar" setting is NOT enabled

Expected behaviour above is based on other comments I have seen. Perhaps
I am missing or misunderstanding something?

**Comment by joshtrichards** [comment]
Works for me today. 

Not sure why experienced this at the time. Might have been a bug or... there is an additional setting in Calendar's own settings labeled "Show tasks in Calendar" that *also* needs to be on (in addition to the one you mentioned in Deck itself).

Feel free to ping back if you're still experiencing this behavior today and I'll re-open/revisit.

**Comment by jpmv27** [comment]
Well, if "Show tasks in Calendar" must be on, that explains it. As I stated, I did not have this setting on.

So there is no way to have Boards in the Calendar without Tasks?
