### ISSUE TITLE
Feature request: Assign task to a user

### ISSUE THREAD

**Issue by messalas** [nextcloud/deck#357]
I would be a nice feature, if the manager of a group could assign tasks to the users he manages.
When the manager assigns a task, then the user will get notified from announcement center and by email.

```
**Operating system**: Ubuntu 16.04
**Web server:** Apache 2
**Database:** MySQL
**PHP version:** 7.0.22
**Nextcloud version:** 12.0.4
**Deck version:**  	0.2.8
```

**Comment by juliushaertl** [comment]
Duplicate of #11 
Will be there in the next release 😉

**Comment by messalas** [comment]
Great! thanks a lot for the reply!
