### ISSUE TITLE
Unable to add any user to deck card

### ISSUE THREAD

**Issue by posix4e** [nextcloud/deck#3570]
**Describe the bug**

I am Unable to add any user to deck card and there’s no documentation about it

**To Reproduce**
1. Create a new deck
2. Click on add user
3. You wont see any
**Expected behavior**
All local users should show up. You should have the ability to select a circle

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Operating system**:

Linux 4.14.252

**Web server:**

**Database:**
10.14 pg
**PHP version:**
7.4.19
**Nextcloud version:** (see Nextcloud admin page)
21.0.1
**Where did you install Nextcloud from:**

serverless nextgen implementation example,

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by jakobroehrl** [comment]
You have to share the board with some user before you can add these users to a card

**Comment by stefan-niedermann** [comment]
Maybe the UX can be improved here, for example by suggesting all users and if a user is  chosen which is not in the list of sharees, a dialog can ask to add this user?

**Comment by posix4e** [comment]
Let’s add to docs and close the issue
