### ISSUE TITLE
in Bigger Card view - not possible to add comments nor to edit

### ISSUE THREAD

**Issue by theCreativeMind-mrTP** [nextcloud/deck#3571]
**Describe the bug**

I prefer to use the bigger view whilst working with card … yet the commenting function is not working, nor i can add comment, nor edit existing one - when i am on side view it is all working fine

**Client details:**
 - OS: MacOs
 - Browser chrome, safari, 
 - Version 22.2.3 Enterprise
 - Device: MBPro 16

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
22.2.3 Enterprise - managed NC installation at IONOS

**Comment by Pietro-Aretino** [comment]
OS: Windows 10
Browser: Firefox, Chrome
Nextcloud Version: 24.0.12
Deck Version:  1.7.4

I am having the same issues. Modify and Reply functionality in comments does not work in "Big Card" mode.

When one attempts to click on "Reply" or "Modify" nothing happens. Clicking does nothing.

Once you disable "Big Card" mode, the buttons function properly, and one is able to "Reply" or "Modify" in the comment section.

**Comment by joshtrichards** [comment]
Not sure why you both experienced this, but it's definitely not the case today. Big card mode is the default mode. If you're still encountering this, troubleshoot a bit via the help forum - https://help.nextcloud.com
