### ISSUE TITLE
leave comments in  deck, but it did  not show up by real-time

### ISSUE THREAD

**Issue by czjjwx** [nextcloud/deck#3585]
[Nextcloud](https://nextcloud.com/) 22.2.3    
plugin   Version: TrueNAS-12.0-U8 

A user leave comments in deck card. The another user will not be able to see it if the user didn't refresh the card. So, you will miss some information. It's not convenience.  I don't know how to setup it.

Thank you

**Comment by joshtrichards** [comment]
Fixed in #4273
