### ISSUE TITLE
Wrong rendering of nested checkbox lists

### ISSUE THREAD

**Issue by a-mair** [nextcloud/deck#3637]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
After updating to NextCloud 23 and Deck 1.6.0 nested checkbox lists no longer render correctly.

**To Reproduce**
Add a new card, set description to:
```
- [ ] a
	- [ ] a.a
- [ ] b
* x
	* x.x
* y
```
**Expected behavior**
This used to indent option "a.a", but now it's no longer indented. This makes it hard to distinguish both. It works for simple lists ("x.x").

**Screenshots**
![Screenshot_20220312_094058](https://user-images.githubusercontent.com/13726027/158010817-4f18fc2c-c692-4da2-94db-e8daa556789d.png)

**Client details:**
 - OS: Gentoo Linux
 - Browser Firefox 97, Chrome 99
 - Device: desktop

<details>
<summary>Server details</summary>
**Operating system**: Gentoo Linux

**Web server:** nginx

**Database:** mariadb

**PHP version:** 8.0

**Nextcloud version:** 23.0.2.1
</details>

<details>

**Comment by flummer** [comment]
Looks like this line is the culprit:

https://github.com/nextcloud/deck/commit/0fcbe2cb47a77c748a25e188953e7ad025e340f1#diff-df4c0a65a3465bff9b48533e35d4da7fd687e7875a61482850cdf7cd32f03a29R26

though having it seems correct, to move the checkbox left, and eliminate the extra margin.

Maybe adding this to the file ([src/css/markdown.scss](https://github.com/nextcloud/deck/blob/master/src/css/markdown.scss)) will solve it:

```css
li ul {
    margin-left: 40px;
}
```

**Comment by a-mair** [comment]
You are right! That change fixes it. Thanks!
