### ISSUE TITLE
suggestion: same color of the board-bullet in the title and in the left sidebar

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#364]
This is not a issue, just a suggestion 

### Steps to reproduce
1. create a new board in deck 0.3 beta with color  #00C906 (green)
2. open the new board

### Expected behaviour
the color of the board-bullet in the title is the same as the color of the board-bullet in the left sidebar

### Actual behaviour
The color in the sidebar is #00C906, the color in the title is lighter (#80E483). It's not obvious at first sight, to which board in the sidebar the active board corresponds, cause there is a darker color.

**Comment by pixelipo** [comment]
I don't think that fits with the design guidelines. @nextcloud/designers ?

**Comment by skjnldsv** [comment]
@cloud2018 Can you provide a screenshot please? :)

**Comment by pixelipo** [comment]
I think this is the idea - see font-color in the sidebar:
![image](https://user-images.githubusercontent.com/4129927/34213560-cf7e8d56-e59f-11e7-8f38-72c132ad8b3c.png)

**Comment by skjnldsv** [comment]
Ooooh, well I don't think we'll advise anyone to do that since with many decks, it will soon looks like @jancborchardt's lsd app! :D

**Comment by jancborchardt** [comment]
This would be very bad for legibility obviously. ;) And I agree with @pixelipo and @skjnldsv

**Comment by cloud2018** [comment]
the idea was that the two bullets have the same color, but with deck 0.3 beta they have different colors:

![screenshot-2017-12-20 test green deck - nextcloud](https://user-images.githubusercontent.com/34692335/34228641-a4340180-e5d1-11e7-996a-9ea1e739aca6.png)

**Comment by pixelipo** [comment]
Aah, that's not colour, it's opacity - maybe worth fixing?

**Comment by juliushaertl** [comment]
Yes, the opacity of the color bullet should be equal 😉

**Comment by jancborchardt** [comment]
I mean I still think the breadcrumb in Deck makes no sense, as commented in the other redesign or first run discussion. ;) Too much duplication and visual noise.

**Comment by juliushaertl** [comment]
@jancborchardt Actually on current master we use the breadcrumbs more for showing that you are on a archived board and that you are currently viewing the card archive. 

But yes, the breadcrumb is not ideal there. Maybe we should consider some header redesign in the future.

**Comment by cloud2018** [comment]
Thanks for changing the opacity, i think the bullets look more consitent now.

When the mouse is over the bullet or boardname (or share-icon) the opacity of the bullet changes again. It seems that the region of the bullet and boardname is a link, but nothing happen when clicked. 
No Problem, I never move the mouse in this region, just now for testing.

**Comment by cloud2018** [comment]
sorry for closing, (wrong button)

**Comment by juliushaertl** [comment]
@cloud2018 Good catch, will fix that as well.
