### ISSUE TITLE
Connect items to a project

### ISSUE THREAD

**Issue by Poldi1977** [nextcloud/deck#3645]
When linking cards, the selection list does not always show all entries. If there is an empty column, subsequent cards do not appear in the selection list.

![Bug](https://user-images.githubusercontent.com/28756918/158458675-47c85c7f-ceca-4f9c-a799-b4759555e3ff.gif)

Operating system:
Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64

Web server:
Apache/2.4.41 (Ubuntu) (apache2handler)

Database:
mysql 10.3.34

PHP version:
7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version:
23.0.2 - 23.0.2.1

Deck version:
1.6.1

**Comment by HonkXL** [comment]
Same problem here -> linking seems todo nothing in my installation.

**Comment by sunjam** [comment]
Projects functionality was removed in 25.  This issue can be closed.

- https://github.com/nextcloud/server/issues/28320
