### ISSUE TITLE
Datepicker opens above datefield

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/deck#365]
**Description:** The Nc datepicker opens above the datefield which makes sense because of the available space but looks really strange.

**Nc Version:** 13 (from git)

**App Version:** v0.3.0-beta1 (from git)

**Browser:** FF 57

![datepicker](https://user-images.githubusercontent.com/1869584/34213053-6fc0dc4e-e59e-11e7-80e8-12c0fffd599f.png)

**Comment by pixelipo** [comment]
which version of Nextcloud are you running?

**Comment by splitt3r** [comment]
Sorry 😁 it´s Nc 13 from git.

**Comment by pixelipo** [comment]
Weird. I'm unable to reproduce:
![image](https://user-images.githubusercontent.com/4129927/34213858-cbea2a50-e5a0-11e7-8efd-c5771986e6c9.png)

**Comment by splitt3r** [comment]
Your browser window is too big ^^:

![datepicker](https://user-images.githubusercontent.com/1869584/34213987-4f82f0ae-e5a1-11e7-8345-2a301e138fb1.png)

**Comment by juliushaertl** [comment]
This also happens in the files app. So I guess it would be better to fix this in the server repo. @splitt3r Can you open an issue there?
