### ISSUE TITLE
'No due date' list not auto updated in Deck 1.6.1

### ISSUE THREAD

**Issue by Milokita** [nextcloud/deck#3659]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
The "no due date" list in the "upcoming cards" board is not auto updated once a new card is added to other board. However, if the board is shared by others, it will auto update again.

**To Reproduce**
1. Create a new card in any list
2. a new card should appear in the "no due date" list

**Expected behavior**
"no due date" list should auto update

This is a follow up bug with same configuration in https://github.com/nextcloud/deck/issues/3633

**Comment by Milokita** [comment]
closed because it can be solved by clicking the "setting due date" without actually setting one

**Comment by dodedodo** [comment]
> closed because it can be solved by clicking the "setting due date" without actually setting one

I do not fully understand the issue. However, this sounds like a workaround, rather than a fix. If the underlying issue is still present you should consider re-opening it.
