### ISSUE TITLE
Scoring on deck cards

### ISSUE THREAD

**Issue by daudtivan** [nextcloud/deck#3660]
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the solution you'd like**
Just like issues on GitHub, there should be a way to vote/react on individual cards to identify those that are more relevant and capture attention of group members. It's intuitive, transparent and clear as selection criteria.

**Describe alternatives you've considered**
Tried inner tasks and tags. All require lots of workarounds and are not intuitive at all.

**Additional context**
Something simple and small, with the count of upvotes in the card.
Dislikes are also a possibility (to identify people against the idea).

**Other thoughts**
I) I tend to believe that displaying or hiding it is a property of the list it belongs to, as you may need that only on early stages of your process: once the selection step is gone you don't need that information anymore. So one should be able to enable it at the list level.
II) having that info bound to the deck/list it belongs to would allow an automatic "reset" once you move your card to a different list (or step in your process), so you can repeat the exercise, without losing history or data.

I've made a small sketch to help illustrate the idea in the attached picture.
![card-likes](https://user-images.githubusercontent.com/91741832/159328144-e76f2469-7977-4de2-9141-28c15fbcf952.png)

**Comment by juliushaertl** [comment]
Thanks for your suggestion. This is something that can be covered by #1833 so I'll close this as a duplicate
