### ISSUE TITLE
Deletion of a list leads to coverage of UI elements

### ISSUE THREAD

**Issue by snuppets** [nextcloud/deck#3671]
### Current behavior
Deleting a list triggers a pop-up in the upper right corner giving the user an option to revert the deletion.
That pop-up covers the UI elements in the upper right corner (add new list, filter, etc).

### The problem
Especially when creating a new board and playing around with its structure it often happens (to me) that I quickly want to delete and create new lists.
After deleting a list the pop-up prevents the creation of new lists for about 30 sec.
I think this is quite interrupting and not necessary.

### Suggestion for improvement
Move the position of that pop-up to the bottom right corner. There it is still visible, but does not interfere with other UI elements.

**Comment by stefan-niedermann** [comment]
Please see [this issue](https://github.com/nextcloud/deck/issues/2809#issuecomment-891623836) and follow the linked upstream issues.
