### ISSUE TITLE
Confirmation button for card title input

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/deck#368]
**Description:** I think to unify the ux a confirmation button for the card title input would be a good idea. Somehow also related to https://github.com/nextcloud/server/pull/7196. And perhaps the title in the sidebar should somehow show that it is editable or have at least an pointer cursor?

**Nc Version:** 13 (from git)

**App Version:** v0.3.0-beta1 (from git)

**Browser:** FF 57

![confirm button](https://user-images.githubusercontent.com/1869584/34214072-a314272e-e5a1-11e7-84f8-c78472ed6a4d.png)

**Comment by juliushaertl** [comment]
Yep, there should be an action to all input fields, so users don't need to know about using enter to confirm.

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master
