### ISSUE TITLE
Docs: Howto setup dev environment

### ISSUE THREAD

**Issue by oneWaveAdrian** [nextcloud/deck#3680]
I would like to contribute to deck. 
However I fail to see how I can test my changes locally.
Would I need a local Nextcloud instance? How would I setup a local docker container to work with the local dev version of deck?

I can't find any suitable documentation for setup, can someone point me in the right direction / update the readme to make the setup more clear?

To be clear, I tried to follow the [readme](https://github.com/nextcloud/deck/blob/master/README.md?plain=1#L69) part to start a local webpack instance but it fails everytime:

```
npx webpack-dev-server --config webpack.hot.js \
    --public localhost:3000 \
    --output-public-path 'http://localhost:3000/js/'
[webpack-cli] Error: Unknown option '--public'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

Hence I think I don't get the full dev setup picture here and something is missing in the install description.

## Update

1. had to temporarily switch my node version back to V14 that brought at least a different set of errors
2. Tried to setup webpack-dev-server commands as per that documentation.
Results in:

```
~/D/D/o/deck ❯❯❯ npx webpack-dev-server --host local-ip --port 3000 --config webpack.hot.js                                                                                                                                                                          ✘ 2 
[webpack-cli] Failed to load '~/D/D/o/deck/webpack.hot.js' config
[webpack-cli] Error: Cannot find module './webpack.dev.js'
```
Now as far as I can tell `webpack.dev.js` is actually not located in repo, hence it can't be found - what step am I missing?

**Comment by oneWaveAdrian** [comment]
Still motivated but still struggling to setup dev env.
Can anybody help?

Painfully went through and installed all peer dependencies manually... now it seems the build process runs into eslint errors before I event started to change ANYTHING... 
Especially this error pops up 36 times
`error  "@nextcloud/vue" is not published  node/no-unpublished-import`

Any help would be really appreciated!

**Comment by oneWaveAdrian** [comment]
After fidgeting with eslint files I seem to be able to finally build deck, however I can not enable it in nextcloud docker instance because apparently it requires nextcloud hub v24 - there is no docker container for that... guys I am really willing to help but getting to the point to do so is highly discouraging so far...

**Comment by oneWaveAdrian** [comment]
Update again - opened an issue in docker repo, will update/close this when I finally get it to run. If I'm doing something completely wrong please advise, I am highly interested in a less time consuming method to get an IDE setup running.

https://github.com/nextcloud/docker/issues/1731

**Comment by PVince81** [comment]
for me it was usually just a way of running:
- `make install-deps`
- `make watch` for hot reload

node v14.17.0 here

**Comment by oneWaveAdrian** [comment]
@PVince81 do you have Nextcloud running as a Docker container then or as an actual install?
When I run your steps with `Node V14.19.1` the first command runs smooth, `make watch` results in this error:
```
[webpack-cli] Failed to load 'deck/webpack.js' config
[webpack-cli] Error: Cannot find module 'vue/compiler-sfc'
```
Is there a sample `webpack.js` to use? I've done many vue projects before but never ran into an issue like this...

**Comment by PVince81** [comment]
@oneWaveAdrian I have a local install, not a docker

not sure why installing deps would not work there

you could also try with https://github.com/juliushaertl/nextcloud-docker-dev

**Comment by CarlSchwan** [comment]
Make sure that package.json and package.lock are not modified, and that you use npm 7 and node 14 (you can use nvm to download a specific version)

**Comment by oneWaveAdrian** [comment]
Thanks @CarlSchwan `nvm` did the trick for compiling. However I can not activate deck inside nextcloud as I get this error message:

>This app cannot be installed because the following dependencies are not fulfilled:
Server version 24 or higher is required.

I don't see anything regarding V24 though - how can I enable my local deck repo inside Nextcloud? Am I missing any setting?

**Comment by CarlSchwan** [comment]
you need a Nextcloud instance using 24 or master, to run the latest deck version from git. You can use the following docker setup https://github.com/juliushaertl/nextcloud-docker-dev to run it locally quite easily as it will take care of downloading Nextcloud from git and setting it up automatically.

**Comment by oneWaveAdrian** [comment]
Success! Thank you @CarlSchwan @PVince81 and of course @juliushaertl.

Steps I took that finally worked:

1. install & run https://github.com/juliushaertl/nextcloud-docker-dev
2. cd into `/[nextcloud-docker-dev-dir]/workspace/server/apps/`
3. `git clone git@github.com:nextcloud/deck.git`
4. `nvm install 14.17.0`
5. `npm install -g npm@7`
6. `nvm use 14`
7.  `make install-deps`
8. `make watch`

Shall I edit the `readme.md` to make it easier for other devs or is this issue enough?

**Comment by CarlSchwan** [comment]
Sounds like something we want in our developer docs at https://docs.nextcloud.com/server/latest/developer_manual/ if it's not already there
