### ISSUE TITLE
Auto save discards changes

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/deck#369]
**Description:** Typing in a long list like:

- Test...
- Test...
- Test...
- ...

sometimes discards some of the changes (last chars).

**Nc Version:** 13 (from git)

**App Version:** v0.3.0-beta1 (from git)

**Browser:** FF 57

**Comment by juliushaertl** [comment]
Cannot reproduce right now, but I might have an idea where this comes from. I'll have another look tomorrow.

**Comment by Aesculapius** [comment]
I'm experiencing the same. In my case it seems to be caused by an 'unsaved changes' mechanism that is too greedy; it tries to save after almost every typed in character and that seems to conflict at some point. But maybe you already fixed it ;-)
