### ISSUE TITLE
Show full date and time of user comment

### ISSUE THREAD

**Issue by webagroprom** [nextcloud/deck#3697]
We need a function to display the full date and time as a result

![1649368117775](https://user-images.githubusercontent.com/30408997/162325988-dd59e174-d84a-4ae3-8457-fc2294f84140.jpg)

**Comment by juliushaertl** [comment]
I think we should keep the relative date by default but a tooltip for the exact date and time would be a good enhancement.

**Comment by webagroprom** [comment]
It would be nice if there was an option to display the full version and time of the comment, and who should be allowed to choose relative.

We need to understand when exactly (date, time) at which a person made his comment.

**Comment by stefan-niedermann** [comment]
I agree with @juliushaertl - Once this has been implemented, you might also be able to show the absolute date via some CSS and the `Custom CSS` app.

**Comment by eugulixes** [comment]
My team needs the feature as well, and we're going to implement it. As far as I understood you all agreed on showing an exact date when hovering the cursor over a relative date, right?

![image](https://user-images.githubusercontent.com/5358223/170691714-90b27f88-5e88-4ad2-9656-0f83f14898e8.png)

**Comment by webagroprom** [comment]
> My team needs the feature as well, and we're going to implement it. As far as I understood you all agreed on showing an exact date when hovering the cursor over a relative date, right?
> 
> ![image](https://user-images.githubusercontent.com/5358223/170691714-90b27f88-5e88-4ad2-9656-0f83f14898e8.png)

It would be nice to be able to show the full date and time forcibly and on hover

**Comment by aquananu** [comment]
hi 

Is it possible to show the exact date and time in timeline

**Comment by webagroprom** [comment]
> hi
> 
> Is it possible to show the exact date and time in timeline

I need this feature too

**Comment by daandres** [comment]
Is there any starting point to do this?

**Comment by viceldan** [comment]
Totally agree with it, in what form whatsoever, be it hovering over a timestamp or having some sort of switch.
Now after using nextcloud for several months, it's just not enough to know something happened 3 months ago, but at least the date, better off with the complete timestamp.
