### ISSUE TITLE
Avatars are misplaced after saving a board

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/deck#370]
**Description:** Avatars are misplaced after saving board changes:

**Nc Version:** 13 (from git)

**App Version:** v0.3.0-beta1 (from git)

**Browser:** FF 57

![avatars](https://user-images.githubusercontent.com/1869584/34214824-db20cfee-e5a3-11e7-93fe-343bde15a2c5.png)

Nav bar overlaps the display name tooltip:

![title](https://user-images.githubusercontent.com/1869584/34214816-d5870ab2-e5a3-11e7-885a-373a674bd069.png)

Here too:

![tooltip](https://user-images.githubusercontent.com/1869584/34214962-3e47c5be-e5a4-11e7-83b2-b77e98d032b3.png)

**Comment by juliushaertl** [comment]
Fixed with #376
