### ISSUE TITLE
Rename of list is not taken into account on the frontend

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#3716]
![Peek 2022-04-11 12-55](https://user-images.githubusercontent.com/213943/162725919-a59d047e-68c9-4254-a335-7bef36d08050.gif)

Just tried again on this PR and it seems to be "one edit behind"

_Originally posted by @nickvergessen in https://github.com/nextcloud/deck/issues/3670#issuecomment-1094905316_

Still cannot reproduce that here. @nickvergessen I assume you used master and built the frontend code? Firefox as a browser?

**Comment by nickvergessen** [comment]
Yes, latest master, `npm ci && npm run dev` with: `Now using node v14.18.1 (npm v7.24.2)`
Using Firefox 99

**Comment by nickvergessen** [comment]
I don't know, The PUT to the server is good, returns the new correct title with 200 OK

**Comment by summer-espresso** [comment]
Hello, for me the server returns `{"status":403,"message":"Permission denied"}` when I try to rename a list. I'm admin.
- Nextcloud Hub II 23.0.5
- Deck 1.6.1
- PostgreSQL 11.16 (Debian 11.16-1.pgdg90+1)
- PHP 7.4
- Firefox 91.10 ESR (Linux)

**Comment by summer-espresso** [comment]
This seems to be solved for me with nextcloud 23.0.6

**Comment by nickvergessen** [comment]
Also not happening in master anymore (although it's flickering for a brief time)
