### ISSUE TITLE
Enhancement: better controls bar

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/deck#372]
Let's talk about `#controls` bar.

Currently it is using `.crumb` system to show a sort of a structure, but it doesn't really follow the real structure, because "All boards" ("Home icon) does not include "Archived boards" (second breadcrumb):
![image](https://user-images.githubusercontent.com/4129927/34298333-9065a53a-e71d-11e7-9f71-79e62bbd4145.png)
As you can see, that board is not listed here:
![image](https://user-images.githubusercontent.com/4129927/34298342-9b1a0d9a-e71d-11e7-8303-3d2bf359f342.png)

From several discussions, last one in #364 , it seems that we need to take a different approach.

The real question is - what information should be presented there?

- [ ] `#app-navigation-toggle` :white_check_mark: :white_check_mark: 
- [ ] link to board's parent container
- [ ] color (bullet) of the current board :white_check_mark: 
- [ ] title of the current board :white_check_mark: 
- [ ] share board icon (opens right sidebar) :white_check_mark: 
- [ ] add a new stack input field
- [ ] generic "Add" button :white_check_mark: 
- [ ] generic "3-dots" button :white_check_mark: :white_check_mark: 
- [ ] ~"Archive board"~ button
- [ ] "Board details" button (opens right sidebar)

I've added a :white_check_mark: next to each. What is your take, @juliushaertl @jancborchardt @skjnldsv and other @nextcloud/designers @nextcloud/deck  that want to get involved? Let me know and I'll add checkmarks.

**Comment by pixelipo** [comment]
Reasoning behind my choice:

1. `#app-navigation-toggle` was a requested feature. It is non-intrusive and it also exists (in the same location, but only for smaller screen sizes) in Files app as well
2. I don't remember if there are plans to be able to "add" more than just new stack to a board, but if there are, a generic "+" button (like in the Files app) might make sense. If not, I will switch my decision to the "Add a new stack" input field
3. I would put everything else into a 3-dot menu, because none of those functions seem to be used very often. maybe the "Board details", but this is a problem that's discussed in case of Files, too - right @jancborchardt ? Board's right sidebar might contain much more useful stuff in the future, but until then, it's not really a _must-have-within-a-single-click_ feature

I don't think items 2-4 (link to parent, color bullet and title) are required, because we have flat structure and those are already visible in the sidebar.

**Comment by cloud2018** [comment]
regarding title of the current board (item 4): 
On smaller screen sizes without sidebar i think to show the title of the board is helpful and consitent with the file-apps, which shows the current path. Just my 2 cents.

**Comment by pixelipo** [comment]
@cloud2018 your first comment is a valid point, but I don't think the second one is. Deck has a "flat" structure, Files is showing a path, but only for the dfolder structure - not for the sidebar items. See this:
![image](https://user-images.githubusercontent.com/4129927/34299956-23214ade-e726-11e7-8ab6-24fbcfb69caf.png)
When viewing "shared with others" - there is no breadcrumb structure in the Files app...

**Comment by cloud2018** [comment]
Yes, you're right, the layout is not 100% comparable. I took a look at "all files" and compared this with "all boards".  The files as content of documents is from my view (as a user) similar to the stacks and cards as content of the board. I think the main difference is, that the boards additionally are shown in the left sidebar as shortcuts in the deck-app.

![screenshot-2017-12-22 documents - files - nextcloud](https://user-images.githubusercontent.com/34692335/34301117-692e63e0-e72b-11e7-921e-02d987d1f089.png)

**Comment by jancborchardt** [comment]
So as mentioned before, the breadcrumb makes no sense in Deck. It's only visual noise and duplication of the sidebar.

- app-navigation-toggle needs to be there for the mobile view, yes
- what is "board's parent container"? The overview list of all boards? Thought we said we remove that cause that's what the sidebar is for.
- Add new stack: Thought we put that on the right as a " ghost stack"? Like Trello
- Generic add button for what, cards? Should be not needed there, duplication cause every stack already has one
- Archive and board details buttons should go into the 3-dots menu

So the header should have only:

- app-navigation-toggle on the left
- next to it (or centered) the title of the board with the color bullet to left, share icon to right
- 3-dot menu either to the far right, or directly right of the share icon

**Comment by juliushaertl** [comment]
> app-navigation-toggle needs to be there for the mobile view, yes

We had that as a feature request and I think it makes sense for deck to show it always, because sometimes users need a lot of space when managing cards.

> what is "board's parent container"? The overview list of all boards? Thought we said we remove that cause that's what the sidebar is for.

:+1: Yep, agree on that.

> Add new stack: Thought we put that on the right as a " ghost stack"? Like Trello

We had that in the past, but I'm not sure what is the better option there. A "ghost stack" makes it clear for the user, where the new stack is being added, but it also adds a lot of noise to the overall view.

> Archive and board details buttons should go into the 3-dots menu

I'd say we should just move the board details over to there. I would like to have the archive button replaced with a more generic filter button that allows filtering for either archived cards or labels/assigned users/... ( ref #289)

**Comment by stefan-niedermann** [comment]
@pixelipo i have a strong feeling that nearly everything you suggested has solved with version `1.0.0`. Could you please check your list items again and mark those as done which actually are solved in the meantime? :slightly_smiling_face:

**Comment by juliushaertl** [comment]
Let's actually close this, and have separate issues for remaining stuff that might come up.
