### ISSUE TITLE
usability: after removing tags, the color of the remaining tags are changed (in the property view)

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#373]
### Steps to reproduce
tested with 0.3.0-beta1 and deck 0.2.8 

1. assign a tag with label YELLOW and color yellow
2. assign a tag with label RED and color red
3. close card properties -> the two labels with the correct colors are assigned
4. open card properties
![tags_1_screenshot-2017-12-23 board1 deck - nextcloud](https://user-images.githubusercontent.com/34692335/34319853-63021964-e7ec-11e7-8243-d7d58b9599b7.png)

5. delete the first yellow tag (and don't close the property view) -> the yellow tag disappears  and the remaining tag (label RED) changes the color to yellow
![tags_2_screenshot-2017-12-23 board1 deck - nextcloud 1](https://user-images.githubusercontent.com/34692335/34319854-6a67b1b4-e7ec-11e7-88a3-8babeafe767a.png)

### Expected behaviour
After deletion of a tag, the color of the remaining tag is unchanged (in the property view)

### Actual behaviour
In the property view the remaining tag (label RED) changes the color to yellow (=color of deleted tag) .
Since after closing the card-properties everything is like expected, this is only a very low limitation of the usability.

**Nextcloud version:** (see Nextcloud admin page)
NC 12

**Comment by juliushaertl** [comment]
Thanks for reporting and for providing a way to reproduce this.

**Comment by cloud2018** [comment]
thank you, works fine
