### ISSUE TITLE
spanish translation and visualization

### ISSUE THREAD

**Issue by RNogales94** [nextcloud/deck#374]
### Steps to reproduce
1. Create a new tableau
2. Look at the "add new hip" button

### Expected behaviour
Tell us what should happen
In spanish it is "Crear nuevo montón" 
I suggest to write only "Crear montón" because "nuevo = new" it's implicit, and it would improve a lot the visualization and the understanding for noobs in the app like me.
### Actual behaviour
Tell us what happens instead
In spanish it is "Crear nuevo montón" 
but there's too long, and you only can read "Crear nuevo mont"

That's my first issue in a open source project, I hope it will be useful

### Server configuration

**Operating system**:
Mac OS X 10.12.6
**Web server:**
Safari 11.0.2
**Database:**
SQLite
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Where did you install Nextcloud from:**
with wget directly 
**Signing status:**
Logged as admin

**Comment by juliushaertl** [comment]
Translations are done via Nextcloud Transifex: https://www.transifex.com/nextcloud/nextcloud/languages/

Feel free to joint the translation team there and propose a different translation.
