### ISSUE TITLE
Description entry of a card is deleted after card is dragged to a new stack

### ISSUE THREAD

**Issue by rkraken** [nextcloud/deck#375]
### Steps to reproduce
1. add a description to a card
2. drag the card to a new stack

### Expected behaviour
dragging a card should preserve contents including entered description 

### Actual behaviour
The card's description disappears

### Server configuration

**Operating system**:
Linux Mint 18

**Web server:**
apache2
Apache/2.4.18 (Ubuntu)

**Database:**
mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
PHP 7.0.22-0ubuntu0.16.04.1 

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.4

### Client configuration
**Browser:**
Vivaldi

**Comment by juliushaertl** [comment]
What version of deck are you using? I cannot reproduce that on 0.3.0 beta1 so I guess this was fixed and will be fine with the next release.

**Comment by rkraken** [comment]
Sorry!  version 0.2.8 

The problem seems to be intermittent now.
Looking forward to the next release.  Thanks for your hard work.
