### ISSUE TITLE
Can't rename list in cloned board 

### ISSUE THREAD

**Issue by xeruf** [nextcloud/deck#3752]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When I clone a board from another one, I can neither rename columns nor restore deleted ones

**To Reproduce**
1. Create a board with a list
2. Clone the board
3. Try to rename the list on the cloned board
4. Does not work, not even an error message
5. If I delete the list, I can also not recover it - clicking the restoration error does nothing, it just stays there

**Expected behavior**
Things work

<details>
<summary>Server details</summary>
Operating System: | Linux 5.10.0-12-amd64 x86_64
-- | --
CPU: | Common KVM processor (8 cores)
Memory: | 61.70 GB

**Nextcloud version:** [Nextcloud Hub II](https://ftt.gmbh/) (23.0.2)

**Where did you install Nextcloud from:** Running from helm chart as container managed by https://docs.stackspin.net/en/v0.8/applications.html#nextcloud

```
No errors have been found.
```

#### Nextcloud log (data/nextcloud.log)
nothing relevant

#### Browser Log
PUT | https://example.org/apps/deck/stacks/20 fails with a 403 Forbidden while it works with a 200 for non-cloned boards

**Comment by xeruf** [comment]
Probably related to https://github.com/nextcloud/deck/issues/2090 and https://github.com/nextcloud/deck/issues/2749

**Comment by ammannbe** [comment]
I have the same problem and can reproduce it.
I receive following errors:

**Request-URL:**
```
/apps/deck/stacks/123
```

**Request-Body:**
```json
{"id":123,"title":"test","boardId":12,"deletedAt":0,"lastModified":0,"order":null,"ETag":"<some-random-string>"}
```

**Response-Status:**
```
400 Bad Request
```

**Response-Body:**
```json
{"status":400,"message":"order must be provided and must be numeric"}
```

The problem is, that in the request body the order number is missing.

If I reorder a list before renaming it, the renaming works as expected.

**Comment by bentuna** [comment]
Is there any news on this? We can still reproduce this in Nextcloud 27.1.4 with Deck Version 1.11.1.

**Comment by estux** [comment]
I still can reproduce this in Nextcloud 28.0.3 with Deck version 1.12.2.

**Comment by bentuna** [comment]
@estux Same here.
