### ISSUE TITLE
Nothing to update lastModified on

### ISSUE THREAD

**Issue by ylebre** [nextcloud/deck#3763]
Minor issue I bumped on:

https://github.com/nextcloud/deck/blob/1578c13bf505403917b9db9e4d00b2a1ed7cecf8/src/store/card.js#L253

I'm not familiar enough with the codebase, but I'm pretty sure this line should be removed.

This line of code runs when there is no card found to update, yet it tries to update the lastModified on the card on the -1 index anyway, which obviously fails.

Note: this does not happen in normal situations - it triggered for me when an update to the card returns  a non-existing card ID, which is a bug in my own code.

**Comment by juliushaertl** [comment]
Good catch, yes that should rather be done included in the above if-condition. Are you up for a pull request to address that? That would be highly appreciated :)

**Comment by ylebre** [comment]
PR opened!
