### ISSUE TITLE
can't deassign user 

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#379]
tested with 0.3.0-beta1 (deck_nightly_latest.tar.gz,  2018-01-09 00:29) and Nextcloud 12.0.4
(and compared to deck_nightly_2017-12-24.tar.gz)

### Steps to reproduce
1. Assign a user to a card
2. Close card properties -> the user is correct assigned
3. Open card properties and move the mouse over the user icon
4. The name of the assigned user is displayed (above) and there is no delete-icon 
![deck_20180109](https://user-images.githubusercontent.com/34692335/34715894-7a349bf8-f52e-11e7-949c-b8ad5a2d6571.png)
### Expected behaviour
There is a delete-icon to delete the assigned user.

With deck_nightly_2017-12-24.tar.gz the name of user was displayed (below) and there was a delete-icon on the avatar:
![deck_20171224](https://user-images.githubusercontent.com/34692335/34716187-66cfdc84-f52f-11e7-9051-dfb6810f9a43.png)
### Actual behaviour
When the mouse over the user icon there is no delete-icon or any other possibility to deassign a user.

**Nextcloud version:** 
12.0.4

**Note** 
Perhaps a local problem, because I installed very often different versions of deck and my environment isn't correct.

**Comment by juliushaertl** [comment]
The unassign action has been moved to the menu that opens when clicking the avatar. Can you check if that works for you? Maybe that's an issue with NC12. The avatar should actually show a pointer on mouse over to indicate that it is clickable.

**Comment by cloud2018** [comment]
When clicking the avatar I can deassign the user, that works fine. Thank your for your hint.

I don't see a hand-pointer on mouse over (like in the first screenshot) and in the pop-up are the two items "No action available" and "Remove user from card"

![deck_3](https://user-images.githubusercontent.com/34692335/34718569-7479522c-f537-11e7-8c9f-f7fb1f97bed8.png)

"Remove user from card" works like expected.
"No action available" closes the whole board and displays the "All Boards"-view. Perhaps this behavior is a little confusing, but I'm happy with this.

**Comment by cloud2018** [comment]
I think "No action available" is displayed only when no email of the user is configured.

It seems, that I can only deassign the users, who didn't create the card. How to deassign the creator?
