### ISSUE TITLE
Card-View: Duedate delete-Icon not aligned properly

### ISSUE THREAD

**Issue by Ben-Ro** [nextcloud/deck#3791]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When a Duedate is set, the Delete Icon isn't aligned properly but a bit tu much up. It should be within the yellow lines of the screenshot. Affects both the bigger card view and the default view.

**To Reproduce**
1. Create a Card with Due Date
2. Close and open the card to see the misaligned delete Icon (is this a complete other bug, imo the icon should appear directly after setting a duedate and not only after exiting and reopening)

**Affected Versions**
At least 1.6.1 up to git master

**Expected behavior**
The Icon should be within the yellow lines correctly aligned.

**Screenshots**
<img width="388" alt="Bildschirmfoto 2022-05-08 um 20 01 copy" src="https://user-images.githubusercontent.com/22852640/167310009-84d09ca7-4434-493a-8727-e733559f1d63.png">
<img width="386" alt="Bildschirmfoto 2022-05-08 um 20 01 56" src="https://user-images.githubusercontent.com/22852640/167310351-f8e27cb6-c8a9-445d-9232-bbf0a049d492.png">

**Client details:**
 - OS: macOS
 - Browser chrome, safari
 - Version Safari: 15.4 Chrome: 101
 - Device: Macbook Pro 13

**Operating system**: Debian 11

**Web server:** php -S, it's a frontend bug

**Database:** SQLITE

**PHP version:** 8.1

**Nextcloud version:** git-master

**Where did you install Nextcloud from:** git clone

**Comment by Ben-Ro** [comment]
The misalignment annoyed me too much every time i looked at it, so i fixed it and created a Pull-Request. I hope thats fine :)

**Comment by juliushaertl** [comment]
@Ben-Ro This is awesome, thanks a lot for that :)
