### ISSUE TITLE
box to small for German translation of  "Click to set" : "Klicken zum Übernehmen"

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#380]
In the property-view of the card the box for the German translation of "Click to set" is to short.
Only "Klicken zum" is displayed

![translation](https://user-images.githubusercontent.com/34692335/34720935-fd33c940-f540-11e7-9115-c707f4ed2ce3.png)

If the size of the box is fixed, "Auswählen" could be an altenative and short translation.

Same in français   "Click to set" : "Cliquez pour définir", shows only "Cliquez pou".

**Comment by juliushaertl** [comment]
Translations are actually handled in transifex: https://www.transifex.com/nextcloud/nextcloud

The german translation has already been updated to "Setzen" which should be fine to understand as well.

**Comment by ldmpub** [comment]
French translation changed to "Définir".
