### ISSUE TITLE
Dark mode menu icon on card is black on dark grey

### ISSUE THREAD

**Issue by PVince81** [nextcloud/deck#3800]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
<img width="199" alt="image" src="https://user-images.githubusercontent.com/277525/167638853-ef45c829-ca1a-454f-a686-650328850f61.png">

Observed on c.nc.com (NC 24.0.0)

**Comment by mokkin** [comment]
Seems to be solved in NC 25:
![grafik](https://user-images.githubusercontent.com/2938748/200510995-b12915e7-44fc-4123-adc1-1eb90e0d08d6.png)
