### ISSUE TITLE
button "Undo board deletion - ..." is not translated

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#381]
tested with 0.3.0-beta1 (deck_nightly_latest.tar.gz, 2018-01-09 00:29) and Nextcloud 12.0.4

### Steps to reproduce
1. Change in NC Personal Language to other than English (US)
2. Open deck Archived boards
3. Move over undelete icon and the description is displayed

### Expected behaviour
The description is in user language and not in English

### Actual behaviour
The description is not translated:

![deck_undo_delete](https://user-images.githubusercontent.com/34692335/34729471-0a53990e-f55d-11e7-82db-37022e4df824.png)

**suggestion** 
in /templates/part.boardlist.php line 83:
`<button class="icon icon-history button-inline" ng-click="boardDeleteUndo(b)" 
title="Undo board deletion - Otherwise the board will be deleted during the next cronjob run.">
<span class="hidden-visually"><?php p($l->t('Undo board deletion - Otherwise the board will be deleted during the next cronjob run.')); ?></span></button>`

use php to translate the title-attribute like follow:
`<button class="icon icon-history button-inline" ng-click="boardDeleteUndo(b)" title="<?php p($l->t('Undo board deletion - Otherwise the board will be deleted during the next cronjob run.')); ?><span class="hidden-visually"><?php p($l->t('Undo board deletion - Otherwise the board will be deleted during the next cronjob run.')); ?></span></button>`

**Comment by juliushaertl** [comment]
@cloud2018 Thanks for reporting. A fix is waiting in #382
