### ISSUE TITLE
Card-View: Text jumping when changing to/from editing description

### ISSUE THREAD

**Issue by Ben-Ro** [nextcloud/deck#3812]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When Changing from/to Editing the Card Description, the description jumpes a litle bit and while editing there's a light gray border. 

**To Reproduce**
1. Create a card and open it
2. Add a description
3. Save the description
4. See the jumping in the left upper corner of the description

**Expected behavior**
The description should stay at the same position

**Screenshots**
Since Screenshots can't demonstrate this very good, i created a gif: [http://www.giphy.com/gifs/3AYp7OXauH45SxvTmM](http://www.giphy.com/gifs/3AYp7OXauH45SxvTmM)
View
<img width="862" alt="Bildschirmfoto 2022-05-12 um 10 47 52" src="https://user-images.githubusercontent.com/22852640/168031013-0300e8c3-2f9d-4457-a913-b92dfc0f64b3.png">
Editing
<img width="853" alt="Bildschirmfoto 2022-05-12 um 10 47 59" src="https://user-images.githubusercontent.com/22852640/168031025-1a2f211e-98ed-4b58-be8f-e56b6cc22918.png">

**Client details:**
- OS: macOS
- Browser chrome, safari
- Version Safari: 15.4 Chrome: 101
- Device: Macbook Pro 13

**Operating system:** Debian 11

**Web server:** php -S, it's a frontend bug

**Database:** SQLITE

**PHP version:** 8.1

**Nextcloud version:** git-master

**Where did you install Nextcloud from:** git clone

**Comment by dodedodo** [comment]
I personally don't see this as a problem. For me, it acts as a visual aid to identify which mode I'm in (edit / view).

For those curious, here's the gif.
![gif](https://media1.giphy.com/media/3AYp7OXauH45SxvTmM/giphy.gif?cid=790b761186252baf93af03a0ff24bb9d297c84778efd9581&rid=giphy.gif&ct=g)

**Comment by Ben-Ro** [comment]
> I personally don't see this as a problem. For me, it acts as a visual aid to identify which mode I'm in (edit / view).

I'd agree with you, that an indicator for the current mode is important. Even though the jumping is annoying and even the line-height changes. To address this need, there could be ui indicator like a small border (w/o changing the text position) with a light background color change or so, but no jumping text when switching the mode :)

**Comment by juliushaertl** [comment]
This is fixed with the new editor
