### ISSUE TITLE
Global logout menu displayed under card details side bar view.

### ISSUE THREAD

**Issue by probastaller** [nextcloud/deck#3835]
When the detail view side bar of a card is opened and you want to logout from nextcloud, the global menu shows behind the card details and is not visible nor clickable.

You have to close detail view of the card to be able to logout from nextcloud.

The issue started just after nextcloud update to 24 and it remains in 24.0.1 in the Hanssonit VM.

**Comment by aljawaid** [comment]
Same on NC v23

**Comment by probastaller** [comment]
I guess it is fixed with PR https://github.com/nextcloud/deck/pull/3884
