### ISSUE TITLE
Add delete/archive/move card capability in bigger view

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#3857]
When reviewing the cards in a list you can often find ones that should no longer be in the list, where you might want to move, archive or delete them. In addition, the card title might not be enough to make that decision; but while bigger view is great for seeing all the info quickly, if you then decide that card should be moved/archived/deleted you have to close the view to take the action.

Solution:

add to the card buttons (or a menu) that gives access to those actions; this should probably in the top section so that it's consistently available regardless of which aspect of the card needs reviewing for the action decision to be made.

**Comment by tobiasfabian** [comment]
All actions from the overview context menu (screenshot 1) should be available in the details/sidebar/bigger view (screenshot 2).

This would be a huge UX/productivity improvement.

<img width="200" alt="Bildschirmfoto 2024-01-25 um 10 38 47" src="https://github.com/nextcloud/deck/assets/1524319/fe33922b-b372-4fc7-83fa-27b87aba5a20" alt="Screenshot context menu of overview view">

<img width="200" alt="Bildschirmfoto 2024-01-25 um 10 46 47" src="https://github.com/nextcloud/deck/assets/1524319/ae7409cd-01d0-4f9c-9b69-71b4727216d9" alt="Screenshot of context menu of sidebar view">
