### ISSUE TITLE
missing translation when create new card

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#386]
![neuekarte_nottranslated](https://user-images.githubusercontent.com/34692335/34882406-c6de595a-f7b6-11e7-89a0-b8f8c84dc324.png)

### Steps to reproduce
1. Change personal language
2. Click on the "+" to create a new card
3. Don't fill the text box wit a cardtitle
4. Move the mouse out of the text box and then back over the textbox
5. The Hint "Please fill out this Field." is displayed

### Expected behaviour
The Hint is translated

**Comment by juliushaertl** [comment]
This seems to be a message of your browser so out of scope for this repo. The string is not present in the deck source code. :wink:

**Comment by cloud2018** [comment]
Sorry for reporting, you're right. The language of the hint depends on the browser.

**Comment by juliushaertl** [comment]
No problem, I really appreciate all your bug reports. Helps a lot to improve deck. :+1:
