### ISSUE TITLE
[Feature request] Link tasks to cards

### ISSUE THREAD

**Issue by orglube** [nextcloud/deck#3860]
Hello,

Currently, in the card detail panel, it is possible to link another board, another card, a file, a poll or a conversation. 

Would it be to possible to also link cards with a task (from tasks app) ?

![card-detail](https://user-images.githubusercontent.com/101201297/172836347-ef46dd30-4786-4d16-b914-f7e433dda984.jpg)

That would be really useful.

Thanks

**Comment by stefan-niedermann** [comment]
You will need to ask the tasks app for supporting thr "Nextcloud Projects" feature which allowd linking entities to other entities in their corresponding repository - please search there for existing issues regarding this topic, I guess this has already been asked :)
