### ISSUE TITLE
Missing release for 1.7.1

### ISSUE THREAD

**Issue by dvzrv** [nextcloud/deck#3869]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Hi! I maintain this app for Arch Linux. I saw that there is a tag for 1.7.1 but no release so far.

**To Reproduce**
1. Try to download prebuilt release for deck 1.7.1

**Expected behavior**
Deck has a prebuilt release for 1.7.1.

**Screenshots**
n/a

**Client details:**
 - OS: Arch Linux
 - Browser n/a
 - Version n/a
 - Device: n/a

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by dvzrv** [comment]
@juliushaertl this ticket has been open since June and is about not being able to update this software, as the release is missing. Would you be able to respond to this ticket please? :)

**Comment by szaimen** [comment]
See https://github.com/nextcloud-releases/deck/releases/tag/v1.7.1

**Comment by dvzrv** [comment]
@szaimen why are releases of some of the apps alternating between their own repository and nextcloud-releases? This is a bit cumbersome to track tbh :(

**Comment by szaimen** [comment]
Due to security considerations

**Comment by dvzrv** [comment]
> Due to security considerations

That sounds rather weird. Some of the apps sometimes release in their own repo, then in nextcloud-releases and back.
If the names of the tarballs change during that time as well, it gets really hard for downstreams to track this.
