### ISSUE TITLE
Linebreaks are not shown in card text

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/deck#3882]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
If you use line breaks in a cards description they are only shown while editing.  when viewing the card all lines are shown in one single line.

**To Reproduce**
just create a card description with three lines.

**Expected behavior**
line breaks should be shown when viewing the card.

**Screenshots**
maybe I am blind, but can't find an upload button/section here.

**Comment by Emma-Peel** [comment]
I have observed the same problem, which makes the card description more or less unusable - especially when using hierarchical text formatting. Maybe this additional information could help to reproduce:
- The problem has been seen first after upgrading from Nextcloud 22.x to 23.0.6. 
- It applies as well to existing cards as to new cards and even new boards

**Comment by ilippert** [comment]
In my understanding, the deck application uses markdown, and you describe its default treatment for linebreaks vs paragraphs. See the [protocol](https://whatismarkdown.com/how-to-format-paragraphs-in-markdown/). This is just an observation, not an evaluation.

**Comment by juliushaertl** [comment]
This should be no longer a problem as we use the rich text editor now. Otherwise this was expected behaviour according to the markdown syntax definition.
