### ISSUE TITLE
Add link to github page in the appstore

### ISSUE THREAD

**Issue by dragetd** [nextcloud/deck#389]
Hello,

it would be nice if Deck had a link to their GitHub repository under 'Resources' as a homepage or something.
https://apps.nextcloud.com/apps/deck

I was looking for the changelog and not coming here via the store is a bit cumbersome. :P

**Comment by juliushaertl** [comment]
Hm, we already have the repo link in the appinfo.xml. That should be parsed by the app store. https://github.com/nextcloud/deck/blob/master/appinfo/info.xml#L24

Btw. you can also view the changelog directly on the versions in the app store: :wink: 
https://apps.nextcloud.com/apps/deck/releases?platform=13#13

**Comment by juliushaertl** [comment]
Let's see if we can show the repo url in the app store, otherwise I'll add it as a homepage link so it will show up in the resources list.

**Comment by dragetd** [comment]
In the german shop page, this overview / changelog is hidden behind 'Alle Veröffentlichungen', which means 'All releases'.

Up until 30 seconds ago, I would have never assumed to find a changelog there. x.x
