### ISSUE TITLE
Make add card button visible on large stacks

### ISSUE THREAD

**Issue by dudasfau** [nextcloud/deck#393]
I have many cards in one stack; as a result the button to add cards is always hidden and I have to scroll downwards.
I think it would be convenient to have an option per board to move this button to the top of the stack.

**Comment by juliushaertl** [comment]
That is a good point. Maybe we should make the button sticky at the bottom and have it always visible. @nextcloud/deck

**Comment by juliushaertl** [comment]
I've summarized this in #399 so we have one issue about the board behavior.
