### ISSUE TITLE
Colors for Lists

### ISSUE THREAD

**Issue by sascha08-15** [nextcloud/deck#3948]
Would be great to have colors for lists, e.g. for a Kanban like deck. I saw features for cards, but not for lists.

**Comment by stefan-niedermann** [comment]
Thi has been discussed in https://github.com/nextcloud/deck/issues/833

See response of the maintainer @juliushaertl: https://github.com/nextcloud/deck/issues/833#issuecomment-476548587

**Comment by sascha08-15** [comment]
I wonder why this never has been realized? It's been around for a while and doesn't seem to be such a headache to implement.
@juliushaertl I don't see coloring of cards as a super specific feature. Trello e.g. does it. Also very generic.
