### ISSUE TITLE
Custom Color Tag

### ISSUE THREAD

**Issue by 8sd** [nextcloud/deck#395]
I'd like to have more colors for the tags
I'm using more than 8 tags, currently some colors are use multiple times.
Maybe you could add a HTML5 color picker to select any color you like for tagging

**Comment by juliushaertl** [comment]
Yes, also related to https://github.com/nextcloud/deck/issues/204. Maybe @ossie wants to have a look at the tag color as well. :wink:

**Comment by juliushaertl** [comment]
Fixed with #405. Big thanks to @ossie for the implementation. :clap:
