### ISSUE TITLE
Do not open (bigger) Card View after drag and drop of a card

### ISSUE THREAD

**Issue by b3nks** [nextcloud/deck#3962]
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When using the option "us bigger card views" when sorting many cards e.g. for reorganizing, you don't wish to see the content of a card but you want immediately touch the next one. At the moment (v1.7.1) after every drag and drop action you have to close the card view to handle another card.

**Describe the solution you'd like**
After dropping a card, the bigger card view should not open.

**Describe alternatives you've considered**
There could be an option for the behavior.

related to #2445

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/deck/pull/3916
