### ISSUE TITLE
error 500 with nc25.0.0 beta 1

### ISSUE THREAD

**Issue by RoundAboutWEB** [nextcloud/deck#3978]
NC: 25.0.0 beta 1
PHP: 8.0

PHP Fatal error:  Declaration of OCA\Deck\Sharing\DeckShareProvider::getSharesInFolder($userId, OCP\Files\Folder $node, $reshares) must be compatible with OCP\Share\IShareProvider::getSharesInFolder($userId, OCP\Files\Folder $node, $reshares, $shallow = true) in /html/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php on line 494

**Comment by drpetersen** [comment]
Same error here with NC 25.0.0 beta 2, PHP 8.1, and deck 1.7.1

**Comment by Houserocker** [comment]
Same here. any solution ?

**Comment by juliushaertl** [comment]
A 1.8.0-beta.1 was released yesterday to address this incompatibility with the 25 beta releases.
