### ISSUE TITLE
Expand selected stack on demand / solo view

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#400]
With stacks containing many elements it might be helpful to be able to open one to some kind of "full screen" view, temporarily covering the other stacks.

**Comment by juliushaertl** [comment]
How should the cards be arranged then? I don't see a benefit in having many cards spread over the whole screen. Proper filtering to just have the cards you want is probably the better way to solve the issue. (#289 #222)

**Comment by bpcurse** [comment]
I'm closing this feature request as there is compact mode available since 0.5.0.
