### ISSUE TITLE
Deck, not able to update the comments if it has a User mentioned by using @username

### ISSUE THREAD

**Issue by aquananu** [nextcloud/deck#4003]
hi i am having the same issue with one user only, the user is not able to update the comments, tried the same on machine on which other users are able to update comments
[Talk (2).log](https://github.com/nextcloud/deck/files/9433614/Talk.2.log)

attached in the console log of the user browser

kindly help me out, if this is a bug in the Deck version 1.7.1 on nextcloud 24.0.3

_Originally posted by @aquananu in https://github.com/nextcloud/deck/issues/3332#issuecomment-1228510506_

**Comment by aquananu** [comment]
The problem is that the comments are not updated if a user has been tagged in the comment by using @username in the comment text.

you can edit the comment but it doesnt proceed to save

**Comment by joshtrichards** [comment]
Thanks for you report. This works today. Closing.
