### ISSUE TITLE
Some small things regarding usability, which doesn't reduces functionality

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#402]
tested with deck 0.3.0, NC12.0.4

1) Filter of users who can assigned is not updated immediatly
2) Inconsistent items in pop-ups "more" (3 dots)
3) Left pop-up from more (3 dots) doesn't disappear

### 1. Filter of users who can assigned is not updated immediatly ###
**Steps to reproduce**
1.1 Share board  with user "testuser"
1.2 Open card details and try to assign the card to the testuser
1.3 Not expected:testuser doesn't appear in the list of users I can assign
Workaround: close board and then it's possible to assign the testuser

### 2. Inconsistent items in pop-ups more (3 dots) ###
**Steps to reproduce**
2.1 Open right pop-up "more" (3 dots) in boardlist view
2.2 There is the item "Delete board"
2.3 Open left pop-up "more" (3 dots) in sidebar view
2.4 Not expected: There is no item "Delete board"
![deck_20180119_issues3](https://user-images.githubusercontent.com/34692335/35144038-a586022e-fd03-11e7-86cf-2d2496fa14e4.png)

### 3. Left pop-up from more (3 dots) doesn't disappear ###
**Steps to reproduce**
3.1 Same steps as in 2)
3.2 Like expected: after open left pop-up "more" (3 dots) in sidebar view the right pop-up "more" (3 dots) in boardlist view disappears
3.3 Open right pop-up "more" (3 dots) in boardlist view again
3.4 Not expected: Left is still displayed (above image is a screenshot, not a montage)

**Comment by juliushaertl** [comment]
@cloud2018 Thanks for reporting.

**Comment by juliushaertl** [comment]
Split those issues into #429 and #430.
