### ISSUE TITLE
Collapse and expand cards in a stack

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#403]
In a stack that contains lots of cards a collapse / expand command might be useful.

Example:
![deck collapse cards example](https://user-images.githubusercontent.com/29312856/35153293-33d552d8-fd26-11e7-9f65-4e48c8b8dc95.png)

After clicking on a collapsed card, either only the single card could be expanded or the size of all cards could be restored and the view scrolls to the selected card.

**Comment by juliushaertl** [comment]
I get the point why this might be needed, but adding another button for that doesn't seem like the best solution. I think we should focus on proper filtering so users can decide to just see the cards they need to see. Any opinions @nextcloud/deck ?

**Comment by Nebri** [comment]
@juliushaertl I think a filter field at the same level or just underneath the stack title would be ideal. Maybe having a 'pin card to top' could also be useful while we are at it?

**Comment by juliushaertl** [comment]
@Nebri Checkout https://github.com/nextcloud/deck/issues/414 for the filters

@bpcurse I'll close this because filtering will be a much more universal way than just adding a collapse card mode.
