### ISSUE TITLE
as a user, i would like to be able to browse a card's content without having to navigate thru tabs much

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nextcloud/deck#4030]
**Is your feature request related to a problem? Please describe.**
as a user, I would prefer to not need to navigate thru tabs much, but just having a card's content, attachments and comments all in one and the same view.

**Describe the solution you'd like**
similarly merge some of these views for Deck, or allow the user such an option.

**Describe alternatives you've considered**
Trello

**Comment by dodedodo** [comment]
This is also discussed in #2702
