### ISSUE TITLE
Adapt upcoming cards dashboard widget for mobile clients

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/deck#4034]
### Is your feature request related to a problem? Please describe.

With https://github.com/nextcloud/server/pull/33658 mobile clients can access app widget data.

### Describe the solution you'd like

Adapt the *upcoming cards* widget to https://github.com/nextcloud/server/pull/33658 once it's done.

**Comment by eneiluj** [comment]
It's done with the current state of https://github.com/nextcloud/server/pull/33658
I will adjust if there are some changes there.
