### ISSUE TITLE
AttachmentList.vue uses uid instead of display name

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/deck#4035]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
The AttachmentList.vue component uses the UID instead of the Display Name

Especially for configurations that use LDAP UUIDs this is weird.

https://github.com/nextcloud/deck/blob/f8a255a9f066bb5aa9c7c93cc8056bc5f52516fa/src/components/card/AttachmentList.vue#L66

**To Reproduce**

1. Share a deck card with an attachment
2. Look at the attachments list

**Expected behavior**
The display name is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/7427347/188895597-02952c3a-b59d-47b5-907d-54a03f7c4f84.png)

**Client details:**
 - Browser : Chrome

On c.nc.com

**Comment by eneiluj** [comment]
@miaulalala Ok done, I'll tell you once it's merged and backported.
