### ISSUE TITLE
Move "add card" buttons to top of stacks

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#404]
When working with large stacks it can be really inconvenient to first scroll down the whole stack to click the add button. Moving or copying the add button to the top of the stack seems favourable.

Example A:
![deck_move_card_buttons_on_top_of_stack_example](https://user-images.githubusercontent.com/29312856/35172772-45ed5978-fd69-11e7-8e5e-51277cd76a43.png)

Example B:
![deck_move_card_buttons_on_top_of_stack_example_b](https://user-images.githubusercontent.com/29312856/35173143-9f528ed8-fd6a-11e7-9604-7c9e9cba351d.png)

**EDIT**
Or probably the easiest way with the least programming effort. Example C:
![deck_move_card_buttons_on_top_of_stack_example_c](https://user-images.githubusercontent.com/29312856/35177391-468800f2-fd7f-11e7-92d8-910ff9eca05f.png)

And thank you for this really awesome app!

**Comment by juliushaertl** [comment]
@bpcurse Thanks for the ideas. I think we should rather go and make the add card button sticky at the bottom, so that it is always visible. As described in https://github.com/nextcloud/deck/issues/399
