### ISSUE TITLE
Default Lists "Todo | Doing | Done" or other admin choice

### ISSUE THREAD

**Issue by compumatter** [nextcloud/deck#4040]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
In our case, new boards are most commonly started as something like "Todo, Doing and Done".  Though other business models will have their own favorite default columns.  In any case, I feel it is obvious that default columns are an important addition.

**Describe the solution you'd like**
When clicking "Add Board" to create a new board, it could automatically start with a template of X columns (titles) which were pulled from Admin > Settings > Deck.  

**Describe alternatives you've considered**
None

**Additional context**
 None

**Comment by putt1ck** [comment]
Dealt with in https://github.com/nextcloud/deck/issues/119#issuecomment-578393767

**Comment by knob-msmr** [comment]
I´d like to reopen this issue. as it would be used by our colleagues **all the time**.

1. Cloning a board,
2. unselecting cards,
3. creating it, selecting it
4. and renaming the title

... is really not a feasible solution for everyday usage.

Thanks for possibly reviewing this again!
