### ISSUE TITLE
Combined sidebars, or card editing popover

### ISSUE THREAD

**Issue by nekohayo** [nextcloud/deck#408]
I have only one board, but it has six columns, and Deck is quite space-inefficient when it comes to letting me see them all. I typically can only see one and a half columns at a time, because there is a sidebar on the left (for boards) and a big fat sidebar on the right (for card properties) that pops up all the time.

So in practice, on a tiled half-screen browser window (half of 2560px), Deck is using 66% of the available horizontal space for... "UI cruft". And wasting a huge amount of vertical space in each of those individual sidebars as well.

Possible solutions:

* Merge the "card/board properties" sidebar into the "Boards list" sidebar on the left. This would have the advantage that I would stop considering that the lefthandside sidebar is wasting space 100% of the time in my case.
* Replace the properties sidebar by a popover widget that shows on top of the clicked card only when necessary, and goes away when I save the properties or click the X or click anywhere outside the popover. This is a "fun" approach but less space-efficient perhaps.

**Comment by pixelipo** [comment]
You do realize that we have this button to hide the left sidebar?
![image](https://user-images.githubusercontent.com/4129927/35432785-7512f290-0281-11e8-9b86-064796d85227.png)

Second suggestion will mostly be solved once we implement in-place card editing #251

**Comment by nekohayo** [comment]
> You do realize that we have this button to hide the left sidebar?

No I didn't. For starters it is really not obvious because it's a hamburger and not a "collapse me" arrow icon. The hamburger is not typically used to symbolize this unless the sidebar would be a permanently collapsed thing that only pops up temporarily when you click the hamburger and then self-closes again after use...

Secondly, my points about the properties sidebar being hugely wasteful still stand, unless you're indeed planning to move ALL its features into in-place-editing through #251 (in that case, yay!)

**Comment by juliushaertl** [comment]
> No I didn't... It is really not obvious because it's a hamburger and not a "collapse me" arrow icon. The hamburger is not typically used to symbolize this unless the sidebar would be a permanently collapsed thing that only pops up temporarily when you click the hamburger and then self-closes again after use...

Yeah, that is a good point, we should probably use just a close icon there if the sidebar is open.

> Secondly, my points about the properties sidebar being hugely wasteful still stand, unless you're indeed planning to move ALL its features into in-place-editing through #251 (in that case, yay!)

Not really. You can also just close the sidebar again - as it would work with the popover as well. I'd prefer to keep the sidebar there, since it allows to still have a look at the board while editing a card.
