### ISSUE TITLE
Breaking API change in `1.8b1`: card `overdue` missing

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#4095]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
The `overdue` property of a card can be missing (and therefore be interpreted as `null`) where formerly was always an integer (like `0`).
See https://github.com/stefan-niedermann/nextcloud-deck/issues/1337
First observed in Deck 1.8b1

**To Reproduce**
1. Use Deck Android `1.20.2` or earlier to import an Deck account from Deck 1.8b1

**Expected behavior**
This is considered to be a breaking change. The API should not change its behavior without announcing it.

**Client details:**
Deck Android `1.20.2`

Server details

Backend used for testing: `cloud.nextcloud.com`. I don't know the server details for this backend. I also don't have access to logs since I only have a guest account

**Comment by juliushaertl** [comment]
Fixed by #4115 as well
