### ISSUE TITLE
Tag-Language changed - old tags cannot be removed

### ISSUE THREAD

**Issue by cablesky** [nextcloud/deck#4104]
After suddenly changing the language from English to German, the English tags can no longer be removed.

E.g. The tag "Action needed" can no longer be removed. 
Instead, only the tag "Handlung erforderlich" can be added.

How can I delete the tags in other languages?

**Comment by DJE98** [comment]
# Step by step reproduction of the bug
## Use english deck version

![Screenshot 2022-10-19 at 20-49-59 Personal - Deck - Nextcloud](https://user-images.githubusercontent.com/73851419/196779850-69919a09-b26d-444f-930e-f906a0acbced.png)

## Add default tags like action needed
![Screenshot 2022-10-19 at 20-50-24 Personal - Deck - Nextcloud](https://user-images.githubusercontent.com/73851419/196779849-8f7135be-ebcf-4333-aa99-2fbad2f0bae0.png)

## Change language to german

![Screenshot 2022-10-19 at 20-51-15 Personal - Deck - Nextcloud](https://user-images.githubusercontent.com/73851419/196779870-924e24cc-9c12-424b-ae5e-d4a062c9b661.png)

## Try to modify Tags 

![Screenshot 2022-10-19 at 20-52-03 Personal - Deck - Nextcloud](https://user-images.githubusercontent.com/73851419/196779925-a46bb4ed-8673-498b-b3d6-ea960c327094.png)

## Old default tags are removable

![Screenshot 2022-10-19 at 20-53-33 Personal - Deck - Nextcloud](https://user-images.githubusercontent.com/73851419/196780022-cbdd824d-ba2c-4ba9-86e8-800d38dbe540.png)

## New default tags are still in english and not in german

![Screenshot 2022-10-19 at 21-07-50 Personal - Deck - Nextcloud](https://user-images.githubusercontent.com/73851419/196781825-c905b919-6fff-4e84-8d57-b21716573e60.png)

**Comment by juliushaertl** [comment]
Tags are created once you create the board, so this is expected behaviour. As those are free text fields, we don't apply dynamic translations to the values.

**Comment by DJE98** [comment]
Thank you for your report. I think also these default tags shouldn't be deleted, because the information behind the tags would be lost. Instead, I think the tags should be translated with the change of the current system language. @cablesky Do you agree with me? @juliushaertl Is there a reason why we don't apply dynamic translation to the values?
