### ISSUE TITLE
Push Notifications for Comments and Actions

### ISSUE THREAD

**Issue by BiglifeMatt** [nextcloud/deck#4107]
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Not sure if this is an existing feature and just not working with my settings or if this is known not to be available or working.

**Describe the solution you'd like**
I'm expecting Push Notifications when someone makes comments or changes in a Deck, specifically a Card, that is connected with the user.  I would want the notification to push to the Web app under the Notification section up top and also in the Deck app for Android.

**Comment by stefan-niedermann** [comment]
This [FAQ entry](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#how-to-receive-notifications-when-a-due-date-is-reached) should explain everything from the point of the Deck Android app. It applies also to the Deck server app though. If you don't receive notifications while you are sure you configured everything correctly, i would consider this being a duplicate of #3843 (or #3878).

**Comment by BiglifeMatt** [comment]
That FAQ does explain it... I wish notifications could be set globally at first.  But at least we can get it working for us.
