### ISSUE TITLE
Breaking API change in `1.8.0-beta.2`: card `duedate` has wrong date format

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#4112]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
The `duedate` property had the format `2021-03-09T18:35:00+00:00"` in version `1.7.1`, while Deck `1.8.0-beta.2` returns a date with format `2022-10-20 22:00:00`.

**To Reproduce**
1. Use Deck Android to connect to an instance running Deck `1.8.0-beta.2` (like cloud.nextcloud.com). Ensure there is a card with a due date.

**Expected behavior**
Date format did not change compared to previous Deck versions.

<details>
<summary>Server details</summary>

See cloud.nextcloud.com

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)

Not available because I am only using a guest account.

</details>

Originally reported at https://github.com/stefan-niedermann/nextcloud-deck/issues/1355

**Comment by nickvergessen** [comment]
Regression from https://github.com/nextcloud/deck/pull/3782 I assume.

Will check if I can isolate the problem
