### ISSUE TITLE
Creating a docker container for easier development 

### ISSUE THREAD

**Issue by DJE98** [nextcloud/deck#4120]
I would like to have an easy to install docker container for starting development at nextcloud deck. This should be helpful in motivating more people to start supporting the project. I tried to develop such a container.

docker-compose.yml
```
version: "3.3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./deck:/deck
```
dockerfile
```
FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install nodejs -y
RUN apt-get install git -y
RUN apt-get install composer -y
RUN apt-get install vim -y
RUN apt-get install npm  -y
RUN apt-get install php-xml -y
RUN apt-get install php-mbstring -y
RUN git clone https://github.com/DJE98/deck
WORKDIR /deck
RUN npm install -D webpack
RUN npm install -D webpack-merge
RUN npm install -D webpack-cli
RUN npm install -D webpack-dev-server
RUN make install-deps
RUN make build-js
RUN npx webpack-dev-server --config webpack.hot.js --output-public-path 'http://localhost:3000/js/'
EXPOSE 3000
```

If the line make build-js executes, there is a  cascade of missing dependencies. 
```
[webpack-cli] Failed to load '/deck/webpack.js' config
[webpack-cli] { Error: Cannot find module 'vue-loader' 
```

And after the installation of such a dependence, there are new dependencies missing. I get the same problems, if I try to run the project on my productive system. Maybe a person who is more experienced in the project could help me to fix the problem.

**Comment by juliushaertl** [comment]
You will need to setup a Nextcloud server in order to run the app and test it, so I'd recommend to either have a look at https://docs.nextcloud.com/server/latest/developer_manual//getting_started/devenv.html for the manual setup, or if you prefer docker, we are currently working quite actively on a set of tutorials to get a developer setup running:

https://nextcloud.com/developer/
https://help.nextcloud.com/t/tutorial-how-to-set-up-a-nextcloud-development-environment-on-mac-or-ubuntu/145462

The tutorial actually uses a docker-compose based setup that I started at https://github.com/juliushaertl/nextcloud-docker-dev.

**Comment by juliushaertl** [comment]
Please don't hesitate to reach out if you have any further questions :)

**Comment by juliushaertl** [comment]
Also a easier way for just app development is currently in the planning at https://github.com/juliushaertl/nextcloud-docker-dev/issues/81

**Comment by DJE98** [comment]
Thank you for your fast and polite answer @juliushaertl. Now I used your docker container as in another [issue](https://github.com/nextcloud/deck/issues/3680#issuecomment-1109944704) as possible solution described and get still the same errors. Do you have an idea what the missing dependencies causes instead?

**Comment by juliushaertl** [comment]
Looking at it again maybe your distribution npm/node version is too old? We currently require node 16, npm 7/8, however it seems our README is outdated in that regard.

https://github.com/nextcloud/deck/blob/master/package.json#L71-L72

You might want to consider installing node through a version manager like https://github.com/nvm-sh/nvm that allows you to switch between different versions.

**Comment by DJE98** [comment]
Thank you for your support. Now the development environment works properly :+1:
