### ISSUE TITLE
Attach a shared file to a deck card: remember last folder location

### ISSUE THREAD

**Issue by GHBLoos** [nextcloud/deck#4128]
**How to use GitHub**
Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
Subscribe to receive notifications on status change and new comments.

**Is your feature request related to a problem? Please describe.**
When I want to add a shared file to a deck card, a pop up with folders comes up. The folder that is opened by default is the top level folder. I can browse through the folders and pick a file.
Sometimes I want to add another file. That file is most of the times in the same folder (or in a folder close by). When I want to add that file I start again with the pop-up. I expect it to start from the same folder, but it starts from the top level folder, so I have to browse through all folders again. 
See also [issue 4079](https://github.com/nextcloud/deck/issues/4079)

**Describe the solution you'd like**
Remember the last used folder when selecting a file to add to the deck card. 

**Describe alternatives you've considered**
None found

**Comment by GHBLoos** [comment]
Rethinking this issue, remembering the last folder should be an option of the file dialog. If it is already an option, then this issue is related to _deck_, because then the option should be set to `true`. Otherwise, a new issue should be created in '[server](https://github.com/nextcloud/server/issues)' for a new feature of the file dialog box (adding the feature `rememberLastSelectedDirectory (true/false)`.

**Comment by GHBLoos** [comment]
Same issue [nextcloud/server #644 ](https://github.com/nextcloud/server/issues/644)

**Comment by AndyScherzinger** [comment]
replaced with issue https://github.com/nextcloud/server/issues/39186
