### ISSUE TITLE
How to restore a deleted column ?...

### ISSUE THREAD

**Issue by ParnBlade** [nextcloud/deck#413]
Hi !
I'm on Nextcloud 12.0.3 en deck 0.3.0.

A user had del a column in deck for his project and ask me if there any change to restore it.
Have you a hint for doing this ?

Could be a good things to have a trash option or a alert message to avoid this ?

Sorry for my english ! Good work and have a nice day !

**Comment by juliushaertl** [comment]
I'm sorry, unless you have a backup of the database, there is currently no way to restore a deleted stack. This feature is already on our list for the next version. #259
