### ISSUE TITLE
Migrating from Deck to new Nextcloud instance

### ISSUE THREAD

**Issue by DuncanLithgow** [nextcloud/deck#4136]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Nextcloud 24
Deck Android App 1.20.3

**Is your feature request related to a problem? Please describe.**
I can't find any type of forum to ask for help - so I'm asking here.
My nextcloud instance died so I made a new one. This means I lost all my Deck information. But I still have it in the app. Is there a way to migrate the data from one instance to another?

**Describe the solution you'd like**
A way to move my Deck cards to a different instance from the Android app

**Describe alternatives you've considered**
I couldn't find a file to copy in my local backup of the "Files" app after nextcloud died

**Comment by logicalwillow** [comment]
I don't know how to help with the problem you're facing but the Nextcloud forum is at [help.nextcloud.com](https://help.nextcloud.com), someone might be able to help there

**Comment by DuncanLithgow** [comment]
I had to give up and lose a bunch of data. Disappointing. Thanks for the tip.

**Comment by putt1ck** [comment]
@DuncanLithgow you might have got an answer from the developer of the app https://github.com/stefan-niedermann/nextcloud-deck/

**Comment by stefan-niedermann** [comment]
> A way to move my Deck cards to a different instance from the Android app

This is already possible - card by card though. Keep in mind: the Deck Android app is *not* a backup tool. We currently do not have any plans to provide complete migrations to another instance in our **client** application
