### ISSUE TITLE
Freeze after editing a card and going back to upcoming cards

### ISSUE THREAD

**Issue by lordg2009** [nextcloud/deck#4144]
**Describe the bug**
After editing a card in the tab 'upcoming cards' the decks app jumps to the board, the card is stored in. After going back to 'upcoming cards' no card nor a other board can be loaded. while clicking on the card or board the url in the address bar is beeing updated but the link is not beeing loaded. To edit another card or go to another board I have to click on the decks app icon in the main navigation bar once again to start from scratch.

**To Reproduce**
1. Go to 'decks'
2. click on a card in the 'upcoming cards' tab
3. close the card
4. click on 'upcoming cards'
5. See error: no other card or board is beeing loaded

**Expected behavior**
After clicking on a card or a board the edit windows or board will apear as normal.

**Screenshots**

**Client details:**
 - OS-server: debian 11
 - OS-client: Windows
 - Browser: edge and firefox
 - Version (nextcloud): 25 but also 24 before Upgrade
 - Version (decks): 1.8 but also 1.7.x
 - PHP-Version: 7.4
 - web-server: apache2

**Javascript console after clicking the card with nothing happening:**
```
DOMException: Node.insertBefore: Child to insert before is not a child of this node [main.js:60:25](webpack:///deck/src/main.js)
    errorHandler main.js:60
    VueJS 10
    init vue-router.esm.js:2985
    init vue-router.esm.js:2985
    updateRoute vue-router.esm.js:2402
    transitionTo vue-router.esm.js:2251
    confirmTransition vue-router.esm.js:2540
    r vue-router.esm.js:2068
    r vue-router.esm.js:2072
    r vue-router.esm.js:2072
    r vue-router.esm.js:2072
    Hn vue-router.esm.js:2073
    confirmTransition vue-router.esm.js:2535
    r vue-router.esm.js:2068
    r vue-router.esm.js:2071
    p vue-router.esm.js:2372
    n vue-router.esm.js:2144
    p vue-router.esm.js:2506
    r vue-router.esm.js:2068
    r vue-router.esm.js:2072
    r vue-router.esm.js:2072
    r vue-router.esm.js:2072
    Hn vue-router.esm.js:2073
    confirmTransition vue-router.esm.js:2373
    transitionTo vue-router.esm.js:2246
    push vue-router.esm.js:2703
    push vue-router.esm.js:3027
    push vue-router.esm.js:3026
    openCard CardItem.vue:167
    VueJS 33
No new notification data received [NotificationsApp.vue:370](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:402](webpack:///notifications/src/NotificationsApp.vue)
No new notification data received [NotificationsApp.vue:370](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:402](webpack:///notifications/src/NotificationsApp.vue)
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 [globals.js:60:15](webpack:///nextcloud/core/src/globals.js)
No new notification data received [NotificationsApp.vue:370](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:402](webpack:///notifications/src/NotificationsApp.vue)
No new notification data received [NotificationsApp.vue:370](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:402](webpack:///notifications/src/NotificationsApp.vue)
No new notification data received [NotificationsApp.vue:370](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:402](webpack:///notifications/src/NotificationsApp.vue)
No new notification data received [NotificationsApp.vue:370](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000
```

**Comment by neufeind** [comment]
Same here with NC 25.0.1 and Deck 1.8.2. Could it be that's just about "upcoming cards"?

**Comment by neufeind** [comment]
Would it be possible to add allow some "open in new tab" as a quick workaround? Since these aren't normal links but click-events instead you unfortunately can't use new-tab-clicks of the browser.

**Comment by HonkXL** [comment]
Is this the same as #3837 ?

**Comment by juliushaertl** [comment]
I also cannot reproduce this. Since the version reported is quite old, please try if this is still an issue on the latest and don't hesitate to reopen if it is still an issue.
