### ISSUE TITLE
Feature Request: Add option to revoke user/group "delete" permissions

### ISSUE THREAD

**Issue by chrisHRD** [nextcloud/deck#4160]
**Description of Feature Request**
Add a checkbox option to a board's "sharing" settings which would remove a user/group (who has editing permission) ability to delete cards/lists. 

**Purpose of Feature**
To enable managers who are responsible for a card's successful completion to delegate the card to an employees without losing control of the "closing" of a card/list. Also to prevent accidental data deletion by the employee, which could result in termination from the organization. 

**Related Issues**
#872

**Comment by Gobytego** [comment]
also archive

**Comment by juliushaertl** [comment]
Thanks for your feature request. I can see this is a valid use case however we currently consider deck more as a simple tool that is easy to use and want to keep the complexity low. We target common use cases but don’t necessarily want to extend to a fully fledged project management tool. There are lots of good open source tools out there already for more complex use cases. Therefore I’d consider this out of scope.

It might be worth to have a look at the tables app  which would allow separate views with different permissions on a shared dataset.
