### ISSUE TITLE
In the new NC dark theme with NC version 25, individual deck cards have poor visibility against the black background

### ISSUE THREAD

**Issue by emes81** [nextcloud/deck#4181]
<!--
Thanks for reporting issues back!

Guidelines for submitting issues:

* Please search the existing issues first, it's likely that your issue was already reported or even fixed.
  
* SECURITY: Report any potential security bug to us via our HackerOne page (https://hackerone.com/nextcloud) following our security policy (https://nextcloud.com/security/) instead of filing an issue in our bug tracker.  

* The issues in other components should be reported in their respective repositories: You will find them in our GitHub Organization (https://github.com/nextcloud/)
  
**Describe the bug**
Individual cards have poor visibility

**To Reproduce**
1. Set NC to use dark mode
2. Go to Deck and create several cards
3. Select 1 card. The other cards will now be hardly distinct from the background, as the card and background have the same colour, separated by a border of similar colour

**Expected behavior**
Cards are visible and distinct

**Screenshots**
![image](https://user-images.githubusercontent.com/25403691/199768921-2758f47a-4ba8-4da4-9406-25b237987947.png)

**Client details:**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 105
 - Device: [desktop]

**Comment by mokkin** [comment]
I'm not completely sure if @emes81 means distinguishing one card from another or the visibility of checked tags. The first one could be better, but the checkboxes are indeed invisible:
![grafik](https://user-images.githubusercontent.com/2938748/200514095-60037dfa-a265-4d3e-8b64-baca6c728439.png)

![grafik](https://user-images.githubusercontent.com/2938748/200514229-133ca9d7-19c4-43f8-8fc1-536d6e47d519.png)

**Comment by juliushaertl** [comment]
@emes81 Maybe you can provide some screenshots on what exactly you are referring to.

**Comment by emes81** [comment]
That's odd - I did include a screenshot before, unsure what happened.

What I meant was that individual cards are difficult to perceive against the background, and thus difficult to distinguish from one another:

![image](https://user-images.githubusercontent.com/25403691/200546330-a709ebe9-47ca-4b5f-b729-713f5b57e0d1.png)

Here's the same cards in light mode, somewhat more clear:

![image](https://user-images.githubusercontent.com/25403691/200546578-0bf924cd-b841-4071-b623-5e726d216aec.png)

And for comparison, a similar setup from Trello:

![image](https://user-images.githubusercontent.com/25403691/200546800-a637f3a4-8c57-428c-a9ad-f6cccafc02b2.png)

**Comment by nivadis** [comment]
same here with white background (see keywords)
<img width="450" alt="Bildschirmfoto 2022-12-09 um 13 08 59" src="https://user-images.githubusercontent.com/814064/206699712-2fe84d49-c7d5-4950-b886-8945a38e37d0.png">

**Comment by mhzawadi** [comment]
This is still an issue, I can tell where 1 card end and the next starts. Please add some kind of highlight to cards

![image](https://user-images.githubusercontent.com/11944327/213567996-eaa6a6bb-e15a-4af5-a1d8-fe6d4bf1e4c4.png)

**Comment by juliushaertl** [comment]
Closing as a duplicate of #5034 which is newer but has design discussion already kicked off
