### ISSUE TITLE
Unified search broken : an error occured when searching for Deck

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/deck#4190]
**Describe the bug**
With Nextcloud 25.0.1 / PHP8.0 and Deck 1.8.1, when using unified search, I get the error "An error occured when searching for Deck" and "An error occured when searching for Card comment".

**To Reproduce**
1. Type some text in unified search box
2. See error

**Expected behavior**
Unified search should work as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/6248852/200164821-eeb3880a-fad6-4b93-8de9-d3abc853be43.png)

**Client details:**
 - OS: Xubuntu
 - Browser Firefox
 - Version 106.0.5.
 - Device: Computer

<details>
<summary>Server details</summary>

**Operating system**:
Debian 11

**Web server:**
Apache 2

**Database:**
Maria DB

**PHP version:**
8.0.22

**Nextcloud version:** (see Nextcloud admin page)
25.0.1

**Where did you install Nextcloud from:**
Upgrading from NC24

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - analytics: 4.5.0
  - announcementcenter: 6.4.0
  - calendar: 4.1.0
  - cfg_share_links: 3.0.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.1
  - emlviewer: 1.0.2
  - event_update_notification: 2.0.0
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_automatedtagging: 1.15.0
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_linkeditor: 1.1.12
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_texteditor: 2.14.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.1.2
  - forms: 3.0.1
  - groupfolders: 13.0.0
  - issuetemplate: 0.7.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.1.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.0
  - polls: 4.0.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - smb_test: 0.3.5
  - snappymail: 2.20.2
  - spreed: 15.0.1
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.2.0
  - calendar_resource_management: 0.1.0
  - customproperties: 2.0.4
  - encryption
  - extract: 1.3.5
  - files_markdown: 2.3.6
  - firstrunwizard: 2.12.0
  - group_everyone: 0.1.10
  - impersonate: 1.11.0
  - pdfdraw
  - privacy: 1.7.0
  - recommendations: 1.3.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - suspicious_login
  - tables: 0.2.1
  - workflow_script: 1.8.0

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.agglo-montbeliard.fr",
            "192.168.50.106",
            "192.168.50.106"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.agglo-montbeliard.fr\/",
        "dbtype": "mysql",
        "version": "25.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto, 15",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "default_phone_region": "FR",
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "spreed",
            "files_mindmap",
            "pdfdraw",
            "issuetemplate",
            "files_linkeditor",
            "files_texteditor",
            "files_trackdownloads",
            "emlviewer"
        ],
        "allow_local_remote_servers": true,
        "default_language": "fr",
        "force_language": "fr",
        "default_locale": "fr_FR",
        "force_locale": "fr_FR",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_memory": 512,
        "app.mail.verify-tls-peer": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 'owncloud.c.title' isn't in GROUP BY

#### Browser log
```
Insert your browser log here, this could for example include:

[ERROR] unified-search: Error searching for Deck 
Object { level: 2, app: "unified-search", uid: "jvuitten", message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…} }
[ConsoleLogger.js:64:10](webpack:///nextcloud/node_modules/@nextcloud/logger/dist/ConsoleLogger.js)
    value ConsoleLogger.js:64
    value ConsoleLogger.js:91
    t UnifiedSearch.vue:522
    Babel 3
    pn SearchResultPlaceholders.vue:20
    s SearchResultPlaceholders.vue:20
    (Asynchrone : promise callback)
    pn SearchResultPlaceholders.vue:20
    o SearchResultPlaceholders.vue:20
    fn SearchResultPlaceholders.vue:20
    fn SearchResultPlaceholders.vue:20
    t UnifiedSearch.vue:482
    t UnifiedSearch.vue:482
    Babel 3
    pn SearchResultPlaceholders.vue:20
    o SearchResultPlaceholders.vue:20
    (Asynchrone : promise callback)
    pn SearchResultPlaceholders.vue:20
    o SearchResultPlaceholders.vue:20
    fn SearchResultPlaceholders.vue:20
    fn SearchResultPlaceholders.vue:20
    onInput UnifiedSearch.vue:441
    onInputDebounced UnifiedSearch.vue:540
    l index.js:27
    (Asynchrone : setTimeout handler)
    l index.js:22
    (Asynchrone : setTimeout handler)
    c index.js:38
    VueJS 3
        Ft
        n
        _wrapper

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Can you share the full json log line from the nextcloud.log file?

**Comment by Mer0me** [comment]
As a workaround I've added this lines on the top of the search function of  /deck/lib/Search/CardCommentProvider.php and /deck/lib/Search/DeckProvider.php :

` public function search(IUser $user, ISearchQuery $query): SearchResult {
                $result=[];
                return SearchResult::paginated(
                        'Deck',
                        [],
                        null
                );
                $cursor = $query->getCursor();
`

Warning : it's disabling the search on Deck app too...

**Comment by Mer0me** [comment]
Still present on v1.8.2

**Comment by Mer0me** [comment]
Still present on v1.8.3

**Comment by marcelklehr** [comment]
Which MariaDB version is this? From what I can tell, since the title column is funtionally dependent on the id column it shouldn't be necessary to list it in the GROUP BY clause. This should be supported in MySQL 5.7.5+

**Comment by Mer0me** [comment]
5.5.5-10.3.36-MariaDB-0+deb10u2

**Comment by Mer0me** [comment]
It works ! Thank you.
