### ISSUE TITLE
Exact date/time display not working for timestmamp of comments, only for timestamps of card title

### ISSUE THREAD

**Issue by Alphaphi15** [nextcloud/deck#4192]
Bug description: 
Date/timestamp of the creation date of a deck card is displayed correctly when hovering with the mouse over the title. But the date/timestamp is NOT displayed when hovering with the mouse over the field "X mins/days/months ago" right to a comment.

To reproduce:
Create a card in deck. Open the card, go to comments, and add a comment. Save the comment.
Hover with the mouse over the title. In addition to "created a min ago / changed a min ago", a bubble text with the exact created/changed timestamp is displayed.
Hover with the mouse over the field right to the commend. No exact timestamp is desplayed in addition of "1 minute ago".

Expected behavior:
A bubble text with the exact timestamp should be displayed.

Screenshot
![221107-Screenshot](https://user-images.githubusercontent.com/90706231/200312101-dd2464da-9baa-4916-a1eb-8db2c0e07cbf.png)

Client details:
- Linux
- Firefox 106.0.5
- Nextcloud 24.0.5 as provided by Hetzner (Storage Share)

**Comment by seabokas** [comment]
This fix would be excelent, can´t wait.

**Comment by Alphaphi15** [comment]
Is there a way to see what the status of this topic is? Are things happening upstream already, and is there an ETA? I'm not yet familiar with the development process, thus the question.

**Comment by fitrahfm** [comment]
I've added a tooltip for the timestamp of comments. Can I make a pull request?

**Comment by fleopaulD** [comment]
> I've added a tooltip for the timestamp of comments. Can I make a pull request?

Don’t hesitate to make your pull request !! This is a highly anticipated feature 😅
Owners will make comments directly in the PR section
