### ISSUE TITLE
Board share button has no function

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#4197]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
In the left sidebar, the share button next to the board name has no function

**To Reproduce**
1. Go to the Deck app
2. Click on the share button in the left sidebar next to a board name

**Expected behavior**
The right sidebar being opened with the Share tab being selected

**Screenshots**
![image](https://user-images.githubusercontent.com/4741199/200770543-d3ed2724-1d57-4dd4-9173-0f9b315522ad.png)

**Client details:**
 - OS: Debian
 - Browser Firefox
 - Version Flatpak 106
 - Device: Desktop

<details>
<summary>Server details</summary>

**Nextcloud version:** 25

**Deck version:** 1.8.1
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
No relevant log

#### Browser log
No relevant log

</details>

**Comment by etieng** [comment]
After upgrading to Nextcloud 25 it's now impossible to share a deck. Old shares cannot be modified/removed anymore. Any info on this ?
Nextcloud 25.0.2
Deck 1.8.2

**Comment by jdavid82** [comment]
This is the error I get after upgrading to Nextcloud Hub 3 (25.0.3)/Deck 1.8.3
![image](https://user-images.githubusercontent.com/463793/213053679-ecf792cd-6f83-4dac-8478-b1d436575953.png)

**Comment by fschrempf** [comment]
This bug is also reproducible on NC 24.0.10 and Deck 1.7.3. The browser console shows:

```
Uncaught TypeError: OCA.Files.fileActions is undefined
    <anonymous> viewer.js:63
    <anonymous> viewer.js:43
    <anonymous> viewer.js:43
```

**Comment by fschrempf** [comment]
It seems like this has never been working. See https://github.com/nextcloud/deck/issues/2910. Closing this as duplicate.

**Comment by thamin-i** [comment]
For anyone still dealing with this issue, I encountered the same error, and enabling the file_sharing app on my Nextcloud instance resolved it.
