### ISSUE TITLE
Line break ignored in Card Description

### ISSUE THREAD

**Issue by knieskopp** [nextcloud/deck#4199]
Line breaks in card description are ignored once editing is finished.

Steps to reproduce:

1. create card
2. add description with line breaks
3. click outside of card to finish edit
4. reopen card

Expected behavior:
Line breaks showing up in description preview

![grafik](https://user-images.githubusercontent.com/62883209/200799461-1be80db8-be08-4db6-aed0-00c0ddda7a31.png)

![grafik](https://user-images.githubusercontent.com/62883209/200799360-cc183027-64c5-4f3c-aeb6-c409466ef54f.png)

**Comment by ma651851384** [comment]
Hi @knieskopp . As far as I know, this is not a bug, it is a known function of the markdown language, which is used for formatting the text of the deck card description.

To add a line break, you have to add at least to spaces (by space bar) at the end of a line. Then, the line break works fine. I have tried this with my installation.

**Comment by juliushaertl** [comment]
Yes, this is the expected behaviour and the markdown spec is also referenced in https://deck.readthedocs.io/en/latest/Markdown/

However this might of course be confusing. This will improve once we switch to a rich text editor as planned with #1561
