### ISSUE TITLE
Separate "high priority" card tag

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#421]
While using deck in our setup the use case for a separate "high priority" mark has shown up. The self defined colour tags are useful but lack some unique attribute to distinguish high priority tasks. For us it seems to be useful to be able to tag a card as "high priority" separate to the self defined tags.

A card marked this way could optionally be moved automatically to the top and / or be filtered by the upcoming filter features in https://github.com/nextcloud/deck/issues/414

It could look something like this (with a better and more suitable design):

![deck_high_priority_card_example](https://user-images.githubusercontent.com/29312856/36366524-d834a9ec-154e-11e8-884a-d9aa449b423b.png)

**Comment by juliushaertl** [comment]
From my point of view using normal tags would be enough for that. You can just use one color for a high priority label, so it should be easy to distinguish and filters from #414 will allow you to sort them first/show just those cards.
