### ISSUE TITLE
Add a confirm dialog box for deleting stacks (& perhaps cards)?

### ISSUE THREAD

**Issue by jacestk** [nextcloud/deck#424]
Lot of usershere have lost complete stacks with tons on cards in.
When they try to re-order the stacks, as the delete button is actually masked, some of them accidently click on the trash and delete all the job! It is not cool... :/
Is it possible to display a confirm dialog ?

### Steps to reproduce
1. Just clic on delete icon
2. and it is deleting without confirmation!

### Expected behaviour
A dialog box asking if we are sure of this :D

**Comment by juliushaertl** [comment]
We plan to add undo to delete as described in #259 in the next version. So closing this as a duplicate. I'm aware that his is something urgent, this is actually the next on my list when starting to develop features for deck 0.4.
