### ISSUE TITLE
Invisibly assign users to cards without sending notification

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/deck#426]
Feature request:

In our daily workflow we would like to be able to assign users without sending out a notification or the need to share a board. (assignment should be invisible to assigned user at first)
* First use case is for personally monitoring tasks without the need of sharing boards.
* Second use case is to create a board with cards and assign users and share the board only when everything is finally ready to be shared (better for larger projects).

**Comment by juliushaertl** [comment]
> First use case is for personally monitoring tasks without the need of sharing boards.

It would make sense to not notify about own actions of course. :+1: 

> Second use case is to create a board with cards and assign users and share the board only when everything is finally ready to be shared (better for larger projects).

Assigning users that have no access to the board seems to be somehow wrong from a UX point of view. That might lead to confusion when users think that they assigned a card to someone, but that person isn't aware of it, because the board is not shared.

**Comment by supremesyntax** [comment]
First use case is for personally monitoring tasks without the need of sharing boards.

It would make sense to not notify about own actions of course. +1

oh you got me wrong on this one... both use cases are based on assigning users without notifying them until i want them to be notified.

I agree in the UX pov. 
Of course there needs to be some hint or indicator that a user is assigned but board is not visible to this user(s) and needs to be shared to be visible (maybe greyed out user icon or with a striked out eye icon overlay).

Background is this:
A manager wants to create a large board for a project with dozens of cards. Every card should be assigned to different user(s).
As soon as the board is shared with a group (circles are not available in current version) the whole board (all cards) are visible to the users with no users assigned to the cards.
So the user(s) get notifications about the board being shared but doesn't see his name anywhere.
The manager now has to assign users to the already shared and visible cards one by one and the user(s) have to check if they are assigned periodically.

Better solution in this case would be the second point in my first post.

Better/alternative solutions welcome!

**Comment by 9662** [comment]
Just write the name of the to-be-assigned user in the content (or title) of the card.

**Comment by juliushaertl** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
