### ISSUE TITLE
Deck - Link issues and Board Timeline not being shown

### ISSUE THREAD

**Issue by aquananu** [nextcloud/deck#4279]
after update to deck 1.7.3 on nextcloud snap 24.0.7, 

the deck has started to behave abruptly, some times clicking on  the navigation menu doesnt open the menu rather it bring back to upcoming cards board

Even on click the cards from upcoming board leads to someother board than the card and card doesnt open up

also the timeline of the boards is empty.

**Comment by juliushaertl** [comment]
Please fill out the issue template and provide the relevant details (especially brower/nextcloud error messages). It is there for a reason. Otherwise we cannot tell what went wrong.
