### ISSUE TITLE
Description and Comments listed in the same screen for easyier reading/interacting

### ISSUE THREAD

**Issue by ronniegarcia** [nextcloud/deck#4300]
Nextcloud 24.0.7
Deck  1.7.2

**Is your feature request related to a problem? Please describe.**
From time to time, my users and myself are no longer using the "Comments" feature but instead we write comments inside the Description text area. The reason is : here we can read the initial Description AND the Comments in one place.
The problem with such "comments" inside the Description area is that we loose the automatic "Author" and "Date" metadata, such "comments" may not be well sorted, some people write new comments on top of others, others write bellow older comments, etc

**Describe the solution you'd like**
I would like the "Comments" feature to be in the same screen as the Description text area :
- New Comment text input
- List of all comments sorted (by date)

The only limitation i imagine is that, if the Description is a very long text, the Comments will be far bellow. Maybe an anchor link placed at the top of this screen, and pointing to the "New Comment" text input can be the solution.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by juliushaertl** [comment]
This is part of the larger design discussion in https://github.com/nextcloud/deck/issues/2702 so I'll close this as a duplicate
