### ISSUE TITLE
scrolling in the deck

### ISSUE THREAD

**Issue by MercuryOZ** [nextcloud/deck#433]
### Steps to reproduce
1. open your deck with 10 decks in it
2. try to reach the last deck
3. scrolling bar is to small to observe it

### Expected behavior
scrolling bar is easy to observe it. the user can change standard wide of the deck so its no need to scroll it.

### Actual behaviour
The scrollbar is too small and it hard to observe it. A lot of decks is hidden out of the screen border

**VIDEO** - https://goo.gl/jUQgEA

### Server configuration

**Nextcloud version:** Nextcloud 13.0.0

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.
**List of activated apps:**

Activities for shared file downloads | 1.2.0
-- | --
Activity | 2.6.1
Admin notifications | 1.0.1
AppOrder | 0.4.1
  |  
Auditing / Logging | 1.3.0
Calendar | 1.6.0
  |  
Collaborative tags | 1.3.0
Comments | 1.3.0
Deck | 0.3.0
  |  
Deleted files | 1.3.0
Draw.io | 0.8.9
Federation | 1.3.0
File sharing | 1.5.0
First run wizard | 2.2.1
Gallery | 18.0.0
  |  
Impersonate | 1.0.2
  |  
LDAP user and group backend | 1.3.1
Log Reader | 2.0.0
  |  
Mail | 0.7.10
  |  
Monitoring | 1.3.0
  |  
Notifications | 2.1.2
ONLYOFFICE | 1.2.0
Password policy | 1.3.0
  |  
PDF viewer | 1.2.0
  |  
QOwnNotesAPI | 17.5.0
  |  
Share by mail | 1.3.0
Text editor | 2.5.1
  |  
Theming | 1.4.1
Update notification | 1.3.0
  |  
Usage survey | 1.1.0
  |  
Versions | 1.6.0
Video player | 1.2.0

```

**Comment by juliushaertl** [comment]
The reasoning is the same as in #434, so we won't add an option for the width. The scroll bar height is actually the same across Nextcloud, but I'm not sure if it is worth making that bigger since you can access it and tochpads and mouses offer their own mechanism for scrolling.

**Comment by juliushaertl** [comment]
Closing as a server issue. See https://github.com/nextcloud/server/issues/6275 for further discussion about the scrollbar size.
