### ISSUE TITLE
Crashing iOS Deck app

### ISSUE THREAD

**Issue by dirk80** [nextcloud/deck#4331]
When opening the Nexcloud Deck app on my Iphone 12 the app shows the loading icon like in the attached screenshot for one second. After one second the screen turns white. I can not get the app get working again.

I deinstalled and reinstalled the app but the problem stays.
I havenot used the app for some probably 2-3 weeks. I do not know if there has been an update on the app on nextcloud or iOS but suddenly it is not working any more.

My collegue using the same Nextcloud installation with his login has no problem on his older iPhone.

 - OS: iOS 16.1
 - Nextcloud Version: 24.0.7
 - Deck Version: 1.7.3
 - Nextcloud provider: Ionos

**Comment by stefan-niedermann** [comment]
This is the repository of the Deck server app. Please open your issue in the repository of the Deck iOS app you are using.
