### ISSUE TITLE
Tags/Labels are not shown directly after adding

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#4332]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

When adding a tag/label to a card, it is not shown directly in the label field. However, this makes it hard to see if a label is already applied or not.
Do I imagine it or was this working before? (I'm not sure but I feel like this broke couple of versions ago)

**To Reproduce**
1.  Create new card
2. Add label
3. Label does not show up in list, only until one clicks somewhere else

**Expected behavior**
The label should show up immediately in the label field

**Screenshots**
![Animation](https://user-images.githubusercontent.com/431045/209312378-01e2021e-4e94-41bd-b02b-0412815e4898.gif)

**Client details:**
 - OS: W11
 - Browser: Firefox
 - Version: 108.0.1
 - Device: Desktop
<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**
nginx

**Database:**
psql

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
25.0.2

**Deck Version:**
1.8.2

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
```

</details>

**Comment by sebastiaanveld** [comment]
I've the same issue and running into this over several NC versions;

Client details:
    OS: Win11
    Browser: Firefox
    Version: 118.0.1
    Device: Desktop

Server details:
Operating system:
Ubuntu

Web server:
Aapache

Database:
psql

PHP version:
8.1

Nextcloud version: (see Nextcloud admin page)
27.1.2.1

Deck Version:
1.11.0

**Comment by joshtrichards** [comment]
This has been fixed.
