### ISSUE TITLE
Decks no longer managable by shared users/groups

### ISSUE THREAD

**Issue by sauramel** [nextcloud/deck#4343]
**Describe the bug**
Users with whom a deck is shared with (and have can edit turned on) are unable to invite others to that deck or add new lists to it, this was previously possible.

**To Reproduce**
1. Create a deck
2. Add another nc user to that deck with the edit permission
3. As that user, go to create a new list on this deck (there will be no option)

**Expected behavior**
The manage permission should be assignable again

**Install details**
- Nextcloud Version: 25.0.1
- Decks Version: 1.8.2

**Client details:**
 - OS: Windows
 - Browser: Chrome
 - Version ??
 - Device: Desktop

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/deck/pull/4315 and released as 1.8.3
