### ISSUE TITLE
Deck shows empty white dialog box after creating a new card

### ISSUE THREAD

**Issue by nuokh** [nextcloud/deck#4349]
**Describe the bug**
Nextcloud Deck displays an empty box after adding a new card inside the "Upcoming Cards" view.

**To Reproduce**
1. Go to 'Upcoming Cards'
2. Click on the + to add a new card
3. Fill out the new card dialog
4. Click "Create card"
5. See the empty box

**Expected behavior**
No empty box after card creation.

**Screenshots**

![image](https://user-images.githubusercontent.com/9081831/210079299-27989932-f7ab-469e-8e73-a4e54115ea8d.png)
![image](https://user-images.githubusercontent.com/9081831/210079314-73ec1592-a36b-4b23-97e3-135f949009cb.png)

**Client details:**
 - OS: Windows
 - Browser: Chrome 
 - Version: 108.0.5359.125
 - Device: Desktop

**Comment by nuokh** [comment]
This also happens when using the "+ Add Card" button within the dashboard Deck widget "Upcoming Cards".

**Comment by nokia001** [comment]
Same here

**Comment by St3f4nJ** [comment]
Same here. Just installed Deck and wondered that it is not working.

**Comment by dkennerknecht** [comment]
Same for me 
Browser: Chrome
Nextcloud 25.0.3
Deck 1.8.3

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/deck/pull/4561
