### ISSUE TITLE
Translation of confirmation when delete a stack is not displayed

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#435]
tested with Deck v0.3.1-rc1 and NC 13

The confirmation when deleting a card is translated, but when deleting a stack the confirmation is not translated

Perhaps it's the missing t(...) in StackService.js

[https://github.com/nextcloud/deck/blob/ad9ce6cd26f06bf46db11d2355be8c077734ae02/js/service/StackService.js#L126](https://github.com/nextcloud/deck/blob/ad9ce6cd26f06bf46db11d2355be8c077734ae02/js/service/StackService.js#L126)

like in 
[https://github.com/nextcloud/deck/blob/ad9ce6cd26f06bf46db11d2355be8c077734ae02/js/controller/BoardController.js#L172](https://github.com/nextcloud/deck/blob/ad9ce6cd26f06bf46db11d2355be8c077734ae02/js/controller/BoardController.js#L172)

**Comment by juliushaertl** [comment]
Thanks for testing the RC, yes that needs to be fixed.

**Comment by juliushaertl** [comment]
@cloud2018 mind opening a pull request to fix that? Would be awesome.
