### ISSUE TITLE
Link Card to Project - option missing

### ISSUE THREAD

**Issue by aquananu** [nextcloud/deck#4351]
Deck app 1.8.3

Nextcloud version 25.0.2 Snap install

The option of linking cards to a project is no longer there in the cards.

Also the earlier linked cards cannot be accessed by opening a card

Please advise from where to enable this option.

**Comment by stefan-niedermann** [comment]
Please use the 🔍 search function before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/4213
