### ISSUE TITLE
Update workflows to use a more recent ubuntu image

### ISSUE THREAD

**Issue by alangecker** [nextcloud/deck#4357]
the Ubuntu 18.04 runner image is deprecated and its actions currently fail due to a scheduled brownout which intends to raise awareness about that (it works 🎉 )
see https://github.com/actions/runner-images/issues/6002

## What to do
- in `phpunit.yml` and `appbuild.yml` update the runner images to `ubuntu-22.04` or `ubuntu-latest` (which one to choose?)
- ensure everything works

**Comment by juliushaertl** [comment]
I think bumping should work fine since other apps work fine with that. Let me open a pr to see if it still passes.

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/deck/pull/4358
