### ISSUE TITLE
Missing column 'deleted_at' on table 'oc_deck_attachment'

### ISSUE THREAD

**Issue by Engwer** [nextcloud/deck#4361]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

I wanted to install, actually re-install, the deck app from the admin account. When installing or enabling the deck app, I get the error message `Database error when running migration 10800Date20220422061816 for app deck. There is no column with name 'deleted_at' on table 'oc_deck_attachment'.`

After doing some research, I came across this issue #2754 where one question was whether I had deck installed before and skipped a few versions. This is in fact true. Unfortunately, I can't run `occ migrations:status deck` as this gives the error `There are no commands defined in the "migrations" namespace.` 

When I run `occ app:list`, the output shows `deck: 0.3.1` under disabled apps.

**To Reproduce**
1. Login to admin account
2. Go "Apps" page
3. Install or enable "Deck" app

**Expected behavior**
Deck app is installed, enabled and usable

**Screenshots**

**Client details:**
 - OS: Windows
 - Browser: Firefox
 - Version: 108.0.1 (64-bit)
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**: Ubuntu 20.04.5 LTS

**Web server:** NGINX

**Database:** MariaDB 8.0.31-0ubuntu0.20.04.2

**PHP version:** PHP 8.1.13

**Nextcloud version:** 25.0.2

**Where did you install Nextcloud from:** manually from nextcloud download

</details>

**Comment by joshtrichards** [comment]
> When I run occ app:list, the output shows deck: 0.3.1 under disabled apps.

v0.3.1 is from ~2017. It's very old. Try removing kt (not just disabling) and then installing a more current version installed.

This matter was addressed a long time ago via #2521.

See also https://github.com/nextcloud/deck/issues/2040#issuecomment-645915789
