### ISSUE TITLE
Give the user an option to return to board, not default ot upcoming cards

### ISSUE THREAD

**Issue by rightsaidfred99** [nextcloud/deck#4372]
I think some users will never use upcoming cards, but individual boards. 
I think it would be great to have a little setting in Deck, whereby a user can choose the default landing page for Deck. 

Upcoming cards
Use last view
Use "x" board

**Comment by stefan-niedermann** [comment]
Please use the 🔍 search function before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/2590

**Comment by alvarofranz** [comment]
The linked issue is not a duplicate. This issue is different.

> Linked is about showing the board list on load.
> This issue is about showing a default board on load.
