### ISSUE TITLE
No access to Deck from iPhone

### ISSUE THREAD

**Issue by witzker** [nextcloud/deck#4384]
Pls see this:
https://help.nextcloud.com/t/white-page-after-login-after-updating-deck/151992/3
and this in German:
https://help.nextcloud.com/t/zugriff-auf-die-nextcloud-url-von-iphone-nicht-moglich/153670
Access to deck in Android App is working!
Access with Nextcloud app is also working on iPhone!

Maybe get in contact with your colleges from NextCloud APP to get their knowledge how to connect an APP from iPhone to NextCloud
Hope for solution soon

**Comment by joshtrichards** [comment]
The iOS Deck client app you appear to be using handles it's issues here per the developer: https://framagit.org/StCyr/deck-react-native/

Looks like this may be related to an active issue over there: https://framagit.org/StCyr/deck-react-native/-/issues/89
