### ISSUE TITLE
Import/Export function

### ISSUE THREAD

**Issue by JOduMonT** [nextcloud/deck#4394]
I simply love NextCloud and Deck but one big thing I feel is missing is the ability to export and import such as; of course inside the same account and nextCloud I could duplicate a deck but what if, like Trello, Notion ... I want to make a template and allowed other user, outside of my NextCloud to simply import it into their Cloud?
I believe that would even open an opportunity to make it more viral

**Comment by dodedodo** [comment]
This is a duplicate to issue #3508 and #3507.

Oh and also  #3709, #2654, #1847, #1089, #87 and #30...

**Comment by max-nextcloud** [comment]
closing as duplicate
