### ISSUE TITLE
As the last element of the "Assign a tag to this card…" menu, add a "+ Add a new tag" option

### ISSUE THREAD

**Issue by SethFalco** [nextcloud/deck#4397]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

It's a bit annoying when users want to assign tags to a card, but the tag doesn't exist. Then the user has to navigate out to the board settings under tags, create it, then navigate back.

**Describe the solution you'd like**

It would be very pleasant if users could create tags through the flow to assign tags instead of having to manually navigate to the tags menu. 

**Describe alternatives you've considered**

If it's too difficult to come up with a positive UX for the above, at least adding a new option at the bottom called `+ Add a new tag` which just redirects the user to the board menu tags settings to create a new tag so users don't have to navigate there manually would be great!

**Additional context**

Here is an example of how it could look via dev tools:
![image](https://user-images.githubusercontent.com/22801583/213861878-9a2eeef1-3bec-46c5-bba3-0a33ddc4d368.png)

Then if a user clicks "+ Add a new tag" it will either:
* Direct the user to board settings → tags → add a new tag
* Or the UI to add a tag will appear here as a modal to be created without unfocusing on the current card whatsoever

**Comment by joshtrichards** [comment]
This is since been implemented. :)
