### ISSUE TITLE
Cannot add stacks as no menu is there

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/deck#440]
### Steps to reproduce
Simply open the deck layout in nextcloud.

### Expected behaviour
In the upper right corner there are the controls to add a new stack, view the archived cards and open the board configuration.

### Actual behaviour
The corresponding `div` tag has a class `hidden` attached and therefore is not visible by css. Removing the class in the web developer of the browser allows to use the site.

### Server configuration

**Operating system:** Linux 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64

**Webserver:** Apache/2.4.29 (Unix) OpenSSL/1.1.0g mod_fcgid/2.3.9 (fpm-fcgi)

**Database:** mysql 10.1.31

**PHP version:** 7.2.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, apcu, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, bcmath, curl, gd, iconv, intl, ldap, mysqli, odbc, pdo_mysql, zip, apc, Phar, Zend OPcache, xdebug

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:**  fresh install with minor updates in the apps

**Signing status:**

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.6.1
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - checksum: 0.3.5
  - comments: 1.3.0
  - contacts: 2.1.2
  - dashboard: 4.0.6
  - dav: 1.4.6
  - deck: 0.3.1
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_frommail: 0.1.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.0
  - files_reader: 1.2.3
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.2
  - issuetemplate: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ocsms: 1.12.2
  - ownpad: 0.6.5
  - password_policy: 1.3.0
  - phonetrack: 0.2.2
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - richdocuments: 2.0.3
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_usage_report: 1.0.1
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www2.wolf-stuttgart.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/www2.wolf-stuttgart.net\/nextcloud",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "production",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN"
    }
}
```

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Firefox 58.0.2

**Operating system:** Ubuntu 14.04LTE

#### Nextcloud log (data/nextcloud.log)
This is quite lengthy. I will add it if needed but it might well be useless here.

#### Browser log
```

Unhandled rejection (<{"readyState":0,"status":0,"statusText...>, no stack trace)
main.js:28:21699
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
2018-03-15T15:36:02.034Z[Content::MessageService] Send to background & wait: GET_GENERAL_CONTENT 
Array []
ConsoleLogger.ts:27:12
2018-03-15T15:36:02.266Z[Content::MessageService] Send to background & wait response 
Array [ {…} ]
ConsoleLogger.ts:27:12
2018-03-15T15:36:02.472Z[Notification::MessageService] Send to background & wait: GET_GENERAL_CONTENT 
Array []
ConsoleLogger.ts:27:12
2018-03-15T15:36:02.474Z[Notification::MessageService] Send to background & wait: GET_MAINTENANCE_CONTENT 
Array []
ConsoleLogger.ts:27:12
2018-03-15T15:36:02.475Z[Notification::MessageService] Send to background & wait: GET_NOTIFICATION_CONTENT 
Array []
ConsoleLogger.ts:27:12
2018-03-15T15:36:02.757Z[Notification::MessageService] Send to background & wait response 
Array [ {…} ]
ConsoleLogger.ts:27:12
2018-03-15T15:36:02.760Z[Notification::MessageService] Send to background & wait response 
Array [ {…} ]
ConsoleLogger.ts:27:12
2018-03-15T15:36:02.798Z[Notification::MessageService] Send to background & wait response 
Array [ {…} ]
ConsoleLogger.ts:27:12
2018-03-15T15:36:02.804Z[Notification::NotificationComponent] no render 
Array []
ConsoleLogger.ts:27:12
2018-03-15T15:36:02.805Z[Notification::CollectAlertComponent] no render 
Array []
ConsoleLogger.ts:27:12

```

**Comment by juliushaertl** [comment]
@christianlupus I cannot reproduce the issue. Can you state which div actually has the hidden class?

**Comment by christianlupus** [comment]
I think an image will tell more than 100 words: ![nextcloud-screenshot](https://user-images.githubusercontent.com/8202922/37595475-3ef592dc-2b79-11e8-8cb6-dea01b1753b9.png)

You can see that `div` that contains the `div#stack-add` has the attached class `hidden`. If I remove the class, the control appear.
I am unsure if I just missed some needed user interaction like clicking on some button to remove the class by javascript or similar.

**Comment by juliushaertl** [comment]
Hm, the hidden rule should actually be overwritten by the .board-header-controls class. Looks a bit weired that the css rule for the hidden class is not from server.css but from Inline:276. Can you check where that is set? The deck styles should be loaded after server styles and therefore overwrite them.

**Comment by christianlupus** [comment]
Dear juliushaertl, I am unfortunately unable to localize the exact source of the `.hidden` definition. In line 276 of the index file the `a` tag in the top menu seems to be located as far as I understand.

Would it be useful if I gave you access to the server to track down the error?

**Comment by juliushaertl** [comment]
@christianlupus That could help, yes. Just send me a test account login via mail, then I can have a look.

**Comment by christianlupus** [comment]
@juliushaertl I just sent you an email with the credentials.

**Comment by christianlupus** [comment]
OK, you sent me an email, that you could not confirm the problem.

I tried with Chrome (normally I use Firefox). Chrome shows the buttons. I still do not get any buttons in FF although I removed my whole cache (and lost the saved keys in the password manager thereby). No success.

**Comment by christianlupus** [comment]
What the h****? I just opened the nextcloud instance and found the buttons there in firefox. I am completely lost here as it seems to work without any further modification. Maybe the upgrade I installed changed anything.
Anyhow I will close this issue now as it seems to be solves. If necessary I will reopen it.
