### ISSUE TITLE
usability: refresh view when click on a card 

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#442]
Tested with deck 0.4.0-alpha1 Nextcloud 13.0.1

### Steps to reproduce
1. Create two cards 
2. Click on a card (card2) and then click on the 3 dots of the card  to open the menu
3. Click on another card (card1) 
![3 deck 2018-03-16 11-06-35](https://user-images.githubusercontent.com/34692335/37515200-59cbeb04-290a-11e8-8f26-784d826c3857.png)

### Expected behaviour
The 3 dots menu from card 2 is not visible 

### Actual behaviour
The 3 dots menu from card 2 is still visible and the items are more transparent

**Comment by juliushaertl** [comment]
This is already fixed on current master.
