### ISSUE TITLE
Checklist feature in Deck cards

### ISSUE THREAD

**Issue by yuisheaven** [nextcloud/deck#4424]
Many huge kanban style boards added a feature to put a Checklist into your kanban Card (example Microsoft Azure Board and Trello).

I would really love to see this feature in Deck as well. Best would be with a preview on the card showing how many tasks of the connected checklist are already done

**Comment by yuisheaven** [comment]
I see that it is possible to add this to the card already by putting - [ ] item in the description. All that needs to be done is to add a button next to the description saying "add checklist point" so that none-technical users can easily take use of the feature

**Comment by reox** [comment]
I guess this is already solved with https://github.com/nextcloud/deck/pull/4399
