### ISSUE TITLE
Feature: Markdown Parser toggle

### ISSUE THREAD

**Issue by daniel-wtd** [nextcloud/deck#444]
### Steps to reproduce
1. Open Deck
2. Open a Board
3. Click a Task
4. Description is parsed as markdown

### Expected behaviour

The parsing of markdown for descriptions should be configurable.
At least a switch to turn it on/off would be awesome. In many cases the description does not consist of too many content and the parser is somewhat "overpowered" for 10 lines of bullet points.

A global switch to turn the parser off would be a good idea and may even reduce the JS Footprint, if wanted.

### Actual behaviour

Markdown can not be turned off, even if not needed.

### Additional information

Deck Version: 0.3.1
NC Version: 13.0.1.1

**Comment by juliushaertl** [comment]
I don't see this happen as it will most likely have only a very small benefit for a quite limited number of users, so having a separate option to toggle is not something that we should introduce.
