### ISSUE TITLE
wysiwig editor in Deck

### ISSUE THREAD

**Issue by thoys1** [nextcloud/deck#4448]
Good morning, 

i like deck and i like markdown. Sadly not all people do like it. 
Is it possible to integrate an (optional) wysiwig editor in Deck? Each user should work with deck and make formatet notes withoud learning Markdown. 

It's not neccesary to make everything on your own. Is it possible to integrade an existing wysiwyg editor in deck?

Thanks
Thoys1

**Comment by marcelklehr** [comment]
Hi @thoys1 

as it happens we've already implemented this :) The next release will use the text app editor.

**Comment by thoys1** [comment]
Thank you for your work!
And thank you for this messege. So i will wait for the next release. 

Greets Thoys1
