### ISSUE TITLE
Blank popup window appear when creating card

### ISSUE THREAD

**Issue by gdudas** [nextcloud/deck#4449]
**Describe the bug**
Blank popup window appear when creating card.

**To Reproduce**
1. Go to 'Apps / Deck'
2. Click on 'Add card'
3. Fill in the fields.
4. After clicking on 'Create card', a blank popup window appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/24443023/218441770-8cea793d-f7e5-4553-9dd4-980d2079ddc3.png)

**Client details:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 110.0.5481.77
 - Device: desktop

<details>
<summary>Server details</summary>

**Operating system**: Ubuntu 20.04

**Web server:** Apache 2.4.41

**Database:** MySQL

**PHP version:** 8.1

**Nextcloud version:** 25.0.3

**Where did you install Nextcloud from:** From tar.gz package.

**Signing status:** No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - announcementcenter: 6.4.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.2
  - calendar_resource_management: 0.3.1
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - encryption: 2.13.0
  - event_update_notification: 2.0.0
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.0
  - guests: 2.3.0
  - integration_whiteboard: 0.0.14
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - polls: 4.1.2
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quicknotes: 0.8.5
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - whiteboard: 0.0.3
  - workflowengine: 2.7.0
Disabled:
  - dashboardcharts: 0.1.3
  - files_antivirus: 4.0.2
  - files_external
  - twofactor_u2f: 6.3.0
  - user_ldap
  - workflow_script: 1.10.0

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "..."
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "...",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "log_type": "file",
        "loglevel": 0,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "app_install_overwrite": [
            "announcementcenter",
            "files_accesscontrol",
            "dashboardcharts",
            "bruteforcesettings",
            "whiteboard",
            "pdfdraw",
            "files_mindmap",
            "integration_whiteboard"
        ],
        "mysql.utf8mb4": true,
        "encryption.legacy_format_support": true,
        "encryption.key_storage_migrated": false,
        "debug": true
    }
}

**Are you using an external user-backend, if yes which one:** No

</details>

<details>
<summary>Logs</summary>

#### Browser log

</details>

**Comment by humanfans** [comment]
Me too.how to solove it

**Comment by Jerome-Herbinet** [comment]
Same here. 
NC 25.0.6
Deck 1.8.3

**Comment by juliushaertl** [comment]
Already fixed with #4561, I'll publish a new release soonish.
