### ISSUE TITLE
Moving cards with finger in android browser doesn't work

### ISSUE THREAD

**Issue by ikke-t** [nextcloud/deck#446]
### Steps to reproduce
1. Open Deck in either Chrome or Firefox in Android
2. Have e.g.  ToDo, Doing, Done stacks, and cards in them
3. Press a card and try moving it from left stack to any other

### Expected behaviour
Card would move and get dropped to correct stack. Or there would be button to drag it from. Or there would be drop down menu to select the stack to move to.

### Actual behaviour
Card doesn't start dragging until some text gets selected, and once you try to move the left bar starts to slide open, and you can't really move the card. I couldn't move the card from mobile One+ 5, 5.5 inch screen.
I tried both in potrait and landscape mode.

### Server configuration
**Operating system**:
Freebsd 11.1 (freenas jail)

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
13.1

**Where did you install Nextcloud from:**
freebsd pkg

### Client configuration
**Browser:**
Firefox, Chrome

**Operating system:**
Android

**Comment by ashgoodman** [comment]
Drag and drop on mobile has always seemed problematic to me in every app I've used, even native apps.

Maybe a better solution is to have a 3 dot menu option that lets you "assign to stack"?

However that wouldn't address the issue of ordering the card withinn a stack

**Comment by ikke-t** [comment]
Perhaps four direction buttons there or smth like that, top/bottom?

**Comment by liquidat** [comment]
I'd like to mention that this works for me. First, the stacks are shown underneath if I keep the normal orientation. If I tilt the mobile, the stacks are shown left to right.

Dragging cards works for me in both ways, though in Firefox there were problems dragging it to the staples on the right side if the display was tilted. Tested on Android 9 with Chrome 68 and Firefox 62

**Comment by juliushaertl** [comment]
Drag and drop is always a bit problematic on mobile, so ideally this should be fixed by #249 which should also support moving the card to a different stack on mobile.

**Comment by ikke-t** [comment]
@juliushaertl, I agree, the other issue covers this.

**Comment by juliushaertl** [comment]
Dragging has improved a lot on master with the vue rewrite so closing this.

**Comment by ikke-t** [comment]
Ok @juliushaertl , looking forward to changes to come to production version, thanks. As with latest it's still impossible to use deck for kanban, at least I can't find a way to move the cards anywhere in mobile.
