### ISSUE TITLE
Deck > Timeline Icon wrong color in dark mode

### ISSUE THREAD

**Issue by foss-** [nextcloud/deck#4463]
Timeline Icon uses wrong color in dark mode.

**Reproduce**

1. open Deck > Card
2. look at sidebar icons

**Expected behavior**

Timeline icon should respect dark mode.

**Screenshots**

<img width="296" alt="1" src="https://user-images.githubusercontent.com/5708172/219882291-d7529a89-64a3-49c0-9637-ae6ae35220f3.png">

**Client details:**
 - Nextcloud 25.0.3
 - Firefox 110.0
 - Deck 1.8.3
- WebUI (not Deck app)

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/deck/commit/2066080e56dad2b7478600685d9a9e6088c492fb
