### ISSUE TITLE
can't copy formatted text from card on Android mobile

### ISSUE THREAD

**Issue by ikke-t** [nextcloud/deck#447]
### Steps to reproduce
1. Have a card with markdown syntax
2. try selecting formatted text for copying

### Expected behaviour
Text would remain formatted and allow selecting.

### Actual behaviour
Text turns into markdown source format, and won't let you copy the formatted text.

### Server configuration
**Operating system**:
FreeBSD

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
13.1

**Where did you install Nextcloud from:**
pkg

### Client configuration
**Browser:** Chrome, Firefox

**Operating system:**
Android

**Comment by juliushaertl** [comment]
Fixed with the new button toggle in the upcoming 1.0
