### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by githubnobr** [nextcloud/deck#4482]
**Describe the bug**
No boards are displayed after login. 
Error message: Request failed with status code 401 

**To Reproduce**
1. register server
2. login
4. error message is displayed
5. no boards are visible

**Expected behavior**
boards displayed

**Client details:**
 - OS: IOS 16.3.1
 - Version 0.15
 - Device: iPhone 11

<details>
<summary>Server details</summary>

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud Hub 3 (25.0.4)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
App token login name does not match
{"reqId":"BKeD9F3VZg16vjRStAiK","level":3,"time":"2023-02-26T08:58:32+00:00","remoteAddr":"84.139.217.229","user":"--","app":"no app in context","method":"GET","url":"/index.php/apps/deck/api/v1.0/boards","message":"App token login name does not match","userAgent":"NextcloudDeck/49 CFNetwork/1404.0.5 Darwin/22.3.0","version":"25.0.4.1","data":{"tokenLoginName":"FirstName LastName","sessionLoginName":"FirstName+LastName"},"id":"63fb21fcf10a1"}

The problem seems to be the encoding of the whitespace character in the username:
 

</details>

**Comment by juliushaertl** [comment]
This looks like an issue with the app you are using, so I'd suggest to open a bug report upstream there. Token handling is done by the server and whitespaces in usernames work well for other clients.
