### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by BiglifeMatt** [nextcloud/deck#4486]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the solution you'd like**
I know that the idea of the Mobile App would be additional to the Nextcloud App, however I'm not sure of the best way to address the need for a mobile app especially for iOS users.  The current two offerings I find either crash while using or do not allow much control over modifying the data.  Are their known iOS options I do not know of or a better way to handle this?

**Comment by HeyWatchOutDude** [comment]
Any update on this? Will the feature "Nextcloud deck" implemented into the current NC iOS/iPadOS app?

**Comment by juliushaertl** [comment]
There are no plans from our side to work on something like that. As stated in https://github.com/nextcloud/deck/issues/1769#issuecomment-628589380 anyone is welcome to start development or contribute to the existing https://github.com/StCyr/deck-react-native and https://meltzow.github.io/deck-ng/
