### ISSUE TITLE
Implement support for the fulltextsearch app

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#449]
Deck should integrate with the fulltextsearch app as in making the content of all cards searchable though it. 

As a starting point the following data should be added to the search index for each card:
- Card title
- Stack name
- Board name
- List of labels

An example implementation can be found at https://github.com/nextcloud/bookmarks_fulltextsearch

I would say we can integrate it directly into the deck repo, so we don't have the dependency of installing another app for admins.

Tasks:
- [ ] Add hooks for changes inside deck (ref: https://github.com/nextcloud/bookmarks/pull/431)
- [ ] Implement a provider using IFullTextSearchProvider https://github.com/nextcloud/bookmarks_fulltextsearch/tree/master/lib/Provider
- [ ] Add search frontent inside the deck app
	- [ ] Search all boards when no board is open
	- [ ] Filter existing cards in board view

**Comment by juliushaertl** [comment]
cc @xh3n1 @daita

**Comment by Aesculapius** [comment]
search can be improved but if that topic is developed I'd also vote to enable search in card descriptions. Stack, board or card names can be found by using simple control-F in your browser but you can't do that within the card descriptions...

**Comment by juliushaertl** [comment]
@Aesculapius General search improvements are tracked in https://github.com/nextcloud/deck/issues/286

**Comment by juliushaertl** [comment]
Already done with https://github.com/nextcloud/deck/pull/885
