### ISSUE TITLE
Workflow for changing Tages by using Board in Kanban style

### ISSUE THREAD

**Issue by blitzie75** [nextcloud/deck#4524]
Hi all.
Is it possible to creat an workflow for changing the Tag by moving the card in a Kanban board.
Eg. a Board with four rows
Backlog
Next 
Work 
Done
If  card moves from work to done change the tag to closed or what else.
(Like in Jira)

**Comment by stefan-niedermann** [comment]
Duplicate of https://github.com/nextcloud/deck/issues/1722
