### ISSUE TITLE
Deck-List not visible - only after resizing

### ISSUE THREAD

**Issue by xstable** [nextcloud/deck#4533]
Deck-Version: 1.8.3
NextCloud: 25.0.3

Following Video show the issue:
[deck_error.webm](https://user-images.githubusercontent.com/1778068/225258581-27f4122f-cb9c-4427-b14f-e9898f7b6eb4.webm)

**Comment by juliushaertl** [comment]
I cannot reproduce this and it looks like an issue with the menu customisation you have in place. I'd suggest to report that to the app in use for that.

**Comment by xstable** [comment]
@juliushaertl 
Ok, but strange that only decks have trouble with it. No other App. 
So do you only suggest that the cause is the custom-menu plugin, or did you deep check it?
