### ISSUE TITLE
1.9.0/NC26: Dashboard widget does not load

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/deck#4555]
![grafik](https://user-images.githubusercontent.com/24530680/227004901-c4fe124b-87bf-466e-962b-9c9198d5ef12.png)

console:
![grafik](https://user-images.githubusercontent.com/24530680/227005620-5556c873-6539-46b0-b792-25e5b0a82d70.png)

**Comment by JordanDIG** [comment]
I have this bug too

**Comment by caloracloud** [comment]
The same bug here !!

**Comment by TheIceMagmaCube** [comment]
I have the same bug. It doesn't seem it prevents the app from functioning properly.
Also, I tried to repair my nextcloud installation with the occ commands.

Here's my error screenshot.
![image](https://user-images.githubusercontent.com/38074756/228451163-928df6ac-5304-459c-9b0b-c59d8adc26cc.png)

**Comment by Chartman123** [comment]
It might be PHP/DB related. On a second instance with MariaDB and PHP 8.2 it works without problems. The malfunctioning instance is official Docker with PHP 8.1 and PSQL.

**Comment by chrstn-hntschl** [comment]
see also #4593 ('Upcoming cards' filter is affected as well)

**Comment by kinimodmeyer** [comment]
I´m unsure if this is related to this error, but since 26 we can not see overdue cards in the "Anstehende Karten" board on the "Heute/Today" column anymore.
