### ISSUE TITLE
NC 25.0.5 - Card: month and year cannot be selected!

### ISSUE THREAD

**Issue by Nick-Git2** [nextcloud/deck#4564]
only days can be selected but no month & no year

![grafik](https://user-images.githubusercontent.com/65270786/228044674-e6560f25-8970-4a9e-a6f2-76caf43dcaca.png)

**Comment by reox** [comment]
Duplicate of #4296 and others...

edit the text, so the modal container gets larger and the full calender is displayed.

**Comment by juliushaertl** [comment]
Fixed in #4643
