### ISSUE TITLE
Database error when running migration 10800Date20220422061816 for app deck There is no column with name 'duedate' on table 'oc_deck_cards'.

### ISSUE THREAD

**Issue by J0kerFace** [nextcloud/deck#4572]
**Describe the bug**
A few years ago i already used Deck in this instance. Know i cant download and activate it. 

**To Reproduce**
1. Go to 'App Deck'
2. Click on 'download and activate'
3. See error

**Expected behavior**
Reactivate the Deck App

**Screenshots**
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/42066984/228529397-4abd50d7-5bfc-4f3e-a06c-0a7ec21b1a31.png">

**Client details:**
 - OS: MacOS
 - Browser Chrome
 - Version 111
 - Device: Macbook Air M2

<details>
<summary>Server details</summary>

**Operating system**: Ubuntu 20.04

**Web server:*Apache*

**Database:*mysql*

**PHP version:*8.1.16*

**Nextcloud version:** 25.0.5

**Where did you install Nextcloud from:** nextclou.de

**Signing status:**

No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - encryption: 2.13.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.2.0
  - issuetemplate: 0.7.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.2
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_webauthn: 1.1.2
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - deck: 0.1.2
  - twofactor_totp: 2.1.2
  - user_ldap

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[settings] Fehler: Exception: Database error when running migration 10800Date20220422061816 for app deck
There is no column with name 'duedate' on table 'oc_deck_cards'. at <<closure>>

0. /var/www/nextcloud/lib/private/Installer.php line 153
   OC\DB\MigrationService->migrate()
1. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 451
   OC\Installer->installApp()
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Settings\Controller\AppSettingsController->enableApps()
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController()
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
5. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
6. /var/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
7. /var/www/nextcloud/index.php line 36
   OC::handleRequest()


```

**Comment by juliushaertl** [comment]
Would be interesting to know which version you had installed before, however I assume that is hard to know after that time ;)

If you don't have any data you want to preserve in the deck tables, you could just drop them and make sure to clear the relevant migrations to start from scratch:

⚠️ Those commands will delete all deck data
```
show tables like 'oc_deck_%';
drop table oc_deck_assigned_labels, oc_deck_attachment, oc_deck_board_acl, oc_deck_boards, oc_deck_cards, oc_deck_labels, oc_deck_stacks;
delete from oc_migrations where app = 'deck';
```

After that enabling deck should work again.

**Comment by J0kerFace** [comment]
Thanks. After dropping the tables and the entry in oc_migrations it works!

**Comment by benibr** [comment]
I had to add another table called `oc_deck_assigned_users` to the drop command.
```
drop table oc_deck_assigned_labels, oc_deck_attachment, oc_deck_board_acl, oc_deck_boards, oc_deck_cards, oc_deck_labels, oc_deck_stacks, oc_deck_assigned_users;
```
