### ISSUE TITLE
Toolbar in rich-text editor is covering dropdowns from user and tags

### ISSUE THREAD

**Issue by mrejas** [nextcloud/deck#4583]
In 1.9.0 the toolbar in the richtext editor is to high in z-level covering the dropdowns from tags and users.

In my case this makes it impossible to remove the tag hidden by the toolbar since there is no scrolling.

![Skärmbild från 2023-04-03 10-43-25](https://user-images.githubusercontent.com/3830271/229459290-ca46ac67-c3e5-4c45-9297-33aa73aa06e7.png)

**Comment by psttf** [comment]
Do you by any chance know how to turn off the rich text editor and revert to direct markdown editing? I can't find such a setting.

**Comment by loffa** [comment]
Direct markdown editing still works for me. I can use ``###`` to create a h3 header for example. The editor converts it to rich text directly tho.

A workaround for the above problem is to filter the tags by writing the name of the tag. And use the delete key to remove all tags in the input field.

**Comment by ros-financial-com** [comment]
The toolbar of the rich-text editor has a z-index of 100, while the multiselect--multiple class appears to have no z-index defined or it's less than 100 in _src/components/card/CardSidebarTabDetails.vue_.
Unfortunately, I'm very inexperienced with vue, So I dare not create a PR to suggest a fix.

**Comment by reox** [comment]
Also the overflow menu of the editor itself renders behind the modal box:
![image](https://user-images.githubusercontent.com/431045/231867754-5625f24f-0a95-4fbd-a8ec-c9c0012eb7cd.png)

**Comment by pschopen** [comment]
I just tried via inspector and a "z-index: 1" seems to solve the issue.

**Comment by pschopen** [comment]
#4617
