### ISSUE TITLE
Indicate presence of attachment/comment

### ISSUE THREAD

**Issue by DuncanLithgow** [nextcloud/deck#4592]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
There is no indication of attachments/comments in the main card UI. For Deck lists that don't often use attachments/comments very much this means unnecessary clicks and the potential for missing the presence of attachments or comments.

**Describe the solution you'd like**
A small dot or number could show if there are attachments or comments on a card.

Here's a quick mockup
![bitmap](https://user-images.githubusercontent.com/3223028/230871955-42e083e6-a708-4337-b106-95180338d163.png)

**Describe alternatives you've considered**
   * The icons could become underlined?

**Additional context**

**Comment by stefan-niedermann** [comment]
Note that this information is already visible *before* opening a card in the overview next to the corresponding icon in the bottom left of each card:

![Screenshot_20230410-113059_Fennec](https://user-images.githubusercontent.com/4741199/230875263-95fa6e5e-4c08-478e-ae34-19b5b8fe55d7.png)

**Comment by DuncanLithgow** [comment]
I'll let you decide if you want to close this or just keep it as a low priority feature request.

**Comment by juliushaertl** [comment]
Thanks for the suggestion. Since those indicators are not common around other areas of Nextcloud I'd close this.
