### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by fkaup** [nextcloud/deck#46]
The behavior of keyboard shortcuts/keys is IMO confusing. Pressing ctrl-s opens the page file dialog, tab jumps to the next input field.  What I would expect is:

When editing a card:
* ctrl-s to save the card

When in detail view:
* tab to indent line
* shift-tab to remove indentation

**Comment by juliushaertl** [comment]
Good point, we need a proper keyboard shortcut support. Although I'm not a big fan of overwriting browser defaults like ctrl-s. maybe we can use strl+enter there?

Some other ideas for that

```
arrow navigation between cards

a    archive card
l    assign labels (jump to label assignment field)
o    open card that is currently hovered by mouse
e   edit card title
n   create a new card
```

**Comment by fkaup** [comment]
That would make navigation even easier. 

The save suggestion came from my habit of always pressing ctrl-s to save my changes after I edit some text, so without thought the save file dialog always opens.

**Comment by BennyLi** [comment]
I was looking for keyboard shortcuts for the deck app and found this issue. I also found nextcloud/server#1444

So maybe you could contribute there too. 

Just to mention it: I'm very familiar with Vim keybindings. Google uses these in there web apps too. I would prefer these type of keybindings.

**Comment by reox** [comment]
> Good point, we need a proper keyboard shortcut support. Although I'm not a big fan of overwriting browser defaults like ctrl-s. maybe we can use strl+enter there?

In my opinion, catching Ctrl+s improves the usability. For example, if I see that a card is not yet saved, I automatically press Ctrl+s, which pop ups the browser's "save page as" dialog.
I really have to contain myself not to press Ctrl+s all the time, because it is already so automated when working with other tools :grin:

**Comment by bfloog** [comment]
Please add taskell keybindings and make it work at the speed of taskell and we'll be in good shape.

I really hate using the mouse with your product.

https://github.com/smallhadroncollider/taskell

**Comment by oneWaveAdrian** [comment]
I feel Deck is very close to Trello in its whole user interface. The trello team has spent a lot of time already coming up with good shortcuts over the years. Being a heavy user myself I can recommend their pattern. https://trello.com/shortcuts

**Comment by l-mb** [comment]
The ability to quickly toggle whether a label is assigned to a card without lots of mouse interaction would be very very useful.

**Comment by ilovefreesw** [comment]
Is there any shortcut for activating search tool?

**Comment by stefan-niedermann** [comment]
https://help.nextcloud.com/t/where-is-the-list-of-keyboard-shortcuts/189926/5

**Comment by ilovefreesw** [comment]
Ow so search not supported :(
