### ISSUE TITLE
0.2/NC25: Card Details - Deck doesn't show Month or Year

### ISSUE THREAD

**Issue by patrix487** [nextcloud/deck#4602]
![Githubdeckissuesdoesntshowmonthandyear](https://user-images.githubusercontent.com/56065627/232206258-e33fdc9d-a423-43d6-96d6-e8fe1ab8c689.JPG)

This happens when i open the card details of a card other than the 2nd card in a list.

![Githubdeckissue1](https://user-images.githubusercontent.com/56065627/232206295-eb613240-249d-4e24-a3bb-9b9671a646f2.JPG)

As you can see deck displays month and year when i select the second item.

It doesn't happen when using the mobile app only on desktop. It doesn't work at all on my laptop. 
I tested different browser and also cleared my browsercache. 
Therefore i guess it is an app issue.

Can anybody help me who had the same issue or does know of the problem?

**Comment by juliushaertl** [comment]
Fixed with #4643
