### ISSUE TITLE
New markdown editor helper hiding label in dropdown menu and making it unaccessible

### ISSUE THREAD

**Issue by yuisheaven** [nextcloud/deck#4621]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**
1. Create a new board if you don't already have one
2. Create a few more labels for the board, so there are at least 5-6 labels available
3. Create a new list and new card
4. See error by trying to select the labels. You will notice that at least one is hidden by the new markdown editor helper and therefore can't be selected and also can't be cleared.

**Expected behavior**

I would have expected that the labels are visible and hide the markdown editor as long as the labels dropdown is selected/in use.

**Screenshots**

As you can see in the screenshots, the card has the "Prio" label on it but I cannot clear the label because it is hidden by the new markdown editor.

![Nc-Talk-Bug-Card_Overview](https://user-images.githubusercontent.com/91854357/234376111-9d02dee0-6119-43ed-ab13-5fb5aa48eacd.png)
![Nc-Talk-Bug-Label_dropdown](https://user-images.githubusercontent.com/91854357/234376138-5950e604-1965-4f4e-bb02-af1398035b04.png)
![Nc-Talk-Bug-Label_dropdown-small_card_view](https://user-images.githubusercontent.com/91854357/234376157-b4845874-3ed5-4089-8c80-6ff6b8742ddb.png)

**Client details:**
 - Desktop (Windows 11)
 - Browser Google Chrome
 - Version Nextcloud 26.0.0, Deck version 1.9.0 (current latest)

<details>
<summary>Server details</summary>

**Operating system**: 
Linux Ubuntu 22 (Operating System: Linux 5.15.0-70-generic x86_64)

**Web server:**
Apache

**Database:**
Type: mysql, Version: 10.5.19

**PHP version:**
Version: 8.1.17

**Nextcloud version:** (see Nextcloud admin page)
26.0.0

**Where did you install Nextcloud from:**
Docker image

**Signing status:**
?

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 4b0a99fbab7bc4824176101150bd0ab2b553e128a390e0f872580db4541462b31aad13099fd41533b6695d1b185dabca26a45e9a78227cfb9479eafa439c7bff
                            [current] => a8e818876a7eff2a2137601eafc6c7d96b99cbf27d94ff9bb59eb237bdab92076ecc2828242bb37551c9c8b6772c0718887bd49cee5b49b3be48d3b9ecaa558f
                        )

                )

        )

)
```
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - announcementcenter: 6.5.1
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.3
  - cfg_share_links: 3.0.2
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - collectives: 2.4.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - deck: 1.9.0
  - drawio: 2.1.1
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_accesscontrol: 1.16.0
  - files_antivirus: 5.0.0
  - files_linkeditor: 1.1.14
  - files_markdown: 2.4.0
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_texteditor: 2.15.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - forms: 3.2.0
  - groupfolders: 14.0.1
  - guests: 2.4.0
  - integration_github: 2.0.2
  - integration_gitlab: 1.0.15
  - integration_openai: 1.0.4
  - integration_youtube: 0.1.3
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.1.1
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - onlyoffice: 7.8.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - polls: 5.0.3
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - ransomware_protection: 1.14.0
  - recognize: 3.7.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - spreed: 16.0.3
  - support: 1.9.0
  - survey_client: 1.14.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - tables: 0.4.0
  - tasks: 0.14.5
  - text: 3.7.2
  - text_templates: 1.0.1
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_reminder: 1.0.0
  - twofactor_totp: 8.0.0-alpha.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - cms_pico: 1.0.21 (installed 1.0.21)
  - encryption: 2.14.0
  - files_3dmodelviewer: 0.0.8 (installed 0.0.8)
  - files_external: 1.18.0
  - user_ldap: 1.16.0
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
- No.
</details>

<details>
<summary>Logs</summary>
#### Browser log
```
Console log is empty. 
```

</details>

**Comment by JordanDIG** [comment]
I have also this bug.

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/deck/pull/4617
