### ISSUE TITLE
Add Toolbar for markdowns in description of cards

### ISSUE THREAD

**Issue by Orange-Raven** [nextcloud/deck#4647]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Markdowns are comlicated to use for normal users and its hard to write longer texts with them. Its a reason for normal users not to use the Deck Addon, because it is hard to write clear text in the description.

**Describe the solution you'd like**
It would be best to place a small toolbar above the description area in which the most important markdowns are located and can be inserted in the style of a WYSIWSG editor. Ideally, the preview should be visible directly, and not the markdown first.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by juliushaertl** [comment]
This is available since Nextcloud 26 with the integration of the text editor.
