### ISSUE TITLE
expired cards in the dashboard

### ISSUE THREAD

**Issue by Weltenstoeberer** [nextcloud/deck#4659]
If a deck card has been given a date, it will still show up as a pending card in the dashboard after it has expired. Unfortunately, even if it has been given a "done" label. Is this the way it should be? It would be nice if expired dates automatically disappeared from the dashboard.

**Comment by stefan-niedermann** [comment]
There currently is no `done` state, the label is just a label like each other with no special magical or technical meaning.

Closing as duplicate of https://github.com/nextcloud/deck/issues/534
