### ISSUE TITLE
Board doesn't scroll to right side, when moving a card to right side

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#466]
**Describe the bug**
Board doesn't scroll to right side, when moving a card to right side

**To Reproduce**
1.  Create 6 or more stacks (to reproduce there must be more stacks than visible in one screen)
2.  Create a card on very right stack
3. Move the card from right to the most left stack. Then the viewport scrolls to the left.
4. Try to move the card from the most left stack to the most right stack
Error: When the card reaches the right side of the screen the viewport doesn't scroll to the right, so that you can't drop the card on the most right stack.

**Expected behavior**
Same scrolling (to right) in step 4 like scrolling (to left) in step 3.

**Workaround**
Move the card with two steps:
Move the card to the most right visible stack. Use the scrollbar of the browser till the most right stack is visible. Then move the card to the right.

**Environment**
Tested with deck 0.3.1 Nextcloud 13.0.2, Firefox 60.0.1

**Comment by juliushaertl** [comment]
It seems that scrolling only works if the mouse cursor is out of the window. Thanks for reporting.

**Comment by juliushaertl** [comment]
Fixed with the new drag-and-drop library on master.
