### ISSUE TITLE
Calendar does not show in due date after upgrade to 1.9.1

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#4663]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

I just upgraded to 1.9.1 and the calender does not show anymore when clicking in the due date.

**To Reproduce**
1. click in the due date
2. no calendar pops up

**Expected behavior**

The calender should show when clicking in the due date

**Screenshots**

**Client details:**
 - OS: W11
 - Browser: firefox / chrome
 - Version 112
 - Device: desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by reox** [comment]
> Will check later as I'm currently on mobile, but can you tell if there is a different behavior between using the sidebar vs modal for the card details view?

yes: In the sidebar it works fine. It is just the modal!

**Comment by caloracloud** [comment]
The same here.

**Comment by jjasoncool** [comment]
same issue

**Comment by juliushaertl** [comment]
Pull request is in https://github.com/nextcloud/deck/pull/4664 will push a new release out later today

**Comment by Peachy74** [comment]
The same here.

**Comment by reox** [comment]
1.9.2 indeed solves the problem, but for who knows why reasons, I had to reload the page with cache invalidation in some instances - even it worked in the same browser before. Thus, if it still does not show up, press Ctrl+Shift+R

**Comment by juliushaertl** [comment]
> 1.9.2 indeed solves the problem, but for who knows why reasons, I had to reload the page with cache invalidation in some instances - even it worked in the same browser before. Thus, if it still does not show up, press Ctrl+Shift+R

Are you running your instance in debug mode by any chance? That could explain why the browser cache is not automaticaly invalidated.

**Comment by reox** [comment]
> Are you running your instance in debug mode by any chance? That could explain why the browser cache is not automaticaly invalidated.

You mean https://docs.nextcloud.com/server/latest/developer_manual/getting_started/debugging.html#debug-mode ?
no, not that I'm aware of... I did `occ config:list` and do not see any `debug` in there.

**Comment by juliushaertl** [comment]
Yes, that was what I was referring to. Then I'd not have a good idea why this might have been required.

**Comment by reox** [comment]
> Yes, that was what I was referring to. Then I'd not have a good idea why this might have been required.

Maybe it has to do something with pinned tabs in firefox... Maybe they behave differently. I have no idea either.
But reloading the paper solved the issue, so 🤷

**Comment by solracsf** [comment]
Any reason why patch has not been published to v24?

**Comment by magikmw** [comment]
> Any reason why patch has not been published to v24?

Nextcloud 24 is EOL since May 3rd.

**Comment by solracsf** [comment]
v1.7.4 has been published at May 10 (so, after May 3rd...)
Patch is at https://github.com/nextcloud/deck/pull/4666 but not merged.
