### ISSUE TITLE
Editor Toolbar wrap at different positions / unused space around editor

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#4686]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

The new text editor is very nice. However, I noticed that the toolbar sometimes wraps at different positions in the modal dialog.
In the sidebar, it is not visible, because the width of the editor is much smaller.

For example, sometimes almost all icons are visible, while at some instances, only three to four icons show up.
I'm not sure if this is an issue of deck or if it relates to github.com/nextcloud/text

There is also a lot of unused space for the editor (see screenshots)

**Describe the solution you'd like**
The whole toolbar should be visible, if space allows it.

**Describe alternatives you've considered**
-

**Additional context**

Only some icons show up:
![grafik](https://github.com/nextcloud/deck/assets/431045/31912b69-3013-4d3f-b3d4-d343647da93a)

Even less icons show up:
![grafik](https://github.com/nextcloud/deck/assets/431045/9b6bb6bf-a49f-42d7-ba27-448d3d890c5b)

Most of the icons show up, but there is a lot of unused space on both sides (red arrows):
![grafik](https://github.com/nextcloud/deck/assets/431045/05a19c97-65cd-4f5b-ad66-1f04ea12bc15)

**Comment by reox** [comment]
It looks like part of this issue were already resolved in NC 28 / Deck 1.12.
However, I think there is still too much unused space around the editor. Is that on purpose?

**Comment by juliushaertl** [comment]
Yes, the maximum width is determined by the editor itself to [accommodate a recommended reading width](https://github.com/nextcloud/text/issues/125#issuecomment-506819278). 

Will close this here as there is an upstream discussion in https://github.com/nextcloud/text/issues/4024

**Comment by reox** [comment]
Ah okay, did not know that this is on purpose, but it makes sense! Thanks for the information :)
