### ISSUE TITLE
[stable24] Due date setting not working

### ISSUE THREAD

**Issue by zentaurr** [nextcloud/deck#4687]
Since V1.7.4 has been released for Nextcloud Enterprise, it's no longer possible for me to set a deadline in browser, neither by selecting a date from the drop-down-menu nor by manually typing a date into the according field. Due to the fact, that changes can still be made via the Deck-App for Android, some kind of bug in the front-end seems to be very likely.

**Comment by juliushaertl** [comment]
We are aware of this issue and a fix has been merged for Nextcloud 25 and 26 but the same fix didn't fully apply to 24 yet, so investigations are still ongoing in that regard. If you are an enterprise customer I'd kindly ask you to open a support request through your usual channel as this will help to prioritize the issue.

**Comment by zentaurr** [comment]
Thank you for your info! I already reported the issue to IONOS, since I've subscribed for their managed-nextcloud. Therefore a rollback to a functioning version is not an option. Unfortunately I haven't found anything related to the subscription-key needed to report an issue regarding a support request. Am I missing something?

**Comment by Hugoto-beep** [comment]
> Since V1.7.4 has been released for Nextcloud Enterprise, it's no longer possible for me to set a deadline in browser, neither by selecting a date from the drop-down-menu nor by manually typing a date into the according field. Due to the fact, that changes can still be made via the Deck-App for Android, some kind of bug in the front-end seems to be very likely.

Any schedule to solve this big issue ?

**Comment by Martin-bl** [comment]
In the corner left go to settings, and change "use the biggercard view" and  it should work (it is ok for me)
![image](https://github.com/nextcloud/deck/assets/75613706/3862b3e2-f25f-4d8e-a515-666ff407d59d)

**Comment by Netfreak25** [comment]
> In the corner left go to settings, and change "use the biggercard view" and it should work (it is ok for me) ![image](https://user-images.githubusercontent.com/75613706/243281059-3862b3e2-f25f-4d8e-a515-666ff407d59d.png)

Unchecking this option worked for me as workaround!

Nextcloud: 24.0.12
Deck: 1.7.4

**Comment by juliushaertl** [comment]
Since the version reported is quite old, please try if this is still an issue on the latest and don't hesitate to reopen if it is still an issue.
