### ISSUE TITLE
Remove boards when a user gets deleted

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#469]
Once a user is deleted from the Nextcloud instance all his personal boards should be removed. Boards that are shared should ideally be transfered to another user who has managing permissions on the board.

**Comment by arnowelzel** [comment]
BTW: This can also lead to the infamous "Call to a member function getUID() on null" errors in the cron log - see https://github.com/nextcloud/server/issues/9953.

Also see the documentation about event hooks in Nextcloud:
https://docs.nextcloud.com/server/13/developer_manual/app/hooks.html

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/deck/pull/1976
