### ISSUE TITLE
Card no longer assigned to a user remains in his deck

### ISSUE THREAD

**Issue by Foxdynamics** [nextcloud/deck#4726]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Hi everyone,
If I assign a card with a due date to another user in the Nextcloud Deck app (tested with NC V25.0.5 and 25.0.6) and then remove the assignment to this user, the card is still displayed to him. Both in the overview of upcoming cards, as well as in the respective board.

1. Login as user A
2. Share a (new or existing) board with User B.
3. Create a card within the board as user A, set a due date and then assign the card to user B.
4. The card is now also visible in the deck of user B
5. Remove the assignment to user B again
6. The card remains in the deck app of user B

My understanding is that the card should be removed from User B's deck as soon as he is no longer assigned to the card.

**Comment by stefan-niedermann** [comment]
> users can only be granted access to all cards on a board equally, right?

Right

> Is there a known way to make cards visible only to a subset of users within a specific board?

No, unfortunately not.

Please search GitHub for existing issues, I am pretty sure there is already at least one issue requesting more fine granular permissions.
