### ISSUE TITLE
Disable URL preview

### ISSUE THREAD

**Issue by eRaid6** [nextcloud/deck#4728]
**Is your feature request related to a problem? Please describe.**
Nextcloud Deck tries to preview URLs in the Description of the card which is not always desired.  For example previewing URLs can disclose IP information unintentionally and some links might be intentionally unreachable.

**Describe the solution you'd like**
It would be great if there was a per deck, card or global option to disable URL previews.

**Describe alternatives you've considered**
None

**Additional context**
Looks like there is a request in Notes for this same feature https://github.com/nextcloud/notes/issues/1033

**Comment by stefan-niedermann** [comment]
A possible alternative might be proxying the requests through the Nextcloud instance for privacy reasons?

**Comment by eRaid6** [comment]
Perhaps, that might help limit disclosing IP information unintentionally (the Nextcloud server IP would still be disclosed to the link target) but links that are intentionally unreachable would still try to render and eventually time out.  When I say links that are intentionally unreachable think about the scenario where the user is using Nextcloud Deck to track some work they are doing for their employer but the Nextcloud instance and their end device are not connected to the employer VPN so any link they add that requires the VPN will currently always time out.

**Comment by kartoffelheinz** [comment]
This "feature" is so unbelievably annoying and a huge privacy and security risk. 
There must be an option to disable it completely for any given whole instance ASAP.

**Comment by andreas1107** [comment]
I agree - I would love to see an option where this can be disabled.

**Comment by resoli** [comment]
I agree with @kartoffelheinz ; moreover, it should be absolutely opt-in.

**Comment by Rik44444** [comment]
+1 this is bizarrely annoying and I don't understand how people have not fought harder to be able to make this optional in the Settings (both at user and instance level)!

**Comment by andreas1107** [comment]
One workaround I have found is to paste URLs within a code block 
```URL here```

It makes the URL easy to copy (there's a copy button on code blocks) and it stops the preview behaviour.

**Comment by Rik44444** [comment]
> One workaround I have found is to paste URLs within a code block `URL here`
> 
> It makes the URL easy to copy (there's a copy button on code blocks) and it stops the preview behaviour.

Thanks for this!!

**Comment by Rik44444** [comment]
> One workaround I have found is to paste URLs within a code block `URL here`
> 
> It makes the URL easy to copy (there's a copy button on code blocks) and it stops the preview behaviour.

Workaround 2: put any character directly before or after the URL. This will also stop the preview behaviour.

**Comment by juliushaertl** [comment]
Starting with Nextcloud 29 you can toggle the link preview on after inserting a link:

<img width="596" alt="Screenshot 2024-08-05 at 09 13 26" src="https://github.com/user-attachments/assets/7e1a0be3-f310-4ece-8bce-6ad3cebd39ff">


To avoid doing the remote request you can disable the opengraph provider in config php `'reference_opengraph' => false,`

**Comment by eRaid6** [comment]
Thank you @juliushaertl I will upgrade and test!

**Comment by CodeAlDente** [comment]
I just ran into the same issue. The link preview isn’t necessary, especially in the title. A setting should be available to disable this, eliminating the need for any workarounds.

```
Nextcloud Version: 32.0.6
Deck Version: 1.16.3
```
