### ISSUE TITLE
Deck API attachment upload from NODEJS

### ISSUE THREAD

**Issue by toniojst** [nextcloud/deck#4749]
Hi,

i trying to parsing email and get all attachment. I succesfuly create first part so i get all attachment and save it to local disk, Now i need to upload this file to Deck over API. I trying with next code but i get some error back... Does someone know what is this error?

```
.
.
.
mail.attachments.forEach(function (arrayItem) {
	
fs.writeFile(arrayItem.filename, arrayItem.content, (err) => { if (err) throw err; });
console.log('File Buffer:')
console.log(arrayItem.content) // content of file <Buffer 25 50 44 46....
console.log('-----------------------------')

const url = 'https://site.com/apps/deck/api/v1.1/boards/4/stacks/11/cards/27/attachments';
const options = {
    method: 'POST',
	 headers : {
		  'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': 'Basic ' + Buffer.from('username:password').toString('base64'),
    }
};
const data = "type=file&file=" + arrayItem.content; // content of file <Buffer 25 50 44 46....

let result = '';
const req = https.request(url, options, (res) => {
    console.log(res.statusCode);

    res.setEncoding('utf8');
    res.on('data', (chunk) => {
        result += chunk;
    });

    res.on('end', () => {
        console.log(result);
    });
});

req.on('error', (e) => {
    console.error(e);
});

req.write(data);
req.end();  
.
.
.
```

As you can see i gett error 500.
![image](https://github.com/nextcloud/deck/assets/8342958/c07b9a73-9a3d-4f70-9295-420aada08f0d)

with fs.WriteFile i succesfuly create this physical file to disk from Buffer
![image](https://github.com/nextcloud/deck/assets/8342958/f8b25512-0b16-4c1e-afd0-f8783b847876)

So why i can upload this to Deck over API?

**Comment by juliushaertl** [comment]
Please read the error message, it looks like a configuration issue. https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html should give some pointers
