### ISSUE TITLE
Notifications on card assignment

### ISSUE THREAD

**Issue by maherbm** [nextcloud/deck#475]
I want to use Deck in a large research project and unfortunately the following important features are missing to make that easy:

* Notifications when assigning a card: In a big project with many boards and cards it is important to notify the user when a card is assigned to her/him.

* Cards assigned to me: In a big project with many boards and cards it would be nice to quickly find (Active) cards assigned to self, either in a list or as a number behind each board name in the boards list page.

Thank you and best regards,

Maher

**Comment by davedauria** [comment]
I was just coming here to request this feature. It would make the system so much more useful with what I am using it for. Also reminders would be another great thing to have. I love the app and appreciate all the hard work you do for free. I'm using it as part of a small development team at a transportation company and it's great at helping me stay organizized...

**Comment by naguibihelek** [comment]
Likewise. I thought this would be a pretty important function.

**Comment by Goldenflamer** [comment]
+1

**Comment by juliushaertl** [comment]
Please use the [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) feature instead of commenting that also need a specific feature. That way we can see your support without notifying all users subscribed to a given issue.

Note this has already been implemented with https://github.com/nextcloud/deck/commit/769053b76dc0f52bc68073466920a31320ab1532

**Comment by ddixan** [comment]
HI! my nextcloud server (16.0.1) sent all notification successfully but for Deck app is not working. I have all activities enabled for send email notification but for deck, no email notification is arriving. It seems to be some bug between deck and the notification system via email

**Comment by juliushaertl** [comment]
> The single most important notification would be to inform a user about a new assigned card. It would be very nice to have a separate notification option for that.

Card assignment notifications are exposed thought he notifications app.

**Comment by klemens-u** [comment]
Hi Julius, 
> Card assignment notifications are exposed thought he notifications app.
What do you mean by that exactly?

To be more precise: I want to have an option to receive notifications per email only when someone assigns a card to me. In no other cases.

**Comment by juliushaertl** [comment]
@klemens-u In that case this is related to activity so we need to create a separate type of deck activities specific for card assignments. Mind to open a new issue for that?

**Comment by klemens-u** [comment]
Done: #1238
