### ISSUE TITLE
Cannot share Decks with Groups which I am not a part

### ISSUE THREAD

**Issue by handkerchief333** [nextcloud/deck#4776]
I don't know if this is a bug or configuration issue.

I can't share the boards with another group which I'm not part of it.
I can share a board with my own group only. Is this a bug or a feature? :)

Nextcloud 26.0.2
Deck: 1.9.2

#644

**Comment by handkerchief333** [comment]
Ok mabye this is correct. Because Users from different Groups should not see other Groups oder Member on the platform. So it's a good thing that not all groups shows up. I had to add my User to the Group temporary so I was able to add the Group to the Deck. After that, I remove my User from the Group. And the Group has still permission for the Deck. So it's alright.

**Comment by juliushaertl** [comment]
Yes, it is expected behavior that youcc be an only share to your own groups. We use the same endpoint as files for sharing.
