### ISSUE TITLE
Changelog is not up-to-date with releases

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/deck#4799]
The [`CHANGELOG.md`](https://github.com/nextcloud/deck/blob/main/CHANGELOG.md) does not contain all [releases](https://github.com/nextcloud/deck/releases) and is not up-to-date.

**Comment by joshtrichards** [comment]
The CHANGELOG is up-to-date, but does require changing to the appropriate branch (stableXX or the via a specific version tag), since there are multiple stable versions maintained simultaneously for different Server versions.
