### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by SergeyMosin** [nextcloud/deck#4807]
**Describe the bug**
Missing Icon for `Details`, `Comments` and `Timeline` tabs
NC25, Deck 1.8.5 , tested in Firefox and Chrome

**To Reproduce**
Open a Deck card

**Expected behavior**
All icons should be visible

**Screenshots**

![image](https://github.com/nextcloud/deck/assets/10747559/693e1c92-c9a3-4c9d-9df8-0f47ec919c23)

**Client details:**
NC25, Deck 1.8.5 , tested in Firefox and Chrome

<details>
<summary>Server details</summary>

**Operating system**:
Tested on AlmaLinux and Ubuntu

**Web server:**
Tested on Nginx and Apache

**Database:**
MySQL

**PHP version:**
8

**Nextcloud version:** (see Nextcloud admin page)
25.0.6

#### Logs
```
Nothing related to the Icons in NC or Console logs
```

</details>

**Comment by sebphi** [comment]
I can confirm this issue. I cannot see the icon to edit the card's description. However, when hovering over the expected position (to the right of 'Beschreibung' in the attached screenshot), i can see a grey circle and can click to edit.

![Bildschirmfoto vom 2023-06-13 10-14-39](https://github.com/nextcloud/deck/assets/34366521/e8b07ec7-debf-4efe-9671-1724b1a1c75a)

**Comment by sebphi** [comment]
It could be fixed by running `occ config:app:set theming cachebuster --value=$(date +%s)` . 

According to https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#maintenance-commands, this could also help:

```
Run the `maintenance:theme:update command` if the icons of your custom theme are not updated correctly. This updates the mimetypelist.js and cleares the image cache.
```

Cheers,

**Comment by SergeyMosin** [comment]
The `occ` commands do NOT help in my case. I think it has something to do with NC switching to `material design icons` https://github.com/nextcloud/server/issues/32060 

Version 1.8.5 has not been updated https://github.com/nextcloud/deck/blob/3c3837c8d3260c9a776c9422ccb03b849bc0f79d/src/components/card/CardSidebar.vue#L51-L80 

There is a commit for later versions https://github.com/nextcloud/deck/commit/2066080e56dad2b7478600685d9a9e6088c492fb that has not been back-ported to 1.8.5 as the result all NC v25 installations are effected  :cry: :angry: :lady_beetle: 

![image](https://github.com/nextcloud/deck/assets/10747559/752e1c3e-53b5-41e3-af21-73db15bf5fdf)

**Comment by tuetenk0pp** [comment]
Does that mean an update to`NC 26 would solve the issue?

**Comment by juliushaertl** [comment]
Yes, this is solved in the most recent releases.
