### ISSUE TITLE
formatting in the comment field causes the 1000 character limit. 

### ISSUE THREAD

**Issue by dennisTGC** [nextcloud/deck#4834]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**  
I think formatting is counting (but not showing) with the 1000 characters limit in the comments. This is very confusing, especially for end-users. 

**To Reproduce**  
1. Go to a card, comment and fill in:
test
---
het doel is van de Circle:
Circles allows your users to create their own groups of users/colleagues/friends. Those groups of users (or 'circles') can then be used by any other app for sharing purpose (files, social feed, status update, messaging, …).
Different type of circles can be created:
- A personal circle is a list of users known only to the owner. This is the right option if you want to do recurrent sharing with the same group of people.
- A public circle is an open group visible to anyone willing to join. Your circle will be visible to everyone and everyone will be able to join the circle.
- A closed circle requires invitation or confirmation by an admin. This is the right circle if you are looking for privacy when sharing your files or ideas.
- An Secret circle is an open group that can be protected by a password. Users won't be able to find this Circle using Nextcloud search engine

2. Select the text and use Italian formatting, with CTRL-I
3. you have just now hit the 1000 characters limit with 913 visible characters.

I think this has been reported before, like [here](https://github.com/nextcloud/deck/issues/1059#issuecomment-890760475), but I think it's a seperate issue. 

**Expected behavior**
Show what is happening and how to fix the 1000 characters issue. 

**Screenshots**

**Client details:**
 - OS: Ubuntu
 - Browser: Brave
 - Version: v1.52.133 (Jun 14, 2023) based on Chromium to 114.0.5735.133.
 - Device: desktop

<details>
<summary>Server details</summary>

**Operating system**: Debian

**Web server:** 
nginx

**Database:**   
mariadb 10.5.15

**PHP version:**   
8.1.17

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**   
from enterprise source.

**List of activated apps:**
Enabled:
  - activity: 2.17.0
  - calendar: 4.3.4
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.5
  - drawio: 2.1.1
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_mindmap: 0.0.28
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - forms: 3.3.0
  - group_everyone: 0.1.12
  - groupfolders: 13.1.3
  - impersonate: 1.12.1
  - login_notes: 1.2.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.6
  - maps: 1.0.2
  - music: 1.8.3
  - notes: 4.7.2
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.6
  - systemtags: 1.15.0
  - tasks: 0.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - user_saml: 5.2.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0

**Are you using an external user-backend, if yes which one:** 
no

**Comment by gbytedev** [comment]
I feel like the limit itself should not be a thing or should be customizable when comments are used e.g. in Deck. There comments are used to work on issues and could include code or text suggestions. See https://github.com/nextcloud/server/issues/33619 for the related issue.

**Comment by juliushaertl** [comment]
No this is up to the server. Let me close this here as there is a server issue
