### ISSUE TITLE
Floating keyboard prevents editing in app (iPad)

### ISSUE THREAD

**Issue by hatlawrence** [nextcloud/deck#4857]
In the iPad app, when using the floating keyboard, there is a bug. Screen fills with white space. Only happens after clicking “edit” and trying to edit a field.

Switched to docked keyboard at bottom of screen and it went away.

**Comment by juliushaertl** [comment]
This repo is only for tracking issues of the deck app itself not the ipad app. Please report this to the maintainer of the actual iOS app.
