### ISSUE TITLE
Prepare for `@nextcloud/vue` v8

### ISSUE THREAD

**Issue by susnux** [nextcloud/deck#4859]
The next `@nextcloud/vue` version, version 8, has some breaking changes as some deprecated components and properties were removed. For **deck** at least this places need to be adjusted:

* Migrate from `NcMultiselect` to `NcSelect`
  * https://github.com/nextcloud/deck/blob/deaed6324d144a78e89f47804e5889dda1e421cd/src/CardSelector.vue#L27
  * https://github.com/nextcloud/deck/blob/deaed6324d144a78e89f47804e5889dda1e421cd/src/components/cards/CardMenu.vue#L63
  * https://github.com/nextcloud/deck/blob/deaed6324d144a78e89f47804e5889dda1e421cd/src/components/card/CardSidebarTabDetails.vue#L30
  * https://github.com/nextcloud/deck/blob/deaed6324d144a78e89f47804e5889dda1e421cd/src/components/navigation/AppNavigation.vue#L95
  * https://github.com/nextcloud/deck/blob/deaed6324d144a78e89f47804e5889dda1e421cd/src/components/board/SharingTabSidebar.vue#L3
  * https://github.com/nextcloud/deck/blob/deaed6324d144a78e89f47804e5889dda1e421cd/src/CardCreateDialog.vue#L28
* `NcPopoverMenu` was removed and needs to be replaced https://github.com/nextcloud/nextcloud-vue/pull/4081
  * https://github.com/nextcloud/deck/blob/4ddbf472c359533e071ac51accc2cab6881504e5/src/components/cards/AvatarList.vue#L54
* NcAppNavigationCounter was removed and needs to be replaced https://github.com/nextcloud/nextcloud-vue/pull/4096 
  * https://github.com/nextcloud/deck/blob/4ddbf472c359533e071ac51accc2cab6881504e5/src/components/navigation/AppNavigationBoard.vue#L32

For more information see this tracker issue https://github.com/nextcloud/nextcloud-vue/issues/4223

**Comment by juliushaertl** [comment]
Done with https://github.com/nextcloud/deck/pull/5621
