### ISSUE TITLE
I updated the deck version 1.7.4, but we cannot delete anymore, and when we click on close (cross) it doesn't work, if we want to upload or download, it doesn't work and if we want to erase a joined doc, it's the same

### ISSUE THREAD

**Issue by oovoom** [nextcloud/deck#4901]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by oovoom** [comment]
Go to deck, open a card, upload a document, then,  click on ... and try to download, or erase : it doesn't work
Go to deck, open a card, open a document, then,  click on X you cannot go out

Safari, chrome, Internet explorer

**Comment by juliushaertl** [comment]
Please provide a fully filled out issue template, especially the log sections, otherwise it is impossible to know what's going on.

**Comment by joshtrichards** [comment]
Closing due to insufficient info after 10 months. Feel free to return it still experiencing and we can revisit this issue.
