### ISSUE TITLE
PUBLIC SHARE

### ISSUE THREAD

**Issue by punkyard** [nextcloud/deck#4942]
A public view of a deck could be very useful to us.
We are non-profit and work with volunteers that won't create an account on NC.
But it would be very handy if could share a public view of a deck with them of the status of our projects.

Thanks ✌️

**Comment by juliushaertl** [comment]
Duplicate of #14 

Please use the search before opening new issues to see if there are already existing ones.

**Comment by punkyard** [comment]
ok @juliushaertl 
sorry then
As it's a 2017 thread, I thought I'd update the subject
Thanks for your response!

**Comment by cyberstrawberry101** [comment]
I also would like to see this functionality if anyone else is to task to get it implemented.  Last I recall, there were underlying structural reasons in the sharing system that made sharing decks publicly difficult to implement.
