### ISSUE TITLE
Feature request : Put dashboard in group

### ISSUE THREAD

**Issue by Julien-Faure** [nextcloud/deck#4944]
Hello all,

I use Nextcloud Deck every day and I find that it's a great application.

Since I use it, my Dashboard list is growing.

It would be interesting to be able to put dashboard in groups.

For example, put all my finance Dashboard in a group named "finance".

**Comment by stefan-niedermann** [comment]
Please use the 🔍  **search function** before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/2006
