### ISSUE TITLE
Card sharing breaks all shares to that card, because the (board + card ID) is used instead of (unique card ID) in the URL

### ISSUE THREAD

**Issue by gwnmikedus** [nextcloud/deck#4946]
**Describe the bug**
When moving a card from one board to another, all previously shared links in Talk / mail or elsewhere become broken. The sharing doesn't seem to be using the unique card ID. nextcloud.local/apps/deck/#/board/6/card/10

Previously mentioned here: #2906 

**To Reproduce**
1. Share a card using the smart-picker in Talk or e-mail (possibly all sharing links, but untested). 
2. Have at least 2 boards and after the sharing is complete, move a card from one to another using the card options. 
3. Try to open the link that was previously shared.
4. You will see a grey overlayed board (if having access to it) of which the card originated from when sharing. On mobile it also opens an empty card modal in Portrait Orientation.

**Expected behavior**
The sharing of a card uses the cards unique ID regardless of the board it is in. I am not yet fully aware of how access rights are currently managed, but if access would be lost after moving to another board it would be nice if a user either remains to have access to this specific card or can request access. It would also be nice if you could switch the ID shown in a card to the unique one (for git reference).

**Screenshots**
![IMG_1593](https://github.com/nextcloud/deck/assets/62672081/e7adab22-6954-452b-ab8b-ea00cf9ea76b)
<img src="https://github.com/nextcloud/deck/assets/62672081/84e3f9f2-a10b-40b2-bf57-9202d9b0c2b2" width="200" />

**Client details:**
 - OS: Any
 - Browser Any
 - Version 27.0.0
 - Device: Any

**Comment by juliushaertl** [comment]
Thanks a lot for the separate repot.

A few thoughts already without looking in depth into the implementation details:
- We should fetch the card info and change to the new board if it doesn't match (and if the user has access of course)
- I think we should move our frontend urls to `/board/6/card/10` instead of `/#/board/6/card/10` so we could check and redirect in the backend

**Comment by Uatschitchun** [comment]
This is the same with text app adding smart picker links. Once moved, the link doesn't follow.
Or is there a way to update links?

**Comment by Gobytego** [comment]
same issue here, thanks for posting this

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/deck/pull/5047 where we now have a board independent link being inserted. There is unfortunately no way to update existing references.
