### ISSUE TITLE
After archiving a card, drag and drop cards is not working anymore

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/deck#4948]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
After archiving a card, drag and drop cards is not working anymore.

**To Reproduce**
1. Go to a Deck board
2. Try to drag and drop a card to change its column. It works.
3. Archive a card
4. The archived card gets grayed, and stays visible (I think in older version it disappeared)
5. Try to drag and drop a card to change its column. It does not work.

**Expected behavior**
Drag and drop a card should work

**Screenshots**

**Client details:**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox 115
 - Version [e.g. 22] c.nc.c
 - Device: [e.g. iPhone6, desktop] desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by KralaBenjamin** [comment]
I have a similar issue though using chrome I dont have the problem anymore

**Comment by maximelehericy** [comment]
cannot reproduce anymore (Firefox 115.0.3)
