### ISSUE TITLE
Option to update smart picker links 

### ISSUE THREAD

**Issue by Uatschitchun** [nextcloud/deck#4967]
**Is your feature request related to a problem? Please describe.**
Adding smart picker links to cards, files, etc are nice, but cards, files etc can move. 
If a deck card gets moved (another board, another list) or a file gets moved into another folder, the links in the text file are pointing into nirvana. 

**Describe the solution you'd like**
Allow smart picker links to be smart and follow the object it points to or a way to update/refresh the links

**Comment by juliushaertl** [comment]
Route endpoint to use: https://github.com/nextcloud/deck/blob/ccf73736c4e9d3bcb67b951c709f82263b3c0ea2/appinfo/routes.php#L28
URLs used from the picker are coming from https://github.com/nextcloud/deck/blob/264be93a74215d3baf19e7a66305a8be2db8cd71/lib/Search/CardSearchResultEntry.php#L43

**Comment by juliushaertl** [comment]
@luka-nextcloud Could you take this one as well?
