### ISSUE TITLE
line feed in decription of cards after update to deck 0.4.0-beta2

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#502]
**Describe the bug**
After update to deck 0.4.0-beta2 the line feeds in the description of a card are lost

**To Reproduce**
1. Create a card in deck 0.3.1 and add a description with some lines (markup with no special code, just line feeds)
2. Update to deck 0.4.0-beta2
3. Open the card
4. All lines (edited in deck 0.3.1) are in one line in deck 0.4.0-beta2. 

**Expected behavior**
Same layout of the description after update to deck 0.4.0-beta2

**Screenshots**

**deck 0.3.1: card with in edit mode:**
![d3_m](https://user-images.githubusercontent.com/34692335/41736201-1fffdf6a-758c-11e8-9c40-2375beefa54f.png)

**deck 0.3.1: card with in viewing  mode:**
![d3_](https://user-images.githubusercontent.com/34692335/41736217-2756fad2-758c-11e8-9357-1a555e31ab6c.png)

**0.4.0-beta2:  card with in viewing mode:**
![d4_](https://user-images.githubusercontent.com/34692335/41736238-3242f0d6-758c-11e8-8661-b42e8d38c8fd.png)

**Client details:**
Ubuntu 18.04
Firefox 60.0.2

**Server details:**
Ubuntu 18.04
Nextcloud 13.0.4
deck 0.3.1 and update to  
deck 0.4.0-beta2  downloaded and extracted from github.../releases/download/v0.4.0-beta2/deck.tar.gz

**Comment by juliushaertl** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/nextcloud/deck/issues/237 (Error when updating Deck), https://github.com/nextcloud/deck/issues/231 (The style is broken after update to 0.2.1), and https://github.com/nextcloud/deck/issues/110 (0.1.3 renamed to deck instead decks).

**Comment by juliushaertl** [comment]
Fixed by #508
