### ISSUE TITLE
upload attachment only for admin possible ?

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#503]
**Describe the bug**
A user, who is not admin of nextcloud can't upload an attachment to a card?

**To Reproduce**
1. Login as admin-user
2. Open a card and attach a file, then the file is uploaded 
3. Share the board to a non admin user
4. Login with the non-admin user
5. Open a card and try to upload an attachment
6, The non-admin user is able to select a file, but the upload doesn't start

Or

1. Login with a non-admin user
2. Create a card and try to upload an attachment
3, The non-admin user is able to select a file, but the upload doesn't start

**Expected behavior**
All user who have the right to change the description of a card can upload attachments

**nextcloud.log:**
...
{"reqId":"oQM1lNlHJNwZqg8Br5d3",
"level":0,
"time":"2018-06-21T21:01:06+00:00",
"remoteAddr":"127.0.0.1",
"user":"testuser",
"app":"no app in context",
"method":"POST",
"url":"\/nextcloud\/index.php\/apps\/deck\/cards\/2\/attachment",
**"message":"Logged in user must be an admin",**
"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0",
"version":"13.0.4.0"}

**Comment by juliushaertl** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/nextcloud/deck/issues/17 (Attachments), https://github.com/nextcloud/deck/issues/167 (It's possible to open more than one context menus), and https://github.com/nextcloud/deck/issues/204 (It's not possible to use custom color for a board).

**Comment by juliushaertl** [comment]
Thanks for reporting. Can you check the beta2 https://github.com/nextcloud/deck/releases/tag/v0.4.0-beta2 ? Fix was implemented in 313bbca4626fb81fa99a80dcf64df0e626c84d3c

**Comment by cloud2018** [comment]
works well with beta2 
and thanks for this app
