### ISSUE TITLE
Remember last board/list for new card dialog

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#5031]
Small enhancement task for the create card dialog:

- We should remember the last board and stack used in the create card dialog
- If none is previously remembered we fall back to the least recently edited one
- Store this in the browser localStorage

**Comment by luka-nextcloud** [comment]
@juliushaertl 
> If none is previously remembered we fall back to the least recently edited one

Do you mean recently edited board or card?

**Comment by juliushaertl** [comment]
Recently edited board and list, the lastModified property should be good to use as it always updates if something's changes.
