### ISSUE TITLE
Option to turn off strike thru with check boxes

### ISSUE THREAD

**Issue by Gobytego** [nextcloud/deck#5033]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
This started with new update

**Describe the solution you'd like**
An option to turn off strike thru with check boxes

**Describe alternatives you've considered**
maybe have a separate checkbox with strike thru

**Additional context**
most of our guys get confused because we used to use strike thru's for items we did not need and we use check boxes to show completed items... having the checkbox also do a strike thru causes confusion.

**Comment by juliushaertl** [comment]
This has been an upstream design decision in the text editor and we won't add a config flag just for that.

However you could of course apply some custom css using https://github.com/nextcloud/theming_customcss to change this to your preference. The following rule should work for that:

```css
div.ProseMirror .checkbox-item.checked label {
	text-decoration: none !important;
}
```

**Comment by Gobytego** [comment]
We do not want to implement the custom CSS.

**Comment by Gobytego** [comment]
thank you this worked

**Comment by 1358** [comment]
```
div.ProseMirror .checkbox-item.checked>label>p {
	text-decoration: none !important;
}
```
IMO the upstream decision is somewhat questionable as this removes the visual distinction between tasks that are completed and those that are discarded. Plus the original feature request was only about "a little bit of some beauty and aesthetics" (https://github.com/nextcloud/text/issues/886).
