### ISSUE TITLE
error when removing a tag from a card

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#504]
**Describe the bug**
When removing a tag from a card, deck crash and in the adress line of the browser is "unsafe:javascript:;"

**To Reproduce**
1. Open a card, which has a tag
2. Remove the tag (Click on 'x' of the tag)
3. A error page from the browser is displayed (The address wasn’t understood: unsafe:javascript:;)

**Work around**
Just use the back button of the browser and ererything is fine

**Client details:**
Ubuntu 18.04
Firefox 60.0.2

**Server details:**
Ubuntu 18.04
Nextcloud 13.0.4
deck 0.4.0-beta2 downloaded and extracted from github.../releases/download/v0.4.0-beta2/deck.tar.gz

**Comment by juliushaertl** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/nextcloud/deck/issues/217 (Error when tag will be removed), https://github.com/nextcloud/deck/issues/421 (Separate "high priority" card tag), https://github.com/nextcloud/deck/issues/138 (Card redesign), https://github.com/nextcloud/deck/issues/480 (Recurrently cards), and https://github.com/nextcloud/deck/issues/237 (Error when updating Deck).

**Comment by juliushaertl** [comment]
Fixed by #504
