### ISSUE TITLE
iOS/Android App Notification

### ISSUE THREAD

**Issue by kagstrom2100** [nextcloud/deck#5071]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Some users in my Nextcloud instance don't use the WEB-GUI but only the iOS/android app.

**Describe the solution you'd like**
Notifications like new comments on cards, or new card assignments to users via the Nextcloud iOS/android app.

**Describe alternatives you've considered**
E-mail could work for some people, but in my instance we're not using email.

**Additional context**
Not sure I'm posting this in the right repository. Please let me know if it needs to be moved :)

**Comment by stefan-niedermann** [comment]
For Deck Android check out https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#how-to-receive-notifications-when-a-due-date-is-reached

**Comment by kagstrom2100** [comment]
> For Deck Android check out https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#how-to-receive-notifications-when-a-due-date-is-reached

Ah, thanks. Still an issue on iOS though.

**Comment by juliushaertl** [comment]
Please report this to the iOS app itself as this repo is only for the server part.
