### ISSUE TITLE
Card edit modal does not show up when access from direct url

### ISSUE THREAD

**Issue by luka-nextcloud** [nextcloud/deck#5086]
#### Description
Card edit modal does not show up when access from direct url

#### Steps to reproduce: 
1. Open any card
2. Reload browser
#### Expected behaviour:
Card edit modal show up
#### Actual behaviour:
Card edit modal does not show up

**Comment by gwnmikedus** [comment]
Hmm, my installation 27.0.2 does seem to work. Opened different cards on different boards and reload works just fine. I see the url change to the card and when reloading it re-opens the modal.
