### ISSUE TITLE
Feature: mutually exclusive labels

### ISSUE THREAD

**Issue by OrvilleQ** [nextcloud/deck#5092]
Hi.

I'm using NextCloud Deck to track progress on things do not need code. It works great but I found is really annoying browsing all the labels I created, It might could be better if have some kind of mutually exclusive labels.

For example:

You can only choose on between Scope/Art & Scope/Narrative & Scope/Music and hide other once you make your choice. Same to Priority/Critical & Priority/Low or things like that.

Also it would be great to choose board/label's color with hex.

What do you think?

**Comment by juliushaertl** [comment]
Hi @OrvilleQ 

Thanks for your feature request. I can see this is a valid use case however we currently consider deck more as a simple tool that is easy to use and want to keep the complexity low. We target common use cases but don’t necessarily want to extend to a fully fledged project management tool. There are lots of good open source tools out there already for more complex use cases. Therefore I’d consider this out of scope.

**Comment by juliushaertl** [comment]
> Also it would be great to choose board/label's color with hex.

There is an upstream issue for that in the color picker component that we use at https://github.com/nextcloud-libraries/nextcloud-vue/issues/1687
