### ISSUE TITLE
OS App refuses to log in

### ISSUE THREAD

**Issue by ntTim** [nextcloud/deck#5093]
When trying to log in to the OS app, we permanently receive an error message and cannot determine the background for this.
![f3214a53f803bafb3748feaa50f8c8720e65030f](https://github.com/nextcloud/deck/assets/144261755/d4658db7-b892-4dad-a6bd-9d86de152db8)

**Comment by juliushaertl** [comment]
Not sure which app that is but please report it to the developer as this repo only covers the nextcloud webapp itself.
