### ISSUE TITLE
wrong target of link of release 0.4.0-beta4?

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#517]
The extracted deck/appinfo/info.xml of the release v0.4.0-beta4 has &lt;version&gt;0.4.0-beta**3**&lt;/version&gt; instead of &lt;version>0.4.0-beta**4**&lt;/version&gt;

The deck.tar.gz was downloaded from page https://github.com/nextcloud/deck/releases/
with the first link (https://github.com/nextcloud/deck/releases/download/v0.4.0-beta4/deck.tar.gz) 

The other two links [Source code (zip) and Source code (tar.gz)] are ok and refer to an info.xml with &lt;version&gt;0.4.0-beta4&lt;/version&gt;.

**Comment by juliushaertl** [comment]
Thanks for reporting. The package uploaded was apparently packaged before bumping the version number. This should have no influence on the functionality. I've uploaded the correct package now.
