### ISSUE TITLE
Random https error after manual syncing

### ISSUE THREAD

**Issue by carling-knock** [nextcloud/deck#5251]
Hey there,

getting a random error with resulting in a "NC Deck log" this happened after swiping down on the screen for manual synchronisation to the NC server.
[NC Deck log.txt](https://github.com/nextcloud/deck/files/13204626/NC.Deck.log.txt)

Other NC apps running in parallel, device is clearly connected to NC.
Full integration with Nextcloud server ver.26.0.5 in conjunction with latest Nextcloud Desktop ver.3.10.1.20231025 and NextcloudServices Ver.1.0-beta16 app for syncing running in background too.
Not sure if it matters if DAVx5 ver.4.3.9-gplay (full paid version) running at the same time as well, well just mention it in case it has an effect on the situation.

1. Regular Play store Apps:
current Nextcloud Ver.3.26.0 Updated on 8.Sept.2023
current Nextcloud Notes Ver.4.1.0 Updated on 20 Sept 2023
current Nextcloud Talk Ver.17.1.2 Updated on 19 Oct 2023
current DAVx5 ver.4.3.9-gplay Update 27.10.2023

2. Additional F-Droid Apps, hooked up to my Nextcloud account:
working as expected and as far as these are maintained on GitHub...
Nextcloud Deck Ver.1.23.4 (1023004) Added on 2023-10-04
NextcloudServices Ver.1.0-beta16 Added on 2023-06-23
NextPush Ver.1.8.1 (28) Added on 2023-09-12
Quillpad Ver.1.4.11 (15) Added on 2023-07-24
Readrops Ver.1.3.1 (14) Added on 2021-10-12

**Comment by stefan-niedermann** [comment]
Hello,

the Android clients are all irrelevant given they only display "Server Error HTTP 500" - obviously the Android apps can't work if the server does respond with errors.

However, please fill out the completen issue template, it is there for a reason. Especially check the **server** error logs, where the error is happening.

**Comment by juliushaertl** [comment]
Please check the server logs and report depending on where the error points to with a properly filled out issue template. Will close this for now.
