### ISSUE TITLE
Add new Cards at the top of a list

### ISSUE THREAD

**Issue by b3nks** [nextcloud/deck#5311]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When adding a new Card, it is most often the case, that this card needs to be finished sooner than the last one.
In long lists, the card will be placed at the very bottom and after scrolling down needs to be dragged somewhere up. When adding lot's of Tasks (e.g. when people are dumping their minds) this takes a lot of scrolling.

**Describe the solution you'd like**
As already proposed in #2632 new card should be placed at the very top, after having saved it.

**Describe alternatives you've considered**
Next to the safe Button there could also be a checkbox, "place at bottom" to make the user choose the behavior.
Or there could be two save buttons e.g. "Add at top" "Add to bottom"
Also it would reduce scrolling to have a Bulk Create, where you enter multiple lines at once that will become titles for cards.

**Comment by juliushaertl** [comment]
Thanks for the suggestion. There is already an existing ticket for this in https://github.com/nextcloud/deck/issues/1961 so I'll close this one as a duplicate.
