### ISSUE TITLE
After inserting attachment in description, auto-save doesn't work anymore...

### ISSUE THREAD

**Issue by Aesculapius** [nextcloud/deck#532]
**Describe the bug**
Awesome to see the attachment feature, but after inserting an attachment into the description field, it isn't being auto-saved....

**To Reproduce**
1. create a card
2. enter some description
3. Go to Attachments tab and upload an attachment
4. Go back to description tab and insert attachment, choose the uploaded one with the arrow
5. Enter some text after the inserted link... 

**Expected behavior**
I'd expect auto-save to work and the image to be shown

**Screenshots**
Attached is the status without saving:
![image](https://user-images.githubusercontent.com/617061/42690302-fb44cef0-86a3-11e8-9e53-5f9283cbcf43.png)

**Client details:**
 - OS: Win10
 - Browser Chrome
 - Version 67
 - Device: Desktop

**Comment by juliushaertl** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/nextcloud/deck/issues/17 (Attachments), https://github.com/nextcloud/deck/issues/518 (Broken link in description after the attachment is deleted), https://github.com/nextcloud/deck/issues/369 (Auto save discards changes), https://github.com/nextcloud/deck/issues/247 (Sharing in left navigation doesn’t seem to work), and https://github.com/nextcloud/deck/issues/324 (Description unable to saved if add Due Date).

**Comment by Aesculapius** [comment]
Well, good catch; that definately seems to be the point where things fail :-)

![image](https://user-images.githubusercontent.com/617061/42748124-40f2ecba-88df-11e8-9b45-091eae1ce051.png)

**Comment by Aesculapius** [comment]
obviously that PUT command is failing with a 500-error. What permissions are needed to make this work? I already created the /cards folder with write permission in the /apps/deck/ folder (wasn't there) but to no avail...

**Comment by juliushaertl** [comment]
Thanks for the log files. This is actually a bug. Your database doesn't have 4-byte support enabled and therefore fails to insert the attachment icon. We should not add that icon in that case.

Reference regarding 4-byte support:
https://docs.nextcloud.com/server/13/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by Aesculapius** [comment]
Or should I just enable this 4-byte support then?

**Comment by juliushaertl** [comment]
Yes, that should fix it as well :wink:
