### ISSUE TITLE
REQUEST: Nextcloud Deck in Wordpress Integration Plugin

### ISSUE THREAD

**Issue by gurutto-manila** [nextcloud/deck#5333]
is there a way to integrate Deck in to Wordpress Website as Plugins? or is there a plugin already?

**Comment by juliushaertl** [comment]
I'm not aware of any plugin but would of course be happy to hear about someone developing such an integration. 

However as this is an issue tracker mainly for the app itself, I'll close this. Best place to ask such questions or even brainstorm about developing such an integration would be the forum at help.nextcloud.com.
