### ISSUE TITLE
Sidebar-Menu Icon  miss-placed

### ISSUE THREAD

**Issue by xstable** [nextcloud/deck#5334]
1. Open an existing Board
2. Collapse the side-menu of the decks
3. Looks like this if the side-bar is collapsed:
![image](https://github.com/nextcloud/deck/assets/1778068/51b9cd36-db0e-4482-bdb0-224d3737a60e)

# How to solve
I recommend to put the Menu-button right in front of the Title (inside the <main>-Tag), so that it can not overlap with it: 
![image](https://github.com/nextcloud/deck/assets/1778068/91515416-f59f-48d5-b7cb-3c9c2420a3bb)

Some minor css-adjustments and it should be done.

Another solution / workaround may be to set this stylesheet.: 
```css
.board-title{ margin-left: 65px;}
```

**Comment by juliushaertl** [comment]
I cannot reproduce this and would think this is caused by the sidebar menu app you are using. Please report this over there

**Comment by xstable** [comment]
@juliushaertl you are right... it's caused by the "custom menu" I do use (with vertical alignment).  (https://apps.nextcloud.com/apps/side_menu) 

I've opened an issue here: https://gitnet.fr/deblan/side_menu/issues/302
