### ISSUE TITLE
Error When Posting Deck Card to Conversation via Quick Menu

### ISSUE THREAD

**Issue by melbruki** [nextcloud/deck#5336]
![test](https://github.com/nextcloud/deck/assets/34458218/fd899101-8fbd-4525-a4e3-fd546ef1f2c0)
![test2](https://github.com/nextcloud/deck/assets/34458218/07a5b93c-a3b1-45c5-a150-7e27fff44a2e)
Body:

Environment:

Nextcloud Version: 27.1.3
Deck App Version: 1.11.2
Description:
There is an error when attempting to post a Deck card to a conversation without opening the card's details. The error does not occur when posting from within the card's details.

Steps to Reproduce:

Click on the three dots menu of a Deck card.
Choose 'Post to Conversation'.
Select the conversation and click 'OK'.
An error message appears: "An error occurred while posting deck card to conversation."
Expected Behavior:
The card should be posted to the selected conversation without any error, similar to when it is done from the card's details view.

Actual Behavior:
An error prevents the card from being posted to the conversation when done from the card's quick menu.

Additional Information:

The issue does not occur when posting to a conversation from within the card's detailed view.
This seems to be a specific issue with the quick action menu.

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/deck/pull/5351
