### ISSUE TITLE
Attaching card to chat in talk doesn't work

### ISSUE THREAD

**Issue by pschopen** [nextcloud/deck#5350]
When one tries to add a card to a chat in talk, that results in the following error:

<img width="618" alt="grafik" src="https://github.com/nextcloud/deck/assets/65334274/db8d12a7-2feb-455c-ac93-ee8ae6659318">

Version of deck: 1.11.2

**Comment by juliushaertl** [comment]
Was fixed with https://github.com/nextcloud/deck/pull/5351
