### ISSUE TITLE
Colour picker does not show in Safari

### ISSUE THREAD

**Issue by wiertz** [nextcloud/deck#537]
**Describe the bug**
Using Firefox and Chrome, clicking on the color picker icon in board properties or new board menu opens a small window to choose a color. Using Safari no such window appears.

**To Reproduce**
Create a new board in Safari and click on the color picker icon to the right of the color scale.

**Client details:**
MacOS High Sierra
Nextcloud 13.04
Deck 0.4
Safari 11.1.1

No big issue for me, but of course it would be nice if the color picker worked also in Safari.

**Comment by juliushaertl** [comment]
Thanks for reporting. Seems that color input is not supported by IE and Safari 9, but you seem to have Safari 11. Anyway we might need something like jscolor as a fallback then.

https://caniuse.com/#feat=input-color

**Comment by juliushaertl** [comment]
It is more work to do that, so moving to 0.5

**Comment by juliushaertl** [comment]
Closing as this was fixed in the vue branch and is now merged to master.
