### ISSUE TITLE
Bring comments to the main card tab

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/deck#5396]
Updating cards via comments is one of the most useful features, so I think that comments should be in the main tab.

**Comment by juliushaertl** [comment]
I'm not sure, this highly depends on the use case and the normal card details tab is already quite crowded. For me personally comments are not used a lot and the state is rather represented in the description.

**Comment by marcoambrosini** [comment]
It's crowded with information that isn't important if not used (empty form elements).
I think we should adopt Trello's approach, where blocks can be added to a single main view and are not shown in case they're going to be used. Their approach is advantageous precisely because there can be different use cases. With our design if you mostly fill description, date and assignee you're in luck, but if you work with attachments and comments you find yourself going back and forth with tabs, which adds much more friction than just scrolling up and down in the main view.

**Comment by juliushaertl** [comment]
Right, we actually have an issue with design mockups already covering that in https://github.com/nextcloud/deck/issues/2702

**Comment by marcoambrosini** [comment]
Oh right, i forgot about that one!
