### ISSUE TITLE
Typing a 0 in the date picker removes the due date

### ISSUE THREAD

**Issue by pschopen** [nextcloud/deck#5398]
When typing a date (e.g. 01.01.2024), typing the 0 results in removing the die date; that also causes a lot of entries in the activity app.

Even if that was on purpose it doesn't seem very intuitive; mainly because the date format (01.01.) encourages to also type the 0.

**Comment by nickvergessen** [comment]
it's not only this, but also typing any other number is "problematic".

The date saves too fast after typing the first number and so when you type `12` it will store `01` after the 1 was typed already. Maybe a little debounce could help?
