### ISSUE TITLE
Hide marked as done cards

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/deck#5406]
It's nice to have the new feature: 
Added ability to mark a card as done

Maybe it would make sense to hide done cards at the end of the list e.g. MS Planner is doing like that

![image](https://github.com/nextcloud/deck/assets/24530680/b8bba4f2-cfa5-4a94-9f8d-b9fb20990c0c)

**Comment by schiessle** [comment]
This, or add two filter option in the section "filter by due date":

- done (only show done tasks)
- open (to hide the done tasks in order not to be distracted from the open tasks)

**Comment by juliushaertl** [comment]
Yes, I'd say we should definitely add this to the existing list of filters in the board:

<img width="255" alt="Screenshot 2024-01-17 at 16 15 32" src="https://github.com/nextcloud/deck/assets/3404133/7fa960ec-ec28-45ce-8ce0-85b4b44a59f0">

**Comment by pedroponte** [comment]
+1
