### ISSUE TITLE
Trusted_Domain when run docker command

### ISSUE THREAD

**Issue by wcdfilll** [nextcloud/deck#5419]
when i run **docker run --rm \ -p 8080:80 \ -v ~/path/to/app:/var/www/html/apps-extra/app \ ghcr.io/juliushaertl/nextcloud-dev-php80:latest**, i had problem about trusted_domain, when i ran the previous command, i didn't know how to edit trusted_domain instead of `nextcloud` it should be `mydomain`

**Comment by stefan-niedermann** [comment]
How is this related to the Nextcloud Deck app? Are you sure you are in the correct repository?

**Comment by juliushaertl** [comment]
> How is this related to the Nextcloud Deck app? Are you sure you are in the correct repository?

This is about the development setup described in https://github.com/nextcloud/deck#docker-simple-app-development-container.

Currently I'd recommend to use http://localhost:8080 for this. I'll see if we can use a wildcard for the trusted_domains there instead to make it more straight forward but using nextcloud as a hostname is not documented anywhere as far as I'm aware or where did you take that from?
