### ISSUE TITLE
Node(cards)-based interface

### ISSUE THREAD

**Issue by jonidimo** [nextcloud/deck#542]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when i'm trying to see the connections and relations between the cards, dates, actions to take in certain columns delineating workflow activities.

**Describe the solution you'd like a clear and concise description of what you want to happen.**

Implementing a node(cards)-based interface like many others like Blueprints Visual Scripting, mindnode, relate this with the calendar to take acctions, IFTTT, mindmaps, some other app like flowchart, etc.

**Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.**

There is no app that have all this. I tried onenote, evernote, mindmeister, trello, etc.

**Additional context add any other context or screenshots about the feature request here.**
![image](https://user-images.githubusercontent.com/400642/42956528-9228e412-8b56-11e8-9e0a-186f19d2241c.png)

![image](https://user-images.githubusercontent.com/400642/42956537-97afee6c-8b56-11e8-8768-b5aea171c131.png)

![image](https://user-images.githubusercontent.com/400642/42956828-577a07e6-8b57-11e8-9896-557991c990da.png)

**Comment by juliushaertl** [comment]
This is a totally different concept from what the deck app is designed for, so adding a view like this is out of scope. Maybe you can move your request over to the https://github.com/splitt3r/mindmaps app, which at least already provides some type of visual connection between notes.

**Comment by juliushaertl** [comment]
From my mail to @jonidimo, who asked about some more details, why this was closed:

> Right now we don't have any relation between cards in Deck. The current data model is strongly based on the Kanban principle and the goal is to have a simple to use UI that fits most of the use cases. Having a visual connection of cards would add alot of complexity to the UI and to me the requirement seems to be rather specific. 
> 
> There is a request for parent/child dependencies for cards, which would be a first step to have some deeper linking between cards: https://github.com/nextcloud/deck/issues/272 But this is not on our roadmap, at least for the near future.
> 
> If you would like to further discuss this, feel free to just comment in the issue, I might have missed something or maybe you can just provide some more details how you would have imagined such an implementation.
