### ISSUE TITLE
Done cards are still shown in the "upcoming cards" overview

### ISSUE THREAD

**Issue by schiessle** [nextcloud/deck#5482]
I see it currently with the latest version on c.nc.com

Tasks marked as done are still shown in the "upcoming cards" board. This is a real distraction from the important and open tasks. Done tasks should no longer be sown as "upcoming cards"

**Comment by juliushaertl** [comment]
I cannot reproduce that and tried a owned board as well as a shared one. Can you share an example card id from our instance with me?
