### ISSUE TITLE
Show tag title on cards overview

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#551]
**Is your feature request related to a problem? Please describe.**
It is possible to set differently coloured tags, but colour alone is often not intuitive enough.
Especially when one is using many different colour tags it soon gets complicated and many users won't remember the colour specific relevance. E.g. setting different priority levels is hardly possible.

**Describe the solution you'd like**
Enhance visual tag identification by allowing the user to add an optional char that is displayed inside the tag. E.g.: A-Z, a-z, 0-9, !?$+-, ...

**Describe alternatives you've considered**
If the tag size was dynamic, there could even be multiple chars or the whole tag name used in this.
E.g.: todo, !2, it, 42, ?
Instead of setting a separate char, a user set checkbox per tag ("show tag description permanently") could simplify the process.

**Additional context**
If considered in https://github.com/nextcloud/deck/issues/414 it would provide a more granular sorting option, e.g. by different priority levels (1-...) in red tags or whatever char and colour is used.
The char colour needs to be automatically adjusted depending on the background colour.
This way https://github.com/nextcloud/deck/issues/421 could be realized indirectly.

**Comment by bpcurse** [comment]
@juliushaertl Thank you for your fast reply. That is exactly what I meant in the alternatives section.
I agree that the additional information will be very helpful and displaying the whole tag name is the better way. Maybe just let the user additionally choose if it is displayed or not or if only the first x letters are shown?

**Comment by juliushaertl** [comment]
Regarding the design, I'd just propose to show them as it is done with GitHub issues, under the card title with a smaller font size.

![image](https://user-images.githubusercontent.com/3404133/43096997-00c6992a-8ebb-11e8-9263-9fe5af67bfc3.png)

**Comment by philippe-levan** [comment]
@juliushaertl : I can take this issue if you want.

**Comment by juliushaertl** [comment]
@philippe-levan That would be awesome. I've invited you to the deck project, so you can push your branch directly to the repo. That makes it a bit easier to test/contribute on a pull request.

**Comment by juliushaertl** [comment]
Implemented with #561
