### ISSUE TITLE
NC 28 Deck 1.12.1 dark theme date picker

### ISSUE THREAD

**Issue by bin101** [nextcloud/deck#5513]
**Describe the bug**
With the default nc dark theme the date picker icon is barely visible and the date picker itself is not dark at all:
<img width="865" alt="image" src="https://github.com/nextcloud/deck/assets/12427722/b863488b-e464-46b5-9a75-8ec31263ae23">

Sidenote: The picker is not translated

**Client details:**
 - OS: MacOS
 - Browser Chrome
 - Version 120
 - Device: Macbook Pro M1

Deck Version: 1.12.1
NC Version: Nextcloud Hub 7 (28.0.1)

**Comment by joshtrichards** [comment]
Fixed
