### ISSUE TITLE
Link cards with related content

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#552]
**Is your feature request related to a problem? Please describe.**
Sometimes multiple cards in a stack are connected to each other (logically and/or by content). If you want them to stay visually together you have to pay attention when a card is moved to not separate them.

**Describe the solution you'd like**
It should be possible to "link" cards together. Select 2 or more cards and issue a "link cards" command. The cards should then be moved to consecutive positions in the stack and a chain link symbol should be displayed in the space between the connected cards.
If they were to be moved now, all connected cards should be moved together.

**Alternative**
Add the feature to select multiple cards e.g. by using ctrl + click and move them together.

**Comment by juliushaertl** [comment]
> It should be possible to "link" cards together. Select 2 or more cards and issue a "link cards" command. The cards should then be moved to consecutive positions in the stack and a chain link symbol should be displayed in the space between the connected cards.
If they were to be moved now, all connected cards should be moved together.

I think that would add to much complexity to the way a user interacts with cards.

> Add the feature to select multiple cards e.g. by using ctrl + click and move them together.

That sounds like a way nicer approach to me. It doesn't add any additional UI and is way more flexible than having a static linking.
