### ISSUE TITLE
Deck breaks Nextcloud Public Share Links & Permissions

### ISSUE THREAD

**Issue by Pietro-Aretino** [nextcloud/deck#5535]
**Describe the bug**
Creating a public share link for a file or folder works, however when one navigates to the public share via the link one receives the error, "This directory is unavailable, please check the logs or contact the administrator."

**To Reproduce**
Create public link
Navigate to public link
Unable to view contents receive error "This directory is unavailable"
Deactivating the "Deck" application from within Nextcloud fixes issue.
Once the app is deactivated all the public share links function, and end-users are able to view contents of shared folders and files.

**Expected behavior**
Creating a public share link should work. Once someone clicks on link they should be brought to file or folder.

**Client details:**
All clients

<details>
<summary>Server details</summary>

Deck Version: 1.8.7
Nextcloud Version: 25.0.13

PHP: Version: 8.1.27
Memory limit: 1000 MB
Max execution time: 3600
Upload max size: 100 MB
Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, Zend OPcache

Database: PGSQL
 Version: PostgreSQL 12.17 (Ubuntu 12.17-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit
Size: 2,4 GB 

Running inside of VM on ESXI

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

"No errors have been found."
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - analytics: 4.11.1
  - announcementcenter: 6.6.2
  - bruteforcesettings: 2.5.0
  - calendar: 4.6.4
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - drawio: 2.1.4
  - external: 5.0.3
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.3.1
  - impersonate: 1.12.1
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.9.2
  - notifications: 2.13.1
  - oauth2: 1.13.1
  - onlyoffice: 7.9.4
  - previewgenerator: 5.3.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - sharelisting: 1.1.1
  - socialsharing_email: 2.6.0
  - spreed: 15.0.8
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tables: 0.6.6
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - apporder: 0.15.0
  - deck: 1.8.7
  - encryption
  - federation: 1.12.0
  - files_antivirus: 5.4.1
  - integration_excalidraw: 2.0.4
  - password_policy: 1.12.0
  - photos: 1.4.0
  - recommendations: 1.2.0
  - twofactor_totp: 6.4.1
  - unroundedcorners: 1.0.9

**Nextcloud configuration:**
$CONFIG = array (

  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 
    2 => 
    3 => 
  ),
  'datadirectory' => '/mnt/ncdata',
  'dbtype' => 'pgsql',
  'version' => '25.0.13.2',
  'overwrite.cli.url' => 'https://cloud
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'instanceid' => '',
  'upgrade.disable-web' => true,
  'lost_password_link' => 'disabled',
  'log_type' => 'file',
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'loglevel' => '2',
  'log.condition' =>
  array (
    'apps' =>
    array (
      0 => 'admin_audit',
    ),
  ),
  'mail_smtpmode' => 'smtp',
  'remember_login_cookie_lifetime' => '1800',
  'log_rotate_size' => '0',
  'trashbin_retention_obligation' => 'auto, 60',
  'versions_retention_obligation' => 'auto, 180',
  'activity_expire_days' => '120',
  'simpleSignUpLink.shown' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis-server.sock',
    'port' => 0,
    'timeout' => 0.5,
    'dbindex' => 0,
 'dbindex' => 0,
    'password' => '',
  ),
  'default_phone_region' => 'it',
  'defaultapp' => 'files',
  'logtimezone' => 'Europe/Rome',
  'default_language' => 'it',
  'htaccess.RewriteBase' => '/',
  'allow_local_remote_servers' => true,
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    11 => 'OC\\Preview\\PNG',
    12 => 'OC\\Preview\\JPEG',
    13 => 'OC\\Preview\\GIF',
    14 => 'OC\\Preview\\BMP',
    15 => 'OC\\Preview\\MarkDown',
    16 => 'OC\\Preview\\MP3',
    17 => 'OC\\Preview\\TXT',
    18 => 'OC\\Preview\\Movie',
  ),
  'preview_max_x' => '2048',
  'preview_max_y' => '2048',
  'jpeg_quality' => '60',
  'trusted_proxies' =>
  array (
    0 => '127.0.0.1',
  ),
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'maintenance' => false,
  'mail_smtpsecure' => 'tls',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'cloud',
  'mail_domain' => '',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpport' => '465',
  'mail_smtphost' => 'mail.',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'cloud.it',
  'mail_smtppassword' => 'a',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Using LDAP for user-backend
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
"line": 310, "function": "getUserIdGroupIds", "class": "OC\\Group\\Manager",
"type": "->"
}, {
    "file": "/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php",
    "line": 245,
    "function": "isInGroup",
    "class": "OC\\Group\\Manager",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php",
    "line": 114,
    "function": "userCan",
    "class": "OCA\\Deck\\Service\\PermissionService",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php",
    "line": 164,
    "function": "getPermissions",
    "class": "OCA\\Deck\\Service\\PermissionService",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php",
    "line": 289,
    "function": "checkPermission",
    "class": "OCA\\Deck\\Service\\PermissionService
    ","
    type ":" - > "},{"
    file ":" /
    var / www / nextcloud / apps / deck / lib / Sharing / DeckShareProvider.php ",
    "line": 668,
    "function": "applyBoardPermission",
    "class": "OCA\\Deck\\Sharing\\DeckShareProvider",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php",
    "line": 780,
    "function": "resolveSharesForRecipient",
    "class": "OCA\\Deck\\Sharing\\DeckShareProvider",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/lib/private/Share20/Manager.php",
    "line": 1407,
    "function": "getSharedWith",
    "class": "OCA\\Deck\\Sharing\\DeckShareProvider",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php",
    "line": 99,
    "function": "getSharedWith",
    "class": "OC\\Share20\\Manager",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php",
    "line": 134,
    "function": "getMountsForUser",
    "class": "OCA\\Files_Sharing\\MountProvider",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/lib/private/Files/SetupManager.php",
    "line": 226,
    "function": "addMountForUser",
    "class": "OC\\Files\\Config\\MountProviderCollection",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/lib/private/Files/SetupManager.php",
    "line": 318,
    "function": "OC\\Files\\{closure}",
    "class": "OC\\Files\\SetupManager",
    "type": "->",
    "args": ["*** sensitive parameters replaced ***"]
}, {
    "file": "/var/www/nextcloud/lib/private/Files/SetupManager.php",
    "line": 227,
    "function": "setupForUserWith",
    "class": "OC\\Files\\SetupManager",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/lib/private/legacy/OC_Util.php",
    "line": 111,
    "function": "setupForUser",
    "class": "OC\\Files\\SetupManager",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php",
    "line": 97,
    "function": "setupFS",
    "class": "OC_Util",
    "type": "::"
}, {
    "file": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/ServerFactory.php",
    "line": 133,
    "function": "{closure}",
    "args": ["*** sensitive parameters replaced ***"]
}, {
    "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
    "line": 89,
    "function": "OCA\\DAV\\Connector\\Sabre\\{closure}",
    "class": "OCA\\DAV\\Connector\\Sabre\\ServerFactory",
    "type": "->",
    "args": ["*** sensitive parameters replaced ***"]
}, {
    "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
    "line": 456,
    "function": "emit",
    "class": "Sabre\\DAV\\Server",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
    "line": 253,
    "function": "invokeMethod",
    "class": "Sabre\\DAV\\Server",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
    "line": 321,
    "function": "start",
    "class": "Sabre\\DAV\\Server",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php",
    "line": 123,
    "function": "exec",
    "class": "Sabre\\DAV\\Server",
    "type": "->"
}, {
    "file": "/var/www/nextcloud/public.php",
    "line": 81,
    "args": ["/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php"],
    "function": "require_once"
}],
"File": "/var/www/nextcloud/lib/private/Group/Manager.php", "Line": 327,
"message": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, 
called in /var/www / nextcloud / lib / private / Group / Manager.php on line 310 ","
exception ":{},
"CustomMessage": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, 
called in /var/www / nextcloud / lib / private / Group / Manager.php on line 310 "}} {
    "reqId": "72bniaA7JBjKpUzxkwZV",
    "level": 3,
    "time": "2024-01-30T10:15:57+01:00",
    "remoteAddr": "10.177.76.2",
    "user": "--",
    "app": "index",
    "method": "GET",
    "url": "/s/GPfn6qtrLDxGAzc/download",
    "message": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, 
    called in /var/www / nextcloud / lib / private / Group / Manager.php on line 310 in file '/var/www/nextcloud/lib/private/Group/Manager.php'
    line 327 ",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0",
    "version": "25.0.13.2",
    "exception": {
        "Exception": "Exception",
        "Message": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, 
        called in /var/www / nextcloud / lib / private / Group / Manager.php on line 310 in file '/var/www/nextcloud/lib/private/Group/Manager.php'
        line 327 ",
        "Code": 0,
        "Trace": [{
            "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
            "line": 172,
            "function": "dispatch",
            "class": "OC\\AppFramework\\Http\\Dispatcher",
            "type": "->"
        }, {
            "file": "/var/www/nextcloud/lib/private/Route/Router.php",
            "line": 298,
            "function": "main",
            "class": "OC\\AppFramework\\App",
            "type": "::"
        }, {
            "file": "/var/www/nextcloud/lib/base.php",
            "line": 1053,
            "function": "match",
            "class": "OC\\Route\\Router",
            "type": "->"
        }, {
            "file": "/var/www/nextcloud/index.php",
            "line": 36,
            "function": "handleRequest",
            "class": "OC",
            "type": "::"
        }],
        "File": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "Line": 165,
        "Previous": {
            "Exception": "TypeError",
            "Message": "OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given,
            called in /var/www / nextcloud / lib / private / Group / Manager.php on line 310 ","
            Code ":0,
            "Trace": [{
                    "file": "/var/www/nextcloud/lib/private/Group/Manager.php",
                    "line": 310,
                    "function": "getUserIdGroupIds",
                    "class": "OC\\Group\\Manager",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php",
                    "line": 245,
                    "function": "isInGroup",
                    "class": "OC\\Group\\Manager",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php",
                    "line": 114,
                    "function": "userCan",
                    "class": "OCA\\Deck\\Service\\PermissionService",
                    "type": "->"
                }, {
                    "file": "/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php",
                    "line": 164,
                    "function": "getPermissions",
                    "class": "OCA\\Deck\\Service\\PermissionService",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php",
                    "line": 289,
                    "function": "checkPermission",
                    "class": "OCA\\Deck\\Service\\PermissionService",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php",
                    "line": 668,
                    "function": "applyBoardPermission",
                    "class": "OCA\\Deck\\Sharing\\DeckShareProvider",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php",
                    "line": 780,
                    "function": "resolveSharesForRecipient",
                    "class": "OCA\\Deck\\Sharing\\DeckShareProvider",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/lib/private/Share20/Manager.php",
                    "line": 1407,
                    "function": "getSharedWith",
                    "class": "OCA\\Deck\\Sharing\\DeckShareProvider",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php",
                    "line": 99,
                    "function": "getSharedWith",
                    "class": "OC\\Share20\\Manager",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php",
                    "line": 134,
                    "function": "getMountsForUser",
                    "class": "OCA\\Files_Sharing\\MountProvider",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/lib/private/Files/SetupManager.php",
                    "line": 226,
                    "function": "addMountForUser",
                    "class": "OC\\Files\\Config\\MountProviderCollection",
                    "type": "->"
                },
                {
                    "file": "/var/www/nextcloud/lib/private/Files/SetupManager.php",
                    "line": 318,
                    "function": "OC\\Files\\{closure}",
                    "class": "OC\\Files\\SetupManager",
                    "type": "->",
                    "args": ["*** sensitive parameters replaced ***"]
                }, {
                    "file": "/var/www/nextcloud/lib/private/Files/SetupManager.php",
                    "line": 227,
                    "function": "setupForUserWith",
                    "class": "OC\\Files\\SetupManager",
                    "type": "->"
                }, {
                    "file": "/var/www/nextcloud/lib/private/legacy/OC_Util.php",
                    "line": 111,
                    "function": "setupForUser",
                    "class": "OC\\Files\\SetupManager",
                    "type": "->"
                }, {
                    "file": "/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareController.php",
                    "line": 673,
                    "function": "setupFS",
                    "class": "OC_Util",
                    "type": "::"
                }, {
                    "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                    "line": 225,
                    "function": "downloadShare",
                    "class": "OCA\\Files_Sharing\\Controller\\ShareController",
                    "type": "->"
                }, {
                    "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                    "line": 133,
                    "function": "executeController",
                    "class": "OC\\AppFramework\\Http\\Dispatcher",
                    "type": "->"
                }, {
                    "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
                    "line": 172,
                    "function": "dispatch",
                    "class": "OC\\AppFramework\\Http\\Dispatcher",
                    "type": "->"
                }, {
                    "file": "/var/www/nextcloud/lib/private/Route/Router.php",
                    "line": 298,
                    "function": "main",
                    "class": "OC\\AppFramework\\App",
                    "type": "::"
                }, {
                    "file": "/var/www/nextcloud/lib/base.php",
                    "line": 1053,
                    "function": "match",
                    "class": "OC\\Route\\Router",
                    "type": "->"
                }, {
                    "file": "/var/www/nextcloud/index.php",
                    "line": 36,
                    "function": "handleRequest",
                    "class": "OC",
                    "type": "::"
                }
            ],
            "File": "/var/www/nextcloud/lib/private/Group/Manager.php",
            "Line": 327
        },
        "CustomMessage": "--"
    }
}
root @cloud: /var/log / nextcloud #
```

</details>

**Comment by Pietro-Aretino** [comment]
New error;

`{"reqId":"vetEWXFWlidnj2LaEZMj","level":3,"time":"2024-02-12T16:45:16+01:00","remoteAddr":"156.54.175.231","user":"--","app":"index","method":"GET","url":"/s/trqw7Q2cBXtrZ8Z/download/Biorefinery.zip","message":"OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /var/www/nextcloud/lib/private/Group/Manager.php on line 310 in file '/var/www/nextcloud/lib/private/Group/Manager.php' line 327","userAgent":"Mozilla/5.0 (Android 13; Mobile; rv:122.0) Gecko/122.0 Firefox/122.0","version":"25.0.13.2","exception":{"Exception":"Exception","Message":"OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /var/www/nextcloud/lib/private/Group/Manager.php on line 310 in file '/var/www/nextcloud/lib/private/Group/Manager.php' line 327","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1053,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /var/www/nextcloud/lib/private/Group/Manager.php on line 310","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Group/Manager.php","line":310,"function":"getUserIdGroupIds","class":"OC\\Group\\Manager","type":"->"},{"file":"/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php","line":245,"function":"isInGroup","class":"OC\\Group\\Manager","type":"->"},{"file":"/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php","line":114,"function":"userCan","class":"OCA\\Deck\\Service\\PermissionService","type":"->"},{"file":"/var/www/nextcloud/apps/deck/lib/Service/PermissionService.php","line":164,"function":"getPermissions","class":"OCA\\Deck\\Service\\PermissionService","type":"->"},{"file":"/var/www/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php","line":289,"function":"checkPermission","class":"OCA\\Deck\\Service\\PermissionService","type":"->"},{"file":"/var/www/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php","line":668,"function":"applyBoardPermission","class":"OCA\\Deck\\Sharing\\DeckShareProvider","type":"->"},{"file":"/var/www/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php","line":780,"function":"resolveSharesForRecipient","class":"OCA\\Deck\\Sharing\\DeckShareProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1407,"function":"getSharedWith","class":"OCA\\Deck\\Sharing\\DeckShareProvider","type":"->"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php","line":99,"function":"getSharedWith","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":134,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SetupManager.php","line":226,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SetupManager.php","line":318,"function":"OC\\Files\\{closure}","class":"OC\\Files\\SetupManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/SetupManager.php","line":227,"function":"setupForUserWith","class":"OC\\Files\\SetupManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":111,"function":"setupForUser","class":"OC\\Files\\SetupManager","type":"->"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareController.php","line":673,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"downloadShare","class":"OCA\\Files_Sharing\\Controller\\ShareController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1053,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Group/Manager.php","Line":327},"CustomMessage":"--"}}`

**Comment by Pietro-Aretino** [comment]
If it can be of use to anyone, the only way I was able to fix my issue was downgrading to Deck 1.8.5.
Make a backup of your Nextcloud and make a backup of your DB before making any of these modifications.

    You can download older versions of Deck here: https://apps.nextcloud.com/apps/deck/releases?platform=25#25
    Login to your Nextcloud server as an admin and disable the Deck app.
    SSH into your Nextcloud server, go to your apps directory (/var/www/nextcloud/apps/)
    Move the folder "deck" somewhere else /home/ or /root/ or anywhere else, no need to delete, just in case something goes wrong, you can plop it right back.
    Download and extract the 1.8.5 version of deck from the aforementioned link
    Move the 1.8.5 deck folder to the same location /var/www/nextcloud/apps/
    Give the the same user rights and permissions "chown -r www-data:www-data deck/"
    Log back into your Nextcloud server and now Enable Deck, you should see your Nextcloud server telling you to update the Deck app.

I tested my link shares and the Deck app and both of them are now functioning correctly.

If you have a cron job to auto-update apps and what not, ensure to disable that.

**Comment by juliushaertl** [comment]
I backported a fix to https://github.com/nextcloud/deck/pull/5595, testing is very welcome

**Comment by juliushaertl** [comment]
Has been released
