### ISSUE TITLE
Deck Card can't be moved to other board.

### ISSUE THREAD

**Issue by djaniol** [nextcloud/deck#5538]
Debian 11 all updated

Test Case:
1. open board
2. select card
3. go to card menu
4. chose different different member
Manu is closed by it self. Not possible to get to chose board in the menu.
Severity: always

**Comment by stefan-niedermann** [comment]
Fill out the issue template, it is there for a reason.

**Comment by enbata** [comment]
I just see this pull request: https://github.com/nextcloud/deck/pull/5537

related #5404

**Comment by stefan-niedermann** [comment]
I agree. Given the original poster didn't respond, I'll close this issue.

**Comment by djaniol** [comment]
Thank you guys, that was super fast response!
