### ISSUE TITLE
horizontal scrolling broken on Nextcloud 14 beta

### ISSUE THREAD

**Issue by schiessle** [nextcloud/deck#560]
I just tried the deck app with Nextcloud 14beta1 on c.nc.com and noticed that I can't scroll horizontally if I have more stacks then what fits on the screen

Maybe because of https://github.com/nextcloud/server/pull/9982 ?

**Comment by juliushaertl** [comment]
Thanks, yes seems there is still something broken, scrolling works, but the scrollbar is not visible.

**Comment by juliushaertl** [comment]
Seems to work fine on master, so it has probably been fixed with https://github.com/nextcloud/server/pull/10421

Let's wait for beta2 and see if it works.

**Comment by rullzer** [comment]
Beta2 is out :)

**Comment by juliushaertl** [comment]
Yes works as expected for me now with both releases.
