### ISSUE TITLE
Add a new "Add card button" at the top of the columns

### ISSUE THREAD

**Issue by philippe-levan** [nextcloud/deck#562]
**Is your feature request related to a problem? Please describe.**

When you have a lot of cards in a column, you have to scroll down to add a new card.
If you want your card to be at the top of the column, you have to move it manually to the top.

**Describe the solution you'd like**

We could add a new "add card button" at the top of a column that would add a card at the top of the column.
(the "add card button" at the bottom would remain unchanged)

**Describe alternatives you've considered**

The button could be a "+" button on the right of the card title => no space lost at the top of the column, but a little more dev and this is different than the button at the bottom.

The button could be a "+" identical than the botton at the bottom. => space lost at the bottom, but the UI remain completely coherent.

**Additional context**

![image](https://user-images.githubusercontent.com/393066/43447338-94554678-94ab-11e8-89ff-355ae2d2c7e1.png)

**Comment by bpcurse** [comment]
Please have a look at #399 and #404

**Comment by juliushaertl** [comment]
Yes, lets continue discussing that in #399
