### ISSUE TITLE
deck card descriptions sometimes are not saved

### ISSUE THREAD

**Issue by fferri** [nextcloud/deck#5628]
It was hard to track down this problem, as it happened only on one computer randomly.

This is what it happens:
- user modifies the card description
- the change is not recorded sometimes (I can see this by the fact under the card title it still says "modified minutes ago" or more in the past, while when it is saved it changes to "modified seconds ago")
- the user closes the card edit window (at this point the entered information is lost without any notice! it should prevent closing the window if the information has not been saved yet, no? also #5627 would help mitigate...?)
- when the user reopens the card window, he will see the old description (only in the case the save failed in the previous step)

I could not notice any error relevant to this in the JS console.

There are no other issues with the underlying data, e.g. if the change is recorded (i.e. the last changed date updates, the change shows in the changes timeline) then for sure it is not lost.

But the problem is that the change to description sometimes is not picked up, so the automatic save is never triggered (or it is triggered, but never succeeds, I can't really tell), and the entered information is lost.

Modifying other fields (e.g. label, comments) seems to be more reliable, I have not observed this issue in modifying other fields.

Deck app version is latest 1.11.4
Nextcloud 27.1.5 Enterprise

**Client details:**
 - OS: Windows
 - Browser: issue happened with multiple browsers: Edge, Chrome
 - Device: desktop

Tried also to disable browser extensions, but same result.

The cause of the not-triggered save might be a simple network lag or a lost protocol message (just a wild guess...) but the fact this makes so easy to lose the entered information is perhaps the most critical aspect of this.

I tried to wait longer after changing the description field: sometimes it eventually saves, and some other times it never saves.

**Comment by gnilebein** [comment]
I can confirm this if you create a map using the "N" shortcut. The cards are created without a description.

The "Save" text never disappears.


![2024-03-05 20_18_47](https://github.com/nextcloud/deck/assets/2871059/6d62745a-70c6-47e1-9753-8eecd7c9ad63)

**Comment by bullet92** [comment]
I want to add that the very same issue happens to me with latest nextcloud 28.0.4 and deck 1.12.2
Replicate the issue is simple: write fast and use enter
If you end your sentence with enter, the file will never be saved.
