### ISSUE TITLE
Nextcloud Files integration

### ISSUE THREAD

**Issue by schiessle** [nextcloud/deck#564]
Would be nice if I could not only upload new files as attachment but also select files which are already stored in my Nextcloud to connect then with a specific card.

## Updated specification:

* The user is able to upload a file as an attachment to a card.
* Files uploaded from local storage will be stored in a default folder, pre-defined by the user.
* The uploaded file will be shared with all users who have access to the board.
* If the owner of the uploaded file deletes it, it will be removed from the board and from all users storage.
* The user is able to select an already existing file from Nextcloud Files and attach it to a card.

## Mockups

Being able to attach files to a card, either by choosing an existing file from the Nextcloud files app or by uploading a new one.

![image](https://user-images.githubusercontent.com/1589737/75150914-c0d72680-5705-11ea-8d9f-88a936abe9b2.png)
The sidebar of a card will have an "Attachments" tab which will enable the user to upload files from the local storage and attach it to a card or to attach a file which was already uploaded to Nextcloud

![image](https://user-images.githubusercontent.com/1589737/75150919-c6cd0780-5705-11ea-8d9c-291935c4c544.png)
A file picker will enable the user to attach a file which already exists in Nextcloud, to a card 

![image](https://user-images.githubusercontent.com/1589737/75150931-cdf41580-5705-11ea-9997-936a119ca91a.png)
The user will be able to jump to the file directly ("Show in files")

**Comment by juliushaertl** [comment]
Yes, definitely. There are some things that need to be discussed. It doesn't seem to be easily possible with the current share API the server provides, therefore i opened https://github.com/nextcloud/server/issues/10292. 

- Files should somehow be accessible by all users who have access to the board
  - Should they just show up in the home directory or in a deck specific subfolder
- Files need to be editable by all users who have write access to the board
  - How would editing with collabora/other apps be achieved?
- In case there is public board sharing (#14), how is the file being made accessible to guest users

**Comment by schiessle** [comment]
True, didn't thought about shared boards. Maybe you could use the existing share api to automatically share the file/folder with all users to who the board is shared.

**Comment by shashankmc** [comment]
Started using deck a couple of days ago, and this feature is definitely useful. Hoping to see this feature! :)

**Comment by soerpoers** [comment]
yeah – should be possible. We want to use it in our team instead of trello, but this feature is missing. yes we know, we can go to the file and copy the share link but it's not pretty elegant. Is it possible to show this window of copy the link to share it?
i would help but haven't any skills in programming with API's :(

**Comment by tjareson** [comment]
Is that feature still planned? I just got stuck with that as well in NC18. 
Other apps like mail are supporting it. Would make it the activity cards approach more complete, as at least in our case quite often a document or concept is one of the results of such acitivities. So an easy reference of it would be great.

**Comment by tobealive** [comment]
![talk-nexcloud-files](https://user-images.githubusercontent.com/34311583/77907068-4f047680-7289-11ea-8301-1543f4010e89.jpg)

the nextcloud talk app supports it too. Maybe there are some revelations the get from looking into their coding approach.

**Comment by juliushaertl** [comment]
Yes, our plan is to do this like it is implemented in talk. I've updated the first post with our spec that was defined during the last contributor week.

**Comment by q-wertz** [comment]
> Yes, our plan is to do this like it is implemented in talk. I've updated the first post with our spec that was defined during the last contributor week.

One thing that is missing, is the question if already existing files:
1) will only be able to be seen by the people that the file is shared by nextcloud itself
2) the file permission is changed such that each participant of the board has e.g. read access
3) the board members that have no access to the file cannot see it
4) the file is additionally moved to the hidden folder and users that have no direct access to the file can view it from there (-> maybe bad solution as the file has to be kept in sync with the "original" file)
5) promt to decide between e.g. 1) & 2) & 3) of the above solutions during linking process

**Comment by putt1ck** [comment]
I would strongly recommend 1 & 2 as options, with 1 as default and where 2 is implemented like the "share link" function - and equally respects advanced permissions in group folders i.e. will tell the person trying to share via a deck attachment that they do not have permission to share the file.

**Comment by miguelsan** [comment]
I would like having a config option in a board, whether its attachments should follow policy 1 (current file permissions) or 2 (shared with the board), being 1 the default, as most restrictive. This could be then changed on a file basis. Perhaps simply implemented as a yes/no tick "share with the board" for the file owner.

**Comment by putt1ck** [comment]
I think a file owner can already set permissions. But many files in an organisation will be shared to users without them being granted permission to reshare, and Deck cannot be allowed to override that permission or it breaks the security model.

**Comment by metbril** [comment]
How different is this from the current feature where I can link the selected card to another card, board or file from the details pane? Referred to as "projects".

**Comment by aktivde** [comment]
Quite different, because a project creates a nextcloud-wide project entry that apps can access. Assuming that would be the case for more than a few cards, the project search would become a total mass very quickly. 

The project link is a solid workaround though before this is implemented. If you don't want to screw up your project search you can also attach the internal link to a file in the description.

**Comment by llucax** [comment]
A first iteration of this feature that might be much easier to implement is to add a "nextcloud file import" option. So the file will still be duplicated when added to the card, but at least I don't have to download the file from nextcloud to my filesystem and then upload it again to the card. Saves bandwidth, time and it is more convenient.

**Comment by juliushaertl** [comment]
@jancborchardt @Clementine46 I've also created two very quick mockups of how the sharing part could look like from the files app. As discussed we have two options here, from my point of view the last one makes most sense as otherwise users will end up with their sharing auto complete being filled with tons of cards.

## Option 1: Show results of cards to share with immediately in the sharing input

![image](https://user-images.githubusercontent.com/3404133/100865585-cc772b00-3497-11eb-81fc-2a291619cd0c.png)

## Option 2: Only show one entry and let the user pick the card to share with in a modal


![image](https://user-images.githubusercontent.com/3404133/100865450-a2256d80-3497-11eb-80d8-801b5cf378a8.png)
![image](https://user-images.githubusercontent.com/3404133/100865754-0e07d600-3498-11eb-9576-8abbc457f35d.png)

**Comment by juliushaertl** [comment]
From our design call:
- Rename actions to **Upload new files / Share from Files** as in talk

**Comment by Clementine46** [comment]
> Being able to attach files to a card, either by choosing an existing file from the Nextcloud files app or by uploading a new one.
> 
> ![image](https://user-images.githubusercontent.com/1589737/75150914-c0d72680-5705-11ea-8d9f-88a936abe9b2.png)

For wording, maybe "Upload new file" and "Attach from files" would be better. It's easier to understand and more consistent with the rest of Nextcloud.

**Comment by juliushaertl** [comment]
Implemented with https://github.com/nextcloud/deck/pull/2638 follow up fixes collected in https://github.com/nextcloud/deck/issues/2698

**Comment by compumatter** [comment]
Needing this feature right now.  Does anyone know the rough expected release date on this feature?

**Comment by juliushaertl** [comment]
1.3.0 will be released for Nextcloud 21+ but you can of course already run the beta releases of the server and deck app in case you want to help testing this.

https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule#nextcloud-21
