### ISSUE TITLE
Deliver due date notifications only to assigned users

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#566]
**Is your feature request related to a problem? Please describe.**
If a card has a due date, notifications about a passed due date are displayed to all board users, even if they aren't assigned to it.
With many cards and users this can be annoying, some kind of filtering or additional notification option seems to be a probable solution.

**Describe the solution you'd like**
If a card has a due date *and* at least one user assigned to it, the notification should only be displayed to the assigned user(s).

**Additional options to consider**
- Make this setting customizable under "settings".
- Allow to tag due dates on cards as "do not notify"

**Comment by bpcurse** [comment]
I would like to give some additional feedback on this issue from a larger project using deck.

We have multiple stacks and many cards with due dates and a lot of users working on it.
The problem we have encountered is that the due date notification load on the single user gets quite high as most of the notifications are not specific to the individual users and they don't (have to) care about the cards mentioned.
As this flood of unspecific notifications annoys our users, they are finally turning off notifications for deck, hence missing the due dates on cards they were assigned to :(

My recommendation is to give this issue a higher internal priority as this probably is pretty relevant and important for the usability in many larger projects.

**Comment by joshtrichards** [comment]
FIxed in #2430
