### ISSUE TITLE
Missing indicator in board view if more than 3 users are assigned to a card

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#567]
**Is your feature request related to a problem? Please describe.**
If there are more than 3 users assigned to a card there is no way to tell in board view. One has to open the card to see it.

**Describe the solution you'd like**
Indicate somehow that there are more users assigned than displayed.

- Show a "+" sign in the third user icon if there are more than 3 users assigned.

**Alternatives**
- Make user icons overlap horizontally probably up to 5-6 users than show a "+" sign or another indicator.
- Dynamically? reduce icons in size, maybe display them in two rows.
- Combine these two.

Any other ideas how to do this neatly?

**Comment by juliushaertl** [comment]
> Make user icons overlap horizontally probably up to 5-6 users than show a "+" sign or another indicator.

That would actually be the direction I'd go. Maybe use a 3-dots indicator and show them in a popover then, because a + would always indicate that you can add more on click.

**Comment by jakobroehrl** [comment]
as described here: 
https://github.com/nextcloud/deck/issues/938#issuecomment-526928568

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master.
