### ISSUE TITLE
Card - Incorrect element placement

### ISSUE THREAD

**Issue by johanneskopf** [nextcloud/deck#5681]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**
1. Go to Deck
2. Click on a board (or create a new one)
3. Click on a card (or create a new one)

**Expected behavior**
The card header tab-bar should be shown on top of the card and the content of any tab below the header tab-bar.

**Screenshots**
![image](https://github.com/nextcloud/deck/assets/13490371/79374697-1a07-44eb-a5e9-2085101a02c1)

**Client details:**
 - OS: Windows 10
 - Browser: chrome
 - Version: 123.0.6312.59 (Official Build) (64-bit)
 - Device: desktop

**Comment by johanneskopf** [comment]
Today it mysteriously started working again (the issue was the same on two clients). No need for switching the theme from dark theme to light theme. I wonder what caused this.
Thanks for the suggestion though @user8446 , would have made sense that this could be a possible solution!

**Comment by juliushaertl** [comment]
As far as I know this was caused and fixed by an update of the calendar app

**Comment by johanneskopf** [comment]
Thanks for the clarification @juliushaertl . I'm glad that the problem was solved so quickly!
