### ISSUE TITLE
Tag colour does not change immediately

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#570]
**Describe the bug**
After having edited a tag by setting a new colour, the tags on the cards are not immediately updated.
It is necessary to reload the page, open the board details again or click once on all affected cards.

**To Reproduce**
1. Tag a card with tag x
2. Go to board-details and edit tag x
3. Change tag colour
4. Confirm change
5. Exit board-details
6. Tag still shows the old colour

**Expected behavior**
Tags should be updated on all cards once the change is confirmed.

**Client details:**
 - Browser Firefox
 - Version 61.0.1
 - Device: Linux Desktop PC

**Nextcloud version:** (see Nextcloud admin page)
13.0.5, Deck 0.4.1

**Comment by henning** [comment]
Maybe related to this: 

I just experienced the issue that after adding tags, and editing them to change their color, some tags at first did show up "properly" as expected. But suddenly i added a card and the color of the tag didn't show up. I did a full reload of the page/deck - and now all colors for tags disappeared completely. No tag had the previously selected and configured color. In the edit tags dialogue, all my new added custom tags where white.
