### ISSUE TITLE
Template enhancement

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/deck#576]
**Is your feature request related to a problem? Please describe.**
I don't like the sidebar It use to much space on my small monitor. In different situation I need different views.

**Describe the solution you'd like**
View Button:
![grafik](https://user-images.githubusercontent.com/7795891/43971136-44c68cca-9cd0-11e8-8eb3-920a1b4533a4.png)

TaskList view:
![grafik](https://user-images.githubusercontent.com/7795891/43971119-350b8d9e-9cd0-11e8-9b12-d90fe9926a34.png)

**Comment by juliushaertl** [comment]
Let's merge this with https://github.com/nextcloud/deck/issues/587 since the request is kind of similar.
