### ISSUE TITLE
Checklist items are not stable marked

### ISSUE THREAD

**Issue by linuxpete** [nextcloud/deck#577]
**Describe the bug**

- I have cards in which I have made a checklist, and this card is put in a stack. 
- When I mark these checklist items "done" the card shows this in the summary in the Stack (see picture stack1.png
![stack1](https://user-images.githubusercontent.com/7695965/43994717-08a5729c-9da2-11e8-96c2-5ef1955720ea.png)
- When I move the card between stacks the checked items become unchecked
![stack2](https://user-images.githubusercontent.com/7695965/43994728-23760ef6-9da2-11e8-8aa2-2d9ea9376b4f.png)
- This behavior is consistent in the deck I show in the pictures

- The card content is like : 
![stack4](https://user-images.githubusercontent.com/7695965/43994744-5990206c-9da2-11e8-83a2-7d8d3367a71d.png)

![stack3](https://user-images.githubusercontent.com/7695965/43994751-711d93c2-9da2-11e8-9729-433b9f4215e5.png)

- Using another account (admin) this problem seems not to show up but this could be because of too few decks.

**To Reproduce**
1. Make a Deck
2. Make some Stacks
3. Make a Card and in this card make a checklist
4. Check all items
5. Move card from Deck 1 to Deck 2 after moving one or more checkboxes are unchecked.

**Expected behavior**
Marked checkboxes stay marked and vv

**Screenshots**
See description above

**Deckversion**
 - deck: 0.4.1

**Client details:**
 - OS: Ubuntu 16.04.5
 - Browser  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
 - Version : 60
 - Device: desktop

## Server configuration detail

**Operating system:** Linux 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64

**Webserver:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 5.7.23

**PHP version:** 7.0.30-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.5 - 13.0.5.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - apporder: 0.5.0
 - audioplayer: 2.3.1
 - bookmarks: 0.11.0
 - bookmarks_fulltextsearch: 0.8.0
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.1
 - checksum: 0.4.0
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.7
 - deck: 0.4.1
 - dicomviewer: 0.0.6
 - dropit: 0.1.1
 - encryption: 2.0.0
 - end_to_end_encryption: 1.0.5
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_external_dropbox: 1.0.0
 - files_external_gdrive: 0.2.8
 - files_fulltextsearch: 0.8.2
 - files_fulltextsearch_tesseract: 0.1.0
 - files_markdown: 2.0.4
 - files_opds: 0.8.8
 - files_pdfviewer: 1.2.1
 - files_reader: 1.2.3
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trackdownloads: 1.2.2
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - flowupload: 0.0.7
 - fulltextsearch: 0.8.1
 - fulltextsearch_elasticsearch: 0.8.0
 - gallery: 18.0.0
 - gpxedit: 0.0.8
 - gpxmotion: 0.0.6
 - gpxpod: 2.2.2
 - impersonate: 1.0.4
 - issuetemplate: 0.3.0
 - keeporsweep: 0.1.6
 - ldaporg: 1.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - mindmaps: 0.1.0
 - music: 0.9.0
 - news: 12.0.4
 - nextcloud_announcements: 1.2.0
 - notes: 2.4.0
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - ocdownloader: 1.5.6
 - passman: 2.1.4
 - password_policy: 1.3.0
 - previewgenerator: 1.1.0
 - provisioning_api: 1.3.0
 - qownnotesapi: 18.8.0
 - quicknotes: 0.1.3
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.2.5
 - spreedme: 0.3.11
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "oc.**********.nl"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "oc.**********.nl",
    "dbtype": "mysql",
    "version": "13.0.5.2",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "loglevel": 0,
    "defaultapp": "apporder",
    "knowledgebaseenabled": "true",
    "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' data: blob:; frame-src *; img-src *; font-src 'self' data: blob:; media-src *",
    "maintenance": false,
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "data-fingerprint": "tytttttt",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\Epub",
        "OC\\Preview\\PDF",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\StarOffice",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\FB2"
    ],
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by laurentiu2** [comment]
I can confirm the problem. When marking in checklist, I can see Autosave working, but then when I leave the card and return afterwards, some other items appear marked/checked, not the one I marked initially.

**Comment by juliushaertl** [comment]
I might have an idea where this is goin wrong. Can you check if it works fine, if you click the checkbox instead of the label text besides it?

**Comment by nrgeen** [comment]
Normally I click on the checkboxes and have the same problem. So I can't confirm that it works reliably with this approach.

**Comment by ashgoodman** [comment]
still occurs

**Comment by aeph6Ee0** [comment]
The **deep copy** in following two lines looks suspicious:
https://github.com/nextcloud/deck/blob/6754cfe73bbbae388742bbc0664fa1fd09bcc09d/js/controller/CardController.js#L103
https://github.com/nextcloud/deck/blob/6754cfe73bbbae388742bbc0664fa1fd09bcc09d/js/controller/CardController.js#L144
