### ISSUE TITLE
Optional parameter $userId declared before required parameter $path is implicitly treated as a required parameter at /var/www/apps/deck/lib/Service/ConfigService.php#234

### ISSUE THREAD

**Issue by snetat** [nextcloud/deck#5793]
After the update to nextcloud 29 the following is written to the logfile every minute:

`Optional parameter $userId declared before required parameter $path is implicitly treated as a required parameter at /var/www/apps/deck/lib/Service/ConfigService.php#234`

**List of activated apps:**
...
user_external ?

**Comment by PrzemekSkw** [comment]
> Thanks for reporting, fix is in #5794
Can You expalin please?
I don't see any fix there.
Regards.

**Comment by janomat** [comment]
I received the error message mentioned above with every run of the cron jobs aftwer upgrading to NC 28.0.7 today.

Line 234 in  /apps/deck/lib/Service/ConfigService.php needs to be edited. 

Described here [fix: Avoid optional before required parameter #5794](https://github.com/nextcloud/deck/pull/5794/commits/cf89d4d1c89823954f218b2d09833efc261f07fa)

After editing ConfigService.php the error logs are clean.

**Comment by snetat** [comment]
Update your deck app to 1.13.1

### Fixed
 - fix: Adjust dependencies to fix filepicker #6038
 - Fix npm audit #6028
 - Fix npm audit #6001
 - fix: Avoid optional before required parameter #5820
 - fix: permission check for cloning board #5853
