### ISSUE TITLE
Prevent duplicate tag names

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/deck#586]
**Describe the bug**
I am able to create duplicate tags (identical in spelling, capitalization etc) for the same board

**To Reproduce**
1. Create tag for a board
2. Create another tag for the same board with an identical name

**Expected behavior**
A warning message that the tag already exists for that board

**Comment by juliushaertl** [comment]
Makes sense, however this is nothing to urgent. Thanks for reportin :+1:

**Comment by ashgoodman** [comment]
Yep, I understand.

Glad to help improve the project!
