### ISSUE TITLE
Card Title can be empty and hence not be edited anymore

### ISSUE THREAD

**Issue by fpetry** [nextcloud/deck#589]
**Describe the bug**
If I create a card and then click it and edit the title  to an empty string on the right, I cannot edit it afterwards because of the way it is displayed (field gets smaller and cannot be clicked anymore)

**To Reproduce**
1. Click the big "+" to create a new card
2. Write anything as title
3. Click the card and edit the title to an empty string
4. Click somewhere out of the edit field (Pressing enter pops up a message that the field should not be empty)
5. Click the card again
6. The edit field is much smaller and cannot be written to

**Expected behavior**
The title before the edit should be restored

**Screenshots**
![screenshot_20180816_153859](https://user-images.githubusercontent.com/4649876/44212434-a95fca80-a16b-11e8-8014-bc24907e3848.png)
![screenshot_20180816_154147](https://user-images.githubusercontent.com/4649876/44212436-ad8be800-a16b-11e8-9144-4ad64c0f1851.png)
![screenshot_20180816_154611](https://user-images.githubusercontent.com/4649876/44212441-afee4200-a16b-11e8-8b09-67225b1b0b66.png)

**Client details:**
 - OS: Kubuntu 18.04
 - Browser Chromium 
 - Version:  68.0.3440.75  
 - Device: desktop

**Comment by fpetry** [comment]
It also works if you just write a " " when creating the card.

**Comment by weeman1337** [comment]
I'll have a look at this.

**Comment by matchish** [comment]
Regression bug in `1.0.1` version. Do I have to open a new issue or it's ok to continue here?

**Comment by juliushaertl** [comment]
Ideally please open a new issue, but let's keep this for now

**Comment by juliushaertl** [comment]
@jakobroehrl Make something small for you :wink:
