### ISSUE TITLE
Description cannot be saved when creating new card with 'n' shortcut

### ISSUE THREAD

**Issue by fracklaus** [nextcloud/deck#5908]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When creating a new card in nextcloud deck browser interface using the 'n' shortcut, the field of the description does no longer get saved. It states "saving...", but does never reach the saved state.
This issue occurs since I upgraded to nextcloud 29.0.1.1, before, the feature used to work normally. 

**To Reproduce**
1. Install nextcloud 29.0.1.1 with deck
2. open a deck in the browser
3. Press 'n' to create a new card
4. Give the card a title, and enter a description
5. Note how the description gets stuck in "saving..."
6. Click "save" to save the card
7. New card is created with empty description

**Expected behavior**
Description is saved correctly and is part of the card

**Client details:**
 - OS: Windows 11
 - Browser: firefox 
 - Version 115.11 esr

<details>
<summary>Server details</summary>

**Operating system**: Debian bookworm

**Web server:** apache

**Database:** postgresql

**PHP version:** 8.2.18

**Nextcloud version:** (see Nextcloud admin page) 29.0.1.1

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here:

No errors have been found.

```

**Are you using an external user-backend, if yes which one:** Active Directory

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Nothing relevant in the nextcloud logs.
```

#### Browser log
Apache access log shows this line when trying to save the card in the editor that opens with 'n':
```
192.168.YYY.XXX - - [24/May/2024:11:01:24 +0200] "PUT /index.php/apps/deck/cards/undefined HTTP/1.1" 400 1257 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
```

</details>

**Comment by joshtrichards** [comment]
I'm unable to reproduce this behavior today. Are you still experiencing this in current versions?

**Comment by fracklaus** [comment]
Works for me in latest nextcloud release - the bug can be closed.
