### ISSUE TITLE
Fixed deck headlines

### ISSUE THREAD

**Issue by lllHuber** [nextcloud/deck#595]
When there are many cards on one deck and it's needed to scroll down the screen, the headlines of the decks scroll out of the screen as well. It becomes difficult to see which cards are on which deck.
It would be wonderful if the headlines were fixed to keep a good overview of which card is on which deck.

**Comment by juliushaertl** [comment]
@lllHuber Thanks for reporting. We already have https://github.com/nextcloud/deck/issues/399 for this, so I'm closing this as a duplicate.
