### ISSUE TITLE
After updating to version 29.0.2: INVALID_HASH Error

### ISSUE THREAD

**Issue by gmt-it** [nextcloud/deck#5970]
Hello.

After updating to version 29.0.2, nextcloud, I encountered the following error:

> 

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- deck
	- INVALID_HASH
		- lib/Service/ConfigService.php

Raw output
==========
Array
(
    [deck] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/Service/ConfigService.php] => Array
                        (
                            [expected] => 6ca8ed032cedd45cdce550d602a07f535ae17d7a7145ed3d7fd6557491ef8537d71a056a12e258c99e2f57dc188f0f1f237a150774cdc561038a5cde128b1c80
                            [current] => a257604480fafd249dc2ba7ca2f796de714d24faa45f19eddf5b476f4a6d5ff96f8d683f852ab5e0491b194e9f073eb62c9c7e42574dbfa8c5bffbf54db2ce3d
                        )

                )

        )

)

**Comment by joshtrichards** [comment]
The hash of the distributed file is correct and matches the one mentioned. Perhaps you manually patched Deck at some point?

**Comment by gmt-it** [comment]
Yes, that's it. How do I get rid of the message?

**Comment by joshtrichards** [comment]
You either remove the manually patch or ignore the warning until the next release. :-)
