### ISSUE TITLE
Optional parameter $userId declared before required parameter $path is implicitly treated as a required parameter

### ISSUE THREAD

**Issue by ibahnasy** [nextcloud/deck#5983]
There are so many errors logged with the below message:
```
[PHP] Error: Optional parameter $userId declared before required parameter $path is implicitly treated as a required parameter at /var/www/nextcloud.kernelone.com/apps/deck/lib/Service/ConfigService.php#234
	GET /apps/logreader/api/poll?lastReqId=
	from 10.2.1.6 by ncadmin at Jun 8, 2024, 9:41:50 AM

```

<details>
<summary>Server details</summary>

**Operating system**: Ubuntu 22.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 8.1

**Nextcloud version:** 29.0.1

**Where did you install Nextcloud from:** TAR

**Comment by stefan-niedermann** [comment]
> Please search the existing issues first, it's likely that your issue was already reported or even fixed.

Did you? Yes? Please do not delete issue templates. *Read* them. *Fill* them out.
