### ISSUE TITLE
Problem with sharing the files from the files of nextcloud ...

### ISSUE THREAD

**Issue by Farhat-WP-Developer** [nextcloud/deck#6012]
I am using the latest version **(1.13.0) of deck** and also latest version of **Nextcloud (29+)** on my server but now when i try to add attachment to the deck card it is working when i try to upload from my device but not working and just showing loading blue window when try to choose from my existing nextcloud files.

Thanks!
![Screenshot from 2024-06-20 16-20-22](https://github.com/nextcloud/deck/assets/91801926/cacb2854-ce19-402b-a4cc-39c340a97349)
![Uploading Screenshot from 2024-06-20 16-24-46.png…]()

**Comment by StefInP** [comment]
@Farhat-WP-Developer it seems to be related with #5822

**Comment by niclasheinz** [comment]
This problem has been solved in the new deck version 1.13.1 :tada:. Let me know if the file browser works for you now.

**Comment by Farhat-WP-Developer** [comment]
Yeah in updated version it is resolved thanks!
