### ISSUE TITLE
Clone a Card

### ISSUE THREAD

**Issue by BeFreeNowHere** [nextcloud/deck#6014]
New Feature:

I want to be able to copy a card.
But this feature is missing in the menu:
![Bildschirmfoto vom 2024-06-21 17-59-56](https://github.com/nextcloud/deck/assets/69630826/bc7a68ca-7983-47eb-964f-99469e6088aa)
This would be so important, if you have
a lot of information in a card that does
not change for other cards.

This should be very easy to implement.

Thanks for Deck
Best regards

Patrick

**Comment by stefan-niedermann** [comment]
Please use the search function before opening new issues.
