### ISSUE TITLE
Display tag (colors) in compact mode

### ISSUE THREAD

**Issue by weeman1337** [nextcloud/deck#603]
As an user I want to see the colors of the tags at the card in compact mode,
so I know which tags are assigned to the card.

Followup to #587, #602

**Comment by corpuslinea** [comment]
Hi this is class we want to edit and organize our processes in Nextcloud
How can I visualize and edit this on the go with the app?

**Comment by bpcurse** [comment]
+1 @weeman1337: The display of "old / pre 0.5.0" style tags in compact mode would be nice.

**Comment by rhersel** [comment]
I agree that colored cards in compact mode would be much appreciated. Currently the compacted cards don't carry any color information. I suggest two different approaches:
1. Enable background color assignment per card (users may use it for whatever they want)
2. Use color of the first tag of the card to set the background color of that card.

**Comment by fmorato** [comment]
I don't think the card should have as a background the color of a tag. The tags could be displayed as small badges without text below the text of the card, perhaps without adding extra spacing to the card size.

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master

![image](https://user-images.githubusercontent.com/3404133/73119467-8fcad100-3f62-11ea-9c20-c3cff4fc0ca6.png)
