### ISSUE TITLE
Feature request: "Deck" attachement folder with same structure as decks, not in root

### ISSUE THREAD

**Issue by turnschuhadmin1337** [nextcloud/deck#6037]
Hi there,

I was wondering if it's possible to create folders under the "Deck" folder of the Nextcloud-structure.

Right now:
All attachements are directly under "/Nextcloud/Deck/" and it's getting a bit chaotic now if you like to edit the one of the many attachements on a PC synced with Nexctloud-client. We're using it like a "ticket-system" for some construction works (e.g. list "roof"/card "chimney", list "kitchen"/card "floor", etc.) of our project.

Request:
To create a folder vor every new list and card.
e.g. folder structure like inside the Deck-App (Web/Android)
/Nextcloud/Deck/List1/card1
/Nextcloud/Deck/List1/card2 etc.
or with example above:
/Nextcloud/roof/chimney/

/Nextcloud/Deck/List2/card1
/Nextcloud/Deck/List2/card1 etc.
or with example above:
/Nextcloud/kitchen/floor/

Hope it's possible and not too much work. Would be awesome.
Thanks so much.

**Comment by stefan-niedermann** [comment]
Please search for existing issues before opening new ones.

https://github.com/nextcloud/deck/issues/3244

**Comment by turnschuhadmin1337** [comment]
Ah, sorry. Couldn't find it that way. Thanks
