### ISSUE TITLE
Integrate with Mail app so email can be linked to from card

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/deck#605]
**Is your feature request related to a problem? Please describe.**
It would be nice if a card could have a link to email(s) related to it

**Describe the solution you'd like**
Add another attachment option: attach email, that lets you select an email((s) from the Mail app to link to from the card. Cicking the link should take you to that mail in the Mail app

Granted given the mail app isn't really production ready maybe this feature will have to wait a while, plus the mail app only seems to retrieve a few messages, and doesn't do a full search of ALL mails on your mail sever. So maybe this is just wishful thinking?

**Describe alternatives you've considered**
Copying email content to the card. But linking the email would be quicker if it were possible

**Comment by juliushaertl** [comment]
Thanks for your feature request. 

This is another use case for https://github.com/nextcloud/server/issues/11015

**Comment by juliushaertl** [comment]
Closing in favor of #810
