### ISSUE TITLE
Recurring tasks

### ISSUE THREAD

**Issue by RobTranquillo** [nextcloud/deck#6058]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
It is an extension of the deck's abilities. Because I would like to divide recurring tasks that occur in households, such as cleaning the bathroom, vacuuming, shopping, etc., among the household members and display them when they have been completed in a period of time, e.g. once a week.

**Describe the solution you'd like**
I would like Nextcloud Deck to support recurring tasks. Specifically, I would like tasks to be subject to a time-dependent automatism. For example, I would like a card containing a task to be automatically moved to a specific column every Sunday evening or given a specific status/day (e.g. todo). When the assigned person has completed the task, they move it to the corresponding column (done) or remove the tag.

**Describe alternatives you've considered**
I haven't thought of any alternative options yet, but of course I'm open to all ideas and suggestions. Unfortunately, I don't know Deck well enough to try it myself. But with a lot of support I would try to do it myself.

**Additional context**
/

**Comment by stefan-niedermann** [comment]
Ppease search for existing issues before opening new ones.

**Comment by RobTranquillo** [comment]
Sorry. I did, but while writing the issue the thing becomes clearer in my mind, but i don't searched one more time. So thank you for closing this.

If anyone ever comes across this site, this is the place to be: https://github.com/nextcloud/deck/issues/480
