### ISSUE TITLE
Devcontainer/Codespaces is not working anymore

### ISSUE THREAD

**Issue by ronau** [nextcloud/deck#6061]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
README suggests to use Devcontainer/Codespaces for developing: https://github.com/nextcloud/deck#github-codespaces--vs-code-devcontainer
However, if I start a Github Codespace or a Devcontainer in my VS Code, then the Nextcloud base is not installed properly.
In the bash logs I get this error message:

```
=======================================================================================
 🚨 Could not find a valid Nextcloud source in /var/www/html                                
 Double check your REPO_PATH_SERVER and STABLE_ROOT_PATH environment variables in .env 
=======================================================================================
```
I bet there are dozens of other way to setup a development environment. However, due to certain limitations on my computer, I cannot (or don't want to) install node/npm and others. So it would be nice to have the Devcontainer option working again.

**To Reproduce**
1. Fork the project and start a Github Codespace. Alternatively, clone the repo locally and start a VS Code Devcontainer
2. Wait for container initialization
3. See error message.
4. Open the container's HTTP port and see the "Installing container" page with just the error message from step 3.

**Expected behavior**
Nextcloud base is installed properly

I filed a bug already over in the [nextcloud-dev-container repo](https://github.com/juliushaertl/nextcloud-docker-dev/issues/316). However, I'm not sure if it's maybe just a config issue here regarding devcontainer setup.

**Comment by juliushaertl** [comment]
Should be all good again now (ref https://github.com/juliushaertl/nextcloud-docker-dev/issues/316)
