### ISSUE TITLE
Due date is cool, start date would be nice!

### ISSUE THREAD

**Issue by NikoKS** [nextcloud/deck#6066]
Since there is already a due date feature in deck, why not add the capability to add start date also?

![Screenshot 2024-07-02 at 17 55 50](https://github.com/nextcloud/deck/assets/24285511/5483042b-cb78-4d60-948f-9f8c21eee9e3)

Nextcloud Calendar already support this for their events.

Would be useful for creating gantt like charts in calendar.

**Comment by theWarFlower** [comment]
This would sell my team on it.

**Comment by juliushaertl** [comment]
Thanks for your suggestion, this is actually already tracked in https://github.com/nextcloud/deck/issues/3146
