### ISSUE TITLE
Setting a default board 

### ISSUE THREAD

**Issue by Rik44444** [nextcloud/deck#6067]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open Deck and it is not on the only Board I use but on Upcoming Cards

**Describe the solution you'd like**
I would like the ability to change in the Settings the default opening page of Deck to a specific Board

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by stefan-niedermann** [comment]
> I'm always frustrated when 

people don't search for existing issues before opening duplicates.

https://github.com/nextcloud/deck/issues/5130
