### ISSUE TITLE
Duplicate a project WITH cards, and duplicate cards inside a project

### ISSUE THREAD

**Issue by MLhx972** [nextcloud/deck#6086]
Hi, 
Please, could you add
- Duplicate a project WITH the same model of cards 
- Duplicate a model of cards into a project.
Lot of thanks !

Martine

**Comment by stefan-niedermann** [comment]
Hi,
Please, could you
- Fill out the issue template instead of ignoring it
- Search for existing issues before opening new ones?
Lot of thanks.

https://github.com/nextcloud/deck/issues/2797
