### ISSUE TITLE
Design review issues

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#6090]
This is a collection of design fixes that need to be done for the updated design in Hub 9 / Nextcloud 30.

- [ ] Verify that we migrate hardcoded 44px values to [the relevant css variables](https://help.nextcloud.com/t/css-variable-change-and-probable-regressions-in-apps/196999)
- [ ] Deck: Inputline half white half blue
  <img width="407" alt="24" src="https://github.com/nextcloud/deck/assets/3404133/9c45bf56-998d-4cf4-ab7d-c1748f21afec">
- [ ] Adjust header styles
  - [ ] Deck: Text size for Todo, Doing and Done too big compared with the rest of the UI 
    <img width="1523" alt="25" src="https://github.com/nextcloud/deck/assets/3404133/d615d605-724f-428a-83d8-0c6c0ce03e0e">
  - [ ] Deck: ‘Deleted items’ is cut and not readable. Text of ‘Deleted lists’ and ‘Deleted card’ is too big. 
    <img width="477" alt="27" src="https://github.com/nextcloud/deck/assets/3404133/d12fae1b-3ef5-4cbb-a271-74229ee12b7d">
- [ ] Deck: Card Details dialog has scrollbars. 
  <img width="1453" alt="26" src="https://github.com/nextcloud/deck/assets/3404133/2eb4ccc2-249d-4e9f-bd9d-27f55271532d">
- [ ] Deck: ‘...’ and + buttons are not aligned 
  <img width="1215" alt="28" src="https://github.com/nextcloud/deck/assets/3404133/581b40af-344d-4870-9696-2a12401808e0">

**Comment by alexanderdd** [comment]
maybe you can also consider this? https://github.com/nextcloud/deck/issues/6091
