### ISSUE TITLE
description edits not saved

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/deck#6112]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
I edited the description of a card for ~20mins on cloud.nextcloud.com Closed the card. Opened the card. The edits were not saved, I saw the old version from 20mins ago.

**To Reproduce**
cannot reproduce

**Expected behavior**
edits should be saved instantly and never lost

**Client details:**
 - OS: Linux Mint
 - Browser Firefox 128
 - Device: desktop

**Version:** 
NC 29.0.4 RC1
Deck Version I cannot find out. cloud.nextcloud.com

**Comments**
I thought it does not make sense to report if I cannot reproduce, but an employee encouraged me to still do it.

**Comment by janhack** [comment]
I experienced that description updates were most of the time not saved for NC 28.0.6 and Deck App 1.12.2, but occasionally it did work. I now upgraded to Deck App 1.12.4 and from testing it only shortly, description updates now seemed to be saved reliably for me.

**Comment by alexanderdd** [comment]
@joshtrichards I'm closing this, since it cannot be reproduced reliably. I just wanted to make engineers aware and have an issue about it in the repo.

Anyone who experiences this, feel free to reopen.
