### ISSUE TITLE
Copy a card with contents

### ISSUE THREAD

**Issue by Daybreakerflint** [nextcloud/deck#6131]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
We have many similar cards with the same process over and over and need to copy the cards to assign to different people to do. Now we need to manually create each card, copy the content and tags. So we can make those cards as easily as possible,

**Describe the solution you'd like**
In the dropdown menu of the card should be an option to copy a card with it's content. It then copies the exact same card in the same list.

**Comment by stefan-niedermann** [comment]
Please use the search function before opening new issues.

**Comment by stefan-niedermann** [comment]
https://github.com/nextcloud/deck/issues/1813
