### ISSUE TITLE
Configure attachement path

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/deck#6135]
Many other plugins have a configuration for the location of the folder where attachements are stored. Like here in in Calendar:
![Screenshot 2024-07-23 at 12-20-59 Juli 2024 - Kalender - plan neo cloud](https://github.com/user-attachments/assets/c4fc74a1-821d-49cb-9895-d6a00e1f6aa2)

It would be cool, if Deck offered the same settings and I could choose where files are stored.

Moreover it would be cool if the folder was hidden by default. See: https://github.com/nextcloud/server/issues/46309

**Comment by stefan-niedermann** [comment]
Please use the search function before opening new issues.

https://github.com/nextcloud/deck/issues/3176

**Comment by kaffeeringe** [comment]
I searched for "path" and scrolled through the results without finding this one. Didn't know you call it "location". 😉
