### ISSUE TITLE
Can't load decks into Android app

### ISSUE THREAD

**Issue by erahhal** [nextcloud/deck#6160]
**Describe the bug**
Logging into Deck on Android results in 2 or 3 decks out of 20 getting imported successfully, but then errors out. It appears to either be a timeout or one of the decks is causing problems.

The web interface for Deck works perfectly fine.

**To Reproduce**
1. Load android app
2. Select already logged in Nextcloud account
3. 2-3 decks are imported, then an error is thrown

**Expected behavior**
All decks imported and the app loads

**Screenshots/Data**

No errors found in Nextcloud logs

Error message on Android:

```
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.13.1
App Flavor: fdroid

Files App Version Code: 30290190 (PROD)

---

OS Version: 5.15.149-gcf9863dbdbf6(ba3a229cd9)
OS API Level: 34
Device: OP594DL1
Manufacturer: OnePlus
Model (and Product): CPH2451 (CPH2449)

---

it.niedermann.nextcloud.deck.exceptions.OfflineException: Connection rejected
	at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler$Handler.handle(ServerCommunicationErrorHandler.java:52)
	at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler.translateError(ServerCommunicationErrorHandler.java:28)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onFailure(RequestHelper.java:95)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)
```
**Client details:**
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Operating system**:

NixOS 24.05 + docker

**Web server:**

Docker + haproxy

**Database:**

Postgres 13.4 in Docker

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

Nextcloud Hub 8 (29.0.4)

**Where did you install Nextcloud from:**

Docker `nextcloud:latest`

**Signing status:**

`No errors have been found.`

**List of activated apps:**

Enabled:
  - activity: 2.21.1
  - breezedark: 28.0.0
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.14
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - cookbook: 0.11.1
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - fileslibreofficeedit: 1.1.0
  - firstrunwizard: 2.18.0
  - integration_google: 3.0.0
  - issuetemplate: 0.7.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - maps: 1.4.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tasks: 0.16.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - encryption: 2.17.0
  - files_external: 1.21.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - richdocuments: 8.4.3 (installed 8.4.3)
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0

**Nextcloud configuration:**

```
{
    "system": {
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud",
            "nextcloud.localdomain",
            "nextcloud.rahh.al"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "29.0.4.1",
        "overwrite.cli.url": "https:\/\/nextcloud.rahh.al",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance_window_start": 1,
        "default_phone_region": "US",
        "csrf.optout": [
            "\/Nextcloud-android\/"
        ],
        "loglevel": 0,
        "filesystem_check_changes": 1,
        "theme": "",
        "app_install_overwrite": [
            "breezedark",
            "issuetemplate"
        ]
    }
}
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No.

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
I went through the log file and there's nothing related to Deck there.
```

#### Browser log
```
Browser works perfectly. Android error message included above.
```

</details>

**Comment by juliushaertl** [comment]
As there are no server errors mentioned, please file this at https://github.com/stefan-niedermann/nextcloud-deck
