### ISSUE TITLE
Nextcloud 30 design issues

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#6164]
- [ ] List/column headings bottom of some letters are cut off
  <img width="360" alt="Screenshot 2024-08-02 at 13 04 00" src="https://github.com/user-attachments/assets/0ed20419-23d6-4b9c-b103-e8c5c254a077">
- [ ] Spacing between a list with scroll bar/no bar is different at the top
  <img width="360" alt="Screenshot 2024-08-02 at 13 04 00" src="https://github.com/user-attachments/assets/0ed20419-23d6-4b9c-b103-e8c5c254a077">
- [ ] Should the share icon be white like 3 dot menu -> Migrate to a vue-material-design-icon that picks up the text color
    <img width="121" alt="Screenshot 2024-08-02 at 13 03 52" src="https://github.com/user-attachments/assets/462ff59e-15fb-46e5-96a0-09e286228e41">
- [ ] Still have that issue with card's content being pushed to left.
  <img width="491" alt="Screenshot 2024-08-02 at 13 06 29" src="https://github.com/user-attachments/assets/d956af35-addd-4a0f-92eb-d83421ad2c06">
- [x] Board / upcoming card heading has wrong indent
<img width="339" alt="Screenshot 2024-08-02 at 13 06 52" src="https://github.com/user-attachments/assets/74220279-19a4-4d0a-beaa-522cab89fcb7">
<img width="442" alt="Screenshot 2024-08-02 at 13 06 47" src="https://github.com/user-attachments/assets/e1dfc72f-0083-4411-bbdf-17057ce7242b">

**Comment by viktorix** [comment]
A few additional styling issues:

1. Some cards with content have 3 scrollbars:
![image](https://github.com/user-attachments/assets/46a65dd5-80ea-4190-bcb7-e0c7984b56bc)

2. Left corners of the card are not round:
![image](https://github.com/user-attachments/assets/48872be0-b360-46d6-a962-f3fd22b458a3)

3. Move card screen issues:
![image](https://github.com/user-attachments/assets/94ed2fa2-ed72-4660-82e3-a1d7deb63402)

4. Not sure if it's an issue, card title/input seems to be missing top margin:
![image](https://github.com/user-attachments/assets/b7eae9f9-dd4a-4a2a-9534-74a209283df6)

**Comment by alexanderdd** [comment]
If you create many cards (~10) in a column, the spacing is wrong:
![2024-08-12_12-01](https://github.com/user-attachments/assets/8a93b1ed-8563-485b-8676-0a25c9fde80a)

**Comment by alexanderdd** [comment]
Also, **all card titles are now bold** (see screenshot above) 

Was this a deliberate design choice? IMO in an interface, not everything should be bold. It makes reading hard, and it screams in your face.. 

Should I open a separate issue about this?

And for the meantime: is there a custom css that I can use to make it not bold?

**Comment by luka-nextcloud** [comment]
I cannot reproduce these 3 issues:

- Still have that issue with card's content being pushed to left.
- Some cards with content have 3 scrollbars
- Move card screen issues

**Comment by viktorix** [comment]
@luka-nextcloud 

> Still have that issue with card's content being pushed to left.

This can be marked resolved.

> Some cards with content have 3 scrollbars

Just checked, and some cards still do have 3 scroll bars. Ping me in Talk, maybe I can share a card which has 3 scroll bars.
![image](https://github.com/user-attachments/assets/7c7b8e52-cf37-4706-8707-d2b571b36bc8)

> Move card screen issues

This still happens. See GIF:
![ee8cff86-b2ea-4bae-97e2-aca53c54d8b5](https://github.com/user-attachments/assets/b739b1bb-aae4-47c1-a48e-3b9d11e6ce63)

**Comment by alexanderdd** [comment]
@juliushaertl Is it on purpose that all card titles are now in bold text, or is it a bug? (see [screenshot above](https://github.com/nextcloud/deck/issues/6164#issuecomment-2283561216))

If it is a bug, can you add it to the checklist in the initial post?

IMO not everything in an interface should be bold.

**Comment by juliushaertl** [comment]
Yes, though that is fixed now already in https://github.com/nextcloud/deck/pull/6235
