### ISSUE TITLE
Create a list of predefined labels to be applied to each new board

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/deck#617]
**Is your feature request related to a problem? Please describe.**
When running a lot of projects, I tend to use the same labels for each board. It would be useful to be able to edit the predefined list so that each new board automatically has the labels I want without having to create the labels for each new board manually.

**Describe the solution you'd like**
A settings UI where I can pick a label title and color. These would then override the defaults the app ships with so that my predefined list would automatically be added to each new board

**Describe alternatives you've considered**
Editing /lib/Service/BoardService.php

```
`// create new labels
		$default_labels = [
			'31CC7C' => $this->l10n->t('Finished'),
			'317CCC' => $this->l10n->t('To review'),
			'FF7A66' => $this->l10n->t('Action needed'),
			'F1DB50' => `$this->l10n->t('Later')`
		];`
```
But I am concerned that

1) This would get overwritten when I update the app
2) That I might break something

**Additional context**
Is it safe to edit that file as a workaround in the meantime?

**Comment by ffuentes** [comment]
+1

**Comment by buzter** [comment]
Just wanted to ask the same question: I want to add four more default labels which are always given when creating a new board.

**Comment by linuxpete** [comment]
+1

**Comment by plages** [comment]
+1
Lack of a possibility to create predefined labels for all boards (if possible for all users) is the first thing i stumbled upon.
This would be a huge time saver.

**Comment by stefan-niedermann** [comment]
Since version `1.0.0` there's an option to clone a board (including tags and lists, excluding cards).

This way you are able to create a board e. g. with the title "Template", configure it the way you like it and use this as the source for new boards.

In my opinion the requested use case is covered and this issue can be closed therefore. Separate or pursuing issues should go into new issues and describe the needed use cases more detailed.

**Comment by rvsch** [comment]
Hallo,
I dont think this issue should be closed. I admit that the idea to create a board "Template" and clone this each time you want to create a new board could be a kind of work around. But it is no solution. It is rather a crutch than a solution. 

This are my arguments: There is still the button (in German): "+ Board hinzufügen". If you are working in a group with many members you have to tell every team member not to create a new board using the button that is intended for this very purpose and is prominently offered in Deck. That definitely will not work. Instead you will get boards with the wrong labels again and again over time. TThat's not exactly helpful if you want to organize project management efficiently - with a tool that is meant for exactly this purpose, isn't it? 

In my opinion it would be a great help to give at least the admin the possibility to define the set of labels for all new boards - and to give him the chande to change the colours of all defined and used labels afterwards. That definitly will save a lot of time. Today I was busy all the time to find out where I could change this set of labels. Right now I changed all labels in the database. And I changed the set of labels in the code in .../lib/Service/BoardService.php ... knowing that this is only a solution till the next update:

Kind regards
Ruediger
