### ISSUE TITLE
Feature Request - Offline Deck App for Desktop/Laptop

### ISSUE THREAD

**Issue by rogercreagh** [nextcloud/deck#6179]
Having to fire up a browser and login etc is a bit clunky for desktop/laptop use and requires you to be online which is not always possible.

A Linux (ubuntu) (and I suppose mac and windows) application for Nextcloud Deck would be very useful

Alternatively is anyone aware of any Kanban type linux apps that will sync with Nextcloud Deck?

It seems odd that there is an app for Android phones with small screens that make it hard to use other than for reminders and yet nothing to use on a desktop or laptop with plenty of screen real estate.

A simple approach for starters might be something like the P3X-OneNote application which is essentially a dedicated browser:
```
P3X OneNote Linux is, actually, an independent browser window for the online OneNote. You can use this program without having to clutter your browser. The main functions are:

that is independent from any browser, as it works in it's own process
it provides a tray, that allows you to close your browser while it keeps running in the tray
the data is cached and is faster than always opening a new window
```
It would still require being online, but would be an improvement on using a full general purpose web browser.

**Comment by putt1ck** [comment]
Once you need to be online, what's the downside of using a browser tab?

**Comment by pschopen** [comment]
For some reason people like real apps and don't enjoy working from a browser that much. I personally don't care but I know that many do.

You can give ferdium a try. It's available cross platform on Mac, windows and Linux and has a deck app. www.ferdium.org

**Comment by rogercreagh** [comment]
> For some reason people like real apps and don't enjoy working from a browser that much. I personally don't care but I know that many do.
> 
Thanks for understanding that.

> You can give ferdium a try. It's available cross platform on Mac, windows and Linux and has a deck app. [www.ferdium.org](http://www.ferdium.org)

I've looked at the link and the github but I have no clear idea of what on earth that is/does. What I'm looking for is a simple focused standalone Deck application, ideally that works offline and will re-sync (biderectional) when a connection is available

**Comment by pschopen** [comment]
Well, there is no such thing. But ferdium turns every website into an app. And some have even advanced features, if there's a integration. And for Deck there is an integration

**Comment by rogercreagh** [comment]
> Once you need to be online, what's the downside of using a browser tab?

All of the other browser stuff and overhead and tracking and so on and on. Plus actually I don't need, or want, to be online all the time - the P3X-OneNote example is a possible starting point (it doesn't save changes while offline, but perhaps that can be fixed)

I general I prefer to use the right tool for the job rather than a general purpose tool with compromises. Nextcloud is a great tool for personal cloud storage and file/data sharing, but most of the apps within NC are better done by dedicated local tools that simply use NC as storage.

**Comment by rogercreagh** [comment]
> Well, there is no such thing. But ferdium turns every website into an app. And some have even advanced features, if there's a integration. And for Deck there is an integration

Ok, thanks - that is not at all clear from the descriptions. Does the deck integration allow you to create different views, and does it work offline - I will take another look. Is there a link to info about how it integrates with Deck and what it does?

**Comment by pschopen** [comment]
Ferdium has it's own app store. Just activate the Nextcloud deck app from there and give it a try. I don't know Amy further details.

**Comment by abelbabel** [comment]
I would also highly appreciate a CLI/TUI for Deck - like [pimutils/khal](https://github.com/pimutils/khal) / vdirsyncer for the calendar stuff ...

**Comment by joshtrichards** [comment]
If someone wants to build one, the APIs are documented:

https://github.com/nextcloud/deck/tree/main/docs

**Comment by juliushaertl** [comment]
Let's close this, since we have no plans to do so. As with the mobile apps anyone is of course welcome to start building an app.
