### ISSUE TITLE
Upload once attach many times

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/deck#618]
**Is your feature request related to a problem? Please describe.**
There are situations where several cards in a board or across boards may need to reference the same image or file. Currently, I have to re-upload that file each time

**Describe the solution you'd like**
I would like to be able to upload a file once but attach it to as many cards as I need. This could be limited to just cards on one board but even better would be to allow it across different boards

**Describe alternatives you've considered**
Uploading the same file many times which is wasteful both in time and storage space.

**Additional context**

**Comment by LollenJumplan** [comment]
This sounds like something that could be solved by supporting attaching files from nextcloud itself, rather than the local machine only. Wasn't that planned anyway?

**Comment by juliushaertl** [comment]
It is already possible to add the attachment link or inline embedded by copying the URL to a different cards description.

As @LollenJumplan mentioned at some point attaching files from your nextcloud would solve this, so I'm closing this in favour of #564
