### ISSUE TITLE
Move card | can not select board anymore |  Deck 1.13.1 / Nextcloud 29.0.4

### ISSUE THREAD

**Issue by slu-010101** [nextcloud/deck#6181]
We can not select a board anymore (empty list), is this a known issue?

There was some closed bugs with copy cards/lists, but not with move cards to another board...

![can not move card Peek 2024-08-06 11-50](https://github.com/user-attachments/assets/e0d5434a-f86e-49a4-aeda-3f6e74b58ad6)

**Comment by Arksom** [comment]
Same here, Nextcloud version 29.05, Deck Plugin Version 1.13.1 installed on Ubuntu 22.04 LTS, Nginx, PHPFPM 8.1

**Comment by slu-010101** [comment]
Still not possible with Nextcloud 29.0.6 and Deck 1.13.1.
Any chance to fix this?

**Comment by fcharlaix-opendsi** [comment]
I have the same issue, Nextcloud 29.0.7, Deck 1.13.1.

If I move the card from the option when it's not open, it's working.

**Comment by slu-010101** [comment]
Works with Nextcloud 30.0.0 / Deck 1.14.0
