### ISSUE TITLE
Copy option for Deck cards

### ISSUE THREAD

**Issue by Julia-TGC** [nextcloud/deck#6184]
Submitting this on behalf of multiple customers on our hosting platform:

It would be convenient to be able to copy a Deck card with the relevant details but without the remarks.

This seems to be an expected function as it is, on occasion, reported as an issue.

Perhaps a copy function could be invoked with a button next to the move card option, here:

![gnome-shell-screenshot-743po3](https://github.com/user-attachments/assets/590d860e-0758-4598-afdb-eb72fac3be4c)

PS: I had a quick look and did not see a request for this, but I could be wrong. 

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stefan-niedermann** [comment]
Please search for existing issues before opening new ones.

https://github.com/nextcloud/deck/issues/1813

**Comment by juliushaertl** [comment]
> Submitting this on behalf of multiple customers on our hosting platform:

In case you are a Nextcloud partner or customer, please also share your feature request through the customer portal. If not you may also consider a Nextcloud enterprise subscription if you are relying on the software for customers in production environments. Learn more about this at https://nextcloud.com/enterprise/
