### ISSUE TITLE
List indentation only works in sidebar view

### ISSUE THREAD

**Issue by b90g** [nextcloud/deck#6214]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Writing lists on a card only works when card is in sidebar view

**To Reproduce**
1. create card
2. start a list
3. write at least 2 points
4. press TAB key on 2nd point.

**Expected behavior**

list indentation

**Screenshots**

![grafik](https://github.com/user-attachments/assets/239bb3e5-df72-407d-a1a3-70577e3b3c23)

**Client details:**
 - OS: [e.g. iOS] linux
 - Browser [e.g. chrome, safari] chromium & firefox
 - Version [e.g. 22] 127 & 129
 - Device: [e.g. iPhone6, desktop] desktoop

<details>
<summary>Server details</summary>

**Operating system**: debian

**Web server:** apache2

**Database:** mariadb

**PHP version:** 8.2

**Nextcloud version:** (see Nextcloud admin page) 29

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

Deck  Version 1.13.1, AGPL-licensed 
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by narFnarF** [comment]
Seems like a duplicate of https://github.com/nextcloud/deck/issues/5939

**Comment by b90g** [comment]
thanks, will close in favor of #5939
