### ISSUE TITLE
Show ID on cards and boards

### ISSUE THREAD

**Issue by tarpin** [nextcloud/deck#622]
**Is your feature request related to a problem? Please describe.**
Can't simply and strict refer to specific card or board.

**Describe the solution you'd like**
Each card and board should have a visible numeric ID.
- The ID should be unique (globally) and not editable.
- The IDs may be visible as greyed out number on the bottom, like issue's ID in Projects on GitHub [link](https://github.com/nextcloud/server/projects/1).
- The ID can be a combination of board ID and card ID form the Deck's URL (for [...]index.php/apps/deck/#!/board/3//card/2 it will be 32 or 3.2, for example).
- The ID can be used in URL and REST API, e.g. [...]index.php/apps/deck/3.2 is the same as [...]index.php/apps/deck/#!/board/3//card/2

**Comment by juliushaertl** [comment]
The card id is unique, so if you have the url `#!/board/3//card/2` card 2 is only available once on the whole Nextcloud instance.

I'm not sure if showing the id in the user interface is a good idea or if it is just additional noise inside of the ui. cc @nextcloud/designers

**Comment by tarpin** [comment]
> The card id is unique, so if you have the url `#!/board/3//card/2` card 2 is only available once on the whole Nextcloud instance.

I didn't know. Anycase, I still have to know board's ID to display card 2 in browser by URL (I've tried without any luck). Is there possibility to display this card without board's ID, e.g. `[...]index.php/apps/deck/2`?

> I'm not sure if showing the id in the user interface is a good idea or if it is just additional noise inside of the ui. cc @nextcloud/designers

It could be optional, disabled by default.

**Comment by jancborchardt** [comment]
I’m with @juliushaertl here – there already is the ID of the URL. 

> It could be optional, disabled by default.

We need to build and maintain every setting, that’s why we keep it simple. It also ensures we don’t just spend all time on fixing issues with little-used features.
