### ISSUE TITLE
Show Percentage of Completion

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/deck#627]
In one of the earlier versions, it was possible to add the percentage of completion to each task!

Why this feature was dropped ? Please add again!

regards, hitam4450

**Comment by juliushaertl** [comment]
We didn't have any percentage tracking in the past. We introduced an indicator for checkboxes that shows `finished tasks/total tasks`. That should be enough indication on the progress. Adding an additional percentage indicator would clutter the UI to much in my oppinion.

**Comment by hitam4450** [comment]
Sorry, perhaps I mixed up something!
