### ISSUE TITLE
[Design feature request] Default view without left menu

### ISSUE THREAD

**Issue by biva** [nextcloud/deck#631]
Thank you for this great app that we use all days.

The way we use it is with specific URL for different boards, for example: https://mynextcloud.com/apps/deck/#!/board/1/ for the board 1

But when I open this URL, the left menu is present: If I want to see only my board on the full screen, I need to click on the 3-bars menu (next to the "Home" icon).

Is there a possibility to hide the left menu by default? Or to add a parameter in the URL to hide it?

Thank you!

**Comment by juliushaertl** [comment]
I think the best way would be to just store the shown/hidden status when toggling the sidebar using the burger button.

**Comment by weeman1337** [comment]
I'll have a look at this one
