### ISSUE TITLE
modifications lost after a delay of inactivity

### ISSUE THREAD

**Issue by tykayn** [nextcloud/deck#633]
**Describe the bug**
after some time without activity (minutes or hours), the user is logged out, be we can still fill cards and move them to other columns. Nothing notifies us our modifications will not be taken, the app acts like everything is ok but when we reload the page we are still at the previous state. this is really annoying.

**To Reproduce**
Steps to reproduce the behavior:like described, could take lots of minutes to see the bug.

**Expected behavior**
I expect the app to show a thing saying we are logged out, or anything blocking us from interacting with the cards if modifications will not be taken.
or something to automatically re

**Client details:**
 - OS: windows 10, ubuntu 18.4
 - Browser firefox quantum
 - Deck Version 0.4.1
 - Device: desktop

<details>
<summary>Server details</summary>

**Operating system**:
ubuntu 17.4
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13 something, couldnt find the version in the admin panel. would be great to have it output in the js console.
**Where did you install Nextcloud from:**
the official site

**Signing status:**
what ?

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
That is an issue with Nextcloud 13 since after some timeout the CSRF token is becoming invalid. There is nothing we can do about that in deck, but with Nextcloud 14 the token is updating in the background so the issue should be fixed there.
