### ISSUE TITLE
Card deskription text partly visible on mobile browser

### ISSUE THREAD

**Issue by cieska** [nextcloud/deck#634]
**Description**
When using Deck on mobile phone Card text description partly visible, only about 60-70% of line visible. Not really possible to slide some frame or text itself to read it fully. 

**Screenshots**
![screenshot_20181007-213759](https://user-images.githubusercontent.com/41318524/46586815-a4d4d580-ca7b-11e8-9587-bfa93c348e4a.png)
![screenshot_20181007-213817](https://user-images.githubusercontent.com/41318524/46586817-a9998980-ca7b-11e8-8f39-271040fbd4be.png)

**Client details:**
 - OS: android 8.1
 - Browser: Firefox, Brave, 
 - Version: newest versions at present 2018 October
 - Device: LG Nexus 5x

**Operating system**: ubuntu 18.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** Not sure (newest at present October 2018)

**Nextcloud version:** 13.0.5

**Where did you install Nextcloud from:**

**List of activated apps:**

Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - camerarawpreviews: 0.5.6
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - deck: 0.4.1
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_reader: 1.2.3
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - news: 12.0.4
  - nextcloud_announcements: 1.2.0
  - notes: 2.4.2
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.4
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - ocr
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.200",
            "ap.hopto.org",
            "nextcloud.ap.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.ap.com",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN"
    }
}

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by juliushaertl** [comment]
Fixed with a6da1de
