### ISSUE TITLE
new card input field: wrong dimensions, last characters is not displayed

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/deck#6351]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**To Reproduce**
1. click "new card"
2. enter a longer title
3. last character is not displayed (hidden behind "->" button)

**Expected behavior**
you should see the last character you typed

**Screenshots**

![grafik](https://github.com/user-attachments/assets/b8ef626f-797c-4482-91d7-4e860211b188)

**Details**
NC 30.0.0
this is on c.nc.com - I can't check app version

**Comment by alexanderdd** [comment]
@nextcloud/designers can someone triage this regression please?

(or is triage done by engineering?)

**Comment by marcoambrosini** [comment]
It's triaged by the office team @alexanderdd

**Comment by alexanderdd** [comment]
@nextcloud/office can you please triage?
