### ISSUE TITLE
Сan't create new board as user

### ISSUE THREAD

**Issue by Vini-dav** [nextcloud/deck#6389]
Hi,
I administration NC deck on my company, and have trabl. I create new user and add it on group 'DIA'. This user can't create in ouw profil new board, if I add it on default grop "admin", It works normly, but he get accses too mach setting

![Image](https://github.com/user-attachments/assets/61333d4f-466c-45fb-9d5e-8c1e1152723d)

How do I manage this user, what  I give him neded rules?

**Comment by luka-nextcloud** [comment]
@Vini-dav
- Does group "DIA" have write permission?
- Please provide client details, server details and logs according to this template https://github.com/nextcloud/deck/issues/new?template=Bug_report.md

**Comment by Vini-dav** [comment]
Thanks friend, your comment gave me an idea, my interface (Russian) has bad localization. This setting lives here (maybe it will help someone):
![Image](https://github.com/user-attachments/assets/dccd399b-d760-4382-81d4-3992288d0929)
