### ISSUE TITLE
How can I cut a release?

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/deck#6419]
Hi,

trying to help here :)

I had enough rights to backport this:
https://github.com/nextcloud/deck/pull/6418

I'd like to cut a 1.12.6 release:
https://github.com/nextcloud/deck/compare/v1.12.5...stable28?expand=1

Do I have enough rights to do so?

If yes, what would be the process?

Thanks a lot and have a nice day!

**Comment by juliusknorr** [comment]
Releases need to be built by maintainers, I'll align with @luka-nextcloud to see if we can build one next week

**Comment by elzody** [comment]
I will close this for now as it doesn't seem entirely useful now
