### ISSUE TITLE
[UX] Enhancement for adding new card

### ISSUE THREAD

**Issue by philffm** [nextcloud/deck#6458]
**Is your feature request related to a problem? Please describe.**
Even though I got used to working with Deck and love it, one aspect still confuses me:
When adding a new card (top of the screen) it appears in the bottom of the screen. What happens here is called [change blindness](https://www.nngroup.com/articles/change-blindness-definition/) due to the nature of the users' eyes (central vision vs. peripheral vision)

**Describe the solution you'd like**
Would be better to insert the new card right below the creation button (to the top) - This would also **improve the experience on mobile** where adding cards is not possible (input for card is displayed in the bottom thus swallowed by the keyboard, but would work if card was added on the top of the screen)

![Image](https://github.com/user-attachments/assets/b6806fdb-7470-4051-bc75-38bced068843)

**Describe alternatives you've considered**
Alternative would be for each deck to have the card inserted in the bottom (as is) and also place the button there. 
![Image](https://github.com/user-attachments/assets/ed3d7ad9-a3f5-451a-8352-a7940ec15681)

**Comment by XueSheng-GIT** [comment]
On NC 29 and Deck 1.13.2 new cards are created directly below the "+" button:

![Image](https://github.com/user-attachments/assets/5c75c4a4-2feb-495a-ac80-070cc753721e)

I'm still testing NC 30 before doing the upgrade and while doing some tests, I thought deck would be broken because I did not realize that the new cards will pop up at the bottom of the page. I would consider this a bug.

**Comment by XueSheng-GIT** [comment]
Seems there's already another issue for this https://github.com/nextcloud/deck/issues/6457. Maybe would be best to close this one in favour of the other!?

**Comment by philffm** [comment]
> On NC 29 and Deck 1.13.2 new cards are created directly below the "+" button:

Oh interesting, I'm using NC30 and 1.14.1 - so this was probably a recent adjustment 🤷‍♂️

**Comment by elzody** [comment]
I will indeed close this as one already exists at #6457 that seems to be the same
