### ISSUE TITLE
cardinfo: Modified: ... created: .. by

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#647]
**Describe the bug**
In card-metainformation modifier and creator of a card are swapped

**To Reproduce**
1. create a card with testuser_creator
2. modify the card with testuser_modifier
3. open the card
4. "Modified: seconds ago **Created: 6 minutes ago by testuser_modifier**" is displayed, although the card was not created by test_modifier: 
![___screenshot from 2018-10-12 00-25-27](https://user-images.githubusercontent.com/34692335/46857246-c8e04000-ce08-11e8-988e-da145264e5a5.png)

**Expected behavior**
 "**Modified: seconds ago by testuser_modifier** Created: 6 minutes ago"

(or more complex:
 "Modified: seconds ago by testuser_modifier Created: 6 minutes ago by testuser_creator"
)
**Suggestion**
In .../templates/part.card.php move line 33
`<span>{{ cardservice.getCurrent().owner.displayname }}</span>
`
between line 30 and 31
because cardservice.getCurrent().owner returns the last modifier and not the creator

**Environment**
Tested with deck 0.5.0-dev2

**Comment by juliushaertl** [comment]
I think we could actually get rid of the user, since we have pretty detailed change log in the activity feed now.

**Comment by cloud2018** [comment]
ja, Deine Variante ist noch geschickter

**Comment by juliushaertl** [comment]
@cloud2018 Since you have already looked into the template code, would you mind to create a pull request to remove the user from the sidebar then? That would be awesome :wink:

**Comment by cloud2018** [comment]
sorry, i'm not very familiar with github :-(

**Comment by juliushaertl** [comment]
@cloud2018 No problem. ;)
