### ISSUE TITLE
Close button appears twice

### ISSUE THREAD

**Issue by pschopen** [nextcloud/deck#6475]
![20241104_145554.jpg](https://github.com/user-attachments/assets/d57ec17a-dbf3-4576-bd45-b5039dc20825)

Since the last update two different close buttons exist when opening a card.

**Comment by elzody** [comment]
I was only able to reproduce this on master branch, do you mind sharing which version you have

**Comment by pschopen** [comment]
> I was only able to reproduce this on master branch, do you mind sharing which version you have

Deck: 1.14
NC: 30.0.1

**Comment by pschopen** [comment]
Duplicate of #6428
