### ISSUE TITLE
i18n: Understanding problem with "{user} has mentioned in a comment on "%s""

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/deck#649]
https://github.com/nextcloud/deck/blob/1d777550edbe6879cf94d94e6aacddba726b6651/lib/Notification/Notifier.php#L121

What does this sentence is about?

Please provide some context.

Issue at Transifex: https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/deck/154637012?q=text%3A'{user}+has+mentioned'

**Comment by juliushaertl** [comment]
This is a notification, that a user has mentioned you in a comment on a card. %s is the title of the card.

**Comment by juliushaertl** [comment]
Commented on the transifex issue as well.

**Comment by rakekniven** [comment]
Maybe my english skillz are not good enough.

> "{user} has mentioned in a comment on "%s"

For me this does not sound valid.

It should be
> "{user} has mentioned you in a comment on "%s"

or?

**Comment by juliushaertl** [comment]
@rakekniven Totally right :see_no_evil: Thanks for recognizing.
