### ISSUE TITLE
Change Due date without jumping into card details

### ISSUE THREAD

**Issue by KernSani** [nextcloud/deck#6551]
I'm working a lot with due dates in Deck cards to schedule my days (I know this is not proper Kanban, however I'm pretty happy with my workflow). This involves unfortunately regular changes of the date. Right now I have to go to the card details to change the date. It would be great to add the "change date" menu directly to th three dots on the card, so users are able to select a new date saving some extra clicks.

Thanks,

Oli

**Comment by luka-nextcloud** [comment]
Thank you. We already have an issue opening similar to this. https://github.com/nextcloud/deck/issues/5330
