### ISSUE TITLE
Ability to easily make a copy of a card

### ISSUE THREAD

**Issue by odecif** [nextcloud/deck#6571]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I use the deck with quite heavy cards that I like to reuse on different boards.

**Describe the solution you'd like**
I would like to be able to search for a card and click the three dots and select "make a copy" or "copy card" that I then can move to another board.

**Describe alternatives you've considered**
Nothing really. I mean, it is possible to copy the contents of the card and paste them into a new one but that takes quite a lot more effort if I have data in multiple different fields.

**Additional context**
Awesome product, I really hope that it gets to live a long and prosperous life.

**Comment by stefan-niedermann** [comment]
Please stop opening duplicates of existig issues.

https://github.com/nextcloud/deck/issues/1813

**Comment by odecif** [comment]
Oooh, I see that all enhancement issues do not have "Type = enhancement" in Github. Thought for a second there that there was only 4 enhancement requests and got a little carried away :)
