### ISSUE TITLE
Checkboxes or subtasks on cards

### ISSUE THREAD

**Issue by odecif** [nextcloud/deck#6572]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
A card sometimes has multiple smaller parts/actions that are too small to be considered their own card and the best way to visualize that today is to write them in plain text/regular lists which is not as clear as having something more organized.

**Describe the solution you'd like**
I would like to (like in Trello and Google Keep) be able to add checkboxes/list of checkboxes that can be checked/unchecked.

**Describe alternatives you've considered**
Possibly instead of checkboxes add subtasks or child-cards to the cards (called snippets maybe?) that can be marked as done or not done.

**Additional context**

**Comment by stefan-niedermann** [comment]
Please use Markdown to create checkboxes

```
- [ ] Item 1
- [x] Item 2
```

or use the corresponding checkbox button in the toolbar.

For dedicated subtasks please use the search function of GitHub, issues already exist.
