### ISSUE TITLE
Exception in Deck/DB/BoardMapper.php line 218

### ISSUE THREAD

**Issue by Gravelbones** [nextcloud/deck#6590]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
In the log file there is the following exception multiple times:
{"reqId":"Zqx6PuhDcZXxSJhl4Tld","level":2,"time":"2024-12-10T10:37:11+00:00","remoteAddr":"x.x.x.x","user":"x","app":"no app in context","method":"GET","url":"/nextcloud/ocs/v2.php/apps/deck/api/v1.0/overview/upcoming","message":"Using where() on non-empty WHERE part, please verify it is intentional to not call andWhere() or orWhere() instead. Otherwise consider creating a new query builder object or call resetQueryPart('where') first.","version":"30.0.1.2","exception":{"Exception":"Doctrine\\DBAL\\Query\\QueryException","Message":"Using where() on non-empty WHERE part, please verify it is intentional to not call andWhere() or orWhere() instead. Otherwise consider creating a new query builder object or call resetQueryPart('where') first.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/deck/lib/Db/BoardMapper.php","line":218,"function":"where","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"}

**To Reproduce**
1. Go to Deck
2. Create a board
3. Create a card
4. Click card details
5. Add any text

**Expected behavior**
The program should not throw an exception

**Client details:**
 - OS: Windows
 - Browser Firefox
 - Version 133
 - Device: Laptop

**Server details**
- **Operating system**: Debian
- **Web server:** Apache
- **Database:** Postgres
- **PHP version:** 8.2.26
- **Nextcloud version:** 30.0.1
- **Where did you install Nextcloud from:** Source

To fix this you need to change ->where after an innerjoin to andWhere. This must be because innerjoin adds its own where clause.

**Comment by juliusknorr** [comment]
Thanks you for reporting. We have fixed this at https://github.com/nextcloud/deck/pull/6611 and will be available with the next release
