### ISSUE TITLE
latest release link is broken

### ISSUE THREAD

**Issue by shadow4040** [nextcloud/deck#6618]
latest link `https://github.com/nextcloud/deck/releases/latest/download/deck.tar.gz`

resolves to

`https://github.com/nextcloud/deck/releases/download/v1.14.2/deck.tar.gz` -> not found

**Comment by juliusknorr** [comment]
The release link published to the app store at https://apps.nextcloud.com/apps/deck should be this one:

https://github.com/nextcloud-releases/deck/releases/download/v1.14.2/deck-v1.14.2.tar.gz

The separate github org is the main location where we publish the release archive nowadays, but I'd suggest to always stick to the link that is available through the apps management / apps.nextcloud.com
