### ISSUE TITLE
Limit number of cards on stacks

### ISSUE THREAD

**Issue by Salokyn** [nextcloud/deck#662]
To use Desk as a Kanban board, it would be great to be able to set a maximum number of card in a column.

**Comment by juliushaertl** [comment]
Not sure about this, while I get that you might want to limit the number cards, I'm a bit concerned that we mess up the UI with to many settings. Especially since we don't have any section in the UI that would allow us to quickly add some values for stacks.

cc @nextcloud/deck

**Comment by pixelipo** [comment]
This is a very important feature for professional users of Kanban boards. However, I'm not sure if it doesn't require some additional pro-features, such as:
- permissions: having user roles and limiting which roles are allowed to move cards to which stacks
- workflow: conditions that allow/block moving cards to certain stacks
- card types: each type with a unique set of user role permissions and workflows
- custom colour-coding: define which card property is responsible for color-coding cards on a particular Kanban board
- automation: automatically move cards to a defined stack when condition is met; move other cards to defined stack when another card is move to a defined stack

I'm not sure what is the long-term plan for Deck, @juliushaertl  - but if we want to cater to professionals, then we should discuss all of these features. Perhaps we could define a milestone "Good enough for private users" and once we reach it, spend a couple of subsequent releases working on "pro" package?

**Comment by juliushaertl** [comment]
@pixelipo I think our first goal should be to provide a basic feature set before considering more advanced features like the ones you've mentioned. So this is nothing that is on our roadmap for now.
