### ISSUE TITLE
show deleted items only from active board not from all boards

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#683]
**Is your feature request related to a problem? Please describe.**
In the right board details, all deleted items are displayed, regardless of which board the cards or stacks are deleted from.

**Describe the solution you'd like**
In the right board-details view show only the deleted items, which are deleted from the active board, not from other boards

**Comment by juliushaertl** [comment]
Thanks for reporting. I could reproduce, seems the list isn't cleared properly.

**Comment by cloud2018** [comment]
Danke
