### ISSUE TITLE
Click outside the card details page to close it

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/deck#69]
### Steps to reproduce

1. Click on any card within your board - the card details appear on the right side of the screen
2. Click outside of the card details (somewhere on the left of the screen)

### Expected behaviour
The card details should close, like it does when clicking the X on the right-hand side

### Actual behaviour
The card stays opened, requiring to click on the little X on the right side of the screen.
In order to work more fluently and faster, it should close when clicked outside of the card.

**Comment by juliushaertl** [comment]
Fixed with #102
