### ISSUE TITLE
Papercut: unify name of actions

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#691]
Sometimes the name of actions is short, sometimes long
ex.: board actions: edit board, delete board...
ex.: card actions: edit, delete, assign, ...:

![action](https://user-images.githubusercontent.com/34692335/48301499-7bcab900-e4ef-11e8-81d4-e3bd89ed688e.png)

What do you think about always use action + object (delete board, delete card, delete attachment, ...)?
I prefer this to just only edit, delete, ... , because it makes it easier for the user to remember which actions are possible for which object.

**Comment by juliushaertl** [comment]
Yes, I think action+object makes the most sense here. So we would have to rename the board details to "Show board details" and have "Assign to me" renamed to "Assign card to me".
