### ISSUE TITLE
405 on GET-call for stacks

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/deck#692]
**Describe the bug**
From the Deck-Android-app i am trying to request the stacks of a board.

**To Reproduce**
1. Checkout Deck app
2. Run it
3. See error (on console):

2018-11-10 14:24:45.970 14734-14734/it.niedermann.nextcloud.deck E/#### deck: GET
2018-11-10 14:24:45.970 14734-14734/it.niedermann.nextcloud.deck E/#### deck: /index.php/apps/deck/api/v1.0/board/7/stacks
2018-11-10 14:24:46.159 14734-14734/it.niedermann.nextcloud.deck E/Deck: HTTP request failed with HTTP status-code: 405

first output is the method, second the url, third the response.

Tags:
@stefan-niedermann

**Comment by desperateCoder** [comment]
Never mind. wrong URL, its "board**s**" not "board". RTFM at its finest.

**Comment by stefan-niedermann** [comment]
Actually i would expect to get a `404` instead of a `405`...?

**Comment by juliushaertl** [comment]
Seems this is caused by the preflighted_cors route that matches anything unter /api/v1.0/ https://github.com/nextcloud/deck/blob/37a2858d5f1cd61c7a92eb47ad7578cdd8753cb4/appinfo/routes.php#L117 So there is a route matching the url but only with the OPTIONS method.

**Comment by stefan-niedermann** [comment]
well, makes perfectly sense now.

But instead of matching globally `/api/v1.0/{path}` - shouldn't be there a preflight route for each normal route? this way we could keep cors working while returning more descriptive http status codes? :)

**Comment by juliushaertl** [comment]
The thing is, we can't have multiple routes use the same controller method, so we would need to have a separate controller method for each route matching the api routes. And for the regular routes, they are not needed, since those are only called from the nextcloud server.

**Comment by stefan-niedermann** [comment]
well, if there are technical limitations, i am fine with it. Just wanted to point out, that i would expect a `404` in this case :) - feel free to close!

**Comment by juliushaertl** [comment]
I see no easy way of returning a 404 for now, so let's close this.
