### ISSUE TITLE
Live-View for groups

### ISSUE THREAD

**Issue by UkeFan** [nextcloud/deck#698]
As a replacement for trello it would be great if all users being in the same staple could see changes one does. By now you have to reload in order to see changes. If it was more/less live like the NC-file-handling itself - GREAT (-:
But so far: Cool to have your app in NC!! Thank your very much!!

**Comment by juliushaertl** [comment]
@UkeFan Thanks for your request. We already have an issue for that, so I'm closing this as a duplicate of https://github.com/nextcloud/deck/issues/256
