### ISSUE TITLE
Ability to archive boards

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/deck#70]
### Steps to reproduce

1.Click on the three dots next to a board

### Expected behaviour
It should provide the ability to archive the board instead of deleting the board.
An archived board should have the ability to be deleted.

This way there are two benefits
* Old boards can be hidden from the main view because they're archived
* It's harder to accidentally delete a board (there is no recovery option, or so it seems)

### Actual behaviour
There is no option to archive a board. Instead there is an option to delete the board.
When the delete button is accidentally clicked, the complete board is gone. There doesn't seem to be a recovery option.
If you want to keep the history of boards, you can end up with a big list

**Comment by juliushaertl** [comment]
@armaccloud Thanks for the idea. We should definitely implement that. :+1:

**Comment by juliushaertl** [comment]
implemented with #133
