### ISSUE TITLE
Cannot create new cards in Deck 0.5.0 / NC 13.0.7

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#705]
**Describe the bug**
Just updated to deck 0.5.0 and ran some tests. Creating a new card seems to be impossible.

**To Reproduce**
1. Click on the '+' sign in a stack
2. Enter a card title
3. Hit Enter
4. Nothing happens. Keyboard 'enter' command is ignored.

**Expected behavior**
A new card should be created.

**Client details:**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 63.0.1
 - Device: Desktop

**Nextcloud version:** (see Nextcloud admin page)
- 13.0.7 (no problems in 14.0.3)

**Comment by juliushaertl** [comment]
Thanks for your report @bpcurse Un fortunately I cannot reproduce this with Firefox on 13.0.7 

Can you check your browser console for errors and maybe try with an empty browser cache?

**Comment by bpcurse** [comment]
@juliushaertl Thanks for the advice. Unfortunately clearing the browser cache and restarting the browser did not help.

**Browser console log (cache emptied before), all entries created after hitting 'enter':**
Possibly unhandled rejection: Fetchingcards failed vendor.js:7:78644
i/<   https://cloud.fachschaftmedizin.de/apps/deck/js/build/vendor.js:7:78644
En/this.$get</<   https://cloud.fachschaftmedizin.de/apps/deck/js/build/vendor.js:7:60454
c   https://cloud.fachschaftmedizin.de/apps/deck/js/build/vendor.js:7:94417
$digest   https://cloud.fachschaftmedizin.de/apps/deck/js/build/vendor.js:7:100279
$apply   https://cloud.fachschaftmedizin.de/apps/deck/js/build/vendor.js:7:102468
y/b</</<   https://cloud.fachschaftmedizin.de/apps/deck/js/build/vendor.js:7:65608
_   https://cloud.fachschaftmedizin.de/apps/deck/js/build/vendor.js:7:68492
Bn/this.$get</</</y.onload   https://cloud.fachschaftmedizin.de/apps/deck/js/build/vendor.js:7:67863

Is this what you wanted, can I supply any other helpful information?

**Comment by bpcurse** [comment]
@juliushaertl 
The cards actually seem to be created. One just has to reload the page.
Same behaviour when deleting or assigning a card to oneself via 3 dot menu. Nothing seems to happen, but the card is deleted anyway, which can only be seen after a page reload.

Curiously, archiving the card via 3-dot menu works immediately...

**Comment by juliushaertl** [comment]
Yes, those errors should be helpful. I'll look into that.

**Comment by bpcurse** [comment]
Do I get this right, that there is a problem with the correct use of the dbtableprefix? Our dbtableprefix is not 'oc_', it is an individual string.

From the nextcloud log, after hitting the enter key:
`{"reqId":"W@7x4zCgQ0B5QtC4E3n3bQAAAA8","level":3,"time":"2018-11-16T16:35:47+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"index","method":"POST","url":"\/index.php\/apps\/deck\/cards","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT s.board_id as id, c.stack_id as stack_id FROM oc_deck_stacks as s inner join oc_deck_cards as c ON c.stack_id = s.id WHERE c.id = ?' with params [439]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table '[anonymized db name].oc_deck_stacks' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT s.board_...', Array)\\n#2 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/lib\\\/private\\\/DB\\\/Connection.php(195): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT s.board_...', Array, Array, NULL)\\n#3 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/deck\\\/lib\\\/Db\\\/ChangeHelper.php(69): OC\\\\DB\\\\Connection->executeQuery('SELECT s.board_...', Array)\\n#4 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/deck\\\/lib\\\/Service\\\/CardService.php(184): OCA\\\\Deck\\\\Db\\\\ChangeHelper->cardChanged(439, false)\\n#5 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/deck\\\/lib\\\/Controller\\\/CardController.php(80): OCA\\\\Deck\\\\Service\\\\CardService->create('newtest', 76, 'plain', 999, '[anonymized]')\\n#6 [internal function]: OCA\\\\Deck\\\\Controller\\\\CardController->create('newtest', 76, 'plain', 999)\\n#7 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#8 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Deck\\\\Controller\\\\CardController), 'create')\\n#9 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Deck\\\\Controller\\\\CardController), 'create')\\n#10 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Deck\\\\\\\\Contro...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/deck\\\/card...')\\n#14 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/index.php(42): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}`

**Comment by bpcurse** [comment]
The browser network tab info returns 500:

`POST /index.php/apps/deck/cards HTTP/1.1
Host: [anonymized]
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: application/json, text/plain, */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
requesttoken: [anonymized]
Content-Type: application/json;charset=utf-8
Content-Length: 48
DNT: 1
Connection: keep-alive
Cookie: [anonymized]; oc_sessionPassphrase=[anonymized]; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true

HTTP/2.0 500 Internal Server Error
date: Fri, 16 Nov 2018 16:29:30 GMT
server: Apache
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval' 'nonce-[anonymized]='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-robots-tag: none
x-download-options: noopen
x-permitted-cross-domain-policies: none
strict-transport-security: max-age=63072000
content-type: text/html; charset=UTF-8
X-Firefox-Spdy: h2`

**Comment by bpcurse** [comment]
Looks like the individual dbprefix is missing indeed and "oc_" is used instead.
@juliushaertl Could you please check if this is the correct solution?

I have made the following change in /lib/Db/ChangeHelper.php (line 68):

FROM: 
$sql = 'SELECT s.board_id as id, c.stack_id as stack_id FROM oc_deck_stacks as s inner join oc_deck_cards as c ON c.stack_id = s.id WHERE c.id = ?';

TO: 
$sql = 'SELECT s.board_id as id, c.stack_id as stack_id FROM `` `*PREFIX*deck_stacks` `` as s inner join `` `*PREFIX*deck_cards` `` as c ON c.stack_id = s.id WHERE c.id = ?';

At least this seems to work :)

**Comment by juliushaertl** [comment]
@bpcurse Ah yes, that makes sense. Mind to open a pull request with the change? Thanks for looking into that. :+1:

**Comment by bpcurse** [comment]
I hope the pull request is correct as I have never made a commit to github before.
