### ISSUE TITLE
Missing icons for "show archived cards" and "compact mode" in Deck 0.5.0 / NC14.0.3 and Firefox 63.0.1

### ISSUE THREAD

**Issue by cappuMUC** [nextcloud/deck#706]
The icons of the buttons to "Show archived cards" and "Switch to compact mode" are missing. It seems, that the `background-image` property gets overwritten by another style rule.
![grafik](https://user-images.githubusercontent.com/9985266/48566801-f9316780-e8fb-11e8-9ac5-dcf5d5164a2c.png)

**Comment by cappuMUC** [comment]
I've found more missing icons in the sidebar... 
![grafik](https://user-images.githubusercontent.com/9985266/48568790-719a2780-e900-11e8-99c8-3d237faa2e69.png)

...and the cards actions menu.
![grafik](https://user-images.githubusercontent.com/9985266/48568925-cb9aed00-e900-11e8-8c7e-907a960fb5e5.png)

They get overridden by the same CSS rule for example the Deck icon gets overridden by:
``` css
.icon-deck {
    background-image: var(--icon-deck-000);
}
```

**Comment by bpcurse** [comment]
All icons are displayed fine here on a 14.0.3 instance / Deck 0.5.0 accessed by Firefox 63.0.1 on Linux Desktop. NC Server running manjaro i3, nginx, mariadb.

**Comment by juliushaertl** [comment]
@cappuMUC Can you try a forced reload so that your browser also redownloads cached css files? Should work by pressing Ctrl+F5 in Firefox.

**Comment by juliushaertl** [comment]
If that is the case we probably want to backport https://github.com/nextcloud/server/pull/12408 to stable14 as well.

**Comment by joergmschulz** [comment]
confirmed. With Firefox on apple: Shift-Cmd-R reloads and displays icons alright.

**Comment by cappuMUC** [comment]
@juliushaertl A forced reload with Ctrl+F5 did the trick on my machine. Now everything looks as expected.
Thank you very much! :smile:

**Comment by juliushaertl** [comment]
Ok, closing this as a server issue then. I will prepare a backport for stable14 as well.
