### ISSUE TITLE
After 0.50 update, can't enter in decks

### ISSUE THREAD

**Issue by magaiverpr** [nextcloud/deck#708]
Updated to version 0.50. Now I can't enter in the decks created. Nextcloud version 13.0.6.

Error message:

![imagem 9](https://user-images.githubusercontent.com/10533823/48617521-d3e53d80-e97d-11e8-9bc8-06db08e475d8.png)

Found log when trying to access:

![imagem 7](https://user-images.githubusercontent.com/10533823/48617539-e2cbf000-e97d-11e8-9b74-8cd67b1ec1b2.png)

**Comment by juliushaertl** [comment]
@magaiverpr Can you provide the full log message of the last error? You can expand that usually by clicking on it.

**Comment by magaiverpr** [comment]
![imagem 10](https://user-images.githubusercontent.com/10533823/48633278-276d8080-e9aa-11e8-96db-017685f8f7a5.png)

**Comment by magaiverpr** [comment]
Restarted the Nextcloud server and now it's working.

**Comment by juliushaertl** [comment]
Probably some weired caching issue then. Let's close this since you seem to be the only one affected.
