### ISSUE TITLE
Possible to assign a user to a card twice (duplicate)

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#710]
**Describe the bug**
When adding a user and you think you have mis-clicked and try adding again, it is possible to end up with the user assigned to the card twice.
![image](https://user-images.githubusercontent.com/2872580/48658775-58e45b80-ea3f-11e8-9c6b-67e978bd099d.png)

This is both visual on the card and shows as separate activity entries.

NC 14.03

Related: browser is under heavy load (bad user, bad) which may have allowed an effective escape in scripts

Additional: as a related outcome, the users assigned do not show in the card details sidebar so the "double add" user can't be unassigned.

**Comment by juliushaertl** [comment]
Thanks for reporting @putt1ck Indeed we should show a proper loading indicator and avoid inserting the user assignment twice.

**Comment by juliushaertl** [comment]
Should be fine with the multiselect that is used in the next release.
