### ISSUE TITLE
Papercut: Unify text of activity

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#711]
Papercut: Unify text of activity
Sometimes "card {card}", "stack {stack}" or "board {board}" is coded, sometime just "{card}", "{stack}" or {board}.

**current:**
You have unarchived {card} in {stack} on {board}'
You have moved the **card** {card} from {stackBefore} to {stack}
{user} has added a description to {card} in {stack} on {board}'

**suggestion:**
1)Use always "object" +" title of object" and not only "title of object" :
You have unarchived **card** {card} in **stack** {stack} on **board** {board}'
You have moved the **card** {card} from **stack** {stackBefore} to {stack}
{user} has added a description to **card** {card} in **stack** {stack} on **board** {board}'

or
2)Use only for the first "object" + "title of object":
You have unarchived **card** {card} in  {stack} on  {board}'
You have moved the **card** {card} from  {stackBefore} to {stack}
{user} has added a description to **card** {card} in {stack} on {board}'

What do you think about it?

**Comment by juliushaertl** [comment]
I think your first suggestion is the best. Otherwise it is hard to understand what the object title is about. Good proposal @cloud2018 :+1:

**Comment by cloud2018** [comment]
@juliushaertl A question before implementation:
In activities "label" and in board/card view "tag" is used. How should this unified? "tag" also in activities or (with another PR) everywhere "label"?
