### ISSUE TITLE
Search results in blank page (after briefly displaying the correct results)

### ISSUE THREAD

**Issue by woosting** [nextcloud/deck#712]
**Describe the bug**
After initiating a search using the Nextcloud search bar (top right corner in the blue bar) the page does shortly display the correct search result, but it gets replaced with a blank page after ca. half a second (on Firefox) or even a This page isn't working (405) error on Vivaldi. Rendering the Search functionality unusable.

**To Reproduce**

Reproduces on the `Nextcloud public demo system` and on a `local Nextcloud 14.0.3` instance.

1. Go to Deck within a Nextcloud (demo) instance
2. Click on search (magnifier icon)
3. Enter a search terms/string (query) that should yield results.
4. Press enter.

**Expected behavior**
Display a regular Deck overview showing only deck cards corresponding to the search string.

**Screenshots**
MP4 video of the issue: https://imgur.com/a/AuooJpF

**Client details:**
 - OS: Windows10 and GNU/Linux Debian 9 (Gnome3)
 - Browser Firefox (and Vivaldi)
 - Version 63.0.1 (64-bit)
 - Device: Desktop

#### Browser log
```
405 Method not allowed
```

**Comment by woosting** [comment]
Reproduces on the Nextcloud public demo system (and reproduces 100% of the times)!

Please let me know if more/specific information is required!

**Comment by rolandwells** [comment]
I am experiencing the same 405 page. 
Deck version 0.5.0
Nextcloud version 14.0.4

**Comment by juliushaertl** [comment]
Yes, I could reproduce as well. I'll look into fixing this for 0.5.1
