### ISSUE TITLE
Ability to choose to be notified per board

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#713]
If you are involved with lots of projects or sub-projects, being notified of changes for every board can become a distraction. If you could choose to be notified only on a per board basis, you could decide which boards were a priority for you and not receive updates from every board.

Bonus addition: board admin to have option to set for all users (useful for boards tracking reported issues on a new release or rollout)

Alternative approach: have 2 notification types for Deck, general and "mention", where mention would include being @'ed in a card or being added/removed from a card or board. This might be a simple workaround i.e. you tell people if they want you to look at something they need to mention you

**Comment by jakobroehrl** [comment]
Does it make sense to favourite single cards and get notifications only for them?

**Comment by putt1ck** [comment]
Only if people who are assigned to a card don't get notifications. Although you could treat favouriting a card similar to watching a issue on github; you're not assigned (not directly involved) but want to know how it is progressing

**Comment by juliushaertl** [comment]
Let's keep this simple for now. Most of the use cases where you want to be notified about cards should be covered with the board wide setting I'd say. cc @jancborchardt

**Comment by jancborchardt** [comment]
Agree with @juliushaertl. For the board-wide setting, we can do it exactly the same as Talk and have the actions menu with "Notifications":
- All changes
- @-mentions only
- Off

![image](https://user-images.githubusercontent.com/925062/76601535-b73e2300-653b-11ea-9fbd-e7d8af99b07a.png)
(Header alignment is off for some reason, ignore that.)

**Comment by juliushaertl** [comment]
For deck we would have basically these options:
- Card notifications
  - All cards
  - Assigned cards
  - Off

**Comment by jakobroehrl** [comment]
@juliushaertl 
Could you give me a rough sketch how to start here?
