### ISSUE TITLE
Editing card description stops when swapping windows

### ISSUE THREAD

**Issue by lucianpricop** [nextcloud/deck#718]
**To Reproduce**
1. Start editing the description of a card
2. Type some text
3. Swap window (e.g. want to copy some URL to paste it in description)
4. Swap back to Deck window
5. The description has been saved to card, editing disabled. You need to click and wait again to be able to continue typing

**Expected behavior**
Cursor at the end of the typed text and being able to continue to type or to paste directly.

**Comment by saro** [comment]
may be it's not very relevant, but this is also breaking the external editor functionality of `qutebrowser` :(

**Comment by juliushaertl** [comment]
Closing as this was fixed in the vue branch and is now merged to master
