### ISSUE TITLE
Activity notification emails don't contain user and other details

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#721]
If you enable email notification for Deck, the notification emails don't identify the user who carried out the action, nor the action e.g.

 _Today at 08:21 
 has created  in Notes on__

The user and action are correctly identified in the same item in the activity stream e.g.
	
_**John Doe** has created My example note in Notes on_

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ashgoodman** [comment]
another example

In the activity stream it says:
John Doe has commented on Some card name                         30 minutes ago

Comment content goes here

but in the email it says
Today at 4:10 PM
has commented on 

So the email is missing context (what card), who, and what was said

**Comment by putt1ck** [comment]
Deck 0.61 on NC15
Received email of form

{user} has updated the description of the card CardName in stack StackName on board BoardName.

where the activity stream for the card (and general) has

UserName has updated the description of the card CardName in stack StackName on board BoardName

Looking at an older email with more activity to report, the failure to include the username is inconsistent (same user/board/stack and even card) and is sometimes included and sometimes not.

NB this is the only activity I'm currently opting for emails on (any NC instance) so cannot tell if it's Deck specific or not. Same bug?

**Comment by Nils160988** [comment]
Can confirm this behavior, is deck specific (other notifications are ok).

**Comment by rubo77** [comment]
I also got this message today (exactly lilke this, with curly brackets):

```
> Es gab Aktivitäten bei myExample cloud
> Heute um 09:13
> Rich subject or a parameter for "{user} has updated the description of
> the card {card} in list {stack} on board {board}" is malformed
>

**Comment by rubo77** [comment]
see https://github.com/nextcloud/deck/issues/1254#issuecomment-594555122

> This is definitely a activity issue !
> See :
> https://github.com/nextcloud/activity/blob/2c6ec88c465ff79342b6c5ffbce03625f10f08e4/lib/Data.php#L124
> 
> There is no check when doing the insert into activity_mq

can we close this as duplicate?
