### ISSUE TITLE
Don't open detail sidebar when editing card title

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#725]
### Usability proposal:
When you click on the upper part of a card only to edit the description, the details sidebar is opened.
If you just want to quickly edit some card descriptions this seems unnecessary and takes some time on slow systems.

### How to change this behaviour:
Only open details if the lower (grey) part of the card is clicked on.

**Comment by juliushaertl** [comment]
Yes, that sounds like a good idea. Clicking the text should not result in opening the details.

**Comment by bpcurse** [comment]
@juliushaertl I could try to look into this, success not guaranteed :wink:
Could you point me to the deck files I should have a look at?
