### ISSUE TITLE
Show comments on a separate tab

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#728]
**Is your feature request related to a problem? Please describe.**
In deck app comments are integrated into the timeline. In files app comments are on a separate tab.
Is there a special reason why comments are implemented in another way in deck? My personal favourite is the files app's way of showing comments. What do you think?

**Describe the solution you'd like**
To have this streamlined throughout nextcloud, comments should be on a separate tab just like in files app. It might also be more intuitive for first time deck users.

**Describe alternatives you've considered**
Integrate comments in the description tab.

**Comment by juliushaertl** [comment]
Combining all time based entries into one tab is actually a bigger design goal we have set for quite a long time around Nextcloud: https://github.com/nextcloud/server/issues/658 

@bpcurse In case there are concrete issues with the unified tab, we should discuss those at the server issue.

**Comment by bpcurse** [comment]
@juliushaertl Thank you for linking the server issue. I wasn't aware of this. Will talk to our user community here and afterwards join the server discussion with that input. First user reactions towards mixing comments and other activity in one tab have been negative.
