### ISSUE TITLE
Indicate on a card that comments were made

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#730]
**Is your feature request related to a problem? Please describe.**
At the moment you cannot see if anyone commented on a card if you do not open the details and click on the corresponding tab.

**Describe the solution you'd like**
Alike the paper symbol that is displayed on the card if a description exists, a ballon / speech bubble symbol should be displayed next to the paper symbol if a comment was made.

**Describe alternatives you've considered**
A more sophisticated approach could show the number of comments inside or next to the balloon.

**Comment by juliushaertl** [comment]
We actually have the same behavior here as the files app. If you were mentioned in a comment we show the speech bubble on the card. cc @nextcloud/designers Maybe we should show it in general if there were new comments and highlight it a bit more if the user has been mentioned?

**Comment by bpcurse** [comment]
I really like the idea of showing it in general when comments exist and highlighting it in some way if the user has been mentioned. As people use nextcloud/deck differently especially in regard to notification settings, this could help keeping an overview without cluttering the interface too much. It is a logical addition to the paper symbol I would expect without reading a manual.

**Comment by skjnldsv** [comment]
@juliushaertl We could even add a counter?

**Comment by jancborchardt** [comment]
A comment icon is good, a counter is a bit information overload and takes more space. In the end it doesn’t really matter if there’s 4 or 5 comments. What’s important is:
- Were there comments at all?
- Did any of them mention you?

:)

**Comment by juliushaertl** [comment]
@jancborchardt That sounds like a good solution to me. :+1:

**Comment by jancborchardt** [comment]
@juliushaertl cool! I’ll make the icons then and add them to core.

**Comment by bpcurse** [comment]
@jancborchardt @juliushaertl I just made a quick and ugly mockup of the design:

The variations "comments were made" and "comment(s) unread" in grey fit in very nicely, but I'm not so sure of the blue one?

![deck_mock_up_card_comments2](https://user-images.githubusercontent.com/29312856/49453517-95f07200-f7e3-11e8-87fd-508c8012d0cf.png)

**Comment by natrius** [comment]
Any updates on this one?

@blue one: My suggestion would be just an '@' at the top. No blue colour. 

- Grey: Messages made
- Red dot: New messages
- @: Mentioned

**Comment by jakobroehrl** [comment]
In the latest version there is a icon for unread comments. 
If a user is mentioned in a comment there is a nextcloud notification.

![grafik](https://user-images.githubusercontent.com/24530680/81906543-b589ed80-95c6-11ea-9b20-a180b186801d.png)

**Comment by juliushaertl** [comment]
> @juliushaertl cool! I’ll make the icons then and add them to core.

@jancborchardt Did anything happen in that regards? :wink:

**Comment by pascalfranke** [comment]
+1

**Comment by juliushaertl** [comment]
We show it always these days, will close
