### ISSUE TITLE
user permissions unclear

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#737]
**Describe the bug**
Clicks on actions of user with insufficient rights are confusing

**To Reproduce**
1. Archive a card
2. Share Board with user "U", without rights (no Share, no Edit, no Manage)
3. Open the board with user "U"
4. Click "show archived cards"
5. Click card's 3-dots-icon and click action "unarchive card"
6. the card disappears
7. reopen the board
8. the card is still archived
**Expected:**
1) the card should not disappear if the card is not unarchived
2) On card's 3-dots-icon.popup don't show "unarchive card" if it's not possible to unarchive the card cause of insufficient rights

Similar constellation
1. Create a card
2. Share Board with user "U", without rights (no Share, no Edit, no Manage)
3. Open the board with user "U"
4. Click card's 3-dots-icon and click action "delete card"
5. nothing happens and the popup is still shown
**Expected:**
On card's 3-dots-icon.popup don't show "delete card" if it's not possible to delete

Similar constellation (in card view)
1. Delete a card
2. Share Board with user "U", without rights (no Share, no Edit, no Manage)
3. Open the board with user "U"
4. Click card's timeline and try to undelete card
5. The card is not undeleted
**Expected:**
On timeline don't show "undelete card" if it's not possible to undelete

**Version**
NC: 15.0.0 beta 2
deck: source 23.11.2018

**Comment by juliushaertl** [comment]
Fixed on master during the vue rewrite.
