### ISSUE TITLE
uuid shown as username

### ISSUE THREAD

**Issue by himbeere** [nextcloud/deck#74]
Hello Devs.

I have a litte problem. When i try to share a deck with colleagues only the uuid are shown (see screenshot)
![bildschirmfoto 2017-03-22 um 10 43 37](https://cloud.githubusercontent.com/assets/631865/24191556/73441ce8-0eec-11e7-839e-c61fae3d2a49.png)

I have a setup running where users are authenticated via LDAP. When sharing files there is not such a problem. Any hints how to solve this?

My System:
Nextcloud 11.0.2
Deck current

thanks and cheers

**Comment by himbeere** [comment]
I guess it was a ldap setting. After starting over everything is fine now. Sorry for the noise.

**Comment by juliushaertl** [comment]
Also a duplicate of #43, this will be fixed soon.
