### ISSUE TITLE
New version add false db prefix

### ISSUE THREAD

**Issue by quenenni** [nextcloud/deck#749]
**Describe the bug**
I installed a new instance of NC14.04 with the last version of deck (0.5.0).
When going on the deck page, I have an "Internal Server Error".

In the logs, there is this error:
```
"Exception":"Doctrine\\DBAL\\Exception\\TableNotFoundException","Message":"An exception occurred while executing 'SELECT s.board_id as id, c.stack_id as stack_id FROM oc_deck_stacks as s inner join oc_deck_cards as c ON c.stack_id = s.id WHERE c.id = ?' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nc_test2.oc_deck_stacks' doesn't exist","Code
```

In config.php, I have: 'dbtableprefix' => '',

And in the Db, I have 8 tables starting with deck_ and the table deck_stacks exists.

Somewhere in your code, you add oc_ as a table prefix.

**Comment by quenenni** [comment]
I put back v0.4.1 and deck works again.

**Comment by bpcurse** [comment]
Probably related to this one, as I haven't found another file containing "oc_" after a quick search:
https://github.com/nextcloud/deck/issues/705#issuecomment-439551610

Try to edit the file [yournextclouddirectory]/apps/deck/lib/Db/ChangeHelper.php (line 68) as shown in the comment.

**Comment by quenenni** [comment]
@bpcurse Yes, it fixes the problem. Thanks a lot.

**Comment by juliushaertl** [comment]
Will be fixed in the next version.
