### ISSUE TITLE
integration : Deck-Task-Calendar-Mail 

### ISSUE THREAD

**Issue by jbonlinea** [nextcloud/deck#751]
Hi guys ! 

I saw plenty has been said and planned about integrating Deck with Task and Calendar, and mail to a lesser extend (`[here](https://github.com/nextcloud/deck/issues/15)`, [here](https://github.com/nextcloud/deck/issues/605) and [here](https://github.com/nextcloud/deck/issues/392)), but I'm not sure how far are we.
Also I say [this threat](https://github.com/nextcloud/deck/issues/414) about sorting cards and totally support the idea.

All togather, I have an dream wish !

**Is your feature request related to a problem? Please describe.**
Basically an integrated system with Mail/Kanban/Calendar which not rely on gmail or outlook and would be open source ! 

**Describe the solution you'd like**
Basically linking several board to several calendars and several cards to an email and several email to a card.

**Describe alternatives you've considered**
I recently tried various Mail/Kanban/Calendar app, such as e-flow, sortd and yanando.
Yanando appeared to me as the most flexible.
The way I set Yanado up is as such : 
I have three board.
One board is assigned to a calendar, and the two other to an other calendar.
If I add a due date to a card, it creates an event in a calendar. As cards are created within a board, the calendar used is defined accordingly.

When an email implies a task, I create a card linked to this email (the card title and descriptions are copied from the mail object and content, but the title might be enough to start as we can always retrieve the email).
When an email has been linked to a task it is automatically moved from the inbox and labeled with the name of the board the card has been created in.

As such I can keep my inbox clean of email that need work to do, without loosing them in the folder it will be archived when the whole process is fished.

Actually an email can be linked to more than one card which is usefull if the email content involves two due dates, for instance.

With my three boards, I do not distinguish "to-do", "reminders", and "cards" as slightly more sophisticated task within a production process.

One board is named To-Do : its column are "don't mess with me" "stop thinking" "wait for reply" "mehh" and "procrastination"
I create cards manually or for email. When an email involve something to do, in is linked to a cards in this board, and if I reply to this email but want to remember to follow up let's say in a week, I add/change the due date and move it to "wait for reply" 
This board uses a dedicated calendar.

One board is for broader project management, with more usual columns 
As I said some email may be linked to two cards, for instance one "quick to-do" card on the to-do board, and a card which involves more continuous work within a broader process. That's great.

What I can't do I link a card to two mails but this would be awesome. for instance I receive a first mail with some info about the wish of a colleague. I create a card accordingly in my project board.
Later an other colleague send me an email with his imput on the same subject, but this two email are not grouped as a conversation (there may be many human and technical reasons to that, you know it for sure). I can't link the card I created to this new email (and rearranging email header to group them is not a solution). 
Again later, I send a prototype and my colleague send me a feedback, by mail, again not in the same conversation, and I can't add it the the already existing card.

This, the ability to link boards to calendar (even a calendar per-board, we can always name and display/hide them to be workable), link mails to several cards, and cards to several email would be a killer functionality. 

No let's be crasy.
Imagine the board is shared by two user having their own email address. It would be awesome if both user can create card from linked to their own email, and have the option to "share" the email. As such, I could create a card linked to an email, and keep the email private, my colleague with who I share the board can only see the card itself but can't retreive the email linked to it, or I could create a card linked to an email and pin a checkbox to share the email, my colleague would be able to see the card, and retrieve the email linked to it !!! 
if for technical reason it would be too difficult to achieve that in a "proper" way, the ability of automatically coping the email content in the card description would cover that to e great extend, or better would be that deck create some sort of "copy" of the email is stores as a "joint file" to the card so that my colleague can get the content...

**Additional context**
Well being able to use open standards, not gmail and chrome (or chromium) is the idea

**Comment by laurentiu2** [comment]
I'd find useful to have the option 'Show in Calendar' under Due Date on Tasks, like in the image below.

**Comment by laurentiu2** [comment]
![screenshot 2019-01-04 at 13 07 52](https://user-images.githubusercontent.com/29857699/50685525-307de400-1022-11e9-991d-50193a1e16a4.png)

**Comment by laurentiu2** [comment]
The same with Deck. The entry in Calendar might be 'Deck/Board_name/Stack_name/Card_name'

![screenshot 2019-01-04 at 13 16 29](https://user-images.githubusercontent.com/29857699/50685757-26101a00-1023-11e9-8002-17d38f0c4962.png)

**Comment by nhoening** [comment]
@laurentiu2, maybe your suggestion can become its own issue. It's pretty well-defined, while this issue (#751) is rather broad.

**Comment by juliushaertl** [comment]
This is pretty similar to #15 and #810 so I'm closing this as a duplicate. 

@laurentiu2 Your mockup looks pretty nice, however we still would need to decide somehow in which calendar we show the card then. Would you mind to move that to #15 ?
