### ISSUE TITLE
Print Style Error

### ISSUE THREAD

**Issue by mat-man** [nextcloud/deck#752]
### Steps to reproduce
1. Create a Deck with 1 or more Stacks that will cover more than 1 Page when printed.
2. Click on Print and view the print-preview, only the first page will be displayed correctly.

### Expected behaviour
All items should be displayed on as many pages as necessary

### Actual behaviour
When printing Decks with multiple elements covering more than 1 Page in Firefox and/or Google Chrome only the first Page will be displayed.
With Firefox (63.0.3) the first page will appear normally, the following page page will be blank.
With Chrome (70.0.3538.110) the first page will appear normally, there's no following page.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/24832685/49254697-2b79b380-f42a-11e8-820d-b24cf42d5f61.png)

[testboard _ Deck - with Firefox.pdf](https://github.com/nextcloud/deck/files/2631040/testboard._.Deck.-.with.Firefox.pdf)
[testboard _ Deck - With Chrome.pdf](https://github.com/nextcloud/deck/files/2631041/testboard._.Deck.-.With.Chrome.pdf)

## Server configuration detail

**Operating system:** Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.37

**PHP version:** 

7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, json, exif, memcache, msgpack, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - admin_notifications: 1.0.2
 - announcementcenter: 3.3.1
 - apporder: 0.6.0
 - bookmarks: 0.14.2
 - bruteforcesettings: 1.2.0
 - calendar: 1.6.4
 - caniupdate: 0.2.0
 - circles: 0.15.2
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.7
 - dav: 1.6.0
 - deck: 0.5.0
 - event_update_notification: 0.3.0
 - external: 3.1.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_downloadactivity: 1.3.0
 - files_external: 1.5.0
 - files_linkeditor: 1.0.7
 - files_markdown: 2.0.5
 - files_pdfviewer: 1.3.2
 - files_rightclick: 0.8.4
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trackdownloads: 1.3.1
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - impersonate: 1.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mail: 0.11.0
 - metadata: 0.8.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - ocsms: 2.0.2
 - onlyoffice: 2.1.0
 - passman: 2.1.4
 - password_policy: 1.4.0
 - passwords: 2018.11.2
 - phonetrack: 0.3.9
 - polls: 0.8.3
 - provisioning_api: 1.4.0
 - quota_warning: 1.3.0
 - registration: 0.4.5
 - scanner: 0.0.2
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - sharerenamer: 2.3.0
 - smb_test: 0.2.1
 - socialsharing_email: 1.0.4
 - spreed: 4.0.1
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.8
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - user_pwauth: 2.5.2
 - user_usage_report: 1.1.1
 - w2g2: 2.2.3
 - weather: 1.5.4
 - workflowengine: 1.4.0
Disabled:
 - dashboard
 - defaultgroup
 - encryption
 - files_clipboard
 - files_inotify
 - spreedme
 - theming
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
       ***REMOVED SENSITIVE VALUE***
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": ***REMOVED SENSITIVE VALUE***,
    "dbtype": "mysql",
    "version": "14.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "appstoreenabled": true,
    "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
    "default_language": "en",
    "defaultapp": "dashboard,calendar,files",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpdebug": false,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "loglevel": 0,
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

**Operating system:** Windows 7 X64

**Comment by JochenHWezel** [comment]
Just for clarification: this feature is required for horizontal as well as vertical dimensions

**Comment by JochenHWezel** [comment]
Optional feature: the scaling for printing might be automatically-calculated or with a manual value

**Comment by kbeerepoot** [comment]
Is there ayone working on this issue ? Ik would be really great if it got solved...

**Comment by weeman1337** [comment]
I would like to work on this one. There should be an option to provide a print view in the details.

Possible print options are:
- Number of columns
- Include descriptions
- Include comments

Apart of that control like menu buttons should be hidden. Additionally instead of avatars the names should be shown.

Do you think the dedicated print option in the board details is the way to go @juliushaertl ?

**Comment by stefan-niedermann** [comment]
@weeman1337 awesome! :rocket: I think the first step should be to fix the actual issue - that cards which do not fit to the first page are cut. The sidebar could also be hidden and we should start with good defaults (Let's just print what currently is displayed, so no description).

We can then in a second step decide if and what options are necessary, but i recommend to keep the steps small to review and ship improvements quickly :slightly_smiling_face:
