### ISSUE TITLE
No Data with "If-Modified-Since" header

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/deck#772]
**Describe the bug**
Hi @juliushaertl! 
I am currently trying out the "If-Modified-Since" Header and encountered a strange behavior:
As soon as I set the header, no matter to what date, i stop getting the expected Results.

**To Reproduce**
This is my Request: 
![grafik](https://user-images.githubusercontent.com/6911132/49655167-36d86a80-fa3a-11e8-9259-90ba811743cb.png)

And this is the Result:
![grafik](https://user-images.githubusercontent.com/6911132/49655235-69826300-fa3a-11e8-85e4-d875fa531c15.png)

**Expected behavior**
Since the Date set is the "default" for the never-before-synced Deck-App, I would expect to get all the Data ever saved, but all i get is an empty array.
Just omitting the Header brings back all the results. 

Looking at the request, i saw the "+01:00" at the end of the date, but should this break the whole thing? Timezones should be respected at this point...

**Client details:**
 - OS: Linux Mint Debian Edition 3 (Cindy), via AVD, Android Studio, proxied by mitmproxy
 - Version 0.5.1 
 - Device: AVD (Nexus 5X, API-level 27)

Am i missing something?

**Comment by juliushaertl** [comment]
Can you check if the array has a result if you create a new board? It might be that the boards that have been created before the if-modified-since support was introduced lack of a proper timestamp (which I would of course need to fix).

**Comment by juliushaertl** [comment]
I'll need to investigate this a bit. By all the data you mean all boards, not only the changed ones?

**Comment by desperateCoder** [comment]
Yes. I would expect to get an empty result.

I am currently trying out only boards. Since i have a huge but unstable changeset here, i wouldn't like to push it.

**Comment by juliushaertl** [comment]
@desperateCoder I pushed a fix to #774, here is a test release of that pr: https://cloud.nextcloud.com/s/dSmqmFcXp79kWMR 

You probably need to adjust the date you send (as the ones from your requests seem to be invalid due to the timezone added https://tools.ietf.org/html/rfc7231#section-7.1.1.1)

**Comment by desperateCoder** [comment]
@juliushaertl thanks! i changed my call, no more '+01:00' is sent.
I don't have a nextcloud, i am testing on @stefan-niedermann 's. Maybe he could find some time to patch?

**Comment by juliushaertl** [comment]
@desperateCoder If you need, i can setup you an account on a test instance, with the latest changes. Just drop me an email for that.

**Comment by juliushaertl** [comment]
Should be fixed with #774
