### ISSUE TITLE
Top-Down stack view option

### ISSUE THREAD

**Issue by Progdrasil** [nextcloud/deck#79]
It should be possible to have a top down view of all the stacks instead of left to right. This would be helpful for visibility if stack order is not important.

**Comment by artemanufrij** [comment]
@Progdrasil we have implemented it here #159. Solves it your issue?

**Comment by juliushaertl** [comment]
Yes. Let's close, since this does only make sense on mobile where we have it now.

**Comment by Progdrasil** [comment]
What I had in mind was for the desktop, when the order is not important to the user and when the decks overflow from the screen, you would expect the decks to wrap to a new row so that they are all in view without needing to scroll horizontally. For example the PEI Deck and all subsequent decks would wrap to a second row under the row containing Quebec, Ontario and Nouveau Brunswick.
![deck](https://cloud.githubusercontent.com/assets/11562522/26608194/5598e7b6-4568-11e7-9b90-4bfbc0543b08.png)

**Comment by pixelipo** [comment]
No, not really, @Progdrasil - vertical scrolling is used for cards, so stacks must overflow horizontally.

If you have very few cards per stack, then it would make more sense to convert stacks to cards and use labels/tags to group related cards
