### ISSUE TITLE
Timeline icons should be grey / have an opacity

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/deck#790]
**Describe the bug**
activity icons on timeline are black instead of grey (black+opacity)

**To Reproduce**
1. Click on any card
2. open the timeline'
3. See error/screenshot

**Expected behavior**
Icons should be grey (they are in the main activity stream. Other than that "timeline" for consistency reasons should maybe be renamed to "activity" to be consistent with the files app.

**Screenshots**
<img width="243" alt="2018-12-11 00_10_53-test _ deck" src="https://user-images.githubusercontent.com/1315170/49767628-88525500-fcd9-11e8-8ffd-4090de9dd236.png">

**Client details:**
 - OS: Win10 enterprise
 - Browser Firefox
 - Version 63.0.3 64-bit
 - Device: desktop

**Nextcloud version:**
15.0.0 / deck 0.5.1

**Where did you install Nextcloud from:**
upgraded via web updater

@juliushaertl my guess is that the icons are simply missing the opacity part.

**Comment by jakobroehrl** [comment]
@juliushaertl The reason is here: https://github.com/nextcloud/deck/blob/master/css/style.scss#L991
Do you have an idea why this is so implemented?

**Comment by juliushaertl** [comment]
No, sorry can't remember, but should be an easy fix then :wink:

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/deck/pull/906
