### ISSUE TITLE
Activity log returns 404

### ISSUE THREAD

**Issue by wdfee** [nextcloud/deck#794]
Commenting on a card doesn't work. Script is blocked by Content Security Policy.

**To Reproduce**
1. Go to board
2. Click on card
3. Click on Timeline
4. Type Comment
5. Click on arrow
6. No comment (timeline stays empty). new comment field is cleared.

**Expected behavior**
Comment should be saved and show up in timeline.
(Commenting on files is working as expected.)

**Client details:**
 - OS: Mac OS X 10.13.6
 - Browser: Firefox 63.0.3, Opera 57.0.3098.102

Ubuntu 18.04.1 LTS
Apache
MySQL
PHP 7.2.13
Nextcloud: 14.0.4

**Signing status:**
```
No errors have been found.
```

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
(empty)

#### Browser log
[Firefox:]
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). deck:3:14011
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). deck:7:14244 

[Opera:]
vendor.js?v=37477d2b-15:7 
GET https://[mydomain]/ocs/v2.php/apps/activity/api/v2/activity/filter?format=json&object_type=deck_card&object_id=2&limit=50&since=-1&sort=asc 404

  | (anonymous) | @ | vendor.js?v=37477d2b-15:7
  | (anonymous) | @ | vendor.js?v=37477d2b-15:7
  | (anonymous) | @ | vendor.js?v=37477d2b-15:7
  | (anonymous) | @ | vendor.js?v=37477d2b-15:7
  | (anonymous) | @ | vendor.js?v=37477d2b-15:7
  | $digest | @ | vendor.js?v=37477d2b-15:7
  | $apply | @ | vendor.js?v=37477d2b-15:7
  | (anonymous) | @ | deck.js?v=37477d2b-15:624
  | $emit | @ | vendor.js?v=37477d2b-15:7
  | notify | @ | deck.js?v=37477d2b-15:3629
  | (anonymous) | @ | deck.js?v=37477d2b-15:3602
  | triggerEvents | @ | core.js?v=37477d2b-15:2984
  | triggerApi | @ | core.js?v=37477d2b-15:2969
  | eventsApi | @ | core.js?v=37477d2b-15:2768
  | Events.trigger | @ | core.js?v=37477d2b-15:2959
  | _onModelEvent | @ | core.js?v=37477d2b-15:3768
  | triggerEvents | @ | core.js?v=37477d2b-15:2985
  | triggerApi | @ | core.js?v=37477d2b-15:2970
  | eventsApi | @ | core.js?v=37477d2b-15:2768
  | Events.trigger | @ | core.js?v=37477d2b-15:2959
  | options.success | @ | core.js?v=37477d2b-15:3251
  | (anonymous) | @ | oc-backbone-webdav.js?v=37477d2b-15:244
  | Promise.then (async) |   |  
  | callMethod | @ | oc-backbone-webdav.js?v=37477d2b-15:227
  | davCall | @ | oc-backbone-webdav.js?v=37477d2b-15:280
  | davSync | @ | oc-backbone-webdav.js?v=37477d2b-15:354
  | save | @ | core.js?v=37477d2b-15:3260
  | create | @ | core.js?v=37477d2b-15:3662
  | postComment | @ | deck.js?v=37477d2b-15:773
  | fn | @ | VM687:4
  | e | @ | vendor.js?v=37477d2b-15:7
  | $eval | @ | vendor.js?v=37477d2b-15:7
  | $apply | @ | vendor.js?v=37477d2b-15:7
  | (anonymous) | @ | vendor.js?v=37477d2b-15:7
  | dispatch | @ | core.js?v=37477d2b-15:3
  | r.handle | @ | core.js?v=37477d2b-15:3
</details>

**Comment by XarisA** [comment]
Same here on 

- Arch Linux
- Nginx 1.14.2
- Mysql 10.1.37
- PHP 7.2.12
- Nextcloud 15.0.0
- Deck 0.5.1

accessed through Firefox 64.

**Comment by juliushaertl** [comment]
Can you try if disabling and enabling the deck app fixes the issue for you?

**Comment by wdfee** [comment]
yes I tried it. seems to work now!

**Comment by juliushaertl** [comment]
> GET https://[mydomain]/ocs/v2.php/apps/activity/api/v2/activity/filter?format=json&object_type=deck_card&object_id=2&limit=50&since=-1&sort=asc 404

@nickvergessen Do you have any idea why a newly added activity filter might only be available after disabling/enabling the app?

We had the same issue for comments which could also be fixed by reenabiling in https://github.com/nextcloud/deck/issues/704

**Comment by nickvergessen** [comment]
> Do you have any idea why a newly added activity filter might only be available after disabling/enabling the app?

Try increasing the version of your app, I guess some caching is going on, but in theory there is no reason for that and I never noticed this.

**Comment by juliushaertl** [comment]
The version is already bumped two times since the activities were introduced in 0.5.2 so it should not happen again. Let's close this since we are unable to reproduce and disabling/enabling fixes it.
