### ISSUE TITLE
missing translation for tooltips "Access for group" in board.sidebarView

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#795]
**Describe the bug**
missing translation for tooltips "Access for group" in board.sidebarView

**To Reproduce**
1. Chosse German as language
2. Open board details and select a group for sharing
3. In the selection.menu the tooltip ("Access for **group**") of the avatar of a group  is not fully translated
4. After shared with a group, the tooltip ("Access for **group**") of the avatar of a group  is not fully translated, too

**Expected behavior**
Both tooltips should be translated

**Screenshots**
Step 3:
![screenshot from 2018-12-15 12-01-19](https://user-images.githubusercontent.com/34692335/50042493-d2359500-0063-11e9-9f80-6e648c219337.png)

Step 4:
![screenshot from 2018-12-15 12-00-50](https://user-images.githubusercontent.com/34692335/50042492-d06bd180-0063-11e9-8eff-91498040dfa3.png)

**Version**
NC 15.0.0
deck 0.5.1

**Comment by jakobroehrl** [comment]
@juliushaertl: What do you think about removing the title attribute, is brings not much value: 
https://github.com/nextcloud/deck/blob/master/templates/part.board.sidebarView.php#L53

**Comment by cloud2018** [comment]
yes, remove the title would be fine. 
How about putting "(group)" after the name and using a different avatar. Same as in the Files app:

![dateien nextcloud 2](https://user-images.githubusercontent.com/34692335/51737953-3ea5aa00-208e-11e9-9fac-65df8acd3d34.png)

**Comment by juliushaertl** [comment]
Yes, we should remove the title and add the group hint to the main label.
