### ISSUE TITLE
Open/Assigned Tasks in all board [$100]

### ISSUE THREAD

**Issue by mixvoip** [nextcloud/deck#805]
Hi,

we are using several boards in Deck right now. To avoid manual copying and to avoid missed tasks, we want to request some sort of filter where all tasks for a specific user across all board can be found. For Follow-Up etc it should not be only "my tasks".
As we are requesting to have this for all boards in one view, we think it is not a duplicate.

Best regards
Clemens

**Comment by mixvoip** [comment]
Bounty of 75$ linked: https://www.bountysource.com/issues/67677436-open-assigned-tasks-in-all-board

**Comment by juliushaertl** [comment]
@mixvoip Thanks for your feature request and for adding a bounty on it. Can you describe a bit more in detail what you mean by this:

> For Follow-Up etc it should not be only "my tasks".

**Comment by mixvoip** [comment]
@juliushaertl I just wanted to make clear that we are not requesting a feature to see only all own tasks in all boards at one place. We need to be able to list all tasks across all boards for all existing users.
So to make it somehow visible:
Imagine you have 3 boards (X,Y,Z) with different tasks for 3 Users (A,B,C).
We want to have a view where we can see all tasks from A or from B or from C (via a filter or something like that). There should be no filitering like "A can see only tasks from A".

Is that now clearer?

**Comment by BKapelari** [comment]
I would really like to see something like the "today" and "this week" view in Wunderlist: [(LINK)](https://www.wunderlist.com/blog/wunderlist-for-osx-yosemite/01@2x.png)

So showing all the tasks asigned to me for today/this week: [LINK](https://www.google.com/search?client=firefox-b-d&biw=1405&bih=815&tbm=isch&sa=1&ei=WKl6XPiXDumZjLsPmum72Ag&q=wunderlist+week&oq=wunderlist+week&gs_l=img.3...362436.363136..363281...0.0..0.98.470.5......1....1..gws-wiz-img.......0j0i30j0i24.lgnGkBEYmKo#imgrc=PoMoUGA2WwMs5M:)

If I click on the task, there could be a link to the board who is containing it.
This would be a simple solution for not missing tasks. What do you think about it?

Hopefully I can help in develop this. I'm new in Nextcloud extension programming

**Comment by putt1ck** [comment]
> @juliushaertl I just wanted to make clear that we are not requesting a feature to see only all own tasks in all boards at one place. We need to be able to list all tasks across all boards for all existing users.
> So to make it somehow visible:
> Imagine you have 3 boards (X,Y,Z) with different tasks for 3 Users (A,B,C).
> We want to have a view where we can see all tasks from A or from B or from C (via a filter or something like that). There should be no filitering like "A can see only tasks from A".

To clarify:

You want to be able to see cards assigned to a user, across all boards;
but not have an option for a user to see only cards assigned to them?

I'd have thought the latter was the single most useful option.

**Comment by BKapelari** [comment]
Just as an idea:
Maybe the best option would be to have a search syntax and the option to safe the search as a smart list.
I really like the way how you can to it in Jira:
https://confluence.atlassian.com/jirasoftwarecloud/advanced-searching-764478330.html

**Comment by tomdereub** [comment]
Hi, I'm really interested by this feature too. For me the most would be to be able to filter the same way we can filter in one board, but in all boards, or even a selection of boards. We would have in the filter options : 
- boards
- lists (listing all lists existing in the different boards)
- tags (idem, all tags in all boards)
- users
- due date
It could be used with the same filter button that already exists, with the current board ticked by default.
One other thing that would make this easy to use : the lists of boards, lists, tags, users... could be big, so it must be scrollable and ideally with an easy search function (or just typing a letter to jump in the list).

Examples of use of such a functionality:
- filter all cards assigned to a user like wanted here
- filter all cards with due date this week in some boards and all users (for example, I have a few boards dedicated to projects and some to internal organization, and I want to see urgent cards only on project boards, and for any user and lists).

One more thing and I stop my letter to Santa Claus : possibility to save some filter selections. It would give some personalized "views", like in portable kanban for example. Below the board list, we could have a saved filter list.

I hope it's clear enough...

**Comment by juliushaertl** [comment]
Hey there,

I'd just like to let you know that due to the [ongoing issue with Bountysource](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943) we're discussing ways to move to a different platform. As it looks right now, Bountysource might claim some of the money that was contributed by the community. We will try our best to prevent that. Historically we – the Nextcloud GmbH employees – simply put the claimed bounties back to other tickets until one was solved by a community member. So the money was always *from the community* and *for the community*. We'll therefore move to a better platform and currently don't post any new bounties until this situation is resolved. The current goal is to move/donate the money to [Nextcloud include](https://nextcloud.com/include/) but details will follow in the [forum post](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).

Hope this makes sense. If you have any questions please ask them on the forum. This comment will be copy-pasted to all open issues with bounties.

**Comment by alexanderdd** [comment]
related https://github.com/nextcloud/deck/issues/398 maybe even duplicate? There is also https://github.com/nextcloud/deck/issues/12 --- they all go in the same direction kind of?

**Comment by varac** [comment]
Thanks a lot like this useful feature. I noticed that only cards with a date from my *personal* deck show up in the `upcoming cards` overview, which are not shared. Cards from shared decks won't show up.

**Comment by jakobroehrl** [comment]
@varac 
Thanks, please could you create a new Issue with this?

**Comment by juliushaertl** [comment]
Cards from shared boards will only show up if you are assigned to them.
