### ISSUE TITLE
Android flow

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#806]
At all @nextcloud/designers 

i would like to request some input from you for the general flow of the android app.

# The current state:

## Overview with stacks

sidebar contains boards

![overview](https://raw.githubusercontent.com/stefan-niedermann/nextcloud-deck/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png)

## Planned detail view

![detail](https://user-images.githubusercontent.com/4741199/49882781-9b783880-fe31-11e8-8b5d-5630dc5f385d.png)

# Questions

- What do you think about the general flow?
- Which meta data (labels, overdue, ...) should be shown in the overview and which only in the detail view (to avoid duplicate data and crowded views)

PS.: This issue was opened in this repository to be able to mention y'all.

cc @jancborchardt @desperateCoder @AndyScherzinger @juliushaertl

**Comment by jancborchardt** [comment]
Nice! :)

- In the overview, currently a lot of space is used
   - Do we need to show the description there? Title should be enough
   - Due date and labels could go on one line, with the date always on the left
- The tab title "WIP" is just from your board, right? Cause people won’t understand that, "Doing" or "In progress" should be the default
- Is it possible that when the tabs don’t take up the full width, to make them fill the space? That would look much nicer.
- The detail view seems nice and simple for now- That’s good.
   - For a new card, the title field should automatically be focused and the keyboard open
   - The title shouldn’t say "Nextcloud Deck" but "New card" or "Card in `board name`"?
   - How do you save?
- I’m guessing the header of the board view and of the detail view will reflect the color you chose for the board so you know where you are at?

**Comment by AndyScherzinger** [comment]
> - In the overview, currently a lot of space is used
>   - Do we need to show the description there? Title should be enough

That is up for discussion I guess, Technically speaking there is no "need"

>   - Due date and labels could go on one line, with the date always on the left

Tricky since the screenshots shows just examples with a little amount of labels, if you add several they will also need need several lines and the labels part is technically a view container

> - The tab title "WIP" is just from your board, right? Cause people won’t understand that, "Doing" or "In progress" should be the default

All the tabs titles are the original stack titles from the server

> - Is it possible that when the tabs don’t take up the full width, to make them fill the space? That would look much nicer.

Should be possible, yes

> - The detail view seems nice and simple for now- That’s good.

The view already evolved, see https://github.com/stefan-niedermann/nextcloud-deck/pull/25

>   - For a new card, the title field should automatically be focused and the keyboard open
>   - The title shouldn’t say "Nextcloud Deck" but "New card" or "Card in `board name`"?
>   - How do you save?

Atm we don't have creation of cards implemented, so yes the title could then be as stated by you

>- I’m guessing the header of the board view and of the detail view will reflect the color you chose for the board so you know where you are at?

Atm we don't respecet the colors set for the boards, so all blue. This should be possible to implpement though

**Comment by juliushaertl** [comment]
> That is up for discussion I guess, Technically speaking there is no "need"

As stated in https://github.com/stefan-niedermann/nextcloud-deck/issues/28 the description can be quite big and contains markdown so I would actually like to keep it out of the board overview.

>> Due date and labels could go on one line, with the date always on the left

> Tricky since the screenshots shows just examples with a little amount of labels, if you add several they will also need need several lines and the labels part is technically a view container

I think thats fine the way it is currently. It is the same way we have it in the web UI and there might be more indicators besides the due date, like attachments, comments and assigned users.

**Comment by pixelipo** [comment]
good work, @stefan-niedermann !

I have one comment - there is no place for stack-related tasks - stuff like "Rename current stack", "New stack" and "Delete Stack". Should there be yet another 3-dot meu in the stack-titles row?

what do you think, @nextcloud/deck ?

**Comment by juliushaertl** [comment]
I think we discussed that those should be placed in the main action menu in the top right iirc.

@stefan-niedermann I'd say we can close this and continue discussion in separate tickets at the Android repo.

**Comment by stefan-niedermann** [comment]
yes, thanks :)

@pixelipo like julius said, it has already been implemented (though yet without functionality) in a global 3-dot-menu in the top right corner of the app :)
