### ISSUE TITLE
Share Markdown code with Notes-App

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#81]
Is it possible to share the Markdown code with the Note-App?
The main feature i am missing is the live-edit mode (one edits and the text is directly formatted while typing).

**Comment by juliushaertl** [comment]
Live-editing would be nice to have, but using the current notes implementation doesn't make much sense since it is about to be replaced, see https://github.com/nextcloud/notes/pull/22

**Comment by juliushaertl** [comment]
Simplemde looks great in general, but if we switch to a different markdown editor it should support checkboxes which would be nice to have for #212 

Issue at simplemde: https://github.com/sparksuite/simplemde-markdown-editor/issues/635

**Comment by sunjam** [comment]
[Posting SimpleMDE status here for reference](https://github.com/nextcloud/notes/issues/204). Seems alternatives are being considered.

**Comment by juliushaertl** [comment]
I'll keep track of what is happening over at the notes app. Since SimpleMDE is not maintained anymore, i'll close this one. Once there is a good alternative for the notes app, we'll reevaluate switching the markdown renderer.
