### ISSUE TITLE
Changing deck title doesn't get into timeline

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#827]
**Describe the bug**
Changing deck title doesn't get into timeline

**To Reproduce**
1. Go to a deck and change his title

**Expected behavior**
Title change gets an entry in timeline

- Deck 0.5.2
- Nextcloud 14.0.3

**Comment by juliushaertl** [comment]
Works as expected for me: 
![image](https://user-images.githubusercontent.com/3404133/50523314-b3a5b400-0acf-11e9-864a-888a03699712.png)

Do the other activity entries work as expected?

**Comment by Dubidubiduu** [comment]
Depends, changes on description doesn't get an info in timeline, but tagging and changing the due date gets an info.

**Comment by juliushaertl** [comment]
Description changes will get added after some delay though the cron job or after someone else edits it, since we merge individual saves to bigger chunks.

**Comment by Dubidubiduu** [comment]
Ahh, right, there it is. Thanks!
