### ISSUE TITLE
Comments in Timeline > won't "Save"

### ISSUE THREAD

**Issue by Karamelmar** [nextcloud/deck#828]
After clicking on a card, and selecting the Timeline Tab, i start writing a new comment.
As soon as as i click the arrow to post/save the comment, what i wrote vanishes but does not show as a comment.

What i already tried to solve the problem:
- disabled enabled the app
- removed the app and installed it again
- removed the app and installed/build form git repo
- removed the app, deleted the database tables, reinstalled the app (from git and nextcloud apps)
- let occ repair the database
- checked the file permissions of the app
- tried different browsers (firefox, chrome, vivaldi)

My system:
- Centos 7.6
- Nextcloud 15
- Apache 2.4.37
- PHP 7.3

Checked in the system logs and also in the nextcloud log (in debug mode), but i can not get any output in the log regarding this error :(

**Comment by Karamelmar** [comment]
Update:
I found the cause for this error:
I do use U2F Authentication to login. Users on this instance who do not use U2F can post comments, users who use U2F can not.

The following log entry in the apache access log lead me to this conclusion:
[27/Dec/2018:11:45:20 +0100] "PROPFIND /nextcloud/remote.php/dav/comments/deckCard/8/39 HTTP/1.1" 207 691 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.85 Safari/537.36 Vivaldi/2.3.1401.7"

To access my U2F Account via webdav with an app, i would have to give this app an app token.
Is there a way/option to do this?

**Comment by juliushaertl** [comment]
Do you have the activity app enabled on your instance? Is the regular activity log working as expected?

**Comment by Karamelmar** [comment]
yes, the activity app is active, but initial was not, when is started using deck.
The activity logs works as expected for all views but the deck view (and the all activities view), on the deck view it shows the loading circle, but won't finish to load. 
I did clear the activity database table of the nc instance, after that the deck view (and all activity view) in the activity app was working again (but empty).

I started testing and was surprised, that it worked to post a comment as U2F user, but not on all cards.
On cards with a description i can not post a comment. 
When a card has no description i can post a comment.
It is also possible to post a comment as soon as i delete the description.
When i paste the text of the description back in, it stops working.
To be sure i checked if the text is formatted in some form but it is not.

So actually my conclusion that it has something to do with U2F is most probably wrong, since i can recreate this behavior with a user that does not use U2F, sorry for that...

**Comment by JohnWalkerx** [comment]
I also tried to add comments to a card.
Comments are listed in the oc_comments database table.
But in the Browser you can't see any comment. Tested with Firefox 64.0 and Chrome 71.
It doesn't matter if a card has a description or not.
Not U2F activated. Activity app is enabled. Regular activity log working as expected.

**System:**
Ubuntu 16.04
Apache 2.4.37
PHP 7.2.14
Nextcloud 15.0.2

**Comment by Karamelmar** [comment]
Update:
When i try to move a Card with a description from one Group to another, it looks like it works (its in the group i moved it to) but after i reload the Deck, its in the old group. 
When i delete the description and then move it, it works.

**Comment by Karamelmar** [comment]
Solution:
I finally found out the cause for all the above problems of mine. When the moving of cards failed i got the following error:
`String data, right truncated: 1406 Data too long for column 'subjectparams' at row 1`
I took a look at the activity database table, it was set to varchart (1000).
I changed it to longtext and delete 1000.
Now i can move the Cards and write Comments.
Had some follow up issues:
Had to raise max_input_vars in phph.ini because phpMyAdmin warned me that there are longer values in the table.
Had to manually fix database entries in cards with umlauts (ü,ä,...) in the title of cards because they where not the right format. After that also these cards work again for commenting and moving.

After all it was a database problem not a deck problem.

The database is quiet old since i started with owncloud and moved on and on...
my understanding was, that when i do an occ upgrade and the tables are upgrade, wrong/old function types get updated aswell, but at least for me that was not true.

So thanks for your support!

**Comment by a1pilot** [comment]
Same issue here. Any news on a fix?

I write a comment in the timeline and it just vanishes.

**Comment by UserXH726** [comment]
The same problem with me

**Comment by 3Fish** [comment]
Hav the same issue with a hosted nextcloud version. 
Nextcloud: 16.0.1
Deck: 0.6.2
The whole timeline in Deck is not working. (not just the comments)

**Comment by juliushaertl** [comment]
Ok, I prepared a fix for the timeline not showing up at all in #1110. 

@Karamelmar After checking again, it seems you were correct with the changed data type. the subjectparams field needs to be longtext.

**Comment by a1pilot** [comment]
@juliushaertl Comments still not showing for me. Version 0.6.4

**Comment by juliushaertl** [comment]
Any change you can create me a test account on your instance so I can check what is going wrong there?

**Comment by a1pilot** [comment]
I have these two errors when clicking the comments tab:

`/ocs/v2.php/apps/activity/api/v2/activity/filter?format=json&object_type=deck_card&object_id=5&limit=50&since=0:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/ocs/v2.php/apps/activity/api/v2/activity/filter?format=json&object_type=deck_card&object_id=5&limit=50&since=-1&sort=asc:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by juliushaertl** [comment]
@a1pilot Could I also ask you to open a separate issue, with a filled issue template, so we have more details about the setup? Please also share your activity settings

**Comment by a1pilot** [comment]
New report opened #1112

**Comment by rprpx** [comment]
I am not able to make comments in the Timeline either.

NextCloud 16
Deck 0.6.6
Ubuntu 18.04
Apache 2.4.29
PHP 7.2.19

**Comment by juliushaertl** [comment]
Once we finished our vue js rewrite for 1.0.0, activity and comments will be separate so they will work independently from each other then.
