### ISSUE TITLE
Sync with Kanboard?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/deck#832]
Would be awesome if there was a way to sync Deck with an external Kanboard installation.
API reference here:
https://docs.kanboard.org/en/latest/api/

Would allow easy linking up to github etc for issue management.

**Comment by juliushaertl** [comment]
Syncing with a different kanban solution is out of scope for this project. Kanboard has a different approach in data handling and is far more complex so syncing to deck is nothing on our roadmap.

**Comment by MayeulC** [comment]
Would it be out-of-scope to support migrating form one to another, though?
I have been using kanboard for a while, and kept a look on deck for a better-integrated solution (also, I was never able to make kandroid work with my server).

**Comment by putt1ck** [comment]
@MayeulC we're about to start looking at importing Trello JSON, and if we get that working it would provide a template for the same sort of process with Kanboard, depending on what sort of export that can do.

**Comment by mxmilkiib** [comment]
An 'Import from Kanboard' would be welcome. I used [this](https://github.com/matueranet/kanboard-import-trello) to move from Trello originally.

**Comment by jonasof** [comment]
I created a script to import the main data from Kanboard (projects, columns and tasks) to Nextcloud Deck in the database level. It's very limited and assumes that the Kanboard instance is used by a single user, because it copies all the data to a specific user on Deck. https://github.com/jonasof/kb-to-nd.
