### ISSUE TITLE
When a card is being edited, all cards get a darker shadow.

### ISSUE THREAD

**Issue by RobertZenz** [nextcloud/deck#835]
When a card is being selected/edited, all cards receive a darker shadow. Is that by design?

**Comment by juliushaertl** [comment]
@RobertZenz Can you give some details about the browser you are using, only the currently selected card should get a darker shadow.

**Comment by juliushaertl** [comment]
This is how it looks for me:
![image](https://user-images.githubusercontent.com/3404133/51896329-7f623380-23ac-11e9-81f8-da424d557d15.png)

Yes, the `card-selected` is added to the board, but `.card.current` should overwrite the actually selected card with a more intense shadow: 

![image](https://user-images.githubusercontent.com/3404133/51896418-b6384980-23ac-11e9-955e-77facc1833c7.png)

**Comment by RobertZenz** [comment]
It does for the selected one, but every other card still changes.

![cards](https://user-images.githubusercontent.com/611377/51903079-bab82e80-23bb-11e9-8fe5-b0f0b46b923d.png)

The box-shadow of all cards in the board changes from

    rgb(219, 219, 219) 0px 0px 3px 1px

to

    rgb(219, 219, 219) 0px 0px 7px 0px

and as far as I can see that is because the rule `#board.card-selected .card` wins over `.card` because it is more specific.

If I'm not mistaken, it is [styles.scss:204](https://github.com/nextcloud/deck/blob/a7f8b66cceff1e6317e783c51e14235803e0383b/css/style.scss#L204) which is the problem, because it wins over [styles.scss:450](https://github.com/nextcloud/deck/blob/a7f8b66cceff1e6317e783c51e14235803e0383b/css/style.scss#L450).

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master.
