### ISSUE TITLE
support "Limit to groups"

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#845]
**Actual behavior**
Deck does not support "Limit to groups"

**Steps to reproduce the behavior**
   1. Go to apps
   2. Compare to "Calendar" app for exmaple

**New feature**
Deck app should support "Limit to groups" as Calendar, Gallery, ...

![apps nextcloud nc myispindel de](https://user-images.githubusercontent.com/34692335/51072908-6269f880-1669-11e9-8e6a-3450cc6ab65b.png)

![apps nextcloud nc myispindel de 2](https://user-images.githubusercontent.com/34692335/51072921-92190080-1669-11e9-96d6-37ee002c86af.png)

**Comment by juliushaertl** [comment]
Thanks for reporting. This actually got lost when implementing the activity integration. https://github.com/nextcloud/deck/pull/739 fixes that, but it was not merged until now, as it requires the latest patch release of Nextcloud to work.

**Comment by juliushaertl** [comment]
Done with #739
