### ISSUE TITLE
No Emails in Nextcloud 15

### ISSUE THREAD

**Issue by mikshepard** [nextcloud/deck#847]
**Describe the bug**
Upgraded Nextcloud from v14 to v15.0.2, emails from Deck to users stopped working.  They worked fine before the upgrade, and and the user activity settings still are checked for emails with Deck.

**To Reproduce**
1. Create a board and a card
2. Assign a user to card
3. Make changes to card
4. User does not receive any emails.

**Expected behavior**
Activity emails are sent to user. 

<details>
<summary>Server details</summary>

**Operating system**:
Debian 8.11
**Web server:**
Apache 2.4.10
**Database:**
mysql 5.7.24
**PHP version:**
7.1.25
**Nextcloud version:** (see Nextcloud admin page)
15.0.2
**Where did you install Nextcloud from:**
App Store

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - circles: 0.16.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - deck: 0.5.2
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.8.4.2
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0.1
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - music: 0.9.3.1
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - passwords: 2019.1.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.1.1
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0

</details>

#### Nextcloud log (data/nextcloud.log)
```
Argument 1 passed to OC\\Activity\\Event::setAuthor() must be of the type string, null given, called in \/var\/www\/nextcloud\/apps\/deck\/lib\/Activity\/DeckProvider.php on line 105


"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/deck\/lib\/Activity\/DeckProvider.php","line":105,"function":"setAuthor","class":"OC\\Activity\\Event","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/apps\/activity\/lib\/MailQueueHandler.php","line":465,"function":"parse","class":"OCA\\Deck\\Activity\\DeckProvider","type":"->","args":["en",{"__class__":"OC\\Activity\\Event"}]},{"file":"\/var\/www\/nextcloud\/apps\/activity\/lib\/MailQueueHandler.php","line":374,"function":"parseEvent","class":"OCA\\Activity\\MailQueueHandler","type":"->","args":["en",{"__class__":"OC\\Activity\\Event"}]},{"file":"\/var\/www\/nextcloud\/apps\/activity\/lib\/MailQueueHandler.php","line":183,"function":"sendEmailToUser","class":"OCA\\Activity\\MailQueueHandler","type":"->","args":["UserA","UserA@testemail.org","en","America\/Chicago",1547584200]},{"file":"\/var\/www\/nextcloud\/apps\/activity\/lib\/BackgroundJob\/EmailNotification.php","line":65,"function":"sendEmails","class":"OCA\\Activity\\MailQueueHandler","type":"->","args":[500,1547584200]},{"file":"\/var\/www\/nextcloud\/lib\/private\/BackgroundJob\/Job.php","line":61,"function":"run","class":"OCA\\Activity\\BackgroundJob\\EmailNotification","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/BackgroundJob\/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"\/var\/www\/nextcloud\/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"\/var\/www\/nextcloud\/lib\/private\/Activity\/Event.php","Line":164,"CustomMessage":"--"},"userAgent":"--","version":"15.0.2.0"}
```

**Comment by ymybe** [comment]
https://github.com/nextcloud/deck/issues/921 - is this related?

**Comment by juliushaertl** [comment]
Can you try to trigger a new email and send me the last entry from your activity mail queue from your database with

```
select * from oc_activity_mq WHERE object_type='deck_card';
```

**Comment by mikshepard** [comment]
I did this.  I took an existing card and assigned it to a user "amys".  That is what this entry seems to be describing.  Here is the output:

>|    6410 |    1554916230 |      1554916230 | deck                  | amys             | deck      | card_user_assign        | {"card":{"title":"Offsite-Router Rebuild","description":"- [ ] install SAS card\n- [ ] hook up storage rack\n- [ ] build zfs raid\n- [ ] mirror raid for OS on server\n- [ ] clone OS back\n- [ ] rsync over network\n- [ ] setup bandwidth throttling for backups","stackId":11,"type":"plain","lastModified":1536605439,"lastEditor":null,"createdAt":1534955257,"labels":[],"assignedUsers":null,"attachments":null,"attachmentCount":null,"owner":{"primaryKey":"mikshepard","uid":"mikshepard","displayname":"Shepard, Mike"},"order":9,"archived":false,"duedate":null,"deletedAt":0,"commentsUnread":0,"id":237,"overdue":0},"stack":{"title":"Ready to Begin","boardId":3,"deletedAt":0,"lastModified":1554916230,"order":1,"id":11},"board":{"title":"mikshepard's SysAdmin Work","owner":"mikshepard","color":"00c9c6","archived":false,"labels":[],"acl":[],"permissions":[],"users":[],"deletedAt":0,"lastModified":1554916230,"id":3},"author":"mikshepard","assigneduser":"amys"}  

 The entry after that appears to go to the other member the board is shared with.  This users, johnd, is not assigned to the card.  Here is that output:

> |    6417 |    1554916237 |      1554919837 | deck                  | johnd            | deck      | label_assign            | {"card":{"title":"Offsite-Router Rebuild","description":"- [ ] install SAS card\n- [ ] hook up storage rack\n- [ ] build zfs raid\n- [ ] mirror raid for OS on server\n- [ ] clone OS back\n- [ ] rsync over network\n- [ ] setup bandwidth throttling for backups","stackId":11,"type":"plain","lastModified":1536605439,"lastEditor":null,"createdAt":1534955257,"labels":[{"title":"Low Priority","color":"F1DB50","boardId":3,"cardId":237,"id":14}],"assignedUsers":null,"attachments":null,"attachmentCount":null,"owner":{"primaryKey":"mikshepard","uid":"mikshepard","displayname":"Shepard, Mike"},"order":9,"archived":false,"duedate":null,"deletedAt":0,"commentsUnread":0,"id":237,"overdue":0},"stack":{"title":"Ready to Begin","boardId":3,"deletedAt":0,"lastModified":1554916237,"order":1,"id":11},"board":{"title":"mikshepard's SysAdmin Work","owner":"mikshepard","color":"00c9c6","archived":false,"labels":[],"acl":[],"permissions":[],"users":[],"deletedAt":0,"lastModified":1554916237,"id":3},"author":"mikshepard","label":{"title":"Low Priority","color":"F1DB50","boardId":3,"cardId":null,"id":14}} | deck_card   |       237 |


Please let me know what further info I can provide.  Thanks,
-Mike
