### ISSUE TITLE
Provide undo-operation on delete

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/deck#85]
When one deletes a board or a card, there should be an undo operation available for 4 seconds, so if a user deletes something by accident, it can be easily restored with a single click.

**Comment by juliushaertl** [comment]
Makes sense. Also related to https://github.com/nextcloud/deck/issues/70

**Comment by juliushaertl** [comment]
Maybe as a quick fix we can just delay the deletion for 10 sec, to provide that kind of undo functionality. A good starter issue I think.

**Comment by juliushaertl** [comment]
Basic implementation is in #113 but we should just mark the board as deleted in the database and add a cleanup job to finally remove those boards after some time. Then the user doesn't have to wait the 10 sec. until the request for deleting is sent to the server.

**Comment by juliushaertl** [comment]
implemented with #133
