### ISSUE TITLE
Unable to add to timeline on cards and unable to view just Deck in Activity 

### ISSUE THREAD

**Issue by jshotton** [nextcloud/deck#863]
When I go to add a comment to the time line, the processing circle just spins,  I can type and add the comment and click the right arrow. the comment disappears.  the processing cirlcle keeps spinning.

If I click the activity log, I can see changes to DECK in the  all activities. and it includes the what I typed in the comment.  If I click on just the Deck listings.   the processing circle spins and nothing shows up.

**Operating system**:
Ubuntu 16.04.1 LTS

**Web server:**
Apache
**Database:**
mysql 5.7.25
**PHP version:**
7.032

**Nextcloud version:** (see Nextcloud admin page)
13.04
**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
``` no errors have been found

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Can you check the browser console if there are errors when loading the timeline view?


<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by jshotton** [comment]
timeline:

vendor.js?v=c7cab516-12:7 Error: [$rootScope:inprog] $digest already in progress
https://errors.angularjs.org/1.7.5/$rootScope/inprog?p0=%24digest
    at vendor.js?v=c7cab516-12:7
    at b (vendor.js?v=c7cab516-12:7)
    at i.$digest (vendor.js?v=c7cab516-12:7)
    at i.$apply (vendor.js?v=c7cab516-12:7)
    at deck.js?v=c7cab516-12:881
    at vendor.js?v=c7cab516-12:7
    at vendor.js?v=c7cab516-12:7
    at i.$digest (vendor.js?v=c7cab516-12:7)
    at i.$apply (vendor.js?v=c7cab516-12:7)
    at vendor.js?v=c7cab516-12:7 "Possibly unhandled rejection: {}"
(anonymous) @ vendor.js?v=c7cab516-12:7
vendor.js?v=c7cab516-12:7 Error: [$rootScope:inprog] $digest already in progress
https://errors.angularjs.org/1.7.5/$rootScope/inprog?p0=%24digest
    at vendor.js?v=c7cab516-12:7
    at b (vendor.js?v=c7cab516-12:7)
    at i.$apply (vendor.js?v=c7cab516-12:7)
    at deck.js?v=c7cab516-12:881
    at vendor.js?v=c7cab516-12:7
    at vendor.js?v=c7cab516-12:7
    at i.$digest (vendor.js?v=c7cab516-12:7)
    at i.$apply (vendor.js?v=c7cab516-12:7)
    at vendor.js?v=c7cab516-12:7
    at ni.completeTask (vendor.js?v=c7cab516-12:7)
(anonymous) @ vendor.js?v=c7cab516-12:7
vendor.js?v=c7cab516-12:7 Error: [$rootScope:inprog] $digest already in progress
https://errors.angularjs.org/1.7.5/$rootScope/inprog?p0=%24digest
    at vendor.js?v=c7cab516-12:7
    at b (vendor.js?v=c7cab516-12:7)
    at i.$digest (vendor.js?v=c7cab516-12:7)
    at i.$apply (vendor.js?v=c7cab516-12:7)
    at deck.js?v=c7cab516-12:881
    at vendor.js?v=c7cab516-12:7
    at vendor.js?v=c7cab516-12:7
    at i.$digest (vendor.js?v=c7cab516-12:7)
    at i.$apply (vendor.js?v=c7cab516-12:7)
    at vendor.js?v=c7cab516-12:7
(anonymous) @ vendor.js?v=c7cab516-12:7
vendor.js?v=c7cab516-12:7 Error: [$rootScope:inprog] $digest already in progress
https://errors.angularjs.org/1.7.5/$rootScope/inprog?p0=%24digest
    at vendor.js?v=c7cab516-12:7
    at b (vendor.js?v=c7cab516-12:7)
    at i.$digest (vendor.js?v=c7cab516-12:7)
    at i.$apply (vendor.js?v=c7cab516-12:7)
    at deck.js?v=c7cab516-12:881
    at vendor.js?v=c7cab516-12:7
    at vendor.js?v=c7cab516-12:7
    at i.$digest (vendor.js?v=c7cab516-12:7)
    at i.$apply (vendor.js?v=c7cab516-12:7)
    at vendor.js?v=c7cab516-12:7 "Possibly unhandled rejection: {}"
(anonymous) @ vendor.js?v=c7cab516-12:7
vendor.js?v=c7cab516-12:7 TypeError: Cannot read property 'data' of undefined
    at deck.js?v=c7cab516-12:3776
    at vendor.js?v=c7cab516-12:7
    at vendor.js?v=c7cab516-12:7
    at i.$digest (vendor.js?v=c7cab516-12:7)
    at i.$apply (vendor.js?v=c7cab516-12:7)
    at vendor.js?v=c7cab516-12:7
    at m (vendor.js?v=c7cab516-12:7)
    at XMLHttpRequest.p.onload (vendor.js?v=c7cab516-12:7) "Possibly unhandled rejection: {}"
(anonymous) @ vendor.js?v=c7cab516-12:7

**Comment by jshotton** [comment]
Activity with Deck selected

Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.success (script.js?v=c7cab516-12:97)
    at j (core.js?v=c7cab516-12:2)
    at Object.fireWith [as resolveWith] (core.js?v=c7cab516-12:2)
    at x (core.js?v=c7cab516-12:4)
    at XMLHttpRequest.<anonymous> (core.js?v=c7cab516-12:4)
success @ script.js?v=c7cab516-12:97
j @ core.js?v=c7cab516-12:2
fireWith @ core.js?v=c7cab516-12:2
x @ core.js?v=c7cab516-12:4
(anonymous) @ core.js?v=c7cab516-12:4
load (async)
send @ core.js?v=c7cab516-12:4
ajax @ core.js?v=c7cab516-12:4
loadMoreActivities @ script.js?v=c7cab516-12:82
prefill @ script.js?v=c7cab516-12:63
setFilter @ script.js?v=c7cab516-12:46
(anonymous) @ script.js?v=c7cab516-12:303
dispatch @ core.js?v=c7cab516-12:3
r.handle @ core.js?v=c7cab516-12:3

**Comment by brtptrs** [comment]
timeline problems on NC14 with Deck 0.5.2 Deck activities show up in the global activities list but not whe viewing the timeline from within the deck app.
