### ISSUE TITLE
Board jumps up and down when the Title is edited

### ISSUE THREAD

**Issue by der-Daniel** [nextcloud/deck#864]
**Describe the bug**
This is and UI issue. The board jumps up and down when the title is edited. This is very distracting as you are currently typing a new name.

**To Reproduce**
1. Create a new board
2. Edit the name of the board.
3. It will jump up and down depending on the alphabetical ordering.

**Expected behavior**
Keep the text field of the board on the same spot, until the edit is over. Then sort it.

**Client details:**
 - OS: Windows
 - Browser: Chrome
 - Version: 0.5.2
 - Device: desktop

**Comment by juliushaertl** [comment]
@jakobroehrl Not yet fixed.

![Peek 2020-01-25 11-03](https://user-images.githubusercontent.com/3404133/73119456-6b6ef480-3f62-11ea-9836-0d8a36c3fdac.gif)
