### ISSUE TITLE
Keep the text field accessible when creating a new Card

### ISSUE THREAD

**Issue by der-Daniel** [nextcloud/deck#866]
**Describe the bug**
This is and UI issue. When I create a new card I click on the plus sign. Then I can enter a title for the card. When I lose focus of this Element, the UI is showing me the plus sign again. It seems like this also happens when the focus of the browser is lost like using `ALT+Tab` to change to a different program.
This is very annoying for workflows like copying text from a document into cards. Everytime I switch to the document and then back to the deck app, the text field is basically gone.

**To Reproduce**
1. Click the plus sign to create a new card.
2. Enter a title, do not hit `Enter` yet
3. Change the focus, like clicking next to the text field or use `ALT+Tab`
4. The text field is reverted to the plus sign

**Expected behavior**
Once I have clicked on the plus sign, keep the text field visible. This way I can easily access it for a workflow as described above.

**Screenshots**
Not possible. As soon as focus is lost, the text field is gone.

**Client details:**
 - OS: Windows
 - Browser: Chrome
 - Version: 0.5.2
 - Device: desktop

**Comment by juliushaertl** [comment]
That is indeed an issue with the way we show inline input fields right now.

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master.
