### ISSUE TITLE
Responsive label name field

### ISSUE THREAD

**Issue by der-Daniel** [nextcloud/deck#867]
**Describe the bug**
This us an UI issue. I have my browser snapped to the left. When I tried to create a new label, the text field for the name was very small. For this reason I did not notice it.

**To Reproduce**
1. Go to deck setting
2. Go to tagsetting
3. Click create new tag
4. Make the browser window smaller by e.g. snap it to the left.

**Expected behavior**
There should be a line break between the text field and the colors, when the window in too small.

**Screenshots**
Red marks the space for entering the label.
![image](https://user-images.githubusercontent.com/7686866/51895581-c9e2b080-23aa-11e9-87c8-5529e68f32d8.png)

**Client details:**
 - OS: Windows
 - Browser: Chrome
 - Version: 0.5.2
 - Device: desktop

**Comment by juliushaertl** [comment]
Fixed on master
