### ISSUE TITLE
Permissions: User should be able to work with cards, but not to delete it

### ISSUE THREAD

**Issue by drmnk** [nextcloud/deck#872]
If you share deck with the user and give him permissions to edit it, he is able to edit cards, move them, attach tags and **delete it.**

But if I am boss and I want to give my colleague task and **control it afterwards**, I need to see every task that I gave him. What if I forget about task and he just delete it?

I think when we create deck we shoud have checkbox like "Other users can delete cards", disabled by default.

**Comment by juliushaertl** [comment]
Having a separate setting sounds a bit overkil. I think we could achieve the same with just limiting card deletion to users who have a manage permission.

**Comment by juliushaertl** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now.
