### ISSUE TITLE
Deleting a comment triggers different issues

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#875]
**Describe the bug**
After a comment is deleted and deck is reloaded, the spinner in the timeline of the affected card spins forever and new comments cannot be created in any existing card (in newly created cards after this it works again).
In addition comments on cards in the next stack to the right of the affected stack do not show, only the timeline entry that they were created is visible.

**To Reproduce**
1. create 4 stacks (a,b,c,d) in a test board
2. create a card in each stack (a1,b1,c1,d1)
3. comment on every card (a1c,b1c,c1c,d1c)
4. delete comment b1c
5. reload deck (click on files app and change back to deck)
6. check timeline of b1 -> spinner does not disappear
7. check timeline of c1 -> comment has gone, only the info that is has been created is visible.
8. create another comment in a1 (a1c2) -> it won't show
9. check timeline of d1 -> existing comment d1c seems ok, but timeline tells you that you have created a1c2 on d1 !?

**Expected behavior**
Spinner should disappear immediately on timeline of b1, other comments should not disappear and be created at the correct location.

**Client details:**
 - OS: Manjaro Linux
 - Browser Firefox
 - Version 65.0
 - Device: Desktop

Nextcloud 14.0.6 and 15.0.2, Deck 0.5.2

**Comment by juliushaertl** [comment]
Frontend comment handling has gotten full rewrite in the next release and should now properly handle the comments on different cards.
