### ISSUE TITLE
Nextcloud Deck - embed images in description

### ISSUE THREAD

**Issue by pcephaspjm** [nextcloud/deck#877]
In the last update for Deck it mentioned that you could embed images in the description on the back of cards.  I have looked online for instructions and tried different things myself but I can't work out how to actually do this.  My hosting service said they think the feature may have been removed.

**Describe the solution you'd like**
It would be very helpful if we could embed images onto cards

**Describe alternatives you've considered**
Not sure what other alternatives there would be

**Comment by juliushaertl** [comment]
You need to add the image as an attachment to the card inside deck. After that you can insert the images when editing the description with the following button:

![image](https://user-images.githubusercontent.com/3404133/52574978-b78e5b00-2e1d-11e9-914e-d0523904402d.png)

**Comment by pcephaspjm** [comment]
Thanks very much - I see now how to do it - it wasn’t immediately obvious - you need to click into the description to start editing before the button appears.

Peter

**Comment by juliushaertl** [comment]
> Thanks very much - I see now how to do it - it wasn’t immediately obvious - you need to click into the description to start editing before the button appears.

Yes, we probably should improve on the visbility of that option.

**Comment by Kru-x** [comment]
Took me a while to find that one as well. Would be great if you could have a small thumbnail beside the title.

**Comment by ceemarcus** [comment]
> You need to add the image as an attachment to the card inside deck. After that you can insert the images when editing the description with the following button:
> 
> ![image](https://user-images.githubusercontent.com/3404133/52574978-b78e5b00-2e1d-11e9-914e-d0523904402d.png)

I can't seem to find this `Insert Attachment` icon anywhere in the card, was it removed from NC, I know I'm commenting 2 years after your post :)

**Comment by thefiredragon** [comment]
Same issue here, the little icon is not showed when editing the description, could this be fixed? best regards
Dan
