### ISSUE TITLE
Add the ability to make calculations with cards of a stack

### ISSUE THREAD

**Issue by SteOtt** [nextcloud/deck#897]
First of all thanks a lot for your fantastic work. We use it a lot.

**Is your feature request related to a problem? Please describe.**
In our company we use deck to keep track of open invoices. If you want to know how much money is open you have to note it on the cards and then go through each card and manually add up the amounts.

**Describe the solution you'd like**
I would like to have the possibility to add one or more key/value pairs to a card and then do some calculations with it on the header of the stack.
An example how this can look like is freeplane.
![image](https://user-images.githubusercontent.com/17461591/52868240-0f410500-3143-11e9-91d2-6a7467e7cb86.png)
But it has not to be as complex as freeplane I think the following calculations could be sufficient:
Cards:count (Count the cards on the stack), Key:sum (sum up the values of the key Key), Key:average (calculate the average), Key:min (caluclate the minimum value), key:max (calculate the maximum value).

**Describe alternatives you've considered**
I don't see any alternatives.

**Additional context**
This feature could be used for a vast area just think of project management and it would make deck quite unique.

**Comment by putt1ck** [comment]
I think this something that could be built using the API (and doesn't sound like a core feature?)

**Comment by SteOtt** [comment]
You're right such a feature isn't commonly considered to be a core feature of kanban software. Nevertheless I would find such a feature very useful and it would add some extra functionallity that is unique (as far as I know) in kanban software.

Also I'd like to have the function available in deck and not as an external app using the API. Besides I don't see how to realize this with the API.

**Comment by juliushaertl** [comment]
Thanks for your feature request. This sounds like a nice feature however it will be quite a complex one if done properly. I also agree with @putt1ck that this is more something that should be integrated with external solutions, and is rather out of scope of the direction we aim with deck currently. I'll close this as this is not on our roadmap for now.
