### ISSUE TITLE
Scrollbar is partly hidden

### ISSUE THREAD

**Issue by demonicpancake** [nextcloud/deck#90]
I tested on both chrome and firefox and I noticed that the scrollbar is being clipped and not entirely visible.

The right is about half visible and the bottom one only shows about 3 px.

**Comment by juliushaertl** [comment]
@demonicpancake Thanks for your report. I'm not entirely sure which scrollbar you mean, can you post a screenshot for clarification?

**Comment by demonicpancake** [comment]
Here it is. I'm using the latest firefox version, also chromium
![deepinscreenshot20170422093334](https://cloud.githubusercontent.com/assets/6271598/25304914/1a9cb62a-273f-11e7-84f3-2803c28a7fa3.png)
![deepinscreenshot20170422093316](https://cloud.githubusercontent.com/assets/6271598/25304915/1a9d5076-273f-11e7-9ef5-d46809b7a2c2.png)

**Comment by juliushaertl** [comment]
Lets move this to 0.2.0

**Comment by artemanufrij** [comment]
It's not a deck issue. 
solution:
/core/css/styles.scss
`height: 5px;`

**Comment by artemanufrij** [comment]
will be fixed in NC core:
https://github.com/nextcloud/server/pull/5307

**Comment by juliushaertl** [comment]
Ah so it is not hidden but just set to different size. Thanks @artemanufrij for investigating.
