### ISSUE TITLE
attachment in card description fails in Safari

### ISSUE THREAD

**Issue by FahrJo** [nextcloud/deck#907]
**Describe the bug**
Adding an attachment into the description leads to page freeze.

**To Reproduce**
adding an attachment to a card just works fine. 
but with selecting the folder icon for embedding an attachment the page freezes.
In Firefox its working besides that the orientation of pictures is not right.

**Client details:**
 - OS: macOS Mojave 10.14.3
 - Browser Safari
 - Version: 12.0.3
 - Device: desktop

**Operating system**:
Ubuntu 16.04.6 LTS

**PHP version:**
7.0.33-0ubuntu0.16.04.1.

**Nextcloud version:** (see Nextcloud admin page)
15.0.4

**Comment by Tealk** [comment]
I think i have the sampe problem in Firefox
![image](https://user-images.githubusercontent.com/12276250/56885038-bdcec380-6a6b-11e9-9d42-5f8ad9ecd73d.png)
