### ISSUE TITLE
Clear indicator if a card is readonly for a user

### ISSUE THREAD

**Issue by botic** [nextcloud/deck#908]
We have multiple boards for each workgroup. All company members can view every board, but only edit if they are member of a workgroup. Example: Mr. X is in the finance team, so he can edit all cards  in the finance board, but is readonly in the software development board.

It would be very helpful to indicate a user that he/she is only a reader of a board and its cards. At the moment the input fields for a card look the same in both situations and users try to edit cards they have no permissions for.

**Comment by juliushaertl** [comment]
> It would be very helpful to indicate a user that he/she is only a reader of a board and its cards. At the moment the input fields for a card look the same in both situations and users try to edit cards they have no permissions for.

Yes, we should improve on that. The forms should not be available anywhere if there is just read-only access.

**Comment by juliushaertl** [comment]
Fixed on master with the vue migration.
