### ISSUE TITLE
markdown-it-abbr plugin

### ISSUE THREAD

**Issue by Salokyn** [nextcloud/deck#909]
Hello,

It would be useful to me if the [markdown-it-abbr](https://github.com/markdown-it/markdown-it-abbr) plugin was added:

Is it possible ?

**Comment by juliushaertl** [comment]
Would be fine by me. Contributions are very welcome :wink:

**Comment by juliushaertl** [comment]
Let's not introduce new plugins for now since we're going to switch to the text editor at some point #1561 and if we add markdown-it plugings that are not covered by text we will have a feature regression
