### ISSUE TITLE
Deck lists all users and all groups to anybody

### ISSUE THREAD

**Issue by oparoz** [nextcloud/deck#92]
### Steps to reproduce

1. Create groups
2. Assign different users to different groups
3. Log in as a user who is only a member of one group

### Expected behaviour

User should only be able to share with members of his group

### Actual behaviour

User can see all groups and all users
This is a big privacy issue.

### Server configuration

**Nextcloud version:** 11.0.2

**Comment by juliushaertl** [comment]
@oparoz Thanks for reporting. I'll have a look. The best might be to just use the OCS api to fetch users and groups.

For reference:
/ocs/v1.php/apps/files_sharing/api/v1/sharees

**Comment by juliushaertl** [comment]
Fixed with #94
