### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by Sunsheep** [nextcloud/deck#928]
I would love to see a Gantt Style view of the Tasks.
In my opinion, this gives you the best overview of a long term project and will enhance Task management a lot.

I already found #134, but the Deck project was in an early phase of development back in 2017 and hasn't  implemented "due dates". Right now "start dates" are also not implemented - so this must be first done, to get gantt charts to work. 

I will extend this feature request in the next days how it might work out, but I want to get some resonance first.

**Comment by Mannshoch** [comment]
May also see https://github.com/nextcloud/deck/issues/15

**Comment by juliushaertl** [comment]
Closing as a dupliate of #134 

As stated there this is nothing that is currently on our roadmap: https://github.com/nextcloud/deck/issues/134#issuecomment-448910458
