### ISSUE TITLE
Enrich boards with existing labels

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/deck#954]
As a user of the API the deck Android app is synchronizing the data starting with the get boards call. While we added the stacks in the response of this call, the existing labels are still missing and I would have to request all boards separately to also get the labels, causing more traffic and slowing down the sync.

I'd suggest including a verbose flag or even an overriden endpoint retuning all the data in the boards, including labels and stacks. The stacks are called sperately anyways, so there would be the break for the verbose data. 

You could also remove the stack data for the non-verbose call and only include them in the verbose one.

Thanks in advance!

**Comment by juliushaertl** [comment]
Done with #960
