### ISSUE TITLE
New API endpoint: get all users

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/deck#957]
Currently i only know about the users, that are already assigned to a card or are a board owner. For now, an unassigned user can't be found by the deck app.

A new endpoint, able to deliver all known users of the deck app would be great! 

This isn't urgent at all, since we have way more to do now, so just consider implementing this, as soon as you want.

Thanks @juliushaertl ! :grin:

**Comment by juliushaertl** [comment]
Yes, we have that one as a private endpoint for the web UI, but somehow missed to implement it for the public one. I'll look into that.

**Comment by desperateCoder** [comment]
The users are board-independant, global for a specific account, right?

**Comment by juliushaertl** [comment]
No, the list of users depends on to whom a board is shared with. Note that the etag/if modified since header will also not be available there since it will just be a list of the users that are currently part of the board (or part of a group that was added to the board).

**Comment by desperateCoder** [comment]
But wait... Aren't you talking about the ACL list? Isn't that the same thing?

**Comment by juliushaertl** [comment]
Well, the acl list contains user and group elements, but groups can constist of any number of users that are not listed as part of the acl. So the search user for assigning just returns all of the users who have access to the board.

**Comment by desperateCoder** [comment]
Didn't even know there were groups... Nice to know! @stefan-niedermann can you create some test groups and make them accessible for my account? I think a group would currently kill the whole App.

Thanks @juliushaertl I'm looking forward to the new endpoint!

**Comment by juliushaertl** [comment]
Done with #960
