### ISSUE TITLE
Collections for cards

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#965]
Collections support should also be available for cards not only for boards.

**Comment by jakobroehrl** [comment]
@juliushaertl What's to do for this in the code?
Is adding this https://github.com/nextcloud/deck/blob/vue/src/components/board/SharingTabSidebard.vue#L37-L38 to the CardSidebar enough?

**Comment by juliushaertl** [comment]
@jakobroehrl for the frontend we also need a card selector, similar to https://github.com/nextcloud/deck/blob/vue/js/views/BoardSelector.vue and https://github.com/nextcloud/deck/blob/vue/js/init-collections.js (which we also currently don't have migrated to the new src/ directory of the vue branch i think)

In the backend we need a separate provider class for cards (see https://github.com/nextcloud/deck/blob/vue/lib/Collaboration/Resources/ResourceProvider.php) which then needs to be registered as well https://github.com/nextcloud/deck/commit/e2be00a18df44788f0382db7712b1e15e8abeb9b#diff-b8a11151e44bcffc222c5fddc9ab92c9R162

**Comment by juliushaertl** [comment]
Closing as this was implemented in the vue branch and is now merged to master
