### ISSUE TITLE
Cannot assign card to user from group

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#969]
**Describe the bug**
When a deck is shared with a group I cannot assign a card within it to a member of that group.

**To Reproduce**
Create a deck
Share with a group
Create a stack and a card
Try to assign the card to a member of the group (that is not also a member individually

**Expected behavior**
That any member of a group that a deck is shared with will be available individually to assign to cards

New uptodate install with Deck 0.5.2

**Comment by juliushaertl** [comment]
I cannot reproduce that. Any errors in the logs? Can you check the network console of your browser if the list of users is contained in the API request for the board. 

![image](https://user-images.githubusercontent.com/3404133/55781620-e84fe100-5aaa-11e9-92eb-f0039877c27e.png)

**Comment by putt1ck** [comment]
Ok, it works now. I'm guessing there's some sort of delay between the creation of the group or its assignation to the board and the list of members becoming available. In the scenario above it was "create board, create card, share board with group, attempt to assign group member to card" within a very short tirmeframe.
