### ISSUE TITLE
Printable/Exportable Deck report

### ISSUE THREAD

**Issue by pprossi** [nextcloud/deck#971]
Would'nt it be nice to get some Deck Card Status overview.

Something like Deck in List or Excel/CSV format to Print all Deck Cards in one Overview?

**Comment by putt1ck** [comment]
Sounds like something to look at building against the API

**Comment by juliushaertl** [comment]
I agree with @putt1ck this is something that sould be built separately as an external integration using the REST API. Nothing that will be included into deck itself.
