### ISSUE TITLE
Inline preview and popup of Attached Images.

### ISSUE THREAD

**Issue by pprossi** [nextcloud/deck#972]
It would be very nice to open the Images without downloading it.
My be some small preview of attached images in card detail and view with lightbox view of the image.

**Comment by sunjam** [comment]
I was just testing this functionality in Deck 0.60 and attempted to embed images in card descriptions by appending `/preview` to the url, [as this functionality is now supported in Nextcloud](https://github.com/nextcloud/server/pull/6599).

Quick thought:  Would be great to embed images using their Internal Link ID so they do not have to be shared first for those who already have r/w access.

Shared URL Example Embedded here is `https://cloud.example.com/s/Z6TxaNobcdnyEMG/preview:`
![Photo](https://cloud.disroot.org/s/Z6TxaNobcdnyEMG/preview)

**Comment by jakobroehrl** [comment]
Spreed is using the internal view for that: https://github.com/nextcloud/spreed/pull/2778

**Comment by juliushaertl** [comment]
Viewer currently only works with files that are located in the users files. This is kind of blocked by #992

**Comment by jakobroehrl** [comment]
> Viewer currently only works with files that are located in the users files. This is kind of blocked by #992

OK, but we will implement this: https://github.com/nextcloud/deck/issues/564

**Comment by juliushaertl** [comment]
Ah I linked the wrong issue :wink:

**Comment by stefan-niedermann** [comment]
> small preview of attached images in card detail and view with lightbox view of the image.

Available for attachments which have been uploaded with Deck `1.3.0` or higher. A migration step for earlier uploaded attachments [is supposed to follow](https://github.com/nextcloud/deck/issues/2698).

![grafik](https://user-images.githubusercontent.com/4741199/114273953-8cfbb500-9a1c-11eb-8236-6ba21a844aa7.png)
![Bildschirmfoto vom 2021-04-10 um 16 48 41](https://user-images.githubusercontent.com/4741199/114273964-9f75ee80-9a1c-11eb-81e5-0e2b1480975b.png)
