### ISSUE TITLE
Not loading comments to some decks (mouse cursor spinning forever)

### ISSUE THREAD

**Issue by catauadrian** [nextcloud/deck#979]
**Describe the bug**
Comments not loading on some decks, spinning indicator goes on forever

**To Reproduce**
1. Create a stack and a card
2. Create some comments in timeline
3. Click on other cards 
4. Some stacks will not load comments

**Expected behavior**
Expected to load all comments 

**Screenshots**

**Client details:**
 - OS: Windows 10
 - Browser [firefox, chrommium]

Server: Ubuntu 18.04
Lastest Mysql-server
Latest php7/apache2 server
Nextcloud 15.0.6

Error log in Nextcloud: 

```
Undefined variable: comment at /var/www/html/nextcloud/apps/deck/lib/Activity/DeckProvider.php#291

Error: Call to a member function getMessage() on null at /var/www/html/nextcloud/apps/deck/lib/Activity/DeckProvider.php#291
```

In Javascript console:
```
vendor.js?v=f0542af1-12:7 TypeError: Cannot read property 'data' of undefined
    at deck.js?v=f0542af1-12:3776
    at vendor.js?v=f0542af1-12:7
    at vendor.js?v=f0542af1-12:7
    at i.$digest (vendor.js?v=f0542af1-12:7)
    at i.$apply (vendor.js?v=f0542af1-12:7)
    at vendor.js?v=f0542af1-12:7
    at m (vendor.js?v=f0542af1-12:7)
    at XMLHttpRequest.p.onload (vendor.js?v=f0542af1-12:7) "Possibly unhandled rejection: {}"

vendor.js?v=f0542af1-12:7 Error: [$rootScope:inprog] $digest already in progress
https://errors.angularjs.org/1.7.5/$rootScope/inprog?p0=%24digest
```

**Comment by catauadrian** [comment]
I replaced the problematic code and it works now. Thanks a lot!

**Comment by juliushaertl** [comment]
Thanks for reporting back. :+1:

**Comment by SnackyWell** [comment]
I have some same error Comments not loading on all my timelines have you andy idea to solve this ?

**Comment by juliushaertl** [comment]
@SnackyWell Please try with the latest release, as there have been some fixes regarding the timeline. Otherwise feel free to open a new issue with some more details :wink:
