### ISSUE TITLE
Attachments from within Nextcloud Filesystem

### ISSUE THREAD

**Issue by sunjam** [nextcloud/deck#992]
**Is your feature request related to a problem? Please describe.**

Thanks for all the great work on Deck!  I'd like to attach files and folders that exist within the Nextcloud filesystem.  [Attachments are currently supported by being uploaded externally from a browser](https://github.com/nextcloud/deck/issues/202).  See @pdschandler recent comment on that issue.

**Describe the solution you'd like**
-  Attach files or folders by selecting them within Nextcloud as a *Direct Link*.  This would avoid needing share permissions since access will only be granted to those who already have r/w access.
-  Or, use three dot menu on a specific file or folder to "Add to Deck".

**Describe alternatives you've considered**
Downloading and re-uploading files per card.

Thanks for reading!

**Comment by putt1ck** [comment]
Related to #564 #618 #982
